// İngilizce çeviri eki — Tasarım Adım 2, şerit "ana". Anahtar Türkçe metnin kendisidir
// (dil.js ile aynı kural). Şeritler paralel çalıştığı için her biri kendi dosyasına yazar;
// dil.js bu dosyaları SOZLUK.en'e katar (buradaki karşılık önce gelir).
export default {
  // Kabuk (Layout, CoinHapi)
  "{n} bekleyen istek": "{n} pending",
  "{n} coin — dükkâna git": "{n} coins — open the shop",
  // Ana sayfa
  "{n} soru": "{n} questions",
  "{ad} meydan okumanı kabul etti": "{ad} accepted your challenge",
  "20 soru · canlı rakip": "20 questions · live opponent",
  "Rakip bul": "Find an opponent",
  "Maçın yarım — sıra sende": "Unfinished match — your turn",
  "Davetin gönderildi": "Invite sent",
  "{n} kişi bekleniyor": "Waiting for {n} players",
  "Daveti görmedi — bekleniyor": "Hasn't seen the invite yet",
  "Diğer modlar": "More modes",
  "{n} soru seni bekliyor": "{n} questions to review",
  "Günlük görevler": "Daily quests",
  "+{n} al": "Claim +{n}",
  "Tüm görevleri gör": "See all quests",
  "Lig ve dükkân": "League and shop",
  "Haftalık lig": "Weekly league",
  "Skill ve coin": "Jokers and coins",
  "Skillerini tazele, coin kazan": "Restock jokers, earn coins",
  // Modlar, mod seçimi, rakip arama
  "Oyun modları": "Game modes",
  "Hızlı cevap ver, skillerini kullan ve rakibini geç.": "Answer fast, use your jokers and pull ahead.",
  "{n} skill": "{n} jokers",
  "Skillerini doğru anda kullan. Rakibinin planını boz ve taktik üstünlük kur.": "Time your jokers, wreck their plan and take the tactical edge.",
  "{n} skill · 3 can": "{n} jokers · 3 lives",
  "Skillsiz": "No jokers",
  "Her gün": "Every day",
  "3–5 arkadaş · ödülsüz. Aynı sorularda eğlencesine yarış.": "3–5 friends · just for fun. Same questions, pure bragging rights.",
  "Kur": "Set up",
  "Arkadaşların ve sen": "You and your friends",
  // Meydan okumalar
  "bekliyor": "waiting",
  "Sana gelen davetler": "Invites for you",
  "Çözülen sorular": "Questions solved",
  "Her zaman hazır rakipler": "Always-ready opponents",
  "Arkadaşlar sekmesinden davet linkini paylaş.": "Share your invite link from the Friends tab.",
  "Maçınız var": "Match on",
  "veren puan alır. Skill yok!": "scores. No jokers!",
  "Sıra sende": "Your turn",
  // Ana sayfa (seçenek A, 23 Eyl 2026) + turnuva şeridi
  "Klasik · 20 soru": "Classic · 20 questions",
  "DÜELLO": "DUEL",
  "Etkinlikler": "Events",
  "LV": "LV",
  "Rütbe": "Rank",
  "Meydan Okumalar": "Challenges",
  "Meydan okumalar": "Challenges",
  "{n} davet bekliyor": "{n} invites waiting",
  "{n} bekleyen davet": "{n} pending invites",
  "3–5 kişi": "3–5 players",
  "Skill yok": "No jokers",
  "Yanlışlarını çalış": "Study your mistakes",
  "{n} soru bekliyor": "{n} questions waiting",
  "{ad} ile maçın sürüyor": "Your match with {ad} is on",
  "Soru {n}/{t}": "Question {n}/{t}",
  "{ad} davetine cevap bekleniyor": "Waiting for {ad} to reply",
  "Ödüller: {liste} coin": "Prizes: {liste} coins",
  "Turnuva şu an canlı": "Tournament is live now",
  "Turnuvaya git": "Go to the tournament",
  "{saat} turnuvası · lobi açık": "{saat} tournament · lobby open",
  "Lobide {n} oyuncu": "{n} players in the lobby",
  "Sonraki turnuva {saat}": "Next tournament {saat}",
  "Katılıyor…": "Joining…",
  "Günde {n} turnuva": "{n} tournaments a day",
  "Türkiye saati": "Türkiye time",
  "Saatler cihazının saat dilimine göre": "Times shown in your device's time zone",
  "Katıl, son kalan kazansın": "Join — last one standing wins",
};
