// İngilizce çeviri eki — Düello v4 tek arena (Duello4Arena, 9 Eki 2026). Anahtar Türkçe metnin kendisidir.
// Başka sözlükte zaten olan anahtarlar (Sen, Rakip, Doğru, SON DÜELLO …) burada TEKRARLANMAZ — genel çeviri değişmesin.
// Sözlük: kontrol = control · seri = streak · saldırı = attack · tur = round · Son Düello = Last Duel · nötr = neutral.
export default {
  "Kontrolü al, üst üste 3 doğru yap, düelloyu kazan.": "Take control, get 3 correct in a row, win the duel.",
  "Nötr soru, tek bilen kontrolü alır": "Neutral question: the sole correct answer takes control",
  "İkinize aynı soru gelir. Yalnız biriniz bilirse kontrol onda olur.": "You both get the same question. If only one of you knows it, that player takes control.",
  "Kartlar: rakibe gönder, kendine seç": "Cards: send one, pick one",
  "Kontrol sende: 4 karttan birini rakibe gönderir, birini kendine seçersin. Her biriniz kendi kategorinizin sorusunu cevaplarsınız.": "With control, you send one of 4 cards to your opponent and pick another for yourself. Each of you answers your own category's question.",
  "Üst üste 3 doğru": "3 in a row",
  "Tur sınırına ya da art arda 5 nötr soruya gelinirse Son Düello başlar: aynı soru, joker yok, tek bilen kazanır.": "If the round limit or 5 neutral questions in a row is reached, the Last Duel starts: same question, no jokers, the sole correct answer wins.",
  "50:50, Ek Süre, İkinci Şans, Zaman Baskısı ve Soru Değiştir. Soru başına en çok 1 joker; Son Düello'da joker yok.": "50:50, Extra Time, Second Chance, Time Pressure and Swap Question. At most 1 joker per question; no jokers in the Last Duel.",
  "Tur {n}": "Round {n}",
  "NÖTR": "NEUTRAL",
  "BAŞLA": "GO",
  "Tek bilen KONTROLÜ alır · 3/3 seri kazanır": "Sole correct answer takes CONTROL · 3/3 streak wins",
  "Rakibe gönder": "Send to opponent",
  "Kendine seç": "Pick for me",
  "Rakibe gönderilecek kategoriyi seç": "Pick a category to send your opponent",
  "Kendi kategorini seç": "Pick your own category",
  "RAKİP SEÇİYOR": "OPPONENT IS PICKING",
  "KENDİNE ALDIN": "YOU TOOK",
  "SANA GÖNDERDİ": "SENT TO YOU",
  "RAKİBE GÖNDERDİN": "YOU SENT",
  "KENDİNE ALDI": "THEY TOOK",
  "Aynı soru · joker yok": "Same question · no jokers",
  "Süre doldu · otomatik seçiliyor": "Time's up · auto-picking",
  "Seçimin": "Your pick",
  "Rakipten": "From opponent",
  "Rakibin sorusu: {k}": "Opponent's question: {k}",
  "SON DÜELLO SENİN": "LAST DUEL IS YOURS",
  "SON DÜELLO RAKİBİN": "OPPONENT WINS LAST DUEL",
  "Tek doğru bilen sendin": "Only you got it right",
  "Tek doğru bilen rakipti": "Only your opponent got it right",
  "İKİNİZ DE BİLDİNİZ": "BOTH CORRECT",
  "İKİNİZ DE BİLEMEDİNİZ": "BOTH MISSED",
  "Yeni soru": "New question",
  "KONTROL RAKİPTE": "OPPONENT HAS CONTROL",
  "Kontrol kimsede değil": "No one has control",
  "RAKİP SALDIRDI": "OPPONENT LANDED",
  "KONTROL RAKİBE GEÇTİ": "CONTROL LOST",
  "SERİ DEĞİŞMEDİ": "STREAK UNCHANGED",
  "Seri {n}/{t}": "Streak {n}/{t}",
  "Rakip {n}/{t}": "Opponent {n}/{t}",
  "SON BASKI": "FINAL PUSH",
  "Bir saldırı daha, düello senin": "One more hit and the duel is yours",
  "Rakip bir saldırı uzakta": "Opponent is one hit away",
  "Sorular": "Questions",
  "Son Düello'yu sen bildin": "You won the Last Duel",
  "Son Düello'yu rakip bildi": "Your opponent won the Last Duel",
  "3/3 seri — düello senin": "3/3 streak — the duel is yours",
  "Rakip 3/3 seriye ulaştı": "Your opponent reached a 3/3 streak",
};
