// İngilizce çeviri eki — Düello v4 tek arena (Duello4Arena, 9 Eki 2026). Anahtar Türkçe metnin kendisidir.
// Başka sözlükte zaten olan anahtarlar (Sen, Rakip, Doğru, SON DÜELLO …) burada TEKRARLANMAZ — genel çeviri değişmesin.
// Sözlük: kontrol = control · seri = streak · saldırı = attack · tur = round · Son Düello = Last Duel · nötr = neutral.
export default {
  "Tur {n}": "Round {n}",
  "NÖTR": "NEUTRAL",
  "BAŞLA": "GO",
  "Tek bilen KONTROLÜ alır · 3/3 seri kazanır": "Sole correct answer takes CONTROL · 3/3 streak wins",
  "Rakibe gönder": "Send to opponent",
  "Kendine seç": "Pick for me",
  "RAKİP SEÇİYOR": "OPPONENT IS PICKING",
  "KENDİNE ALDIN": "YOU TOOK",
  "SANA GÖNDERDİ": "SENT TO YOU",
  "RAKİBE GÖNDERDİN": "YOU SENT",
  "KENDİNE ALDI": "THEY TOOK",
  "Aynı soru · joker yok": "Same question · no jokers",
  "Süre doldu · otomatik seçiliyor": "Time's up · auto-picking",
  "Seçimin": "Your pick",
  "Rakipten": "From opponent",
  "Rakip: {k}": "Opponent: {k}",
  "SON DÜELLO SENİN": "LAST DUEL IS YOURS",
  "SON DÜELLO RAKİBİN": "OPPONENT WINS LAST DUEL",
  "Tek doğru bilen sendin": "Only you got it right",
  "Tek doğru bilen rakipti": "Only your opponent got it right",
  "İKİNİZ DE BİLDİNİZ": "BOTH CORRECT",
  "İKİNİZ DE BİLEMEDİNİZ": "BOTH MISSED",
  "Yeni soru": "New question",
  "KONTROL RAKİPTE": "OPPONENT HAS CONTROL",
  "Kontrol kimsede değil": "No one has control",
  "RAKİP SALDIRDI": "OPPONENT LANDED",
  "KONTROL RAKİBE GEÇTİ": "CONTROL LOST",
  "SERİ DEĞİŞMEDİ": "STREAK UNCHANGED",
  "Seri {n}/{t}": "Streak {n}/{t}",
  "Rakip {n}/{t}": "Opponent {n}/{t}",
  "SON BASKI": "FINAL PUSH",
  "Bir saldırı daha, düello senin": "One more hit and the duel is yours",
  "Rakip bir saldırı uzakta": "Opponent is one hit away",
  "Sorular": "Questions",
  "Son Düello'yu sen bildin": "You won the Last Duel",
  "Son Düello'yu rakip bildi": "Your opponent won the Last Duel",
  "3/3 seri — düello senin": "3/3 streak — the duel is yours",
  "Rakip 3/3 seriye ulaştı": "Your opponent reached a 3/3 streak",
};
