// İngilizce çeviri eki — Tasarım Adım 2, şerit "dukkan". Anahtar Türkçe metnin kendisidir
// (dil.js ile aynı kural). Şeritler paralel çalıştığı için her biri kendi dosyasına yazar;
// dil.js bu dosyaları SOZLUK.en'e katar (buradaki karşılık önce gelir).
export default {
  // ——— Dükkân ———
  "Skill": "Jokers",
  "Kıyafet": "Outfits",
  "Dükkânın bazı bölümleri yüklenemedi. Tekrar dene.": "Some parts of the shop didn't load. Try again.",
  "Satın alma fiyatları alınamadı. Tekrar dene.": "Couldn't load store prices. Try again.",
  "Dükkân bölümleri": "Shop sections",
  "Coin'in şu an hiçbir skill'e yetmiyor.": "You don't have enough coins for any joker right now.",
  "Sende: {n}": "Owned: {n}",
  "Lv {0}": "Lv {0}",
  "Paketler": "Bundles",
  "Paket içeriği": "Bundle contents",
  "Skill kuralları": "Joker rules",
  "Bir video = +{0} coin.": "One video = +{0} coins.",
  "Bugün {0}/{1}": "Today {0}/{1}",
  "Video izle": "Watch a video",
  "Satın alma yalnızca Android uygulamasında yapılabilir. Tarayıcıda paket satın alınamaz.":
    "Purchases are only available in the Android app. Bundles can't be bought in the browser.",
  "Şu an satışta coin paketi yok": "No coin packs on sale right now",
  "+{n} bonus": "+{n} bonus",
  "Skill setin yüklenemedi. Tekrar dene.": "Couldn't load your joker set. Try again.",
  "Skill setin kaydedilemedi; önceki seçim geri yüklendi.": "Couldn't save your joker set — your previous picks are back.",
  "Boş yuva": "Empty slot",

  // ——— Profil bileşenleri ———
  "kullanılan skill": "jokers used",
  "Seri ve skiller": "Streaks & jokers",
  "{n} doğru": "{n} correct",
  "{0} ustalığı": "{0} mastery",
  "{0}: doğru oranı": "{0}: correct rate",

  // ——— Profil ———
  "Maç sırası ve davetler için haber veririz.": "We'll let you know when it's your turn or someone invites you.",
  "Kapalı — izin var ama bu cihaz bağlı değil. Açmak için dokun.": "Off — permission is granted but this device isn't connected. Tap to turn on.",
  "Kapalı — henüz izin verilmedi. Açınca tarayıcı izin isteyecek.": "Off — no permission yet. Turn it on and your browser will ask.",
  "Quiz Tactics'te benimle yarışmaya var mısın? Bu linkle gel, ikimiz de {n} coin kazanalım: {link}":
    "Up for a Quiz Tactics challenge? Join with this link and we both get {n} coins: {link}",
  "Quiz Tactics'te benimle yarışmaya var mısın? Bu linkle gel, ikimiz de coin kazanalım: {link}":
    "Up for a Quiz Tactics challenge? Join with this link and we both get coins: {link}",
  "Turnuva kazan, ilk kupan gelsin": "Win a tournament to earn your first trophy",
  "Maç oyna, serin başlasın": "Play a match to start your streak",
  "Kategori başarın": "Your category record",
  "Öğrenilen soru: {0} · Bankada: {1}": "Learned: {0} · In your bank: {1}",
  "{0} rütbesine ilerleme": "Progress to {0}",
  "Oyun ayarları": "Game settings",
  "Sayaç, doğru/yanlış ve maç sonu sesleri": "Timer, right/wrong and match-end sounds",
  "Değiştirmek için {0} kaldı.": "You can change it again in {0}.",
  "Her davet için ikiniz de {n} coin kazanırsınız.": "You both get {n} coins for every friend who joins.",
  "Her davet için ikiniz de coin kazanırsınız.": "You both get coins for every friend who joins.",
  "Şu ana kadar {n} kişi davet ettin.": "You've invited {n} so far.",
  "Bu işlem geri alınamaz. Onaylamak için aşağıya hesap kimliğini ({0}) yaz.":
    "This can't be undone. To confirm, type your account ID ({0}) below.",
  "ornek@eposta.com": "you@example.com",
  "Konumunu tekrar değiştirebilmen için {0} kaldı.": "You can change your location again in {0}.",

  // ——— Skill açıklamaları ve kuralları (Faz 4: EN taramasında Türkçe kalanlar) ———
  "İki yanlış şık elenir": "Removes two wrong answers",
  "Yanlış cevapta normal puanın yarısını kurtarır": "Saves half the normal points on a wrong answer",
  "Doğru cevabın puanını ikiye katlar": "Doubles the points for a correct answer",
  "İkinci Şans": "Second Chance",
  "İlk yanlışta aynı soruda bir kez daha cevaplatır": "After your first wrong answer, lets you answer the same question once more",
  "İlk yanlışta aynı süre içinde bir kez daha denersin": "After your first wrong answer, you get one more try within the same time",
  "Soru Değiştir (eski)": "Swap Question (old)",
  "Bir maçta en çok {0} skill kullanabilirsin.": "You can use up to {0} jokers per match.",
  "Seçtiğin her skill'i maçta en çok 2 kez kullanabilirsin.": "You can use each joker you pick up to 2 times per match.",
  "Her soruda en fazla 1 skill kullanabilirsin.": "You can use at most 1 joker per question.",
  "Ücretsiz 50:50 yalnız Serbest Klasik Mod'da; Dereceli maçta ve Düello'da hiçbir skill ücretsiz değil.":
    "The free 50:50 is only in Casual Classic; no joker is free in Ranked matches or Duels.",
  "Turnuva finalinde ve altın soruda skill kullanılamaz.": "Jokers can't be used in the tournament final or on the golden question.",
  "Skill'in bittiyse maçın içinden alabilirsin — dükkâna gitmene gerek yok.":
    "Out of a joker? You can buy it during the match — no need to visit the shop.",
  "Maçta {0} skill · tür başına 2 · soru başına 1": "{0} jokers per match · 2 per type · 1 per question",
  // Coin paketleri (328) — küçükten büyüğe
  "Avuç": "Handful",
  "Kese": "Pouch",
  "Sandık": "Chest",
  "Define": "Hoard",
  "En iyi değer": "Best value",
  "+%{n} bonus": "+{n}% bonus",
  "+{n} bonus coin": "+{n} bonus coins",
  // ——— 480/481: elmas · aura · koleksiyon (Ajan C, 24 Eyl 2026) ———
  "Joker": "Jokers",
  "Arka Plan": "Background",
  "İşlem uzun sürdü. Bağlantını kontrol et; alım yapıldıysa envanterinde görünür.": "That took too long. Check your connection; if the purchase went through it will show in your inventory.",
  "Elmas|para": "Gems",
  "Jokerler": "Jokers",
  "Bakiyen": "Your balance",
  "{n} elmas": "{n} gems",
  "Elmas yetmiyor": "Not enough gems",
  "Jokerler hesabına eklendi.": "Jokers added to your account.",
  "Jokerler şimdilik ücretsiz ve sınırsız — maçta stok gerekmez, satın almana gerek yok.": "Jokers are free and unlimited for now — no stock needed in matches, no need to buy.",
  "Coin'in şu an hiçbir jokere yetmiyor.": "You don't have enough coins for any joker right now.",
  "Joker kuralları": "Joker rules",
  "Coin nasıl kazanılır?": "How do I earn coins?",
  "Coin yalnızca oynayarak kazanılır, parayla satılmaz. Maç kazan, turnuvaya katıl, seriyi sürdür, rozet topla — jokerleri coin'le al.": "Coins are earned only by playing — they're never sold for money. Win matches, join tournaments, keep your streak, collect badges — and buy jokers with coins.",
  "Video izle, elmas kazan": "Watch a video, earn gems",
  "Günde {0} video = +{1} elmas.": "{0} video a day = +{1} gems.",
  "Şimdilik lig, turnuva, level ve serilerle elmas kazanabilirsin.": "For now you can earn gems from leagues, tournaments, levels and streaks.",
  "Video izle (+{0} elmas)": "Watch video (+{0} gems)",
  "+{0} elmas kazandın!": "You earned +{0} gems!",
  "Oynayarak elmas kazan": "Earn gems by playing",
  "Haftalık lig grubunda 1. / 2. / 3.": "Weekly league group 1st / 2nd / 3rd",
  "Turnuva birinciliği": "Winning a tournament",
  "Her {n} levelde bir": "Every {n} levels",
  "{n} günlük seri": "{n}-day streak",
  "Zor (elmas kademeli) rozetler": "Hard (diamond-tier) badges",
  "Elmas paketleri": "Gem packs",
  "Satın alma yalnızca Android uygulamasında yapılabilir. Elmas yalnızca arka plan ve çerçeve gibi görünüm eşyaları alır; oyunda avantaj sağlamaz.": "Purchases are only available in the Android app. Gems only buy cosmetics like backgrounds and frames; they give no in-game advantage.",
  "Elmas paketleri yakında satışta. Elmas yalnızca arka plan ve çerçeve gibi görünüm eşyaları alır; oyunda avantaj sağlamaz.": "Gem packs are coming soon. Gems only buy cosmetics like backgrounds and frames; they give no in-game advantage.",
  "Şu an satışta elmas paketi yok": "No gem packs on sale right now",
  "+{n} bonus elmas": "+{n} bonus gems",
  "Yakında": "Coming soon",
  "Satın alman tamamlandı, elmas hesabına eklendi.": "Purchase complete — gems added to your account.",
  "{ad} arka planı senin. Şimdi takabilirsin.": "The {ad} background is yours. You can equip it now.",
  "Arka plan takıldı.": "Background equipped.",
  "Arka plan çıkarıldı.": "Background removed.",
  "Arka plan takılamadı.": "Couldn't equip the background.",
  "Arka plan avatarının arkasında durur; takılı çerçeven önde kalır.": "A background sits behind your avatar; your equipped frame stays in front.",
  "{ad} arka planını satın al — {n} elmas": "Buy the {ad} background — {n} gems",
  "Arka Planlar": "Backgrounds",
  "Dokun, kendi avatarında dene. Arka plan elmasla alınır; taktığın arka planı maçta ve listelerde herkes görür.": "Tap to try it on your own avatar. Backgrounds are bought with gems; everyone sees your background in matches and lists.",
  "Çerçeveler satılmaz: lig, turnuva, level ve etkinliklerle kazanılır.": "Frames aren't sold: you earn them through leagues, tournaments, levels and events.",
  "Koleksiyonuna bak": "See your collection",
  "Koleksiyon": "Collection",
  "Koleksiyon yüklenemedi.": "Couldn't load your collection.",
  "Görünümün": "Your look",
  "Arka plan arkada, avatar ortada, çerçeve önde. Maçta, lig tablosunda ve profilinde herkes böyle görür.": "Background behind, avatar in the middle, frame in front. That's how everyone sees you in matches, the league table and your profile.",
  "{a}/{b} çerçeve · {c}/{d} arka plan": "{a}/{b} frames · {c}/{d} backgrounds",
  "Çerçeve satılmaz, kazanılır: lig, turnuva, level ve etkinliklerle.": "Frames aren't sold — they're earned through leagues, tournaments, levels and events.",
  "{ad} — kilitli: {kosul}": "{ad} — locked: {kosul}",
  "Arka plan avatarının arkasında durur. Dükkân'da elmasla alınır.": "A background sits behind your avatar. Buy them with gems in the Shop.",
  "Arka plansız": "No background",
  "{ad} — Dükkân'da {n} elmas": "{ad} — {n} gems in the Shop",
  "{ad} — etkinlik ödülü": "{ad} — event reward",
  "Dükkân'da arka planlar": "Backgrounds in the Shop",
  "Avatarlar": "Avatars",
  "Avatar değişti.": "Avatar changed.",
  "{lig} Lig'e yüksel": "Get promoted to {lig} League",
  "Level {n}'e ulaş": "Reach Level {n}",
  "Bir turnuvayı birinci bitir": "Win a tournament",
  "Yılbaşı etkinliğinde kazanılır": "Earned in the New Year event",
  "Ramazan Bayramı etkinliğinde kazanılır": "Earned in the Eid al-Fitr event",
  "Etkinlik": "Event",
  "Turnuva Şampiyonu": "Tournament Champion",
  "Yılbaşı": "New Year",
  "Ramazan Bayramı": "Eid al-Fitr",
  "Çerçeveler satılmaz, kazanılır": "Frames aren't sold — they're earned",
  "Yetersiz elmas": "Not enough gems",
  "Böyle bir aura yok": "No such background",
  "Bu aura satılmıyor": "This background isn't for sale",
  "Bu aura zaten sende": "You already own this background",
  "Bu aura sende yok": "You don't own this background",
  "Bugünkü elmas reklamı hakkın doldu (%/%)": "You've used today's gem video (%/%)",
  // Ajan B7 — boş ekran kurtarma, "Bağlantı yok" şeridi (D-103/D-201/D-206)
  "Sayfa yüklenemedi": "Couldn't load this page",
  "Bağlantı yok. İnternetini kontrol edip tekrar dene.": "No connection. Check your internet and try again.",
  "Beklenmedik bir hata oluştu. Tekrar dene; sorun sürerse sayfayı yenile.": "Something unexpected happened. Try again; if it keeps happening, reload the page.",
  "Bağlantı gelince sayfa kendiliğinden açılır.": "The page will open by itself once you're back online.",
  "Bağlantı yok": "No connection",
  // Ajan B7 — dükkân satın alma onayı + elmas çıkmazı (D-301/D-304)
  "{0} → kalan {1}": "{0} → {1} left",
  "Elmasın yetmiyor: {0} gerekli, {1} var": "Not enough gems: you need {0}, you have {1}",
  "Coin'in yetmiyor: {0} gerekli, {1} var": "Not enough coins: you need {0}, you have {1}",
  "Nasıl kazanılır?": "How to earn",
  "{0} kilidini aç": "Unlock {0}",
};
