// İngilizce çeviri eki — Düello Hâkimiyet (680), maç ekranı (Alt Ajan B). Anahtar Türkçe metnin kendisidir.
// dil.js en sonda katar: buradaki karşılık eski dosyalardakini ezer — bu yüzden "Al" gibi başka ekranlarda
// başka anlamı olan anahtarlar BURAYA KONMAZ (DuelloTahta.jsx › eylemEtiketi "Al"ı dile göre kendisi çözer: Claim).
// Sözlük: yuva = slot · Elinden al = Take · Al = Claim · Pekiştir = Reinforce · Baskın/Kalkan = Ambush/Shield.
export default {
  // Belirtme hâlleri (Rakip Sanat'ı aldı → Opponent took Art)
  "Bilim'i": "Science", "Tarih'i": "History", "Coğrafya'yı": "Geography", "Edebiyat'ı": "Literature", "Spor'u": "Sports",
  "Sanat'ı": "Art", "Sinema'yı": "Cinema", "Müzik'i": "Music", "Teknoloji'yi": "Technology", "Genel Kültür'ü": "General Knowledge",

  // Yuvalar + kartlar
  "Yuva durumu": "Slot status",
  "{n} tur kilitli": "Locked · {n} rounds",
  "Rakibin kategorileri · elinden al": "Opponent's categories · take",
  "Boş kategoriler · al": "Empty categories · claim",
  "Senin kategorilerin · pekiştir": "Your categories · reinforce",
  "sen önde": "you lead",
  "denk": "even",
  "rakip önde": "opponent leads",
  "Elinden al": "Take",
  "Pekiştir": "Reinforce",

  // Mesaj satırı
  "{n} yuvaya ilk ulaşan kazanır": "First to {n} slots wins",
  "Hamle tutması için: sen doğru, rakip yanlış": "For a move to land: you right, opponent wrong",
  "Rakip {n}'te! Bir tane daha alırsa kazanır.": "Opponent is at {n}! One more and they win.",
  "{n}'tesin! Bir tane daha al, maçı kazan.": "You're at {n}! Take one more and win.",
  "Rakip seçiyor…": "Opponent is choosing…",
  "Kategorini bekle": "Wait for the category",
  "Yalnız biriniz bilirse o kazanır": "Whoever alone knows it wins",
  "rakibin kategorisi": "opponent's category",
  "boş kategori": "empty category",
  "senin kategorin": "your category",
  "Elinden almak için: sen doğru, rakip yanlış": "To take it: you right, opponent wrong",
  "Boşta bilen alır · sen doğru, rakip yanlış": "Empty: the one who knows takes it",
  "Boş kategoride ikiniz de bilirseniz saldıran alır.": "Empty category: if you both know it, the attacker takes it.",
  "Pekiştirmek için: sen doğru, rakip yanlış": "To reinforce: you right, opponent wrong",
  "Rakip {kat} için saldırıyor": "Opponent attacks {kat}",
  // Soru ekranı: kategori durumu — renkli çerçeve + en çok 4 kelimelik etiket (DuelloTahta › hkKategoriDurumu)
  "Sen saldırıyorsun": "You're attacking",
  "Rakip saldırıyor": "Opponent is attacking",
  "Kategorin tehlikede": "Your category at risk",
  "Boş kategori · fırsat": "Empty category · chance",
  "Rakibin kategorisi": "Opponent's category",
  "Rakip pekiştiriyor": "Opponent reinforcing",
  // İlk 3 Düello: savunan beklerken çerçeve renginin anlamı (DuelloTahta › DURUM_IPUCLARI)
  "Mavi çerçeve = fırsat. Boş kategoride rakip yanlış yapar ve sen bilirsen kategori senin olur.": "Blue frame = chance. In an empty category, if your opponent is wrong and you are right, it's yours.",
  "Kırmızı çerçeve = kategorin tehlikede. Yanlış bilirsen ve rakip bilirse kaybedersin; Kalkan durdurur.": "Red frame = your category is at risk. Get it wrong while they get it right and you lose it; Shield stops it.",
  "Gri çerçeve = rakip pekiştiriyor. Kategori el değiştirmez; doğru bilirsen kilitlenmesini önlersin.": "Grey frame = opponent reinforcing. It doesn't change hands; a right answer from you stops the lock.",
  "Sen doğru bilirsen kategori sende kalır": "If you're right, it stays yours",
  "Rakip yanlış, sen doğru bilirsen alırsın": "Opponent wrong + you right: you take it",
  "Rakip doğru, sen yanlış bilirse 2 tur kilitlenir": "Opponent right + you wrong: locked 2 rounds",

  // Tur sonucu bandı
  "Sen: {b} · Rakip: {r}": "You: {b} · Opponent: {r}",
  "{kat} artık senin!": "{kat} is yours now!",
  "Rakip {kat} aldı": "Opponent took {kat}",
  "Rakip {kat} elinden aldı": "Opponent took {kat} from you",
  "{kat} {n} tur kilitlendi": "{kat} locked for {n} rounds",
  "Rakip {kat} pekiştirdi": "Opponent reinforced {kat}",
  "Kontra: boşta bilen aldı": "Counter: the one who knew the empty category took it",
  "İkiniz de bildiniz: boşta saldıran alır": "You both knew it: the attacker takes an empty category",
  "Hamle tutmadı": "The move didn't land",
  "ikiniz de bildiniz": "you both knew it",
  "ikiniz de bilemediniz": "neither of you knew it",
  "sen bilemedin": "you got it wrong",
  "rakip bilemedi": "the opponent got it wrong",
  "Baskın kullandın": "You used Ambush",
  "Rakip Baskın kullandı": "Opponent used Ambush",
  "Kalkan hamleyi durdurdu": "Shield stopped the move",
  "Baskın ve Kalkan birbirini götürdü": "Ambush and Shield cancelled each other out",

  // Alt çubuk
  "Bir kategori seç": "Pick a category",
  "Seçim": "Selection",
  "tutarsa Sen {a}→{b}, Rakip {r}→{s}": "if it lands: You {a}→{b}, Opponent {r}→{s}",
  "tutarsa Sen {a}→{b}": "if it lands: You {a}→{b}",
  "tutarsa {n} tur kilitli": "if it lands: locked {n} rounds",
  "Kazanırsın!": "You win!",

  // Maç sonu
  "Son tahta": "Final board",
  "yuva": "slots",
  "Hâkimiyet zaferi! {n} yuva doldu": "Domination victory! {n} slots filled",
  "Rakip {n} yuvayı doldurdu": "The opponent filled {n} slots",
  "Eşit ({a}-{b}) — Altın Soru'yu sen bildin": "Tied ({a}-{b}) — you got the Golden Question",
  "Eşit ({a}-{b}) — Altın Soru'yu rakip bildi": "Tied ({a}-{b}) — the opponent got the Golden Question",
  "{a}-{b} önde, kazandın": "Ahead {a}-{b}, you won",
  "{a}-{b} geride, kaybettin": "Behind {a}-{b}, you lost",
  "Tutmadı": "Didn't land",
  "Aldın": "You claimed it",
  "Elinden aldın": "You took it",
  "Pekiştirdin": "You reinforced it",
  "Rakip aldı": "Opponent claimed it",
  "Rakip elinden aldı": "Opponent took it",
  "Rakip pekiştirdi": "Opponent reinforced it",
  "Kontra: aldın": "Counter: you took it",
  "Kontra: rakip aldı": "Counter: opponent took it",

  // 853 · Savunma banı
  "Bir kategori banla": "Ban a category",
  "Rakip bu turda o kategoriyi seçemez": "Your opponent can't pick it this round",
  "Rakip ban seçiyor…": "Opponent is choosing a ban…",
  "Banladığı kategoriyi bu turda seçemezsin": "You can't pick the banned category this round",
  "Banlı": "Banned",
  "Önceki banın": "Your last ban",
  "RAKİP SALDIRACAK": "OPPONENT ATTACKS",
  "Bir kategoriyi BANLA": "BAN a category",
  "Dokun: rakip o kategoriden saldıramaz": "Tap: opponent can't attack from that category",
  "Geçen tur banladın": "You banned it last round",
  "Süre dolarsa ban kullanılmaz": "No ban is used if time runs out",
  "Banladın: {kat}": "You banned: {kat}",
  "Ban seçimi": "Ban selection",
  "Banlamak için bir karta dokun": "Tap a card to ban it",
  "Süre dolarsa ban yapılmaz.": "No ban if time runs out.",
  "Ardından kategorini seçeceksin.": "Then you'll pick your category.",
  "Şu an ban sırası sende değil": "It's not your turn to ban right now",
  "Bu Düello'da ban yok": "There are no bans in this Duel",   // 982: ban kapalı maçta duello_ban_sec
  "Aynı kategoriyi arka arkaya banlayamazsın": "You can't ban the same category twice in a row",
  "Bu kategori şu an banlanamaz": "This category can't be banned right now",

  // Savunma banı anları (DuelloBanAni.jsx): durum satırı, giriş damgası, açıklama, geçiş
  "BAN SIRASI SENDE": "YOUR BAN",
  "Bir karta dokun · rakip oradan saldıramaz": "Tap a card · opponent can't attack from it",
  "Bir kategoriyi kapat": "Lock one category",
  "Bir kategorin bu tur kapanacak": "One category will be locked this round",
  "Rakip bu tur seçemez": "Opponent can't pick it this round",
  "RAKİP BANLADI": "OPPONENT BANNED",
  "BANLADIN": "YOU BANNED",
  "Bu tur seçemezsin": "You can't pick it this round",
  "BAN KULLANILMADI": "NO BAN USED",
  "Süre doldu · rakip her kategoriden saldırabilir": "Time ran out · opponent can attack from any category",
  "SIRA SENDE": "YOUR MOVE",
  "Kategorini seç": "Pick your category",
  "Rakip ban kullanmadı · hepsi açık": "Opponent used no ban · all open",
  "Rakip ban kullanmadı": "Opponent used no ban",
  "Rakip {kat} banladı": "Opponent banned {kat}",
  "Rakip bunu banladı": "Opponent banned this",
  "Başka bir kategori seç": "Pick another category",
  "Rakip banladı": "Banned by opponent",
  "Sen banladın": "Banned by you",
  "Banın: {kat} · rakip seçemez": "Your ban: {kat} · opponent can't pick it",
  "Ban kullanılmadı · rakip serbest": "No ban used · opponent picks freely",
  "Banladığın kategoriyi rakip bu tur seçemez. Süre dolarsa ban kullanılmaz.": "Your opponent can't pick the category you ban this round. If time runs out, no ban is used.",
};
