// İngilizce çeviri eki — çerçeveler, rozetler, davet, kozmetik önizleme. Anahtar Türkçe metnin
// kendisidir (dil.js ile aynı kural); dil.js bu dosyayı SOZLUK.en'e katar.
export default {
  // ——— Nadirlik ———
  "Sıradan": "Common",
  "Nadir": "Rare",
  "Epik": "Epic",
  "Efsanevi": "Legendary",
  // ——— Çerçeve adları (görsel tanımlar; katalogdaki ad varsa o kullanılır) ———
  "Gece Mavisi": "Night Blue",
  "Nane": "Mint",
  "Mercan": "Coral",
  "Okyanus": "Ocean",
  "Zümrüt": "Emerald",
  "Yakut": "Ruby",
  "Ametist": "Amethyst",
  "Kutup Işığı": "Aurora",
  "Nebula": "Nebula",
  "Güneş Tacı": "Sun Crown",
  "Anka": "Phoenix",
  "Ejder": "Dragon",
  "Gümüş Lig": "Silver League",
  "Altın Lig": "Gold League",
  "Elmas Lig": "Diamond League",
  "Efsane Lig": "Legend League",
  "Level 25 Madalyonu": "Level 25 Medallion",
  "Level 50 Yıldızı": "Level 50 Star",
  "Level 75 Kanatları": "Level 75 Wings",
  "Level 100 Tacı": "Level 100 Crown",
  "Çerçevesiz": "No frame",
  "{ad} çerçevesi": "{ad} frame",
  // ——— Rozet kademeleri ve grupları ———
  "Bronz": "Bronze",
  "Gümüş": "Silver",
  "Altın": "Gold",
  "Elmas": "Diamond",
  "Level": "Level",
  "Klasik galibiyet": "Classic wins",
  "Düello galibiyet": "Duel wins",
  "Günlük seri": "Daily streak",
  "Kategori ustalığı": "Category mastery",
  "Turnuva": "Tournament",
  "Lig": "League",
  "Özel an": "Special moment",
  "Sosyal": "Social",
  "Gizli": "Hidden",
  "Gizli rozet": "Hidden badge",
  "Kilitli rozet": "Locked badge",
  // ——— Profil › Rozetler / vitrin / bildirim ———
  "Vitrinim": "My showcase",
  "Profilinde ve oyuncu kartında görünen {n} rozet. Kazandığın bir rozete dokun, vitrine ekle.":
    "The {n} badges shown on your profile and player card. Tap a badge you've earned to showcase it.",
  "Boş vitrin yeri": "Empty showcase slot",
  "Rozetler yüklenemedi.": "Couldn't load badges.",
  "Vitrin kaydedilemedi.": "Couldn't save the showcase.",
  "Kilitli": "Locked",
  "Vitrinden çıkar": "Remove from showcase",
  "Vitrine koy (ilkinin yerine)": "Showcase (replaces the first)",
  "Vitrine koy": "Add to showcase",
  "Bu rozet bir avatar çerçevesi de verir.": "This badge also unlocks an avatar frame.",
  "Nasıl kazanılacağı sır. Oynamaya devam et, kazandığında adı ortaya çıkar.":
    "How to earn it is a secret. Keep playing — its name is revealed when you earn it.",
  "Kazanıldı: {t}": "Earned: {t}",
  "İlerleme": "Progress",
  "Vitrin rozetleri": "Showcase badges",
  "Rozet": "Badge",
  "Yeni rozet: {ad}": "New badge: {ad}",
  "+{n} coin": "+{n} coins",
  "Yeni çerçeve kazandın": "You earned a new frame",
  "Rozet ödülü": "Badge reward",
  "Rozet ödülü ({kademe})": "Badge reward ({kademe})",
  // ——— Çerçevelerim ———
  "Çerçeveler yüklenemedi.": "Couldn't load frames.",
  "Çerçeve takılamadı.": "Couldn't equip the frame.",
  "Çerçevelerim": "My frames",
  "Taktığın çerçeve maçta, lig tablosunda ve arkadaş listesinde herkese görünür.":
    "Your equipped frame is visible to everyone in matches, the league table and friend lists.",
  "Takılı": "Equipped",
  "Takılıyor…": "Equipping…",
  "Tak": "Equip",
  "Dükkân'da daha fazla çerçeve": "More frames in the Shop",
  // ——— Dükkân › Çerçeve ———
  "Çerçeve": "Frames",
  "{lig} Lig'e çık": "Get promoted to {lig} League",
  "Level {n} rozetiyle gelir": "Comes with the Level {n} badge",
  "Etkinlik ödülü": "Event reward",
  "{ad} çerçevesi senin. Şimdi takabilirsin.": "The {ad} frame is yours. Equip it now.",
  "Çerçeve takıldı.": "Frame equipped.",
  "Çerçeve çıkarıldı.": "Frame removed.",
  "Sende var": "Owned",
  "Çıkar": "Remove",
  "Satılmaz": "Not for sale",
  "Dokun, kendi avatarında dene. Taktığın çerçeveyi maçta ve listelerde herkes görür.":
    "Tap to try it on your avatar. Everyone sees your equipped frame in matches and lists.",
  "Kazanılan çerçeveler": "Earned frames",
  "Lig atlayarak ve level rozetleriyle kazanılır; satılmaz.": "Earned through league promotion and level badges; not for sale.",
  // ——— Ana sayfa (kompakt oyuncu kartı, canlı lig kartı, görev şeridi) ———
  "Profilim: {ad}, Level {n}": "My profile: {ad}, Level {n}",
  "{g}g {s}s": "{g}d {s}h",
  "{s}s {dk}dk": "{s}h {dk}m",
  "Gümüş'e çıkmana {n} puan": "{n} points to Silver",
  "Altın'a çıkmana {n} puan": "{n} points to Gold",
  "Elmas'a çıkmana {n} puan": "{n} points to Diamond",
  "Efsane'ye çıkmana {n} puan": "{n} points to Legend",
  "Yükselme bölgesindesin": "You're in the promotion zone",
  "Bir üst sıraya {n} puan": "{n} points to the next rank",
  "Grubun zirvesindesin": "You're top of the group",
  "{lig} Lig, {s}. sıra. Lig sayfasına git": "{lig} League, rank {s}. Go to the league page",
  "{lig} Lig": "{lig} League",
  "Hafta bitimine {k}": "Week ends in {k}",
  "Haftalık lig": "Weekly league",
  "Dereceli bir maç oyna, lig grubuna katıl.": "Play a ranked match to join a league group.",
  "Günlük görevler: {a}/{b} tamam": "Daily quests: {a}/{b} done",
  "Görevler": "Quests",
  // ——— Davet ———
  "Arkadaşın": "Your friend",
  "{ad} seni davet etti: +{n} coin! Artık arkadaşsınız.": "{ad} invited you: +{n} coins! You're now friends.",
  "{ad} seni davet etti. Artık arkadaşsınız.": "{ad} invited you. You're now friends.",
  "{ad} ile arkadaş oldunuz. Aynı cihazdan açılan hesaplarda davet ödülü verilmez.":
    "You and {ad} are now friends. Accounts opened on the same device don't get invite rewards.",
  "Bu hesap zaten bir davetle bağlı.": "This account is already linked to an invite.",
  "Davet kodu yalnız yeni hesaplarda (ilk 3 gün) kullanılabilir.": "Invite codes only work on new accounts (first 3 days).",
  "Bu senin kendi kodun.": "That's your own code.",
  "Bu davet kodu bulunamadı. Kontrol edip tekrar dene.": "Invite code not found. Check it and try again.",
  "Davet kodu kullanılamadı.": "Couldn't use the invite code.",
  "Ödül alındı": "Reward received",
  "Aylık sınır doldu": "Monthly limit reached",
  "Ödülsüz": "No reward",
  "Level {a}/{b}": "Level {a}/{b}",
  "Davet kodun var mı?": "Have an invite code?",
  "Örn. J8K2M4PR": "e.g. J8K2M4PR",
  "Bağla": "Apply",
  "Davet bilgileri yüklenemedi.": "Couldn't load invite details.",
  "Quiz Tactics'te benimle yarış! Bu bağlantıyla gel, başlangıçta +{n} coin kazan: {link}":
    "Play Quiz Tactics with me! Join with this link and get +{n} coins to start: {link}",
  "Bağlantı kopyalanamadı. Kodu elle paylaşabilirsin.": "Couldn't copy the link. You can share the code by hand.",
  "Arkadaşın gelince +{b} coin alır; Level {lv}'e ulaşınca sen {a} coin kazanırsın.":
    "Your friend gets +{b} coins on joining; you earn {a} coins when they reach Level {lv}.",
  "sana": "for you",
  "arkadaşına": "for your friend",
  "Bağlantıyı paylaş": "Share link",
  "Bu ay ödüllü davet: {a}/{b}. Aynı cihazdan açılan hesaplar sayılmaz.":
    "Rewarded invites this month: {a}/{b}. Accounts opened on the same device don't count.",
  "Seni {ad} davet etti.": "{ad} invited you.",
  "bir arkadaşın": "a friend",
  "Davet ettiklerin": "People you invited",
  // ——— /kozmetik-onizleme ———
  "Kozmetik Önizleme": "Cosmetics Preview",
  "Bütün çerçeveler ve rozet madalyonları 24 / 40 / 64 / 120 px'te. 40 px altında süs ve hareket kapanır, yalnız renkli halka kalır.":
    "Every frame and badge medal at 24 / 40 / 64 / 120 px. Below 40 px ornaments and motion turn off; only the coloured ring remains.",
  "Hareket": "Motion",
  "Oyunda ekranda en çok 3 çerçeve oynar; bu sayfada sınır yok.": "In the game at most 3 frames animate per screen; no limit on this page.",
  "Maç zemini": "Match background",
  "Çerçeveleri koyu maç sahnesinde gör.": "See the frames on the dark match scene.",
  "Çerçeveler": "Frames",
  "Rozetler": "Badges",
  "Dükkân · Sıradan": "Shop · Common",
  "Dükkân · Nadir": "Shop · Rare",
  "Dükkân · Epik": "Shop · Epic",
  "Dükkân · Efsanevi": "Shop · Legendary",
  "Gri-mavi. Kalın tek renk halka, iç gölge, kabartma.": "Slate blue. Thick single-colour ring, inner shadow, embossed.",
  "Mavi. İki tonlu metal, üstte küçük süs.": "Blue. Two-tone metal with a small ornament on top.",
  "Mor. Çok katmanlı halka, mücevherler, 6 sn'de bir parıltı.": "Purple. Layered ring, gems, a shine every 6 s.",
  "Altın-turuncu. Dönen ışık halkası, kıvılcımlar, taç/kanat.": "Gold-orange. Rotating light ring, sparks, crown/wings.",
  "Lig çerçeveleri": "League frames",
  "Lig atlayınca kazanılır, satılmaz.": "Earned by promotion; not for sale.",
  "Level çerçeveleri": "Level frames",
  "Level 25 · 50 · 75 · 100 rozetiyle gelir.": "Comes with the Level 25 · 50 · 75 · 100 badge.",
  "Takılı çerçevesi olmayan oyuncu: ince beyaz halka.": "Player with no frame equipped: thin white ring.",
  "Kademe yalnız renkle değil, alt kenardaki nokta sayısıyla da okunur: bronz 1 · gümüş 2 · altın 3 · elmas 4.":
    "The tier reads from the dots on the bottom edge too, not only colour: bronze 1 · silver 2 · gold 3 · diamond 4.",
  "Gizli ve kilitli": "Hidden and locked",
  "Gizli (kazanılmadı)": "Hidden (not earned)",
  "Kilitli (soluk)": "Locked (faded)",
};
