// İngilizce çeviri eki — çerçeveler, rozetler, davet, kozmetik önizleme. Anahtar Türkçe metnin
// kendisidir (dil.js ile aynı kural); dil.js bu dosyayı SOZLUK.en'e katar.
export default {
  // ——— Nadirlik ———
  "Sıradan": "Common",
  "Nadir": "Rare",
  "Epik": "Epic",
  "Efsanevi": "Legendary",
  // ——— Çerçeve adları (görsel tanımlar; katalogdaki ad varsa o kullanılır) ———
  "Gece Mavisi": "Night Blue",
  "Nane": "Mint",
  "Mercan": "Coral",
  "Okyanus": "Ocean",
  "Zümrüt": "Emerald",
  "Yakut": "Ruby",
  "Ametist": "Amethyst",
  "Kutup Işığı": "Aurora",
  "Nebula": "Nebula",
  "Güneş Tacı": "Sun Crown",
  "Anka": "Phoenix",
  "Ejder": "Dragon",
  "Gümüş Lig": "Silver League",
  "Altın Lig": "Gold League",
  "Elmas Lig": "Diamond League",
  "Efsane Lig": "Legend League",
  "Level 25 Madalyonu": "Level 25 Medallion",
  "Level 50 Yıldızı": "Level 50 Star",
  "Level 75 Kanatları": "Level 75 Wings",
  "Level 100 Tacı": "Level 100 Crown",
  "Çerçevesiz": "No frame",
  "{ad} çerçevesi": "{ad} frame",
  // ——— Rozet kademeleri ve grupları ———
  "Bronz": "Bronze",
  "Gümüş": "Silver",
  "Altın": "Gold",
  "Elmas": "Diamond",
  "Level": "Level",
  "Klasik galibiyet": "Classic wins",
  "Düello galibiyet": "Duel wins",
  "Günlük seri": "Daily streak",
  "Kategori ustalığı": "Category mastery",
  "Turnuva": "Tournament",
  "Lig": "League",
  "Özel an": "Special moment",
  "Sosyal": "Social",
  "Gizli": "Hidden",
  "Gizli rozet": "Hidden badge",
  "Kilitli rozet": "Locked badge",
  // ——— /kozmetik-onizleme ———
  "Kozmetik Önizleme": "Cosmetics Preview",
  "Bütün çerçeveler ve rozet madalyonları 24 / 40 / 64 / 120 px'te. 40 px altında süs ve hareket kapanır, yalnız renkli halka kalır.":
    "Every frame and badge medal at 24 / 40 / 64 / 120 px. Below 40 px ornaments and motion turn off; only the coloured ring remains.",
  "Hareket": "Motion",
  "Oyunda ekranda en çok 3 çerçeve oynar; bu sayfada sınır yok.": "In the game at most 3 frames animate per screen; no limit on this page.",
  "Maç zemini": "Match background",
  "Çerçeveleri koyu maç sahnesinde gör.": "See the frames on the dark match scene.",
  "Çerçeveler": "Frames",
  "Rozetler": "Badges",
  "Dükkân · Sıradan": "Shop · Common",
  "Dükkân · Nadir": "Shop · Rare",
  "Dükkân · Epik": "Shop · Epic",
  "Dükkân · Efsanevi": "Shop · Legendary",
  "Gri-mavi. Kalın tek renk halka, iç gölge, kabartma.": "Slate blue. Thick single-colour ring, inner shadow, embossed.",
  "Mavi. İki tonlu metal, üstte küçük süs.": "Blue. Two-tone metal with a small ornament on top.",
  "Mor. Çok katmanlı halka, mücevherler, 6 sn'de bir parıltı.": "Purple. Layered ring, gems, a shine every 6 s.",
  "Altın-turuncu. Dönen ışık halkası, kıvılcımlar, taç/kanat.": "Gold-orange. Rotating light ring, sparks, crown/wings.",
  "Lig çerçeveleri": "League frames",
  "Lig atlayınca kazanılır, satılmaz.": "Earned by promotion; not for sale.",
  "Level çerçeveleri": "Level frames",
  "Level 25 · 50 · 75 · 100 rozetiyle gelir.": "Comes with the Level 25 · 50 · 75 · 100 badge.",
  "Takılı çerçevesi olmayan oyuncu: ince beyaz halka.": "Player with no frame equipped: thin white ring.",
  "Kademe yalnız renkle değil, alt kenardaki nokta sayısıyla da okunur: bronz 1 · gümüş 2 · altın 3 · elmas 4.":
    "The tier reads from the dots on the bottom edge too, not only colour: bronze 1 · silver 2 · gold 3 · diamond 4.",
  "Gizli ve kilitli": "Hidden and locked",
  "Gizli (kazanılmadı)": "Hidden (not earned)",
  "Kilitli (soluk)": "Locked (faded)",
};
