// İngilizce çeviri eki — çerçeveler, rozetler, davet, kozmetik önizleme. Anahtar Türkçe metnin
// kendisidir (dil.js ile aynı kural); dil.js bu dosyayı SOZLUK.en'e katar.
export default {
  // ——— Nadirlik ———
  "Sıradan": "Common",
  "Nadir": "Rare",
  "Epik": "Epic",
  "Efsanevi": "Legendary",
  // ——— Çerçeve adları (görsel tanımlar; katalogdaki ad varsa o kullanılır) ———
  "Bulut": "Cloud",
  "Çiçek Bahçesi": "Flower Garden",
  "Neon Çizgi": "Neon Line",
  "Buz Kristali": "Ice Crystal",
  "Okyanus Dalgası": "Ocean Wave",
  "Yıldız Tozu": "Stardust",
  "Ejder Pulu": "Dragon Scale",
  "Şimşek": "Lightning",
  "Gezegen Halkası": "Planet Ring",
  "Alev Kanatları": "Flame Wings",
  "Kraliyet": "Royal",
  "Kozmik": "Cosmic",
  "Gümüş Lig": "Silver League",
  "Altın Lig": "Gold League",
  "Elmas Lig": "Diamond League",
  "Efsane Lig": "Legend League",
  "Level 25 Bronz": "Level 25 Bronze",
  "Level 50 Gümüş": "Level 50 Silver",
  "Level 75 Altın": "Level 75 Gold",
  "Level 100 Altın Kanatlar": "Level 100 Golden Wings",
  "Çerçevesiz": "No frame",
  "{ad} çerçevesi": "{ad} frame",
  // ——— Rozet kademeleri ve grupları ———
  "Bronz": "Bronze",
  "Gümüş": "Silver",
  "Altın": "Gold",
  "Elmas": "Diamond",
  "Level": "Level",
  "Klasik galibiyet": "Classic wins",
  "Düello galibiyet": "Duel wins",
  "Günlük seri": "Daily streak",
  "Kategori ustalığı": "Category mastery",
  "Turnuva": "Tournament",
  "Lig": "League",
  "Özel an": "Special moment",
  "Sosyal": "Social",
  "Gizli": "Hidden",
  "Gizli rozet": "Hidden badge",
  "Kilitli rozet": "Locked badge",
  // ——— Profil › Rozetler / vitrin / bildirim ———
  "Vitrinim": "My showcase",
  "Profilinde ve oyuncu kartında görünen {n} rozet. Kazandığın bir rozete dokun, vitrine ekle.":
    "The {n} badges shown on your profile and player card. Tap a badge you've earned to showcase it.",
  "Boş vitrin yeri": "Empty showcase slot",
  "Rozetler yüklenemedi.": "Couldn't load badges.",
  "Vitrin kaydedilemedi.": "Couldn't save the showcase.",
  "Kilitli": "Locked",
  "Vitrinden çıkar": "Remove from showcase",
  "Vitrine koy (ilkinin yerine)": "Showcase (replaces the first)",
  "Vitrine koy": "Add to showcase",
  "Bu rozet bir avatar çerçevesi de verir.": "This badge also unlocks an avatar frame.",
  "Nasıl kazanılacağı sır. Oynamaya devam et, kazandığında adı ortaya çıkar.":
    "How to earn it is a secret. Keep playing — its name is revealed when you earn it.",
  "Kazanıldı: {t}": "Earned: {t}",
  "İlerleme": "Progress",
  "Vitrin rozetleri": "Showcase badges",
  "Rozet": "Badge",
  "Yeni rozet: {ad}": "New badge: {ad}",
  "+{n} coin": "+{n} coins",
  "Yeni çerçeve kazandın": "You earned a new frame",
  "Rozet ödülü": "Badge reward",
  "Rozet ödülü ({kademe})": "Badge reward ({kademe})",
  // ——— Çerçevelerim ———
  "Çerçeveler yüklenemedi.": "Couldn't load frames.",
  "Çerçeve takılamadı.": "Couldn't equip the frame.",
  "Çerçevelerim": "My frames",
  "Taktığın çerçeve maçta, lig tablosunda ve arkadaş listesinde herkese görünür.":
    "Your equipped frame is visible to everyone in matches, the league table and friend lists.",
  "Takılı": "Equipped",
  "Takılıyor…": "Equipping…",
  "Tak": "Equip",
  "Dükkân'da daha fazla çerçeve": "More frames in the Shop",
  // ——— Dükkân › Çerçeve ———
  "Çerçeve": "Frames",
  "{lig} Lig'e çık": "Get promoted to {lig} League",
  "Level {n} rozetiyle gelir": "Comes with the Level {n} badge",
  "Etkinlik ödülü": "Event reward",
  "{ad} çerçevesi senin. Şimdi takabilirsin.": "The {ad} frame is yours. Equip it now.",
  "Çerçeve takıldı.": "Frame equipped.",
  "Çerçeve çıkarıldı.": "Frame removed.",
  "Sende var": "Owned",
  "Çıkar": "Remove",
  "Satılmaz": "Not for sale",
  "Dokun, kendi avatarında dene. Taktığın çerçeveyi maçta ve listelerde herkes görür.":
    "Tap to try it on your avatar. Everyone sees your equipped frame in matches and lists.",
  "Kazanılan çerçeveler": "Earned frames",
  "Lig atlayarak ve level rozetleriyle kazanılır; satılmaz.": "Earned through league promotion and level badges; not for sale.",
  // ——— Ana sayfa (kompakt oyuncu kartı, canlı lig kartı, görev şeridi) ———
  "Profilim: {ad}, Level {n}": "My profile: {ad}, Level {n}",
  "{g}g {s}s": "{g}d {s}h",
  "{s}s {dk}dk": "{s}h {dk}m",
  "Gümüş'e çıkmana {n} puan": "{n} points to Silver",
  "Altın'a çıkmana {n} puan": "{n} points to Gold",
  "Elmas'a çıkmana {n} puan": "{n} points to Diamond",
  "Efsane'ye çıkmana {n} puan": "{n} points to Legend",
  "Yükselme bölgesindesin": "You're in the promotion zone",
  "Bir üst sıraya {n} puan": "{n} points to the next rank",
  "Grubun zirvesindesin": "You're top of the group",
  "{lig} Lig, {s}. sıra. Lig sayfasına git": "{lig} League, rank {s}. Go to the league page",
  "{lig} Lig": "{lig} League",
  "Hafta bitimine {k}": "Week ends in {k}",
  "Haftalık lig": "Weekly league",
  "Dereceli bir maç oyna, lig grubuna katıl.": "Play a ranked match to join a league group.",
  "Günlük görevler: {a}/{b} tamam": "Daily quests: {a}/{b} done",
  "Görevler": "Quests",
  // ——— Davet ———
  "Arkadaşın": "Your friend",
  "{ad} seni davet etti: +{n} coin! Artık arkadaşsınız.": "{ad} invited you: +{n} coins! You're now friends.",
  "{ad} seni davet etti. Artık arkadaşsınız.": "{ad} invited you. You're now friends.",
  "{ad} ile arkadaş oldunuz. Aynı cihazdan açılan hesaplarda davet ödülü verilmez.":
    "You and {ad} are now friends. Accounts opened on the same device don't get invite rewards.",
  "Bu hesap zaten bir davetle bağlı.": "This account is already linked to an invite.",
  "Davet kodu yalnız yeni hesaplarda (ilk 3 gün) kullanılabilir.": "Invite codes only work on new accounts (first 3 days).",
  "Bu senin kendi kodun.": "That's your own code.",
  "Bu davet kodu bulunamadı. Kontrol edip tekrar dene.": "Invite code not found. Check it and try again.",
  "Davet kodu kullanılamadı.": "Couldn't use the invite code.",
  "Ödül alındı": "Reward received",
  "Aylık sınır doldu": "Monthly limit reached",
  "Ödülsüz": "No reward",
  "Level {a}/{b}": "Level {a}/{b}",
  "Davet kodun var mı?": "Have an invite code?",
  "Örn. J8K2M4PR": "e.g. J8K2M4PR",
  "Bağla": "Apply",
  "Davet bilgileri yüklenemedi.": "Couldn't load invite details.",
  "Quiz Tactics'te benimle yarış! Bu bağlantıyla gel, başlangıçta +{n} coin kazan: {link}":
    "Play Quiz Tactics with me! Join with this link and get +{n} coins to start: {link}",
  "Bağlantı kopyalanamadı. Kodu elle paylaşabilirsin.": "Couldn't copy the link. You can share the code by hand.",
  "Arkadaşın gelince +{b} coin alır; Level {lv}'e ulaşınca sen {a} coin kazanırsın.":
    "Your friend gets +{b} coins on joining; you earn {a} coins when they reach Level {lv}.",
  "sana": "for you",
  "arkadaşına": "for your friend",
  "Bağlantıyı paylaş": "Share link",
  "Bu ay ödüllü davet: {a}/{b}. Aynı cihazdan açılan hesaplar sayılmaz.":
    "Rewarded invites this month: {a}/{b}. Accounts opened on the same device don't count.",
  "Seni {ad} davet etti.": "{ad} invited you.",
  "bir arkadaşın": "a friend",
  "Davet ettiklerin": "People you invited",
  // ——— /kozmetik-onizleme ———
  "Kozmetik Önizleme": "Cosmetics Preview",
  "Bütün çerçeveler ve rozet madalyonları 24 / 40 / 64 / 120 px'te. 40–55 px'te yalnız ana süsler çizilir; 40 px altında süs ve hareket kapanır, yalnız renkli halka kalır.":
    "Every frame and badge medal at 24 / 40 / 64 / 120 px. At 40–55 px only the main ornaments are drawn; below 40 px ornaments and motion turn off and only the coloured ring remains.",
  "Hareket": "Motion",
  "Oyunda ekranda en çok 3 çerçeve oynar; bu sayfada sınır yok.": "In the game at most 3 frames animate per screen; no limit on this page.",
  "Maç zemini": "Match background",
  "Çerçeveleri koyu maç sahnesinde gör.": "See the frames on the dark match scene.",
  "Çerçeveler": "Frames",
  "Rozetler": "Badges",
  "Dükkân · Sıradan": "Shop · Common",
  "Dükkân · Nadir": "Shop · Rare",
  "Dükkân · Epik": "Shop · Epic",
  "Dükkân · Efsanevi": "Shop · Legendary",
  "Sade ama temiz, durağan: Bulut · Çiçek Bahçesi · Neon Çizgi.": "Simple but clean, static: Cloud · Flower Garden · Neon Line.",
  "Hafif parıltı: Buz Kristali · Okyanus Dalgası · Yıldız Tozu.": "A gentle glint: Ice Crystal · Ocean Wave · Stardust.",
  "Belirgin süs, 7 sn'de bir parıltı: Ejder Pulu · Şimşek · Gezegen Halkası.": "Bold ornaments, a shine every 7 s: Dragon Scale · Lightning · Planet Ring.",
  "Sürekli canlı efekt + seyrek kıvılcım: Alev Kanatları · Kraliyet · Kozmik.": "A constant live effect + occasional sparks: Flame Wings · Royal · Cosmic.",
  "Lig çerçeveleri": "League frames",
  "Lig atlayınca kazanılır, satılmaz. Gümüş: kalkan + defne · Altın: defne + taç · Elmas: kristal uçlar + ışık kırılması · Efsane: alev aurası + taç.":
    "Earned by promotion; not for sale. Silver: shield + laurel · Gold: laurel + crown · Diamond: crystal spikes + light refraction · Legend: flame aura + crown.",
  "Level çerçeveleri": "Level frames",
  "Level 25 · 50 · 75 · 100 rozetiyle gelir. Alt plakada level, yıldız sayısı artar; 100'de altın kanatlar.":
    "Comes with the Level 25 · 50 · 75 · 100 badge. The level sits on the bottom plate, stars increase; golden wings at 100.",
  "Takılı çerçevesi olmayan oyuncu: ince beyaz halka.": "Player with no frame equipped: thin white ring.",
  "Kademe yalnız renkle değil, alt kenardaki nokta sayısıyla da okunur: bronz 1 · gümüş 2 · altın 3 · elmas 4.":
    "The tier reads from the dots on the bottom edge too, not only colour: bronze 1 · silver 2 · gold 3 · diamond 4.",
  "Gizli ve kilitli": "Hidden and locked",
  "Gizli (kazanılmadı)": "Hidden (not earned)",
  "Kilitli (soluk)": "Locked (faded)",
  // ——— Elmas kozmetikleri + tepki (540–542, Ajan C) ———
  "Efekti yeniden oynat": "Replay the effect",
  "Tekrar": "Replay",
  "Bu bölümde şu an satışta bir şey yok.": "Nothing is on sale in this section right now.",
  "{ad} senin. Şimdi takabilirsin.": "{ad} is yours. You can equip it now.",
  "{ad} paketi senin. Maçta tepkilerin arasında.": "The {ad} pack is yours. It's in your reactions during matches.",
  "Takıldı.": "Equipped.",
  "Çıkarıldı.": "Removed.",
  "Satışta değil — yalnız sen görüyorsun": "Not on sale — only you can see this",
  "Test için tak": "Equip for testing",
  "Test modunda açık": "Unlocked in test mode",
  "{ad} satın al — {n} elmas": "Buy {ad} — {n} diamonds",
  "Satılmıyor": "Not for sale",
  "Aldıkların Profil › Koleksiyon'da; oradan takıp çıkarabilirsin.": "Your purchases are in Profile › Collection; equip or remove them there.",
  "Kostümlü avatar — elmasla alınır.": "Costume avatar — bought with diamonds.",
  "Günlük avatar — bedava.": "Everyday avatar — free.",
  "Bedava": "Free",
  "Bu maçta tepki hakkın bitti": "You've used all your reactions this match",
  "{n} tepki hakkın kaldı": "{n} reactions left",
  "Rakibin zaferi": "Opponent's victory",
  "Sahip test modu: satın almadan takabilirsin; taktığın maçta rakibe de görünür.": "Owner test mode: equip without buying; opponents see what you equip in matches.",
  "Maçta hazır": "Ready in matches",
  "Rakip tepkilerini gizle": "Hide opponent reactions",
  "Maçta rakibinin gönderdiği tepkiler (emoji) ekranında görünmez. Bu cihazda saklanır.": "Reactions (emoji) your opponent sends during a match won't show on your screen. Saved on this device.",
  "Satış seçimi": "Sale choice",
  "Satışa girsin": "Put on sale",
  "Girmesin": "Keep off sale",
  "Dokun: tekrar": "Tap: replay",
  "Kaybedenin ekranı": "Loser's screen",
  "Elmas kozmetikleri": "Diamond cosmetics",
  "Her kalemde seçimini yap. Satış bayrağı açılınca yalnız \"Satışa girsin\" dediklerin satılır; botlar da yalnız onları takar. Seçimler sunucuda, yenileyince durur.": "Choose for each item. When sales open, only items marked \"Put on sale\" are sold, and bots only wear those. Choices are saved on the server and survive a refresh.",
  "Her kozmetik gerçek yerinde. Satış seçimi yalnız sahip hesabıyla görünür.": "Every cosmetic in its real place. The sale choice is visible only to the owner account.",
  "Aura zaten satışta; buradaki seçim satışı değiştirmez, yalnız gizli botların takmasını belirler. Yerleri: maç şeridi, lig tablosu.": "Auras are already on sale; this choice doesn't change that, it only decides what bots wear. Shown in: match bar, league table.",
  "VS Kartı": "VS Card",
  "Rakip aranırken, VS anında ve profil başlığında kartının arka planı. Varsayılan düz kart bedava.": "Your card's background while searching, at the VS moment and in your profile header. The plain default card is free.",
  "İsim Efekti": "Name Effect",
  "Lig tablosu, maç şeridi, maç sonu ve profil. Kontrast her zeminde en az 4,5:1.": "League table, match bar, match end and profile. Contrast at least 4.5:1 on every background.",
  "Zafer Efekti": "Victory Effect",
  "Kazanınca maç sonu sahnesine eklenir; kaybeden rakip de küçük boyutta görür. Sahne sesleri değişmez.": "Added to the match-end scene when you win; the losing opponent sees it small. Scene sounds don't change.",
  "Tepki": "Reaction",
  "Maç içinde gönderenin avatarının yanında ~2 sn balon. Dokun, dene.": "During a match, a bubble next to the sender's avatar for ~2 s. Tap to try.",
  "Bedava 4": "Free 4",
  "herkeste": "everyone has these",
  "Uzay": "Space",
  "Orman": "Forest",
  "Neon Şehir": "Neon City",
  "Okyanus": "Ocean",
  "Volkan": "Volcano",
  "Sakura": "Sakura",
  "Gökkuşağı": "Rainbow",
  "Neon Mavi": "Neon Blue",
  "Alev": "Flame",
  "Buz": "Ice",
  "Mor Işıltı": "Purple Glow",
  "Havai Fişek": "Fireworks",
  "Altın Yağmuru": "Gold Rain",
  "Ejder Alevi": "Dragon Fire",
  "Kar Fırtınası": "Snowstorm",
  "Yıldız Yağmuru": "Star Shower",
  "Eğlence": "Fun",
  "Rekabet": "Competition",
  "Alkış": "Applause",
  "Ter döktüm": "That was close",
  "Hmm": "Hmm",
  "Ateş": "Fire",
  "Tam isabet": "Bullseye",
  "Kral benim": "I'm the king",
  "Güçlü": "Strong",
  "Olamaz": "No way",
  "Saygılar": "Respect",
  "Lütfen": "Please",
  "Avatar": "Avatar",
  "Rakip aranırken, VS anında ve profilinde kartının arka planı.": "Your card's background while searching, at the VS moment and on your profile.",
  "Lig tablosunda, maç şeridinde, maç sonunda ve profilinde adının görünümü.": "How your name looks in the league table, match bar, match end and on your profile.",
  "Kazandığında maç sonu sahnesine eklenir. Rakibin de görür.": "Added to the match-end scene when you win. Your opponent sees it too.",
  "Maçta rakibine gönderebileceğin 4 yeni tepki. Paket takılmaz, alınca maçta hazır.": "4 new reactions to send your opponent in matches. Packs aren't equipped — once bought they're ready.",
};
