// İngilizce çeviri eki — Tasarım Adım 2, şerit "mac". Anahtar Türkçe metnin kendisidir
// (dil.js ile aynı kural). Şeritler paralel çalıştığı için her biri kendi dosyasına yazar;
// dil.js bu dosyaları SOZLUK.en'e katar (buradaki karşılık önce gelir).
export default {
  // --- Maç ekranları (M1) ---
  "{0} sorunun tamamını oynadın. {1} kendi zamanında oynayınca maç sonuçlanacak — bittiğinde sana haber vereceğiz.": "You've played all {0} questions. The match ends once {1} plays their turn — we'll let you know.",
  "{0} senden önde. Bu maç sıra beklemeden oynanır — sen kendi hızında devam et, rakibin de kendi zamanında oynar.": "{0} is ahead of you. This match isn't turn-based — play at your own pace, your opponent plays at theirs.",
  "Rakip cevapladı": "Opponent answered",
  "Doğru!": "Correct!",
  "Soru {n}": "Question {n}",
  "Adil": "Fair",
  "Adil değil": "Not fair",
  "Joker bilgileri alınamadı. Tekrar dene.": "Couldn't load your jokers. Try again.",
  "Sürene {0} saniye eklendi.": "+{0} seconds on your clock.",
  "Sorun değişti.": "New question for you.",
  "Sigorta aktif — yanlışta 5 puan korunur.": "Insurance on — you keep 5 points if you miss.",
  "2X aktif — doğru cevap 20 puan.": "2X on — a correct answer scores 20.",
  "İkinci Şans aktif.": "Second Chance on.",
  "Bu soruda joker kullanılamaz.": "Jokers are locked on this question.",
  "Turnuva finalinde joker kullanılamaz": "No jokers in the tournament final",
  "Bu maçta en fazla {0} joker": "Max {0} jokers this match",
  "Bu sorudaki joker hakkını kullandın": "You've used your joker for this question",
  "Bu joker için maç hakkın doldu": "You've used this joker up for the match",
  "Jokerler şimdilik ücretsiz ve sınırsız": "Jokers are free and unlimited for now",
  "Arkadaş maçı: joker hakkın sınırsız": "Friendly match: unlimited jokers",
  "Bu maçta {0} joker kullanımın kaldı": "{0} joker uses left this match",
  "Maç hakkı: {0}": "Uses left: {0}",
  "Bu maçta joker kullanımın doldu ({0}/{1}).": "No joker uses left this match ({0}/{1}).",
  "Herkes aynı soruyu aynı anda görür. Maç hepiniz hazır olunca başlar.": "Everyone sees the same question at the same time. The match starts when you're all ready.",
  "{0}/{1} hazır": "{0}/{1} ready",
  "Beklenen: {0}": "Waiting for: {0}",
  "İstersen maçı sıra tabanlı bırak: sen kendi bölümünü şimdi oynarsın, rakibin kendi zamanında oynar.": "You can switch to turn-based: play your part now, and your opponent plays when they can.",
  "{0} oyundan ayrıldı. Maç duraklatıldı — süre işlemiyor, bu yüzden bir şey kaybetmiyorsun.": "{0} left the game. The match is paused — the clock is stopped, so you don't lose anything.",
  "{0} üst üste!": "{0} in a row!",
  "{0} karşısında {1}-{2} kazandım!": "I beat {0} {1}-{2}!",
  "Maç bitti ama oturum açık: istersen burada kalıp sohbet edebilirsin. Çıkmak sana kalmış.": "The match is over but the room stays open: stick around and chat if you like. Leave whenever you want.",
  "Maç bitti ama oturum açık: istersen burada kalıp {0} ile konuşmaya devam edebilirsin. Çıkmak sana kalmış.": "The match is over but the room stays open: keep chatting with {0} if you like. Leave whenever you want.",
  "Tamamlandı": "Done",
  "Turların: {d}/{t} doğru": "Your rounds: {d}/{t} correct",
  "{n}. soru: {durum}": "Question {n}: {durum}",
  "{n}. gün": "Day {n}",
  "Serin sürüyor": "Your streak is alive",
  "Bu maçta kullandığın jokerler:": "Jokers you used this match:",
  "{n} soruyu yanlış bildin": "You missed {n} questions",
  "Hatalarım'a eklendi — tekrar çalış": "Added to My Mistakes — practice them",
  "Rütbe atladın!": "Rank up!",
  "Tamam": "OK",
  // Turnuva (M1)
  "Lobiden ayrılamadın. Tekrar dene.": "Couldn't leave the lobby. Try again.",
  "Turnuva bilgisi alınamadı": "Couldn't load the tournament",
  "Sıradaki turnuva": "Next tournament",
  "Bu haftanın ilk 3 ödülü: {ad}": "This week's top-3 prize: {ad}",
  "Turnuva lobisi": "Tournament lobby",
  "Lobiden ayrıl": "Leave lobby",
  "Lobideki oyuncular": "Players in the lobby",
  "Kendi ligim": "My league",
  "Altın soru": "Golden question",
  "{n} oyuncu başa baş — biri bilene kadar sürer": "{n} players neck and neck — it goes on until someone gets one right",
  "Canlı · {n} oyuncu hayatta": "Live · {n} players left",
  "Hayatta kalanlar": "Still standing",
  "{ad} · {n} doğru": "{ad} · {n} correct",
  "Turnuvalar her gün {saatler} saatlerinde başlar; başlamadan lobide olman gerekir.": "Tournaments start every day at {saatler}; you need to be in the lobby before it starts.",
  "Turnuvalar her gün {saatler} saatlerinde başlar (Türkiye saati); başlamadan lobide olman gerekir.": "Tournaments start every day at {saatler} (Turkey time); you need to be in the lobby before it starts.",
  "Son kalan kazanır ve +150 lig puanı alır;": "Last one standing wins +150 league points;",
  "ilk 10'a giren ve katılan herkes de puan kazanır. Finalde joker kullanılamaz — sadece bilgi.": "the top 10 and everyone who joins earn points too. No jokers in the final — just knowledge.",
  "{n} katılımcı": "{n} players",
  "Son turnuvanın ilk üçü": "Last tournament's top three",
  "saat": "hours",
  "dakika": "minutes",
  // Grup + Hatalarım (M1)
  "Davet yanıtlanamadı. Tekrar dene.": "Couldn't answer the invite. Try again.",
  "{n}. sıra": "Place {n}",
  "Skor tablosu": "Scoreboard",
  "soru bankanda": "questions in your bank",
  "öğrenildi": "learned",
  "Henüz yok — denemeye devam et": "None yet — keep trying",
  "Çalışma · puan verilmez": "Practice · no points",
  "{n}/{t} · {k} soru kaldı": "{n}/{t} · {k} questions left",
  "bankandan · {n} kez yanlış": "from your bank · missed {n}×",
  "Bugüne kadar toplam {n} soru öğrendin. Doğru cevapların kategori ustalığına işlendi.": "You've learned {n} questions so far. Your correct answers count toward category mastery.",
  // --- Düello (M2) ---
  "Klasik ile aynı lig puanı ve coin ödülü": "Same league points and coin rewards as Classic",
  "Maçta en fazla 4 joker kullanımı: aynı joker en çok 2 kez, soru başına 1": "Up to 4 joker uses per match: the same one twice at most, 1 per question",
  "Aynı soruyu aynı anda cevaplarsınız.": "You both answer the same question at the same time.",
  "Rakibin ne cevapladığını göremezsin, yalnız cevapladığını görürsün.": "You never see what your opponent picked — only that they answered.",
  "Kategori seçerken süre dolarsa rastgele gelir.": "Run out of time while picking and a random category comes up.",
  "UZATMA": "OVERTIME",
  "Uzatma": "Overtime",
  "Tur {n}/{t}": "Round {n}/{t}",
  "Kategoriyi seçen": "Picking the category",
  "Kategori seçme sırası sende": "Your turn to pick the category",
  "Aynı soru · aynı anda": "Same question · same time",
  "Kategori seç": "Pick a category",
  "{ad} kategori seçiyor…": "{ad} is picking a category…",
  "Süre dolarsa kategori rastgele seçilir.": "If time runs out, a random category is picked.",
  "Kategoriyi seçen taraf değişir, soruyu ikiniz aynı anda cevaplarsınız.": "You take turns picking; you both answer the same question at once.",
  "doldu": "used up",
  "Rakip %{n}": "Opponent {n}%",
  "Rakip": "Opponent",
  "%{n}": "{n}%",
  "Rakip düşünüyor…": "Opponent is thinking…",
  "En güçlü kategorilerin": "Your strongest categories",
  "En zayıf kategorilerin": "Your weakest categories",
  "Kategori oranların birkaç cevaptan sonra burada görünür.": "Your category rates show up here after a few answers.",
  "Bu maçta gelenler": "Played this match",
  "Cevabın kilitlendi": "Answer locked",
  "Yanıtsız": "No answer",
  "yanıtsız": "no answer",
  "düşünüyor…": "thinking…",
  "cevapladı": "answered",
  "Cevabın kilitlendi — sonuç ikiniz de cevaplayınca açılır.": "Answer locked — the result shows once you've both answered.",
  "Süren doldu — sonuç bekleniyor.": "Time's up — waiting for the result.",
  "Şık işaretlenmedi": "No option picked",
  "Soru açılınca kullanılır.": "Usable once the question opens.",
  "Bu maçtaki joker kullanımın doldu.": "You've used all your joker uses for this match.",
  "Cevap verdikten sonra joker kullanılamaz.": "Jokers can't be used after you answer.",
  "Bu soruda joker hakkını kullandın": "You've used your joker for this question",
  "Setinde Düello'da kullanılabilen joker yok.": "Your set has no jokers you can use in Duel.",
  "{k}/{t} kullanıldı": "{k}/{t} used",
  "Aynı joker en çok {n} kez, soru başına {s}.": "Same joker {n}× max, {s} per question.",
  "Maçın soruları": "Match questions",
  "Senin cevabın: {harf}": "Your answer: {harf}",
  "rakip {durum}": "opponent {durum}",
  "Aynı soru, aynı anda": "Same question, same time",
  "Maçta toplam 4 joker kullanımın var; aynı joker en çok 2 kez, bir soruda en çok 1. Soru Değiştir yalnız ikiniz de cevaplamamışken ve rakip o soruda joker kullanmamışken çalışır. Jokerin yoksa maçın içinden satın alabilirsin.": "4 joker uses per match; the same one twice at most, 1 per question. Question Swap only works while neither of you has answered and your opponent hasn't used a joker on that question. Out of a joker? Buy it mid-match.",
  "henüz yok": "none yet",
  // --- Düello Kategori Kalkanı (650) ---
  "Kategori Kalkanı": "Category Shield",
  "Kullanıldı": "Used",
  "Koru": "Shield",
  "Vazgeç": "Cancel",
  "Korumada": "Shielded",
  "Kalkanla koru": "Shield it",
  "Kalkan onayı": "Shield confirmation",
  "Korunacak kategoriyi seç": "Pick the category to shield",
  "Son {n} saniyede kalkan kullanılamaz.": "The shield can't be used in the last {n} seconds.",
  "Rakibe en az bir kategori kalmalı.": "Your opponent must have at least one category left.",
  "{ad} bir kategoriyi korumaya aldı: {kategori}": "{ad} shielded a category: {kategori}",
  "{kategori} korundu": "{kategori} shielded",
  "sen": "you",
  "rakip": "opponent",
  "Kategoriyi sırayla biriniz seçer (15 sn; dolarsa rastgele). Soru ikinize aynı anda açılır, 15 sn'niz var. Rakibin cevapladığını görürsün ama ne cevapladığını göremezsin.": "You take turns picking the category (15 s; random if time runs out). The question opens for both of you at once and you get 15 s. You'll see that your opponent answered, never what.",
  // --- Düello puan sistemi (666) ---
  "Sırayla kategori seçin, aynı soruyu aynı anda cevaplayın. Doğru bilen kategorinin yıldız puanını alır.": "Take turns picking the category and answer the same question at the same time. Whoever gets it right earns the category's star points.",
  "Düello kilitli": "Duel locked",
  "Düello'yu açmak için {n} maç daha oyna": "Play {n} more matches to unlock Duel",
  "Klasik ya da Saf Bilgi: {o}/{g} maç": "Classic or Pure Knowledge: {o}/{g} matches",
  "Klasik maç oyna": "Play a Classic match",
  "Rakibin güçlü olduğu kategori ★★★: doğru bilen 6 puan alır.": "Your opponent's strong categories are ★★★: a correct answer is worth 6 points.",
  "Doğru bilen puanı alır — saldıran da savunan da.": "Whoever answers correctly scores — picker or not.",
  "Kategori Kalkanı: maçta 2 hak, Tur 1–5 ve Tur 6–10.": "Category Shield: 2 uses per match, rounds 1–5 and 6–10.",
  "10 tur sonunda puan eşitse Altın Soru.": "Tied after 10 rounds? Golden Question.",
  "Altın Soru'ya kadar götürdün": "You took it all the way to the Golden Question",
  "Yalnız {n} puan farkla": "Only {n} points apart",
  "zayıf": "weak",
  "orta": "medium",
  "güçlü": "strong",
  "{y} yıldız, {ad} · doğru bilene {p} puan": "{y} stars, {ad} · {p} points for a correct answer",
  "Kategori Kalkanı: {n} hak": "Category Shield: {n} left",
  "Rakibin puanı: {n}": "Opponent's points: {n}",
  "Senin puanın: {n}": "Your points: {n}",
  "ALTIN SORU": "GOLDEN QUESTION",
  "Puanlar eşit. Yalnız biriniz bilirse o kazanır; ikiniz de bilir ya da bilemezseniz yeni Altın Soru gelir. Joker yok.": "Points are tied. If only one of you gets it right, they win; if you both get it right or both miss, a new Golden Question comes. No jokers.",
  "2. Kalkan hakkın Tur {n}'da açılır.": "Your 2nd shield unlocks in round {n}.",
  "Kalkan hakların bitti.": "You've used both shields.",
  "Korumada:": "Shielded:",
  "Rakip bu seçimde alamaz.": "Your opponent can't pick it this time.",
  "Kalan Kalkan hakkın: {n}": "Shields left: {n}",
  "{n} hak": "{n} left",
  "Maçta 2 ücretsiz hak: 1. hak Tur 1–5'te, 2. hak Tur 6–10'da açılır. Kullanmadığın hak kaybolmaz.": "2 free uses per match: the 1st in rounds 1–5, the 2nd opens in rounds 6–10. An unused shield carries over.",
  "bu seçim için korunsun mu?": "shield it for this pick?",
  "Rakibin gördüğü kategorilerin": "Your categories as your opponent sees them",
  "Yıldızı senin doğru oranından: ★★★ kategoride doğru bilen 6 puan alır.": "Stars come from your accuracy: a correct answer in a ★★★ category is worth 6 points.",
  "Yıldızlar rakibin kategori başarısından. Doğru bilen puanı alır — sen de rakip de.": "Stars come from your opponent's accuracy. Whoever answers correctly scores — you or them.",
  "Seçilemez": "Unavailable",
  "Doğru bilen {n} puan alır.": "A correct answer is worth {n} points.",
  "Altın Soru · joker yok": "Golden Question · no jokers",
  "Altın Soru'yu yalnız sen bildin → maçı kazandın!": "Only you got the Golden Question → you win!",
  "Altın Soru'yu yalnız rakip bildi → maçı rakip kazandı": "Only your opponent got the Golden Question → they win",
  "Eşitlik sürüyor — yeni Altın Soru geliyor.": "Still tied — another Golden Question is coming.",
  "İkiniz de doğru → ikiniz de +{n}": "Both right → both +{n}",
  "Sen doğru, rakip {r} → sen +{n}": "You're right, opponent {r} → you +{n}",
  "Sen {b}, rakip doğru → rakip +{n}": "You {b}, opponent right → opponent +{n}",
  "Sen {b}, rakip {r} → kimse puan almadı": "You {b}, opponent {r} → no points",
  "Puan tablosu": "Points table",
  "Altın Soru'da joker kullanılamaz.": "No jokers on the Golden Question.",
  "Altın Soru'yu sen bildin": "You got the Golden Question",
  "Altın Soru'yu rakip bildi": "Your opponent got the Golden Question",
  "Eşitlik sürdü": "Still tied",
  "Sen +{b} · Rakip +{r}": "You +{b} · Opponent +{r}",
  "Yıldızlı kategoriler": "Star-rated categories",
  "Maç başında her kategori, rakibin o kategorideki doğru oranına göre yıldızlanır ve maç boyunca değişmez: %45'e kadar ★ zayıf (1 puan), %70'e kadar ★★ orta (3 puan), üstü ★★★ güçlü (6 puan). Rakibin o kategoride 5'ten az cevabı varsa ★★ sayılır.": "At kick-off every category gets stars from your opponent's accuracy in it and keeps them all match: up to 45% ★ weak (1 point), up to 70% ★★ medium (3 points), above that ★★★ strong (6 points). Fewer than 5 answers in a category counts as ★★.",
  "Doğru bilen alır": "Right answer scores",
  "Saldıran ya da savunan fark etmez: soruyu doğru bilen kategorinin puanını alır. İkiniz de doğruysanız ikiniz de alırsınız, ikiniz de yanlışsanız kimse alamaz. Süre dolarsa 'Yanıtsız' sayılır.": "It doesn't matter who picked: whoever answers correctly earns the category's points. Both right, both score; both wrong, nobody does. Running out of time counts as 'No answer'.",
  "Rakip kategori seçerken kendi kategorilerinden birini o seçim için kapatırsın. Maçta 2 hakkın var ve ikisi de ücretsiz: 1. hak Tur 1–5'te, 2. hak Tur 6–10'da açılır. İlk hakkı kullanmazsan kaybolmaz; Tur 6'dan sonra iki hakkı da istediğin zaman kullanırsın.": "While your opponent picks, you can lock one of your categories for that pick. You get 2 free uses per match: the 1st in rounds 1–5, the 2nd opens in rounds 6–10. An unused 1st shield carries over, so from round 6 you can use both whenever you like.",
  "10 tur ve Altın Soru": "10 rounds and the Golden Question",
  "Maç her zaman 10 tur sürer; sonunda puanı yüksek olan kazanır. Puanlar eşitse Altın Soru gelir: zor, daha önce sorulmamış bir soru, joker yok. Yalnız biriniz bilene kadar sürer.": "A match always lasts 10 rounds; the higher score wins. If points are tied, a Golden Question follows: a hard, fresh question with no jokers. It repeats until only one of you gets it right.",
  "Rakibinin güçlü kategorisinde soru 6 puan eder: doğru bilen alır. 10 tur, eşitlikte Altın Soru.": "In your opponent's strong categories a question is worth 6 points to whoever gets it right. 10 rounds, Golden Question on a tie.",
  "10 tur": "10 rounds",
  "10 tur · aynı soru, aynı anda": "10 rounds · same question, same time",
  "{n} joker türü · 10 tur · puan": "{n} joker types · 10 rounds · points",
  // Ajan A7 (24 Eyl 2026): "Hazır mısın?" bilgi kartı
  "{0} soru": "{0} questions",
  "Soru başına 15 sn": "15 s per question",
  "Jokersiz": "No jokers",
  "Bu maçta joker yok — sadece bilgi ve hız.": "No jokers in this match — just knowledge and speed.",
  "Jokerler soru ekranının altında: 50:50 iki yanlış şıkkı eler.": "Jokers sit below the question: 50:50 removes two wrong answers.",
  "Maç bilgisi": "Match info",
  "{n} oyuncu": "{n} players",
};
