// İngilizce çeviri eki — Tasarım Adım 2, şerit "mac". Anahtar Türkçe metnin kendisidir
// (dil.js ile aynı kural). Şeritler paralel çalıştığı için her biri kendi dosyasına yazar;
// dil.js bu dosyaları SOZLUK.en'e katar (buradaki karşılık önce gelir).
export default {
  // --- Maç ekranları (M1) ---
  "{0} sorunun tamamını oynadın. {1} kendi zamanında oynayınca maç sonuçlanacak — bittiğinde sana haber vereceğiz.": "You've played all {0} questions. The match ends once {1} plays their turn — we'll let you know.",
  "{0} senden önde. Bu maç sıra beklemeden oynanır — sen kendi hızında devam et, rakibin de kendi zamanında oynar.": "{0} is ahead of you. This match isn't turn-based — play at your own pace, your opponent plays at theirs.",
  "Rakip cevapladı": "Opponent answered",
  "Doğru!": "Correct!",
  "Soru {n}": "Question {n}",
  "Adil": "Fair",
  "Adil değil": "Not fair",
  "Skill bilgileri alınamadı. Tekrar dene.": "Couldn't load your jokers. Try again.",
  "Sürene {0} saniye eklendi.": "+{0} seconds on your clock.",
  "Sorun değişti.": "New question for you.",
  "Sigorta aktif — yanlışta 5 puan korunur.": "Insurance on — you keep 5 points if you miss.",
  "2X aktif — doğru cevap 20 puan.": "2X on — a correct answer scores 20.",
  "İkinci Şans aktif.": "Second Chance on.",
  "Bu soruda skill kullanılamaz.": "Jokers are locked on this question.",
  "Turnuva finalinde skill kullanılamaz": "No jokers in the tournament final",
  "Bu maçta en fazla {0} skill": "Max {0} jokers this match",
  "Bu sorudaki skill hakkını kullandın": "You've used your joker for this question",
  "Bu skill için maç hakkın doldu": "You've used this joker up for the match",
  "Skiller şimdilik ücretsiz ve sınırsız": "Jokers are free and unlimited for now",
  "Arkadaş maçı: skill hakkın sınırsız": "Friendly match: unlimited jokers",
  "Bu maçta {0} skill hakkın kaldı": "{0} jokers left this match",
  "Maç hakkı: {0}": "Uses left: {0}",
  "Bu maçta skill hakkın doldu ({0}/{1}).": "No jokers left this match ({0}/{1}).",
  "Herkes aynı soruyu aynı anda görür. Maç hepiniz hazır olunca başlar.": "Everyone sees the same question at the same time. The match starts when you're all ready.",
  "{0}/{1} hazır": "{0}/{1} ready",
  "Beklenen: {0}": "Waiting for: {0}",
  "İstersen maçı sıra tabanlı bırak: sen kendi bölümünü şimdi oynarsın, rakibin kendi zamanında oynar.": "You can switch to turn-based: play your part now, and your opponent plays when they can.",
  "{0} oyundan ayrıldı. Maç duraklatıldı — süre işlemiyor, bu yüzden bir şey kaybetmiyorsun.": "{0} left the game. The match is paused — the clock is stopped, so you don't lose anything.",
  "{0} üst üste!": "{0} in a row!",
  "{0} karşısında {1}-{2} kazandım!": "I beat {0} {1}-{2}!",
  "Maç bitti ama oturum açık: istersen burada kalıp sohbet edebilirsin. Çıkmak sana kalmış.": "The match is over but the room stays open: stick around and chat if you like. Leave whenever you want.",
  "Maç bitti ama oturum açık: istersen burada kalıp {0} ile konuşmaya devam edebilirsin. Çıkmak sana kalmış.": "The match is over but the room stays open: keep chatting with {0} if you like. Leave whenever you want.",
  "Tamamlandı": "Done",
  "Turların: {d}/{t} doğru": "Your rounds: {d}/{t} correct",
  "{n}. soru: {durum}": "Question {n}: {durum}",
  "{n}. gün": "Day {n}",
  "Serin sürüyor": "Your streak is alive",
  "Bu maçta kullandığın skiller:": "Jokers you used this match:",
  "{n} soruyu yanlış bildin": "You missed {n} questions",
  "Hatalarım'a eklendi — tekrar çalış": "Added to My Mistakes — practice them",
  "Rütbe atladın!": "Rank up!",
  "Tamam": "OK",
  // Turnuva (M1)
  "Lobiden ayrılamadın. Tekrar dene.": "Couldn't leave the lobby. Try again.",
  "Turnuva bilgisi alınamadı": "Couldn't load the tournament",
  "Sıradaki turnuva": "Next tournament",
  "Bu haftanın ilk 3 ödülü: {ad}": "This week's top-3 prize: {ad}",
  "Turnuva lobisi": "Tournament lobby",
  "Lobiden ayrıl": "Leave lobby",
  "Lobideki oyuncular": "Players in the lobby",
  "Kendi ligim": "My league",
  "Altın soru": "Golden question",
  "{n} oyuncu başa baş — biri bilene kadar sürer": "{n} players neck and neck — it goes on until someone gets one right",
  "Canlı · {n} oyuncu hayatta": "Live · {n} players left",
  "Hayatta kalanlar": "Still standing",
  "{ad} · {n} doğru": "{ad} · {n} correct",
  "Turnuvalar her gün {saatler} saatlerinde başlar (Türkiye saati); başlamadan lobide olman gerekir.": "Tournaments start every day at {saatler} (Turkey time); you need to be in the lobby before it starts.",
  "Son kalan kazanır ve +150 lig puanı alır;": "Last one standing wins +150 league points;",
  "ilk 10'a giren ve katılan herkes de puan kazanır. Finalde skill kullanılamaz — sadece bilgi.": "the top 10 and everyone who joins earn points too. No jokers in the final — just knowledge.",
  "{n} katılımcı": "{n} players",
  "Son turnuvanın ilk üçü": "Last tournament's top three",
  "saat": "hours",
  "dakika": "minutes",
  // Grup + Hatalarım (M1)
  "Davet yanıtlanamadı. Tekrar dene.": "Couldn't answer the invite. Try again.",
  "{n}. sıra": "Place {n}",
  "Skor tablosu": "Scoreboard",
  "soru bankanda": "questions in your bank",
  "öğrenildi": "learned",
  "Çalışma · puan verilmez": "Practice · no points",
  "{n}/{t} · {k} soru kaldı": "{n}/{t} · {k} questions left",
  "bankandan · {n} kez yanlış": "from your bank · missed {n}×",
  "Bugüne kadar toplam {n} soru öğrendin. Doğru cevapların kategori ustalığına işlendi.": "You've learned {n} questions so far. Your correct answers count toward category mastery.",
  // --- Düello (M2) ---
  "Sırayla kategori seçin, aynı soruyu aynı anda cevaplayın. Yalnız biri bilirse öteki can kaybeder.": "Take turns picking the category and answer the same question at the same time. If only one of you gets it right, the other loses a life.",
  "Klasik ile aynı lig puanı ve coin ödülü": "Same league points and coin rewards as Classic",
  "Biri doğru öteki yanlış/yanıtsız → yanlış olan 1 can kaybeder; ikisi aynıysa nötr": "One right, the other wrong or out of time → they lose a life; same result → nobody does",
  "Beraberlik yok: can eşitse uzatma, kategori rastgele": "No draws: tied lives go to overtime with random categories",
  "Maçta 4 skill: aynı skill en çok 2 kez, soru başına 1": "4 jokers per match: the same one twice at most, 1 per question",
  "Aynı soruyu aynı anda cevaplarsınız.": "You both answer the same question at the same time.",
  "Rakibin ne cevapladığını göremezsin, yalnız cevapladığını görürsün.": "You never see what your opponent picked — only that they answered.",
  "Beraberlik yok: can eşitse uzatma.": "No draws: tied lives go to overtime.",
  "Kategori seçerken süre dolarsa rastgele gelir.": "Run out of time while picking and a random category comes up.",
  "UZATMA": "OVERTIME",
  "Uzatma": "Overtime",
  "Tur {n}/{t}": "Round {n}/{t}",
  "Kategoriyi seçen": "Picking the category",
  "Kategori seçme sırası sende": "Your turn to pick the category",
  "Aynı soru · aynı anda": "Same question · same time",
  "Beraberlik yok, uzatma: biri doğru öteki yanlış yapana kadar sürer.": "No draws — overtime runs until one of you is right and the other wrong.",
  "Kategori rastgele geldi: {kategori}": "Random category: {kategori}",
  "Kategori seç": "Pick a category",
  "{ad} kategori seçiyor…": "{ad} is picking a category…",
  "Süre dolarsa kategori rastgele seçilir.": "If time runs out, a random category is picked.",
  "Kategoriyi seçen taraf değişir, soruyu ikiniz aynı anda cevaplarsınız.": "You take turns picking; you both answer the same question at once.",
  "Her kategori maçta en çok {n} kez gelir; aynı kategori üst üste gelmez.": "Each category comes up at most {n} times a match, never twice in a row.",
  "doldu": "used up",
  "üst üste olmaz": "not twice in a row",
  "Rakip %{n}": "Opponent {n}%",
  "Rakip": "Opponent",
  "%{n}": "{n}%",
  "Kalan hak: {n}": "Picks left: {n}",
  "Rakip düşünüyor…": "Opponent is thinking…",
  "En güçlü kategorilerin": "Your strongest categories",
  "En zayıf kategorilerin": "Your weakest categories",
  "{n}/{m} geldi": "{n}/{m} played",
  "Kategori oranların birkaç cevaptan sonra burada görünür.": "Your category rates show up here after a few answers.",
  "Bu maçta gelenler": "Played this match",
  "Cevabın kilitlendi": "Answer locked",
  "Yanıtsız": "No answer",
  "yanıtsız": "no answer",
  "düşünüyor…": "thinking…",
  "cevapladı": "answered",
  "Cevabın kilitlendi — sonuç ikiniz de cevaplayınca açılır.": "Answer locked — the result shows once you've both answered.",
  "Süren doldu — sonuç bekleniyor.": "Time's up — waiting for the result.",
  "Sen doğru, rakip {r} → rakip 1 can kaybetti": "You're right, opponent {r} → opponent loses a life",
  "Sen {b}, rakip doğru → sen 1 can kaybettin": "You {b}, opponent right → you lose a life",
  "İkiniz de doğru → nötr, can değişmedi": "Both right → neutral, no lives lost",
  "Sen {b}, rakip {r} → nötr, can değişmedi": "You {b}, opponent {r} → neutral, no lives lost",
  "Can tablosu": "Life table",
  "Uzatmada ilk fark maçı bitirir.": "In overtime the first difference ends the match.",
  "Eşitlik sürüyor — sıradaki uzatma sorusu geliyor, kategori yine rastgele.": "Still tied — another overtime question is coming, random category again.",
  "Şık işaretlenmedi": "No option picked",
  "Soru açılınca kullanılır.": "Usable once the question opens.",
  "Bu maçtaki skill hakkın doldu.": "You've used all your jokers for this match.",
  "Cevap verdikten sonra skill kullanılamaz.": "Jokers can't be used after you answer.",
  "Bu soruda skill hakkını kullandın": "You've used your joker for this question",
  "Setinde Düello'da kullanılabilen skill yok.": "Your set has no jokers you can use in Duel.",
  "{k}/{t} kullanıldı": "{k}/{t} used",
  "Aynı skill en çok {n} kez, soru başına {s}.": "Same joker {n}× max, {s} per question.",
  "Maçın soruları": "Match questions",
  "Sen 1 can kaybettin": "You lost a life",
  "Rakip 1 can kaybetti": "Opponent lost a life",
  "Senin cevabın: {harf}": "Your answer: {harf}",
  "rakip {durum}": "opponent {durum}",
  "Aynı soru, aynı anda": "Same question, same time",
  "Kategoriyi sırayla biriniz seçer (8 sn; dolarsa rastgele). Soru ikinize aynı anda açılır, 15 sn'niz var. Rakibin cevapladığını görürsün ama ne cevapladığını göremezsin.": "You take turns picking the category (8 s; random if time runs out). The question opens for both of you at once and you get 15 s. You'll see that your opponent answered, never what.",
  "Yalnız biri doğruysa öteki 1 can kaybeder. İkiniz de doğru ya da ikiniz de yanlışsanız nötr: can değişmez. Süre dolarsa 'Yanıtsız' sayılır. 3 can, en çok 10 tur; tur iki tarafça tamamlanır.": "If only one of you is right, the other loses a life. Both right or both wrong is neutral. Running out of time counts as 'No answer'. 3 lives, up to 10 rounds; both sides always finish the round.",
  "Beraberlik yok. Can eşitse uzatma başlar: kategori rastgele gelir, biri doğru öteki yanlış yapana kadar sürer.": "No draws. Tied lives mean overtime: random categories until one of you is right and the other wrong.",
  "Maçta toplam 4 skill; aynı skill en çok 2 kez, bir soruda en çok 1. Soru Değiştir yalnız ikiniz de cevaplamamışken ve rakip o soruda skill kullanmamışken çalışır. Skill'in yoksa maçın içinden satın alabilirsin.": "4 jokers per match; the same one twice at most, 1 per question. Question Swap only works while neither of you has answered and your opponent hasn't used a joker on that question. Out of a joker? Buy it mid-match.",
  // --- Düello zayıf nokta + kategori sınırı (470, Ajan B) ---
  "henüz yok": "none yet",
  "Zayıf noktalar": "Weak spots",
  "Rakibin zayıf noktası": "Opponent's weak spot",
  "Senin zayıf noktan": "Your weak spot",
  "zayıf noktan": "your weak spot",
  "Rakip zayıf noktanı seçer ve sen bilirsen, rakip 1 can kaybeder.": "If your opponent picks your weak spot and you get it right, they lose a life.",
  "Bilirse sen can kaybedersin": "If they get it right, you lose a life",
  "Rakip zayıf noktana saldırdı!": "Your opponent attacked your weak spot!",
  "Bilirsen rakip 1 can kaybeder.": "Get it right and they lose a life.",
  "İkiniz de doğru ama rakip zayıf noktasında bildi → sen 1 can kaybettin": "Both right, but they got their weak spot → you lost a life",
  "İkiniz de doğru, zayıf noktanda bildin → rakip 1 can kaybetti": "Both right, and you got your weak spot → opponent lost a life",
  "Zayıf noktana saldırıldı": "Your weak spot was attacked",
  "Rakibin zayıf noktasına saldırdın": "You attacked your opponent's weak spot",
  "Zayıf nokta: rakibin en zayıf kategorisini seçersen ve rakip bilirse canı SEN kaybedersin": "Weak spot: pick your opponent's weakest category and if they get it right, YOU lose the life",
  "Her kategori maçta en çok 3 kez, üst üste seçilemez": "Each category up to 3 times per match, never twice in a row",
  "Rakibin zayıf noktasına saldırmak risklidir: bilirse canı sen kaybedersin.": "Attacking your opponent's weak spot is risky: if they get it right, you lose the life.",
  "Kategoriyi sırayla biriniz seçer (15 sn; dolarsa rastgele). Soru ikinize aynı anda açılır, 15 sn'niz var. Rakibin cevapladığını görürsün ama ne cevapladığını göremezsin.": "You take turns picking the category (15 s; random if time runs out). The question opens for both of you at once and you get 15 s. You'll see that your opponent answered, never what.",
  "Zayıf nokta": "Weak spot",
  "Maç başında ikinizin de en zayıf kategorisi sabitlenir ve ikinize de görünür (en az 5 cevap verdiğin kategoriler arasından doğru oranı en düşük olan; henüz yoksa zayıf noktan yok). Rakibin zayıf noktasını seçersen ve rakip bilirse canı SEN kaybedersin — sen de bilsen bile. İkiniz de yanlışsanız kimse kaybetmez; yalnız sen bilirsen rakip kaybeder. Uzatmada bu kural yok.": "At the start of the match each player's weakest category is locked in and shown to both of you (the lowest accuracy among categories with at least 5 answers; none yet means no weak spot). Pick your opponent's weak spot and if they get it right, YOU lose the life — even if you got it right too. If you're both wrong, nobody loses; if only you are right, they lose. This rule doesn't apply in overtime.",
  "Kategori sınırı": "Category limit",
  "Her kategori maçta en çok 3 kez seçilebilir (zayıf nokta dahil) ve bir önceki seçilen kategori hemen tekrar seçilemez. Seçilemeyenler soluk görünür. Süre dolunca gelen rastgele kategori rakibin zayıf noktası olmaz.": "Each category can be picked up to 3 times per match (weak spots included), and the last picked category can't be picked again right away. Unavailable ones are greyed out. When time runs out, the random category is never your opponent's weak spot.",
};
