// İngilizce çeviri eki — /ses-secim (Ajan F). Anahtar Türkçe metnin kendisidir.
// dil.js'e KATILMAZ: sayfa tembel yüklenir, metinleri ana pakete girmesin diye sayfa bu dosyayı
// kendisi okur (SesSecimPage › ts()). Ses anlarının ad/yer metinleri adaylar.js'te (adEn/yerEn).
export default {
  "Ses seçimi": "Sound picker",
  "Her an için adayları dinle, beğendiğini seç. Seçimin oyunda hemen geçerli olur (oyuncu uygulamayı bir sonraki açışında).":
    "Listen to the candidates for each moment and pick the one you like. Your pick takes effect in the game right away (the next time a player opens the app).",
  "{n} / {t} seçildi": "{n} / {t} picked",
  "Seçim ilerlemesi": "Pick progress",
  "Efektler": "Sound effects",
  "Müzik": "Music",
  "Mevcut": "Current",
  "Aday {n}": "Option {n}",
  "Şu an sessiz": "Silent now",
  "Sessiz kalsın": "Keep silent",
  "Bu anda bugün ses çalmıyor.": "No sound plays at this moment today.",
  "Çal": "Play",
  "Durdur": "Stop",
  "{ad} çal": "Play {ad}",
  "{ad} durdur": "Stop {ad}",
  "Bunu seç": "Pick this",
  "Seçildi": "Picked",
  "Seçimi kaldır": "Remove pick",
  "Seçilmedi": "Not picked",
  "Ses seviyesi": "Volume",
  "Döngü önizlemesi": "Loop preview",
  "Parça bitince baştan çalar (30 sn'lik önizleme).": "Restarts when the clip ends (30 s preview).",
  "Kaynaklar ve lisanslar": "Sources and licences",
  "Kenney sesleri CC0 (kamu malı). Pixabay sesleri ve müzikleri Pixabay İçerik Lisansı: ticari kullanım serbest, atıf gerekmez, dosyayı tek başına yeniden dağıtmak/satmak yasak.":
    "Kenney sounds are CC0 (public domain). Pixabay sounds and music use the Pixabay Content License: free for commercial use, no attribution required, redistributing or selling the file on its own is not allowed.",
  "Bu sayfa yalnız sahibe açık": "This page is only open to the owner",
  "Ses seçimini yalnız oyunun sahibi yapabilir.": "Only the game owner can pick sounds.",
  "Ana sayfaya dön": "Back to home",
  "Seçimler yüklenemedi": "Couldn't load picks",
  "Tekrar dene": "Try again",
  "Kaydedilemedi: {hata}": "Couldn't save: {hata}",
  "Ses çalınamadı": "Couldn't play the sound",
  "Kaynak": "Source",
  "Parça bitince baştan çalar (30 sn'lik önizleme; oyunda tam parça çalar).": "Restarts when the clip ends (30 s preview; the game plays the full track).",
  "{n} parça": "{n} tracks",
  "Çalma listesi": "Playlist",
  "Çalma listesi: 2–4 parça seç ve sırala. Oyun bu sırayla çalar, liste bitince başa döner; her girişte rastgele bir parçadan başlar. Tek parça seçilirse döngüde çalar.":
    "Playlist: pick 2–4 tracks and order them. The game plays them in this order and starts over at the end; each visit starts from a random track. A single track loops.",
  "{ad} yukarı taşı": "Move {ad} up",
  "{ad} aşağı taşı": "Move {ad} down",
  "{ad} listeden çıkar": "Remove {ad} from the playlist",
  "Listede · {n}": "In playlist · {n}",
  "Liste dolu": "Playlist full",
  "Listeye ekle": "Add to playlist",
};
