// İngilizce çeviri eki — SUNUCU hata mesajları (raise exception), 25 Eyl 2026 tarama (araclar/ceviri/db-tara.mjs).
// Anahtar sunucunun Türkçe mesajıdır (ttSunucu ile birebir ya da "%" kalıbıyla eşleşir); "skill" iç adı oyuncuya "joker".
// Yalnız sahibe/servise açık ekranların mesajları (kozmetik onayı, ses seçimi, soru denetimi, çeviri doğrulama) da eklendi.
export default {
  // ——— jokerler
  "Bu joker satın alınamaz": "This joker can't be bought",
  "Geçersiz skill": "Invalid joker",
  "Bu skill Düello modunda kullanılamaz": "This joker can't be used in Duel mode",
  "Bu skill bu modda kullanılamaz": "This joker can't be used in this mode",
  "Soru bilgisi gerekli": "Question info is required",
  "Bu skill artık aktif değil": "This joker is no longer active",
  "Bu skill maç setinde değil": "This joker isn't in your match loadout",
  "Bu modda skill kullanılamaz": "Jokers can't be used in this mode",
  "Bu maçtaki skill hakkın doldu": "You've used up your jokers for this match",
  "Bu skill için maç hakkın doldu": "You've used up this joker for the match",
  "Bu soruda skill hakkını kullandın": "You've already used a joker on this question",
  "En fazla % skill seçebilirsin": "You can pick at most % jokers",
  "Geçersiz skill seti": "Invalid joker set",
  "Bu skill Düello'da kullanılamaz": "This joker can't be used in Duels",
  "Skill yalnız soru açıkken kullanılır": "Jokers can only be used while a question is open",
  "Cevap verildikten sonra soru değiştirilemez": "You can't change the question after answering",
  "Rakibin bu soruda skill kullandı, soru değiştirilemez": "Your opponent used a joker on this question, so it can't be changed",
  "Bu maçta en fazla % skill kullanabilirsin": "You can use at most % jokers in this match",
  "Şu an skill kullanılamaz": "Jokers can't be used right now",
  "Savunma skilleri yalnız cevap verirken kullanılır": "Defense jokers can only be used while answering",
  "Bu saldırı skill'i artık aktif değil": "This attack joker is no longer active",
  "Saldırı skilleri yalnız Saldırı Hazırlığı sırasında kullanılır": "Attack jokers can only be used during Attack Prep",
  "Bu skill bu saldırıda zaten kullanıldı": "This joker was already used in this attack",
  "Bu skill'i bu maçta zaten kullandın": "You've already used this joker in this match",
  "Turnuva finalinde skill kullanılamaz": "Jokers can't be used in the tournament final",
  "Bu skill yalnız eş zamanlı maçta kullanılabilir": "This joker can only be used in a live match",
  "Bu kategoride değiştirilecek yeni soru kalmadı": "No new questions left to swap in this category",
  // ——— maç ve düello
  "Başka bir cevap seç": "Pick a different answer",
  "Rövanş zaten başladı": "The rematch has already started",
  "Geri çekilecek rövanş isteği yok": "There's no rematch request to withdraw",
  "Bu mod şu an kapalı": "This mode is closed right now",
  "Grup için en az 3 oyuncu gerekir": "A group needs at least 3 players",
  "Şu an uygun oyuncu yok, birazdan tekrar dene.": "No players are available right now — try again in a moment.",
  "Sorular tamamlandı": "All questions are done",
  "Bu oyuncuyla devam eden bir oyunun var, önce onu bitir.": "You already have a game in progress with this player — finish it first.",
  "Bu oyuncuyla zaten % bekleyen davetin var.": "You already have % pending invite(s) with this player.",
  "Gruba yalnız arkadaşlarını ve botlarını çağırabilirsin.": "You can only invite your friends and bots to a group.",
  "% ile zaten 2 bekleyen davetin var.": "You already have 2 pending invites with %.",
  "Devam eden bir düello var": "There's already a duel in progress",
  "Bu oyuncuyla bekleyen bir düello davetin zaten var": "You already have a pending duel invite with this player",
  "Bu davet sana ait değil": "This invite isn't yours",
  "Davet zaten yanıtlanmış": "This invite has already been answered",
  "Yalnız bot için": "For bots only",
  "Yalnız Düello 1.0 maçı": "Duel 1.0 matches only",
  // ——— kozmetik, çerçeve, avatar, rozet
  "Böyle bir kozmetik yok": "That cosmetic doesn't exist",
  "Bu kozmetik satılmıyor": "This cosmetic isn't for sale",
  "Bu kozmetik zaten sende": "You already own this cosmetic",
  "Bu tür takılmaz": "This type can't be equipped",
  "Bu çerçeve sende yok": "You don't own this frame",
  "Bu çerçeveyi henüz kazanmadın": "You haven't earned this frame yet",
  "Bu aura şu an kullanılamıyor": "This background isn't available right now",
  "Bu avatar henüz kullanılamıyor": "This avatar isn't available yet",
  "Bu hazır avatar artık kullanılamıyor": "This preset avatar is no longer available",
  "Bu avatar bedava — satın alınmaz": "This avatar is free — it can't be bought",
  "Böyle bir avatar yok": "That avatar doesn't exist",
  "Vitrine en fazla % rozet konabilir": "You can showcase at most % badges",
  "Vitrine yalnız kazandığın rozetleri koyabilirsin": "You can only showcase badges you've earned",
  "Geçersiz kaynak": "Invalid source",
  // ——— satın alma ve reklam
  "Kullanıcı gerekli": "User is required",
  "Satın alma jetonu gerekli": "Purchase token is required",
  "Satın alma kaydı çakıştı, tekrar dene": "The purchase record conflicted — try again",
  "Bu satın alma başka bir hesaba ait": "This purchase belongs to another account",
  "Bu sipariş başka bir jetonla işlendi": "This order was processed with a different token",
  "Bu satın alma iade edilmiş": "This purchase has been refunded",
  "Coin hesaba yazılamadı": "The coins couldn't be credited",
  "Geçersiz reklam jetonu": "Invalid ad token",
  "Reklam tamamlanmadan ödül alınamaz": "You can't claim the reward before the ad finishes",
  "Reklam jetonunun süresi doldu": "The ad token has expired",
  // ——— bildirim listesi (bildirimler.metin Türkçe saklanır; ttSunucu "%" kalıbıyla çevirir — push_metinleri EN şablonlarıyla aynı anlam)
  "% davetinle katıldı! Level % ulaşınca +% coin kazanacaksın.": "% joined with your invite! You'll earn +%3 coins when they reach Level %2.",
  "% Level % ulaştı! +% coin": "% reached Level %2! +%3 coins",
  "% sana mesaj attı.": "% sent you a message.",
  "🏆 % Şampiyonu oldun! Unvanın bu hafta profilinde ve maçlarda görünecek.": "🏆 You are the Champion of %! Your title will appear on your profile and in matches this week.",
  "🏆 Dünya Şampiyonu oldun! Unvanın bu hafta profilinde ve maçlarda görünecek.": "🏆 You are the World Champion! Your title will appear on your profile and in matches this week.",
  "Büyük turnuva 20:00'de başlıyor. Lobideki yerini al! 🏆": "The big tournament starts at 20:00. Grab your spot in the lobby! 🏆",
  "Turnuva 14:00'te başlıyor. Lobideki yerini al! 🏆": "The tournament starts at 14:00. Grab your spot in the lobby! 🏆",
  // ——— katalog metinleri (paket adları, eşya)
  "10 × Soru Değiştir": "10 × Swap Question",
  "10 × Sigorta": "10 × Insurance",
  "10 × Zaman Baskısı": "10 × Time Pressure",
  "10 × İkinci Şans": "10 × Second Chance",
  "10 × Ek Süre": "10 × Extra Time",
  "10 hak": "10 uses",
  "Papyon": "Bow Tie",
  // ——— yalnız sahibe / servise açık (kozmetik onayı, ses seçimi, denetim, çeviri doğrulama)
  "Bu sayfa yalnız sahibe açık": "This page is owner-only",
  "Geçersiz seçim": "Invalid choice",
  "Böyle bir kalem yok": "No such item",
  "Geçersiz konu": "Invalid topic",
  "Geçersiz çerçeve tarzı": "Invalid frame style",
  "Geçersiz ses anı": "Invalid sound moment",
  "Geçersiz aday": "Invalid candidate",
  "Çalma listesi yalnız müzik anlarında": "Playlists are for music moments only",
  "Çalma listesi en çok 4 parça": "A playlist can have at most 4 tracks",
  "Aynı parça iki kez eklenemez": "The same track can't be added twice",
  "Kayıtlar dizi olmalı": "Records must be an array",
  "Çeviri: soru bulunamadı (%)": "Translation: question not found (%)",
  "Çeviri: kaynak dil (%) çeviri olarak yazılamaz": "Translation: the source language (%) can't be saved as a translation",
  "Çeviri: secenekler dizi olmalı": "Translation: options must be an array",
  "Çeviri: şık sayısı kaynakla aynı olmalı (% ≠ %)": "Translation: the number of options must match the source (% ≠ %)",
  "Çeviri: soru metni boş olamaz": "Translation: question text can't be empty",
  "Çeviri: % numaralı şık boş": "Translation: option # % is empty",
  "Çeviri: şıklar birbirinden farklı olmalı": "Translation: options must be different from each other",
  "Çeviri: dogru_cevap indeksi şık sayısının dışında": "Translation: the correct-answer index is out of range",
};
