// İngilizce çeviri eki — Tasarım Adım 2, şerit "tasarim". Anahtar Türkçe metnin kendisidir
// (dil.js ile aynı kural). Şeritler paralel çalıştığı için her biri kendi dosyasına yazar;
// dil.js bu dosyaları SOZLUK.en'e katar (buradaki karşılık önce gelir).
// İçerik: oyun/tasarim/ bileşenlerinin iç metinleri + /tasarim-sistemi örnek sayfası.
export default {
  // ——— Bileşen iç metinleri (oyun/tasarim/*.jsx) ———
  "Quiz Tactics ana sayfa": "Quiz Tactics home",
  "Ana menü": "Main menu",
  "Alt menü": "Bottom menu",
  "Bildirimler": "Notifications",
  "Profil menüsü": "Profile menu",
  "Kapat": "Close",
  "{ad} ({sayi} yeni)": "{ad} ({sayi} new)",
  "Seviye {n}": "Level {n}",
  "Çevrimiçi": "Online",
  "{n} coin": "{n} coins",
  "{n} adet": "{n} left",
  "Bronz": "Bronze",
  "Gümüş": "Silver",
  "Altın": "Gold",
  "Elmas": "Diamond",
  "Efsane": "Legend",
  "Elendi": "Eliminated",
  "Şıklar": "Answers",
  "— seçildi": "— selected",
  "— doğru": "— correct",
  "— doğru cevap": "— correct answer",
  "— yanlış": "— wrong",
  "— elendi": "— eliminated",
  "Kalan süre {sn} saniye": "{sn} seconds left",
  "Can": "Lives",
  "{ad}: {dolu} / {toplam} can": "{ad}: {dolu} / {toplam} lives",
  "Senin canın": "Your lives",
  "Rakibin canı": "Opponent's lives",
  "Skill'ler": "Skills",
  "etkin": "active",
  "kullanıldı": "used",
  "kilitli": "locked",
  "Skor: sen {a}, rakip {b}": "Score: you {a}, opponent {b}",
  "Sen": "You",

  // ——— /tasarim-sistemi örnek sayfası ———
  "Tasarım Sistemi": "Design System",
  "Yön A “Şeker Kutusu”: parlak, yuvarlak, kabartmalı. Bütün ekranlar bu sayfadaki token'lar ve bileşenlerle kurulur. Kılavuz: oyun/tasarim/OKU.md":
    "Direction A “Candy Box”: bright, round, raised. Every screen is built from the tokens and components on this page. Guide: oyun/tasarim/OKU.md",
  "Bölümler": "Sections",
  "Renkler": "Colors",
  "Kontrast": "Contrast",
  "Yazı": "Type",
  "Ölçüler": "Measures",
  "İkonlar": "Icons",
  "Düğmeler": "Buttons",
  "Kartlar": "Cards",
  "Küçük parçalar": "Small parts",
  "Liste ve durumlar": "Lists and states",
  "Modal ve bildirim": "Modal and toast",
  "Maç": "Match",
  "Üst çubuk ve menü": "Top bar and menu",
  "Her renk bir rol taşır. Altın yalnız coin ve ödül içindir; mod ve lig renkleri her yerde aynı anlama gelir.":
    "Every color has a role. Gold is only for coins and rewards; mode and league colors mean the same thing everywhere.",
  "WCAG AA: küçük yazı ≥ 4,5 · büyük yazı ≥ 3. Değerler bu sayfanın CSS'inden canlı hesaplanır.":
    "WCAG AA: small text ≥ 4.5 · large text ≥ 3. Values are computed live from this page's CSS.",
  "Baloo 2 başlık ve sayılar, Nunito gövde. Rakamlar eş genişlikli; en küçük yazı 12 px.":
    "Baloo 2 for headings and numbers, Nunito for body. Tabular digits; smallest text 12 px.",
  "4 px ızgara. Kabartma: düğme ve kartların altındaki renkli dudak; basınca o kadar aşağı iner.":
    "4 px grid. Relief: the colored lip under buttons and cards; pressing sinks by that much.",
  "Tek set: 24 px ızgara, 2,4 px yuvarlak çizgi, yarı saydam dolgu. Eski Ikon.jsx'teki bütün adlar aynen var.":
    "One set: 24 px grid, 2.4 px round stroke, translucent fill. Every name from the old Ikon.jsx is kept.",
  "Ekranda tek birincil (turuncu) eylem. Basınca dudak kadar aşağı iner (120 ms).":
    "One primary (orange) action per screen. Pressing sinks it by its lip (120 ms).",
  "Kart iç içe konmaz. Mod kartının rengi o modun her yerdeki rengidir.":
    "Cards are never nested. A mode card's color is that mode's color everywhere.",
  "Modal ve alt sayfa body'ye çizilir; Esc ve örtü kapatır. Bildirim üstte belirir, 3 sn sonra kendiliğinden kalkar.":
    "Modals and sheets render into body; Esc and the backdrop close them. Toasts appear on top and leave after 3 s.",
  "Koyu mor sahne (.qt-sahne-mac). Düğmelerle anları dene: doğru, yanlış, son 5 sn, 50:50, skill'ler.":
    "Dark purple stage (.qt-sahne-mac). Try the moments with the buttons: correct, wrong, last 5 s, 50:50, skills.",
  "Üst çubuk bu sayfanın en üstünde canlı. Alt menü telefonda ekranın altına sabitlenir (sabit); burada yerinde gösteriliyor.":
    "The top bar is live at the top of this page. On phones the bottom menu is pinned to the screen (sabit); here it is shown in place.",
  "Zemin ve yüzey": "Background and surface",
  "Vurgu": "Accent",
  "Durum": "Status",
  "Modlar": "Modes",
  "Ligler": "Leagues",
  "Maç sahnesi": "Match stage",
  "Çift": "Pair",
  "Örnek": "Sample",
  "Oran": "Ratio",
  "geçer": "passes",
  "kalır": "fails",
  "Sayfa yazısı / zemin": "Page text / background",
  "Soluk yazı / zemin": "Muted text / background",
  "Soluk yazı / zemin-2": "Muted text / background-2",
  "Gövde / yüzey": "Body / surface",
  "Soluk / yüzey": "Muted / surface",
  "Soluk / yüzey-2": "Muted / surface-2",
  "Soluk / yüzey-3 (devre dışı)": "Muted / surface-3 (disabled)",
  "Birincil düğme": "Primary button",
  "Mor düğme / seçili": "Purple button / selected",
  "Mor yazı / yüzey": "Purple text / surface",
  "Mor yazı / mor açık": "Purple text / light purple",
  "Doğru şık": "Correct answer",
  "Yeşil yazı / yüzey": "Green text / surface",
  "Yeşil yazı / yeşil açık": "Green text / light green",
  "Yanlış şık / tehlike düğmesi": "Wrong answer / danger button",
  "Kırmızı yazı / yüzey": "Red text / surface",
  "Kırmızı yazı / kırmızı açık": "Red text / light red",
  "Uyarı": "Warning",
  "Uyarı yazısı / uyarı açık": "Warning text / light warning",
  "Bilgi": "Info",
  "Bilgi yazısı / bilgi açık": "Info text / light info",
  "Coin hapı": "Coin pill",
  "Coin yazısı / coin açık": "Coin text / light coin",
  "Gövde / vurgu açık": "Body / light accent",
  "Mod: Klasik": "Mode: Classic",
  "Mod: Düello": "Mode: Duel",
  "Mod: Turnuva": "Mode: Tournament",
  "Mod: Grup": "Mode: Group",
  "Mod: Saf Bilgi": "Mode: Pure Knowledge",
  "Lig: Bronz": "League: Bronze",
  "Lig: Gümüş": "League: Silver",
  "Lig: Altın": "League: Gold",
  "Lig: Elmas": "League: Diamond",
  "Lig: Efsane": "League: Legend",
  "Maç yazısı / maç zemini": "Match text / match background",
  "Maç soluk / maç zemini": "Match muted / match background",
  "Maç soluk / maç zemini 2": "Match muted / match background 2",
  "44 · 3:2": "44 · 3:2",
  "Maç sonu": "Match over",
  "Arkadaşlar": "Friends",
  "Güneş'e en yakın gezegen hangisidir?": "Which planet is closest to the Sun?",
  "Merkür · Düğme · Şık": "Mercury · Button · Answer",
  "Gövde yazısı: kısa, net, oyuncunun dilinde.": "Body text: short, clear, in the player's words.",
  "İkincil bilgi · 2g 14s kaldı": "Secondary info · 2d 14h left",
  "ROZET · ALT MENÜ": "BADGE · BOTTOM MENU",
  "Boşluk": "Spacing",
  "Köşe ve kabartma": "Radius and relief",
  "yüzen": "floating",
  "Oyna": "Play",
  "Meydan oku": "Challenge",
  "Vazgeç": "Cancel",
  "Sil": "Delete",
  "Daha sonra": "Later",
  "Küçük": "Small",
  "Orta": "Medium",
  "Büyük": "Large",
  "Devre dışı": "Disabled",
  "Yükleniyor": "Loading",
  "Ayarlar": "Settings",
  "Paylaş": "Share",
  "Hemen oyna": "Play now",
  "Klasik": "Classic",
  "Düello": "Duel",
  "Turnuva": "Tournament",
  "Grup": "Group",
  "1'e 1 · 10 soru": "1 vs 1 · 10 questions",
  "Can savaşı · skill'li": "Battle of lives · with skills",
  "Sıradaki 20:00": "Next at 20:00",
  "3-5 kişi · davetle": "3-5 players · by invite",
  "Canlı": "Live",
  "Saf Bilgi": "Pure Knowledge",
  "Skillsiz · yalnız bilgi": "No skills · knowledge only",
  "Yeni": "New",
  "Hızlı Mod": "Quick Mode",
  "Şu an kapalı": "Closed for now",
  "Kart": "Card",
  "Beyaz levha, 5 px alt dudak.": "White panel, 5 px bottom lip.",
  "Mor kart": "Purple card",
  "Davet, öne çıkan bilgi.": "Invites, highlighted info.",
  "Kart dokunuldu": "Card tapped",
  "Dokunulur kart": "Tappable card",
  "onClick verince düğme olur.": "Becomes a button when given onClick.",
  "Rozet": "Badge",
  "Nötr": "Neutral",
  "Level 7": "Level 7",
  "6 gün seri": "6-day streak",
  "Kazandın": "You won",
  "Kaybettin": "You lost",
  "Son 1 saat": "Last hour",
  "Serbest": "Casual",
  "YENİ": "NEW",
  "Çip ve sekme": "Chip and tabs",
  "Bilim": "Science",
  "Tarih": "History",
  "Spor": "Sports",
  "Sanat": "Art",
  "Dükkân": "Shop",
  "Kıyafet": "Outfits",
  "Anahtar ve ilerleme": "Switch and progress",
  "Dereceli": "Ranked",
  "Lig puanı + tam coin": "League points + full coins",
  "Lig puanı yok · coin %50": "No league points · 50% coins",
  "Seviye 24 için 320 XP": "320 XP to level 24",
  "Seviye ilerlemesi": "Level progress",
  "Altın Lig · yükselme hattı": "Gold League · promotion line",
  "Lig ilerlemesi": "League progress",
  "Avatar ve coin": "Avatar and coins",
  "Altın Lig · 1.240 puan": "Gold League · 1,240 points",
  "Meydan okuma gönderildi": "Challenge sent",
  "4. sıra": "4th place",
  "Günlük ödül": "Daily reward",
  "Yarın yine gel": "Come back tomorrow",
  "Henüz arkadaşın yok": "No friends yet",
  "Davet kodunu paylaş; ikiniz de 200 coin kazanın.": "Share your invite code; you both get 200 coins.",
  "Davet et": "Invite",
  "Yüklenemedi": "Couldn't load",
  "Bağlantını kontrol edip yeniden dene.": "Check your connection and try again.",
  "Yeniden dene": "Try again",
  "Yükleniyor iskeleti": "Loading skeleton",
  "Modal aç": "Open modal",
  "Alt sayfa aç": "Open sheet",
  "Kazandın!": "You won!",
  "+120 coin · +40 lig puanı": "+120 coins · +40 league points",
  "Başarı": "Success",
  "Bağlantı koptu": "Connection lost",
  "Yeniden bağlanıyor…": "Reconnecting…",
  "Hata": "Error",
  "Mert seni Düello'ya çağırıyor": "Mert challenges you to a Duel",
  "2 dk içinde yanıtla": "Reply within 2 min",
  "Kabul": "Accept",
  "Turnuva 5 dk sonra başlıyor": "Tournament starts in 5 min",
  "Dükkân › Coin": "Shop › Coins",
  "Coin hapı Dükkân'a götürür.": "The coin pill leads to the Shop.",
  "3 yeni bildirim": "3 new notifications",
  "Hareket örnekleri": "Motion samples",
  "Doğru cevap": "Correct answer",
  "Yanlış cevap": "Wrong answer",
  "Son 5 saniye": "Last 5 seconds",
  "50:50 kullan": "Use 50:50",
  "Rakibe baskı": "Pressure opponent",
  "Sıfırla": "Reset",
  "Sigorta etkin": "Insurance active",
  "2 Kat etkin": "Double active",
  "İkinci Şans etkin": "Second Chance active",
  "İkinci Şans: bir hakkın daha var!": "Second Chance: you get one more try!",
  "Sigorta canını korudu.": "Insurance saved your life.",
  "{ad} kilitli": "{ad} is locked",
  "Seviye 10'da açılır.": "Unlocks at level 10.",
  "{ad} kullanıldı": "{ad} used",
  "Rakibin süresi 5 saniye kısaldı.": "Opponent's time cut by 5 seconds.",
  "Doğru! +{n} puan": "Correct! +{n} points",
  "Yanlış — doğrusu {c}": "Wrong — it was {c}",
  "Süre doldu": "Time's up",
  "Soru {n} / {t}": "Question {n} / {t}",
  "Coğrafya": "Geography",
  "Türkiye'nin en yüksek dağı hangisidir?": "What is the highest mountain in Türkiye?",
  "Venüs": "Venus",
  "Merkür": "Mercury",
  "Mars": "Mars",
  "Dünya": "Earth",
  "Erciyes": "Erciyes",
  "Uludağ": "Uludağ",
  "Ağrı Dağı": "Mount Ararat",
  "Süphan Dağı": "Mount Süphan",
  "Şık durumları": "Answer states",
  "Normal": "Normal",
  "Seçili": "Selected",
  "Doğru": "Correct",
  "Doğrusu buydu": "This was correct",
  "Yanlış": "Wrong",
  "Kilitli": "Locked",
  "Solgun": "Faded",
  "Sigorta": "Insurance",
  "2 Kat": "Double",
  "Baskı": "Pressure",
  "Alt menü örneği": "Bottom menu sample",
  "Ana Sayfa": "Home",
  "bekleyen istek var": "pending requests",
  "Lig": "League",
  "Profil": "Profile",
  "50:50 satın al": "Buy 50:50",
  "İki yanlış şıkkı kırıp atar. Bu maçta 1 kez daha kullanabilirsin.": "Breaks away two wrong answers. You can use it once more this match.",
  "50:50 alındı": "50:50 bought",
  "40 coin": "40 coins",
  "Tek adet": "Single",
  "Hemen kullan": "Use now",
  "10'lu paket": "Pack of 10",
  "%20 indirim": "20% off",
  "Profilim": "My profile",
  "Dil": "Language",
  "Çıkış yap": "Log out",
};
