-- ============================================================
-- 1059 — soru_parti_codex_04 (stil: docs/SORU_STIL_PROFILI.md): 200 soru · 2026-10-10
--
-- Kategori: edebiyat 19 · genel_kultur 36 · muzik 16 · sanat 27 · sinema 20 · spor 23 · tarih 30 · teknoloji 29
-- Yerel (kapsam='yerel', ulke='TR'): 0 · zorluk 1–5: 0/140/60/0/0
-- İngilizce çeviri: 200 · çevrilmeyen (ceviri_atlanan, kod 'cevrilemez'): 0
--
-- Kalite: Codex yazımı; codex-kapi.mjs kapı 1–5 (TR/EN biçim ve şık denge,
-- havuz/parti birebir ve Jaccard tekrar, cevap soruda değil, DB kural kapısı,
-- Jev şık ipucu p ≤ 0,75 ve tek doğru yanlış şık p < 0,5).
-- Claude API kullanılmadı. Son Claude incelemesi AYRI; bekleyen SQL onaysız UYGULANMAZ.
--
-- Sıra: sorular doğru şık 0'da eklenir, çeviriler aynı sırayla yazılır, sonunda YALNIZ
-- bu işlemde eklenen satırların şıkları karıştırılır — TR ve EN AYNI permütasyonla
-- (dogru_cevap indeksi ortak olduğu için şart). `created_at >= transaction_timestamp()`
-- koşulu ZORUNLUDUR; onsuz tüm havuz karışır ve oynanan maçlarda indeks kayar.
-- Üretici: node araclar/soru-uretim/uret-migration-parti.mjs --parti 4 --no 1059 --klasor codex-04 --ad soru_parti_codex_04 --codex --bekleyen --yerel
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori, kapsam, ulke, zorluk) values
('Frida Kahlo''nun evlendiği duvar ressamı kimdir?', '["Diego Rivera","José Clemente Orozco","David Alfaro Siqueiros","Rufino Tamayo"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Kuğu Gölü''nde siyah kuğu olarak bilinen Odile, hangi beyaz kuğunun karşıtıdır?', '["Odette","Aurora","Giselle","Swanilda"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Jeff Koons''un ''Balloon Dog'' heykellerinin parlak yüzeyi hangi malzemeden yapılmıştır?', '["Paslanmaz çelik","Krom kaplı bronz","Parlatılmış alüminyum","Nikel kaplı bakır"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Antik ''Semadirek Kanatlı Zaferi'' heykelinde figürün hangi vücut bölümü eksiktir?', '["Baş","Gövde","Bel","Sırt"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Renkli kâğıt kesmeleriyle yaptığı ''Mavi Nü'' serisinin sanatçısı kimdir?', '["Henri Matisse","Pablo Picasso","Georges Braque","Fernand Léger"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Ben ve Köy'' tablosunu yapan ressam kimdir?', '["Marc Chagall","Wassily Kandinsky","Paul Klee","Kazimir Malevich"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Grant Wood''un ''Amerikan Gotiği'' tablosunda adam elinde ne tutar?', '["Dirgen","Kürek","Orak","Baltalı değnek"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Jan van Eyck''in ''Arnolfini Portresi''nde çiftin ayaklarının önündeki hayvan nedir?', '["Köpek","Kedi","Tavşan","Gelincik"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Gaudí''nin Sagrada Família''sındaki sütunlar içeride hangi doğal biçimi andıracak şekilde dallanır?', '["Ağaç","Mercan","Dağ","Dalga"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Londra''daki The Shard gökdeleninin cephesindeki baskın malzeme hangisidir?', '["Cam","Tuğla","Granit","Ahşap"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Milton Glaser''ın ''I Love NY'' logosunda love sözcüğü yerine hangi şekil vardır?', '["Kalp","Yıldız","Elma","Çiçek"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Andy Warhol''un ünlü konserve kutusu serisinde hangi ürünün ambalajı yer alır?', '["Çorba","Fasulye","Ton balığı","Meyve kompostosu"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Sahne müzikali ''Operadaki Hayalet''te Christine Daaé''nin sanatsal işi nedir?', '["Şarkıcılık","Ressamlık","Heykeltıraşlık","Fotoğrafçılık"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Sahne müzikali ''Sefiller''de Jean Valjean hangi yiyeceği çaldığı için hapsedilir?', '["Ekmek","Peynir","Elma","Kurutulmuş et"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Velázquez''in ''Nedimeler'' tablosunda ressam kendi elinde ne tutar?', '["Fırça ve palet","Kalem ve defter","Çekiç ve keski","Makas ve kumaş"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Rodin''in ''Düşünen Adam''ı çenesini neyin üzerine dayar?', '["Eli","Dizi","Koltuğun kolu","Kitap"]'::jsonb, 0, 'sanat', 'global', null, 2),
('LOVE yazısının O harfini eğik yerleştiren ünlü heykellerin sanatçısı kimdir?', '["Robert Indiana","Roy Lichtenstein","Jasper Johns","Claes Oldenburg"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Bilbao Guggenheim Müzesi''nin kıvrımlı dış cephesindeki metal kaplama hangisidir?', '["Titanyum","Alüminyum","Bakır","Paslanmaz çelik"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Prag''daki Dans Eden Ev''in iki kulesine Fred ile hangi dansçının adı verilmiştir?', '["Ginger Rogers","Cyd Charisse","Rita Hayworth","Ann Miller"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Brancusi''nin MoMA''daki ''Uzayda Kuş'' heykeli hangi malzemedendir?', '["Bronz","Ahşap","Çelik","Mermer"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Boccioni''nin ''Uzayda Sürekliliğin Benzersiz Biçimleri'' heykelinin bilinen dökümleri hangi malzemedendir?', '["Bronz","Bakır","Alüminyum","Demir"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Georgia O''Keeffe''in evlendiği fotoğrafçı kimdir?', '["Alfred Stieglitz","Edward Steichen","Alfred Eisenstaedt","Edward Weston"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Picasso''nun ''Guernica''sı 1937''de hangi etkinlikteki İspanya pavyonu için yapıldı?', '["Paris Dünya Sergisi","Venedik Bienali","Berlin Olimpiyatları","Londra Dünya Sergisi"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Ai Weiwei''nin Tate Modern''deki ''Sunflower Seeds'' yerleştirmesinin taneleri hangi malzemedendir?', '["Porselen","Pişmiş toprak","Dökme bronz","Renkli cam"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Manet''nin ''Olympia'' tablosundaki yatan kadın için poz veren model kimdir?', '["Victorine Meurent","Berthe Morisot","Suzanne Valadon","Jeanne de Tourbey"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Diego Rivera''nın Rockefeller Center''daki duvar resminde hangi Sovyet liderin portresi kriz çıkarmıştı?', '["Lenin","Stalin","Troçki","Buharin"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Géricault''nun ''Medusa''nın Salı'' tablosundaki kazazedeler hangi taşıtın kazasından kurtulmuştur?', '["Fırkateyn","Korvet","Yük gemisi","Balıkçı teknesi"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Nevermind'' albümü hangi gruba aittir?', '["Nirvana","The Who","Genesis","Eagles"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Don Giovanni'' operasını kim bestelemiştir?', '["Wolfgang Amadeus Mozart","Christoph Willibald Gluck","Gioachino Rossini","Gaetano Donizetti"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Come Together'' şarkısı ilk olarak hangi albümde yayımlandı?', '["Abbey Road","Rubber Soul","Let It Be","Revolver"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Queen''in ''Bohemian Rhapsody'' şarkısında adı geçen astronom hangisidir?', '["Galileo","Copernicus","Kepler","Ptolemy"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Konser filmi ''Stop Making Sense'' hangi grubun performansını gösterir?', '["Talking Heads","The B-52''s","Blondie","The Pretenders"]'::jsonb, 0, 'muzik', 'global', null, 2),
('B. B. King''in ''Lucille'' adıyla tanınan çalgısı hangisidir?', '["Gitar","Keman","Trompet","Saksafon"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Debbie Harry hangi grubun solistidir?', '["Blondie","The Pretenders","Siouxsie and the Banshees","The Go-Go''s"]'::jsonb, 0, 'muzik', 'global', null, 2),
('KISS grubunun sahne yüzlerinde kullandığı baskın makyaj renkleri hangileridir?', '["Siyah-beyaz","Kırmızı-sarı","Mavi-yeşil","Mor-turuncu"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Michael Jackson''ın ''Thriller'' kaydındaki korku dolu konuşmayı hangi oyuncu seslendirir?', '["Vincent Price","Christopher Lee","Peter Cushing","Boris Karloff"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Chuck Berry''nin sahnede çömelerek ileri hareket ettiği ünlü hareket nasıl anılır?', '["Duck walk","Moonwalk","Chicken dance","Crab walk"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Dire Straits''in ''Money for Nothing'' kaydındaki ''I want my MTV'' bölümünü kim söyler?', '["Sting","Bono","Peter Gabriel","Phil Collins"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''99 Luftballons'' şarkısını söyleyen Alman şarkıcı kimdir?', '["Nena","Sandra","C. C. Catch","Kim Wilde"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Johnny Cash''in yorumladığı ''Hurt'' parçası ilk olarak hangi grubun eseriydi?', '["Nine Inch Nails","Soundgarden","Alice in Chains","Stone Temple Pilots"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Rolling Stones''un ''Exile on Main St.'' kayıtlarının önemli bölümü hangi tür mekânda yapıldı?', '["Bir villanın bodrumu","Bir kilisenin ana salonu","Bir okulun spor salonu","Bir tren garının holü"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Frank Sinatra''nın ''My Way'' şarkısının İngilizce sözlerini kim yazdı?', '["Paul Anka","Neil Sedaka","Burt Bacharach","Hal David"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Radiohead kurulurken kullandığı ilk ad hangisiydi?', '["On a Friday","The Quarrymen","The High Numbers","The New Yardbirds"]'::jsonb, 0, 'muzik', 'global', null, 3),
('İlk iPad hangi yıl piyasaya çıktı?', '["2010","2009","2011","2013"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nintendo Game Boy hangi yıl piyasaya çıktı?', '["1989","1987","1988","1991"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk Sony Walkman hangi yıl piyasaya çıktı?', '["1979","1977","1978","1981"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk ticari müzik CD''leri Japonya''da hangi yıl satışa sunuldu?', '["1982","1980","1981","1983"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Motorola RAZR V3 telefonu açıldığında kullanıcı hangi tür klavyeyle karşılaşırdı?', '["Sayısal tuş takımı","Tam QWERTY klavye","Dokunmatik klavye","Döner numara diski"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk iPod shuffle modelinde diğer iPod''lardan farklı olarak hangi parça yoktu?', '["Ekran","Kulaklık bağlantısı","Fiziksel tuşlar","USB bağlantısı"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Android 4.4 sürümünün tatlı adı hangisiydi?', '["KitKat","Jelly Bean","Ice Cream Sandwich","Lollipop"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Twitter''ın eski logosundaki hayvan hangisiydi?', '["Kuş","Tilki","Balina","Kelebek"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Uzunçalar plaklarla ilişkilendirilen standart dönüş hızı hangisidir?', '["33⅓ devir","45 devir","78 devir","16⅔ devir"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Commodore 64 adındaki sayı cihazın hangi özelliğine gönderme yapar?', '["Bellek kapasitesi","İşlemci hızı","Ekran çözünürlüğü","Klavye tuş sayısı"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('3,5 inç disketin önündeki metal parça kullanımda nasıl hareket eder?', '["Yana kayar","Dışarı döner","Yukarı kalkar","Tamamen çıkar"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nokia 3310''un ekranı renk bakımından hangi türdeydi?', '["Tek renkli","Tam renkli","Üç renkli","Renkli e-mürekkep"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Klasik BlackBerry Curve telefonlarda gezinmek için ortada hangi küçük kontrol vardı?', '["Trackball","Touchpad","Joystick","Scroll wheel"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Dyson Air Multiplier masa vantilatörünün hava çıkışı hangi biçimdedir?', '["Halka","Kare","Üçgen","Yıldız"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('1984 Macintosh reklamında ekrana fırlatılan nesne nedir?', '["Balyoz","Beyzbol sopası","Yangın tüpü","Metal sandalye"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Pixar''ın Luxo Jr. kısa filmindeki başkahraman hangi ev eşyasıdır?', '["Masa lambası","Çalar saat","Tavan vantilatörü","Elektrikli süpürge"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk Macintosh farelerinde kaç ana tıklama düğmesi vardı?', '["1","2","3","4"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('IBM''in 1981 tarihli ilk kişisel bilgisayarında hangi Intel işlemcisi vardı?', '["8088","8086","80186","80286"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Sony PSP oyunlarının satıldığı küçük optik disk biçiminin kısa adı nedir?', '["UMD","MiniDisc","DVD","Blu-ray"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Twitter''ın 2006''da başlayan ilk döneminde bir paylaşımın karakter sınırı kaçtı?', '["140","120","160","180"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nintendo Wii''nin hareket kumandasının yanına bağlanan küçük yardımcı kumandanın adı nedir?', '["Nunchuk","DualShock","Joy-Con","Sixaxis"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('PowerPoint''i Microsoft satın almadan önce geliştiren şirket hangisidir?', '["Forethought","WordPerfect","Ashton-Tate","Borland"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Amazon''un Kindle''ından önceki e-kitap okuyucu ''Rocket eBook''u hangi şirket geliştirdi?', '["NuvoMedia","SoftBook Press","Palm Computing","Sony Electronics"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Nintendo''nun NES Zapper aksesuarı hangi nesne biçimindeydi?', '["Tabanca","Direksiyon","Boks eldiveni","Davul çubuğu"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('James Webb teleskobunun ana aynasında kaç altıgen parça vardır?', '["18","16","20","24"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Çin''in insanlı uzay kapsülü serisinin adı nedir?', '["Shenzhou","Tianzhou","Chang''e","Tianwen"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Nintendo GameCube kasasının arkasındaki belirgin taşıma parçası nedir?', '["Kulp","Omuz askısı","Tekerlek","Deri kayış"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('İlk iPod reklam kampanyaları hangi renk kulaklık kablosuyla özdeşleşti?', '["Beyaz","Siyah","Kırmızı","Gri"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Apple''ın Lisa bilgisayarı Steve Jobs''ın hangi yakınının adını taşır?', '["Kızı","Annesi","Kız kardeşi","Büyükannesi"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Rafael Nadal hangi spor dalıyla tanınır?', '["Tenis","Yüzme","Kayak","Ragbi"]'::jsonb, 0, 'spor', 'global', null, 2),
('Marta Vieira da Silva hangi spor dalıyla tanınır?', '["Futbol","Eskrim","Kriket","Halter"]'::jsonb, 0, 'spor', 'global', null, 2),
('Juventus''un ''Bianconeri'' lakabı hangi iki renge gönderme yapar?', '["Siyah-beyaz","Kırmızı-beyaz","Mavi-siyah","Sarı-lacivert"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Uçmayan Hollandalı'' lakabı hangi futbolcuya aittir?', '["Dennis Bergkamp","Ruud Gullit","Marco van Basten","Patrick Kluivert"]'::jsonb, 0, 'spor', 'global', null, 2),
('Seattle SuperSonics taşındıktan sonra hangi NBA takımının adını aldı?', '["Oklahoma City Thunder","Portland Trail Blazers","New Orleans Pelicans","Minnesota Timberwolves"]'::jsonb, 0, 'spor', 'global', null, 2),
('Ryder Cup''ta Avrupa takımının karşısındaki takım hangisidir?', '["ABD","Avustralya","Kanada","Güney Afrika"]'::jsonb, 0, 'spor', 'global', null, 2),
('Dennis Rodman Chicago Bulls''ta hangi forma numarasını giydi?', '["91","90","92","93"]'::jsonb, 0, 'spor', 'global', null, 2),
('Allen Iverson''ın Philadelphia 76ers''taki ikonik forma numarası hangisidir?', '["3","2","4","5"]'::jsonb, 0, 'spor', 'global', null, 2),
('Steven Gerrard Liverpool''da en çok hangi forma numarasıyla özdeşleşir?', '["8","7","9","10"]'::jsonb, 0, 'spor', 'global', null, 2),
('Andy Murray''nin profesyonel tenisçi olan ağabeyinin adı nedir?', '["Jamie","James","Jack","Jordan"]'::jsonb, 0, 'spor', 'global', null, 2),
('Los Angeles Lakers Los Angeles''a taşınmadan önce hangi kentteydi?', '["Minneapolis","Indianapolis","Milwaukee","Cincinnati"]'::jsonb, 0, 'spor', 'global', null, 2),
('Barcelona''nın geleneksel çubuklu iç saha formasında hangi iki renk vardır?', '["Mavi-bordo","Siyah-beyaz","Kırmızı-beyaz","Yeşil-beyaz"]'::jsonb, 0, 'spor', 'global', null, 2),
('Crystal Palace futbol kulübü hangi kuşla özdeşleşir?', '["Kartal","Şahin","Baykuş","Martı"]'::jsonb, 0, 'spor', 'global', null, 2),
('Liverpool tribünleriyle özdeşleşen ''You''ll Never Walk Alone'' şarkısını popülerleştiren grup hangisidir?', '["Gerry and the Pacemakers","Freddie and the Dreamers","The Dave Clark Five","The Searchers"]'::jsonb, 0, 'spor', 'global', null, 2),
('Chicago Bulls''un boğa maskotunun özel adı nedir?', '["Benny","Bango","Rocky","Clutch"]'::jsonb, 0, 'spor', 'global', null, 2),
('Boston Celtics armasındaki figür hangi giysiyi başında taşır?', '["Melon şapka","Silindir şapka","Beyzbol şapkası","Hasır şapka"]'::jsonb, 0, 'spor', 'global', null, 2),
('Brezilyalı Ronaldo Barcelona''dan hangi İtalyan kulübüne geçti?', '["Inter","Juventus","AC Milan","Lazio"]'::jsonb, 0, 'spor', 'global', null, 3),
('San Antonio Spurs''ün 1999-2014 arasındaki beş şampiyonluğunda koçu kimdi?', '["Gregg Popovich","Phil Jackson","Mike D’Antoni","Rudy Tomjanovich"]'::jsonb, 0, 'spor', 'global', null, 3),
('1970 Dünya Kupası finalinde Pelé''nin pasıyla Brezilya''nın dördüncü golünü atan kimdi?', '["Carlos Alberto","Jairzinho","Roberto Rivellino","Tostão"]'::jsonb, 0, 'spor', 'global', null, 3),
('2000 Sydney''de kadınlar maratonunu kazanan Japon atlet kimdi?', '["Naoko Takahashi","Mizuki Noguchi","Kiyoko Shimahara","Yoshimi Ozaki"]'::jsonb, 0, 'spor', 'global', null, 3),
('Andre Agassi''nin olimpiyat tekler altını kazandığı ABD kenti hangisidir?', '["Atlanta","Los Angeles","Salt Lake City","St. Louis"]'::jsonb, 0, 'spor', 'global', null, 3),
('Boca Juniors''ın ''La Bombonera'' stadının lakabı hangi nesne anlamına gelir?', '["Çikolata kutusu","Müzik kutusu","Kibrit kutusu","Mücevher kutusu"]'::jsonb, 0, 'spor', 'global', null, 3),
('1970 Dünya Kupası''nda Pelé''nin kafa vuruşunu çıkaran İngiliz kaleci kimdi?', '["Gordon Banks","Peter Shilton","Ray Clemence","Joe Corrigan"]'::jsonb, 0, 'spor', 'global', null, 3),
('1912''de batan Titanic''in kurtulanlarını alan gemi hangisidir?', '["Carpathia","Californian","Olympic","Lusitania"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Fransa İmparatoru Napolyon''un 1796''da evlendiği ilk eşinin adı nedir?', '["Joséphine","Marie-Louise","Hortense","Désirée"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Napolyon Bonapart''ın Joséphine''den sonraki eşinin adı nedir?', '["Marie Louise","Maria Carolina","Marie Thérèse","Maria Christina"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Roma İmparatoru Caligula''nın ünlü atının adı nedir?', '["Incitatus","Bucephalus","Marengo","Copenhagen"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Sezar''ın aşarak Roma''da iç savaşı başlattığı İtalyan akarsuyu hangisidir?', '["Rubikon","Arno","Tiber","Volturno"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Gandhi''nin 1930''daki ünlü yürüyüşünde Britanya tekeline karşı ürettiği madde neydi?', '["Tuz","Şeker","Tütün","Pamuk"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Roosevelt''i atom bombası ihtimali konusunda uyaran 1939 mektubunu imzalayan fizikçi kimdi?', '["Albert Einstein","Niels Bohr","Ernest Rutherford","Werner Heisenberg"]'::jsonb, 0, 'tarih', 'global', null, 2),
('VI. George tahta çıkmadan önce ailesinde hangi adla çağrılırdı?', '["Bertie","Dickie","Eddie","Georgie"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Berlin Duvarı''nın simgesel sınır geçişi Checkpoint Charlie''deki askerî kontrol hangi ülkeye aitti?', '["ABD","Fransa","Britanya","Sovyetler Birliği"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Camp David görüşmelerinde İsrail''i temsil eden başbakan kimdi?', '["Menahem Begin","Yitzhak Rabin","Shimon Peres","David Ben-Gurion"]'::jsonb, 0, 'tarih', 'global', null, 2),
('III. Richard''ın ölümüne ve Tudor hanedanının yükselişine yol açan savaş hangisidir?', '["Bosworth","Towton","Tewkesbury","Agincourt"]'::jsonb, 0, 'tarih', 'global', null, 2),
('VIII. Edward''ın tahttan çekilince aldığı soyluluk unvanı nedir?', '["Windsor Dükü","York Dükü","Kent Dükü","Gloucester Dükü"]'::jsonb, 0, 'tarih', 'global', null, 2),
('''Ya özgürlük ya ölüm!'' sözüyle tanınan Amerikan bağımsızlık yanlısı kimdir?', '["Patrick Henry","Samuel Adams","Thomas Jefferson","Benjamin Franklin"]'::jsonb, 0, 'tarih', 'global', null, 2),
('1633''te Engizisyon önünde Dünya''nın hareketinden vazgeçmeye zorlanan bilim insanı kimdi?', '["Galileo Galilei","Johannes Kepler","Tycho Brahe","Christiaan Huygens"]'::jsonb, 0, 'tarih', 'global', null, 2),
('İmparator Justinianus''un yönettiği imparatorluk hangisiydi?', '["Bizans","Sasani","Karolenj","Kutsal Roma"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Japonya''daki Meiji Restorasyonu''nun adını aldığı imparator kimdir?', '["Mutsuhito","Yoshihito","Hirohito","Akihito"]'::jsonb, 0, 'tarih', 'global', null, 2),
('1917 Rus Devrimi''nin simgesi olan Aurora hangi tür araçtı?', '["Kruvazör","Denizaltı","Muhrip","Mayın gemisi"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Fransız Devrimi''nin simgesel başlangıcında basılan Bastille ne tür binaydı?', '["Hapishane","Belediye sarayı","Kraliyet tiyatrosu","Darphane"]'::jsonb, 0, 'tarih', 'global', null, 2),
('İngiltere Kralı II. Charles''a sığınak olan ünlü ağaç hangi türdendi?', '["Meşe","Karaağaç","Kayın","Kestane"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Florence Nightingale hangi sağlık mesleğinin öncülerindendir?', '["Hemşirelik","Diş hekimliği","Eczacılık","Veterinerlik"]'::jsonb, 0, 'tarih', 'global', null, 2),
('1933''teki büyük yangını Nazi baskısının gerekçesi yapılan Berlin binası hangisidir?', '["Reichstag","Brandenburg Kapısı","Charlottenburg Sarayı","Berlin Katedrali"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Rosetta Taşı''nda hiyeroglif ve Yunanca dışında hangi yazı yer alır?', '["Demotik","Çivi yazısı","Aramice","Fenike yazısı"]'::jsonb, 0, 'tarih', 'global', null, 3),
('Çar I. Petro Avrupa gezisinde Hollanda''da hangi işte çalıştı?', '["Gemi yapımı","Saat yapımı","Cam üfleme","İpek dokuma"]'::jsonb, 0, 'tarih', 'global', null, 3),
('1917 Cambrai Savaşı''nda Britanya''nın topluca kullandığı yeni savaş aracı hangisiydi?', '["Tank","Denizaltı","Zeplin","Zırhlı tren"]'::jsonb, 0, 'tarih', 'global', null, 3),
('İbn Battuta''nın yolculuklarını anlatan eser genellikle hangi kısa adla anılır?', '["Rihla","Muqaddimah","Shahnameh","Siyasatnama"]'::jsonb, 0, 'tarih', 'global', null, 3),
('Roma''ya karşı mücadele eden Kraliçe Zenobia''nın merkezi hangi antik kentti?', '["Palmira","Antakya","İskenderiye","Petra"]'::jsonb, 0, 'tarih', 'global', null, 3),
('1970''te Varşova Gettosu anıtı önünde diz çöken Alman şansölyesi kimdi?', '["Willy Brandt","Helmut Schmidt","Konrad Adenauer","Ludwig Erhard"]'::jsonb, 0, 'tarih', 'global', null, 3),
('1945 Potsdam görüşmelerinde Britanya''yı Churchill''in yerine temsil etmeye başlayan başbakan kimdi?', '["Clement Attlee","Anthony Eden","Neville Chamberlain","Stanley Baldwin"]'::jsonb, 0, 'tarih', 'global', null, 3),
('Magna Carta ilk kez hangi hükümdarlık simgesiyle onaylandı?', '["Mühür","El yazısı imza","Parmak izi","Kazınmış monogram"]'::jsonb, 0, 'tarih', 'global', null, 3),
('Churchill''in ''Demir Perde'' konuşmasını yaptığı Amerikan kenti hangisidir?', '["Fulton","Dayton","Topeka","Lincoln"]'::jsonb, 0, 'tarih', 'global', null, 3),
('''Otomatik Portakal'' filmini kim yönetmiştir?', '["Stanley Kubrick","Martin Scorsese","Robert Zemeckis","Steven Spielberg"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Terminatör'' filmini kim yönetmiştir?', '["James Cameron","David Fincher","Peter Jackson","Ridley Scott"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Büyük Budapeşte Oteli'' filmini kim yönetmiştir?', '["Wes Anderson","Noah Baumbach","Sofia Coppola","David O. Russell"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''La La Land'' filmini kim yönetmiştir?', '["Damien Chazelle","Rob Marshall","Baz Luhrmann","Kenneth Branagh"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Guguk Kuşu''ndaki McMurphy karakterini hangi oyuncu canlandırmıştır?', '["Jack Nicholson","Robert De Niro","Robin Williams","Morgan Freeman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yüzüklerin Efendisi'' filmlerindeki Aragorn karakterini hangi oyuncu canlandırmıştır?', '["Viggo Mortensen","Anthony Hopkins","Joaquin Phoenix","Robert De Niro"]'::jsonb, 0, 'sinema', 'global', null, 2),
('The Lord of the Rings''teki Gandalf karakterini hangi oyuncu canlandırmıştır?', '["Ian McKellen","Bruce Willis","Keanu Reeves","Heath Ledger"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Cinema Paradiso'' filminin müziklerini kim bestelemiştir?', '["Ennio Morricone","Alan Silvestri","Bernard Herrmann","Rachel Portman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Can Dostum''un senaryosunu Matt Damon ile birlikte yazan oyuncu kimdir?', '["Ben Affleck","Casey Affleck","Mark Wahlberg","Edward Norton"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Bugün Aslında Dündü''de Phil Connors televizyon için hangi mesleği yapar?', '["Meteorolog","Spor yorumcusu","Haber kameramanı","Yarışma sunucusu"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Amélie''nin Paris''te çalıştığı işletme hangisidir?', '["Kafe","Kitabevi","Çiçekçi","Fırın"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yaratık'' serisindeki büyük şirketin adı nedir?', '["Weyland-Yutani","Tyrell Corporation","Cyberdyne Systems","Omni Consumer Products"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Büyük Budapeşte Oteli''nde M. Gustave''ın oteldeki görevi nedir?', '["Konsiyerj","Aşçıbaşı","Muhasebeci","Güvenlik müdürü"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Akıl Defteri''nde Leonard''ın hatırlamak için bedenine eklediği şeyler nelerdir?', '["Dövmeler","Yaralar","Delikler","Boya desenleri"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Geleceğe Dönüş''te Doc Brown''ın köpeğinin adı nedir?', '["Einstein","Newton","Darwin","Copernicus"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Ucuz Roman''da Vincent Avrupa''da hangi hamburger adını ''Royale with Cheese'' diye anlatır?', '["Quarter Pounder","Big Mac","Whopper","Double Cheeseburger"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Esaretin Bedeli''nde Andy''nin hücre tünelini kazmakta kullandığı küçük alet nedir?', '["Kaya çekici","Metal törpü","Küçük keski","El matkabı"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Gladyatör''de Maximus''a gladyatörlük yaptıran eski gladyatörün adı nedir?', '["Proximo","Commodus","Quintus","Falco"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Otomatik Portakal''daki Alex hangi bestecinin müziğine tutkuyla bağlıdır?', '["Beethoven","Brahms","Tchaikovsky","Rachmaninoff"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Léon'' filminde başkahramanın sürekli yanında taşıdığı ev eşyası nedir?', '["Saksı bitkisi","Ahşap saat","Seramik vazo","Çerçeveli ayna"]'::jsonb, 0, 'sinema', 'global', null, 3),
('İspanya''da içecek yanında sunulan küçük atıştırmalık tabaklarına ne ad verilir?', '["Tapas","Antipasti","Dim sum","Banchan"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kore sofrasında ana yemeğin çevresine dizilen küçük yan yemeklerin ortak adı nedir?', '["Banchan","Yakitori","Satay","Tempura"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Meksika Ölüler Günü sunaklarında yaygın olarak hangi çiçek kullanılır?', '["Kadife çiçeği","Beyaz zambak","Kırmızı karanfil","Mavi sümbül"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İsveç''te Aziz Lucia Günü''yle ilişkilendirilen safranlı çöreğin adı nedir?', '["Lussekatt","Semla","Kanelbulle","Kardemummabulle"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İskoç kiltinin önünde taşınan küçük kesenin adı nedir?', '["Sporran","Tam o'' shanter","Balmoral","Glengarry"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Geleneksel bindi süsü yüzde nereye yerleştirilir?', '["Alna","Çeneye","Yanağa","Burnun ucuna"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Brezilya''da yılbaşı gecesi uğur ve barış için yaygın olarak hangi renk giyilir?', '["Beyaz","Kırmızı","Siyah","Mor"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Buenos Aires ve Montevideo ile özdeşleşen çift dansı hangisidir?', '["Tango","Samba","Rumba","Bachata"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Tayland''da Songkran kutlamalarında insanların birbirine sıçrattığı şey nedir?', '["Su","Renkli toz","Çiçek yaprağı","Pirinç taneleri"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Portekiz pastel de nata tatlısının iç dolgusunda hangi malzeme belirgindir?', '["Yumurta","Badem","Hindistan cevizi","Çikolata"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İspanya''da yılbaşı gece yarısındaki on iki çan vuruşunda hangi meyve yenir?', '["Üzüm","Kiraz","Zeytin","Hurma"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik banana split servisinde muz nasıl hazırlanır?', '["Boyuna ikiye kesilir","Yuvarlak dilimlenir","Püre hâline getirilir","Küp küp doğranır"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Endonezya batik kumaşı boyanırken desenli alanları korumak için ne kullanılır?', '["Balmumu","Kil çamuru","Pirinç unu","Bitki reçinesi"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Yunan vasilopita yılbaşı pastasının içine hangi nesne saklanır?', '["Madeni para","Küçük anahtar","Metal yüzük","Cam boncuk"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Amritsar''daki Altın Tapınak hangi dinin önemli ibadet yeridir?', '["Sihizm","Hinduizm","Budizm","Caynizm"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kare üstlü klasik mezuniyet başlığı üzerinde sarkan parça nedir?', '["Püskül","Kurdele","Tüy demeti","Zincir"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik 3×3 Rubik küpünde merkez parçalarının toplam sayısı kaçtır?', '["6","4","8","12"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik Zippo çakmağının metal kapağı gövdeye neyle bağlanır?', '["Menteşe","Vida","Zincir","Mıknatıs"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik LEGO parçalarının üstündeki çıkıntılar hangi biçimdedir?', '["Daire","Kare","Üçgen","Altıgen"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Standart 52 kartlık destede her bir sembolden kaç kart vardır?', '["13","12","14","15"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik tirbuşonun mantara giren metal parçası hangi biçimdedir?', '["Spiral","Kanca","Düz çivi","Testere dişi"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Geleneksel cappuccino yüzeyindeki kalın açık renkli tabaka nedir?', '["Süt köpüğü","Krema jeli","Şeker kabuğu","Yumurta akı"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Almanya''da ilk okul gününde çocuklara verilen Schultüte hangi biçimdedir?', '["Koni","Küp","Küre","Silindir"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Danimarka Noel geleneğinde nisse için bırakılan risengrød hangi tahılla yapılır?', '["Pirinç","Yulaf","Arpa","Buğday"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Anzak Günü''nde anmayı simgelemek için yakaya takılan bitki hangisidir?', '["Biberiye","Lavanta","Fesleğen","Kekik"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Çek Paskalya geleneğindeki pomlázka geleneksel olarak hangi ağacın dallarından örülür?', '["Söğüt","Huş","Meşe","Kavak"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Macar gulaşına karakteristik rengini veren baharat hangisidir?', '["Paprika","Zerdeçal","Safran","Kimyon"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Hint mehndi düğün süslemesinde ele sürülen boya hangi bitkiden elde edilir?', '["Kına","Çivit","Zerdeçal","Safran"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Maori hongi selamında geleneksel olarak hangi yüz bölümü birbirine değdirilir?', '["Burun","Çene","Yanak","Dudak"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Mahjong oyununda dört oyuncunun yön adları arasında ilk dağıtıcı hangisidir?', '["Doğu","Batı","Kuzey","Güney"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Churros hamuru geleneksel olarak nasıl pişirilir?', '["Yağda kızartılır","Buharda pişirilir","Fırında kurutulur","Suda haşlanır"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Japon Setsubun geleneğinde evden kötü ruhları kovmak için ne atılır?', '["Kavrulmuş soya","Kurutulmuş nohut","Kavrulmuş kestane","Kabuklu yer fıstığı"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Batı düğün geleneğinde gelinin geriye doğru attığı nesne nedir?', '["Çiçek buketi","İnci kolyesi","Dantel duvağı","Saten eldiveni"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Vietnam''ın taze gỏi cuốn ruloları geleneksel olarak neyle sarılır?', '["Pirinç kâğıdı","Mısır yaprağı","Buğday yufkası","Lahana yaprağı"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Etiyopya sofrasında yemeklerin üzerinde sunulduğu gözenekli yassı ekmeğin adı nedir?', '["Injera","Chapati","Lavash","Paratha"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Norveç kransekake pastası geleneksel olarak hangi biçimli katlardan oluşur?', '["Halka","Kare","Yıldız","Üçgen"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Çukurlar'' romanının yazarı kimdir?', '["Louis Sachar","Roald Dahl","Jerry Spinelli","Andrew Clements"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Doktor Dolittle''ın Hikâyesi'' kitabının yazarı kimdir?', '["Hugh Lofting","A. A. Milne","Kenneth Grahame","Beatrix Potter"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Hobbit''te Bilbo''nun Sting adlı silahı hangi türdedir?', '["Kılıç","Balta","Mızrak","Hançer"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Harry Potter''daki Erised hangi nesnedir?', '["Ayna","Kılıç","Yüzük","Kolye"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Küçük Kadınlar''da Jo''nun en küçük kardeşinin adı nedir?', '["Amy","Beth","Meg","Jo"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Harry Potter''ın alnındaki yara izi hangi biçimdedir?', '["Şimşek","Beş köşeli yıldız","Hilal","Kavisli ok"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Anton Çehov edebiyatın yanında hangi mesleği yapmıştır?', '["Doktor","Avukat","Mühendis","Eczacı"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''1984''te Winston Smith''in işvereni olan kurum hangisidir?', '["Gerçek Bakanlığı","Sevgi Bakanlığı","Barış Bakanlığı","Bolluk Bakanlığı"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Oz Büyücüsü'' kitabında Korkuluk ne elde etmek ister?', '["Beyin","Kalp","Cesaret","Ses"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Sherlock Holmes'' öykülerindeki Dr. Watson''ın ilk adı nedir?', '["John","James","William","Henry"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Pippi Uzunçorap''ın kızıl saçları hangi biçimde kullanılır?', '["İki örgü","Tek at kuyruğu","Kısa küt kesim","Topuz"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Paddington Ayısı hangi renk pardösüyle tanınır?', '["Mavi","Kırmızı","Yeşil","Sarı"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Pinokyo okulu bırakıp eğlenceye dalınca hangi hayvana dönüşür?', '["Eşek","Domuz","Tavşan","Köpek"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Büyük Umutlar''da Bayan Havisham''ın durmuş saatleri günün hangi olayını simgeler?', '["Düğünün iptali","Babasının cenazesi","Kız kardeşinin gidişi","Kocasının ölümü"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Yaşlı Adam ve Deniz''de Santiago''nun yakaladığı büyük balık hangi türdür?', '["Marlin","Ton balığı","Köpekbalığı","Kılıçbalığı"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Bülbülü Öldürmek''te Scout''un ağabeyinin lakabı nedir?', '["Jem","Dill","Boo","Huck"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Peter Pan''da timsahın yuttuğu nesne nedir?', '["Saat","Pusula","Çan","Düdük"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Otostopçunun Galaksi Rehberi''nde Dünya''ya çoktan gelmiş Ford Prefect kendisini hangi işte gösterir?', '["Oyuncu","Gazeteci","Öğretmen","Pilot"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Bitmeyecek Öykü'' romanının özgün Almanca metninde şans ejderhasının adı nedir?', '["Fuchur","Gmork","Atreju","Bastian"]'::jsonb, 0, 'edebiyat', 'global', null, 3)
on conflict (soru) do nothing;

-- ---------------------------------------------------- İngilizce çeviri
insert into public.question_translations (question_id, dil, soru, secenekler)
select q.id, 'en', v.en_soru, v.en_secenekler
  from (values
  ('Frida Kahlo''nun evlendiği duvar ressamı kimdir?', 'Which muralist did Frida Kahlo marry?', '["Diego Rivera","José Clemente Orozco","David Alfaro Siqueiros","Rufino Tamayo"]'::jsonb),
  ('''Kuğu Gölü''nde siyah kuğu olarak bilinen Odile, hangi beyaz kuğunun karşıtıdır?', 'In ''Swan Lake'', Odile the black swan is the counterpart of which white swan?', '["Odette","Aurora","Giselle","Swanilda"]'::jsonb),
  ('Jeff Koons''un ''Balloon Dog'' heykellerinin parlak yüzeyi hangi malzemeden yapılmıştır?', 'What material forms the shiny surface of Jeff Koons''s ''Balloon Dog'' sculptures?', '["Stainless steel","Chrome-plated bronze","Polished aluminium","Nickel-plated copper"]'::jsonb),
  ('Antik ''Semadirek Kanatlı Zaferi'' heykelinde figürün hangi vücut bölümü eksiktir?', 'Which body part is missing from the ancient ''Winged Victory of Samothrace''?', '["Head","Torso","Waist","Back"]'::jsonb),
  ('Renkli kâğıt kesmeleriyle yaptığı ''Mavi Nü'' serisinin sanatçısı kimdir?', 'Who made the Blue Nudes series using cut-out coloured paper?', '["Henri Matisse","Pablo Picasso","Georges Braque","Fernand Léger"]'::jsonb),
  ('''Ben ve Köy'' tablosunu yapan ressam kimdir?', 'Who painted I and the Village?', '["Marc Chagall","Wassily Kandinsky","Paul Klee","Kazimir Malevich"]'::jsonb),
  ('Grant Wood''un ''Amerikan Gotiği'' tablosunda adam elinde ne tutar?', 'What does the man hold in Grant Wood''s American Gothic?', '["Pitchfork","Shovel","Sickle","Axe staff"]'::jsonb),
  ('Jan van Eyck''in ''Arnolfini Portresi''nde çiftin ayaklarının önündeki hayvan nedir?', 'What animal stands in front of the couple''s feet in Jan van Eyck''s Arnolfini Portrait?', '["Dog","Cat","Rabbit","Ferret"]'::jsonb),
  ('Gaudí''nin Sagrada Família''sındaki sütunlar içeride hangi doğal biçimi andıracak şekilde dallanır?', 'What natural form do the branching interior columns of Gaudi''s Sagrada Familia resemble?', '["Tree","Coral","Mountain","Wave"]'::jsonb),
  ('Londra''daki The Shard gökdeleninin cephesindeki baskın malzeme hangisidir?', 'What is the predominant material on the facade of London''s Shard?', '["Glass","Brick","Granite","Timber"]'::jsonb),
  ('Milton Glaser''ın ''I Love NY'' logosunda love sözcüğü yerine hangi şekil vardır?', 'What shape replaces the word love in Milton Glaser''s I Love NY logo?', '["Heart","Star","Apple","Flower"]'::jsonb),
  ('Andy Warhol''un ünlü konserve kutusu serisinde hangi ürünün ambalajı yer alır?', 'What product''s packaging appears in Andy Warhol''s famous can series?', '["Soup","Beans","Tuna","Fruit compote"]'::jsonb),
  ('Sahne müzikali ''Operadaki Hayalet''te Christine Daaé''nin sanatsal işi nedir?', 'What is Christine Daae''s artistic profession in the stage musical The Phantom of the Opera?', '["Singing","Painting","Sculpture","Photography"]'::jsonb),
  ('Sahne müzikali ''Sefiller''de Jean Valjean hangi yiyeceği çaldığı için hapsedilir?', 'What food did Jean Valjean steal before his imprisonment in the stage musical Les Miserables?', '["Bread","Cheese","Apple","Dried meat"]'::jsonb),
  ('Velázquez''in ''Nedimeler'' tablosunda ressam kendi elinde ne tutar?', 'What does the painter hold in Velazquez''s Las Meninas?', '["Brush and palette","Pen and notebook","Hammer and chisel","Scissors and cloth"]'::jsonb),
  ('Rodin''in ''Düşünen Adam''ı çenesini neyin üzerine dayar?', 'What does Rodin''s Thinker rest his chin on?', '["Hand","Knee","Chair arm","Book"]'::jsonb),
  ('LOVE yazısının O harfini eğik yerleştiren ünlü heykellerin sanatçısı kimdir?', 'Who created the famous LOVE sculptures with the tilted letter O?', '["Robert Indiana","Roy Lichtenstein","Jasper Johns","Claes Oldenburg"]'::jsonb),
  ('Bilbao Guggenheim Müzesi''nin kıvrımlı dış cephesindeki metal kaplama hangisidir?', 'What metal clads the curved exterior of the Guggenheim Museum Bilbao?', '["Titanium","Aluminium","Copper","Stainless steel"]'::jsonb),
  ('Prag''daki Dans Eden Ev''in iki kulesine Fred ile hangi dansçının adı verilmiştir?', 'Prague''s Dancing House towers are nicknamed Fred and which dancer?', '["Ginger Rogers","Cyd Charisse","Rita Hayworth","Ann Miller"]'::jsonb),
  ('Brancusi''nin MoMA''daki ''Uzayda Kuş'' heykeli hangi malzemedendir?', 'What material is Brancusi''s ''Bird in Space'' at MoMA made from?', '["Bronze","Wood","Steel","Marble"]'::jsonb),
  ('Boccioni''nin ''Uzayda Sürekliliğin Benzersiz Biçimleri'' heykelinin bilinen dökümleri hangi malzemedendir?', 'What is the main material of ''casts of Boccioni''s Unique Forms of Continuity in Space''?', '["Bronze","Copper","Aluminium","Iron"]'::jsonb),
  ('Georgia O''Keeffe''in evlendiği fotoğrafçı kimdir?', 'Which photographer did Georgia O''Keeffe marry?', '["Alfred Stieglitz","Edward Steichen","Alfred Eisenstaedt","Edward Weston"]'::jsonb),
  ('Picasso''nun ''Guernica''sı 1937''de hangi etkinlikteki İspanya pavyonu için yapıldı?', 'For which event''s Spanish pavilion was Picasso''s ''Guernica'' painted in 1937?', '["Paris World''s Fair","Venice Biennale","Berlin Olympics","London World''s Fair"]'::jsonb),
  ('Ai Weiwei''nin Tate Modern''deki ''Sunflower Seeds'' yerleştirmesinin taneleri hangi malzemedendir?', 'What material are the seeds in Ai Weiwei''s ''Sunflower Seeds'' at Tate Modern made from?', '["Porcelain","Terracotta","Cast bronze","Coloured glass"]'::jsonb),
  ('Manet''nin ''Olympia'' tablosundaki yatan kadın için poz veren model kimdir?', 'Who posed for the reclining woman in Manet''s ''Olympia''?', '["Victorine Meurent","Berthe Morisot","Suzanne Valadon","Jeanne de Tourbey"]'::jsonb),
  ('Diego Rivera''nın Rockefeller Center''daki duvar resminde hangi Sovyet liderin portresi kriz çıkarmıştı?', 'Which Soviet leader''s portrait caused controversy in Diego Rivera''s Rockefeller Center mural?', '["Lenin","Stalin","Trotsky","Bukharin"]'::jsonb),
  ('Géricault''nun ''Medusa''nın Salı'' tablosundaki kazazedeler hangi taşıtın kazasından kurtulmuştur?', 'What kind of vessel were the survivors on Gericault''s The Raft of the Medusa travelling in?', '["Frigate","Corvette","Cargo ship","Fishing boat"]'::jsonb),
  ('''Nevermind'' albümü hangi gruba aittir?', 'Which band released ''Nevermind''?', '["Nirvana","The Who","Genesis","Eagles"]'::jsonb),
  ('''Don Giovanni'' operasını kim bestelemiştir?', 'Who composed the opera ''Don Giovanni''?', '["Wolfgang Amadeus Mozart","Christoph Willibald Gluck","Gioachino Rossini","Gaetano Donizetti"]'::jsonb),
  ('''Come Together'' şarkısı ilk olarak hangi albümde yayımlandı?', 'Which album first featured ''Come Together''?', '["Abbey Road","Rubber Soul","Let It Be","Revolver"]'::jsonb),
  ('Queen''in ''Bohemian Rhapsody'' şarkısında adı geçen astronom hangisidir?', 'Which astronomer is named in Queen''s Bohemian Rhapsody?', '["Galileo","Copernicus","Kepler","Ptolemy"]'::jsonb),
  ('Konser filmi ''Stop Making Sense'' hangi grubun performansını gösterir?', 'Which band performs in the concert film Stop Making Sense?', '["Talking Heads","The B-52''s","Blondie","The Pretenders"]'::jsonb),
  ('B. B. King''in ''Lucille'' adıyla tanınan çalgısı hangisidir?', 'What kind of instrument was B. B. King''s Lucille?', '["Guitar","Violin","Trumpet","Saxophone"]'::jsonb),
  ('Debbie Harry hangi grubun solistidir?', 'Which band is fronted by Debbie Harry?', '["Blondie","The Pretenders","Siouxsie and the Banshees","The Go-Go''s"]'::jsonb),
  ('KISS grubunun sahne yüzlerinde kullandığı baskın makyaj renkleri hangileridir?', 'What are the predominant colours of KISS''s stage face paint?', '["Black and white","Red and yellow","Blue and green","Purple and orange"]'::jsonb),
  ('Michael Jackson''ın ''Thriller'' kaydındaki korku dolu konuşmayı hangi oyuncu seslendirir?', 'Which actor performs the spooky spoken passage on Michael Jackson''s Thriller?', '["Vincent Price","Christopher Lee","Peter Cushing","Boris Karloff"]'::jsonb),
  ('Chuck Berry''nin sahnede çömelerek ileri hareket ettiği ünlü hareket nasıl anılır?', 'What is Chuck Berry''s famous crouching stage move called?', '["Duck walk","Moonwalk","Chicken dance","Crab walk"]'::jsonb),
  ('Dire Straits''in ''Money for Nothing'' kaydındaki ''I want my MTV'' bölümünü kim söyler?', 'Who sings I want my MTV on Dire Straits'' Money for Nothing?', '["Sting","Bono","Peter Gabriel","Phil Collins"]'::jsonb),
  ('''99 Luftballons'' şarkısını söyleyen Alman şarkıcı kimdir?', 'Which German singer sang ''99 Luftballons''?', '["Nena","Sandra","C. C. Catch","Kim Wilde"]'::jsonb),
  ('Johnny Cash''in yorumladığı ''Hurt'' parçası ilk olarak hangi grubun eseriydi?', 'Which band originally released Hurt before Johnny Cash covered it?', '["Nine Inch Nails","Soundgarden","Alice in Chains","Stone Temple Pilots"]'::jsonb),
  ('Rolling Stones''un ''Exile on Main St.'' kayıtlarının önemli bölümü hangi tür mekânda yapıldı?', 'What type of location hosted much of the recording of the Rolling Stones'' Exile on Main St.?', '["A villa basement","A church main hall","A school gymnasium","A railway station hall"]'::jsonb),
  ('Frank Sinatra''nın ''My Way'' şarkısının İngilizce sözlerini kim yazdı?', 'Who wrote the English lyrics of Frank Sinatra''s My Way?', '["Paul Anka","Neil Sedaka","Burt Bacharach","Hal David"]'::jsonb),
  ('Radiohead kurulurken kullandığı ilk ad hangisiydi?', 'What was Radiohead''s original band name?', '["On a Friday","The Quarrymen","The High Numbers","The New Yardbirds"]'::jsonb),
  ('İlk iPad hangi yıl piyasaya çıktı?', 'In which year was the original iPad released?', '["2010","2009","2011","2013"]'::jsonb),
  ('Nintendo Game Boy hangi yıl piyasaya çıktı?', 'In which year was Nintendo Game Boy released?', '["1989","1987","1988","1991"]'::jsonb),
  ('İlk Sony Walkman hangi yıl piyasaya çıktı?', 'In which year was the original Sony Walkman released?', '["1979","1977","1978","1981"]'::jsonb),
  ('İlk ticari müzik CD''leri Japonya''da hangi yıl satışa sunuldu?', 'In which year did the first commercial music CDs go on sale in Japan?', '["1982","1980","1981","1983"]'::jsonb),
  ('Motorola RAZR V3 telefonu açıldığında kullanıcı hangi tür klavyeyle karşılaşırdı?', 'What type of keypad was revealed when a Motorola RAZR V3 was opened?', '["Numeric keypad","Full QWERTY keyboard","Touchscreen keyboard","Rotary dial"]'::jsonb),
  ('İlk iPod shuffle modelinde diğer iPod''lardan farklı olarak hangi parça yoktu?', 'What component did the original iPod shuffle lack compared with other iPods?', '["Screen","Headphone socket","Physical buttons","USB connection"]'::jsonb),
  ('Android 4.4 sürümünün tatlı adı hangisiydi?', 'What was the dessert name for Android 4.4?', '["KitKat","Jelly Bean","Ice Cream Sandwich","Lollipop"]'::jsonb),
  ('Twitter''ın eski logosundaki hayvan hangisiydi?', 'What animal appeared in Twitter''s former logo?', '["Bird","Fox","Whale","Butterfly"]'::jsonb),
  ('Uzunçalar plaklarla ilişkilendirilen standart dönüş hızı hangisidir?', 'Which standard playback speed is associated with long-playing records?', '["33⅓ rpm","45 rpm","78 rpm","16⅔ rpm"]'::jsonb),
  ('Commodore 64 adındaki sayı cihazın hangi özelliğine gönderme yapar?', 'What does the number in Commodore 64 refer to?', '["Memory capacity","Processor speed","Display resolution","Keyboard key count"]'::jsonb),
  ('3,5 inç disketin önündeki metal parça kullanımda nasıl hareket eder?', 'How does the metal cover on a 3.5-inch floppy disk move during use?', '["Slides sideways","Swings outwards","Lifts upwards","Comes off entirely"]'::jsonb),
  ('Nokia 3310''un ekranı renk bakımından hangi türdeydi?', 'What kind of display did the Nokia 3310 have in terms of colour?', '["Monochrome","Full colour","Three-colour","Colour e-ink"]'::jsonb),
  ('Klasik BlackBerry Curve telefonlarda gezinmek için ortada hangi küçük kontrol vardı?', 'What small central navigation control was on classic BlackBerry Curve phones?', '["Trackball","Touchpad","Joystick","Scroll wheel"]'::jsonb),
  ('Dyson Air Multiplier masa vantilatörünün hava çıkışı hangi biçimdedir?', 'What shape is the air outlet on a Dyson Air Multiplier desk fan?', '["Ring","Square","Triangle","Star"]'::jsonb),
  ('1984 Macintosh reklamında ekrana fırlatılan nesne nedir?', 'What object is thrown at the screen in the 1984 Macintosh advertisement?', '["Sledgehammer","Baseball bat","Fire extinguisher","Metal chair"]'::jsonb),
  ('Pixar''ın Luxo Jr. kısa filmindeki başkahraman hangi ev eşyasıdır?', 'What household object is the title character in Pixar''s Luxo Jr.?', '["Desk lamp","Alarm clock","Ceiling fan","Vacuum cleaner"]'::jsonb),
  ('İlk Macintosh farelerinde kaç ana tıklama düğmesi vardı?', 'How many main click buttons were on the original Macintosh mouse?', '["1","2","3","4"]'::jsonb),
  ('IBM''in 1981 tarihli ilk kişisel bilgisayarında hangi Intel işlemcisi vardı?', 'Which Intel processor powered IBM''s original 1981 personal computer?', '["8088","8086","80186","80286"]'::jsonb),
  ('Sony PSP oyunlarının satıldığı küçük optik disk biçiminin kısa adı nedir?', 'What is the abbreviation for the small optical disc format used for Sony PSP games?', '["UMD","MiniDisc","DVD","Blu-ray"]'::jsonb),
  ('Twitter''ın 2006''da başlayan ilk döneminde bir paylaşımın karakter sınırı kaçtı?', 'What was Twitter''s character limit when the service launched in 2006?', '["140","120","160","180"]'::jsonb),
  ('Nintendo Wii''nin hareket kumandasının yanına bağlanan küçük yardımcı kumandanın adı nedir?', 'What is the small secondary controller attached to the Nintendo Wii''s motion controller called?', '["Nunchuk","DualShock","Joy-Con","Sixaxis"]'::jsonb),
  ('PowerPoint''i Microsoft satın almadan önce geliştiren şirket hangisidir?', 'Which company developed PowerPoint before Microsoft acquired it?', '["Forethought","WordPerfect","Ashton-Tate","Borland"]'::jsonb),
  ('Amazon''un Kindle''ından önceki e-kitap okuyucu ''Rocket eBook''u hangi şirket geliştirdi?', 'Which company developed the Rocket eBook reader?', '["NuvoMedia","SoftBook Press","Palm Computing","Sony Electronics"]'::jsonb),
  ('Nintendo''nun NES Zapper aksesuarı hangi nesne biçimindeydi?', 'What object did Nintendo''s NES Zapper accessory resemble?', '["Pistol","Steering wheel","Boxing glove","Drumstick"]'::jsonb),
  ('James Webb teleskobunun ana aynasında kaç altıgen parça vardır?', 'How many hexagonal segments form the James Webb telescope''s primary mirror?', '["18","16","20","24"]'::jsonb),
  ('Çin''in insanlı uzay kapsülü serisinin adı nedir?', 'What is the name of China''s crewed spacecraft series?', '["Shenzhou","Tianzhou","Chang''e","Tianwen"]'::jsonb),
  ('Nintendo GameCube kasasının arkasındaki belirgin taşıma parçası nedir?', 'What distinctive carrying feature is on the back of a Nintendo GameCube?', '["Handle","Shoulder strap","Wheel","Leather strap"]'::jsonb),
  ('İlk iPod reklam kampanyaları hangi renk kulaklık kablosuyla özdeşleşti?', 'What colour headphone cable became associated with the early iPod advertising campaigns?', '["White","Black","Red","Grey"]'::jsonb),
  ('Apple''ın Lisa bilgisayarı Steve Jobs''ın hangi yakınının adını taşır?', 'Which of Steve Jobs''s relatives gave her name to Apple''s Lisa computer?', '["Daughter","Mother","Sister","Grandmother"]'::jsonb),
  ('Rafael Nadal hangi spor dalıyla tanınır?', 'Which sport is Rafael Nadal known for?', '["Tennis","Swimming","Skiing","Rugby"]'::jsonb),
  ('Marta Vieira da Silva hangi spor dalıyla tanınır?', 'Which sport is Marta Vieira da Silva known for?', '["Football","Fencing","Cricket","Weightlifting"]'::jsonb),
  ('Juventus''un ''Bianconeri'' lakabı hangi iki renge gönderme yapar?', 'Which two colours does Juventus''s nickname ''Bianconeri'' refer to?', '["Black and white","Red and white","Blue and black","Yellow and navy"]'::jsonb),
  ('''Uçmayan Hollandalı'' lakabı hangi futbolcuya aittir?', 'Which footballer was nicknamed the Non-Flying Dutchman?', '["Dennis Bergkamp","Ruud Gullit","Marco van Basten","Patrick Kluivert"]'::jsonb),
  ('Seattle SuperSonics taşındıktan sonra hangi NBA takımının adını aldı?', 'Which NBA team name replaced the Seattle SuperSonics after relocation?', '["Oklahoma City Thunder","Portland Trail Blazers","New Orleans Pelicans","Minnesota Timberwolves"]'::jsonb),
  ('Ryder Cup''ta Avrupa takımının karşısındaki takım hangisidir?', 'Which team opposes Europe in the Ryder Cup?', '["USA","Australia","Canada","South Africa"]'::jsonb),
  ('Dennis Rodman Chicago Bulls''ta hangi forma numarasını giydi?', 'What jersey number did Dennis Rodman wear with the Chicago Bulls?', '["91","90","92","93"]'::jsonb),
  ('Allen Iverson''ın Philadelphia 76ers''taki ikonik forma numarası hangisidir?', 'What was Allen Iverson''s iconic Philadelphia 76ers jersey number?', '["3","2","4","5"]'::jsonb),
  ('Steven Gerrard Liverpool''da en çok hangi forma numarasıyla özdeşleşir?', 'Which Liverpool jersey number is Steven Gerrard most associated with?', '["8","7","9","10"]'::jsonb),
  ('Andy Murray''nin profesyonel tenisçi olan ağabeyinin adı nedir?', 'What is the name of Andy Murray''s older brother, also a professional tennis player?', '["Jamie","James","Jack","Jordan"]'::jsonb),
  ('Los Angeles Lakers Los Angeles''a taşınmadan önce hangi kentteydi?', 'In which city were the Lakers based before moving to Los Angeles?', '["Minneapolis","Indianapolis","Milwaukee","Cincinnati"]'::jsonb),
  ('Barcelona''nın geleneksel çubuklu iç saha formasında hangi iki renk vardır?', 'Which two colours appear on Barcelona''s traditional striped home shirt?', '["Blue and maroon","Black and white","Red and white","Green and white"]'::jsonb),
  ('Crystal Palace futbol kulübü hangi kuşla özdeşleşir?', 'Which bird is associated with Crystal Palace Football Club?', '["Eagle","Falcon","Owl","Seagull"]'::jsonb),
  ('Liverpool tribünleriyle özdeşleşen ''You''ll Never Walk Alone'' şarkısını popülerleştiren grup hangisidir?', 'Which group popularised You''ll Never Walk Alone, associated with Liverpool supporters?', '["Gerry and the Pacemakers","Freddie and the Dreamers","The Dave Clark Five","The Searchers"]'::jsonb),
  ('Chicago Bulls''un boğa maskotunun özel adı nedir?', 'What is the name of the Chicago Bulls'' bull mascot?', '["Benny","Bango","Rocky","Clutch"]'::jsonb),
  ('Boston Celtics armasındaki figür hangi giysiyi başında taşır?', 'What does the figure on the Boston Celtics logo wear on his head?', '["Bowler hat","Top hat","Baseball cap","Straw hat"]'::jsonb),
  ('Brezilyalı Ronaldo Barcelona''dan hangi İtalyan kulübüne geçti?', 'Which Italian club did Brazilian Ronaldo join from Barcelona?', '["Inter","Juventus","AC Milan","Lazio"]'::jsonb),
  ('San Antonio Spurs''ün 1999-2014 arasındaki beş şampiyonluğunda koçu kimdi?', 'Who coached the San Antonio Spurs through their five championships between 1999 and 2014?', '["Gregg Popovich","Phil Jackson","Mike D’Antoni","Rudy Tomjanovich"]'::jsonb),
  ('1970 Dünya Kupası finalinde Pelé''nin pasıyla Brezilya''nın dördüncü golünü atan kimdi?', 'Who scored Brazil''s fourth goal from Pele''s pass in the 1970 World Cup final?', '["Carlos Alberto","Jairzinho","Roberto Rivellino","Tostão"]'::jsonb),
  ('2000 Sydney''de kadınlar maratonunu kazanan Japon atlet kimdi?', 'Which Japanese runner won the women''s marathon at Sydney 2000?', '["Naoko Takahashi","Mizuki Noguchi","Kiyoko Shimahara","Yoshimi Ozaki"]'::jsonb),
  ('Andre Agassi''nin olimpiyat tekler altını kazandığı ABD kenti hangisidir?', 'In which US city did Andre Agassi win Olympic singles gold?', '["Atlanta","Los Angeles","Salt Lake City","St. Louis"]'::jsonb),
  ('Boca Juniors''ın ''La Bombonera'' stadının lakabı hangi nesne anlamına gelir?', 'What object does Boca Juniors'' stadium nickname La Bombonera mean?', '["Chocolate box","Music box","Matchbox","Jewellery box"]'::jsonb),
  ('1970 Dünya Kupası''nda Pelé''nin kafa vuruşunu çıkaran İngiliz kaleci kimdi?', 'Which England goalkeeper famously saved Pele''s header at the 1970 World Cup?', '["Gordon Banks","Peter Shilton","Ray Clemence","Joe Corrigan"]'::jsonb),
  ('1912''de batan Titanic''in kurtulanlarını alan gemi hangisidir?', 'Which ship rescued survivors of the Titanic''s sinking in 1912?', '["Carpathia","Californian","Olympic","Lusitania"]'::jsonb),
  ('Fransa İmparatoru Napolyon''un 1796''da evlendiği ilk eşinin adı nedir?', 'What was the name of Napoleon''s first wife, whom he married in 1796?', '["Joséphine","Marie-Louise","Hortense","Désirée"]'::jsonb),
  ('Napolyon Bonapart''ın Joséphine''den sonraki eşinin adı nedir?', 'What was the name of Napoleon Bonaparte''s wife after Josephine?', '["Marie Louise","Maria Carolina","Marie Thérèse","Maria Christina"]'::jsonb),
  ('Roma İmparatoru Caligula''nın ünlü atının adı nedir?', 'What was the name of Emperor Caligula''s famous horse?', '["Incitatus","Bucephalus","Marengo","Copenhagen"]'::jsonb),
  ('Sezar''ın aşarak Roma''da iç savaşı başlattığı İtalyan akarsuyu hangisidir?', 'Which Italian river did Caesar cross to begin a Roman civil war?', '["Rubicon","Arno","Tiber","Volturno"]'::jsonb),
  ('Gandhi''nin 1930''daki ünlü yürüyüşünde Britanya tekeline karşı ürettiği madde neydi?', 'What substance did Gandhi make to defy a British monopoly during his 1930 march?', '["Salt","Sugar","Tobacco","Cotton"]'::jsonb),
  ('Roosevelt''i atom bombası ihtimali konusunda uyaran 1939 mektubunu imzalayan fizikçi kimdi?', 'Which physicist signed the 1939 letter warning Roosevelt about the possibility of an atomic bomb?', '["Albert Einstein","Niels Bohr","Ernest Rutherford","Werner Heisenberg"]'::jsonb),
  ('VI. George tahta çıkmadan önce ailesinde hangi adla çağrılırdı?', 'What name was George VI known by within his family before becoming king?', '["Bertie","Dickie","Eddie","Georgie"]'::jsonb),
  ('Berlin Duvarı''nın simgesel sınır geçişi Checkpoint Charlie''deki askerî kontrol hangi ülkeye aitti?', 'Which country operated the military checkpoint at Checkpoint Charlie in Berlin?', '["United States","France","United Kingdom","Soviet Union"]'::jsonb),
  ('Camp David görüşmelerinde İsrail''i temsil eden başbakan kimdi?', 'Which Israeli prime minister took part in the Camp David negotiations?', '["Menachem Begin","Yitzhak Rabin","Shimon Peres","David Ben-Gurion"]'::jsonb),
  ('III. Richard''ın ölümüne ve Tudor hanedanının yükselişine yol açan savaş hangisidir?', 'Which battle led to Richard III''s death and the rise of the Tudor dynasty?', '["Bosworth","Towton","Tewkesbury","Agincourt"]'::jsonb),
  ('VIII. Edward''ın tahttan çekilince aldığı soyluluk unvanı nedir?', 'What title did Edward VIII receive after abdicating?', '["Duke of Windsor","Duke of York","Duke of Kent","Duke of Gloucester"]'::jsonb),
  ('''Ya özgürlük ya ölüm!'' sözüyle tanınan Amerikan bağımsızlık yanlısı kimdir?', 'Which supporter of American independence is known for saying Give me liberty or give me death?', '["Patrick Henry","Samuel Adams","Thomas Jefferson","Benjamin Franklin"]'::jsonb),
  ('1633''te Engizisyon önünde Dünya''nın hareketinden vazgeçmeye zorlanan bilim insanı kimdi?', 'Which scientist was forced to recant Earth''s motion before the Inquisition in 1633?', '["Galileo Galilei","Johannes Kepler","Tycho Brahe","Christiaan Huygens"]'::jsonb),
  ('İmparator Justinianus''un yönettiği imparatorluk hangisiydi?', 'Which empire did Emperor Justinian rule?', '["Byzantine Empire","Sasanian Empire","Carolingian Empire","Holy Roman Empire"]'::jsonb),
  ('Japonya''daki Meiji Restorasyonu''nun adını aldığı imparator kimdir?', 'Which emperor gave his name to Japan''s Meiji Restoration?', '["Mutsuhito","Yoshihito","Hirohito","Akihito"]'::jsonb),
  ('1917 Rus Devrimi''nin simgesi olan Aurora hangi tür araçtı?', 'What type of vessel was the Aurora, a symbol of the 1917 Russian Revolution?', '["Cruiser","Submarine","Destroyer","Minelayer"]'::jsonb),
  ('Fransız Devrimi''nin simgesel başlangıcında basılan Bastille ne tür binaydı?', 'What kind of building was the Bastille, stormed at the symbolic start of the French Revolution?', '["Prison","City hall","Royal theatre","Mint"]'::jsonb),
  ('İngiltere Kralı II. Charles''a sığınak olan ünlü ağaç hangi türdendi?', 'What kind of tree famously sheltered King Charles II of England?', '["Oak","Elm","Beech","Chestnut"]'::jsonb),
  ('Florence Nightingale hangi sağlık mesleğinin öncülerindendir?', 'Which healthcare profession did Florence Nightingale help pioneer?', '["Nursing","Dentistry","Pharmacy","Veterinary medicine"]'::jsonb),
  ('1933''teki büyük yangını Nazi baskısının gerekçesi yapılan Berlin binası hangisidir?', 'Which Berlin building''s 1933 fire was used to justify Nazi repression?', '["Reichstag","Brandenburg Gate","Charlottenburg Palace","Berlin Cathedral"]'::jsonb),
  ('Rosetta Taşı''nda hiyeroglif ve Yunanca dışında hangi yazı yer alır?', 'Besides hieroglyphs and Greek, what script appears on the Rosetta Stone?', '["Demotic","Cuneiform","Aramaic","Phoenician"]'::jsonb),
  ('Çar I. Petro Avrupa gezisinde Hollanda''da hangi işte çalıştı?', 'What trade did Peter the Great practise in the Netherlands during his European tour?', '["Shipbuilding","Clockmaking","Glassblowing","Silk weaving"]'::jsonb),
  ('1917 Cambrai Savaşı''nda Britanya''nın topluca kullandığı yeni savaş aracı hangisiydi?', 'Which new weapon did Britain deploy en masse at the Battle of Cambrai in 1917?', '["Tank","Submarine","Zeppelin","Armoured train"]'::jsonb),
  ('İbn Battuta''nın yolculuklarını anlatan eser genellikle hangi kısa adla anılır?', 'By what short title is the account of Ibn Battuta''s travels commonly known?', '["Rihla","Muqaddimah","Shahnameh","Siyasatnama"]'::jsonb),
  ('Roma''ya karşı mücadele eden Kraliçe Zenobia''nın merkezi hangi antik kentti?', 'Which ancient city was Queen Zenobia''s capital in her struggle against Rome?', '["Palmyra","Antioch","Alexandria","Petra"]'::jsonb),
  ('1970''te Varşova Gettosu anıtı önünde diz çöken Alman şansölyesi kimdi?', 'Which German chancellor knelt before the Warsaw Ghetto memorial in 1970?', '["Willy Brandt","Helmut Schmidt","Konrad Adenauer","Ludwig Erhard"]'::jsonb),
  ('1945 Potsdam görüşmelerinde Britanya''yı Churchill''in yerine temsil etmeye başlayan başbakan kimdi?', 'Which prime minister replaced Churchill as Britain''s representative during the 1945 Potsdam Conference?', '["Clement Attlee","Anthony Eden","Neville Chamberlain","Stanley Baldwin"]'::jsonb),
  ('Magna Carta ilk kez hangi hükümdarlık simgesiyle onaylandı?', 'What royal device was used to authenticate the original Magna Carta?', '["Seal","Handwritten signature","Fingerprint","Engraved monogram"]'::jsonb),
  ('Churchill''in ''Demir Perde'' konuşmasını yaptığı Amerikan kenti hangisidir?', 'In which American town did Churchill deliver his Iron Curtain speech?', '["Fulton","Dayton","Topeka","Lincoln"]'::jsonb),
  ('''Otomatik Portakal'' filmini kim yönetmiştir?', 'Who directed ''A Clockwork Orange''?', '["Stanley Kubrick","Martin Scorsese","Robert Zemeckis","Steven Spielberg"]'::jsonb),
  ('''Terminatör'' filmini kim yönetmiştir?', 'Who directed ''The Terminator''?', '["James Cameron","David Fincher","Peter Jackson","Ridley Scott"]'::jsonb),
  ('''Büyük Budapeşte Oteli'' filmini kim yönetmiştir?', 'Who directed ''The Grand Budapest Hotel''?', '["Wes Anderson","Noah Baumbach","Sofia Coppola","David O. Russell"]'::jsonb),
  ('''La La Land'' filmini kim yönetmiştir?', 'Who directed ''La La Land''?', '["Damien Chazelle","Rob Marshall","Baz Luhrmann","Kenneth Branagh"]'::jsonb),
  ('''Guguk Kuşu''ndaki McMurphy karakterini hangi oyuncu canlandırmıştır?', 'Which actor played McMurphy in One Flew Over the Cuckoo''s Nest?', '["Jack Nicholson","Robert De Niro","Robin Williams","Morgan Freeman"]'::jsonb),
  ('''Yüzüklerin Efendisi'' filmlerindeki Aragorn karakterini hangi oyuncu canlandırmıştır?', 'Which actor played Aragorn in The Lord of the Rings?', '["Viggo Mortensen","Anthony Hopkins","Joaquin Phoenix","Robert De Niro"]'::jsonb),
  ('The Lord of the Rings''teki Gandalf karakterini hangi oyuncu canlandırmıştır?', 'Which actor played Gandalf in The Lord of the Rings?', '["Ian McKellen","Bruce Willis","Keanu Reeves","Heath Ledger"]'::jsonb),
  ('''Cinema Paradiso'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''Cinema Paradiso''?', '["Ennio Morricone","Alan Silvestri","Bernard Herrmann","Rachel Portman"]'::jsonb),
  ('''Can Dostum''un senaryosunu Matt Damon ile birlikte yazan oyuncu kimdir?', 'Which actor co-wrote ''Good Will Hunting'' with Matt Damon?', '["Ben Affleck","Casey Affleck","Mark Wahlberg","Edward Norton"]'::jsonb),
  ('''Bugün Aslında Dündü''de Phil Connors televizyon için hangi mesleği yapar?', 'What is Phil Connors''s television job in ''Groundhog Day''?', '["Weatherman","Sports commentator","News cameraman","Game-show host"]'::jsonb),
  ('''Amélie''nin Paris''te çalıştığı işletme hangisidir?', 'What kind of business does Amélie work in in Paris?', '["Café","Bookshop","Florist''s","Bakery"]'::jsonb),
  ('''Yaratık'' serisindeki büyük şirketin adı nedir?', 'What is the major corporation in the ''Alien'' series called?', '["Weyland-Yutani","Tyrell Corporation","Cyberdyne Systems","Omni Consumer Products"]'::jsonb),
  ('''Büyük Budapeşte Oteli''nde M. Gustave''ın oteldeki görevi nedir?', 'What is M. Gustave''s hotel job in ''The Grand Budapest Hotel''?', '["Concierge","Head chef","Accountant","Security manager"]'::jsonb),
  ('''Akıl Defteri''nde Leonard''ın hatırlamak için bedenine eklediği şeyler nelerdir?', 'What does Leonard add to his body as memory aids in ''Memento''?', '["Tattoos","Scars","Piercings","Painted patterns"]'::jsonb),
  ('''Geleceğe Dönüş''te Doc Brown''ın köpeğinin adı nedir?', 'What is Doc Brown''s dog''s name in Back to the Future?', '["Einstein","Newton","Darwin","Copernicus"]'::jsonb),
  ('''Ucuz Roman''da Vincent Avrupa''da hangi hamburger adını ''Royale with Cheese'' diye anlatır?', 'Which burger does Vincent call a Royale with Cheese in Pulp Fiction?', '["Quarter Pounder","Big Mac","Whopper","Double Cheeseburger"]'::jsonb),
  ('''Esaretin Bedeli''nde Andy''nin hücre tünelini kazmakta kullandığı küçük alet nedir?', 'What small tool does Andy use to dig his cell tunnel in The Shawshank Redemption?', '["Rock hammer","Metal file","Small chisel","Hand drill"]'::jsonb),
  ('''Gladyatör''de Maximus''a gladyatörlük yaptıran eski gladyatörün adı nedir?', 'What is the name of the former gladiator who owns Maximus in Gladiator?', '["Proximo","Commodus","Quintus","Falco"]'::jsonb),
  ('''Otomatik Portakal''daki Alex hangi bestecinin müziğine tutkuyla bağlıdır?', 'Which composer''s music is Alex obsessed with in A Clockwork Orange?', '["Beethoven","Brahms","Tchaikovsky","Rachmaninoff"]'::jsonb),
  ('''Léon'' filminde başkahramanın sürekli yanında taşıdığı ev eşyası nedir?', 'What household item does the title character keep with him in Leon?', '["Potted plant","Wooden clock","Ceramic vase","Framed mirror"]'::jsonb),
  ('İspanya''da içecek yanında sunulan küçük atıştırmalık tabaklarına ne ad verilir?', 'What are the small snack dishes served with drinks in Spain called?', '["Tapas","Antipasti","Dim sum","Banchan"]'::jsonb),
  ('Kore sofrasında ana yemeğin çevresine dizilen küçük yan yemeklerin ortak adı nedir?', 'What are the small side dishes arranged around a Korean main meal called?', '["Banchan","Yakitori","Satay","Tempura"]'::jsonb),
  ('Meksika Ölüler Günü sunaklarında yaygın olarak hangi çiçek kullanılır?', 'What flower is commonly used on Mexican Day of the Dead altars?', '["Marigold","White lily","Red carnation","Blue hyacinth"]'::jsonb),
  ('İsveç''te Aziz Lucia Günü''yle ilişkilendirilen safranlı çöreğin adı nedir?', 'What is the saffron bun associated with Saint Lucia''s Day in Sweden called?', '["Lussekatt","Semla","Kanelbulle","Kardemummabulle"]'::jsonb),
  ('İskoç kiltinin önünde taşınan küçük kesenin adı nedir?', 'What is the small pouch worn at the front of a Scottish kilt called?', '["Sporran","Tam o'' shanter","Balmoral","Glengarry"]'::jsonb),
  ('Geleneksel bindi süsü yüzde nereye yerleştirilir?', 'Where on the face is a traditional bindi placed?', '["On the forehead","On the chin","On the cheek","On the nose tip"]'::jsonb),
  ('Brezilya''da yılbaşı gecesi uğur ve barış için yaygın olarak hangi renk giyilir?', 'What colour is widely worn for peace and good luck on New Year''s Eve in Brazil?', '["White","Red","Black","Purple"]'::jsonb),
  ('Buenos Aires ve Montevideo ile özdeşleşen çift dansı hangisidir?', 'Which partner dance is associated with Buenos Aires and Montevideo?', '["Tango","Samba","Rumba","Bachata"]'::jsonb),
  ('Tayland''da Songkran kutlamalarında insanların birbirine sıçrattığı şey nedir?', 'What do people splash on one another during Thailand''s Songkran celebrations?', '["Water","Coloured powder","Flower petals","Rice grains"]'::jsonb),
  ('Portekiz pastel de nata tatlısının iç dolgusunda hangi malzeme belirgindir?', 'Which ingredient is central to the filling of Portuguese pastel de nata?', '["Egg","Almond","Coconut","Chocolate"]'::jsonb),
  ('İspanya''da yılbaşı gece yarısındaki on iki çan vuruşunda hangi meyve yenir?', 'What fruit is eaten with the twelve midnight chimes on New Year''s Eve in Spain?', '["Grape","Cherry","Olive","Date"]'::jsonb),
  ('Klasik banana split servisinde muz nasıl hazırlanır?', 'How is the banana prepared in a classic banana split?', '["Split lengthways","Cut into round slices","Mashed into a puree","Diced into cubes"]'::jsonb),
  ('Endonezya batik kumaşı boyanırken desenli alanları korumak için ne kullanılır?', 'What is used to protect patterned areas while dyeing Indonesian batik fabric?', '["Wax","Clay paste","Rice flour","Plant resin"]'::jsonb),
  ('Yunan vasilopita yılbaşı pastasının içine hangi nesne saklanır?', 'What object is hidden in a Greek vasilopita New Year''s cake?', '["Coin","Small key","Metal ring","Glass bead"]'::jsonb),
  ('Amritsar''daki Altın Tapınak hangi dinin önemli ibadet yeridir?', 'The Golden Temple in Amritsar is an important place of worship for which religion?', '["Sikhism","Hinduism","Buddhism","Jainism"]'::jsonb),
  ('Kare üstlü klasik mezuniyet başlığı üzerinde sarkan parça nedir?', 'What hangs from a traditional square-topped graduation cap?', '["Tassel","Ribbon","Feather plume","Chain"]'::jsonb),
  ('Klasik 3×3 Rubik küpünde merkez parçalarının toplam sayısı kaçtır?', 'How many centre pieces are on a classic 3-by-3 Rubik''s Cube?', '["6","4","8","12"]'::jsonb),
  ('Klasik Zippo çakmağının metal kapağı gövdeye neyle bağlanır?', 'What connects a classic Zippo lighter''s metal lid to its body?', '["Hinge","Screw","Chain","Magnet"]'::jsonb),
  ('Klasik LEGO parçalarının üstündeki çıkıntılar hangi biçimdedir?', 'What shape are the studs on classic LEGO bricks?', '["Circle","Square","Triangle","Hexagon"]'::jsonb),
  ('Standart 52 kartlık destede her bir sembolden kaç kart vardır?', 'How many cards belong to each suit in a standard 52-card deck?', '["13","12","14","15"]'::jsonb),
  ('Klasik tirbuşonun mantara giren metal parçası hangi biçimdedir?', 'What shape is the metal part of a traditional corkscrew that enters the cork?', '["Spiral","Hook","Straight nail","Saw tooth"]'::jsonb),
  ('Geleneksel cappuccino yüzeyindeki kalın açık renkli tabaka nedir?', 'What is the thick pale layer on top of a traditional cappuccino?', '["Milk foam","Cream jelly","Sugar crust","Egg white"]'::jsonb),
  ('Almanya''da ilk okul gününde çocuklara verilen Schultüte hangi biçimdedir?', 'What shape is the Schultute given to children on their first school day in Germany?', '["Cone","Cube","Sphere","Cylinder"]'::jsonb),
  ('Danimarka Noel geleneğinde nisse için bırakılan risengrød hangi tahılla yapılır?', 'What grain is used in the risengrod left for the nisse in Danish Christmas tradition?', '["Rice","Oats","Barley","Wheat"]'::jsonb),
  ('Anzak Günü''nde anmayı simgelemek için yakaya takılan bitki hangisidir?', 'What herb is worn for remembrance on Anzac Day?', '["Rosemary","Lavender","Basil","Thyme"]'::jsonb),
  ('Çek Paskalya geleneğindeki pomlázka geleneksel olarak hangi ağacın dallarından örülür?', 'Which tree''s branches are traditionally woven into a Czech Easter pomlazka?', '["Willow","Birch","Oak","Poplar"]'::jsonb),
  ('Macar gulaşına karakteristik rengini veren baharat hangisidir?', 'Which spice gives Hungarian goulash its characteristic colour?', '["Paprika","Turmeric","Saffron","Cumin"]'::jsonb),
  ('Hint mehndi düğün süslemesinde ele sürülen boya hangi bitkiden elde edilir?', 'From which plant is the dye for Indian mehndi wedding decoration obtained?', '["Henna","Indigo","Turmeric","Saffron"]'::jsonb),
  ('Maori hongi selamında geleneksel olarak hangi yüz bölümü birbirine değdirilir?', 'Which part of the face is traditionally pressed together in a Maori hongi greeting?', '["Nose","Chin","Cheek","Lips"]'::jsonb),
  ('Mahjong oyununda dört oyuncunun yön adları arasında ilk dağıtıcı hangisidir?', 'Which wind designation belongs to the first dealer in a four-player mahjong game?', '["East","West","North","South"]'::jsonb),
  ('Churros hamuru geleneksel olarak nasıl pişirilir?', 'How is churros dough traditionally cooked?', '["Deep-fried","Steamed","Oven-dried","Boiled in water"]'::jsonb),
  ('Japon Setsubun geleneğinde evden kötü ruhları kovmak için ne atılır?', 'What is thrown to drive away evil spirits during Japan''s Setsubun tradition?', '["Roasted soybeans","Dried chickpeas","Roasted chestnuts","Unshelled peanuts"]'::jsonb),
  ('Batı düğün geleneğinde gelinin geriye doğru attığı nesne nedir?', 'What does the bride throw backwards in a Western wedding tradition?', '["Flower bouquet","Pearl necklace","Lace veil","Satin glove"]'::jsonb),
  ('Vietnam''ın taze gỏi cuốn ruloları geleneksel olarak neyle sarılır?', 'What traditionally wraps Vietnamese fresh goi cuon rolls?', '["Rice paper","Corn husk","Wheat flatbread","Cabbage leaf"]'::jsonb),
  ('Etiyopya sofrasında yemeklerin üzerinde sunulduğu gözenekli yassı ekmeğin adı nedir?', 'What is the porous flatbread used as the base for meals in Ethiopia called?', '["Injera","Chapati","Lavash","Paratha"]'::jsonb),
  ('Norveç kransekake pastası geleneksel olarak hangi biçimli katlardan oluşur?', 'What shape are the stacked layers of a traditional Norwegian kransekake?', '["Ring","Square","Star","Triangle"]'::jsonb),
  ('''Çukurlar'' romanının yazarı kimdir?', 'Who wrote ''Holes''?', '["Louis Sachar","Roald Dahl","Jerry Spinelli","Andrew Clements"]'::jsonb),
  ('''Doktor Dolittle''ın Hikâyesi'' kitabının yazarı kimdir?', 'Who wrote ''The Story of Doctor Dolittle''?', '["Hugh Lofting","A. A. Milne","Kenneth Grahame","Beatrix Potter"]'::jsonb),
  ('''Hobbit''te Bilbo''nun Sting adlı silahı hangi türdedir?', 'What kind of weapon is Bilbo''s Sting in The Hobbit?', '["Sword","Axe","Spear","Dagger"]'::jsonb),
  ('Harry Potter''daki Erised hangi nesnedir?', 'What kind of object is Erised in Harry Potter?', '["Mirror","Sword","Ring","Necklace"]'::jsonb),
  ('Küçük Kadınlar''da Jo''nun en küçük kardeşinin adı nedir?', 'What is the name of Jo''s youngest sister in Little Women?', '["Amy","Beth","Meg","Jo"]'::jsonb),
  ('Harry Potter''ın alnındaki yara izi hangi biçimdedir?', 'What shape is Harry Potter''s forehead scar?', '["Lightning bolt","Five-pointed star","Crescent moon","Curved arrow"]'::jsonb),
  ('Anton Çehov edebiyatın yanında hangi mesleği yapmıştır?', 'What profession did Anton Chekhov practise alongside writing?', '["Doctor","Lawyer","Engineer","Pharmacist"]'::jsonb),
  ('''1984''te Winston Smith''in işvereni olan kurum hangisidir?', 'Which institution employs Winston Smith in ''Nineteen Eighty-Four''?', '["Ministry of Truth","Ministry of Love","Ministry of Peace","Ministry of Plenty"]'::jsonb),
  ('''Oz Büyücüsü'' kitabında Korkuluk ne elde etmek ister?', 'What does the Scarecrow seek in the book ''The Wonderful Wizard of Oz''?', '["Brain","Heart","Courage","Voice"]'::jsonb),
  ('''Sherlock Holmes'' öykülerindeki Dr. Watson''ın ilk adı nedir?', 'What is Dr Watson''s first name in the Sherlock Holmes stories?', '["John","James","William","Henry"]'::jsonb),
  ('Pippi Uzunçorap''ın kızıl saçları hangi biçimde kullanılır?', 'How does Pippi Longstocking wear her red hair?', '["Two braids","One ponytail","Short bob","Bun"]'::jsonb),
  ('Paddington Ayısı hangi renk pardösüyle tanınır?', 'What colour duffle coat is Paddington Bear known for?', '["Blue","Red","Green","Yellow"]'::jsonb),
  ('Pinokyo okulu bırakıp eğlenceye dalınca hangi hayvana dönüşür?', 'What animal does Pinocchio turn into after abandoning school for endless fun?', '["Donkey","Pig","Rabbit","Dog"]'::jsonb),
  ('''Büyük Umutlar''da Bayan Havisham''ın durmuş saatleri günün hangi olayını simgeler?', 'What event is symbolised by Miss Havisham''s stopped clocks in Great Expectations?', '["Her cancelled wedding","Her father''s funeral","Her sister''s departure","Her husband''s death"]'::jsonb),
  ('''Yaşlı Adam ve Deniz''de Santiago''nun yakaladığı büyük balık hangi türdür?', 'What kind of large fish does Santiago catch in The Old Man and the Sea?', '["Marlin","Tuna","Shark","Swordfish"]'::jsonb),
  ('''Bülbülü Öldürmek''te Scout''un ağabeyinin lakabı nedir?', 'What is Scout''s older brother''s nickname in To Kill a Mockingbird?', '["Jem","Dill","Boo","Huck"]'::jsonb),
  ('Peter Pan''da timsahın yuttuğu nesne nedir?', 'What object did the crocodile swallow in Peter Pan?', '["Clock","Compass","Bell","Whistle"]'::jsonb),
  ('''Otostopçunun Galaksi Rehberi''nde Dünya''ya çoktan gelmiş Ford Prefect kendisini hangi işte gösterir?', 'What profession does Ford Prefect pretend to have on Earth in The Hitchhiker''s Guide to the Galaxy?', '["Actor","Journalist","Teacher","Pilot"]'::jsonb),
  ('''Bitmeyecek Öykü'' romanının özgün Almanca metninde şans ejderhasının adı nedir?', 'What is the luckdragon called in the original German novel The Neverending Story?', '["Fuchur","Gmork","Atreju","Bastian"]'::jsonb)
  ) v(soru, en_soru, en_secenekler)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Karıştırma (TR + EN aynı permütasyon)
drop table if exists pg_temp._parti_karistir;
create temp table _parti_karistir as
select q.id, array_agg(s.idx order by s.rnd) as perm
  from public.questions q
  cross join lateral (
    select (ordinality - 1)::int as idx, random() as rnd
      from jsonb_array_elements(q.secenekler) with ordinality
  ) s
 where q.created_at >= transaction_timestamp()
 group by q.id;

update public.questions q
   set secenekler = (select jsonb_agg(q.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o)),
       dogru_cevap = (array_position(k.perm, q.dogru_cevap::int) - 1)::smallint
  from _parti_karistir k
 where q.id = k.id;

update public.question_translations t
   set secenekler = (select jsonb_agg(t.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o))
  from _parti_karistir k
 where t.question_id = k.id;

drop table if exists pg_temp._parti_karistir;
