-- ============================================================
-- 004 — Şık ipucu düzeltmesi, parti 8 (8 Eki 2026, Claude API)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide işaretli kolay/orta
-- (zorluk 1–3) sorulardan 34 tanesinin YANLIŞ şıkları Claude API (claude-sonnet-5-5) ile yeniden yazıldı;
-- soru metni, doğru cevap ve doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar dört kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0.75), Jev tek doğru cevap kontrolü ve
-- yanlış şık başına ayrı Claude hakem çağrısı (kesin_yanlis). Geçemeyen sorulara dokunulmadı, işaretli kalır.
-- EN çeviri: aynı indekslerle güncellenir (EN çevirisi olmayan soruda yalnız TR). Üretici: araclar/soru-temizlik/sik-ipucu-api.mjs --tam
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 8   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('3906177c-d196-4f5d-a73d-eb5f16e7fc6c'::uuid, 3, '["Tek pil","Tek ekran","Tek kablo","Tek gövdede toplanmış devre elemanları"]'::jsonb, '["Tek gövdede toplanmış pil hücreleri","Tek levhada birleştirilmiş ekran panelleri","Tek kılıfta toplanmış iletken kablolar","Tek gövdede toplanmış devre elemanları"]'::jsonb, '["A single battery","A single screen","A single cable","Circuit elements gathered in one body"]'::jsonb, '["Battery cells gathered in one body","Display panels joined on a single sheet","Conductive cables bundled in one sheath","Circuit elements gathered in one body"]'::jsonb),
    ('3a679775-200c-4da9-b405-e48a186d2a95'::uuid, 0, '["Gündelik nesnenin sanat olarak sunulması","El yapımı eser","Kopya","Baskı"]'::jsonb, '["Gündelik nesnenin sanat olarak sunulması","Sanatçının ürettiği tek nüsha heykel","Ünlü bir tablonun sonradan yapılan taklidi","Doğadan toplanan malzemelerle yapılan düzenleme"]'::jsonb, '["Presenting an everyday object as art","A handmade work","A copy","A print"]'::jsonb, '["Presenting an everyday object as art","A one-of-a-kind sculpture made by the artist","A later imitation of a famous painting","An arrangement made from materials gathered in nature"]'::jsonb),
    ('f21670d4-031b-4bbf-b8ec-05954154802f'::uuid, 3, '["Aşırı soğuk","Çöl iklimi","Kuraklık","Bol yağış ve ılıman sıcaklık"]'::jsonb, '["Az yağış ve sert kışlar","Kurak ve yarı kurak step koşulları","Çok sıcak ve yağışsız yazlar","Bol yağış ve ılıman sıcaklık"]'::jsonb, '["Extreme cold","Desert climate","Drought","Plenty of rain and mild temperatures"]'::jsonb, '["Low rainfall and harsh winters","Dry and semi-arid steppe conditions","Very hot and rainless summers","Plenty of rain and mild temperatures"]'::jsonb),
    ('ec71147d-552f-4959-bfa1-e07ab1c010fb'::uuid, 1, '["Belge","İstenmeyen davranışa yol açan hata","Test","Yeni özellik"]'::jsonb, '["Kodun çalışma hızını artıran iyileştirme","İstenmeyen davranışa yol açan hata","Kullanıcıya gösterilen uyarı mesajı","Sistemin yetkisiz erişime karşı korunması"]'::jsonb, '["A document","A fault causing unwanted behaviour","A test","A new feature"]'::jsonb, '["An improvement that boosts code speed","A fault causing unwanted behaviour","A warning message shown to the user","Protection of a system against unauthorised access"]'::jsonb),
    ('888de49b-b39f-42e1-8784-f4f25a807278'::uuid, 3, '["Kasta","Kemikte","Damarda","İki nöron arasında"]'::jsonb, '["Kas lifleri içinde","İki kemik arasında","Kan damarı çeperinde","İki nöron arasında"]'::jsonb, '["In muscle","In bone","In a blood vessel","Between two neurons"]'::jsonb, '["Inside muscle fibers","Between two bones","In a blood vessel wall","Between two neurons"]'::jsonb),
    ('71807dcb-4b77-4efd-825c-5cac51c46d55'::uuid, 1, '["Veri saklar","İstekleri aracı olarak iletir","Kod derler","Ekran kaydeder"]'::jsonb, '["Verileri şifreleyerek yedekler","İstekleri aracı olarak iletir","Ağ cihazlarına IP adresi atar","Alan adlarını IP adreslerine çevirir"]'::jsonb, '["Stores data","Relays requests as an intermediary","Compiles code","Records the screen"]'::jsonb, '["Encrypts and backs up data","Relays requests as an intermediary","Assigns IP addresses to network devices","Translates domain names into IP addresses"]'::jsonb),
    ('4ac56261-cfe3-4402-af22-74f15c6f5879'::uuid, 0, '["Eğim ve kar birikimi","Yağmur","Sıcaklık artışı yalnızca","Rüzgâr yokluğu"]'::jsonb, '["Eğim ve kar birikimi","Deniz seviyesine uzaklık","Yer altı su seviyesi","Ay''ın evreleri"]'::jsonb, '["Slope and accumulated snow","Rain","A rise in temperature alone","The absence of wind"]'::jsonb, '["Slope and accumulated snow","Distance from sea level","Groundwater level","Phases of the Moon"]'::jsonb),
    ('5a905f92-d1d7-4390-8108-f351fdb6f206'::uuid, 1, '["Brno","Prag","Ostrava","Bratislava"]'::jsonb, '["Viyana","Prag","Budapeşte","Varşova"]'::jsonb, '["Brno","Prague","Ostrava","Bratislava"]'::jsonb, '["Vienna","Prague","Budapest","Warsaw"]'::jsonb),
    ('0a5e9518-8cfd-4d10-b03d-8bdc78646544'::uuid, 2, '["Sonsuz döngüde tekrarlamayı","Bellekteki veriyi silmeyi","Duruma göre farklı yol izlemeyi","İşlem hızını yükseltmeyi"]'::jsonb, '["Kod bloğunu tekrar tekrar çalıştırmayı","Verileri sıralı biçimde saklamayı","Duruma göre farklı yol izlemeyi","Programı farklı dillere çevirmeyi"]'::jsonb, '["Infinite repetition","Deleting data","Following different paths depending on the situation","An increase in speed"]'::jsonb, '["Running a code block repeatedly","Storing data in an ordered form","Following different paths depending on the situation","Translating a program into other languages"]'::jsonb),
    ('f1a9ed3d-1888-497e-be90-b478282fccb9'::uuid, 3, '["Atığı yakmak","Atığı denize dökmek","Atığı gömmemek","Çevreye sızıntıyı engellemek"]'::jsonb, '["Atığı geri dönüştürmek","Atığı açık havada bırakmak","Atığı enerjiye dönüştürmek","Çevreye sızıntıyı engellemek"]'::jsonb, '["Burning the waste","Dumping the waste at sea","Not burying the waste","Preventing leakage into the environment"]'::jsonb, '["Recycling the waste","Leaving the waste in the open air","Converting the waste into energy","Preventing leakage into the environment"]'::jsonb),
    ('1e02a2fe-e2a3-4eb9-ba43-cc17e1c2c72a'::uuid, 2, '["Page Down","Pause Break","Print Screen","Scroll Lock"]'::jsonb, '["Page Down","Pause Break","Print Screen","Scroll Lock"]'::jsonb, '["Page Down","Pause Break","Print Screen","Scroll Lock"]'::jsonb, '["Page Down","Pause Break","Print Screen","Scroll Lock"]'::jsonb),
    ('d89afc33-fd08-4eaf-9284-39844b4880a9'::uuid, 1, '["Toprağı kurutması","Erozyonu azaltıp organik madde katması","Tuzu artırması","Verimi düşürmesi"]'::jsonb, '["Toprak sıcaklığını sürekli yükseltip nemi azaltması","Erozyonu azaltıp organik madde katması","Toprak asitliğini artırıp mineralleri tüketmesi","Su tutma kapasitesini düşürüp çoraklaşmayı hızlandırması"]'::jsonb, '["It dries the soil","It reduces erosion and adds organic matter","It raises salinity","It lowers yields"]'::jsonb, '["It constantly raises soil temperature and reduces moisture","It reduces erosion and adds organic matter","It increases soil acidity and depletes minerals","It lowers water retention and speeds up desertification"]'::jsonb),
    ('001b9805-7f4e-4375-b17a-fb11fd8feacf'::uuid, 0, '["Tek dalga boylu ve düzenli","Çok dalga boylu ve dağınık","Geniş bantlı ve zayıf","Değişken boylu ve sönük"]'::jsonb, '["Tek dalga boylu ve düzenli","Çok dalga boylu ve dağınık","Geniş bantlı ve kararsız","Değişken boylu ve yönsüz"]'::jsonb, '["A single wavelength and coherent","Multicoloured","Scattered","Weak"]'::jsonb, '["A single wavelength and coherent","Many wavelengths and scattered","Broadband and unstable","Variable wavelength and directionless"]'::jsonb),
    ('401b2446-25ea-4bf9-a902-e4db0e2b9d88'::uuid, 3, '["Bakım maliyetini","Kullanıcı sayısını","Veri boyutunu","Hizmet veremediği süreyi"]'::jsonb, '["Sunucunun çalışma süresini","Sunucunun yanıt hızını","Yedekleme sıklığını","Hizmet veremediği süreyi"]'::jsonb, '["The maintenance cost","The number of users","The size of the data","The period when it cannot serve"]'::jsonb, '["The server''s running time","The server''s response speed","The backup frequency","The period when it cannot serve"]'::jsonb),
    ('73f83b7e-b00a-4369-97f3-3dd1f0e2024d'::uuid, 3, '["Bir protein türü","Bir hücre organeli","Bir hormon","Kalıtsal bilgi taşıyan DNA parçası"]'::jsonb, '["Hücre zarını oluşturan lipit tabakası","Protein sentezi yapan hücre yapısı","Kanda taşınan kimyasal haberci","Kalıtsal bilgi taşıyan DNA parçası"]'::jsonb, '["A kind of protein","A cell organelle","A hormone","A stretch of DNA carrying hereditary information"]'::jsonb, '["A lipid layer forming the cell membrane","A cell structure that makes proteins","A chemical messenger carried in the blood","A stretch of DNA carrying hereditary information"]'::jsonb),
    ('1517ae79-9e8c-494c-8be1-1518779b947c'::uuid, 0, '["Sağlık ve refah düzeyini","Yalnızca eğitim düzeyini","Yıllık ihracat hacmini","Ulaşım ağının düzeyini"]'::jsonb, '["Sağlık ve refah düzeyini","Tarımsal üretim düzeyini","Enerji tüketim düzeyini","Kentleşme ve ulaşım düzeyini"]'::jsonb, '["The level of health and welfare","Only the level of education","Exports","Transport"]'::jsonb, '["The level of health and welfare","The level of agricultural production","The level of energy consumption","The level of urbanization and transport"]'::jsonb),
    ('d01bc8f0-04c8-4e55-9d23-47efc41d5dbd'::uuid, 2, '["Kuvvet olarak","Manyetik alanla","Uzay zamanın bükülmesiyle","Isı akışıyla"]'::jsonb, '["Kütlelerin birbirini çekmesiyle","Elektrik yüklerinin etkileşimiyle","Uzay zamanın bükülmesiyle","Atom çekirdeğinin güçlü etkileşimiyle"]'::jsonb, '["As a force","Through a magnetic field","Through the curvature of spacetime","Through the flow of heat"]'::jsonb, '["Through the mutual attraction of masses","Through the interaction of electric charges","Through the curvature of spacetime","Through the strong nuclear interaction"]'::jsonb),
    ('014d42fc-f76d-4402-a3f3-ec41188a9c3a'::uuid, 1, '["Batum","Tiflis","Kutaisi","Gori"]'::jsonb, '["Erivan","Tiflis","Bakü","Trabzon"]'::jsonb, '["Batumi","Tbilisi","Kutaisi","Gori"]'::jsonb, '["Yerevan","Tbilisi","Baku","Trabzon"]'::jsonb),
    ('f2d92f35-2800-443c-a84d-84f65e476aed'::uuid, 3, '["Dosyaya bulaşmasıyla","Zarar vermemesiyle","Donanım olmasıyla","Kendi başına yayılabilmesiyle"]'::jsonb, '["Dosyaya bulaşmasıyla","Yalnızca e-postayla çalışmasıyla","Yalnızca internet tarayıcısında çalışmasıyla","Kendi başına yayılabilmesiyle"]'::jsonb, '["It infects a file","It does no harm","It is hardware","It can spread on its own"]'::jsonb, '["It infects a file","It only works through email","It only runs inside a web browser","It can spread on its own"]'::jsonb),
    ('33523ec8-6312-47c8-bbf5-fc91734bf934'::uuid, 0, '["Cihazların ağa bağlanmasını","Yalnız telefonları","Yalnız bilgisayarları","Yalnız sunucuları"]'::jsonb, '["Cihazların ağa bağlanmasını","Verilerin yalnızca bulutta saklanmasını","Web sitelerinin birbirine bağlanmasını","Yazılımların otomatik güncellenmesini"]'::jsonb, '["Devices being connected to the network","Only phones","Only computers","Only servers"]'::jsonb, '["Devices being connected to the network","Data being stored only in the cloud","Websites being linked to each other","Software being updated automatically"]'::jsonb),
    ('a0523806-3167-471d-b1d4-df16028a9c7b'::uuid, 2, '["Mantarlar","Ormanlardaki kuşlar","Deniz yosunları ve fitoplanktonlar","Bakteriler"]'::jsonb, '["Mercan kayalıkları ve süngerler","Tropikal yağmur ormanı böcekleri","Deniz yosunları ve fitoplanktonlar","Kutup bölgesi deniz memelileri"]'::jsonb, '["Fungi","Forest birds","Seaweed and phytoplankton","Bacteria"]'::jsonb, '["Coral reefs and sponges","Rainforest insects","Seaweed and phytoplankton","Polar marine mammals"]'::jsonb),
    ('e1b676b3-a143-4375-949f-7af7b99153e7'::uuid, 0, '["Toprağın verimini korumak için","Ürünü hızlandırmak için","Zararlıyı çoğaltmak için","Suyu artırmak için"]'::jsonb, '["Toprağın verimini korumak için","Tarım ürünlerini kurutmak için","Toprağı tuzlandırmak için","Tarlada rüzgarı kesmek için"]'::jsonb, '["To keep the soil fertile","To speed up the crop","To increase pests","To increase the water"]'::jsonb, '["To keep the soil fertile","To dry out the harvested crops","To make the soil salty","To block the wind in the field"]'::jsonb),
    ('9c45f636-85e2-4095-8de4-cb5c29c9ac8f'::uuid, 0, '["Tepkimeleri hızlandırması","Tepkimeyi durdurması","Enerji üretmesi","Hücre bölmesi"]'::jsonb, '["Tepkimeleri hızlandırması","Tepkimelerde tükenmesi","Hücreye şekil vermesi","Genetik bilgiyi saklaması"]'::jsonb, '["Speeding up reactions","Stopping reactions","Producing energy","Dividing the cell"]'::jsonb, '["Speeding up reactions","Being used up in reactions","Giving the cell its shape","Storing genetic information"]'::jsonb),
    ('936e03e4-c669-42ae-9afb-d1d08db9ea2b'::uuid, 0, '["Katıdan sıvıya geçiş için gereken ısı","Sıcaklık artışı","Hacim artışı","Kütle kaybı"]'::jsonb, '["Katıdan sıvıya geçiş için gereken ısı","Sıvıdan gaza geçiş için gereken ısı","Gazdan sıvıya geçerken açığa çıkan ısı","Maddenin sıcaklığını 1°C artıran ısı"]'::jsonb, '["The heat needed to go from solid to liquid","A rise in temperature","An increase in volume","A loss of mass"]'::jsonb, '["The heat needed to go from solid to liquid","The heat needed to go from liquid to gas","The heat released when going from gas to liquid","The heat that raises a substance''s temperature by 1°C"]'::jsonb),
    ('d2a12914-7dec-41f8-9eb9-5d6b044311d6'::uuid, 1, '["Ağır olması","Yüksek hız ve düşük kayıp","Ucuz olması yalnızca","Kısa mesafe"]'::jsonb, '["Elektrik akımıyla çalışması","Yüksek hız ve düşük kayıp","Bakır kabloya göre daha kalın olması","Yalnızca kısa mesafede çalışması"]'::jsonb, '["Being heavy","High speed and low loss","Being cheap alone","Short range"]'::jsonb, '["Running on electric current","High speed and low loss","Being thicker than copper cable","Working only over short distances"]'::jsonb),
    ('07bc0aea-2a94-4a66-b43a-5d005ce6f047'::uuid, 0, '["Hipokrat","Avicenna","Galen","Asklepios"]'::jsonb, '["Hipokrat","Herofilos","Dioskorides","Erasistratos"]'::jsonb, '["Hippocrates","Avicenna","Galen","Asclepius"]'::jsonb, '["Hippocrates","Herophilus","Dioscorides","Erasistratus"]'::jsonb),
    ('b18da7b6-a985-4c09-af14-383161c53ffe'::uuid, 1, '["Çözücü miktarını","Birim hacimdeki çözünen miktarını","Sıcaklığı","Basıncı"]'::jsonb, '["Birim kütledeki çözücü miktarını","Birim hacimdeki çözünen miktarını","Birim sıcaklıktaki ısı miktarını","Birim alandaki kuvvet miktarını"]'::jsonb, '["The amount of solvent","The amount of solute per unit volume","The temperature","The pressure"]'::jsonb, '["The amount of solvent per unit mass","The amount of solute per unit volume","The amount of heat per unit temperature","The amount of force per unit area"]'::jsonb),
    ('2d8f97da-881b-461b-a5da-6b86300ce376'::uuid, 2, '["Fazla uykuyla","Soğuk havayla yalnızca","Sıvı ve mineral kaybıyla","Yüksek rakımla"]'::jsonb, '["Aşırı D vitamini alımıyla","Kemik yoğunluğu artışıyla","Sıvı ve mineral kaybıyla","Gözlerin yorulmasıyla"]'::jsonb, '["Too much sleep","Cold weather alone","Loss of fluid and minerals","High altitude"]'::jsonb, '["Excess vitamin D intake","Increased bone density","Loss of fluid and minerals","Tired eyes"]'::jsonb),
    ('2ca2acba-d71a-4276-920c-7e005f72e315'::uuid, 3, '["Yağış miktarını","Rüzgâr hızını","Nüfus hareketini","Deniz altı deprem ve dalga verilerini"]'::jsonb, '["Atmosfer basıncı ve bulut hareketlerini","Yer altı suyu seviyesi ve nehir akışlarını","Okyanus tuzluluğu ve su sıcaklığı verilerini","Deniz altı deprem ve dalga verilerini"]'::jsonb, '["Rainfall amounts","Wind speed","Population movement","Undersea earthquake and wave data"]'::jsonb, '["Atmospheric pressure and cloud movements","Groundwater levels and river flows","Ocean salinity and water temperature data","Undersea earthquake and wave data"]'::jsonb),
    ('00a20e91-ffae-4f83-b8e2-470df21e55f9'::uuid, 1, '["Donanım modellerini","İki farklı sürümün etkisini","Renk paletlerini yalnızca","Sunucu markalarını"]'::jsonb, '["Yazılım lisans türlerinin maliyetini","İki farklı sürümün etkisini","Ağ bağlantı hızlarının farkını","Bulut depolama planlarının kapasitesini"]'::jsonb, '["Hardware models","The impact of two different versions","Colour palettes only","Server brands"]'::jsonb, '["The cost of software license types","The impact of two different versions","The difference in network connection speeds","The capacity of cloud storage plans"]'::jsonb),
    ('82caee88-8660-4b36-9b65-a5fe15a10cc6'::uuid, 3, '["Kütle çarpı hacim","Hacim bölü kütle","Kuvvet bölü alan","Kütle bölü hacim"]'::jsonb, '["Kuvvet bölü kütle","Yol bölü zaman","İş bölü zaman","Kütle bölü hacim"]'::jsonb, '["Mass times volume","Volume divided by mass","Force divided by area","Mass divided by volume"]'::jsonb, '["Force divided by mass","Distance divided by time","Work divided by time","Mass divided by volume"]'::jsonb),
    ('edbde11c-5c3b-449d-97cb-52dfa73674c9'::uuid, 2, '["Denize yakın","Yıl boyu yağışlı","Denizden uzak, sıcaklık farkı yüksek","Sıcaklık farkı düşük"]'::jsonb, '["Denize yakın, sıcaklık farkı düşük","Yıl boyu ılık, yağış bol","Denizden uzak, sıcaklık farkı yüksek","Denize komşu, kışlar ılık"]'::jsonb, '["Close to the sea","Rainy all year","Far from the sea, with a large temperature range","A small temperature range"]'::jsonb, '["Close to the sea, with a small temperature range","Warm all year, with heavy rainfall","Far from the sea, with a large temperature range","Next to the sea, with mild winters"]'::jsonb),
    ('67eb73f1-ed7b-489a-9759-59757ce76e03'::uuid, 0, '["Kodun kullanım ve dağıtım koşullarını","Sunucu ücretini","Ağ hızını","Tasarımı"]'::jsonb, '["Kodun kullanım ve dağıtım koşullarını","Yazılımın donanım gereksinimlerini","Geliştiricilerin çalışma saatlerini","Programın arayüz dilini ve çevirilerini"]'::jsonb, '["The terms of use and distribution of the code","The server fee","Network speed","The design"]'::jsonb, '["The terms of use and distribution of the code","The hardware requirements of the software","The working hours of the developers","The interface language and translations of the program"]'::jsonb),
    ('bbe849bd-7d6b-4e02-8613-65d3312a5434'::uuid, 3, '["Bulutlardan","Yağıştan","Sıcaklıktan","Güneş parçacıkları ve manyetik alandan"]'::jsonb, '["Atmosferdeki su buharı ve rüzgârlardan","Okyanus akıntıları ve tuzluluktan","Yer kabuğundaki volkanik gazlardan","Güneş parçacıkları ve manyetik alandan"]'::jsonb, '["Clouds","Precipitation","Temperature","Solar particles and the magnetic field"]'::jsonb, '["Water vapor and winds in the atmosphere","Ocean currents and salinity","Volcanic gases in the Earth''s crust","Solar particles and the magnetic field"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 8: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 8: yanlış şıklar yeniden yazıldı (004)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 8: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 8: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
