-- ============================================================
-- 420 — Şık ipucu düzeltmesi, parti 1/3 (23 Eyl 2026, Ajan J)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide 100 işaretli
-- kolay/orta (zorluk 1–3) sorunun YANLIŞ şıkları yeniden yazıldı; soru metni, doğru cevap ve
-- doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar üç kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0,8) ve tek doğru cevap kontrolü.
-- Geçen 87 soru yazılır ve işareti kaldırılır → rekabetçi havuza döner; 13 soru üç denemede
-- geçemedi, dokunulmadı (işaretli kalır). EN çeviri: 87 satır aynı indekslerle güncellenir.
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 1   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('dc647a19-4e85-46bf-8647-393ef2261b4d'::uuid, 1, '["Virüsü öldürerek","Bağışıklığı önceden hazırlayarak","Ateşi düşürerek","Ağrıyı kesip"]'::jsonb, '["Virüsü doğrudan öldürerek","Bağışıklığı önceden hazırlayarak","Bağışıklığı geçici durdurarak","Hazır antikor aktararak"]'::jsonb, '["By killing the virus","By preparing the immune system in advance","By lowering a fever","By relieving pain"]'::jsonb, '["By killing the virus directly","By preparing the immune system in advance","By pausing the immune system","By transferring ready-made antibodies"]'::jsonb),
    ('0720fd75-9537-47b6-9d0b-458dbbdd4ff9'::uuid, 3, '["Kiev","Minsk","St. Petersburg","Moskova"]'::jsonb, '["Prag","Varşova","Budapeşte","Moskova"]'::jsonb, '["Kyiv","Minsk","St Petersburg","Moscow"]'::jsonb, '["Prague","Warsaw","Budapest","Moscow"]'::jsonb),
    ('0a6192f5-1e47-4fbd-a980-68ae68c4e58d'::uuid, 0, '["Bir düşünce birimini","Tek bir uzun cümleyi","Bütün bir sayfayı","Bir kitap bölümünü"]'::jsonb, '["Bir düşünce birimini","Bir anlatım türünü","Bir metin başlığını","Bir cümle öğesini"]'::jsonb, '["A unit of thought","A sentence","A page","A chapter"]'::jsonb, '["A unit of thought","A literary genre","A text heading","A sentence element"]'::jsonb),
    ('7e3b0826-449b-42f3-bea9-fe8fa7256e70'::uuid, 3, '["Ürün satmak","Yalnız eğlendirmek","Yarışma yapmak","Bilgilendirmek"]'::jsonb, '["Ürün tanıtmak","Kurgu anlatmak","Oy toplamak","Bilgilendirmek"]'::jsonb, '["Selling a product","Merely entertaining","Running a competition","Informing"]'::jsonb, '["Promoting a product","Telling fiction","Winning votes","Informing"]'::jsonb),
    ('4cf870fa-31a3-4ee3-860f-5c9ee40de3b2'::uuid, 0, '["Gelecek ve teknoloji","Sadece geçmiş","Sadece tarım","Sadece spor"]'::jsonb, '["Gelecek ve teknoloji","Geçmiş ve efsaneler","Aşk ve aile","Suç ve adalet"]'::jsonb, '["The future and technology","The past only","Farming only","Sport only"]'::jsonb, '["The future and technology","The past and legends","Love and family","Crime and justice"]'::jsonb),
    ('305f1884-2cf8-4efc-826a-0d25c1ba5af5'::uuid, 3, '["Yalnız otopark","Yalnız bilet indirimi","Yalnız tabela","Rampa ve uygun donanımı"]'::jsonb, '["Aydınlatma ve jeneratör sistemini","Yangın çıkışı ve söndürücüyü","Soyunma odası ve duşları","Rampa ve uygun donanımı"]'::jsonb, '["Only parking","Only a ticket discount","Only signage","Ramps and suitable equipment"]'::jsonb, '["Floodlights and a generator","Fire exits and extinguishers","Changing rooms and showers","Ramps and suitable equipment"]'::jsonb),
    ('137dc199-d674-4d32-988a-853c85d50839'::uuid, 2, '["Saltanatın sürdürülmesini","Manda yönetimi kurulmasını","Egemenliğin millete ait olmasını","Federal yapıya geçilmesini"]'::jsonb, '["Din ve devlet işlerinin ayrılmasını","Toplumda sınıf ayrıcalığı olmamasını","Egemenliğin millete ait olmasını","Ekonomide devletin öncü olmasını"]'::jsonb, '["Keeping the sultanate","Establishing a mandate","Sovereignty belonging to the nation","Moving to a federal structure"]'::jsonb, '["Separating religion and state affairs","No class privilege in society","Sovereignty belonging to the nation","The state leading the economy"]'::jsonb),
    ('56d0c81f-0271-4ec7-b1b0-b1394e4c3ff2'::uuid, 2, '["Sesi yükseltmeyi","Kanalı çoğaltmayı","İstenmeyen sesi azaltmayı","Süreyi kısaltmayı"]'::jsonb, '["Yankıyı yapay olarak eklemeyi","Bas frekanslarını artırmayı","İstenmeyen sesi azaltmayı","Sesi odanın her yanına yaymayı"]'::jsonb, '["Raise the volume","Multiply the channels","Reduce unwanted sound","Shorten the duration"]'::jsonb, '["Artificially adding echo","Boosting bass frequencies","Reduce unwanted sound","Spreading sound around the room"]'::jsonb),
    ('046b138a-1728-49fe-8538-98e95a8147d9'::uuid, 3, '["Rengini açıp parlatmak","Tadını şekerle tatlandırmak","Kıvamını ağırlaştırmak","Zararlı mikropları azaltmak"]'::jsonb, '["Yağ damlacıklarını küçültmek","Suyunu buharlaştırmak","Laktozunu parçalamak","Zararlı mikropları azaltmak"]'::jsonb, '["To colour it","To sweeten it","To thicken it","To reduce harmful microbes"]'::jsonb, '["To break up fat droplets","To evaporate its water","To break down its lactose","To reduce harmful microbes"]'::jsonb),
    ('a4797081-d2c3-4f00-bc7c-28d3ad37217b'::uuid, 0, '["Dublin","Cork","Galway","Belfast"]'::jsonb, '["Dublin","Edinburgh","Cardiff","Belfast"]'::jsonb, '["Dublin","Cork","Galway","Belfast"]'::jsonb, '["Dublin","Edinburgh","Cardiff","Belfast"]'::jsonb),
    ('18116f38-5708-4a90-9fc2-d0dfc39cf0c0'::uuid, 0, '["Willy Wonka","Augustus Gloop","Grandpa Joe","Mike Teavee"]'::jsonb, '["Willy Wonka","Arthur Slugworth","Charlie Bucket","Grandpa Joe"]'::jsonb, '["Willy Wonka","Augustus Gloop","Grandpa Joe","Mike Teavee"]'::jsonb, '["Willy Wonka","Arthur Slugworth","Charlie Bucket","Grandpa Joe"]'::jsonb),
    ('6f81034a-f090-4cd5-beb5-39ea6a5024d4'::uuid, 3, '["Nefes kapasitesi","Duyma","Kas gücü","Görsel algı ve sabır"]'::jsonb, '["Denge ve esneklik","Ritim ve ses duyusu","Kas gücü ve dayanıklılık","Görsel algı ve sabır"]'::jsonb, '["Lung capacity","Hearing","Muscle strength","Visual perception and patience"]'::jsonb, '["Balance and flexibility","Rhythm and hearing","Muscle strength and stamina","Visual perception and patience"]'::jsonb),
    ('4f5ae38e-1e3b-4c7b-9624-49bbff372228'::uuid, 3, '["The Who","The Kinks","The Rolling Stones","The Beatles"]'::jsonb, '["The Monkees","The Hollies","The Animals","The Beatles"]'::jsonb, '["The Who","The Kinks","The Rolling Stones","The Beatles"]'::jsonb, '["The Monkees","The Hollies","The Animals","The Beatles"]'::jsonb),
    ('0951944b-ac0c-4510-915f-3c80b4c060d8'::uuid, 0, '["Kendine özgü anlatım biçimi","Eserinin satış fiyatı","Ürettiği eser sayısı","Doğduğu şehir ve yöre"]'::jsonb, '["Kendine özgü anlatım biçimi","Eğitim aldığı sanat okulu","Eserlerinin toplam değeri","Kullandığı temel malzeme"]'::jsonb, '["Their distinctive manner of expression","Their price","The number of their works","Their birthplace"]'::jsonb, '["Their distinctive manner of expression","The art school they attended","The total value of their works","The main material they use"]'::jsonb),
    ('7c53921c-260c-4b72-aed7-9188fc145099'::uuid, 1, '["Sadece çizgi filmi","Gerçek olayları","Sadece reklamı","Sadece kurguyu"]'::jsonb, '["Hayali olayları","Gerçek olayları","Tarihî efsaneleri","Uyarlanmış romanları"]'::jsonb, '["Only cartoons","Real events","Only advertising","Only fiction"]'::jsonb, '["Imaginary events","Real events","Historical legends","Adapted novels"]'::jsonb),
    ('26d365cf-bbae-4e9d-8f96-6eb53a2e63e7'::uuid, 1, '["Süreyi uzatmak","Hatalı kararı düzeltmek","Seyirciyi eğlendirmek","Maçı ertelemek"]'::jsonb, '["Oyuncu güvenliğini sağlamak","Hatalı kararı düzeltmek","Seyirci davranışını düzenlemek","Maç temposunu korumak"]'::jsonb, '["Extending the time","Correcting a wrong decision","Entertaining the crowd","Postponing the match"]'::jsonb, '["Ensuring player safety","Correcting a wrong decision","Regulating spectator behaviour","Maintaining the match tempo"]'::jsonb),
    ('c1d74827-a7d2-4855-9d19-724da9306a55'::uuid, 2, '["İngiltere ve Fransa","Almanya ve İtalya","ABD ve SSCB","Çin ve Japonya"]'::jsonb, '["Fransa ve İngiltere","Almanya ve Japonya","ABD ve SSCB","Çin ve Hindistan"]'::jsonb, '["Britain and France","Germany and Italy","the USA and the USSR","China and Japan"]'::jsonb, '["France and Britain","Germany and Japan","the USA and the USSR","China and India"]'::jsonb),
    ('7bb1dd9a-c8ff-4674-a6bf-be4ea6cfc047'::uuid, 0, '["Albert Einstein","Isaac Newton","Nikola Tesla","Max Planck"]'::jsonb, '["Albert Einstein","Niels Bohr","Isaac Newton","Stephen Hawking"]'::jsonb, '["Albert Einstein","Isaac Newton","Nikola Tesla","Max Planck"]'::jsonb, '["Albert Einstein","Niels Bohr","Isaac Newton","Stephen Hawking"]'::jsonb),
    ('63e221e3-3cdb-4e43-9a9c-24da445fa928'::uuid, 3, '["Yükseldikçe sıcaklık artar","Etkisi yoktur","Sadece kışın etkilidir","Yükseldikçe sıcaklık düşer"]'::jsonb, '["Enlem arttıkça sıcaklık düşer","Denize yakınlık sıcaklık farkını azaltır","Yükseldikçe hava basıncı düşer","Yükseldikçe sıcaklık düşer"]'::jsonb, '["Temperature rises with height","It has no effect","It only matters in winter","Temperature falls with height"]'::jsonb, '["Temperature falls with latitude","Nearness to the sea narrows temperature ranges","Air pressure falls with height","Temperature falls with height"]'::jsonb),
    ('04a4a123-5567-49bf-ac1f-b546605eb172'::uuid, 3, '["Metinde verilen örnek olayı","Metindeki ayrıntı bilgiyi","Metnin başlığındaki sözü","Metnin verdiği temel iletiyi"]'::jsonb, '["Metnin ele aldığı genel konuyu","Ana fikri destekleyen yan fikirleri","Yazarın metinde kullandığı anlatım biçimini","Metnin verdiği temel iletiyi"]'::jsonb, '["The example","The detail","The title","The core message the text conveys"]'::jsonb, '["The general topic the text deals with","The supporting ideas behind the main one","The mode of narration the author uses","The core message the text conveys"]'::jsonb),
    ('3a4f8efe-b089-446a-a239-246d5fd1f1d5'::uuid, 0, '["2,54","10","1","5"]'::jsonb, '["2,54","3,54","2,45","1,54"]'::jsonb, '["2.54","10","1","5"]'::jsonb, '["2.54","3.54","2.45","1.54"]'::jsonb),
    ('f53d3bff-231f-4902-a473-aa402344756c'::uuid, 2, '["Bilet fiyatını","Salon planını","Çalınacak eserleri ve sırayı","Ses düzeyini"]'::jsonb, '["Bilet fiyatlarını ve indirimleri","Salonun oturma planını","Çalınacak eserleri ve sırayı","Sanatçıların ücretlerini"]'::jsonb, '["The ticket price","The seating plan","The works to be played and their order","The volume"]'::jsonb, '["The ticket prices and discounts","The hall''s seating plan","The works to be played and their order","The performers'' fees"]'::jsonb),
    ('6759c1e5-8c42-472f-ad40-0137b93513d8'::uuid, 1, '["Boyayla","Küçük renkli parçalarla","Kumaşla","Alçıyla"]'::jsonb, '["İnce boya katmanlarıyla","Küçük renkli parçalarla","Dokunmuş kumaş şeritleriyle","Oyulmuş ahşap bloklarla"]'::jsonb, '["Paint","Small coloured pieces","Fabric","Plaster"]'::jsonb, '["Thin layers of paint","Small coloured pieces","Woven strips of fabric","Carved wooden blocks"]'::jsonb),
    ('1b454fb2-912e-4d11-a79a-76deb12cdfed'::uuid, 2, '["Kilo almak","Nabzı durdurmak","Hareket açıklığını artırmak","Kas yırtmak"]'::jsonb, '["Kas kütlesini artırmak","Kalp atışını hızlandırmak","Hareket açıklığını artırmak","Kemik yoğunluğunu artırmak"]'::jsonb, '["Gaining weight","Stopping the pulse","Increasing range of motion","Tearing muscle"]'::jsonb, '["Increasing muscle mass","Speeding up the heartbeat","Increasing range of motion","Increasing bone density"]'::jsonb),
    ('6cf2b0fa-0a81-4de0-bb2d-a736819ce2d4'::uuid, 1, '["Daha çok yakıt","Egzoz salımı olmaması","Daha çok yağ","Daha çok gürültü"]'::jsonb, '["Anında yüksek tork üretmesi","Egzoz salımı olmaması","Uzaktan yazılım güncellemesi alması","Evde şarj edilebilmesi"]'::jsonb, '["More fuel","No exhaust emissions","More oil","More noise"]'::jsonb, '["Producing instant high torque","No exhaust emissions","Receiving over-the-air software updates","Being chargeable at home"]'::jsonb),
    ('68a2a302-1afb-4388-a821-8017478003d4'::uuid, 1, '["Mikropları anında öldürerek","Bağışıklık sistemini eğiterek","Kanı temizleyerek","Ateşi düşürerek"]'::jsonb, '["Kanı mikroplardan arındırarak","Bağışıklık sistemini eğiterek","Sindirim sistemini güçlendirerek","Vücut ısısını dengeleyerek"]'::jsonb, '["By killing germs instantly","By training the immune system","By cleaning the blood","By reducing fever"]'::jsonb, '["By purifying the blood of germs","By training the immune system","By strengthening the digestive system","By balancing body temperature"]'::jsonb),
    ('2fa004d0-73d2-4461-b2d5-654745786b7a'::uuid, 2, '["Yüksek bulut oluşumuyla","Kar erimesiyle","Yer yüzeyine yakın yoğuşmayla","Rüzgârın durmasıyla"]'::jsonb, '["Yüksek irtifada su donmasıyla","Rüzgârın tozu havaya kaldırmasıyla","Yer yüzeyine yakın yoğuşmayla","Kar örtüsünün hızla erimesiyle"]'::jsonb, '["By the formation of high cloud","By melting snow","By condensation close to the ground","By the wind dropping"]'::jsonb, '["By water freezing at high altitude","By the wind lifting dust into the air","By condensation close to the ground","By snow cover melting quickly"]'::jsonb),
    ('3f16e761-1d25-4f20-a0c5-c30df20ce051'::uuid, 1, '["Yardımcı fikir","Metnin verdiği temel mesaj","Başlık","Yazarın adı"]'::jsonb, '["Metnin ele aldığı genel konu","Metnin verdiği temel mesaj","Ana fikri destekleyen yan fikir","Olayların geçtiği yer ve zaman"]'::jsonb, '["A supporting point","The central message of the text","The title","The author''s name"]'::jsonb, '["The general topic the text deals with","The central message of the text","A side idea supporting the main one","The place and time of the events"]'::jsonb),
    ('1a7da5c1-4d20-42f0-a1e4-69d7f4593337'::uuid, 2, '["Farkların yok sayılmasını","Tek cinsiyete öncelik","Fırsat ve haklara eşit erişimi","Yasal ayrım"]'::jsonb, '["Farklı kültürlerin bir arada yaşamasını","Engelli bireylerin topluma tam katılımını","Fırsat ve haklara eşit erişimi","Kuşaklar arasında dayanışma ve saygıyı"]'::jsonb, '["Denying differences","Priority for one gender","Equal access to opportunities and rights","Legal segregation"]'::jsonb, '["Different cultures living side by side","Full inclusion of disabled people in society","Equal access to opportunities and rights","Solidarity and respect between generations"]'::jsonb),
    ('3a2c3be4-3f9f-43e4-bda6-434c507cbd88'::uuid, 2, '["Ürün tanıtmak","Soyut biçim üretmek","Gerçeği tanıklıkla aktarmak","Moda göstermek"]'::jsonb, '["Ürünü satışa hazırlamak","Kişiliği yüzde yakalamak","Gerçeği tanıklıkla aktarmak","Anı sanatsal kurgulamak"]'::jsonb, '["Promoting a product","Producing abstract form","Bearing witness to reality","Showing fashion"]'::jsonb, '["Preparing a product for sale","Capturing personality in a face","Bearing witness to reality","Artistically staging a moment"]'::jsonb),
    ('d8b64604-d506-4c38-99cb-ac945db3624a'::uuid, 2, '["Daha ucuz","Daha kolay","Daha hızlı, daha yüksek, daha güçlü","Daha uzun"]'::jsonb, '["Daha uzağa, daha derine, daha öteye","Daha adil, daha özgür, daha eşit","Daha hızlı, daha yüksek, daha güçlü","Daha çevik, daha sabırlı, daha cesur"]'::jsonb, '["Cheaper","Easier","Faster, higher, stronger","Longer"]'::jsonb, '["Further, deeper, beyond","Fairer, freer, more equal","Faster, higher, stronger","Nimbler, more patient, braver"]'::jsonb),
    ('809f95b4-f693-4e17-90de-e7b93f18c9ce'::uuid, 3, '["Savaş","Deprem","Sel","Vezüv Yanardağı patlaması"]'::jsonb, '["Etna Yanardağı patlaması","Santorini Yanardağı patlaması","Stromboli Yanardağı patlaması","Vezüv Yanardağı patlaması"]'::jsonb, '["A war","An earthquake","A flood","The eruption of Vesuvius"]'::jsonb, '["The eruption of Etna","The eruption of Santorini","The eruption of Stromboli","The eruption of Vesuvius"]'::jsonb),
    ('142e7b46-be82-4a14-9c2f-5af0062f4fd4'::uuid, 0, '["Yetkisiz erişimi engeller","Ağın menzilini artırır","Bağlantı hızını artırır","Cihaz pil ömrünü uzatır"]'::jsonb, '["Yetkisiz erişimi engeller","Kötü amaçlı siteleri engeller","Virüslü dosyaları engeller","İstenmeyen reklamları engeller"]'::jsonb, '["It blocks unauthorised access","It increases the range","It increases the speed","It extends battery life"]'::jsonb, '["It blocks unauthorised access","It blocks malicious websites","It blocks infected files","It blocks unwanted adverts"]'::jsonb),
    ('b07248f4-50c8-4593-a799-1a0378fdb892'::uuid, 1, '["Yerine oturtmaya çalışmak","Bölgeyi hareketsiz tutmak","Masaj yapmak","Sıcak uygulamak"]'::jsonb, '["Kemiği yerine oturtmak","Bölgeyi hareketsiz tutmak","Bölgeye masaj yapmak","Bölgeyi sıcakla ısıtmak"]'::jsonb, '["Try to set it back","Keep the area still","Massage it","Apply heat"]'::jsonb, '["Set the bone back in place","Keep the area still","Massage the area","Warm the area with heat"]'::jsonb),
    ('cf118e22-7e9c-4c83-a677-38d3adc357bd'::uuid, 3, '["Harkov","Odessa","Lviv","Kiev"]'::jsonb, '["Minsk","Kişinev","Riga","Kiev"]'::jsonb, '["Kharkiv","Odesa","Lviv","Kyiv"]'::jsonb, '["Minsk","Chișinău","Riga","Kyiv"]'::jsonb),
    ('41bc1d11-8b66-46ba-a68f-dcaf015e970b'::uuid, 0, '["Yazarın vermek istediği temel ileti","Yardımcı örnek","Başlık","Kaynakça"]'::jsonb, '["Yazarın vermek istediği temel ileti","Metnin ele aldığı genel konu","Ana fikri destekleyen yan düşünce","Olayların geçtiği yer ve zaman"]'::jsonb, '["The central message the author wants to convey","A supporting example","The title","The bibliography"]'::jsonb, '["The central message the author wants to convey","The general topic the text deals with","A side idea supporting the main one","The place and time of the events"]'::jsonb),
    ('a83f6ac3-472d-402b-8132-6d1a5808996b'::uuid, 0, '["Akımı kesmek","Dokunmak","Su dökmek","Beklemek"]'::jsonb, '["Akımı kesmek","Kişiyi yan yatırmak","Kalp masajı yapmak","Yanığı soğutmak"]'::jsonb, '["Cut off the current","Touch the person","Pour water","Wait"]'::jsonb, '["Cut off the current","Put the person in the recovery position","Start chest compressions","Cool the burn"]'::jsonb),
    ('ec506348-fb06-483c-acc2-480fcb66e9fa'::uuid, 2, '["Lionel Richie","Stevie Wonder","Michael Jackson","Prince"]'::jsonb, '["Elvis Presley","George Michael","Michael Jackson","Lionel Richie"]'::jsonb, '["Lionel Richie","Stevie Wonder","Michael Jackson","Prince"]'::jsonb, '["Elvis Presley","George Michael","Michael Jackson","Lionel Richie"]'::jsonb),
    ('70e62f88-1419-402b-9c5e-71ef7a67164f'::uuid, 0, '["Küçük renkli taş ve cam parçaları","Yağlı boya","İpek iplik","Alçı kalıp"]'::jsonb, '["Küçük renkli taş ve cam parçaları","Islak sıva üzerine sürülen su bazlı boyalar","Renkli ipek ve yün ipliklerden dokuma","Kurşun çıtalarla birleştirilmiş renkli camlar"]'::jsonb, '["Small coloured pieces of stone and glass","Oil paint","Silk thread","A plaster mould"]'::jsonb, '["Small coloured pieces of stone and glass","Water-based paint on wet plaster","Woven silk and wool threads","Coloured glass joined with lead strips"]'::jsonb),
    ('7fb8d170-7df8-4868-b7b1-5d9546b8d079'::uuid, 1, '["Yapımcı","Baş karakterin karşısındaki güç","Yönetmen","Kurgucu"]'::jsonb, '["Baş karakterin yanındaki dost","Baş karakterin karşısındaki güç","Hikâyeyi anlatan dış ses","Filmin ana olay örgüsü"]'::jsonb, '["The producer","The force opposing the main character","The director","The editor"]'::jsonb, '["The ally at the main character''s side","The force opposing the main character","The voice narrating the story","The film''s main plot"]'::jsonb),
    ('0adf570d-06a9-4e87-806a-e333cff71276'::uuid, 3, '["Hızlıca kilo almak","Koşu hızını düşürmek","Kasları hızla yormak","Sakatlanmayı azaltmak"]'::jsonb, '["Kas kütlesini artırmak","Dayanıklılığı artırmak","Yağ yakımını hızlandırmak","Sakatlanmayı azaltmak"]'::jsonb, '["Gaining weight","Losing speed","Getting tired","Reducing injury"]'::jsonb, '["Increasing muscle mass","Building endurance","Speeding up fat burning","Reducing injury"]'::jsonb),
    ('3cd43862-148d-47de-83e2-767dd53219ef'::uuid, 1, '["Nüfusun azalması","Yeni ticaret yollarının açılması","Bilimin durması","Feodalitenin güçlenmesi"]'::jsonb, '["Haçlı Seferlerinin başlaması","Yeni ticaret yollarının açılması","İpek Yolu''nun önem kazanması","Feodalitenin güçlenmesi"]'::jsonb, '["A fall in population","The opening of new trade routes","A halt in science","The strengthening of feudalism"]'::jsonb, '["The start of the Crusades","The opening of new trade routes","The Silk Road gaining importance","The strengthening of feudalism"]'::jsonb),
    ('3a1e320c-a284-4f9c-bf4d-cd601db255de'::uuid, 1, '["Veriyi gizlemek","Veriyi anlaşılır biçimde sunmak","Veriyi sıkıştırmak","Veriyi silmek"]'::jsonb, '["Veriyi güvenli biçimde saklamak","Veriyi anlaşılır biçimde sunmak","Veriyi yetkisiz kişilerden gizlemek","Veriyi daha az yer kaplatmak"]'::jsonb, '["Hiding data","Presenting data so it can be understood","Compressing data","Deleting data"]'::jsonb, '["Storing data securely","Presenting data so it can be understood","Hiding data from unauthorised people","Making data take up less space"]'::jsonb),
    ('c3775c53-9102-4627-8e2b-0cc706bb0211'::uuid, 0, '["Dünya, Güneş ile Ay arasına girince","Güneş battığında","Bulutlar kapatınca","Ay söndüğünde"]'::jsonb, '["Dünya, Güneş ile Ay arasına girince","Ay, Güneş ile Dünya arasına girince","Güneş, Dünya ile Ay arasına girince","Ay, Dünya''nın gölgesinden çıkınca"]'::jsonb, '["When the Earth comes between the Sun and the Moon","When the sun sets","When clouds cover it","When the Moon goes out"]'::jsonb, '["When the Earth comes between the Sun and the Moon","When the Moon comes between the Sun and the Earth","When the Sun comes between the Earth and the Moon","When the Moon leaves the Earth''s shadow"]'::jsonb),
    ('d679098a-b9ef-43e4-8529-23b9c4bd9bf4'::uuid, 0, '["Su varlığı","Rüzgâr","Kum","Sıcaklık"]'::jsonb, '["Su varlığı","Maden yatakları","Serin iklim","Kum tepeleri"]'::jsonb, '["The presence of water","The wind","The sand","The heat"]'::jsonb, '["The presence of water","Mineral deposits","A cool climate","Sand dunes"]'::jsonb),
    ('e814a9b4-c2db-4aa2-961b-b0cf226d61c0'::uuid, 0, '["İngiltere","İrlanda","İskoçya","Galler"]'::jsonb, '["İngiltere","İrlanda","Fransa","İtalya"]'::jsonb, '["England","Ireland","Scotland","Wales"]'::jsonb, '["England","Ireland","France","Italy"]'::jsonb),
    ('2fe581b2-97b4-46cc-8040-84f83fe58de1'::uuid, 0, '["Farklı kültürlerin bir arada yaşamasını","Tek kültür dayatmasını","Göçün yasaklanmasını","Dil birliğini"]'::jsonb, '["Farklı kültürlerin bir arada yaşamasını","Kültürel mirasın kuşaklara aktarılmasını","Kadın ve erkeğin eşit haklara sahip olmasını","Herkesin eğitime eşit erişmesini"]'::jsonb, '["Different cultures living together","Imposing a single culture","Banning migration","Linguistic uniformity"]'::jsonb, '["Different cultures living together","Passing cultural heritage down the generations","Women and men having equal rights","Everyone having equal access to education"]'::jsonb),
    ('4a582735-c0d8-4edb-bbf7-daeb957b4204'::uuid, 2, '["Sahne","Ritim aleti","Sesin yazıya dökülmüş hali","Şarkı sözü"]'::jsonb, '["Şarkı sözlerinin yazılı hali","Ritmin hızını gösteren işaret","Sesin yazıya dökülmüş hali","Sessizliği gösteren yazı işareti"]'::jsonb, '["A stage","A percussion instrument","A sound written down","Song lyrics"]'::jsonb, '["The written form of the lyrics","A mark showing the tempo","A sound written down","A written sign showing silence"]'::jsonb),
    ('766663e8-92f8-40f4-9ede-36a16d189dc5'::uuid, 1, '["Ses düzenine","Karakteri görsel olarak anlatmak","Sahne süresine","Bilet fiyatına"]'::jsonb, '["Sahne ışığını dengeli ayarlamak","Karakteri görsel olarak anlatmak","Oyuncu kadrosunu belirlemek","Seyirci sayısını artırmak"]'::jsonb, '["The sound design","Expressing the character visually","The running time","The ticket price"]'::jsonb, '["Balancing the stage lighting","Expressing the character visually","Choosing the cast","Increasing the audience"]'::jsonb),
    ('265f066d-b881-4246-ad1e-6b480b08718b'::uuid, 0, '["Kahramanlık veya karşıtlık","Yalnız belge","Yalnız mizah","Yalnız romantizm"]'::jsonb, '["Kahramanlık veya karşıtlık","Bilimsel buluş ve keşif","Sporda rekabet ve başarı","Modada estetik ve zarafet"]'::jsonb, '["Heroism or opposition to war","Documentary only","Humour only","Romance only"]'::jsonb, '["Heroism or opposition to war","Scientific discovery and invention","Sporting rivalry and success","Elegance and style in fashion"]'::jsonb),
    ('21426d58-cdce-427f-a7e8-3bb0ccc474d5'::uuid, 1, '["En çok gol atana","Sportmenlik davranışına","En hızlı koşana","En çok maç yapana"]'::jsonb, '["Sezonun en iyi performansına","Sportmenlik davranışına","Kariyer boyu başarıya","Yılın en güzel golüne"]'::jsonb, '["The top scorer","Sportsmanlike conduct","The fastest runner","The most appearances"]'::jsonb, '["The best performance of the season","Sportsmanlike conduct","Lifetime achievement","The goal of the year"]'::jsonb),
    ('c082bad0-33f8-48fa-ba4d-888094a8b158'::uuid, 1, '["1912","1914","1916","1918"]'::jsonb, '["1939","1914","1918","1923"]'::jsonb, '["1912","1914","1916","1918"]'::jsonb, '["1939","1914","1918","1923"]'::jsonb),
    ('d62cb875-384e-4df9-b392-49acf9ac5265'::uuid, 1, '["Rengini","Hangi verilere erişebileceğini","Boyutunu","Fiyatını"]'::jsonb, '["Hangi dillerde çalışabileceğini","Hangi verilere erişebileceğini","Hangi sürüme güncelleneceğini","Hangi cihazlara yüklenebileceğini"]'::jsonb, '["Its colour","Which data it can reach","Its size","Its price"]'::jsonb, '["Which languages it can run in","Which data it can reach","Which version it updates to","Which devices it can be installed on"]'::jsonb),
    ('65a03d3c-7143-49f1-a177-d4c29a52b4d3'::uuid, 1, '["Görmeyi","Denge ve koordinasyonu","Sindirimi","Solunumu"]'::jsonb, '["Görme ve işitmeyi","Denge ve koordinasyonu","Sindirim ve boşaltımı","Solunum ve dolaşımı"]'::jsonb, '["Vision","Balance and coordination","Digestion","Breathing"]'::jsonb, '["Vision and hearing","Balance and coordination","Digestion and excretion","Breathing and circulation"]'::jsonb),
    ('744ceae2-7e3f-45cf-ab2e-ecff3ae952a5'::uuid, 2, '["İkisi aynıdır","Deyim öğüt verir","Atasözü yargı bildirir","Deyim uzundur"]'::jsonb, '["Deyim kalıplaşmamıştır","İkisi de kalıplaşmıştır","Atasözü yargı bildirir","Atasözü anonim değildir"]'::jsonb, '["They are the same","The idiom gives advice","The proverb states a judgement","The idiom is longer"]'::jsonb, '["The idiom is not a fixed phrase","Both are fixed phrases","The proverb states a judgement","The proverb is not anonymous"]'::jsonb),
    ('5e3b4cba-7323-443e-aed6-913f0a872077'::uuid, 3, '["Çok şeker","Çok tuz","Az su","Uygun saklama ve pişirme"]'::jsonb, '["Bol su ve lif tüketimi","Vitamin ve mineral takviyesi","Düzenli egzersiz ve uyku","Uygun saklama ve pişirme"]'::jsonb, '["Plenty of sugar","Plenty of salt","Little water","Proper storage and cooking"]'::jsonb, '["Plenty of water and fibre","Vitamin and mineral supplements","Regular exercise and sleep","Proper storage and cooking"]'::jsonb),
    ('1aa8d792-3184-45af-addf-f21f2a2cc994'::uuid, 2, '["Arjantin","Kolombiya","Brezilya","Peru"]'::jsonb, '["Küba","Arjantin","Brezilya","Meksika"]'::jsonb, '["Argentina","Colombia","Brazil","Peru"]'::jsonb, '["Cuba","Argentina","Brazil","Mexico"]'::jsonb),
    ('89e1b3aa-2d2a-402d-9e18-735e183874af'::uuid, 2, '["Tek kare","Işık patlaması","Ardışık karelerin hızlı gösterimi","Ses efekti"]'::jsonb, '["Uzun pozlamayla ışık izi çizilmesi","Tek karede çoklu pozlama yapılması","Ardışık karelerin hızlı gösterimi","Kameranın sahne boyunca kaydırılması"]'::jsonb, '["With a single frame","With a flash of light","By showing successive frames quickly","With a sound effect"]'::jsonb, '["By tracing light with a long exposure","By multiple exposures on one frame","By showing successive frames quickly","By panning the camera across the scene"]'::jsonb),
    ('9ddadf09-7659-4ff4-a01c-c7d9ef414e03'::uuid, 0, '["Ortak evrende süren yapımlar bütünü","Tek film","Kısa film","Belgesel dizisi"]'::jsonb, '["Ortak evrende süren yapımlar bütünü","Tek bir yönetmenin çektiği filmler","Aynı yıl vizyona giren filmlerin hepsi","Bir stüdyonun yıllık yapım kataloğu"]'::jsonb, '["A body of productions continuing in a shared universe","A single film","A short film","A documentary series"]'::jsonb, '["A body of productions continuing in a shared universe","All films made by a single director","All films released in the same year","A studio''s yearly production catalogue"]'::jsonb),
    ('56e1e98f-6a4a-49bf-8dad-902693a9e7c3'::uuid, 0, '["1945","1944","1943","1946"]'::jsonb, '["1945","1918","1939","1923"]'::jsonb, '["1945","1944","1943","1946"]'::jsonb, '["1945","1918","1939","1923"]'::jsonb),
    ('ac705c5c-f598-4e35-8746-0419f118f163'::uuid, 1, '["Dosya sıkıştırır","Kullanıcı bilgisini gizlice toplar","Pil şarj eder","Ağ hızlandırır"]'::jsonb, '["Dosyaları şifreleyip fidye ister","Kullanıcı bilgisini gizlice toplar","Kendini ağda hızla çoğaltır","Ekranda sürekli reklam gösterir"]'::jsonb, '["Compresses files","Secretly collects the user''s information","Charges the battery","Speeds up the network"]'::jsonb, '["Encrypts files and demands a ransom","Secretly collects the user''s information","Rapidly copies itself across a network","Constantly shows adverts on screen"]'::jsonb),
    ('760b269a-84db-4d25-ae62-b2ed9920b3a7'::uuid, 1, '["Denizin yansıması","Işığın saçılması","Ozon rengi","Bulut yoğunluğu"]'::jsonb, '["Işığın kırılması","Işığın saçılması","Işığın soğurulması","Denizin yansıması"]'::jsonb, '["The reflection of the sea","The scattering of light","The colour of ozone","Cloud density"]'::jsonb, '["The refraction of light","The scattering of light","The absorption of light","The reflection of the sea"]'::jsonb),
    ('ee8d7825-e19f-42ae-b37e-e7913cc14151'::uuid, 1, '["Dağ tepesinde olması","Lagün üzerine kurulmuş olması","Çölde olması","Buzul üstünde olması"]'::jsonb, '["Delta üzerine kurulmuş olması","Lagün üzerine kurulmuş olması","Volkan üzerine kurulmuş olması","Fiyort kıyısına kurulmuş olması"]'::jsonb, '["Being on a mountain top","Being built on a lagoon","Being in a desert","Being on a glacier"]'::jsonb, '["Being built on a delta","Being built on a lagoon","Being built on a volcano","Being built on a fjord"]'::jsonb),
    ('0d596711-117c-4741-8021-7803aa0379a0'::uuid, 2, '["İkna etmeyi","Duygulandırmayı","Bilgi vermeyi","Güldürmeyi"]'::jsonb, '["Karşıt görüşü çürütmeyi","Zihinde resim çizmeyi","Bilgi vermeyi","Olay aktarmayı"]'::jsonb, '["Persuade","Move emotionally","Inform","Amuse"]'::jsonb, '["Refute an opposing view","Paint a picture in the mind","Inform","Relate events"]'::jsonb),
    ('0b633087-bb45-46a3-81ec-452c6bf1113b'::uuid, 1, '["Dinin tamamen yasaklanması","Din ve devlet işlerinin ayrılığı","Tek partili yönetim biçimi","Her konuda halk oylaması"]'::jsonb, '["Din ve eğitim işlerinin birliği","Din ve devlet işlerinin ayrılığı","Devlet ve ordu işlerinin ayrılığı","Din ve devlet işlerinin birliği"]'::jsonb, '["Banning religion","The separation of religion and state affairs","One-party rule","A referendum"]'::jsonb, '["The unity of religion and education","The separation of religion and state affairs","The separation of state and military affairs","The unity of religion and state affairs"]'::jsonb),
    ('035a7aed-083f-4316-92c0-1b787a800c4e'::uuid, 0, '["Bütünlük ve yorum birliğini","Konser bilet satışlarını","Sahne ışık düzenini","Nota basım işlerini"]'::jsonb, '["Bütünlük ve yorum birliğini","Nota ve eser yazımını","Bilet ve program satışını","Enstrüman bakım ve onarımını"]'::jsonb, '["Cohesion and unity of interpretation","Ticket sales","Stage lighting","Printing of scores"]'::jsonb, '["Cohesion and unity of interpretation","Writing the scores and works","Selling tickets and programmes","Maintaining and repairing instruments"]'::jsonb),
    ('449f9f78-b915-44f2-a1c2-db8ee18677b9'::uuid, 3, '["Aşırı süslemeyi","Renk bolluğunu","Karmaşayı","Sadeliği"]'::jsonb, '["Süslemeyi","Çokluğu","Gerçekçiliği","Sadeliği"]'::jsonb, '["Lavish ornament","An abundance of colour","Complexity","Simplicity"]'::jsonb, '["Ornament","Abundance","Realism","Simplicity"]'::jsonb),
    ('0a21f6f8-489a-43f1-8735-e174a7b7d597'::uuid, 3, '["Yüksek ses tonu kullanımıyla","Renk düzenlemesi yoluyla","Hızlı kurgu tekniği ile","Beklenen ile olan karşıtlığıyla"]'::jsonb, '["Görüntü ile sesin uyumuyla","Sahneler arası hızlı geçişle","Oyuncunun abartılı mimikleriyle","Beklenen ile olan karşıtlığıyla"]'::jsonb, '["Through loudness","Through colour","Through fast editing","Through the contrast between what is expected and what happens"]'::jsonb, '["Through harmony between image and sound","Through fast cuts between scenes","Through an actor''s exaggerated expressions","Through the contrast between what is expected and what happens"]'::jsonb),
    ('6bb0d0af-2334-4874-bfa5-513add6a8579'::uuid, 0, '["Çalışan işlemleri ve kaynak kullanımını","Ağ şifresini","Ekran çözünürlüğünü","Dosya listesini"]'::jsonb, '["Çalışan işlemleri ve kaynak kullanımını","Yüklü programları ve lisans durumunu","Ağ bağlantılarını ve şifreleri","Takvimi ve yapılacaklar listesini"]'::jsonb, '["Running processes and resource use","The network password","The screen resolution","A file list"]'::jsonb, '["Running processes and resource use","Installed programs and licence status","Network connections and passwords","The calendar and to-do list"]'::jsonb),
    ('01b2e965-5dbe-4fe0-b685-26e7ff60804a'::uuid, 2, '["Asidik","Bazik","Nötr","Doymuş"]'::jsonb, '["Asidik","Bazik","Nötr","Amfoter"]'::jsonb, '["Acidic","Basic","Neutral","Saturated"]'::jsonb, '["Acidic","Basic","Neutral","Amphoteric"]'::jsonb),
    ('32b4b9f2-787f-422d-94a7-fd9bf7519d6f'::uuid, 1, '["Chiang Mai","Bangkok","Phuket","Pattaya"]'::jsonb, '["Hanoi","Bangkok","Manila","Jakarta"]'::jsonb, '["Chiang Mai","Bangkok","Phuket","Pattaya"]'::jsonb, '["Hanoi","Bangkok","Manila","Jakarta"]'::jsonb),
    ('21c10ce5-57f8-45fa-b76e-e38210ea22ba'::uuid, 3, '["Uzunluğu","Sözcük sayısını","Yazı tipini","Düşüncelerin çelişmemesini"]'::jsonb, '["Gereksiz sözcük olmamasını","Kolayca anlaşılmasını","Rahat okunmasını","Düşüncelerin çelişmemesini"]'::jsonb, '["Its length","The number of words","The typeface","That the ideas do not contradict each other"]'::jsonb, '["Having no unnecessary words","Being easy to understand","Reading smoothly","That the ideas do not contradict each other"]'::jsonb),
    ('65ccdb32-acbc-4a96-9185-303790d7c9d2'::uuid, 2, '["Işığı artırmak","Koltuk artırmak","Sesin dengeli yayılmasını sağlamak","Isıyı ayarlamak"]'::jsonb, '["Seyircinin sahneyi rahat görmesini sağlamak","Acil durumda hızlı tahliyeyi sağlamak","Sesin dengeli yayılmasını sağlamak","Salonun ısısını dengede tutmak"]'::jsonb, '["Increasing the light","Adding seats","Making the sound spread evenly","Regulating the temperature"]'::jsonb, '["Ensuring everyone can see the stage","Ensuring quick evacuation in emergencies","Making the sound spread evenly","Keeping the hall temperature steady"]'::jsonb),
    ('fa75cef6-4230-4f3a-9ae2-4fda98ae15f2'::uuid, 1, '["Çok renk zorunluluğu","Akılda kalıcılık ve sadelik","Uzun metin","Karmaşıklık"]'::jsonb, '["Ayrıntı zenginliği ve derinlik","Akılda kalıcılık ve sadelik","Gerçekçilik ve doğallık","Hareketlilik ve dinamizm"]'::jsonb, '["A requirement for many colours","Memorability and simplicity","Long text","Complexity"]'::jsonb, '["Rich detail and depth","Memorability and simplicity","Realism and naturalness","Movement and dynamism"]'::jsonb),
    ('96460747-8a7f-4028-b90d-465b1667f3cc'::uuid, 1, '["Renk artırımıyla","İki görüntünün gözlere ayrı verilmesiyle","Ses yükseltimiyle","Kare hızıyla"]'::jsonb, '["Kare hızının iki katına çıkarılmasıyla","İki görüntünün gözlere ayrı verilmesiyle","İki hoparlörün sesi kulaklara ayrı vermesiyle","Perdenin görüş alanını kaplamasıyla"]'::jsonb, '["By boosting colour","By feeding two images separately to the eyes","By raising the volume","By the frame rate"]'::jsonb, '["By doubling the frame rate","By feeding two images separately to the eyes","By two speakers feeding sound to each ear","By the screen filling the field of view"]'::jsonb),
    ('052f6554-51d4-48aa-a497-616933814e1c'::uuid, 0, '["1945","1944","1946","1943"]'::jsonb, '["1945","1939","1918","1941"]'::jsonb, '["1945","1944","1946","1943"]'::jsonb, '["1945","1939","1918","1941"]'::jsonb),
    ('48e6bdc4-e185-4e59-92aa-4eee739c0f91'::uuid, 0, '["İnternette bıraktığımız veri izi","Pil ömrü","Ayakkabı numarası","Ekran boyutu"]'::jsonb, '["İnternette bıraktığımız veri izi","Çevrim içi geçirdiğimiz toplam süre","Cihazımızın ağdaki adresi","Sosyal medyadaki takipçi sayımız"]'::jsonb, '["The trail of data we leave online","Battery life","Shoe size","Screen size"]'::jsonb, '["The trail of data we leave online","The total time we spend online","Our device''s address on the network","Our follower count on social media"]'::jsonb),
    ('6c72f4ec-7106-4c2d-90a4-af4fb937b828'::uuid, 3, '["110","120","90","100"]'::jsonb, '["4","0","37","100"]'::jsonb, '["110","120","90","100"]'::jsonb, '["4","0","37","100"]'::jsonb),
    ('440af05f-09ac-4838-9691-2ae72561a12b'::uuid, 3, '["Yağış azalması","Deniz alçalması","Kuraklık artışı","Deniz yükselmesi"]'::jsonb, '["Deniz tuzlanması","Deniz çekilmesi","Akıntı hızlanması","Deniz yükselmesi"]'::jsonb, '["Less rainfall","Falling sea level","More drought","Rising sea level"]'::jsonb, '["The sea becoming saltier","The sea retreating","Faster ocean currents","Rising sea level"]'::jsonb),
    ('49aa11c4-9c6c-454c-b1a7-924773abe70a'::uuid, 2, '["Duygu aktarmak","Öykü anlatmak","Bir savı kanıtlarla savunmak","Sahne kurmak"]'::jsonb, '["Bir olayı sırayla anlatmak","Bir duyguyu imgelerle aktarmak","Bir savı kanıtlarla savunmak","Bir yeri ayrıntılarla betimlemek"]'::jsonb, '["Conveying emotion","Telling a story","Defending a claim with evidence","Setting a scene"]'::jsonb, '["Narrating an event in order","Conveying a feeling through images","Defending a claim with evidence","Describing a place in detail"]'::jsonb),
    ('05719bd9-4fea-4aaa-b16f-bf255bf1a2f9'::uuid, 1, '["Yönetmelik","Anayasa","Tüzük","Genelge"]'::jsonb, '["Kanun","Anayasa","Tüzük","Yönetmelik"]'::jsonb, '["A regulation","The constitution","A statute","A circular"]'::jsonb, '["A statute","The constitution","A bylaw","A regulation"]'::jsonb),
    ('41d65ab3-223f-4bd0-920b-1e2dc36fe58c'::uuid, 2, '["Solo çalar","Bas çalar","Akor ve ritim eşliği verir","Davul çalar"]'::jsonb, '["Melodiyi ve soloları çalar","Bas hatlarını ve kökleri çalar","Akor ve ritim eşliği verir","Vurmalı efektleri üretir"]'::jsonb, '["Plays solos","Plays bass lines","Provides chordal and rhythmic accompaniment","Plays the drums"]'::jsonb, '["Plays the melody and solos","Plays the bass lines and roots","Provides chordal and rhythmic accompaniment","Produces percussive effects"]'::jsonb),
    ('2867aae5-d440-40d2-ba74-225c855da281'::uuid, 0, '["Asimetride eşitliğin bozulması","Simetride renk olmaması","Asimetride boşluk olmaması","İkisinin aynı olması"]'::jsonb, '["Asimetride eşitliğin bozulması","Simetride eşitliğin bozulması","Asimetride rengin kullanılmaması","Simetride boşluğun bulunmaması"]'::jsonb, '["In asymmetry the balance of equality is broken","In symmetry there is no colour","In asymmetry there is no empty space","They are the same"]'::jsonb, '["In asymmetry the balance of equality is broken","In symmetry the balance of equality is broken","In asymmetry colour is not used","In symmetry there is no empty space"]'::jsonb),
    ('74c24233-056b-49a9-a0bd-abbff2619bc2'::uuid, 1, '["Bilet satmak","Yapıtı çözümleyip değerlendirmek","Fragman yapmak","Afiş basmak"]'::jsonb, '["Yapıtı tanıtıp pazarlamak","Yapıtı çözümleyip değerlendirmek","Yapıtı kurgulayıp düzenlemek","Yapıtı çevirip altyazılamak"]'::jsonb, '["Selling tickets","Analysing and evaluating the work","Making trailers","Printing posters"]'::jsonb, '["Promoting and marketing the work","Analysing and evaluating the work","Editing and assembling the work","Translating and subtitling the work"]'::jsonb),
    ('f2aabf0d-1eab-4ed4-abd1-8ec489d931c6'::uuid, 1, '["Kask yalnızca","Emniyet ipi ve kemer","Eldiven yalnızca","Gözlük"]'::jsonb, '["Dizlik ve dirseklik","Emniyet ipi ve kemer","Tebeşir ve toz torbası","Eldiven ve bileklik"]'::jsonb, '["A helmet alone","A safety rope and harness","Gloves alone","Goggles"]'::jsonb, '["Knee and elbow pads","A safety rope and harness","Chalk and a chalk bag","Gloves and wristbands"]'::jsonb),
    ('d25fdb90-adee-4cea-8487-20279a3f10f4'::uuid, 0, '["İkinci Dünya Savaşı","Birinci Dünya Savaşı","Kore Savaşı","Vietnam Savaşı"]'::jsonb, '["İkinci Dünya Savaşı","Birinci Dünya Savaşı","Kırım Savaşı","Körfez Savaşı"]'::jsonb, '["The Second World War","The First World War","The Korean War","The Vietnam War"]'::jsonb, '["The Second World War","The First World War","The Crimean War","The Gulf War"]'::jsonb),
    ('c97538ff-e56c-4c19-90e3-4f7a51bfbf97'::uuid, 1, '["Yalnız reklam gösterir","Zararsız görünüp zarar verir","Yalnız yavaşlatır","Yalnız kopyalanır"]'::jsonb, '["Dosyaları şifreleyip fidye ister","Zararsız görünüp zarar verir","Kendini ağda kopyalayıp yayar","Ekranda sürekli reklam açar"]'::jsonb, '["Only shows adverts","Looks harmless and does damage","Only slows things down","Only copies itself"]'::jsonb, '["Encrypts files and demands a ransom","Looks harmless and does damage","Copies itself across a network","Keeps opening adverts on screen"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 1: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 1: yanlış şıklar yeniden yazıldı (420)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 1: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 1: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
