-- ============================================================
-- 1043 — soru_parti_kolay_05 (stil: docs/SORU_STIL_PROFILI.md): 198 soru · 2026-10-10
--
-- Kategori: edebiyat 23 · genel_kultur 40 · muzik 20 · sanat 30 · sinema 21 · spor 23 · tarih 3 · teknoloji 38
-- Yerel (kapsam='yerel', ulke='TR'): 17 · zorluk 1–5: 0/137/61/0/0
-- İngilizce çeviri: 181 · çevrilmeyen (ceviri_atlanan, kod 'cevrilemez'): 17
--
-- Kalite (araclar/soru-uretim/api-uret.mjs; üretim claude-opus-5-5, hakem claude-sonnet-5-5):
-- biçim + şık denge (TR/EN), havuzla birebir ve anlamca tekrar (aynı cevap + Jaccard ≥ 0,3),
-- cevap soru metninde değil, soru_kural_isaretleri (ağırlık ≥ 2 yok), Jev şık ipucu testi
-- (soru gizli, doğru şıkka p ≤ 0,75), Jev tek doğru, Claude hakem (doğru şık kesin, yanlış
-- şıklar kesin yanlış, yasak tip yok: genel kavram / tanımlama / okuduğunu anlama / mantıkla
-- bulunur; tek olgu, eskimez, EN aynı sırada ve doğal, zorluk tahmini etiketle uyumlu).
--
-- Sıra: sorular doğru şık 0'da eklenir, çeviriler aynı sırayla yazılır, sonunda YALNIZ
-- bu işlemde eklenen satırların şıkları karıştırılır — TR ve EN AYNI permütasyonla
-- (dogru_cevap indeksi ortak olduğu için şart). `created_at >= transaction_timestamp()`
-- koşulu ZORUNLUDUR; onsuz tüm havuz karışır ve oynanan maçlarda indeks kayar.
-- Üretici: node araclar/soru-uretim/uret-migration-parti.mjs --parti 5 --no 1043 --klasor kolay-05 --ad soru_parti_kolay_05 --api
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori, kapsam, ulke, zorluk) values
('Besteci Frédéric Chopin hangi ülkede doğmuştur?', '["Polonya","Fransa","Avusturya","Macaristan"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Fındıkkıran'' balesinde Fındıkkıran ve oyuncak askerler hangi hayvanların kralıyla savaşır?', '["Fareler","Kediler","Kurtlar","Yarasalar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Çizgi roman kahramanları Asteriks ile Oburiks hangi halktandır?', '["Galyalılar","Romalılar","Vikingler","Gotlar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Chicago''daki aynalı paslanmaz çelik ''Cloud Gate'' heykeli halk arasında ne diye anılır?', '["Fasulye","Damla","Bezelye","Yumurta"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Arzu Tramvayı'' oyununun yazarı kimdir?', '["Tennessee Williams","Eugene O''Neill","Lorraine Hansberry","Arthur Miller"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Sesler Müziği'' müzikali ve filmi hangi ülkede geçer?', '["Avusturya","İsviçre","Almanya","Macaristan"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Dubai''deki Burj Al Arab oteli neyin biçimini andırır?', '["Yelken","Lale","Hilal","Damla"]'::jsonb, 0, 'sanat', 'global', null, 2),
('The Beatles''ın ''Abbey Road'' albüm kapağında dörtlü nerede yürür?', '["Yaya geçidi","Asma köprü","Tren rayı","Kum plajı"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Oscar heykelciğindeki şövalye figürü elinde ne tutar?', '["Kılıç","Meşale","Asa","Kalkan"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Washington''daki Lincoln Anıtı''nda Lincoln heykeli hangi duruştadır?', '["Oturmuş","Ayakta","Atlı","Diz çökmüş"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''The King and I'' (Kral ve Ben) müzikali hangi krallıkta geçer?', '["Siyam","Burma","Çin","Hindistan"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Andy Warhol''a göre gelecekte herkes kaç dakikalığına dünyaca ünlü olacak?', '["15","10","5","30"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Vatikan''daki ''Laokoon ve Oğulları'' heykelinde rahip ve oğullarına hangi hayvanlar saldırır?', '["Yılanlar","Aslanlar","Kartallar","Kurtlar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Paslanmaz çelikten dev ''Gateway Arch'' kemeri hangi ABD şehrindedir?', '["St. Louis","Kansas City","Denver","Pittsburgh"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Bitmemiş Senfoni'' adıyla bilinen 8. Senfoni hangi besteciye aittir?', '["Schubert","Schumann","Brahms","Mendelssohn"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Güzel Mavi Tuna'' valsinin bestecisi kimdir?', '["Johann Strauss","Franz Lehár","Johannes Brahms","Franz Schubert"]'::jsonb, 0, 'sanat', 'global', null, 2),
('İçine sırtı dönük bozuk para atılan ünlü Trevi Çeşmesi hangi şehirdedir?', '["Roma","Floransa","Venedik","Napoli"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Aslan başlı, balık gövdeli ''Merlion'' heykeli hangi şehrin simgesidir?', '["Singapur","Hong Kong","Bangkok","Manila"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Kırmızı tabanlı ayakkabılarıyla ünlü Fransız tasarımcı kimdir?', '["Christian Louboutin","Manolo Blahnik","Salvatore Ferragamo","Roger Vivier"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Klarnet glissandosuyla açılan ''Rhapsody in Blue'' eserinin bestecisi kimdir?', '["George Gershwin","Leonard Bernstein","Aaron Copland","Cole Porter"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Çizgi roman kahramanı Tenten''in yaratıcısı kimdir?', '["Hergé","Uderzo","Goscinny","Peyo"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Moulin de la Galette''te Balo'' tablosunun ressamı kimdir?', '["Renoir","Monet","Degas","Pissarro"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''My Fair Lady'' müzikali hangi yazarın oyununa dayanır?', '["Shaw","Wilde","Coward","Barrie"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Pink Floyd''un ''Animals'' albüm kapağında santralin üzerinde hangi şişme hayvan uçar?', '["Domuz","Koyun","Köpek","İnek"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Quino''nun çizgi kahramanı küçük Mafalda''nın nefret ettiği yemek hangisidir?', '["Çorba","Ispanak","Brokoli","Karnabahar"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Londra''daki 30 St Mary Axe gökdeleni halk arasında hangi sebzenin adıyla anılır?', '["Kornişon","Patlıcan","Havuç","Kabak"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Dünyanın en büyük Budist tapınağı sayılan Borobudur hangi ülkededir?', '["Endonezya","Tayland","Myanmar","Sri Lanka"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Çaykovski''nin ''1812 Uvertürü''nün finalinde hangi silahın atışları duyulur?', '["Top","Tüfek","Tabanca","Roket"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Puantiyeli dev balkabağı heykelleriyle tanınan Japon sanatçı kimdir?', '["Yayoi Kusama","Takashi Murakami","Yoshitomo Nara","Yoko Ono"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Puccini''nin ''Tosca'' operası hangi şehirde geçer?', '["Roma","Floransa","Venedik","Napoli"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Kızılderili, kovboy ve polis kostümleriyle sahneye çıkan ''Y.M.C.A.'' grubu hangisidir?', '["Village People","Bee Gees","Boney M.","KC and the Sunshine Band"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Ünlü gitar riffiyle bilinen ''Smoke on the Water'' hangi grubun şarkısıdır?', '["Deep Purple","Black Sabbath","Uriah Heep","Led Zeppelin"]'::jsonb, 0, 'muzik', 'global', null, 2),
('2018 yapımı ''Müslüm'' filminde Müslüm Gürses''i canlandıran oyuncu kimdir?', '["Timuçin Esen","Kıvanç Tatlıtuğ","Haluk Bilginer","Engin Akyürek"]'::jsonb, 0, 'muzik', 'yerel', 'TR', 2),
('Queen grubunun gitaristi ve ''We Will Rock You'' şarkısının yazarı kimdir?', '["Brian May","Jimmy Page","Eric Clapton","Ritchie Blackmore"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Hey Ya!'' şarkısıyla 2003''te listeleri sallayan hip hop ikilisi hangisidir?', '["OutKast","Run-DMC","Black Eyed Peas","Fugees"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Annie Lennox''un sesiyle bilinen ''Sweet Dreams (Are Made of This)'' hangi ikilinin şarkısıdır?', '["Eurythmics","Tears for Fears","Pet Shop Boys","Roxette"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Dolores O''Riordan''ın solistliğini yaptığı, ''Zombie'' şarkısıyla bilinen İrlandalı grup hangisidir?', '["The Cranberries","The Corrs","Garbage","The Smashing Pumpkins"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Küçük oğlunun ölümünün ardından ''Tears in Heaven'' şarkısını yazan müzisyen kimdir?', '["Eric Clapton","Phil Collins","Rod Stewart","Elton John"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''U Can''t Touch This'' şarkısı ve bol şalvar pantolonuyla ünlenen rapçi kimdir?', '["MC Hammer","Vanilla Ice","Coolio","Young MC"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Rob Thomas ile seslendirdiği ''Smooth'' şarkısıyla Grammy toplayan gitarist kimdir?', '["Carlos Santana","Stevie Ray Vaughan","Mark Knopfler","George Benson"]'::jsonb, 0, 'muzik', 'global', null, 2),
('1990''da ''Ice Ice Baby'' şarkısıyla listelerin zirvesine çıkan rapçi kimdir?', '["Vanilla Ice","Marky Mark","Kid Rock","Sir Mix-a-Lot"]'::jsonb, 0, 'muzik', 'global', null, 2),
('2018 yapımı ''Bohemian Rhapsody'' filminde Freddie Mercury''yi canlandıran oyuncu kimdir?', '["Rami Malek","Ben Whishaw","Dev Patel","Eddie Redmayne"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''My Way'' şarkısıyla özdeşleşen, ''Ol'' Blue Eyes'' lakaplı şarkıcı kimdir?', '["Frank Sinatra","Dean Martin","Sammy Davis Jr.","Bing Crosby"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Rapçi Eminem''in gerçek adı nedir?', '["Marshall Mathers","Curtis Jackson","Christopher Wallace","Shawn Carter"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''2001: Uzay Macerası''nın açılışında çalan ''Böyle Buyurdu Zerdüşt''ün bestecisi kimdir?', '["Richard Strauss","Gustav Mahler","Richard Wagner","Anton Bruckner"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Michael Jackson''ın ''Thriller'' klibini yöneten yönetmen kimdir?', '["John Landis","Steven Spielberg","John Carpenter","Martin Scorsese"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Yaylılar örneğiyle açılan ''Bitter Sweet Symphony'' hangi İngiliz grubun şarkısıdır?', '["The Verve","Suede","The Charlatans","Pulp"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Verdi''nin ünlü aryası ''La donna è mobile'' hangi operasında yer alır?', '["Rigoletto","La Traviata","Il Trovatore","Otello"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Fransızca şanson klasiği ''Ne me quitte pas'' şarkısını yazıp seslendiren kimdir?', '["Jacques Brel","Charles Aznavour","Serge Gainsbourg","Georges Brassens"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Elton John''un hayatını anlatan ''Rocketman'' filminde Elton John''u oynayan oyuncu kimdir?', '["Taron Egerton","Richard Madden","Jamie Bell","Eddie Redmayne"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Google''ın kurucuları Larry Page ve Sergey Brin hangi üniversitede tanıştı?', '["Stanford","MIT","Harvard","Berkeley"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('1961''de Eskişehir''de üretilen ilk yerli Türk otomobilinin adı nedir?', '["Devrim","Anadol","Murat","Togg"]'::jsonb, 0, 'teknoloji', 'yerel', 'TR', 2),
('İnternet tarayıcılarında yeni bir sekme açmak için kullanılan klavye kısayolu hangisidir?', '["Ctrl+T","Ctrl+N","Ctrl+W","Ctrl+Tab"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Mario ilk kez hangi atari oyununda sahneye çıkmıştır?', '["Donkey Kong","Mario Bros.","Pac-Man","Popeye"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İnternet tarayıcılarında sayfayı yenilemek için basılan işlev tuşu hangisidir?', '["F5","F1","F11","F12"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Windows''ta bilgisayarı anında kilitleyen klavye kısayolu hangisidir?', '["Win+L","Win+D","Win+E","Win+R"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('PUBG''de maçı kazanınca ekranda çıkan ünlü zafer yazısında hangi yemek geçer?', '["Tavuk","Pizza","Hamburger","Biftek"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Microsoft''un Internet Explorer''ın yerine getirdiği tarayıcının adı nedir?', '["Edge","Safari","Opera","Vivaldi"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Sonic oyunlarında Sonic''in baş düşmanı olan bıyıklı bilim insanı kimdir?', '["Dr. Eggman","Dr. Wily","Dr. Neo Cortex","Dr. Nefarious"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Bayraktar TB2 insansız hava aracını üreten Türk şirketi hangisidir?', '["Baykar","Aselsan","Roketsan","TUSAŞ"]'::jsonb, 0, 'teknoloji', 'yerel', 'TR', 2),
('Steve Jobs''un ardından 2011''de Apple''ın CEO''su olan kişi kimdir?', '["Tim Cook","Jony Ive","Phil Schiller","Scott Forstall"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Sonic oyunlarında Sonic''in uçabilen tilki yardımcısının adı nedir?', '["Tails","Knuckles","Shadow","Silver"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Pokémon animesinde Team Rocket''e eşlik eden, insan gibi konuşan Pokémon hangisidir?', '["Meowth","Psyduck","Jigglypuff","Togepi"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('SpaceX''in iniş yapıp yeniden kullanılabilen roket ailesinin adı nedir?', '["Falcon","Atlas","Ariane","Soyuz"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('TÜBİTAK''ın geliştirdiği yerli Linux tabanlı işletim sisteminin adı nedir?', '["Pardus","Kartal","Anadolu","Toros"]'::jsonb, 0, 'teknoloji', 'yerel', 'TR', 2),
('Chrome''da internet bağlantısı yokken çıkan oyunda hangi hayvan koşar?', '["Dinozor","Kanguru","Tavşan","Timsah"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Minecraft''ta lav ve ateşle dolu cehennemsi boyutun adı nedir?', '["Nether","The End","Overworld","Aether"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Assassin''s Creed II''de Rönesans İtalyası''nda geçen hikâyenin kahramanı kimdir?', '["Ezio","Altaïr","Connor","Edward"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Google''ın çatı şirketi olarak 2015''te kurulan holdingin adı nedir?', '["Alphabet","Oracle","Verizon","Nvidia"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Samsung''un amiral gemisi akıllı telefon serisinin adı nedir?', '["Galaxy","Xperia","Pixel","Lumia"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Halo'' oyun serisinin zırhlı kahramanı hangi lakapla bilinir?', '["Master Chief","Doom Slayer","Solid Snake","Big Boss"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Google''ın ''Bard'' adlı yapay zekâ sohbet botu 2024''te hangi adı almıştır?', '["Gemini","Copilot","Grok","Llama"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Grand Theft Auto V'' hangi kurgusal şehirde geçer?', '["Los Santos","Liberty City","Vice City","San Fierro"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Half-Life'' serisinin levye taşıyan bilim insanı kahramanı kimdir?', '["Gordon Freeman","Isaac Clarke","Adam Jensen","Commander Shepard"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Vikipedi''yi Larry Sanger ile birlikte kuran kişi kimdir?', '["Jimmy Wales","Craig Newmark","Pierre Omidyar","Reid Hoffman"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Uncharted'' oyun serisinin hazine avcısı kahramanı kimdir?', '["Nathan Drake","Sam Fisher","Max Payne","Marcus Fenix"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Zelda serisinde Ganon''un ele geçirmek istediği kutsal altın emanetin adı nedir?', '["Triforce","Master Sword","Ocarina","Moon Pearl"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Portal'' oyununda ''yalan'' olduğu söylenen vaat edilmiş ödül nedir?', '["Pasta","Madalya","Kurabiye","Dondurma"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('İlk ''BioShock'' oyunu hangi su altı şehrinde geçer?', '["Rapture","Columbia","Atlantis","Eden"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Nokia, 1865''te kurulduğunda hangi işle uğraşan bir şirketti?', '["Kâğıt üretimi","Gemi yapımı","Tekstil üretimi","Madencilik"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Tesla''nın geliştirdiği insansı robotun adı nedir?', '["Optimus","Atlas","ASIMO","Digit"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('eBay''de satılan ilk ürün olarak bilinen bozuk eşya nedir?', '["Lazer işaretleyici","Cep hesap makinesi","Dijital kol saati","Kaset çalar"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Instagram''ı Mike Krieger ile birlikte kuran kişi kimdir?', '["Kevin Systrom","Evan Spiegel","Jack Dorsey","Jan Koum"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Vikipedi''nin logosunda hangi nesne yer alır?', '["Yapboz parçalı küre","Sayfaları açık kitap","Tüy kalem ve hokka","Büyüteç tutan el"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('''Red Dead Redemption 2''nin ana karakteri kimdir?', '["Arthur Morgan","Cole Phelps","Niko Bellic","Tommy Vercetti"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('''The Legend of Zelda'' serisinde kullanılan para biriminin adı nedir?', '["Rupee","Gil","Zenny","Bells"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('PlayStation 5''in standart kumandasının adı nedir?', '["DualSense","DualShock","Sixaxis","WaveBird"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('''Mount & Blade'' oyun serisini geliştiren Türk şirketi hangisidir?', '["TaleWorlds","Peak Games","Gram Games","Dream Games"]'::jsonb, 0, 'teknoloji', 'yerel', 'TR', 3),
('Clint Eastwood''un ''Invictus'' filmi 1995''te hangi sporun Dünya Kupası''nı konu alır?', '["Ragbi","Futbol","Kriket","Basketbol"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Sarı Duvar'' adlı dev güney tribünüyle ünlü Alman kulübü hangisidir?', '["Borussia Dortmund","Bayern Münih","Schalke 04","Bayer Leverkusen"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Cool Runnings'' filmi, Jamaika''nın hangi kış sporundaki takımını anlatır?', '["Bobsled","Skeleton","Curling","Biatlon"]'::jsonb, 0, 'spor', 'global', null, 2),
('FIFA''nın yılın en güzel golüne verdiği ödül hangi efsane futbolcunun adını taşır?', '["Ferenc Puskás","Alfredo Di Stéfano","Pelé","Eusébio"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Jerry Maguire'' filminde Tom Cruise''un canlandırdığı karakterin mesleği nedir?', '["Spor menajeri","Antrenör","Spor muhabiri","Takım doktoru"]'::jsonb, 0, 'spor', 'global', null, 2),
('Ballon d''Or sahibi orta saha oyuncusu Luka Modrić hangi ülkelidir?', '["Hırvatistan","Sırbistan","Slovenya","Bosna-Hersek"]'::jsonb, 0, 'spor', 'global', null, 2),
('Denzel Washington''ın ''Titanları Hatırla'' filminde çalıştırdığı lise takımı hangi sporu oynar?', '["Amerikan futbolu","Basketbol","Buz hokeyi","Avustralya futbolu"]'::jsonb, 0, 'spor', 'global', null, 2),
('İlk ''Rocky'' filminde Rocky Balboa hangi şehirde yaşayan bir boksördür?', '["Philadelphia","Pittsburgh","Indianapolis","Boston"]'::jsonb, 0, 'spor', 'global', null, 2),
('David Beckham, Spice Girls''ün hangi üyesiyle evlenmiştir?', '["Victoria Adams","Geri Halliwell","Emma Bunton","Melanie Brown"]'::jsonb, 0, 'spor', 'global', null, 2),
('Fenerbahçe''nin Şükrü Saracoğlu Stadyumu İstanbul''un hangi ilçesindedir?', '["Kadıköy","Beşiktaş","Şişli","Üsküdar"]'::jsonb, 0, 'spor', 'yerel', 'TR', 2),
('Margot Robbie''nin ''I, Tonya'' filminde canlandırdığı sporcu hangi branştadır?', '["Artistik patinaj","Sürat pateni","Artistik jimnastik","Kayakla atlama"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Rocky III'' filmiyle özdeşleşen ''Eye of the Tiger'' şarkısını hangi grup seslendirir?', '["Survivor","Journey","Foreigner","Toto"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Ted Lasso'' dizisinde Ted, İngiltere''de hangi futbol kulübünü çalıştırır?', '["AFC Richmond","Brentford FC","Fulham FC","Millwall FC"]'::jsonb, 0, 'spor', 'global', null, 2),
('Adidas''ın kurucusu Adi Dassler''in ağabeyi Rudolf Dassler hangi markayı kurmuştur?', '["Puma","Reebok","Fila","Kappa"]'::jsonb, 0, 'spor', 'global', null, 2),
('2001 yapımı ''Ali'' filminde Muhammad Ali''yi hangi oyuncu canlandırır?', '["Will Smith","Denzel Washington","Jamie Foxx","Cuba Gooding Jr."]'::jsonb, 0, 'spor', 'global', null, 2),
('Quarterback Tom Brady uzun yıllar hangi Brezilyalı süpermodelle evli kaldı?', '["Gisele Bündchen","Adriana Lima","Alessandra Ambrosio","Izabel Goulart"]'::jsonb, 0, 'spor', 'global', null, 2),
('Ballon d''Or sahibi George Weah sonradan hangi ülkenin devlet başkanı oldu?', '["Liberya","Gana","Nijerya","Kamerun"]'::jsonb, 0, 'spor', 'global', null, 3),
('Karate, bugün Japonya''ya bağlı olan hangi adada doğup gelişmiştir?', '["Okinawa","Hokkaido","Kyushu","Shikoku"]'::jsonb, 0, 'spor', 'global', null, 3),
('''Rush'' (2013) filminde Niki Lauda''nın büyük rakibi olan İngiliz pilot kimdir?', '["James Hunt","Jackie Stewart","Nigel Mansell","Graham Hill"]'::jsonb, 0, 'spor', 'global', null, 3),
('Fransa Açık''ın stadına adını veren Roland Garros aslen ne olarak tanınır?', '["Havacı","Tenisçi","Mimar","Bisikletçi"]'::jsonb, 0, 'spor', 'global', null, 3),
('2008''de NBA''de ''En Çok Gelişme Gösteren Oyuncu'' ödülünü alan Türk basketbolcu kimdir?', '["Hedo Türkoğlu","Mehmet Okur","Ersan İlyasova","Enes Kanter"]'::jsonb, 0, 'spor', 'yerel', 'TR', 3),
('Russell Crowe ''Cinderella Man'' filminde hangi gerçek boksörü canlandırır?', '["James J. Braddock","Jack Dempsey","Jersey Joe Walcott","Max Baer"]'::jsonb, 0, 'spor', 'global', null, 3),
('Steve Carell ve Channing Tatum''lu ''Foxcatcher'' filmi hangi sporu konu alır?', '["Güreş","Boks","Kürek","Eskrim"]'::jsonb, 0, 'spor', 'global', null, 3),
('Atı Incitatus''u konsül yapmayı planladığı anlatılan Roma imparatoru kimdir?', '["Caligula","Nero","Commodus","Tiberius"]'::jsonb, 0, 'tarih', 'global', null, 2),
('1911''de Louvre''dan çalınıp iki yıl sonra bulunan ünlü tablo hangisidir?', '["Mona Lisa","Çığlık","Yıldızlı Gece","İnci Küpeli Kız"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Kristof Kolomb''un ilk seferindeki amiral gemisinin adı nedir?', '["Santa María","Victoria","Golden Hind","São Gabriel"]'::jsonb, 0, 'tarih', 'global', null, 3),
('''İnanılmaz Aile'' filminde süper kahraman kostümleri tasarlayan kısa boylu tasarımcının adı nedir?', '["Edna","Mirage","Evelyn","Helen"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Harry Potter ve Felsefe Taşı''nda taşı koruyan üç başlı köpeğin adı nedir?', '["Fluffy","Fang","Norbert","Şahgaga"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Titanic'' filminde Leonardo DiCaprio''nun canlandırdığı Jack''in soyadı nedir?', '["Dawson","Dalton","Dixon","Dawes"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yüzüklerin Efendisi''nde Tek Yüzük yok edilmek için hangi dağa götürülür?', '["Hüküm Dağı","Yalnız Dağ","Caradhras","Rüzgâr Tepesi"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Disney''in ''Encanto'' filminde Madrigal ailesi hangi ülkede yaşar?', '["Kolombiya","Meksika","Peru","Venezuela"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yeni Hayat'' (Cast Away) filminde Chuck Noland hangi kargo şirketinde çalışır?', '["FedEx","UPS","DHL","TNT"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Pixar''ın ''Cesur'' (Brave) filmi hangi ülkede geçer?', '["İskoçya","İrlanda","Galler","Norveç"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Karlar Ülkesi'' filminde Elsa ile Anna''nın krallığının adı nedir?', '["Arendelle","Corona","Agrabah","Atlantica"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Sevimli Canavarlar'' filminde Sulley''nin bağlandığı küçük kızın adı nedir?', '["Boo","Dot","Lily","Mia"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Black Panther'' filminde Wakanda''nın zenginliğinin kaynağı olan kurgusal metal hangisidir?', '["Vibranyum","Adamantiyum","Kriptonit","Mithril"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Eşkıya'' (1996) filminde Şener Şen''in canlandırdığı karakterin adı nedir?', '["Baran","Cumali","Memo","Haydar"]'::jsonb, 0, 'sinema', 'yerel', 'TR', 2),
('''Hababam Sınıfı'' filmlerinde Halit Akçatepe''nin canlandırdığı karakter kimdir?', '["Güdük Necmi","İnek Şaban","Hayta İsmail","Domdom Ali"]'::jsonb, 0, 'sinema', 'yerel', 'TR', 2),
('''Alacakaranlık'' serisinde Jacob Black hangi hayvana dönüşür?', '["Kurt","Ayı","Puma","Kartal"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Madagaskar'' filminde hayvanat bahçesinden kaçan dörtlüden Gloria hangi hayvandır?', '["Hipopotam","Gergedan","Karıncayiyen","Zürafa"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yaralı Yüz'' (1983) filminde Tony Montana ABD''ye hangi ülkeden gelir?', '["Küba","Kolombiya","Meksika","Porto Riko"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Neşeli Günler'' (The Sound of Music) filmi Avusturya''nın hangi şehrinde geçer?', '["Salzburg","Viyana","Innsbruck","Graz"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Oyuncak Hikâyesi''nde oyuncaklara eziyet eden komşu çocuğun adı nedir?', '["Sid","Hank","Max","Pete"]'::jsonb, 0, 'sinema', 'global', null, 3),
('İlk ''Star Wars'' filminde İmparatorluğun yok ettiği, Prenses Leia''nın büyüdüğü gezegen hangisidir?', '["Alderaan","Naboo","Tatooine","Corellia"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Altıncı His'' filminde ölüleri gördüğünü söyleyen küçük çocuğun adı nedir?', '["Cole","Danny","Tommy","Kevin"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Zor Ölüm'' (Die Hard) filminde rehine dramı hangi şirketin gökdeleninde yaşanır?', '["Nakatomi","Tyrell","Weyland","Cyberdyne"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Ratatuy'' filminde Remy''nin saçını çekerek yönettiği genç aşçının adı nedir?', '["Linguini","Skinner","Gusteau","Horst"]'::jsonb, 0, 'sinema', 'global', null, 3),
('The Beatles grubu hangi İngiliz şehrinde kurulmuştur?', '["Liverpool","Manchester","Londra","Birmingham"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Breaking Bad'' dizisinde Walter White''ın asıl mesleği nedir?', '["Kimya öğretmeni","Fizik öğretmeni","Biyoloji öğretmeni","Eczacı"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Uçamayan kivi kuşu hangi ülkenin ulusal simgesidir?', '["Yeni Zelanda","Avustralya","Güney Afrika","Kosta Rika"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Ninja Kaplumbağalar''ı yetiştiren bilge fare ustanın adı nedir?', '["Splinter","Shredder","Krang","Bebop"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('James Cameron''ın ''Avatar'' filmindeki Na''vi halkının yaşadığı uydunun adı nedir?', '["Pandora","Arrakis","Tatooine","Kripton"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Yaprak Dökümü'' romanının yazarı kimdir?', '["Reşat Nuri Güntekin","Halit Ziya Uşaklıgil","Yakup Kadri","Peyami Safa"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('''Aslan Kral'' filmindeki Timon ve Pumbaa ikilisinden Timon hangi hayvandır?', '["Mirket","Gelincik","Sincap","Rakun"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Disney''in ''Pinokyo'' filminde Pinokyo''nun vicdanı olan cırcır böceğinin adı nedir?', '["Jiminy","Timothy","Sebastian","Flounder"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Caz efsanesi Louis Armstrong en çok hangi enstrümanıyla ünlüdür?', '["Trompet","Saksafon","Trombon","Klarnet"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Hokusai''nin ünlü ''Büyük Dalga'' baskısında dalga hangi yerin açığındadır?', '["Kanagawa","Osaka","Nagasaki","Hiroşima"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Stranger Things'' dizisi hangi kurgusal kasabada geçer?', '["Hawkins","Derry","Castle Rock","Riverdale"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Koyun işkembesinde pişirilen haggis hangi ülkenin ulusal yemeğidir?', '["İskoçya","İrlanda","Galler","İzlanda"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Leonardo DiCaprio ilk Oscar''ını hangi filmle kazanmıştır?', '["Diriliş","Başlangıç","Aviator","Köstebek"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Flamenko dansı İspanya''nın hangi bölgesiyle özdeşleşmiştir?', '["Endülüs","Katalonya","Galiçya","Bask Bölgesi"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Çizgi film köpeği Scooby-Doo''nun en yakın arkadaşı ve sahibi kimdir?', '["Shaggy","Fred","Velma","Daphne"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Endülüs''teki ünlü Mağribi sarayı El Hamra (Alhambra) hangi şehirdedir?', '["Granada","Sevilla","Kurtuba","Toledo"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Asteriks'' çizgi romanlarında Oburiks''in küçük köpeğinin adı nedir?', '["Idefix","Milou","Pluto","Rantanplan"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('The Beatles grubunun ünlü kadrosunda davulları çalan isim kimdir?', '["Ringo Starr","Keith Moon","Charlie Watts","Phil Collins"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Minik Serçe'' lakabıyla anılan şarkıcı kimdir?', '["Sezen Aksu","Ajda Pekkan","Nilüfer","Emel Sayın"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('''Behzat Ç.'' dizisi hangi şehirde geçer?', '["Ankara","İstanbul","İzmir","Eskişehir"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('''Pippi Uzuncorap'' kitaplarının yazarı kimdir?', '["Astrid Lindgren","Selma Lagerlöf","Tove Jansson","H. C. Andersen"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Ajan James Bond hangi İngiliz istihbarat servisi için çalışır?', '["MI6","MI5","GCHQ","SAS"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('James Bond''un ''çalkalanmış, karıştırılmamış'' olarak istediği kokteyl hangisidir?', '["Martini","Mojito","Negroni","Manhattan"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Selvi Boylum Al Yazmalım'' filminde Asya karakterini canlandıran oyuncu kimdir?', '["Türkan Şoray","Hülya Koçyiğit","Fatma Girik","Filiz Akın"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('Korku klasiği ''Kuşlar'' (The Birds) filminin yönetmeni kimdir?', '["Alfred Hitchcock","Stanley Kubrick","Steven Spielberg","Roman Polanski"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Mısır''daki Büyük Sfenks hangi şehrin yakınındadır?', '["Gize","Luksor","Asvan","İskenderiye"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İspanyol mutfağının ünlü pilavı paella hangi bölgenin yemeğidir?', '["Valensiya","Endülüs","Katalonya","Galiçya"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Kristof Kolomb''un 1492''deki ilk seferinde komuta ettiği en büyük gemi hangisidir?', '["Santa María","La Pinta","La Niña","San Salvador"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Dört ABD başkanının yüzünün oyulduğu Rushmore Dağı hangi eyalettedir?', '["Güney Dakota","Kuzey Dakota","Montana","Wyoming"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Van Gogh kulağını, yaşadığı hangi Güney Fransa kasabasında kesmiştir?', '["Arles","Nice","Avignon","Marsilya"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Jurassic Park'' romanının yazarı kimdir?', '["Michael Crichton","Stephen King","Arthur C. Clarke","Ray Bradbury"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''The Big Bang Theory'' dizisindeki Sheldon''un soyadı nedir?', '["Cooper","Hofstadter","Wolowitz","Koothrappali"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''How I Met Your Mother'' dizisinde arkadaşların takıldığı barın adı nedir?', '["MacLaren''s","Paddy''s Pub","Moe''s","Cheers"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Friends'' dizisinde Ross''un evcil maymununun adı nedir?', '["Marcel","Bubbles","Bobo","Mojo"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('İzlenimcilik akımına adını veren Monet tablosunun adı ''İzlenim, ...'' diye nasıl sürer?', '["Gün Doğumu","Gün Batımı","Sabah Sisi","Nilüferler"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Friends''te Joey''nin Dr. Drake Ramoray''i oynadığı pembe dizi hangisidir?', '["Days of Our Lives","General Hospital","Santa Barbara","The Bold and the Beautiful"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Star Wars''taki Chewbacca hangi türden bir yaratıktır?', '["Wookiee","Ewok","Jawa","Twi''lek"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Game of Thrones''ta Stark ailesinin kuzeydeki kalesinin adı nedir?', '["Winterfell","Casterly Rock","Riverrun","Highgarden"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Suşi rulolarını sarmakta kullanılan kurutulmuş deniz yosunu yaprağının adı nedir?', '["Nori","Kombu","Wakame","Hijiki"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Yüzüklerin Efendisi''nde Gollum''un yüzüğü bulmadan önceki asıl adı nedir?', '["Sméagol","Déagol","Gríma","Radagast"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Peter Pan''da Peter''ın Londra''da tanıştığı en büyük Darling kardeşin adı nedir?', '["Wendy","Alice","Lucy","Dorothy"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Selma Lagerlöf''ün kitabında küçülen Nils, hangi kuşun sırtında İsveç''i dolaşır?', '["Kaz","Leylek","Kartal","Turna"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Monte Kristo Kontu kimliğine bürünen genç denizcinin ilk adı nedir?', '["Edmond","Fernand","Albert","Gérard"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Kipling''in ''Orman Kitabı''nda Mowgli''yi koruyup kollayan kara panterin adı nedir?', '["Bagheera","Shere Khan","Kaa","Akela"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Oliver Twist''te Oliver''ın yetimhanede "biraz daha" istediği yemek nedir?', '["Yulaf lapası","Mercimek çorbası","Patates püresi","Etli güveç"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Sabahattin Ali''nin ''Kuyucaklı Yusuf'' romanında Yusuf''un evlendiği kız kimdir?', '["Muazzez","Şahinde","Mihriban","Leman"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('Dede Korkut hikâyelerinde Tepegöz''ü öldüren yiğit kimdir?', '["Basat","Bamsı Beyrek","Kan Turalı","Salur Kazan"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('Yaşar Kemal''in ''İnce Memed'' romanında Memed''in dağa çıkmasına yol açan zalim ağa kimdir?', '["Abdi Ağa","Hüseyin Ağa","Kerim Ağa","Rıza Ağa"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('Dickens''ın ''Noel Şarkısı''ndaki cimri Scrooge''un ilk adı nedir?', '["Ebenezer","Jeremiah","Bartholomew","Nathaniel"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Odysseia''da Odysseus''un mağarada gözünü kör ettiği tepegöz devin adı nedir?', '["Polyphemos","Prokrustes","Talos","Antaios"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''İlyada''da Hektor''un öldürdüğü, Akhilleus''un en yakın dostu kimdir?', '["Patroklos","Agamemnon","Menelaos","Aias"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Dracula''da kontun şatosuna Transilvanya''ya giden genç avukatın soyadı nedir?', '["Harker","Seward","Holmwood","Morris"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Da Vinci Şifresi''nin kahramanı olan Harvard''lı simgebilimcinin soyadı nedir?', '["Langdon","Teabing","Saunière","Fache"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Shakespeare''in ''Julius Caesar''ında Sezar''ın ölürken "Sen de mi?" diye seslendiği kişi kimdir?', '["Brutus","Cassius","Antonius","Octavius"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Muhteşem Gatsby''de Gatsby''nin geceleri izlediği, Daisy''nin iskelesindeki ışık ne renktir?', '["Yeşil","Kırmızı","Mavi","Mor"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Jane Austen''ın ''Aşk ve Gurur'' romanında Elizabeth''in ailesinin soyadı nedir?', '["Bennet","Bingley","Wickham","Lucas"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Gulliver''in Gezileri''nde Gulliver''in devlerle karşılaştığı ülkenin adı nedir?', '["Brobdingnag","Lilliput","Blefuscu","Glubbdubdrib"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Tutunamayanlar''da intihar eden ve Turgut''un izini sürdüğü arkadaşının adı nedir?', '["Selim","Süleyman","Hikmet","Olric"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 3),
('H.G. Wells''in ''Zaman Makinesi''nde yeraltında yaşayan yaratıklara ne ad verilir?', '["Morloklar","Eloiler","Selenitler","Marslılar"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Jane Eyre''de Jane''in mürebbiye olarak çalıştığı malikânenin adı nedir?', '["Thornfield","Pemberley","Netherfield","Lowood"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Sineklerin Tanrısı''nda Ralph''ın gözlüklü, tombul arkadaşı hangi adla anılır?', '["Piggy","Jack","Simon","Roger"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Tolstoy''un ''Savaş ve Barış'' romanındaki Pierre''in soyadı nedir?', '["Bezuhov","Bolkonski","Rostov","Kuragin"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Hemingway''in ''Yaşlı Adam ve Deniz''inde Santiago''ya bağlı genç çocuğun adı nedir?', '["Manolin","Pablo","Miguel","Diego"]'::jsonb, 0, 'edebiyat', 'global', null, 3)
on conflict (soru) do nothing;

-- ---------------------------------------------------- İngilizce çeviri
insert into public.question_translations (question_id, dil, soru, secenekler)
select q.id, 'en', v.en_soru, v.en_secenekler
  from (values
  ('Besteci Frédéric Chopin hangi ülkede doğmuştur?', 'In which country was the composer Frederic Chopin born?', '["Poland","France","Austria","Hungary"]'::jsonb),
  ('''Fındıkkıran'' balesinde Fındıkkıran ve oyuncak askerler hangi hayvanların kralıyla savaşır?', 'In the ballet ''The Nutcracker'', the Nutcracker and his toy soldiers battle the king of which animals?', '["Mice","Cats","Wolves","Bats"]'::jsonb),
  ('Çizgi roman kahramanları Asteriks ile Oburiks hangi halktandır?', 'Comic heroes Asterix and Obelix belong to which ancient people?', '["Gauls","Romans","Vikings","Goths"]'::jsonb),
  ('Chicago''daki aynalı paslanmaz çelik ''Cloud Gate'' heykeli halk arasında ne diye anılır?', 'Chicago''s mirrored stainless steel sculpture ''Cloud Gate'' is popularly known by what nickname?', '["The Bean","The Drop","The Pea","The Egg"]'::jsonb),
  ('''Arzu Tramvayı'' oyununun yazarı kimdir?', 'Who wrote the play ''A Streetcar Named Desire''?', '["Tennessee Williams","Eugene O''Neill","Lorraine Hansberry","Arthur Miller"]'::jsonb),
  ('''Sesler Müziği'' müzikali ve filmi hangi ülkede geçer?', 'In which country is ''The Sound of Music'' set?', '["Austria","Switzerland","Germany","Hungary"]'::jsonb),
  ('Dubai''deki Burj Al Arab oteli neyin biçimini andırır?', 'Dubai''s Burj Al Arab hotel is designed to resemble what?', '["A sail","A tulip","A crescent","A teardrop"]'::jsonb),
  ('The Beatles''ın ''Abbey Road'' albüm kapağında dörtlü nerede yürür?', 'On the cover of The Beatles'' ''Abbey Road'', where are the four band members walking?', '["A zebra crossing","A suspension bridge","A railway track","A sandy beach"]'::jsonb),
  ('Oscar heykelciğindeki şövalye figürü elinde ne tutar?', 'What is the knight on the Oscar statuette holding?', '["A sword","A torch","A scepter","A shield"]'::jsonb),
  ('Washington''daki Lincoln Anıtı''nda Lincoln heykeli hangi duruştadır?', 'How is Abraham Lincoln posed in the statue at the Lincoln Memorial?', '["Seated","Standing","On horseback","Kneeling"]'::jsonb),
  ('''The King and I'' (Kral ve Ben) müzikali hangi krallıkta geçer?', 'In which kingdom is the musical ''The King and I'' set?', '["Siam","Burma","China","India"]'::jsonb),
  ('Andy Warhol''a göre gelecekte herkes kaç dakikalığına dünyaca ünlü olacak?', 'Andy Warhol predicted everyone would be world-famous for how many minutes?', '["15","10","5","30"]'::jsonb),
  ('Vatikan''daki ''Laokoon ve Oğulları'' heykelinde rahip ve oğullarına hangi hayvanlar saldırır?', 'In the ancient sculpture ''Laocoon and His Sons'', what creatures attack the priest and his sons?', '["Snakes","Lions","Eagles","Wolves"]'::jsonb),
  ('Paslanmaz çelikten dev ''Gateway Arch'' kemeri hangi ABD şehrindedir?', 'The giant stainless steel Gateway Arch stands in which US city?', '["St. Louis","Kansas City","Denver","Pittsburgh"]'::jsonb),
  ('''Bitmemiş Senfoni'' adıyla bilinen 8. Senfoni hangi besteciye aittir?', 'Which composer''s Symphony No. 8 is known as the ''Unfinished Symphony''?', '["Schubert","Schumann","Brahms","Mendelssohn"]'::jsonb),
  ('''Güzel Mavi Tuna'' valsinin bestecisi kimdir?', 'Who composed the waltz ''The Blue Danube''?', '["Johann Strauss","Franz Lehar","Johannes Brahms","Franz Schubert"]'::jsonb),
  ('İçine sırtı dönük bozuk para atılan ünlü Trevi Çeşmesi hangi şehirdedir?', 'In which city would you find the famous Trevi Fountain?', '["Rome","Florence","Venice","Naples"]'::jsonb),
  ('Aslan başlı, balık gövdeli ''Merlion'' heykeli hangi şehrin simgesidir?', 'The lion-headed, fish-bodied Merlion statue is the symbol of which city?', '["Singapore","Hong Kong","Bangkok","Manila"]'::jsonb),
  ('Kırmızı tabanlı ayakkabılarıyla ünlü Fransız tasarımcı kimdir?', 'Which French designer is famous for shoes with red soles?', '["Christian Louboutin","Manolo Blahnik","Salvatore Ferragamo","Roger Vivier"]'::jsonb),
  ('Klarnet glissandosuyla açılan ''Rhapsody in Blue'' eserinin bestecisi kimdir?', 'Who composed ''Rhapsody in Blue'', which opens with a famous clarinet glissando?', '["George Gershwin","Leonard Bernstein","Aaron Copland","Cole Porter"]'::jsonb),
  ('Çizgi roman kahramanı Tenten''in yaratıcısı kimdir?', 'Who created the comic book hero Tintin?', '["Hergé","Uderzo","Goscinny","Peyo"]'::jsonb),
  ('''Moulin de la Galette''te Balo'' tablosunun ressamı kimdir?', 'Which Impressionist painted ''Bal du moulin de la Galette''?', '["Renoir","Monet","Degas","Pissarro"]'::jsonb),
  ('''My Fair Lady'' müzikali hangi yazarın oyununa dayanır?', '''My Fair Lady'' is based on a play by which writer?', '["Shaw","Wilde","Coward","Barrie"]'::jsonb),
  ('Pink Floyd''un ''Animals'' albüm kapağında santralin üzerinde hangi şişme hayvan uçar?', 'On the cover of Pink Floyd''s ''Animals'', what inflatable animal floats above the power station?', '["A pig","A sheep","A dog","A cow"]'::jsonb),
  ('Quino''nun çizgi kahramanı küçük Mafalda''nın nefret ettiği yemek hangisidir?', 'Which food does Quino''s little comic heroine Mafalda famously hate?', '["Soup","Spinach","Broccoli","Cauliflower"]'::jsonb),
  ('Londra''daki 30 St Mary Axe gökdeleni halk arasında hangi sebzenin adıyla anılır?', 'London''s 30 St Mary Axe skyscraper is popularly nicknamed after which vegetable?', '["Gherkin","Eggplant","Carrot","Zucchini"]'::jsonb),
  ('Dünyanın en büyük Budist tapınağı sayılan Borobudur hangi ülkededir?', 'The great Buddhist temple of Borobudur is located in which country?', '["Indonesia","Thailand","Myanmar","Sri Lanka"]'::jsonb),
  ('Çaykovski''nin ''1812 Uvertürü''nün finalinde hangi silahın atışları duyulur?', 'Tchaikovsky''s ''1812 Overture'' famously features the firing of which weapon?', '["Cannon","Rifle","Pistol","Rocket"]'::jsonb),
  ('Puantiyeli dev balkabağı heykelleriyle tanınan Japon sanatçı kimdir?', 'Which Japanese artist is known for her giant polka-dotted pumpkin sculptures?', '["Yayoi Kusama","Takashi Murakami","Yoshitomo Nara","Yoko Ono"]'::jsonb),
  ('Puccini''nin ''Tosca'' operası hangi şehirde geçer?', 'In which city is Puccini''s opera ''Tosca'' set?', '["Rome","Florence","Venice","Naples"]'::jsonb),
  ('Kızılderili, kovboy ve polis kostümleriyle sahneye çıkan ''Y.M.C.A.'' grubu hangisidir?', 'Which costumed group, featuring a cowboy, a cop and a Native American, sang ''Y.M.C.A.''?', '["Village People","Bee Gees","Boney M.","KC and the Sunshine Band"]'::jsonb),
  ('Ünlü gitar riffiyle bilinen ''Smoke on the Water'' hangi grubun şarkısıdır?', 'Which band recorded ''Smoke on the Water'', famous for its guitar riff?', '["Deep Purple","Black Sabbath","Uriah Heep","Led Zeppelin"]'::jsonb),
  ('Queen grubunun gitaristi ve ''We Will Rock You'' şarkısının yazarı kimdir?', 'Who is Queen''s guitarist and the writer of ''We Will Rock You''?', '["Brian May","Jimmy Page","Eric Clapton","Ritchie Blackmore"]'::jsonb),
  ('''Hey Ya!'' şarkısıyla 2003''te listeleri sallayan hip hop ikilisi hangisidir?', 'Which hip hop duo shook up the charts in 2003 with ''Hey Ya!''?', '["OutKast","Run-DMC","Black Eyed Peas","Fugees"]'::jsonb),
  ('Annie Lennox''un sesiyle bilinen ''Sweet Dreams (Are Made of This)'' hangi ikilinin şarkısıdır?', 'Which duo, fronted by Annie Lennox, recorded ''Sweet Dreams (Are Made of This)''?', '["Eurythmics","Tears for Fears","Pet Shop Boys","Roxette"]'::jsonb),
  ('Dolores O''Riordan''ın solistliğini yaptığı, ''Zombie'' şarkısıyla bilinen İrlandalı grup hangisidir?', 'Fronted by Dolores O''Riordan, which band had a hit with ''Zombie''?', '["The Cranberries","The Corrs","Garbage","The Smashing Pumpkins"]'::jsonb),
  ('Küçük oğlunun ölümünün ardından ''Tears in Heaven'' şarkısını yazan müzisyen kimdir?', 'Which musician wrote ''Tears in Heaven'' after the death of his young son?', '["Eric Clapton","Phil Collins","Rod Stewart","Elton John"]'::jsonb),
  ('''U Can''t Touch This'' şarkısı ve bol şalvar pantolonuyla ünlenen rapçi kimdir?', 'Which rapper was famous for ''U Can''t Touch This'' and his baggy parachute pants?', '["MC Hammer","Vanilla Ice","Coolio","Young MC"]'::jsonb),
  ('Rob Thomas ile seslendirdiği ''Smooth'' şarkısıyla Grammy toplayan gitarist kimdir?', 'Which guitarist teamed up with Rob Thomas on the Grammy-winning hit ''Smooth''?', '["Carlos Santana","Stevie Ray Vaughan","Mark Knopfler","George Benson"]'::jsonb),
  ('1990''da ''Ice Ice Baby'' şarkısıyla listelerin zirvesine çıkan rapçi kimdir?', 'Which rapper topped the charts in 1990 with ''Ice Ice Baby''?', '["Vanilla Ice","Marky Mark","Kid Rock","Sir Mix-a-Lot"]'::jsonb),
  ('2018 yapımı ''Bohemian Rhapsody'' filminde Freddie Mercury''yi canlandıran oyuncu kimdir?', 'Who played Freddie Mercury in the 2018 film ''Bohemian Rhapsody''?', '["Rami Malek","Ben Whishaw","Dev Patel","Eddie Redmayne"]'::jsonb),
  ('''My Way'' şarkısıyla özdeşleşen, ''Ol'' Blue Eyes'' lakaplı şarkıcı kimdir?', 'Which singer nicknamed ''Ol'' Blue Eyes'' is synonymous with ''My Way''?', '["Frank Sinatra","Dean Martin","Sammy Davis Jr.","Bing Crosby"]'::jsonb),
  ('Rapçi Eminem''in gerçek adı nedir?', 'What is rapper Eminem''s real name?', '["Marshall Mathers","Curtis Jackson","Christopher Wallace","Shawn Carter"]'::jsonb),
  ('''2001: Uzay Macerası''nın açılışında çalan ''Böyle Buyurdu Zerdüşt''ün bestecisi kimdir?', 'Who composed ''Also sprach Zarathustra'', heard at the start of ''2001: A Space Odyssey''?', '["Richard Strauss","Gustav Mahler","Richard Wagner","Anton Bruckner"]'::jsonb),
  ('Michael Jackson''ın ''Thriller'' klibini yöneten yönetmen kimdir?', 'Who directed Michael Jackson''s ''Thriller'' music video?', '["John Landis","Steven Spielberg","John Carpenter","Martin Scorsese"]'::jsonb),
  ('Yaylılar örneğiyle açılan ''Bitter Sweet Symphony'' hangi İngiliz grubun şarkısıdır?', 'Which British band recorded ''Bitter Sweet Symphony'', with its sweeping string sample?', '["The Verve","Suede","The Charlatans","Pulp"]'::jsonb),
  ('Verdi''nin ünlü aryası ''La donna è mobile'' hangi operasında yer alır?', 'Verdi''s famous aria ''La donna e mobile'' comes from which of his operas?', '["Rigoletto","La Traviata","Il Trovatore","Otello"]'::jsonb),
  ('Fransızca şanson klasiği ''Ne me quitte pas'' şarkısını yazıp seslendiren kimdir?', 'Who wrote and first sang the chanson classic ''Ne me quitte pas''?', '["Jacques Brel","Charles Aznavour","Serge Gainsbourg","Georges Brassens"]'::jsonb),
  ('Elton John''un hayatını anlatan ''Rocketman'' filminde Elton John''u oynayan oyuncu kimdir?', 'Who played Elton John in the biopic ''Rocketman''?', '["Taron Egerton","Richard Madden","Jamie Bell","Eddie Redmayne"]'::jsonb),
  ('Google''ın kurucuları Larry Page ve Sergey Brin hangi üniversitede tanıştı?', 'At which university did Google founders Larry Page and Sergey Brin meet?', '["Stanford","MIT","Harvard","Berkeley"]'::jsonb),
  ('İnternet tarayıcılarında yeni bir sekme açmak için kullanılan klavye kısayolu hangisidir?', 'Which keyboard shortcut opens a new tab in most web browsers?', '["Ctrl+T","Ctrl+N","Ctrl+W","Ctrl+Tab"]'::jsonb),
  ('Mario ilk kez hangi atari oyununda sahneye çıkmıştır?', 'In which arcade game did Mario make his first appearance?', '["Donkey Kong","Mario Bros.","Pac-Man","Popeye"]'::jsonb),
  ('İnternet tarayıcılarında sayfayı yenilemek için basılan işlev tuşu hangisidir?', 'Which function key refreshes the page in most web browsers?', '["F5","F1","F11","F12"]'::jsonb),
  ('Windows''ta bilgisayarı anında kilitleyen klavye kısayolu hangisidir?', 'In Windows, which keyboard shortcut instantly locks the computer?', '["Win+L","Win+D","Win+E","Win+R"]'::jsonb),
  ('PUBG''de maçı kazanınca ekranda çıkan ünlü zafer yazısında hangi yemek geçer?', 'In PUBG, which food appears in the famous victory message shown to the winner?', '["Chicken","Pizza","Burger","Steak"]'::jsonb),
  ('Microsoft''un Internet Explorer''ın yerine getirdiği tarayıcının adı nedir?', 'Which browser did Microsoft introduce to replace Internet Explorer?', '["Edge","Safari","Opera","Vivaldi"]'::jsonb),
  ('Sonic oyunlarında Sonic''in baş düşmanı olan bıyıklı bilim insanı kimdir?', 'Which mustachioed scientist is Sonic the Hedgehog''s archenemy?', '["Dr. Eggman","Dr. Wily","Dr. Neo Cortex","Dr. Nefarious"]'::jsonb),
  ('Steve Jobs''un ardından 2011''de Apple''ın CEO''su olan kişi kimdir?', 'Who succeeded Steve Jobs as Apple''s CEO in 2011?', '["Tim Cook","Jony Ive","Phil Schiller","Scott Forstall"]'::jsonb),
  ('Sonic oyunlarında Sonic''in uçabilen tilki yardımcısının adı nedir?', 'In the Sonic games, what is the name of Sonic''s flying fox sidekick?', '["Tails","Knuckles","Shadow","Silver"]'::jsonb),
  ('Pokémon animesinde Team Rocket''e eşlik eden, insan gibi konuşan Pokémon hangisidir?', 'In the Pokemon anime, which Pokemon travels with Team Rocket and can talk like a human?', '["Meowth","Psyduck","Jigglypuff","Togepi"]'::jsonb),
  ('SpaceX''in iniş yapıp yeniden kullanılabilen roket ailesinin adı nedir?', 'What is the name of SpaceX''s family of reusable, self-landing rockets?', '["Falcon","Atlas","Ariane","Soyuz"]'::jsonb),
  ('Chrome''da internet bağlantısı yokken çıkan oyunda hangi hayvan koşar?', 'In Chrome''s offline game, which animal does the player control?', '["Dinosaur","Kangaroo","Rabbit","Crocodile"]'::jsonb),
  ('Minecraft''ta lav ve ateşle dolu cehennemsi boyutun adı nedir?', 'In Minecraft, what is the name of the hellish dimension full of lava and fire?', '["The Nether","The End","The Overworld","The Aether"]'::jsonb),
  ('''Assassin''s Creed II''de Rönesans İtalyası''nda geçen hikâyenin kahramanı kimdir?', 'Who is the hero of Assassin''s Creed II, set in Renaissance Italy?', '["Ezio","Altair","Connor","Edward"]'::jsonb),
  ('Google''ın çatı şirketi olarak 2015''te kurulan holdingin adı nedir?', 'What is the name of the parent company created for Google in 2015?', '["Alphabet","Oracle","Verizon","Nvidia"]'::jsonb),
  ('Samsung''un amiral gemisi akıllı telefon serisinin adı nedir?', 'What is the name of Samsung''s flagship smartphone line?', '["Galaxy","Xperia","Pixel","Lumia"]'::jsonb),
  ('''Halo'' oyun serisinin zırhlı kahramanı hangi lakapla bilinir?', 'By what title is the armored hero of the ''Halo'' series known?', '["Master Chief","Doom Slayer","Solid Snake","Big Boss"]'::jsonb),
  ('Google''ın ''Bard'' adlı yapay zekâ sohbet botu 2024''te hangi adı almıştır?', 'In 2024, Google''s AI chatbot Bard was renamed to what?', '["Gemini","Copilot","Grok","Llama"]'::jsonb),
  ('''Grand Theft Auto V'' hangi kurgusal şehirde geçer?', 'In which fictional city is ''Grand Theft Auto V'' set?', '["Los Santos","Liberty City","Vice City","San Fierro"]'::jsonb),
  ('''Half-Life'' serisinin levye taşıyan bilim insanı kahramanı kimdir?', 'Who is the crowbar-wielding scientist hero of the Half-Life series?', '["Gordon Freeman","Isaac Clarke","Adam Jensen","Commander Shepard"]'::jsonb),
  ('Vikipedi''yi Larry Sanger ile birlikte kuran kişi kimdir?', 'Who co-founded Wikipedia with Larry Sanger?', '["Jimmy Wales","Craig Newmark","Pierre Omidyar","Reid Hoffman"]'::jsonb),
  ('''Uncharted'' oyun serisinin hazine avcısı kahramanı kimdir?', 'Who is the treasure-hunting hero of the Uncharted video game series?', '["Nathan Drake","Sam Fisher","Max Payne","Marcus Fenix"]'::jsonb),
  ('Zelda serisinde Ganon''un ele geçirmek istediği kutsal altın emanetin adı nedir?', 'In the Zelda series, what sacred golden relic does Ganon seek to possess?', '["Triforce","Master Sword","Ocarina","Moon Pearl"]'::jsonb),
  ('''Portal'' oyununda ''yalan'' olduğu söylenen vaat edilmiş ödül nedir?', 'In the game ''Portal'', what promised reward is said to be ''a lie''?', '["Cake","A medal","Cookies","Ice cream"]'::jsonb),
  ('İlk ''BioShock'' oyunu hangi su altı şehrinde geçer?', 'The original ''BioShock'' is set in which underwater city?', '["Rapture","Columbia","Atlantis","Eden"]'::jsonb),
  ('Nokia, 1865''te kurulduğunda hangi işle uğraşan bir şirketti?', 'When Nokia was founded in 1865, what kind of business was it?', '["Paper making","Shipbuilding","Textile making","Mining"]'::jsonb),
  ('Tesla''nın geliştirdiği insansı robotun adı nedir?', 'What is the name of the humanoid robot being developed by Tesla?', '["Optimus","Atlas","ASIMO","Digit"]'::jsonb),
  ('eBay''de satılan ilk ürün olarak bilinen bozuk eşya nedir?', 'What broken item is known as the first thing ever sold on eBay?', '["Laser pointer","Pocket calculator","Digital wristwatch","Cassette player"]'::jsonb),
  ('Instagram''ı Mike Krieger ile birlikte kuran kişi kimdir?', 'Who co-founded Instagram with Mike Krieger?', '["Kevin Systrom","Evan Spiegel","Jack Dorsey","Jan Koum"]'::jsonb),
  ('Vikipedi''nin logosunda hangi nesne yer alır?', 'What object is shown in Wikipedia''s logo?', '["Jigsaw puzzle globe","Open book","Quill and inkwell","Hand with magnifier"]'::jsonb),
  ('''Red Dead Redemption 2''nin ana karakteri kimdir?', 'Who is the main protagonist of Red Dead Redemption 2?', '["Arthur Morgan","Cole Phelps","Niko Bellic","Tommy Vercetti"]'::jsonb),
  ('''The Legend of Zelda'' serisinde kullanılan para biriminin adı nedir?', 'What is the name of the currency used in ''The Legend of Zelda'' series?', '["Rupee","Gil","Zenny","Bells"]'::jsonb),
  ('PlayStation 5''in standart kumandasının adı nedir?', 'What is the name of the standard PlayStation 5 controller?', '["DualSense","DualShock","Sixaxis","WaveBird"]'::jsonb),
  ('Clint Eastwood''un ''Invictus'' filmi 1995''te hangi sporun Dünya Kupası''nı konu alır?', 'Clint Eastwood''s ''Invictus'' centers on the 1995 World Cup of which sport?', '["Rugby","Football","Cricket","Basketball"]'::jsonb),
  ('''Sarı Duvar'' adlı dev güney tribünüyle ünlü Alman kulübü hangisidir?', 'Which German club is famous for its giant ''Yellow Wall'' stand?', '["Borussia Dortmund","Bayern Munich","Schalke 04","Bayer Leverkusen"]'::jsonb),
  ('''Cool Runnings'' filmi, Jamaika''nın hangi kış sporundaki takımını anlatır?', '''Cool Runnings'' follows a Jamaican team competing in which winter sport?', '["Bobsleigh","Skeleton","Curling","Biathlon"]'::jsonb),
  ('FIFA''nın yılın en güzel golüne verdiği ödül hangi efsane futbolcunun adını taşır?', 'FIFA''s award for the goal of the year is named after which legendary player?', '["Ferenc Puskas","Alfredo Di Stefano","Pele","Eusebio"]'::jsonb),
  ('''Jerry Maguire'' filminde Tom Cruise''un canlandırdığı karakterin mesleği nedir?', 'What is Tom Cruise''s character''s job in ''Jerry Maguire''?', '["Sports agent","Coach","Sports reporter","Team doctor"]'::jsonb),
  ('Ballon d''Or sahibi orta saha oyuncusu Luka Modrić hangi ülkelidir?', 'Ballon d''Or-winning midfielder Luka Modric represents which country?', '["Croatia","Serbia","Slovenia","Bosnia and Herzegovina"]'::jsonb),
  ('Denzel Washington''ın ''Titanları Hatırla'' filminde çalıştırdığı lise takımı hangi sporu oynar?', 'In ''Remember the Titans'', Denzel Washington coaches a high school team in which sport?', '["American football","Basketball","Ice hockey","Australian rules football"]'::jsonb),
  ('İlk ''Rocky'' filminde Rocky Balboa hangi şehirde yaşayan bir boksördür?', 'In the original ''Rocky'', which city is boxer Rocky Balboa from?', '["Philadelphia","Pittsburgh","Indianapolis","Boston"]'::jsonb),
  ('David Beckham, Spice Girls''ün hangi üyesiyle evlenmiştir?', 'Which Spice Girl did David Beckham marry?', '["Victoria Adams","Geri Halliwell","Emma Bunton","Melanie Brown"]'::jsonb),
  ('Margot Robbie''nin ''I, Tonya'' filminde canlandırdığı sporcu hangi branştadır?', 'In ''I, Tonya'', Margot Robbie plays an athlete from which sport?', '["Figure skating","Speed skating","Artistic gymnastics","Ski jumping"]'::jsonb),
  ('''Rocky III'' filmiyle özdeşleşen ''Eye of the Tiger'' şarkısını hangi grup seslendirir?', 'Which band performed ''Eye of the Tiger'', the song made famous by ''Rocky III''?', '["Survivor","Journey","Foreigner","Toto"]'::jsonb),
  ('''Ted Lasso'' dizisinde Ted, İngiltere''de hangi futbol kulübünü çalıştırır?', 'In the series ''Ted Lasso'', which English football club does Ted coach?', '["AFC Richmond","Brentford FC","Fulham FC","Millwall FC"]'::jsonb),
  ('Adidas''ın kurucusu Adi Dassler''in ağabeyi Rudolf Dassler hangi markayı kurmuştur?', 'Adidas founder Adi Dassler''s older brother Rudolf founded which sportswear brand?', '["Puma","Reebok","Fila","Kappa"]'::jsonb),
  ('2001 yapımı ''Ali'' filminde Muhammad Ali''yi hangi oyuncu canlandırır?', 'Who played Muhammad Ali in the 2001 film ''Ali''?', '["Will Smith","Denzel Washington","Jamie Foxx","Cuba Gooding Jr."]'::jsonb),
  ('Quarterback Tom Brady uzun yıllar hangi Brezilyalı süpermodelle evli kaldı?', 'NFL quarterback Tom Brady was married for years to which Brazilian supermodel?', '["Gisele Bundchen","Adriana Lima","Alessandra Ambrosio","Izabel Goulart"]'::jsonb),
  ('Ballon d''Or sahibi George Weah sonradan hangi ülkenin devlet başkanı oldu?', 'Ballon d''Or winner George Weah later became president of which country?', '["Liberia","Ghana","Nigeria","Cameroon"]'::jsonb),
  ('Karate, bugün Japonya''ya bağlı olan hangi adada doğup gelişmiştir?', 'Karate originated on which island that is now part of Japan?', '["Okinawa","Hokkaido","Kyushu","Shikoku"]'::jsonb),
  ('''Rush'' (2013) filminde Niki Lauda''nın büyük rakibi olan İngiliz pilot kimdir?', 'In ''Rush'' (2013), which British driver is Niki Lauda''s great rival?', '["James Hunt","Jackie Stewart","Nigel Mansell","Graham Hill"]'::jsonb),
  ('Fransa Açık''ın stadına adını veren Roland Garros aslen ne olarak tanınır?', 'Roland Garros, after whom the French Open stadium is named, was famous as what?', '["Aviator","Tennis player","Architect","Cyclist"]'::jsonb),
  ('Russell Crowe ''Cinderella Man'' filminde hangi gerçek boksörü canlandırır?', 'Which real-life boxer does Russell Crowe play in ''Cinderella Man''?', '["James J. Braddock","Jack Dempsey","Jersey Joe Walcott","Max Baer"]'::jsonb),
  ('Steve Carell ve Channing Tatum''lu ''Foxcatcher'' filmi hangi sporu konu alır?', 'The film ''Foxcatcher'', starring Steve Carell and Channing Tatum, centers on which sport?', '["Wrestling","Boxing","Rowing","Fencing"]'::jsonb),
  ('Atı Incitatus''u konsül yapmayı planladığı anlatılan Roma imparatoru kimdir?', 'Which Roman emperor is said to have planned to make his horse Incitatus a consul?', '["Caligula","Nero","Commodus","Tiberius"]'::jsonb),
  ('1911''de Louvre''dan çalınıp iki yıl sonra bulunan ünlü tablo hangisidir?', 'Which famous painting was stolen from the Louvre in 1911 and recovered two years later?', '["Mona Lisa","The Scream","The Starry Night","Girl with a Pearl Earring"]'::jsonb),
  ('Kristof Kolomb''un ilk seferindeki amiral gemisinin adı nedir?', 'What was the name of Christopher Columbus''s flagship on his first voyage?', '["Santa Maria","Victoria","Golden Hind","Sao Gabriel"]'::jsonb),
  ('''İnanılmaz Aile'' filminde süper kahraman kostümleri tasarlayan kısa boylu tasarımcının adı nedir?', 'In ''The Incredibles'', what is the first name of the tiny designer who makes the superhero suits?', '["Edna","Mirage","Evelyn","Helen"]'::jsonb),
  ('''Harry Potter ve Felsefe Taşı''nda taşı koruyan üç başlı köpeğin adı nedir?', 'In ''Harry Potter and the Sorcerer''s Stone'', what is the name of the three-headed dog guarding the stone?', '["Fluffy","Fang","Norbert","Buckbeak"]'::jsonb),
  ('''Titanic'' filminde Leonardo DiCaprio''nun canlandırdığı Jack''in soyadı nedir?', 'In ''Titanic'', what is the surname of Leonardo DiCaprio''s character Jack?', '["Dawson","Dalton","Dixon","Dawes"]'::jsonb),
  ('''Yüzüklerin Efendisi''nde Tek Yüzük yok edilmek için hangi dağa götürülür?', 'In ''The Lord of the Rings'', to which mountain must the One Ring be taken to be destroyed?', '["Mount Doom","The Lonely Mountain","Caradhras","Weathertop"]'::jsonb),
  ('Disney''in ''Encanto'' filminde Madrigal ailesi hangi ülkede yaşar?', 'In Disney''s ''Encanto'', which country is the Madrigal family''s home?', '["Colombia","Mexico","Peru","Venezuela"]'::jsonb),
  ('''Yeni Hayat'' (Cast Away) filminde Chuck Noland hangi kargo şirketinde çalışır?', 'In ''Cast Away'', which delivery company does Chuck Noland work for?', '["FedEx","UPS","DHL","TNT"]'::jsonb),
  ('Pixar''ın ''Cesur'' (Brave) filmi hangi ülkede geçer?', 'In which country is Pixar''s ''Brave'' set?', '["Scotland","Ireland","Wales","Norway"]'::jsonb),
  ('''Karlar Ülkesi'' filminde Elsa ile Anna''nın krallığının adı nedir?', 'In ''Frozen'', what is the name of the kingdom ruled by Elsa and Anna''s family?', '["Arendelle","Corona","Agrabah","Atlantica"]'::jsonb),
  ('''Sevimli Canavarlar'' filminde Sulley''nin bağlandığı küçük kızın adı nedir?', 'In ''Monsters, Inc.'', what name does Sulley give the little girl who wanders into Monstropolis?', '["Boo","Dot","Lily","Mia"]'::jsonb),
  ('''Black Panther'' filminde Wakanda''nın zenginliğinin kaynağı olan kurgusal metal hangisidir?', 'In ''Black Panther'', which fictional metal is the source of Wakanda''s wealth?', '["Vibranium","Adamantium","Kryptonite","Mithril"]'::jsonb),
  ('''Alacakaranlık'' serisinde Jacob Black hangi hayvana dönüşür?', 'In the ''Twilight'' saga, what animal does Jacob Black transform into?', '["Wolf","Bear","Cougar","Eagle"]'::jsonb),
  ('''Madagaskar'' filminde hayvanat bahçesinden kaçan dörtlüden Gloria hangi hayvandır?', 'In ''Madagascar'', what kind of animal is Gloria?', '["Hippo","Rhino","Anteater","Giraffe"]'::jsonb),
  ('''Yaralı Yüz'' (1983) filminde Tony Montana ABD''ye hangi ülkeden gelir?', 'In ''Scarface'' (1983), which country does Tony Montana come to the US from?', '["Cuba","Colombia","Mexico","Puerto Rico"]'::jsonb),
  ('''Neşeli Günler'' (The Sound of Music) filmi Avusturya''nın hangi şehrinde geçer?', 'In which Austrian city is ''The Sound of Music'' set?', '["Salzburg","Vienna","Innsbruck","Graz"]'::jsonb),
  ('''Oyuncak Hikâyesi''nde oyuncaklara eziyet eden komşu çocuğun adı nedir?', 'In ''Toy Story'', what is the name of Andy''s toy-torturing neighbor?', '["Sid","Hank","Max","Pete"]'::jsonb),
  ('İlk ''Star Wars'' filminde İmparatorluğun yok ettiği, Prenses Leia''nın büyüdüğü gezegen hangisidir?', 'In the original ''Star Wars'', which planet, Princess Leia''s home, is destroyed by the Empire?', '["Alderaan","Naboo","Tatooine","Corellia"]'::jsonb),
  ('''Altıncı His'' filminde ölüleri gördüğünü söyleyen küçük çocuğun adı nedir?', 'In ''The Sixth Sense'', what is the first name of the boy who sees dead people?', '["Cole","Danny","Tommy","Kevin"]'::jsonb),
  ('''Zor Ölüm'' (Die Hard) filminde rehine dramı hangi şirketin gökdeleninde yaşanır?', 'In ''Die Hard'', which corporation''s skyscraper is taken over by the hostage-takers?', '["Nakatomi","Tyrell","Weyland","Cyberdyne"]'::jsonb),
  ('''Ratatuy'' filminde Remy''nin saçını çekerek yönettiği genç aşçının adı nedir?', 'In ''Ratatouille'', what is the name of the young cook Remy controls by pulling his hair?', '["Linguini","Skinner","Gusteau","Horst"]'::jsonb),
  ('The Beatles grubu hangi İngiliz şehrinde kurulmuştur?', 'In which English city were The Beatles formed?', '["Liverpool","Manchester","London","Birmingham"]'::jsonb),
  ('''Breaking Bad'' dizisinde Walter White''ın asıl mesleği nedir?', 'In ''Breaking Bad'', what is Walter White''s original job?', '["Chemistry teacher","Physics teacher","Biology teacher","Pharmacist"]'::jsonb),
  ('Uçamayan kivi kuşu hangi ülkenin ulusal simgesidir?', 'The flightless kiwi bird is the national symbol of which country?', '["New Zealand","Australia","South Africa","Costa Rica"]'::jsonb),
  ('Ninja Kaplumbağalar''ı yetiştiren bilge fare ustanın adı nedir?', 'What is the name of the wise rat who trains the Teenage Mutant Ninja Turtles?', '["Splinter","Shredder","Krang","Bebop"]'::jsonb),
  ('James Cameron''ın ''Avatar'' filmindeki Na''vi halkının yaşadığı uydunun adı nedir?', 'In James Cameron''s ''Avatar'', what is the name of the moon where the Na''vi live?', '["Pandora","Arrakis","Tatooine","Krypton"]'::jsonb),
  ('''Aslan Kral'' filmindeki Timon ve Pumbaa ikilisinden Timon hangi hayvandır?', 'In The Lion King, what kind of animal is Timon?', '["Meerkat","Weasel","Squirrel","Raccoon"]'::jsonb),
  ('Disney''in ''Pinokyo'' filminde Pinokyo''nun vicdanı olan cırcır böceğinin adı nedir?', 'In Disney''s ''Pinocchio'', what is the name of the cricket who acts as Pinocchio''s conscience?', '["Jiminy","Timothy","Sebastian","Flounder"]'::jsonb),
  ('Caz efsanesi Louis Armstrong en çok hangi enstrümanıyla ünlüdür?', 'Jazz legend Louis Armstrong was best known for playing which instrument?', '["Trumpet","Saxophone","Trombone","Clarinet"]'::jsonb),
  ('Hokusai''nin ünlü ''Büyük Dalga'' baskısında dalga hangi yerin açığındadır?', 'Hokusai''s famous print shows The Great Wave off which Japanese location?', '["Kanagawa","Osaka","Nagasaki","Hiroshima"]'::jsonb),
  ('''Stranger Things'' dizisi hangi kurgusal kasabada geçer?', 'Stranger Things is set in which fictional town?', '["Hawkins","Derry","Castle Rock","Riverdale"]'::jsonb),
  ('Koyun işkembesinde pişirilen haggis hangi ülkenin ulusal yemeğidir?', 'Haggis, traditionally cooked in a sheep''s stomach, is the national dish of which country?', '["Scotland","Ireland","Wales","Iceland"]'::jsonb),
  ('Leonardo DiCaprio ilk Oscar''ını hangi filmle kazanmıştır?', 'For which film did Leonardo DiCaprio win his first Oscar?', '["The Revenant","Inception","The Aviator","The Departed"]'::jsonb),
  ('Flamenko dansı İspanya''nın hangi bölgesiyle özdeşleşmiştir?', 'Flamenco is most closely associated with which region of Spain?', '["Andalusia","Catalonia","Galicia","Basque Country"]'::jsonb),
  ('Çizgi film köpeği Scooby-Doo''nun en yakın arkadaşı ve sahibi kimdir?', 'Who is Scooby-Doo''s owner and best friend?', '["Shaggy","Fred","Velma","Daphne"]'::jsonb),
  ('Endülüs''teki ünlü Mağribi sarayı El Hamra (Alhambra) hangi şehirdedir?', 'The famous Moorish palace complex of the Alhambra is in which Spanish city?', '["Granada","Seville","Cordoba","Toledo"]'::jsonb),
  ('''Asteriks'' çizgi romanlarında Oburiks''in küçük köpeğinin adı nedir?', 'In the Asterix comics, what is the name of Obelix''s little dog?', '["Dogmatix","Snowy","Pluto","Rantanplan"]'::jsonb),
  ('The Beatles grubunun ünlü kadrosunda davulları çalan isim kimdir?', 'Who played drums in the classic line-up of The Beatles?', '["Ringo Starr","Keith Moon","Charlie Watts","Phil Collins"]'::jsonb),
  ('''Pippi Uzuncorap'' kitaplarının yazarı kimdir?', 'Who wrote the Pippi Longstocking books?', '["Astrid Lindgren","Selma Lagerlof","Tove Jansson","H. C. Andersen"]'::jsonb),
  ('Ajan James Bond hangi İngiliz istihbarat servisi için çalışır?', 'Which British intelligence service does James Bond work for?', '["MI6","MI5","GCHQ","SAS"]'::jsonb),
  ('James Bond''un ''çalkalanmış, karıştırılmamış'' olarak istediği kokteyl hangisidir?', 'Which cocktail does James Bond famously order ''shaken, not stirred''?', '["Martini","Mojito","Negroni","Manhattan"]'::jsonb),
  ('Korku klasiği ''Kuşlar'' (The Birds) filminin yönetmeni kimdir?', 'Who directed the horror classic ''The Birds''?', '["Alfred Hitchcock","Stanley Kubrick","Steven Spielberg","Roman Polanski"]'::jsonb),
  ('Mısır''daki Büyük Sfenks hangi şehrin yakınındadır?', 'Near which Egyptian city does the Great Sphinx stand?', '["Giza","Luxor","Aswan","Alexandria"]'::jsonb),
  ('İspanyol mutfağının ünlü pilavı paella hangi bölgenin yemeğidir?', 'Paella, Spain''s famous rice dish, originally comes from which region?', '["Valencia","Andalusia","Catalonia","Galicia"]'::jsonb),
  ('Kristof Kolomb''un 1492''deki ilk seferinde komuta ettiği en büyük gemi hangisidir?', 'On Columbus''s first voyage in 1492, which was the largest ship, his flagship?', '["Santa Maria","La Pinta","La Nina","San Salvador"]'::jsonb),
  ('Dört ABD başkanının yüzünün oyulduğu Rushmore Dağı hangi eyalettedir?', 'In which US state is Mount Rushmore located?', '["South Dakota","North Dakota","Montana","Wyoming"]'::jsonb),
  ('Van Gogh kulağını, yaşadığı hangi Güney Fransa kasabasında kesmiştir?', 'In which southern French town did Van Gogh cut off his ear?', '["Arles","Nice","Avignon","Marseille"]'::jsonb),
  ('''Jurassic Park'' romanının yazarı kimdir?', 'Who wrote the novel ''Jurassic Park''?', '["Michael Crichton","Stephen King","Arthur C. Clarke","Ray Bradbury"]'::jsonb),
  ('''The Big Bang Theory'' dizisindeki Sheldon''un soyadı nedir?', 'On The Big Bang Theory, what is Sheldon''s surname?', '["Cooper","Hofstadter","Wolowitz","Koothrappali"]'::jsonb),
  ('''How I Met Your Mother'' dizisinde arkadaşların takıldığı barın adı nedir?', 'In How I Met Your Mother, what is the name of the gang''s regular bar?', '["MacLaren''s","Paddy''s Pub","Moe''s","Cheers"]'::jsonb),
  ('''Friends'' dizisinde Ross''un evcil maymununun adı nedir?', 'On Friends, what is the name of Ross''s pet monkey?', '["Marcel","Bubbles","Bobo","Mojo"]'::jsonb),
  ('İzlenimcilik akımına adını veren Monet tablosunun adı ''İzlenim, ...'' diye nasıl sürer?', 'Monet''s painting that gave Impressionism its name is ''Impression,'' what?', '["Sunrise","Sunset","Morning Mist","Water Lilies"]'::jsonb),
  ('''Friends''te Joey''nin Dr. Drake Ramoray''i oynadığı pembe dizi hangisidir?', 'On Friends, which soap opera does Joey star in as Dr. Drake Ramoray?', '["Days of Our Lives","General Hospital","Santa Barbara","The Bold and the Beautiful"]'::jsonb),
  ('''Star Wars''taki Chewbacca hangi türden bir yaratıktır?', 'In ''Star Wars'', what species is Chewbacca?', '["Wookiee","Ewok","Jawa","Twi''lek"]'::jsonb),
  ('''Game of Thrones''ta Stark ailesinin kuzeydeki kalesinin adı nedir?', 'In ''Game of Thrones'', what is the name of the Stark family''s castle in the North?', '["Winterfell","Casterly Rock","Riverrun","Highgarden"]'::jsonb),
  ('Suşi rulolarını sarmakta kullanılan kurutulmuş deniz yosunu yaprağının adı nedir?', 'What is the dried seaweed sheet used to wrap sushi rolls called?', '["Nori","Kombu","Wakame","Hijiki"]'::jsonb),
  ('''Yüzüklerin Efendisi''nde Gollum''un yüzüğü bulmadan önceki asıl adı nedir?', 'In ''The Lord of the Rings'', what was Gollum''s original name?', '["Smeagol","Deagol","Grima","Radagast"]'::jsonb),
  ('''Peter Pan''da Peter''ın Londra''da tanıştığı en büyük Darling kardeşin adı nedir?', 'In ''Peter Pan'', what is the name of the eldest Darling child whom Peter meets in London?', '["Wendy","Alice","Lucy","Dorothy"]'::jsonb),
  ('Selma Lagerlöf''ün kitabında küçülen Nils, hangi kuşun sırtında İsveç''i dolaşır?', 'In Selma Lagerlof''s book, on the back of which bird does the shrunken Nils travel across Sweden?', '["Goose","Stork","Eagle","Crane"]'::jsonb),
  ('Monte Kristo Kontu kimliğine bürünen genç denizcinin ilk adı nedir?', 'What is the first name of the young sailor who becomes the Count of Monte Cristo?', '["Edmond","Fernand","Albert","Gerard"]'::jsonb),
  ('Kipling''in ''Orman Kitabı''nda Mowgli''yi koruyup kollayan kara panterin adı nedir?', 'In Kipling''s ''The Jungle Book'', what is the name of the black panther who protects Mowgli?', '["Bagheera","Shere Khan","Kaa","Akela"]'::jsonb),
  ('''Oliver Twist''te Oliver''ın yetimhanede "biraz daha" istediği yemek nedir?', 'In ''Oliver Twist'', what food does Oliver famously ask for more of in the workhouse?', '["Gruel","Lentil soup","Mashed potatoes","Meat stew"]'::jsonb),
  ('Dickens''ın ''Noel Şarkısı''ndaki cimri Scrooge''un ilk adı nedir?', 'In Dickens''s ''A Christmas Carol'', what is miserly Scrooge''s first name?', '["Ebenezer","Jeremiah","Bartholomew","Nathaniel"]'::jsonb),
  ('''Odysseia''da Odysseus''un mağarada gözünü kör ettiği tepegöz devin adı nedir?', 'In the ''Odyssey'', what is the name of the Cyclops whom Odysseus blinds in his cave?', '["Polyphemus","Procrustes","Talos","Antaeus"]'::jsonb),
  ('''İlyada''da Hektor''un öldürdüğü, Akhilleus''un en yakın dostu kimdir?', 'In the ''Iliad'', which close friend of Achilles is killed by Hector?', '["Patroclus","Agamemnon","Menelaus","Ajax"]'::jsonb),
  ('''Dracula''da kontun şatosuna Transilvanya''ya giden genç avukatın soyadı nedir?', 'In ''Dracula'', what is the surname of the young solicitor who travels to the Count''s castle?', '["Harker","Seward","Holmwood","Morris"]'::jsonb),
  ('''Da Vinci Şifresi''nin kahramanı olan Harvard''lı simgebilimcinin soyadı nedir?', 'In ''The Da Vinci Code'', what is the surname of the Harvard symbologist hero?', '["Langdon","Teabing","Sauniere","Fache"]'::jsonb),
  ('Shakespeare''in ''Julius Caesar''ında Sezar''ın ölürken "Sen de mi?" diye seslendiği kişi kimdir?', 'In Shakespeare''s ''Julius Caesar'', to whom does the dying Caesar say ''Et tu''?', '["Brutus","Cassius","Antony","Octavius"]'::jsonb),
  ('''Muhteşem Gatsby''de Gatsby''nin geceleri izlediği, Daisy''nin iskelesindeki ışık ne renktir?', 'In ''The Great Gatsby'', what color is the light at the end of Daisy''s dock?', '["Green","Red","Blue","Purple"]'::jsonb),
  ('Jane Austen''ın ''Aşk ve Gurur'' romanında Elizabeth''in ailesinin soyadı nedir?', 'In Jane Austen''s ''Pride and Prejudice'', what is Elizabeth''s family name?', '["Bennet","Bingley","Wickham","Lucas"]'::jsonb),
  ('''Gulliver''in Gezileri''nde Gulliver''in devlerle karşılaştığı ülkenin adı nedir?', 'In ''Gulliver''s Travels'', what is the name of the land of giants?', '["Brobdingnag","Lilliput","Blefuscu","Glubbdubdrib"]'::jsonb),
  ('H.G. Wells''in ''Zaman Makinesi''nde yeraltında yaşayan yaratıklara ne ad verilir?', 'In H.G. Wells''s ''The Time Machine'', what are the underground-dwelling creatures called?', '["Morlocks","Eloi","Selenites","Martians"]'::jsonb),
  ('''Jane Eyre''de Jane''in mürebbiye olarak çalıştığı malikânenin adı nedir?', 'In ''Jane Eyre'', at which house does Jane work as a governess?', '["Thornfield","Pemberley","Netherfield","Lowood"]'::jsonb),
  ('''Sineklerin Tanrısı''nda Ralph''ın gözlüklü, tombul arkadaşı hangi adla anılır?', 'In ''Lord of the Flies'', what name is Ralph''s bespectacled, overweight companion known by?', '["Piggy","Jack","Simon","Roger"]'::jsonb),
  ('Tolstoy''un ''Savaş ve Barış'' romanındaki Pierre''in soyadı nedir?', 'In Tolstoy''s ''War and Peace'', what is Pierre''s surname?', '["Bezukhov","Bolkonsky","Rostov","Kuragin"]'::jsonb),
  ('Hemingway''in ''Yaşlı Adam ve Deniz''inde Santiago''ya bağlı genç çocuğun adı nedir?', 'In Hemingway''s ''The Old Man and the Sea'', what is the name of the boy devoted to Santiago?', '["Manolin","Pablo","Miguel","Diego"]'::jsonb)
  ) v(soru, en_soru, en_secenekler)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Çevrilmeyenler
insert into public.ceviri_atlanan (question_id, dil, neden, kod)
select q.id, 'en', v.neden, 'cevrilemez'
  from (values
  ('2018 yapımı ''Müslüm'' filminde Müslüm Gürses''i canlandıran oyuncu kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('1961''de Eskişehir''de üretilen ilk yerli Türk otomobilinin adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Bayraktar TB2 insansız hava aracını üreten Türk şirketi hangisidir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('TÜBİTAK''ın geliştirdiği yerli Linux tabanlı işletim sisteminin adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Mount & Blade'' oyun serisini geliştiren Türk şirketi hangisidir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Fenerbahçe''nin Şükrü Saracoğlu Stadyumu İstanbul''un hangi ilçesindedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('2008''de NBA''de ''En Çok Gelişme Gösteren Oyuncu'' ödülünü alan Türk basketbolcu kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Eşkıya'' (1996) filminde Şener Şen''in canlandırdığı karakterin adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Hababam Sınıfı'' filmlerinde Halit Akçatepe''nin canlandırdığı karakter kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Yaprak Dökümü'' romanının yazarı kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Minik Serçe'' lakabıyla anılan şarkıcı kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Behzat Ç.'' dizisi hangi şehirde geçer?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Selvi Boylum Al Yazmalım'' filminde Asya karakterini canlandıran oyuncu kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Sabahattin Ali''nin ''Kuyucaklı Yusuf'' romanında Yusuf''un evlendiği kız kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Dede Korkut hikâyelerinde Tepegöz''ü öldüren yiğit kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Yaşar Kemal''in ''İnce Memed'' romanında Memed''in dağa çıkmasına yol açan zalim ağa kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Tutunamayanlar''da intihar eden ve Turgut''un izini sürdüğü arkadaşının adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız')
  ) v(soru, neden)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Karıştırma (TR + EN aynı permütasyon)
drop table if exists pg_temp._parti_karistir;
create temp table _parti_karistir as
select q.id, array_agg(s.idx order by s.rnd) as perm
  from public.questions q
  cross join lateral (
    select (ordinality - 1)::int as idx, random() as rnd
      from jsonb_array_elements(q.secenekler) with ordinality
  ) s
 where q.created_at >= transaction_timestamp()
 group by q.id;

update public.questions q
   set secenekler = (select jsonb_agg(q.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o)),
       dogru_cevap = (array_position(k.perm, q.dogru_cevap::int) - 1)::smallint
  from _parti_karistir k
 where q.id = k.id;

update public.question_translations t
   set secenekler = (select jsonb_agg(t.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o))
  from _parti_karistir k
 where t.question_id = k.id;

drop table if exists pg_temp._parti_karistir;
