-- ============================================================
-- 1044 — soru_parti_kolay_06 (stil: docs/SORU_STIL_PROFILI.md): 198 soru · 2026-10-10
--
-- Kategori: edebiyat 23 · genel_kultur 40 · muzik 20 · sanat 30 · sinema 21 · spor 23 · tarih 3 · teknoloji 38
-- Yerel (kapsam='yerel', ulke='TR'): 13 · zorluk 1–5: 0/137/61/0/0
-- İngilizce çeviri: 185 · çevrilmeyen (ceviri_atlanan, kod 'cevrilemez'): 13
--
-- Kalite (araclar/soru-uretim/api-uret.mjs; üretim claude-opus-5-5, hakem claude-sonnet-5-5):
-- biçim + şık denge (TR/EN), havuzla birebir ve anlamca tekrar (aynı cevap + Jaccard ≥ 0,3),
-- cevap soru metninde değil, soru_kural_isaretleri (ağırlık ≥ 2 yok), Jev şık ipucu testi
-- (soru gizli, doğru şıkka p ≤ 0,75), Jev tek doğru, Claude hakem (doğru şık kesin, yanlış
-- şıklar kesin yanlış, yasak tip yok: genel kavram / tanımlama / okuduğunu anlama / mantıkla
-- bulunur; tek olgu, eskimez, EN aynı sırada ve doğal, zorluk tahmini etiketle uyumlu).
--
-- Sıra: sorular doğru şık 0'da eklenir, çeviriler aynı sırayla yazılır, sonunda YALNIZ
-- bu işlemde eklenen satırların şıkları karıştırılır — TR ve EN AYNI permütasyonla
-- (dogru_cevap indeksi ortak olduğu için şart). `created_at >= transaction_timestamp()`
-- koşulu ZORUNLUDUR; onsuz tüm havuz karışır ve oynanan maçlarda indeks kayar.
-- Üretici: node araclar/soru-uretim/uret-migration-parti.mjs --parti 6 --no 1044 --klasor kolay-06 --ad soru_parti_kolay_06 --api
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori, kapsam, ulke, zorluk) values
('''Bir Yaz Gecesi Rüyası'' için bestelenip düğünlerin simgesi olan ''Düğün Marşı'' kimindir?', '["Mendelssohn","Schumann","Rachmaninov","Çaykovski"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Beethoven''ın ''Neşeye Övgü'' korosunu içeren senfonisi kaçıncısıdır?', '["9.","5.","7.","3."]'::jsonb, 0, 'sanat', 'global', null, 2),
('''The Joy of Painting'' programıyla tanınan kıvırcık saçlı televizyon ressamı kimdir?', '["Bob Ross","Thomas Kinkade","Norman Rockwell","Andrew Wyeth"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Çocuklarını öldüren kadını anlatan ''Medea'' tragedyasının yazarı kimdir?', '["Euripides","Sofokles","Aiskhylos","Aristofanes"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Paskalya Adası''ndaki dev Moai heykelleri bugün hangi ülkenin topraklarındadır?', '["Şili","Peru","Ekvador","Yeni Zelanda"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Broadway müzikali ''Hamilton''ı yazıp bestelen ve başrolünü oynayan sanatçı kimdir?', '["Lin-Manuel Miranda","Andrew Lloyd Webber","Stephen Sondheim","Jason Robert Brown"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Shakespeare''in ''Kral Lear'' oyununda Kral Lear''ın kaç kızı vardır?', '["3","2","4","5"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Keşanlı Ali Destanı'' adlı tiyatro oyununun yazarı kimdir?', '["Haldun Taner","Aziz Nesin","Turgut Özakman","Güngör Dilmen"]'::jsonb, 0, 'sanat', 'yerel', 'TR', 2),
('''Martı'' ve ''Vişne Bahçesi'' oyunlarının yazarı olan Rus yazar kimdir?', '["Çehov","Gogol","Gorki","Puşkin"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Bir Sergiden Tablolar'' adlı piyano süitinin bestecisi kimdir?', '["Mussorgsky","Rimski-Korsakov","Borodin","Rahmaninov"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Akordeona benzeyen bandoneon hangi müzik ve dansın simge çalgısıdır?', '["Tango","Salsa","Flamenko","Samba"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Mezuniyet törenlerinde çalınan ''Pomp and Circumstance'' marşlarının bestecisi kimdir?', '["Edward Elgar","Gustav Holst","Henry Purcell","Benjamin Britten"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Âşık Veysel hangi ilin Şarkışla ilçesinde doğmuştur?', '["Sivas","Yozgat","Kayseri","Tokat"]'::jsonb, 0, 'sanat', 'yerel', 'TR', 2),
('Düğünlerde sıkça çalınan ünlü ''Canon in D'' eserinin bestecisi kimdir?', '["Pachelbel","Telemann","Monteverdi","Corelli"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Dakika Valsi'' ve ''Yağmur Damlası'' prelüdünün bestecisi kimdir?', '["Chopin","Liszt","Schumann","Mendelssohn"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Clair de Lune'' adlı ünlü piyano parçasının bestecisi kimdir?', '["Debussy","Satie","Ravel","Chopin"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Eski Mısır''da geçen ''Aida'' operasının bestecisi kimdir?', '["Verdi","Puccini","Rossini","Bellini"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Önemsiz Olmanın Önemi'' adlı komedinin yazarı kimdir?', '["Oscar Wilde","Noël Coward","Bernard Shaw","Somerset Maugham"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Didgeridoo adlı uzun üflemeli çalgı hangi ülkenin yerli halkına aittir?', '["Avustralya","Yeni Zelanda","Papua Yeni Gine","Fiji"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Altı konçertodan oluşan ''Brandenburg Konçertoları''nın bestecisi kimdir?', '["Bach","Handel","Vivaldi","Telemann"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Goya''nın ''Kara Resimler'' serisinde oğlunu yiyen tanrı hangisidir?', '["Satürn","Jüpiter","Mars","Neptün"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Yayoi Kusama''nın puantiyeli heykellerinde en tanınmış sebze hangisidir?', '["Balkabağı","Salatalık","Patlıcan","Domates"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Kral Oidipus'' tragedyasını yazan antik Yunan oyun yazarı kimdir?', '["Sofokles","Euripides","Aiskhylos","Aristofanes"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Jeff Koons''un 2013''te rekor fiyata satılan turuncu balon heykeli hangi hayvandır?', '["Köpek","Kedi","Ayı","Zürafa"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Duchamp ''L.H.O.O.Q.'' eserinde Mona Lisa kartpostalına ne eklemiştir?', '["Bıyık ve sakal","Gözlük ve şapka","Küpe ve kolye","Pipo ve fular"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Gökdelen Tepesinde Öğle Yemeği'' fotoğrafında işçiler neyin üzerinde oturur?', '["Çelik kiriş","Ahşap iskele","Beton korkuluk","Tuğla duvar"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Nessun Dorma'' aryası hangi operada yer alır?', '["Turandot","Tosca","Aida","Rigoletto"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Shakespeare''in ''Fırtına'' oyununda adada yaşayan büyücü kimdir?', '["Prospero","Oberon","Malvolio","Leontes"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Ünlü ''Dua Eden Eller'' çizimi hangi Alman Rönesans sanatçısına aittir?', '["Albrecht Dürer","Hans Holbein","Lucas Cranach","Matthias Grünewald"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Türk Beşleri''nden ''Yunus Emre Oratoryosu''nun bestecisi kimdir?', '["Adnan Saygun","Cemal Reşit Rey","Ulvi Cemal Erkin","Hasan Ferit Alnar"]'::jsonb, 0, 'sanat', 'yerel', 'TR', 3),
('Sia''nın seslendirdiği ''Titanium'' şarkısı hangi DJ''in şarkısıdır?', '["David Guetta","Calvin Harris","Avicii","Martin Garrix"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Pembe Panter'' filminin ünlü müziğini besteleyen kimdir?', '["Henry Mancini","John Barry","Burt Bacharach","Lalo Schifrin"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Sezen Aksu''ya hayranlarınca verilen lakap hangisidir?', '["Minik Serçe","Küçük Bülbül","Tatlı Kanarya","Sarı Kumru"]'::jsonb, 0, 'muzik', 'yerel', 'TR', 2),
('''Circles'' ve ''Better Now'' şarkılarının sahibi kimdir?', '["Post Malone","Travis Scott","Lil Uzi Vert","Khalid"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Thank U, Next'' ve ''7 Rings'' şarkılarının sahibi kimdir?', '["Ariana Grande","Selena Gomez","Demi Lovato","Camila Cabello"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Stay With Me'' ve ''Too Good at Goodbyes'' şarkılarının sahibi kimdir?', '["Sam Smith","Lewis Capaldi","James Arthur","Tom Odell"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Radioactive'' ve ''Believer'' şarkıları hangi gruba aittir?', '["Imagine Dragons","OneRepublic","Twenty One Pilots","Panic! at the Disco"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Gladyatör'' ve ''Inception'' filmlerinin müziklerini besteleyen kimdir?', '["Hans Zimmer","Howard Shore","James Horner","Danny Elfman"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Siyah giyimi nedeniyle ''Man in Black'' lakabıyla anılan country şarkıcısı kimdir?', '["Johnny Cash","Willie Nelson","Kenny Rogers","Hank Williams"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Moves Like Jagger'' ve ''Sugar'' şarkıları hangi gruba aittir?', '["Maroon 5","Fall Out Boy","The Script","Train"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Your Song'' ve ''Rocket Man'' şarkılarının sahibi olan İngiliz şarkıcı kimdir?', '["Elton John","Billy Joel","Rod Stewart","Phil Collins"]'::jsonb, 0, 'muzik', 'global', null, 2),
('2021''de ''drivers license'' şarkısıyla çıkış yapan şarkıcı kimdir?', '["Olivia Rodrigo","Sabrina Carpenter","Gracie Abrams","Lorde"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''İyi, Kötü ve Çirkin'' filminin ünlü müziğini besteleyen kimdir?', '["Ennio Morricone","Armando Trovajoli","Henry Mancini","Nino Rota"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Watermelon Sugar'' ve ''As It Was'' şarkılarının sahibi kimdir?', '["Harry Styles","Niall Horan","Zayn Malik","Louis Tomlinson"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Rock and Roll Onur Listesi Müzesi hangi ABD kentindedir?', '["Cleveland","Memphis","Nashville","Detroit"]'::jsonb, 0, 'muzik', 'global', null, 3),
('The Beatles''ın ''Here Comes the Sun'' şarkısını yazan üyesi kimdir?', '["George Harrison","John Lennon","Paul McCartney","Ringo Starr"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Paganini Teması Üzerine Rapsodi'' adlı eserin bestecisi kimdir?', '["Rahmaninov","Prokofyev","Şostakoviç","Skryabin"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Fantastik Senfoni'' adlı eserin bestecisi kimdir?', '["Hector Berlioz","Camille Saint-Saëns","Georges Bizet","Gabriel Fauré"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Les Paul adlı ünlü elektro gitar modeli hangi markaya aittir?', '["Gibson","Fender","Gretsch","Ibanez"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Cabaret'' müzikali hangi kentteki bir gece kulübünde geçer?', '["Berlin","Viyana","Paris","Münih"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Claude adlı yapay zekâ asistanını geliştiren şirket hangisidir?', '["Anthropic","OpenAI","DeepMind","Mistral"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Fortnite''ta maç başında oyuncuları adanın üzerine taşıyan araç nedir?', '["Otobüs","Uçak","Helikopter","Zeplin"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Adobe''nin vektör çizim programı hangisidir?', '["Illustrator","Photoshop","Premiere Pro","InDesign"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Minecraft''ta köylülerle ticaret yapmak için kullanılan değerli taş hangisidir?', '["Zümrüt","Elmas","Yakut","Ametist"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('The Last of Us''ta Ellie''ye yol boyunca eşlik eden kaçakçının adı nedir?', '["Joel","Tommy","Bill","Henry"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Super Mario oyunlarında sarı-mor giysili, açgözlü Mario rakibi kimdir?', '["Wario","Toad","Bowser Jr.","Koopa"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın akıllı hoparlörünün adı nedir?', '["HomePod","Echo Dot","Nest Hub","SoundTouch"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın 2014''te satın aldığı kulaklık markası hangisidir?', '["Beats","Bose","JBL","Sennheiser"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Bilgisayar markaları Acer ve ASUS hangi ülkenin şirketleridir?', '["Tayvan","Güney Kore","Japonya","Singapur"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nvidia''nın oyuncular için ürettiği ekran kartı serisinin adı nedir?', '["GeForce","Radeon","Arc","Voodoo"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('God of War serisinin ana kahramanının adı nedir?', '["Kratos","Perseus","Leonidas","Achilles"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın 2001''de tanıttığı, 2019''da Mac''te yerini Music''e bırakan medya yazılımı hangisidir?', '["iTunes","Winamp","RealPlayer","Napster"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın 1984''teki ünlü Super Bowl reklamıyla tanıttığı bilgisayar hangisidir?', '["Macintosh","Lisa","Apple II","Apple III"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Xbox 360 için çıkan, kumandasız hareket algılayan kamera aksesuarı hangisidir?', '["Kinect","PlayStation Move","Wii Remote","EyeToy"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Super Mario oyunlarında Mario''nun sırtına binebildiği yeşil dinozorun adı nedir?', '["Yoshi","Birdo","Wario","Toad"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Fortnite''ta kostüm ve dans almak için kullanılan oyun içi paranın adı nedir?', '["V-Bucks","Robux","Minecoins","Riot Points"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Final Fantasy oyun serisinin yapımcısı olan Japon şirketi hangisidir?', '["Square Enix","Bandai Namco","Koei Tecmo","Konami"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Resident Evil serisinde salgına yol açan virüsü üreten şirketin adı nedir?', '["Umbrella","Aperture","Abstergo","Black Mesa"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın iPhone 5 ile getirip 2023''te USB-C için bıraktığı şarj girişi hangisidir?', '["Lightning","MagSafe","Thunderbolt","FireWire"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Game Boy, 1989''da Kuzey Amerika''da hangi oyunla birlikte paketlenerek satıldı?', '["Tetris","Super Mario Land","Dr. Mario","Pac-Man"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Adobe''nin profesyonel video kurgu programı hangisidir?', '["Premiere","Lightroom","InDesign","Audition"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Hitman oyun serisindeki kel suikastçinin kod adı nedir?', '["Ajan 47","Ajan 13","Ajan 99","Ajan 86"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Windows''ta açık bir belgeyi yazdırmak için kullanılan klavye kısayolu hangisidir?', '["Ctrl+P","Ctrl+Y","Ctrl+D","Ctrl+B"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Cyberpunk 2077'' oyununda Johnny Silverhand karakterini canlandıran ünlü oyuncu kimdir?', '["Keanu Reeves","Mads Mikkelsen","Norman Reedus","Tom Hardy"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Windows''ta Görev Yöneticisi''ni doğrudan açan klavye kısayolu hangisidir?', '["Ctrl+Shift+Esc","Ctrl+Alt+Tab","Alt+Shift+Del","Ctrl+Shift+Home"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Microsoft Office paketindeki veritabanı programı hangisidir?', '["Access","Publisher","OneNote","Visio"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın karma gerçeklik başlığının adı nedir?', '["Vision Pro","Quest Pro","HoloLens","Index"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nintendo DS adındaki "DS" neyin kısaltmasıdır?', '["Dual Screen","Digital System","Direct Sound","Double Speed"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Opera internet tarayıcısı ilk olarak hangi ülkede geliştirilmiştir?', '["Norveç","İsveç","Finlandiya","Danimarka"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Mobil bulmaca oyunu Royal Match''i geliştiren İstanbul merkezli şirket hangisidir?', '["Dream Games","Peak Games","Gram Games","TaleWorlds"]'::jsonb, 0, 'teknoloji', 'yerel', 'TR', 3),
('Honda''nın geliştirdiği ünlü insansı robotun adı nedir?', '["ASIMO","Atlas","Pepper","Sophia"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('YouTube''a yüklenen ilk videoda kurucu Jawed Karim hayvanat bahçesinde hangi hayvanların önündedir?', '["Filler","Zürafalar","Aslanlar","Penguenler"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Oracle''ın kurucu ortaklarından olup uzun yıllar CEO''luğunu yapan kişi kimdir?', '["Larry Ellison","Scott McNealy","Michael Dell","Eric Schmidt"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Windows''ta bir dosyayı Geri Dönüşüm Kutusu''na atmadan kalıcı silen kısayol hangisidir?', '["Shift+Delete","Ctrl+Delete","Alt+Delete","Ctrl+Alt+Delete"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Jeff Bezos''un Amazon için ilk düşündüğü ve kısa süre kullandığı şirket adı nedir?', '["Cadabra","Bookstar","Zappos","Webvan"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Windows 95''in açılış sesini besteleyen müzisyen kimdir?', '["Brian Eno","Hans Zimmer","Vangelis","Jean-Michel Jarre"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Açık artırma sitesi eBay''i 1995''te kuran kişi kimdir?', '["Pierre Omidyar","Reid Hoffman","Peter Thiel","Craig Newmark"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('The Sims oyunlarındaki karakterlerin konuştuğu uydurma dilin adı nedir?', '["Simlish","Klingonca","Dothraki","Na''vi"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Eden Hazard hangi ülkenin milli takımında oynadı?', '["Belçika","Hollanda","Fransa","İsviçre"]'::jsonb, 0, 'spor', 'global', null, 2),
('Old Trafford stadı hangi futbol kulübünün evidir?', '["Manchester United","Manchester City","Nottingham Forest","Tottenham Hotspur"]'::jsonb, 0, 'spor', 'global', null, 2),
('Liverpool''da Salah ile forvet hattı kuran Sadio Mané hangi ülkelidir?', '["Senegal","Gana","Mali","Kamerun"]'::jsonb, 0, 'spor', 'global', null, 2),
('İtalyan futbol kulübü Juventus hangi şehrin takımıdır?', '["Torino","Milano","Cenova","Floransa"]'::jsonb, 0, 'spor', 'global', null, 2),
('NBA takımı Raptors Kanada''nın hangi şehrinde oynar?', '["Toronto","Montreal","Vancouver","Ottawa"]'::jsonb, 0, 'spor', 'global', null, 2),
('1980 Moskova Olimpiyatları''nın maskotu Mişa hangi hayvandı?', '["Ayı","Kurt","Tilki","Kartal"]'::jsonb, 0, 'spor', 'global', null, 2),
('Boks filmi ''Million Dollar Baby''nin yönetmeni kimdir?', '["Clint Eastwood","Martin Scorsese","Ron Howard","Darren Aronofsky"]'::jsonb, 0, 'spor', 'global', null, 2),
('ABD kulübü Inter Miami''nin kurucu ortaklarından eski futbol yıldızı kimdir?', '["David Beckham","Thierry Henry","Kaká","Steven Gerrard"]'::jsonb, 0, 'spor', 'global', null, 2),
('Doping nedeniyle yedi Tour de France unvanı silinen bisikletçi kimdir?', '["Lance Armstrong","Bernard Hinault","Greg LeMond","Chris Froome"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Rocky IV'' filminde Rocky''nin karşılaştığı Sovyet boksörün adı nedir?', '["Ivan Drago","Clubber Lang","Apollo Creed","Tommy Gunn"]'::jsonb, 0, 'spor', 'global', null, 2),
('Maratonda iki saatin altına inen ilk koşucu Eliud Kipchoge hangi ülkelidir?', '["Kenya","Etiyopya","Uganda","Tanzanya"]'::jsonb, 0, 'spor', 'global', null, 2),
('Londra''daki Stamford Bridge stadı hangi kulübün iç saha stadıdır?', '["Chelsea","Arsenal","Fulham","West Ham"]'::jsonb, 0, 'spor', 'global', null, 2),
('Serena Williams''ın da efsane tenisçi olan ablasının adı nedir?', '["Venus","Naomi","Coco","Sloane"]'::jsonb, 0, 'spor', 'global', null, 2),
('Tim Duncan tüm NBA kariyerini hangi takımda geçirdi?', '["San Antonio Spurs","Dallas Mavericks","Denver Nuggets","Portland Trail Blazers"]'::jsonb, 0, 'spor', 'global', null, 2),
('Tom Brady 20 sezon boyunca hangi NFL takımında forma giydi?', '["New England Patriots","Washington Commanders","Pittsburgh Steelers","San Francisco 49ers"]'::jsonb, 0, 'spor', 'global', null, 2),
('Leicester City''yi 2015-16''da sürpriz biçimde lig şampiyonu yapan teknik direktör kimdir?', '["Claudio Ranieri","Brendan Rodgers","Nigel Pearson","Roberto Mancini"]'::jsonb, 0, 'spor', 'global', null, 2),
('Michael Jordan 1994''te beyzbola geçerken hangi MLB kulübüyle sözleşme imzaladı?', '["Chicago White Sox","Chicago Cubs","New York Yankees","Boston Red Sox"]'::jsonb, 0, 'spor', 'global', null, 3),
('''Moneyball'' filminde Brad Pitt hangi beyzbol kulübünün genel menajerini oynar?', '["Oakland Athletics","New York Yankees","Boston Red Sox","Los Angeles Dodgers"]'::jsonb, 0, 'spor', 'global', null, 3),
('Glasgow''un iki dev kulübü Celtic ile Rangers arasındaki derbiye ne ad verilir?', '["Old Firm","El Clásico","Der Klassiker","Merseyside Derby"]'::jsonb, 0, 'spor', 'global', null, 3),
('Thierry Henry Arsenal''de hangi forma numarasını giydi?', '["14","9","10","12"]'::jsonb, 0, 'spor', 'global', null, 3),
('Güney Afrika milli ragbi takımının lakabı nedir?', '["Springboks","Wallabies","Pumas","All Blacks"]'::jsonb, 0, 'spor', 'global', null, 3),
('Dart efsanesi Phil Taylor hangi lakapla anılır?', '["The Power","Snakebite","Jackpot","The Menace"]'::jsonb, 0, 'spor', 'global', null, 3),
('NBA''de ''The Mailman'' (Postacı) lakabıyla tanınan Utah Jazz efsanesi kimdir?', '["Karl Malone","John Stockton","Charles Barkley","Patrick Ewing"]'::jsonb, 0, 'spor', 'global', null, 3),
('Marco Polo, Çin''de hangi Moğol hükümdarının sarayında yıllarca hizmet etmiştir?', '["Kubilay Han","Cengiz Han","Ögedey Han","Hülagü Han"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Müttefiklerin 6 Haziran 1944''teki büyük çıkarması Fransa''nın hangi bölgesinin kıyılarına yapılmıştır?', '["Normandiya","Bretanya","Provence","Picardie"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Kaptan James Cook''un Avustralya''nın doğu kıyısına ulaştığı ilk seferindeki gemisi hangisidir?', '["Endeavour","Bounty","Beagle","Golden Hind"]'::jsonb, 0, 'tarih', 'global', null, 3),
('''Yukarı Bak'' filminde yaşlı Carl''ın hayatını paylaştığı eşinin adı nedir?', '["Ellie","Grace","Alice","Lucy"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Forrest Gump'' filminde Forrest''ın çocukluktan beri âşık olduğu kızın adı nedir?', '["Jenny","Sally","Mary","Annie"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yağmur Adam'' filminde Raymond''un kardeşi Charlie''yi canlandıran oyuncu kimdir?', '["Tom Cruise","Kevin Bacon","Michael J. Fox","Matt Dillon"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Sam Raimi''nin ''Örümcek Adam'' (2002) filminde Mary Jane''i canlandıran oyuncu kimdir?', '["Kirsten Dunst","Scarlett Johansson","Emma Stone","Zendaya"]'::jsonb, 0, 'sinema', 'global', null, 2),
('İlk ''Karayip Korsanları'' filminde Siyah İnci''nin lanetli kaptanı kimdir?', '["Barbossa","Davy Jones","Karasakal","Kaptan Kanca"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Rocky'' filminde Rocky Balboa''nın âşık olduğu pet shop çalışanı kadının adı nedir?', '["Adrian","Linda","Carla","Gloria"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Pixar''ın ''Ters Yüz'' filminde küçük Riley ailesiyle hangi şehre taşınır?', '["San Francisco","Salt Lake City","Los Angeles","Seattle"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Pixar''ın ''Coco'' filminde müzisyen olmayı hayal eden küçük çocuğun adı nedir?', '["Miguel","Diego","Mateo","Carlos"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Hayalet'' (1990) filminin ünlü sahnesinde Molly hangi el sanatıyla uğraşmaktadır?', '["Çömlekçilik","Cam üfleme","Yağlı boya","Dokumacılık"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Madagaskar'' filminde hipokondriyak zürafanın adı nedir?', '["Melman","Mort","Maurice","Julien"]'::jsonb, 0, 'sinema', 'global', null, 2),
('1978 yapımı ''Grease'' filminde Sandy''yi canlandıran oyuncu kimdir?', '["Olivia Newton-John","Stockard Channing","Sarah Jessica Parker","Farrah Fawcett"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Disney''in ''Aladdin'' filminde Prenses Yasemin''in evcil hayvanı Rajah hangi hayvandır?', '["Kaplan","Aslan","Leopar","Panter"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Disney''in ''Bambi'' filminde Çiçek adlı utangaç karakter hangi hayvandır?', '["Kokarca","Sincap","Kirpi","Porsuk"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Esaretin Bedeli'' filminde Andy Dufresne''i canlandıran oyuncu kimdir?', '["Tim Robbins","Ed Harris","Bill Pullman","Kevin Costner"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Gremlins'' filminde Billy''ye hediye edilen sevimli Mogwai''nin adı nedir?', '["Gizmo","Stripe","Mojo","Spike"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Jaws'' filminde Quint, Brody ve Hooper''ın köpekbalığı avına çıktığı teknenin adı nedir?', '["Orca","Pequod","Nautilus","Andrea Gail"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Er Ryan''ı Kurtarmak'' filminde kurtarılmaya çalışılan Er Ryan''ın ön adı nedir?', '["James","John","Michael","Robert"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Oyuncak Hikâyesi 2''de kovboy Woody''nin oyuncak atının adı nedir?', '["Bullseye","Silver","Trigger","Seabiscuit"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Kibar Feyzo'' filminde Feyzo''nun başlık parası yüzünden evlenemediği kızın adı nedir?', '["Gülizar","Zeynep","Hacer","Emine"]'::jsonb, 0, 'sinema', 'yerel', 'TR', 3),
('''Yıldızlararası'' filminde Cooper''ın kızının adı nedir?', '["Murph","Lucy","Donna","Amelia"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Ölü Ozanlar Derneği''nde öğrencilerin masaya çıkıp söylediği ''Ey Kaptan! Kaptanım!'' hangi şairindir?', '["Walt Whitman","Robert Frost","Edgar Allan Poe","Emily Dickinson"]'::jsonb, 0, 'sinema', 'global', null, 3),
('Zeki Müren''in hayranlarınca anıldığı ünlü lakabı nedir?', '["Sanat Güneşi","Sanatın Kralı","Musikinin Şahı","Sahnenin Yıldızı"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('Kovboy Red Kit''in (Lucky Luke) zeki atının adı nedir?', '["Jolly Jumper","Silver Blaze","Black Beauty","Tornado"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Solistliğini Bono''nun yaptığı U2 grubu hangi ülkedendir?', '["İrlanda","İskoçya","Galler","İngiltere"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Friends'' dizisinde Ross Geller''ın mesleği nedir?', '["Paleontolog","Arkeolog","Jeolog","Antropolog"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Şirinler''in yaratıcısı çizer Peyo hangi ülkelidir?', '["Belçika","Fransa","Hollanda","İsviçre"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Doğu Avrupa çorbası borşa kırmızı rengini veren sebze hangisidir?', '["Pancar","Lahana","Havuç","Patates"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Siyah bira Guinness hangi ülkenin markasıdır?', '["İrlanda","İskoçya","Belçika","Galler"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Yaşar Kemal''in ''İnce Memed'' romanı hangi yörede geçer?', '["Çukurova","Trakya","Kapadokya","Ege"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('''Ezel'' dizisinde Ezel Bayraktar''ı hangi oyuncu canlandırmıştır?', '["Kenan İmirzalıoğlu","Kıvanç Tatlıtuğ","Mehmet Akif Alakurt","Engin Akyürek"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('Hitchcock''un ''Sapık'' (Psycho) filmindeki motel sahibi Norman''ın soyadı nedir?', '["Bates","Torrance","Bateman","Krueger"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Romalılar Yunan tanrılarının kralı Zeus''a hangi adla taparlardı?', '["Jüpiter","Vulcanus","Merkür","Neptün"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''La Casa de Papel''de soyguncuların taktığı maske hangi ressamın yüzünü taşır?', '["Salvador Dalí","Pablo Picasso","Francisco Goya","Joan Miró"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Harry Potter'' serisinde Harry''nin vaftiz babası kimdir?', '["Sirius Black","Remus Lupin","Severus Snape","Rubeus Hagrid"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Yunan mitolojisinde Girit labirentindeki Minotauros''u öldüren kahraman kimdir?', '["Theseus","Perseus","Herakles","Iason"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Leyla ile Mecnun'' dizisinde Mecnun''u hangi oyuncu canlandırmıştır?', '["Ali Atay","Serkan Keskin","Kıvanç Tatlıtuğ","Engin Altan Düzyatan"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('''The Big Bang Theory''de Sheldon kapıyı çalarken hangi ismi üç kez söyler?', '["Penny","Amy","Leonard","Bernadette"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Aşk-ı Memnu'' dizisinde Bihter karakterini hangi oyuncu canlandırmıştır?', '["Beren Saat","Tuba Büyüküstün","Songül Öden","Nurgül Yeşilçay"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('Yunan mitolojisinde çocuklarını yutan Zeus''un babası kimdir?', '["Kronos","Uranos","Atlas","Hyperion"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Rapçi Eminem''in şarkılarında kullandığı ünlü alter egosunun adı nedir?', '["Slim Shady","Sasha Fierce","Ziggy Stardust","Chris Gaines"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Yunan mitolojisinde Medusa''nın kesilen boynundan doğan kanatlı atın adı nedir?', '["Pegasus","Sleipnir","Arion","Bucephalus"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Homeros''un ''Odysseia''sında Odysseus''un dönmeye çalıştığı yurdu hangi adadır?', '["İthaka","Girit","Rodos","Sakız"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Harry Potter'' serisinde Ron Weasley''nin evcil faresinin adı nedir?', '["Scabbers","Crookshanks","Trevor","Nagini"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Truva Savaşı''nda tahta at hilesini düşünen Yunan kahramanı kimdir?', '["Odysseus","Akhilleus","Agamemnon","Menelaos"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Gurur ve Önyargı''da Elizabeth Bennet sonunda kiminle evlenir?', '["Mr. Darcy","Mr. Bingley","Mr. Wickham","Mr. Collins"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Pixar''ın ''Ratatouille'' filminde şef olmak isteyen farenin adı nedir?', '["Remy","Emile","Django","Linguini"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Shakespeare''in trajedisinde Othello hangi şehrin hizmetindeki bir generaldir?', '["Venedik","Floransa","Cenova","Napoli"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Asteriks'' çizgi romanlarında Oburiks sırtında sürekli ne taşır?', '["Menhir","Fıçı","Kalkan","Kütük"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Truvalı Paris''in kaçırdığı Güzel Helen''in kocası olan Sparta kralı kimdir?', '["Menelaos","Agamemnon","Priamos","Akhilleus"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Dickens''ın ''Büyük Umutlar'' romanının yetim kahramanının lakabı nedir?', '["Pip","Oliver","Tiny Tim","Copperfield"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Game of Thrones''ta Arya Stark''ın küçük kılıcının adı nedir?', '["Needle","Longclaw","Ice","Oathkeeper"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Sahibini yıllarca bekleyen köpek Hachikō''nun heykeli Tokyo''nun hangi istasyonundadır?', '["Shibuya","Shinjuku","Ueno","Ikebukuro"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Wonder Woman''ın doğup büyüdüğü Amazon adasının adı nedir?', '["Themyscira","Atlantis","Apokolips","Wakanda"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Star Trek''te Bay Spock''ın babasının halkının yaşadığı gezegenin adı nedir?', '["Vulkan","Romulus","Kronos","Bajor"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Harry Potter'' serisinde Dumbledore''un anka kuşunun adı nedir?', '["Fawkes","Hedwig","Buckbeak","Errol"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Toblerone çikolatasının ambalajında hangi dağ yer alır?', '["Matterhorn","Mont Blanc","Eiger","Jungfrau"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Rocky'' filminde Rocky''nin koşarak çıktığı ünlü müze merdivenleri hangi şehirdedir?', '["Philadelphia","Indianapolis","Pittsburgh","Baltimore"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Ziggy Stardust'' hangi şarkıcının sahne kişiliğidir?', '["David Bowie","Elton John","Freddie Mercury","Lou Reed"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Baba'' filminde Corleone ailesinin avukatı ve danışmanı kimdir?', '["Tom Hagen","Luca Brasi","Sal Tessio","Peter Clemenza"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Basketbolu 1891''de icat eden beden eğitimi öğretmeni kimdir?', '["James Naismith","Walter Camp","William Morgan","Abner Doubleday"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Doctor Who''da Doktor''un polis kulübesi görünümlü zaman makinesinin adı nedir?', '["TARDIS","Serenity","Galactica","Nostromo"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Tom Sawyer, arkadaşlarını kandırıp ceza olarak kendisine verilen neyi badanalatır?', '["Çit","Ahır","Kayık","Kulübe"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Kral Arthur efsanesinde Kraliçe Guinevere ile yasak aşk yaşayan şövalye kimdir?', '["Lancelot","Gawain","Percival","Galahad"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''İlyada''da Akhilleus''un Patroklos''un intikamını almak için öldürdüğü Truvalı kahraman kimdir?', '["Hektor","Paris","Aeneas","Priamos"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Peter Tavşan'' karakterini yaratan İngiliz yazar kimdir?', '["Beatrix Potter","Enid Blyton","Roald Dahl","A.A. Milne"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Andersen''in ''Küçük Deniz Kızı'', insan bacakları karşılığında cadıya neyini verir?', '["Sesini","Saçlarını","Gözlerini","Kalbini"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Kürk Mantolu Madonna''da Berlin''de Maria Puder''e âşık olan kahraman kimdir?', '["Raif Efendi","Hamdi Bey","Selim Işık","Ömer Bey"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('Dede Korkut''ta Basat''ın, kardeşi Kıyan Selçuk''un öcünü almak için öldürdüğü dev kimdir?', '["Tepegöz","Karakoncolos","Şahmeran","Albastı"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('''Odysseia''da Odysseus''un dönüşünü yıllarca talipleri oyalayarak bekleyen karısı kimdir?', '["Penelope","Helena","Andromakhe","Klytaimnestra"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Alice Harikalar Diyarında''da Mart Tavşanı ile çay partisi veren deli karakter kimdir?', '["Şapkacı","Marangoz","Kunduracı","Saatçi"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Kipling''in ''Orman Kitabı''nda Mowgli''nin baş düşmanı Shere Khan hangi hayvandır?', '["Kaplan","Aslan","Leopar","Timsah"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Dickens''ın ''Noel Şarkısı''nda Bob Cratchit''in hasta küçük oğlunun adı nedir?', '["Tim","Sam","Ben","Joe"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Odysseia''da Odysseus, Truva''dan sonra hangi adadaki krallığına dönmeye çalışır?', '["İthaka","Girit","Rodos","Sakız"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Lolita'' romanının yazarı kimdir?', '["Nabokov","Updike","Roth","Bellow"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Matilda'' ve ''Koca Sevimli Dev'' kitaplarının yazarı kimdir?', '["Roald Dahl","Enid Blyton","Beatrix Potter","Michael Ende"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Verne''in ''Seksen Günde Devrialem'' romanında dünyayı dolaşmak için iddiaya giren beyefendi kimdir?', '["Phileas Fogg","Kaptan Nemo","Michel Strogoff","Ned Land"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Orwell''in ''1984'' romanının baş kahramanı kimdir?', '["Winston Smith","Bernard Marx","Guy Montag","John Savage"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Pi''nin Yaşamı'' romanında Pi ile aynı filikada kalan kaplanın adı nedir?', '["Richard Parker","Henry Morgan","William Bligh","Edward Teach"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Otomatik Portakal'' romanının yazarı kimdir?', '["Anthony Burgess","Kingsley Amis","William Golding","Martin Amis"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Albert Camus''nün ''Veba'' romanı hangi Cezayir şehrinde geçer?', '["Oran","Konstantin","Annaba","Tlemsen"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Hamlet''te Hamlet''in babasını zehirleyip tahta geçen amcasının adı nedir?', '["Claudius","Polonius","Laertes","Horatio"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Bülbülü Öldürmek'' romanını anlatan Atticus Finch''in kızının lakabı nedir?', '["Scout","Jem","Dill","Boo"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Frank Herbert''ın ''Dune'' romanının geçtiği çöl gezegeninin adı nedir?', '["Arrakis","Caladan","Trantor","Solaris"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Sherlock Holmes''u alt ettiği için Holmes''un ''o kadın'' diye andığı karakter kimdir?', '["Irene Adler","Mary Morstan","Violet Hunter","Martha Hudson"]'::jsonb, 0, 'edebiyat', 'global', null, 3)
on conflict (soru) do nothing;

-- ---------------------------------------------------- İngilizce çeviri
insert into public.question_translations (question_id, dil, soru, secenekler)
select q.id, 'en', v.en_soru, v.en_secenekler
  from (values
  ('''Bir Yaz Gecesi Rüyası'' için bestelenip düğünlerin simgesi olan ''Düğün Marşı'' kimindir?', 'Who wrote the famous ''Wedding March'' from the music for ''A Midsummer Night''s Dream''?', '["Mendelssohn","Schumann","Rachmaninoff","Tchaikovsky"]'::jsonb),
  ('Beethoven''ın ''Neşeye Övgü'' korosunu içeren senfonisi kaçıncısıdır?', 'Which Beethoven symphony features the ''Ode to Joy'' choral finale?', '["9th","5th","7th","3rd"]'::jsonb),
  ('''The Joy of Painting'' programıyla tanınan kıvırcık saçlı televizyon ressamı kimdir?', 'Which curly-haired TV painter hosted ''The Joy of Painting''?', '["Bob Ross","Thomas Kinkade","Norman Rockwell","Andrew Wyeth"]'::jsonb),
  ('Çocuklarını öldüren kadını anlatan ''Medea'' tragedyasının yazarı kimdir?', 'Which ancient Greek playwright wrote the tragedy ''Medea''?', '["Euripides","Sophocles","Aeschylus","Aristophanes"]'::jsonb),
  ('Paskalya Adası''ndaki dev Moai heykelleri bugün hangi ülkenin topraklarındadır?', 'The giant Moai statues of Easter Island are in which country''s territory?', '["Chile","Peru","Ecuador","New Zealand"]'::jsonb),
  ('Broadway müzikali ''Hamilton''ı yazıp bestelen ve başrolünü oynayan sanatçı kimdir?', 'Who wrote the Broadway musical ''Hamilton'' and starred in the title role?', '["Lin-Manuel Miranda","Andrew Lloyd Webber","Stephen Sondheim","Jason Robert Brown"]'::jsonb),
  ('Shakespeare''in ''Kral Lear'' oyununda Kral Lear''ın kaç kızı vardır?', 'In Shakespeare''s ''King Lear'', how many daughters does the king have?', '["3","2","4","5"]'::jsonb),
  ('''Martı'' ve ''Vişne Bahçesi'' oyunlarının yazarı olan Rus yazar kimdir?', 'Which Russian writer wrote the plays ''The Seagull'' and ''The Cherry Orchard''?', '["Chekhov","Gogol","Gorky","Pushkin"]'::jsonb),
  ('''Bir Sergiden Tablolar'' adlı piyano süitinin bestecisi kimdir?', 'Who composed the piano suite ''Pictures at an Exhibition''?', '["Mussorgsky","Rimsky-Korsakov","Borodin","Rachmaninoff"]'::jsonb),
  ('Akordeona benzeyen bandoneon hangi müzik ve dansın simge çalgısıdır?', 'The bandoneon, a cousin of the accordion, is the signature instrument of which music and dance?', '["Tango","Salsa","Flamenco","Samba"]'::jsonb),
  ('Mezuniyet törenlerinde çalınan ''Pomp and Circumstance'' marşlarının bestecisi kimdir?', 'Who composed the ''Pomp and Circumstance'' marches heard at graduation ceremonies?', '["Edward Elgar","Gustav Holst","Henry Purcell","Benjamin Britten"]'::jsonb),
  ('Düğünlerde sıkça çalınan ünlü ''Canon in D'' eserinin bestecisi kimdir?', 'Who composed the famous ''Canon in D'', a wedding favourite?', '["Pachelbel","Telemann","Monteverdi","Corelli"]'::jsonb),
  ('''Dakika Valsi'' ve ''Yağmur Damlası'' prelüdünün bestecisi kimdir?', 'Who composed the ''Minute Waltz'' and the ''Raindrop'' Prelude?', '["Chopin","Liszt","Schumann","Mendelssohn"]'::jsonb),
  ('''Clair de Lune'' adlı ünlü piyano parçasının bestecisi kimdir?', 'Who composed the famous piano piece ''Clair de Lune''?', '["Debussy","Satie","Ravel","Chopin"]'::jsonb),
  ('Eski Mısır''da geçen ''Aida'' operasının bestecisi kimdir?', 'Which composer wrote the opera ''Aida'', set in ancient Egypt?', '["Verdi","Puccini","Rossini","Bellini"]'::jsonb),
  ('''Önemsiz Olmanın Önemi'' adlı komedinin yazarı kimdir?', 'Who wrote the comedy ''The Importance of Being Earnest''?', '["Oscar Wilde","Noel Coward","Bernard Shaw","Somerset Maugham"]'::jsonb),
  ('Didgeridoo adlı uzun üflemeli çalgı hangi ülkenin yerli halkına aittir?', 'The didgeridoo is a traditional wind instrument of the indigenous people of which country?', '["Australia","New Zealand","Papua New Guinea","Fiji"]'::jsonb),
  ('Altı konçertodan oluşan ''Brandenburg Konçertoları''nın bestecisi kimdir?', 'Who composed the six ''Brandenburg Concertos''?', '["Bach","Handel","Vivaldi","Telemann"]'::jsonb),
  ('Goya''nın ''Kara Resimler'' serisinde oğlunu yiyen tanrı hangisidir?', 'In one of Goya''s ''Black Paintings'', which god is shown devouring his son?', '["Saturn","Jupiter","Mars","Neptune"]'::jsonb),
  ('Yayoi Kusama''nın puantiyeli heykellerinde en tanınmış sebze hangisidir?', 'Which vegetable is the subject of Yayoi Kusama''s iconic polka-dot sculptures?', '["Pumpkin","Cucumber","Eggplant","Tomato"]'::jsonb),
  ('''Kral Oidipus'' tragedyasını yazan antik Yunan oyun yazarı kimdir?', 'Which ancient Greek playwright wrote ''Oedipus Rex''?', '["Sophocles","Euripides","Aeschylus","Aristophanes"]'::jsonb),
  ('Jeff Koons''un 2013''te rekor fiyata satılan turuncu balon heykeli hangi hayvandır?', 'Jeff Koons''s orange balloon sculpture that sold for a record price in 2013 depicts which animal?', '["Dog","Cat","Bear","Giraffe"]'::jsonb),
  ('Duchamp ''L.H.O.O.Q.'' eserinde Mona Lisa kartpostalına ne eklemiştir?', 'In his work ''L.H.O.O.Q.'', what did Duchamp draw onto a postcard of the Mona Lisa?', '["Mustache and beard","Glasses and a hat","Earrings and a necklace","Pipe and a scarf"]'::jsonb),
  ('''Gökdelen Tepesinde Öğle Yemeği'' fotoğrafında işçiler neyin üzerinde oturur?', 'In the photo ''Lunch atop a Skyscraper'', what are the workers sitting on?', '["A steel beam","Wooden scaffolding","A concrete ledge","A brick wall"]'::jsonb),
  ('''Nessun Dorma'' aryası hangi operada yer alır?', 'The aria ''Nessun Dorma'' comes from which opera?', '["Turandot","Tosca","Aida","Rigoletto"]'::jsonb),
  ('Shakespeare''in ''Fırtına'' oyununda adada yaşayan büyücü kimdir?', 'Who is the island-dwelling sorcerer in Shakespeare''s ''The Tempest''?', '["Prospero","Oberon","Malvolio","Leontes"]'::jsonb),
  ('Ünlü ''Dua Eden Eller'' çizimi hangi Alman Rönesans sanatçısına aittir?', 'The famous drawing ''Praying Hands'' is by which German Renaissance artist?', '["Albrecht Durer","Hans Holbein","Lucas Cranach","Matthias Grunewald"]'::jsonb),
  ('Sia''nın seslendirdiği ''Titanium'' şarkısı hangi DJ''in şarkısıdır?', 'Sia sang the vocals on ''Titanium'', a track by which DJ?', '["David Guetta","Calvin Harris","Avicii","Martin Garrix"]'::jsonb),
  ('''Pembe Panter'' filminin ünlü müziğini besteleyen kimdir?', 'Who composed the famous theme from ''The Pink Panther''?', '["Henry Mancini","John Barry","Burt Bacharach","Lalo Schifrin"]'::jsonb),
  ('''Circles'' ve ''Better Now'' şarkılarının sahibi kimdir?', 'Who sings ''Circles'' and ''Better Now''?', '["Post Malone","Travis Scott","Lil Uzi Vert","Khalid"]'::jsonb),
  ('''Thank U, Next'' ve ''7 Rings'' şarkılarının sahibi kimdir?', 'Who sings ''Thank U, Next'' and ''7 Rings''?', '["Ariana Grande","Selena Gomez","Demi Lovato","Camila Cabello"]'::jsonb),
  ('''Stay With Me'' ve ''Too Good at Goodbyes'' şarkılarının sahibi kimdir?', 'Who sings ''Stay With Me'' and ''Too Good at Goodbyes''?', '["Sam Smith","Lewis Capaldi","James Arthur","Tom Odell"]'::jsonb),
  ('''Radioactive'' ve ''Believer'' şarkıları hangi gruba aittir?', 'Which band is behind ''Radioactive'' and ''Believer''?', '["Imagine Dragons","OneRepublic","Twenty One Pilots","Panic! at the Disco"]'::jsonb),
  ('''Gladyatör'' ve ''Inception'' filmlerinin müziklerini besteleyen kimdir?', 'Which composer scored both ''Gladiator'' and ''Inception''?', '["Hans Zimmer","Howard Shore","James Horner","Danny Elfman"]'::jsonb),
  ('Siyah giyimi nedeniyle ''Man in Black'' lakabıyla anılan country şarkıcısı kimdir?', 'Which country singer was nicknamed ''The Man in Black''?', '["Johnny Cash","Willie Nelson","Kenny Rogers","Hank Williams"]'::jsonb),
  ('''Moves Like Jagger'' ve ''Sugar'' şarkıları hangi gruba aittir?', 'Which band had hits with ''Moves Like Jagger'' and ''Sugar''?', '["Maroon 5","Fall Out Boy","The Script","Train"]'::jsonb),
  ('''Your Song'' ve ''Rocket Man'' şarkılarının sahibi olan İngiliz şarkıcı kimdir?', 'Which British singer is behind the songs ''Your Song'' and ''Rocket Man''?', '["Elton John","Billy Joel","Rod Stewart","Phil Collins"]'::jsonb),
  ('2021''de ''drivers license'' şarkısıyla çıkış yapan şarkıcı kimdir?', 'Which singer broke through in 2021 with ''drivers license''?', '["Olivia Rodrigo","Sabrina Carpenter","Gracie Abrams","Lorde"]'::jsonb),
  ('''İyi, Kötü ve Çirkin'' filminin ünlü müziğini besteleyen kimdir?', 'Who composed the iconic score for ''The Good, the Bad and the Ugly''?', '["Ennio Morricone","Armando Trovajoli","Henry Mancini","Nino Rota"]'::jsonb),
  ('''Watermelon Sugar'' ve ''As It Was'' şarkılarının sahibi kimdir?', 'Who sings ''Watermelon Sugar'' and ''As It Was''?', '["Harry Styles","Niall Horan","Zayn Malik","Louis Tomlinson"]'::jsonb),
  ('Rock and Roll Onur Listesi Müzesi hangi ABD kentindedir?', 'In which US city is the Rock and Roll Hall of Fame museum located?', '["Cleveland","Memphis","Nashville","Detroit"]'::jsonb),
  ('The Beatles''ın ''Here Comes the Sun'' şarkısını yazan üyesi kimdir?', 'Which Beatle wrote ''Here Comes the Sun''?', '["George Harrison","John Lennon","Paul McCartney","Ringo Starr"]'::jsonb),
  ('''Paganini Teması Üzerine Rapsodi'' adlı eserin bestecisi kimdir?', 'Who composed the ''Rhapsody on a Theme of Paganini''?', '["Rachmaninoff","Prokofiev","Shostakovich","Scriabin"]'::jsonb),
  ('''Fantastik Senfoni'' adlı eserin bestecisi kimdir?', 'Who composed the ''Symphonie fantastique''?', '["Hector Berlioz","Camille Saint-Saens","Georges Bizet","Gabriel Faure"]'::jsonb),
  ('Les Paul adlı ünlü elektro gitar modeli hangi markaya aittir?', 'Which brand makes the famous Les Paul electric guitar?', '["Gibson","Fender","Gretsch","Ibanez"]'::jsonb),
  ('''Cabaret'' müzikali hangi kentteki bir gece kulübünde geçer?', 'The musical ''Cabaret'' is set in a nightclub in which city?', '["Berlin","Vienna","Paris","Munich"]'::jsonb),
  ('Claude adlı yapay zekâ asistanını geliştiren şirket hangisidir?', 'Which company develops the AI assistant Claude?', '["Anthropic","OpenAI","DeepMind","Mistral"]'::jsonb),
  ('Fortnite''ta maç başında oyuncuları adanın üzerine taşıyan araç nedir?', 'In Fortnite, what vehicle carries players over the island at the start of a match?', '["A bus","A plane","A helicopter","A blimp"]'::jsonb),
  ('Adobe''nin vektör çizim programı hangisidir?', 'Which is Adobe''s vector drawing program?', '["Illustrator","Photoshop","Premiere Pro","InDesign"]'::jsonb),
  ('Minecraft''ta köylülerle ticaret yapmak için kullanılan değerli taş hangisidir?', 'Which gem is used as currency when trading with villagers in Minecraft?', '["Emerald","Diamond","Ruby","Amethyst"]'::jsonb),
  ('The Last of Us''ta Ellie''ye yol boyunca eşlik eden kaçakçının adı nedir?', 'In The Last of Us, what is the name of the smuggler who escorts Ellie?', '["Joel","Tommy","Bill","Henry"]'::jsonb),
  ('Super Mario oyunlarında sarı-mor giysili, açgözlü Mario rakibi kimdir?', 'In the Super Mario games, who is Mario''s greedy rival dressed in yellow and purple?', '["Wario","Toad","Bowser Jr.","Koopa"]'::jsonb),
  ('Apple''ın akıllı hoparlörünün adı nedir?', 'What is the name of Apple''s smart speaker?', '["HomePod","Echo Dot","Nest Hub","SoundTouch"]'::jsonb),
  ('Apple''ın 2014''te satın aldığı kulaklık markası hangisidir?', 'Which headphone brand did Apple acquire in 2014?', '["Beats","Bose","JBL","Sennheiser"]'::jsonb),
  ('Bilgisayar markaları Acer ve ASUS hangi ülkenin şirketleridir?', 'Computer brands Acer and ASUS are companies from which country?', '["Taiwan","South Korea","Japan","Singapore"]'::jsonb),
  ('Nvidia''nın oyuncular için ürettiği ekran kartı serisinin adı nedir?', 'What is the name of Nvidia''s line of gaming graphics cards?', '["GeForce","Radeon","Arc","Voodoo"]'::jsonb),
  ('God of War serisinin ana kahramanının adı nedir?', 'What is the name of the main hero of the God of War series?', '["Kratos","Perseus","Leonidas","Achilles"]'::jsonb),
  ('Apple''ın 2001''de tanıttığı, 2019''da Mac''te yerini Music''e bırakan medya yazılımı hangisidir?', 'Which Apple media software, launched in 2001, was replaced on the Mac by the Music app in 2019?', '["iTunes","Winamp","RealPlayer","Napster"]'::jsonb),
  ('Apple''ın 1984''teki ünlü Super Bowl reklamıyla tanıttığı bilgisayar hangisidir?', 'Which computer did Apple introduce with its famous 1984 Super Bowl commercial?', '["Macintosh","Lisa","Apple II","Apple III"]'::jsonb),
  ('Xbox 360 için çıkan, kumandasız hareket algılayan kamera aksesuarı hangisidir?', 'What was the name of the controller-free motion-sensing camera released for the Xbox 360?', '["Kinect","PlayStation Move","Wii Remote","EyeToy"]'::jsonb),
  ('Super Mario oyunlarında Mario''nun sırtına binebildiği yeşil dinozorun adı nedir?', 'In the Super Mario games, what is the name of the green dinosaur that Mario rides?', '["Yoshi","Birdo","Wario","Toad"]'::jsonb),
  ('Fortnite''ta kostüm ve dans almak için kullanılan oyun içi paranın adı nedir?', 'What is the in-game currency used to buy skins and emotes in Fortnite?', '["V-Bucks","Robux","Minecoins","Riot Points"]'::jsonb),
  ('Final Fantasy oyun serisinin yapımcısı olan Japon şirketi hangisidir?', 'Which Japanese company is behind the Final Fantasy series?', '["Square Enix","Bandai Namco","Koei Tecmo","Konami"]'::jsonb),
  ('Resident Evil serisinde salgına yol açan virüsü üreten şirketin adı nedir?', 'In the Resident Evil series, which corporation created the virus behind the outbreak?', '["Umbrella","Aperture","Abstergo","Black Mesa"]'::jsonb),
  ('Apple''ın iPhone 5 ile getirip 2023''te USB-C için bıraktığı şarj girişi hangisidir?', 'Which charging port did Apple introduce with the iPhone 5 and drop for USB-C in 2023?', '["Lightning","MagSafe","Thunderbolt","FireWire"]'::jsonb),
  ('Game Boy, 1989''da Kuzey Amerika''da hangi oyunla birlikte paketlenerek satıldı?', 'Which game came bundled with the Game Boy at its 1989 North American launch?', '["Tetris","Super Mario Land","Dr. Mario","Pac-Man"]'::jsonb),
  ('Adobe''nin profesyonel video kurgu programı hangisidir?', 'Which Adobe program is used for professional video editing?', '["Premiere","Lightroom","InDesign","Audition"]'::jsonb),
  ('Hitman oyun serisindeki kel suikastçinin kod adı nedir?', 'What is the code name of the bald assassin in the Hitman games?', '["Agent 47","Agent 13","Agent 99","Agent 86"]'::jsonb),
  ('Windows''ta açık bir belgeyi yazdırmak için kullanılan klavye kısayolu hangisidir?', 'Which keyboard shortcut prints the open document in Windows?', '["Ctrl+P","Ctrl+Y","Ctrl+D","Ctrl+B"]'::jsonb),
  ('''Cyberpunk 2077'' oyununda Johnny Silverhand karakterini canlandıran ünlü oyuncu kimdir?', 'Which famous actor plays Johnny Silverhand in Cyberpunk 2077?', '["Keanu Reeves","Mads Mikkelsen","Norman Reedus","Tom Hardy"]'::jsonb),
  ('Windows''ta Görev Yöneticisi''ni doğrudan açan klavye kısayolu hangisidir?', 'Which keyboard shortcut opens Task Manager directly in Windows?', '["Ctrl+Shift+Esc","Ctrl+Alt+Tab","Alt+Shift+Del","Ctrl+Shift+Home"]'::jsonb),
  ('Microsoft Office paketindeki veritabanı programı hangisidir?', 'Which program is the database application in the Microsoft Office suite?', '["Access","Publisher","OneNote","Visio"]'::jsonb),
  ('Apple''ın karma gerçeklik başlığının adı nedir?', 'What is the name of Apple''s mixed reality headset?', '["Vision Pro","Quest Pro","HoloLens","Index"]'::jsonb),
  ('Nintendo DS adındaki "DS" neyin kısaltmasıdır?', 'What does the DS in Nintendo DS stand for?', '["Dual Screen","Digital System","Direct Sound","Double Speed"]'::jsonb),
  ('Opera internet tarayıcısı ilk olarak hangi ülkede geliştirilmiştir?', 'In which country was the Opera web browser originally developed?', '["Norway","Sweden","Finland","Denmark"]'::jsonb),
  ('Honda''nın geliştirdiği ünlü insansı robotun adı nedir?', 'What is the name of Honda''s famous humanoid robot?', '["ASIMO","Atlas","Pepper","Sophia"]'::jsonb),
  ('YouTube''a yüklenen ilk videoda kurucu Jawed Karim hayvanat bahçesinde hangi hayvanların önündedir?', 'In the first video ever uploaded to YouTube, co-founder Jawed Karim stands in front of which zoo animals?', '["Elephants","Giraffes","Lions","Penguins"]'::jsonb),
  ('Oracle''ın kurucu ortaklarından olup uzun yıllar CEO''luğunu yapan kişi kimdir?', 'Who co-founded Oracle and served as its CEO for decades?', '["Larry Ellison","Scott McNealy","Michael Dell","Eric Schmidt"]'::jsonb),
  ('Windows''ta bir dosyayı Geri Dönüşüm Kutusu''na atmadan kalıcı silen kısayol hangisidir?', 'In Windows, which shortcut deletes a file permanently, skipping the Recycle Bin?', '["Shift+Delete","Ctrl+Delete","Alt+Delete","Ctrl+Alt+Delete"]'::jsonb),
  ('Jeff Bezos''un Amazon için ilk düşündüğü ve kısa süre kullandığı şirket adı nedir?', 'What was the original name Jeff Bezos briefly used for Amazon?', '["Cadabra","Bookstar","Zappos","Webvan"]'::jsonb),
  ('Windows 95''in açılış sesini besteleyen müzisyen kimdir?', 'Which musician composed the Windows 95 startup sound?', '["Brian Eno","Hans Zimmer","Vangelis","Jean-Michel Jarre"]'::jsonb),
  ('Açık artırma sitesi eBay''i 1995''te kuran kişi kimdir?', 'Who founded the auction site eBay in 1995?', '["Pierre Omidyar","Reid Hoffman","Peter Thiel","Craig Newmark"]'::jsonb),
  ('The Sims oyunlarındaki karakterlerin konuştuğu uydurma dilin adı nedir?', 'What is the name of the made-up language spoken by characters in The Sims?', '["Simlish","Klingon","Dothraki","Na''vi"]'::jsonb),
  ('Eden Hazard hangi ülkenin milli takımında oynadı?', 'Eden Hazard played international football for which country?', '["Belgium","Netherlands","France","Switzerland"]'::jsonb),
  ('Old Trafford stadı hangi futbol kulübünün evidir?', 'Old Trafford is the home ground of which football club?', '["Manchester United","Manchester City","Nottingham Forest","Tottenham Hotspur"]'::jsonb),
  ('Liverpool''da Salah ile forvet hattı kuran Sadio Mané hangi ülkelidir?', 'Sadio Mane, who formed a deadly attack with Salah at Liverpool, is from which country?', '["Senegal","Ghana","Mali","Cameroon"]'::jsonb),
  ('İtalyan futbol kulübü Juventus hangi şehrin takımıdır?', 'Italian football club Juventus is based in which city?', '["Turin","Milan","Genoa","Florence"]'::jsonb),
  ('NBA takımı Raptors Kanada''nın hangi şehrinde oynar?', 'The NBA''s Raptors play in which Canadian city?', '["Toronto","Montreal","Vancouver","Ottawa"]'::jsonb),
  ('1980 Moskova Olimpiyatları''nın maskotu Mişa hangi hayvandı?', 'Misha, the mascot of the 1980 Moscow Olympics, was what kind of animal?', '["Bear","Wolf","Fox","Eagle"]'::jsonb),
  ('Boks filmi ''Million Dollar Baby''nin yönetmeni kimdir?', 'Who directed the boxing film ''Million Dollar Baby''?', '["Clint Eastwood","Martin Scorsese","Ron Howard","Darren Aronofsky"]'::jsonb),
  ('ABD kulübü Inter Miami''nin kurucu ortaklarından eski futbol yıldızı kimdir?', 'Which former football star is a co-founder of MLS club Inter Miami?', '["David Beckham","Thierry Henry","Kaka","Steven Gerrard"]'::jsonb),
  ('Doping nedeniyle yedi Tour de France unvanı silinen bisikletçi kimdir?', 'Which cyclist was stripped of seven Tour de France titles for doping?', '["Lance Armstrong","Bernard Hinault","Greg LeMond","Chris Froome"]'::jsonb),
  ('''Rocky IV'' filminde Rocky''nin karşılaştığı Sovyet boksörün adı nedir?', 'What is the name of Rocky''s Soviet opponent in ''Rocky IV''?', '["Ivan Drago","Clubber Lang","Apollo Creed","Tommy Gunn"]'::jsonb),
  ('Maratonda iki saatin altına inen ilk koşucu Eliud Kipchoge hangi ülkelidir?', 'Eliud Kipchoge, the first man to run a marathon in under two hours, is from which country?', '["Kenya","Ethiopia","Uganda","Tanzania"]'::jsonb),
  ('Londra''daki Stamford Bridge stadı hangi kulübün iç saha stadıdır?', 'Which London club plays its home games at Stamford Bridge?', '["Chelsea","Arsenal","Fulham","West Ham"]'::jsonb),
  ('Serena Williams''ın da efsane tenisçi olan ablasının adı nedir?', 'What is the first name of Serena Williams''s older sister, also a tennis great?', '["Venus","Naomi","Coco","Sloane"]'::jsonb),
  ('Tim Duncan tüm NBA kariyerini hangi takımda geçirdi?', 'Tim Duncan spent his entire NBA career with which team?', '["San Antonio Spurs","Dallas Mavericks","Denver Nuggets","Portland Trail Blazers"]'::jsonb),
  ('Tom Brady 20 sezon boyunca hangi NFL takımında forma giydi?', 'Tom Brady spent 20 seasons with which NFL team?', '["New England Patriots","Washington Commanders","Pittsburgh Steelers","San Francisco 49ers"]'::jsonb),
  ('Leicester City''yi 2015-16''da sürpriz biçimde lig şampiyonu yapan teknik direktör kimdir?', 'Who managed Leicester City to their fairy-tale Premier League title in 2015-16?', '["Claudio Ranieri","Brendan Rodgers","Nigel Pearson","Roberto Mancini"]'::jsonb),
  ('Michael Jordan 1994''te beyzbola geçerken hangi MLB kulübüyle sözleşme imzaladı?', 'When Michael Jordan switched to baseball in 1994, which MLB club signed him?', '["Chicago White Sox","Chicago Cubs","New York Yankees","Boston Red Sox"]'::jsonb),
  ('''Moneyball'' filminde Brad Pitt hangi beyzbol kulübünün genel menajerini oynar?', 'In ''Moneyball'', Brad Pitt plays the general manager of which baseball team?', '["Oakland Athletics","New York Yankees","Boston Red Sox","Los Angeles Dodgers"]'::jsonb),
  ('Glasgow''un iki dev kulübü Celtic ile Rangers arasındaki derbiye ne ad verilir?', 'What is the name given to the derby between Glasgow giants Celtic and Rangers?', '["Old Firm","El Clasico","Der Klassiker","Merseyside Derby"]'::jsonb),
  ('Thierry Henry Arsenal''de hangi forma numarasını giydi?', 'What shirt number did Thierry Henry wear at Arsenal?', '["14","9","10","12"]'::jsonb),
  ('Güney Afrika milli ragbi takımının lakabı nedir?', 'What is the nickname of South Africa''s national rugby union team?', '["Springboks","Wallabies","Pumas","All Blacks"]'::jsonb),
  ('Dart efsanesi Phil Taylor hangi lakapla anılır?', 'Darts legend Phil Taylor is known by which nickname?', '["The Power","Snakebite","Jackpot","The Menace"]'::jsonb),
  ('NBA''de ''The Mailman'' (Postacı) lakabıyla tanınan Utah Jazz efsanesi kimdir?', 'Which Utah Jazz legend was nicknamed ''The Mailman''?', '["Karl Malone","John Stockton","Charles Barkley","Patrick Ewing"]'::jsonb),
  ('Marco Polo, Çin''de hangi Moğol hükümdarının sarayında yıllarca hizmet etmiştir?', 'Marco Polo spent years serving at the court of which Mongol ruler in China?', '["Kublai Khan","Genghis Khan","Ogedei Khan","Hulagu Khan"]'::jsonb),
  ('Müttefiklerin 6 Haziran 1944''teki büyük çıkarması Fransa''nın hangi bölgesinin kıyılarına yapılmıştır?', 'The Allied D-Day landings on 6 June 1944 took place on the coast of which French region?', '["Normandy","Brittany","Provence","Picardy"]'::jsonb),
  ('Kaptan James Cook''un Avustralya''nın doğu kıyısına ulaştığı ilk seferindeki gemisi hangisidir?', 'Which ship did Captain James Cook sail on his first voyage to Australia''s east coast?', '["Endeavour","Bounty","Beagle","Golden Hind"]'::jsonb),
  ('''Yukarı Bak'' filminde yaşlı Carl''ın hayatını paylaştığı eşinin adı nedir?', 'In Pixar''s ''Up'', what is the name of Carl Fredricksen''s beloved wife?', '["Ellie","Grace","Alice","Lucy"]'::jsonb),
  ('''Forrest Gump'' filminde Forrest''ın çocukluktan beri âşık olduğu kızın adı nedir?', 'In ''Forrest Gump'', what is the name of the girl Forrest has loved since childhood?', '["Jenny","Sally","Mary","Annie"]'::jsonb),
  ('''Yağmur Adam'' filminde Raymond''un kardeşi Charlie''yi canlandıran oyuncu kimdir?', 'In ''Rain Man'', who played Raymond''s brother Charlie?', '["Tom Cruise","Kevin Bacon","Michael J. Fox","Matt Dillon"]'::jsonb),
  ('Sam Raimi''nin ''Örümcek Adam'' (2002) filminde Mary Jane''i canlandıran oyuncu kimdir?', 'Who played Mary Jane in Sam Raimi''s 2002 ''Spider-Man''?', '["Kirsten Dunst","Scarlett Johansson","Emma Stone","Zendaya"]'::jsonb),
  ('İlk ''Karayip Korsanları'' filminde Siyah İnci''nin lanetli kaptanı kimdir?', 'In the first ''Pirates of the Caribbean'' film, who is the cursed captain of the Black Pearl?', '["Barbossa","Davy Jones","Blackbeard","Captain Hook"]'::jsonb),
  ('''Rocky'' filminde Rocky Balboa''nın âşık olduğu pet shop çalışanı kadının adı nedir?', 'In ''Rocky'', what is the name of the pet shop worker Rocky Balboa falls for?', '["Adrian","Linda","Carla","Gloria"]'::jsonb),
  ('Pixar''ın ''Ters Yüz'' filminde küçük Riley ailesiyle hangi şehre taşınır?', 'In Pixar''s ''Inside Out'', which city does young Riley''s family move to?', '["San Francisco","Salt Lake City","Los Angeles","Seattle"]'::jsonb),
  ('Pixar''ın ''Coco'' filminde müzisyen olmayı hayal eden küçük çocuğun adı nedir?', 'In Pixar''s ''Coco'', what is the name of the boy who dreams of becoming a musician?', '["Miguel","Diego","Mateo","Carlos"]'::jsonb),
  ('''Hayalet'' (1990) filminin ünlü sahnesinde Molly hangi el sanatıyla uğraşmaktadır?', 'In the famous scene from ''Ghost'' (1990), what craft is Molly working at?', '["Pottery","Glassblowing","Oil painting","Weaving"]'::jsonb),
  ('''Madagaskar'' filminde hipokondriyak zürafanın adı nedir?', 'In ''Madagascar'', what is the name of the hypochondriac giraffe?', '["Melman","Mort","Maurice","Julien"]'::jsonb),
  ('1978 yapımı ''Grease'' filminde Sandy''yi canlandıran oyuncu kimdir?', 'Who played Sandy in the 1978 film ''Grease''?', '["Olivia Newton-John","Stockard Channing","Sarah Jessica Parker","Farrah Fawcett"]'::jsonb),
  ('Disney''in ''Aladdin'' filminde Prenses Yasemin''in evcil hayvanı Rajah hangi hayvandır?', 'In Disney''s ''Aladdin'', what kind of animal is Princess Jasmine''s pet Rajah?', '["Tiger","Lion","Leopard","Panther"]'::jsonb),
  ('Disney''in ''Bambi'' filminde Çiçek adlı utangaç karakter hangi hayvandır?', 'In Disney''s ''Bambi'', what kind of animal is the shy character named Flower?', '["Skunk","Squirrel","Hedgehog","Badger"]'::jsonb),
  ('''Esaretin Bedeli'' filminde Andy Dufresne''i canlandıran oyuncu kimdir?', 'Who played Andy Dufresne in ''The Shawshank Redemption''?', '["Tim Robbins","Ed Harris","Bill Pullman","Kevin Costner"]'::jsonb),
  ('''Gremlins'' filminde Billy''ye hediye edilen sevimli Mogwai''nin adı nedir?', 'In ''Gremlins'', what is the name of the cute Mogwai given to Billy as a gift?', '["Gizmo","Stripe","Mojo","Spike"]'::jsonb),
  ('''Jaws'' filminde Quint, Brody ve Hooper''ın köpekbalığı avına çıktığı teknenin adı nedir?', 'In ''Jaws'', what is the name of the boat Quint, Brody and Hooper take out to hunt the shark?', '["Orca","Pequod","Nautilus","Andrea Gail"]'::jsonb),
  ('''Er Ryan''ı Kurtarmak'' filminde kurtarılmaya çalışılan Er Ryan''ın ön adı nedir?', 'In ''Saving Private Ryan'', what is Private Ryan''s first name?', '["James","John","Michael","Robert"]'::jsonb),
  ('''Oyuncak Hikâyesi 2''de kovboy Woody''nin oyuncak atının adı nedir?', 'In ''Toy Story 2'', what is the name of Woody''s toy horse?', '["Bullseye","Silver","Trigger","Seabiscuit"]'::jsonb),
  ('''Yıldızlararası'' filminde Cooper''ın kızının adı nedir?', 'In ''Interstellar'', what is the name of Cooper''s daughter?', '["Murph","Lucy","Donna","Amelia"]'::jsonb),
  ('''Ölü Ozanlar Derneği''nde öğrencilerin masaya çıkıp söylediği ''Ey Kaptan! Kaptanım!'' hangi şairindir?', 'In ''Dead Poets Society'', the students'' ''O Captain! My Captain!'' comes from which poet?', '["Walt Whitman","Robert Frost","Edgar Allan Poe","Emily Dickinson"]'::jsonb),
  ('Kovboy Red Kit''in (Lucky Luke) zeki atının adı nedir?', 'What is the name of Lucky Luke''s clever horse?', '["Jolly Jumper","Silver Blaze","Black Beauty","Tornado"]'::jsonb),
  ('Solistliğini Bono''nun yaptığı U2 grubu hangi ülkedendir?', 'Bono''s band U2 comes from which country?', '["Ireland","Scotland","Wales","England"]'::jsonb),
  ('''Friends'' dizisinde Ross Geller''ın mesleği nedir?', 'On ''Friends'', what is Ross Geller''s profession?', '["Paleontologist","Archaeologist","Geologist","Anthropologist"]'::jsonb),
  ('''Şirinler''in yaratıcısı çizer Peyo hangi ülkelidir?', 'The creator of The Smurfs, the cartoonist Peyo, came from which country?', '["Belgium","France","Netherlands","Switzerland"]'::jsonb),
  ('Doğu Avrupa çorbası borşa kırmızı rengini veren sebze hangisidir?', 'Which vegetable gives the Eastern European soup borscht its red color?', '["Beetroot","Cabbage","Carrot","Potato"]'::jsonb),
  ('Siyah bira Guinness hangi ülkenin markasıdır?', 'The stout Guinness originally comes from which country?', '["Ireland","Scotland","Belgium","Wales"]'::jsonb),
  ('Hitchcock''un ''Sapık'' (Psycho) filmindeki motel sahibi Norman''ın soyadı nedir?', 'In Hitchcock''s ''Psycho'', what is the surname of motel owner Norman?', '["Bates","Torrance","Bateman","Krueger"]'::jsonb),
  ('Romalılar Yunan tanrılarının kralı Zeus''a hangi adla taparlardı?', 'By what name did the Romans worship Zeus, king of the gods?', '["Jupiter","Vulcan","Mercury","Neptune"]'::jsonb),
  ('''La Casa de Papel''de soyguncuların taktığı maske hangi ressamın yüzünü taşır?', 'In ''Money Heist'', the robbers'' masks depict which painter''s face?', '["Salvador Dali","Pablo Picasso","Francisco Goya","Joan Miro"]'::jsonb),
  ('''Harry Potter'' serisinde Harry''nin vaftiz babası kimdir?', 'In the ''Harry Potter'' series, who is Harry''s godfather?', '["Sirius Black","Remus Lupin","Severus Snape","Rubeus Hagrid"]'::jsonb),
  ('Yunan mitolojisinde Girit labirentindeki Minotauros''u öldüren kahraman kimdir?', 'In Greek myth, which hero slew the Minotaur in the labyrinth of Crete?', '["Theseus","Perseus","Heracles","Jason"]'::jsonb),
  ('''The Big Bang Theory''de Sheldon kapıyı çalarken hangi ismi üç kez söyler?', 'In The Big Bang Theory, whose name does Sheldon call out three times as he knocks?', '["Penny","Amy","Leonard","Bernadette"]'::jsonb),
  ('Yunan mitolojisinde çocuklarını yutan Zeus''un babası kimdir?', 'In Greek mythology, who was Zeus''s father, the Titan who swallowed his children?', '["Cronus","Uranus","Atlas","Hyperion"]'::jsonb),
  ('Rapçi Eminem''in şarkılarında kullandığı ünlü alter egosunun adı nedir?', 'What is the name of rapper Eminem''s famous alter ego?', '["Slim Shady","Sasha Fierce","Ziggy Stardust","Chris Gaines"]'::jsonb),
  ('Yunan mitolojisinde Medusa''nın kesilen boynundan doğan kanatlı atın adı nedir?', 'In Greek myth, what is the name of the winged horse that sprang from Medusa''s neck?', '["Pegasus","Sleipnir","Arion","Bucephalus"]'::jsonb),
  ('Homeros''un ''Odysseia''sında Odysseus''un dönmeye çalıştığı yurdu hangi adadır?', 'In Homer''s ''Odyssey'', which island is Odysseus trying to return home to?', '["Ithaca","Crete","Rhodes","Chios"]'::jsonb),
  ('''Harry Potter'' serisinde Ron Weasley''nin evcil faresinin adı nedir?', 'In the Harry Potter series, what is the name of Ron Weasley''s pet rat?', '["Scabbers","Crookshanks","Trevor","Nagini"]'::jsonb),
  ('Truva Savaşı''nda tahta at hilesini düşünen Yunan kahramanı kimdir?', 'Which Greek hero came up with the wooden horse trick in the Trojan War?', '["Odysseus","Achilles","Agamemnon","Menelaus"]'::jsonb),
  ('''Gurur ve Önyargı''da Elizabeth Bennet sonunda kiminle evlenir?', 'In ''Pride and Prejudice'', whom does Elizabeth Bennet eventually marry?', '["Mr. Darcy","Mr. Bingley","Mr. Wickham","Mr. Collins"]'::jsonb),
  ('Pixar''ın ''Ratatouille'' filminde şef olmak isteyen farenin adı nedir?', 'In Pixar''s ''Ratatouille'', what is the name of the rat who dreams of becoming a chef?', '["Remy","Emile","Django","Linguini"]'::jsonb),
  ('Shakespeare''in trajedisinde Othello hangi şehrin hizmetindeki bir generaldir?', 'In Shakespeare''s tragedy, Othello is a general in the service of which city?', '["Venice","Florence","Genoa","Naples"]'::jsonb),
  ('''Asteriks'' çizgi romanlarında Oburiks sırtında sürekli ne taşır?', 'In the ''Asterix'' comics, what does Obelix constantly carry on his back?', '["Menhir","Barrel","Shield","Log"]'::jsonb),
  ('Truvalı Paris''in kaçırdığı Güzel Helen''in kocası olan Sparta kralı kimdir?', 'Which Spartan king was the husband of Helen, who was taken by Paris of Troy?', '["Menelaus","Agamemnon","Priam","Achilles"]'::jsonb),
  ('Dickens''ın ''Büyük Umutlar'' romanının yetim kahramanının lakabı nedir?', 'What is the nickname of the orphan hero of Dickens''s ''Great Expectations''?', '["Pip","Oliver","Tiny Tim","Copperfield"]'::jsonb),
  ('''Game of Thrones''ta Arya Stark''ın küçük kılıcının adı nedir?', 'In ''Game of Thrones'', what is the name of Arya Stark''s small sword?', '["Needle","Longclaw","Ice","Oathkeeper"]'::jsonb),
  ('Sahibini yıllarca bekleyen köpek Hachikō''nun heykeli Tokyo''nun hangi istasyonundadır?', 'At which Tokyo station does the statue of the loyal dog Hachiko stand?', '["Shibuya","Shinjuku","Ueno","Ikebukuro"]'::jsonb),
  ('Wonder Woman''ın doğup büyüdüğü Amazon adasının adı nedir?', 'What is the name of the Amazon island where Wonder Woman was raised?', '["Themyscira","Atlantis","Apokolips","Wakanda"]'::jsonb),
  ('''Star Trek''te Bay Spock''ın babasının halkının yaşadığı gezegenin adı nedir?', 'In ''Star Trek'', what is the home planet of Mr. Spock''s father''s people?', '["Vulcan","Romulus","Kronos","Bajor"]'::jsonb),
  ('''Harry Potter'' serisinde Dumbledore''un anka kuşunun adı nedir?', 'In the ''Harry Potter'' series, what is the name of Dumbledore''s phoenix?', '["Fawkes","Hedwig","Buckbeak","Errol"]'::jsonb),
  ('Toblerone çikolatasının ambalajında hangi dağ yer alır?', 'Which mountain appears on the packaging of Toblerone chocolate?', '["The Matterhorn","Mont Blanc","The Eiger","The Jungfrau"]'::jsonb),
  ('''Rocky'' filminde Rocky''nin koşarak çıktığı ünlü müze merdivenleri hangi şehirdedir?', 'The museum steps Rocky famously runs up are in which city?', '["Philadelphia","Indianapolis","Pittsburgh","Baltimore"]'::jsonb),
  ('''Ziggy Stardust'' hangi şarkıcının sahne kişiliğidir?', 'Ziggy Stardust was the stage persona of which singer?', '["David Bowie","Elton John","Freddie Mercury","Lou Reed"]'::jsonb),
  ('''Baba'' filminde Corleone ailesinin avukatı ve danışmanı kimdir?', 'In ''The Godfather'', who is the Corleone family''s lawyer and consigliere?', '["Tom Hagen","Luca Brasi","Sal Tessio","Peter Clemenza"]'::jsonb),
  ('Basketbolu 1891''de icat eden beden eğitimi öğretmeni kimdir?', 'Which physical education instructor invented basketball in 1891?', '["James Naismith","Walter Camp","William Morgan","Abner Doubleday"]'::jsonb),
  ('''Doctor Who''da Doktor''un polis kulübesi görünümlü zaman makinesinin adı nedir?', 'In ''Doctor Who'', what is the Doctor''s police-box-shaped time machine called?', '["TARDIS","Serenity","Galactica","Nostromo"]'::jsonb),
  ('Tom Sawyer, arkadaşlarını kandırıp ceza olarak kendisine verilen neyi badanalatır?', 'Which object does Tom Sawyer trick his friends into whitewashing for him?', '["Fence","Barn","Boat","Shed"]'::jsonb),
  ('Kral Arthur efsanesinde Kraliçe Guinevere ile yasak aşk yaşayan şövalye kimdir?', 'In Arthurian legend, which knight has a forbidden love affair with Queen Guinevere?', '["Lancelot","Gawain","Percival","Galahad"]'::jsonb),
  ('''İlyada''da Akhilleus''un Patroklos''un intikamını almak için öldürdüğü Truvalı kahraman kimdir?', 'In the ''Iliad'', which Trojan hero does Achilles kill to avenge Patroclus?', '["Hector","Paris","Aeneas","Priam"]'::jsonb),
  ('''Peter Tavşan'' karakterini yaratan İngiliz yazar kimdir?', 'Which English author created the character Peter Rabbit?', '["Beatrix Potter","Enid Blyton","Roald Dahl","A.A. Milne"]'::jsonb),
  ('Andersen''in ''Küçük Deniz Kızı'', insan bacakları karşılığında cadıya neyini verir?', 'In Andersen''s ''The Little Mermaid'', what does the mermaid give the sea witch in exchange for legs?', '["Her voice","Her hair","Her eyes","Her heart"]'::jsonb),
  ('''Odysseia''da Odysseus''un dönüşünü yıllarca talipleri oyalayarak bekleyen karısı kimdir?', 'In ''The Odyssey'', which wife holds off her suitors for years while waiting for Odysseus?', '["Penelope","Helen","Andromache","Clytemnestra"]'::jsonb),
  ('''Alice Harikalar Diyarında''da Mart Tavşanı ile çay partisi veren deli karakter kimdir?', 'In ''Alice''s Adventures in Wonderland'', who hosts the mad tea party with the March Hare?', '["The Hatter","The Carpenter","The Cobbler","The Clockmaker"]'::jsonb),
  ('Kipling''in ''Orman Kitabı''nda Mowgli''nin baş düşmanı Shere Khan hangi hayvandır?', 'In Kipling''s ''The Jungle Book'', what kind of animal is Mowgli''s enemy Shere Khan?', '["Tiger","Lion","Leopard","Crocodile"]'::jsonb),
  ('Dickens''ın ''Noel Şarkısı''nda Bob Cratchit''in hasta küçük oğlunun adı nedir?', 'In Dickens''s ''A Christmas Carol'', what is the name of Bob Cratchit''s sickly young son?', '["Tim","Sam","Ben","Joe"]'::jsonb),
  ('''Odysseia''da Odysseus, Truva''dan sonra hangi adadaki krallığına dönmeye çalışır?', 'In the ''Odyssey'', to which island kingdom is Odysseus trying to return after Troy?', '["Ithaca","Crete","Rhodes","Chios"]'::jsonb),
  ('''Lolita'' romanının yazarı kimdir?', 'Who wrote the novel ''Lolita''?', '["Nabokov","Updike","Roth","Bellow"]'::jsonb),
  ('''Matilda'' ve ''Koca Sevimli Dev'' kitaplarının yazarı kimdir?', 'Who wrote the children''s books ''Matilda'' and ''The BFG''?', '["Roald Dahl","Enid Blyton","Beatrix Potter","Michael Ende"]'::jsonb),
  ('Verne''in ''Seksen Günde Devrialem'' romanında dünyayı dolaşmak için iddiaya giren beyefendi kimdir?', 'In Jules Verne''s ''Around the World in Eighty Days'', which gentleman makes the famous wager?', '["Phileas Fogg","Captain Nemo","Michel Strogoff","Ned Land"]'::jsonb),
  ('Orwell''in ''1984'' romanının baş kahramanı kimdir?', 'Who is the main character of George Orwell''s ''Nineteen Eighty-Four''?', '["Winston Smith","Bernard Marx","Guy Montag","John Savage"]'::jsonb),
  ('''Pi''nin Yaşamı'' romanında Pi ile aynı filikada kalan kaplanın adı nedir?', 'In ''Life of Pi'', what is the name of the tiger stranded in the lifeboat with Pi?', '["Richard Parker","Henry Morgan","William Bligh","Edward Teach"]'::jsonb),
  ('''Otomatik Portakal'' romanının yazarı kimdir?', 'Who wrote the novel ''A Clockwork Orange''?', '["Anthony Burgess","Kingsley Amis","William Golding","Martin Amis"]'::jsonb),
  ('Albert Camus''nün ''Veba'' romanı hangi Cezayir şehrinde geçer?', 'In which Algerian city is Albert Camus''s novel ''The Plague'' set?', '["Oran","Constantine","Annaba","Tlemcen"]'::jsonb),
  ('''Hamlet''te Hamlet''in babasını zehirleyip tahta geçen amcasının adı nedir?', 'In ''Hamlet'', what is the name of the uncle who poisons Hamlet''s father and seizes the throne?', '["Claudius","Polonius","Laertes","Horatio"]'::jsonb),
  ('''Bülbülü Öldürmek'' romanını anlatan Atticus Finch''in kızının lakabı nedir?', 'In ''To Kill a Mockingbird'', what is the nickname of Atticus Finch''s daughter, who narrates the story?', '["Scout","Jem","Dill","Boo"]'::jsonb),
  ('Frank Herbert''ın ''Dune'' romanının geçtiği çöl gezegeninin adı nedir?', 'What is the name of the desert planet on which Frank Herbert''s ''Dune'' is set?', '["Arrakis","Caladan","Trantor","Solaris"]'::jsonb),
  ('Sherlock Holmes''u alt ettiği için Holmes''un ''o kadın'' diye andığı karakter kimdir?', 'Which character outwits Sherlock Holmes and is forever known to him as ''the woman''?', '["Irene Adler","Mary Morstan","Violet Hunter","Martha Hudson"]'::jsonb)
  ) v(soru, en_soru, en_secenekler)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Çevrilmeyenler
insert into public.ceviri_atlanan (question_id, dil, neden, kod)
select q.id, 'en', v.neden, 'cevrilemez'
  from (values
  ('''Keşanlı Ali Destanı'' adlı tiyatro oyununun yazarı kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Âşık Veysel hangi ilin Şarkışla ilçesinde doğmuştur?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Türk Beşleri''nden ''Yunus Emre Oratoryosu''nun bestecisi kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Sezen Aksu''ya hayranlarınca verilen lakap hangisidir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Mobil bulmaca oyunu Royal Match''i geliştiren İstanbul merkezli şirket hangisidir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Kibar Feyzo'' filminde Feyzo''nun başlık parası yüzünden evlenemediği kızın adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Zeki Müren''in hayranlarınca anıldığı ünlü lakabı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Yaşar Kemal''in ''İnce Memed'' romanı hangi yörede geçer?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Ezel'' dizisinde Ezel Bayraktar''ı hangi oyuncu canlandırmıştır?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Leyla ile Mecnun'' dizisinde Mecnun''u hangi oyuncu canlandırmıştır?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Aşk-ı Memnu'' dizisinde Bihter karakterini hangi oyuncu canlandırmıştır?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Kürk Mantolu Madonna''da Berlin''de Maria Puder''e âşık olan kahraman kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Dede Korkut''ta Basat''ın, kardeşi Kıyan Selçuk''un öcünü almak için öldürdüğü dev kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız')
  ) v(soru, neden)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Karıştırma (TR + EN aynı permütasyon)
drop table if exists pg_temp._parti_karistir;
create temp table _parti_karistir as
select q.id, array_agg(s.idx order by s.rnd) as perm
  from public.questions q
  cross join lateral (
    select (ordinality - 1)::int as idx, random() as rnd
      from jsonb_array_elements(q.secenekler) with ordinality
  ) s
 where q.created_at >= transaction_timestamp()
 group by q.id;

update public.questions q
   set secenekler = (select jsonb_agg(q.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o)),
       dogru_cevap = (array_position(k.perm, q.dogru_cevap::int) - 1)::smallint
  from _parti_karistir k
 where q.id = k.id;

update public.question_translations t
   set secenekler = (select jsonb_agg(t.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o))
  from _parti_karistir k
 where t.question_id = k.id;

drop table if exists pg_temp._parti_karistir;
