-- ============================================================
-- 1051 — soru_parti_codex_03 (stil: docs/SORU_STIL_PROFILI.md): 191 soru · 2026-10-10
--
-- Kategori: edebiyat 18 · genel_kultur 41 · muzik 18 · sanat 28 · sinema 23 · spor 24 · tarih 5 · teknoloji 34
-- Yerel (kapsam='yerel', ulke='TR'): 0 · zorluk 1–5: 0/132/59/0/0
-- İngilizce çeviri: 191 · çevrilmeyen (ceviri_atlanan, kod 'cevrilemez'): 0
--
-- Kalite: Codex yazımı; codex-kapi.mjs kapı 1–5 (TR/EN biçim ve şık denge,
-- havuz/parti birebir ve Jaccard tekrar, cevap soruda değil, DB kural kapısı,
-- Jev şık ipucu p ≤ 0,75 ve tek doğru yanlış şık p < 0,5).
-- Claude API kullanılmadı. Son Claude incelemesi AYRI; bekleyen SQL onaysız UYGULANMAZ.
--
-- Sıra: sorular doğru şık 0'da eklenir, çeviriler aynı sırayla yazılır, sonunda YALNIZ
-- bu işlemde eklenen satırların şıkları karıştırılır — TR ve EN AYNI permütasyonla
-- (dogru_cevap indeksi ortak olduğu için şart). `created_at >= transaction_timestamp()`
-- koşulu ZORUNLUDUR; onsuz tüm havuz karışır ve oynanan maçlarda indeks kayar.
-- Üretici: node araclar/soru-uretim/uret-migration-parti.mjs --parti 3 --no 1051 --klasor codex-03 --ad soru_parti_codex_03 --codex --onayli
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori, kapsam, ulke, zorluk) values
('Botticelli''nin ''İlkbahar''ını görmek isteyen biri hangi müzeyi ziyaret etmelidir?', '["Uffizi","Louvre","Prado","MoMA"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Van Gogh''un kardeşi Theo hangi mesleği yapıyordu?', '["Sanat tüccarı","Gazete editörü","Orkestra şefi","Tiyatro oyuncusu"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Yayoi Kusama''nın resim ve heykellerinde sık kullandığı desen hangisidir?', '["Puantiyeler","Zikzak çizgiler","Spiral çizgiler","Kare ızgaralar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Keith Haring''in ''Radiant Baby'' figüründe bebek hangi pozisyondadır?', '["Emekler","Oturur","Ayağa kalkar","Yatar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Jeff Koons''un Bilbao''daki ''Puppy'' heykelinin yüzeyi neyle kaplıdır?', '["Canlı çiçekler","Renkli camlar","Metal plakalar","Ahşap parçalar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Frida Kahlo’nun Meksiko’daki müze evinin dış duvarlarının baskın rengi hangisidir?', '["Mavi","Kırmızı","Sarı","Yeşil"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Rodin''in ''Öpücük'' heykelindeki iki figür hangi konumdadır?', '["Oturarak sarılır","Ayakta el ele durur","Yan yana yürür","Sırt sırta oturur"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Kuğu Gölü'' balesinde kuğuya dönüştürülen prensesin adı nedir?', '["Odette","Aurora","Giselle","Clara"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Toulouse-Lautrec''in Moulin Rouge afişleri en çok hangi sahne sanatını konu alır?', '["Dans","Opera","Pandomim","Kukla tiyatrosu"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Goya''nın kraliyet fabrikası için hazırladığı renkli tasarımlar hangi ürünün dokunmasında kullanıldı?', '["Duvar halısı","Masa örtüsü","Koltuk döşemesi","Saray perdesi"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Vermeer''in ''Sütçü Kız'' tablosundaki kadının üst giysisinin baskın rengi nedir?', '["Sarı","Kırmızı","Yeşil","Lacivert"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Wyeth''in “Christina''nın Dünyası” tablosundaki kadın hangi açık alanda görülür?', '["Çayır","Orman","Sahil","Şehir meydanı"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''West Side Story''de Jets çetesinin rakibi olan çetenin adı nedir?', '["Sharks","Tigers","Eagles","Panthers"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Chicago'' sahne müzikalinin kadın baş karakterlerinden Roxie''nin soyadı nedir?', '["Hart","Kelly","Morton","Sunshine"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Cabaret'' sahne müzikalindeki gece kulübünün adı nedir?', '["Kit Kat Club","Moulin Rouge","Crazy Horse","Folies Bergère"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Rodin''in ''Calais Burjuvaları'' heykel grubu kaç insan figüründen oluşur?', '["6","4","5","7"]'::jsonb, 0, 'sanat', 'global', null, 2),
('New York''taki Flatiron Binası''nın planı hangi geometrik şekli andırır?', '["Üçgen","Dikdörtgen","Beşgen","Daire"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Seurat''nın “La Grande Jatte Adası''nda Bir Pazar Öğleden Sonra” tablosunda hangi ortam görülür?', '["Nehir kıyısındaki park","Deniz kıyısındaki liman","Dağ yamacındaki köy","Kent merkezindeki pazar"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Annie'' sahne müzikalinin başkahramanı başlangıçta nerede yaşar?', '["Yetimhane","Yatılı okul","Çiftlik evi","Sirk kampı"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Habitat 67 tasarımını yapan mimar kimdir?', '["Moshe Safdie","Le Corbusier","Antoni Gaudí","Alvar Aalto"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Vitra İtfaiye İstasyonu tasarımını yapan mimar kimdir?', '["Zaha Hadid","Louis Kahn","Jørn Utzon","Tadao Ando"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Lloyd''s of London binası tasarımını yapan mimar kimdir?', '["Richard Rogers","Walter Gropius","Oscar Niemeyer","Eero Saarinen"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Bernini''nin ''Apollon ve Dafne'' heykelinin ana malzemesi hangisidir?', '["Mermer","Granit","Bazalt","Bronz"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Winston Churchill''in ''Kükreyen Aslan'' portresini çeken fotoğrafçı kimdir?', '["Yousuf Karsh","Alfred Eisenstaedt","Robert Capa","Ansel Adams"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Umberto Boccioni hangi sanat akımının önde gelen temsilcilerindendir?', '["Fütürizm","Pop art","Romantizm","Kübizm"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Venedik Bienali''ndeki Arsenale yapıları başlangıçta ne olarak kullanılıyordu?', '["Tersane","Tren istasyonu","Elektrik santrali","Tekstil fabrikası"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Man Ray''in nesneleri ışığa duyarlı kâğıda koyarak yaptığı fotoğraflar hangi adla anılır?', '["Rayograf","Dagerreyotip","Ambrotip","Ferrotip"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Christo''nun büyük ölçekli projelerinde 2009''a kadar ortak çalıştığı eşi kimdir?', '["Jeanne-Claude","Niki de Saint Phalle","Sonia Delaunay","Louise Bourgeois"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Christine McVie hangi grubun üyesiydi?', '["Fleetwood Mac","Black Sabbath","Led Zeppelin","Dire Straits"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Tony Iommi hangi grubun üyesiydi?', '["Black Sabbath","Fleetwood Mac","Led Zeppelin","Dire Straits"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Buddy Rich en çok hangi enstrümanla tanınır?', '["Bateri","Klavye","Gitar","Keman"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''The Joshua Tree'' albümü hangi gruba aittir?', '["U2","Yes","ABBA","Blur"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Madama Butterfly'' operasını kim bestelemiştir?', '["Giacomo Puccini","Richard Strauss","Giuseppe Verdi","Richard Wagner"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''While My Guitar Gently Weeps'' şarkısı ilk olarak hangi albümde yayımlandı?', '["The White Album","Please Please Me","With the Beatles","A Hard Day’s Night"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Nothing Compares 2 U'' şarkısını yazan müzisyen kimdir?', '["Prince","George Michael","David Bowie","Stevie Wonder"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Queen''in ''Under Pressure'' kaydında Freddie Mercury ile düet yapan kimdir?', '["David Bowie","Elton John","Mick Jagger","Rod Stewart"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Eminem''in ''Stan'' şarkısında hangi şarkıcının ''Thank You'' kaydı örneklenir?', '["Dido","Enya","Sade","Sarah McLachlan"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Bee Gees''teki Robin''in ikiz kardeşi olan üye kimdir?', '["Maurice Gibb","Barry Gibb","Andy Gibb","Colin Petersen"]'::jsonb, 0, 'muzik', 'global', null, 2),
('The Beatles''ın son halka açık konseri 1969''da hangi yerde yapıldı?', '["Bina çatısı","Tren peronu","Otel lobisi","Sinema salonu"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Don''t Go Breaking My Heart''ta Elton John''un düet partneri kimdir?', '["Kiki Dee","Dusty Springfield","Bonnie Tyler","Kate Bush"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Tosca'' operasında Cavaradossi hangi sanat dalıyla uğraşır?', '["Resim","Heykel","Müzik","Tiyatro"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Mozart''ın ''Sihirli Flüt'' operasındaki Gece Kraliçesi rolü hangi ses türü için yazılmıştır?', '["Soprano","Kontralto","Tenor","Bariton"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Freddie Mercury''nin rock kariyerinden önce eğitimini aldığı görsel alan hangisidir?', '["Grafik tasarım","Moda tasarımı","Endüstriyel tasarım","İç mimarlık"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Puccini''nin ''La bohème'' operasında Rodolfo''nun âşık olduğu genç kadın kimdir?', '["Mimì","Musetta","Tosca","Butterfly"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Bizet''nin ''Carmen'' operasında Carmen''in âşık olduğu boğa güreşçisi kimdir?', '["Escamillo","Don José","Le Remendado","Dancaïre"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Beethoven''ın Beşinci Senfonisi''nin ünlü açılış motifinde kaç nota vardır?', '["4","3","5","6"]'::jsonb, 0, 'muzik', 'global', null, 3),
('ZX Spectrum hangi şirket tarafından üretilmiştir?', '["Sinclair Research","Texas Instruments","Hewlett-Packard","Microsoft"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Sega Dreamcast, Japonya''da hangi yıl piyasaya çıktı?', '["1998","1997","1999","2001"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Google''ın Chrome tarayıcısı hangi yıl piyasaya çıktı?', '["2008","2007","2009","2011"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Stardew Valley'' oyununu geliştiren kişi kimdir?', '["Eric Barone","Toby Fox","Lucas Pope","Daniel Mullins"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Adobe Photoshop 1.0 ilk kez hangi yıl yayımlandı?', '["1990","1989","1991","1993"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nintendo Switch ilk kez hangi yıl yayımlandı?', '["2017","2015","2016","2019"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Cassini''nin Titan''a indirdiği sondanın adı nedir?', '["Huygens","Philae","Deep Space 2","MINERVA"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Ethernet''in ilk çalışmalarının yapıldığı PARC hangi şirkete aitti?', '["Xerox","Adobe","Intel","Nokia"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Standart RJ45 Ethernet fişinde kaç temas ucu vardır?', '["8","4","6","10"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk uzay mekiği uçuşu STS-1 hangi mekikle yapıldı?', '["Columbia","Discovery","Atlantis","Endeavour"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Java dili, Oracle satın almadan önce hangi şirkette geliştirildi?', '["Sun Microsystems","Silicon Graphics","Digital Equipment","Hewlett-Packard"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('2012''de Mars''a inen ve ''Sky Crane'' sistemiyle bırakılan keşif robotu hangisidir?', '["Curiosity","Opportunity","Sojourner","Spirit"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('NASA''nın 2004''te Mars''a indirdiği Spirit''in ikiz keşif robotu hangisidir?', '["Opportunity","Curiosity","Sojourner","Perseverance"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İnternetteki ilk YouTube videosunda Jawed Karim hangi tür yerde görülür?', '["Hayvanat bahçesi","Lunapark","Tren istasyonu","Alışveriş merkezi"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('1990''larda yaygınlaşan sert plastik gövdeli küçük disketin çapı kaç inçti?', '["3,5","2,5","4,5","5,5"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('1990''ların iMac G3 bilgisayarında sistem birimi hangi parçayla aynı kasadaydı?', '["Ekran","Yazıcı","Tarayıcı","Hoparlör standı"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın 2016''da tanıttığı kablosuz kulaklık serisinin adı nedir?', '["AirPods","EarPods","Beats Studio","Powerbeats"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Amazon Kindle''ın ilk modellerinde kullanılan kâğıda benzeyen ekran teknolojisi hangisidir?', '["Elektronik mürekkep","Plazma görüntü paneli","Katot ışın tüpü","Sıvı kristal ekran"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('BlackBerry telefonları klasik modellerinde hangi fiziksel özelliğiyle tanınmıştır?', '["QWERTY klavye","Sayısal çevirme diski","Sadece yön tuşları","Çıkarılabilir oyun kolu"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple iPod''un klasik modellerindeki dairesel kontrol yüzeyinin adı nedir?', '["Click Wheel","Magic Trackpad","Touch Bar","Digital Crown"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Atari 2600''ün oyunları konsola hangi fiziksel ortamda takılırdı?', '["Kartuş","Disket","CD-ROM","DVD-ROM"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('ThinkPad klavyelerindeki kırmızı işaretleme çubuğunun adı nedir?', '["TrackPoint","Trackball","TouchPad","Magic Mouse"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('NASA''nın Apollo Ay modülleri inişte kaç ayağa dayanıyordu?', '["4","3","5","6"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Sputnik 1''in gövdesi hangi geometrik biçimdeydi?', '["Küre","Küp","Silindir","Koni"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Microsoft Kinect aygıtı geliştirilirken hangi kod adı kullanıldı?', '["Project Natal","Project Scorpio","Revolution","Project Morpheus"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('1998''de tanıtılan ilk iMac''in mavi tonu hangi adla pazarlandı?', '["Bondi Blue","Pacific Blue","Ocean Blue","Midnight Blue"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('1984''teki ilk Macintosh''ta hangi şirketin 68000 işlemcisi kullanılmıştır?', '["Motorola","National Semiconductor","Texas Instruments","Intel"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('1947''de Harvard Mark II''de bulunan ve hata günlüğüne yapıştırılan böcek hangisiydi?', '["Güve","Karınca","Sinek","Hamamböceği"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Adobe şirketinin adı kuruculardan birinin evinin yanındaki hangi doğal oluşumdan alınmıştır?', '["Dere","Mağara","Okyanus","Tepe"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('İlk Photoshop sürümü başlangıçta hangi bilgisayar platformu için yayımlandı?', '["Macintosh","Windows PC","Amiga","Atari ST"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('eBay''deki ilk satışta Pierre Omidyar''ın sattığı bozuk nesne neydi?', '["Lazer işaretçi","Cep hesap makinesi","Taşınabilir radyo","Dijital kol saati"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Uluslararası Uzay İstasyonu''nun 1998''de fırlatılan ilk modülü hangisidir?', '["Zarya","Zvezda","Unity","Destiny"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Hewlett-Packard''ın ilk ticari ürünü hangi tür cihazdı?', '["Ses osilatörü","Radyo alıcısı","Fotoğraf makinesi","Mekanik hesap makinesi"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Apple''ın 1977''deki ısırılmış elma logosunu tasarlayan kişi kimdir?', '["Rob Janoff","Ronald Wayne","Paul Rand","Susan Kare"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Carl Lewis hangi spor dalıyla tanınır?', '["Atletizm","Bisiklet","Basketbol","Beyzbol"]'::jsonb, 0, 'spor', 'global', null, 2),
('Lin Dan hangi spor dalıyla tanınır?', '["Badminton","Masa tenisi","Tenis","Squash"]'::jsonb, 0, 'spor', 'global', null, 2),
('Anfield hangi futbol kulübünün stadıdır?', '["Liverpool","Barcelona","Feyenoord","Juventus"]'::jsonb, 0, 'spor', 'global', null, 2),
('Santiago Bernabéu hangi futbol kulübünün stadıdır?', '["Real Madrid","Inter Milan","Barcelona","Liverpool"]'::jsonb, 0, 'spor', 'global', null, 2),
('Camp Nou hangi futbol kulübünün stadıdır?', '["Barcelona","Liverpool","Feyenoord","Juventus"]'::jsonb, 0, 'spor', 'global', null, 2),
('Claret Jug hangi spor dalında verilen bir kupadır?', '["Golf","Boks","Tenis","Yüzme"]'::jsonb, 0, 'spor', 'global', null, 2),
('Magic Johnson hangi forma numarasıyla özdeşleşmiştir?', '["32","31","33","34"]'::jsonb, 0, 'spor', 'global', null, 2),
('Larry Bird hangi forma numarasıyla özdeşleşmiştir?', '["33","32","34","35"]'::jsonb, 0, 'spor', 'global', null, 2),
('Paolo Maldini''nin AC Milan dönemi hangi forma numarasıyla özdeşleşmiştir?', '["3","7","8","9"]'::jsonb, 0, 'spor', 'global', null, 2),
('Kobe Bryant''ın ilk Lakers yılları hangi forma numarasıyla özdeşleşmiştir?', '["8","3","7","9"]'::jsonb, 0, 'spor', 'global', null, 2),
('Shaun White hangi spor dalıyla tanınır?', '["Snowboard","Kayakla atlama","Serbest stil kayak","Alp disiplini kayak"]'::jsonb, 0, 'spor', 'global', null, 2),
('Cruyff dönüşü hareketi hangi spor dalında kullanılır?', '["Futbol","Eskrim","Kriket","Halter"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Toprak Kortların Kralı'' lakabıyla tanınan tenisçi kimdir?', '["Rafael Nadal","Novak Djokovic","Roger Federer","Juan Carlos Ferrero"]'::jsonb, 0, 'spor', 'global', null, 2),
('''The Dream'' lakabıyla tanınan NBA pivotu kimdir?', '["Hakeem Olajuwon","Dikembe Mutombo","Patrick Ewing","David Robinson"]'::jsonb, 0, 'spor', 'global', null, 2),
('1973''teki ''Battle of the Sexes'' maçında Billie Jean King''in rakibi kimdi?', '["Bobby Riggs","Jack Kramer","Pancho Gonzales","Roy Emerson"]'::jsonb, 0, 'spor', 'global', null, 2),
('Chicago Bulls''un 1990''lardaki şampiyonluklarında koç kimdi?', '["Phil Jackson","Pat Riley","Chuck Daly","Gregg Popovich"]'::jsonb, 0, 'spor', 'global', null, 2),
('Lewis Hamilton''ın ilk Formula 1 şampiyonluğu hangi yılda gerçekleşti?', '["2008","2007","2009","2011"]'::jsonb, 0, 'spor', 'global', null, 3),
('Thierry Henry, Arsenal''e transfer olmadan hemen önce hangi kulüpteydi?', '["Juventus","Inter Milan","AC Milan","Fiorentina"]'::jsonb, 0, 'spor', 'global', null, 3),
('Nadia Comăneci olimpiyatlarda ilk tam 10 puanını hangi jimnastik aletinde aldı?', '["Asimetrik paralel","Yerden hareketler","Atlama beygiri","Denge tahtası"]'::jsonb, 0, 'spor', 'global', null, 3),
('Wimbledon erkekler tekler kupasının tepesinde hangi meyve figürü vardır?', '["Ananas","Nar","Elma","Portakal"]'::jsonb, 0, 'spor', 'global', null, 3),
('Juventus siyah-beyaz formalarını hangi İngiliz kulübünden esinlenerek benimsemiştir?', '["Notts County","Derby County","Newcastle United","Sunderland"]'::jsonb, 0, 'spor', 'global', null, 3),
('Bob Beamon 1968 Mexico City''de 8,90 metre ile hangi atletizm dalında olimpiyat şampiyonu oldu?', '["Uzun atlama","Üç adım atlama","Yüksek atlama","Sırıkla atlama"]'::jsonb, 0, 'spor', 'global', null, 3),
('1998 Dünya Kupası''nı kazanan Fransa''nın teknik direktörü kimdi?', '["Aimé Jacquet","Roger Lemerre","Gérard Houllier","Didier Deschamps"]'::jsonb, 0, 'spor', 'global', null, 3),
('Michael Jordan''ın 1997 NBA finali altıncı maçta galibiyet basketi için pas verdiği takım arkadaşı kimdi?', '["Steve Kerr","John Paxson","Ron Harper","Toni Kukoč"]'::jsonb, 0, 'spor', 'global', null, 3),
('1773 Boston protestosunda denize atılan ticari yük neydi?', '["Çay","Tütün","Şeker","Kahve"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Titanic''in 1912''deki kaptanının soyadı nedir?', '["Smith","Rostron","Lord","Lightoller"]'::jsonb, 0, 'tarih', 'global', null, 2),
('İngiltere Kralı VIII. Henry''nin ilk eşi kimdir?', '["Aragonlu Catherine","Avusturyalı Catherine","Anne Boleyn","Jane Seymour"]'::jsonb, 0, 'tarih', 'global', null, 2),
('ABD''nin Savunma Bakanlığı binasına adını veren geometrik şekil hangisidir?', '["Beşgen","Altıgen","Dörtgen","Sekizgen"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Roma İmparatoru Nero''nun gençlik dönemindeki Stoacı öğretmeni kimdir?', '["Seneca","Musonius Rufus","Epiktetos","Hierokles"]'::jsonb, 0, 'tarih', 'global', null, 3),
('''Altıncı His'' filmini kim yönetmiştir?', '["M. Night Shyamalan","Guillermo del Toro","Quentin Tarantino","Christopher Nolan"]'::jsonb, 0, 'sinema', 'global', null, 2),
('The Matrix''teki Neo karakterini hangi oyuncu canlandırmıştır?', '["Keanu Reeves","Bruce Willis","Heath Ledger","Hugh Jackman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Harry Potter filmlerindeki Severus Snape karakterini hangi oyuncu canlandırmıştır?', '["Alan Rickman","Ralph Fiennes","Jeremy Irons","Timothy Spall"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Can Dostum''daki Sean Maguire karakterini hangi oyuncu canlandırmıştır?', '["Robin Williams","Robert De Niro","Morgan Freeman","Dustin Hoffman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yüzüklerin Efendisi: Yüzük Kardeşliği'' filminin müziklerini kim bestelemiştir?', '["Howard Shore","Danny Elfman","James Horner","John Williams"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Chariots of Fire'' filminin müziklerini kim bestelemiştir?', '["Vangelis","Nino Rota","Hans Zimmer","Danny Elfman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('2018 yılında verilen En İyi Film Oscar''ını hangi film kazandı?', '["Suyun Sesi","Dunkirk","Üç Billboard Ebbing, Missouri","Lady Bird"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Madagascar''daki Kral Julien hangi tür hayvandır?', '["Lemur","Panda","Aslan","Tilki"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Apollo 13'' filminde görev kontrol merkezi hangi şehirde bulunur?', '["Houston","Dallas","Austin","San Antonio"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''RoboCop'' (1987) filminde Detroit polisini yöneten şirket hangisidir?', '["OCP","Weyland-Yutani","Tyrell Corporation","Cyberdyne Systems"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Büyük Lebowski''de Dude ve arkadaşları hangi salon sporunu oynar?', '["Bowling","Bilardo","Masa tenisi","Badminton"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Amélie''de babanın süs olarak bahçesine koyduğu figür hangisidir?', '["Cüce","Flamingo","Kaplumbağa","Kurbağa"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Ucuz Roman''da Vincent ile Mia restoranda birlikte hangi etkinliğe katılır?', '["Dans yarışması","Karaoke yarışması","Bilgi yarışması","Bilardo turnuvası"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Ölüm Tarlaları'' (The Killing Fields) hangi ülkedeki Kızıl Kmer dönemini anlatır?', '["Kamboçya","Bangladeş","Endonezya","Tayland"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Gremlinler''de Gizmo''nun türünün adı nedir?', '["Mogwai","Ewok","Wookiee","Tribble"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Bıçak Sırtı'' (1982) filmindeki yapay insanların adı nedir?', '["Replikant","Terminatör","Sibernot","Mekanoid"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Çitlerin Ötesinde''deki RJ hangi tür hayvandır?', '["Rakun","Kokarca","Porsuk","Kirpi"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Kuzuların Sessizliği'' filminin uyarlandığı kitabın yazarı kimdir?', '["Thomas Harris","Winston Groom","John le Carré","Stephen King"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Tutku'' (The Passion of the Christ) filminde konuşulan başlıca antik Sami dili hangisidir?', '["Aramice","Arapça","Akadca","Fenikece"]'::jsonb, 0, 'sinema', 'global', null, 3),
('Salvador Dalí ile Luis Buñuel''in birlikte yaptığı 1929 kısa filminin adı nedir?', '["Bir Endülüs Köpeği","Suyun Kızı","Akşam Ziyaretçileri","Bir Kır Gezisi"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Kahraman'' (Hero, 2002) filminde Adı Olmayan savaşçının hikâyesini anlattığı hükümdar hangi devletin kralıdır?', '["Qin","Han","Tang","Song"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''127 Saat''te Aron''un kolunu sıkıştıran nesne nedir?', '["Kaya","Devrilmiş ağaç","Metal kiriş","Buz kütlesi"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Geceyarısı Paris''te Gil''in gece yolculuklarında karşılaştığı sanatçılar ağırlıkla hangi on yıldandır?', '["1920''ler","1910''lar","1930''lar","1940''lar"]'::jsonb, 0, 'sinema', 'global', null, 3),
('Pizza Margherita için geleneksel olarak hangi peynir kullanılır?', '["Mozzarella","Mascarpone","Gorgonzola","Roquefort"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Yunan salatası için geleneksel olarak hangi peynir kullanılır?', '["Feta","Ricotta","Cheddar","Gruyère"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Farfalle makarnası hangi biçimdedir?', '["Kelebek","Kısa tüp","Burgu","Küçük kulak"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Çin Yeni Yılı''nda para hediye etme geleneğinde hangi nesne öne çıkar?', '["Kırmızı zarf","İç içe bebek","Kâğıt turna","Çiçek çelengi"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Noel''de altında öpüşme geleneği için hangi bitki sembol olarak kullanılır?', '["Ökseotu","Çobanpüskülü","Çam dalı","Sarmaşık"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Jenga oyununu tasarlayan kişi kimdir?', '["Leslie Scott","Alfred Butts","Elizabeth Magie","Reiner Knizia"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Qantas markasının ambleminde hangi hayvan görülür?', '["Kanguru","Penguen","Timsah","Jaguar"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Tac Mahal''in ana yapısını çevreleyen kaç minare vardır?', '["4","2","3","5"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Geleneksel Çin düğünlerinde gelinin giydiği baskın renk hangisidir?', '["Kırmızı","Lacivert","Zümrüt yeşili","Altın sarısı"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Pavlova tatlısı adını hangi meslekten bir kadından alır?', '["Balerin","Opera şarkıcısı","Sinema oyuncusu","Roman yazarı"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Standart Monopoly tahtasında her turda yeniden geçilen köşenin adı nedir?', '["Başla","Ücretsiz Park","Hapis","Hapse Gir"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Gideon Sundback''ın geliştirdiği günlük giysi kapatma parçası hangisidir?', '["Fermuar","Cırt cırt","Çıtçıt","Kopça"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kore''nin ''baechu kimchi'' türünün ana sebzesi hangisidir?', '["Çin lahanası","Beyaz lahana","Kara lahana","Taze soğan"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Alman sauerkraut geleneksel olarak hangi sebzeden yapılır?', '["Lahana","Karnabahar","Brokoli","Kereviz"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Bagel hamuru fırına verilmeden önce hangi işlemden geçirilir?', '["Suda haşlanır","Yağda kızartılır","Buharda pişirilir","Izgarada çevrilir"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İspanyol paella geleneksel olarak hangi tür kapta pişirilir?', '["Sığ tava","Derin çömlek","Buhar sepeti","Döküm tencere"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Japon wasabi ezmesi genellikle hangi renktedir?', '["Yeşil","Kırmızı","Sarı","Beyaz"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Meksika tamales''i geleneksel olarak pişirilirken sık kullanılan sarma malzemesi hangisidir?', '["Mısır yaprağı","Üzüm yaprağı","Lahana yaprağı","Marul yaprağı"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Birleşmiş Milletler amblemindeki dünya haritasını hangi bitkinin dalları çevreler?', '["Zeytin","Defne","Palmiye","Okaliptüs"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İrlanda geleneğinde leprechaun''un hazinesi hangi nesnede saklanır?', '["Altın dolu kap","Gümüş dolu sandık","Taş dolu torba","İnci dolu kutu"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Japon kimonosundaki obi vücudun hangi bölümüne bağlanır?', '["Bel","Boyun","Baş","Ayak bileği"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Trivial Pursuit''te oyuncuların topladığı renkli parçalar hangi biçimdedir?', '["Dilim","Halka","Küp","Silindir"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik Scrabble tahtası her kenarda kaç kareden oluşur?', '["15","12","14","16"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('İrlanda''nın euro madeni paralarının ulusal yüzünde hangi çalgı vardır?', '["Arp","Keman","Gayda","Akordeon"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Çin''in Ay Festivali''nde geleneksel olarak hangi tatlı hediye edilir?', '["Ay çöreği","Pirinç pudingi","Susam helvası","Muzlu kek"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Fransız ''galette des rois'' pastasındaki küçük figürü bulan kişi başına ne takar?', '["Taç","Başbandı","Kasket","Şapka"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Tayland''ın Loy Krathong festivalinde suya bırakılan geleneksel nesne hangisidir?', '["Çiçekli sepet","Kâğıt kandil","Bambu yelpaze","Kumaş bayrak"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Alman Polterabend geleneğinde düğün öncesi uğur için ne kırılır?', '["Porselen","Cam bardak","Ahşap kaşık","Metal tepsi"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Japon senbazuru geleneğinde hangi nesne öne çıkar?', '["Kâğıt turna","Renkli toz","İç içe bebek","Kırmızı zarf"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Antik Olimpiyat galiplerinin tacı hangi bitkiden yapılırdı?', '["Zeytin dalı","Defne dalı","Meşe dalı","Palmiye dalı"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('İngilizce Scrabble setinde boş taşın puan değeri kaçtır?', '["0","1","2","3"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('San Francisco''daki Golden Gate Köprüsü''nün boya rengi hangi adla bilinir?', '["International Orange","International Red","International Yellow","International Blue"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Japonya''da yıl sonunda geleneksel olarak 108 kez çalınan nesne hangisidir?', '["Tapınak çanı","Taiko davulu","Bambu flüt","Metal gong"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Standart mahjong taşlarında bambu ve çember yanında üçüncü sayı grubu hangisidir?', '["Karakterler","Çiçek taşları","Rüzgâr taşları","Ejderha taşları"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Hanuka için kullanılan hanukiyada yardımcı mum dahil kaç mum yeri vardır?', '["9","7","8","10"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Japon daruma bebeğinde bir dilek tutulurken ilk olarak hangi bölüm boyanır?', '["Bir göz","Ağız","Bir kulak","Burun"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('İskoç quaich içki kabının karşılıklı kaç sapı vardır?', '["2","1","3","4"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Japon koi balığı biçimli koinobori süsleri hangi bayramda asılır?', '["Çocuklar Günü","Yeni Yıl","Yaşlılara Saygı Günü","Deniz Günü"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Japon kintsugi geleneğinde hangi eşyaların kırıkları altın renkli birleşimlerle onarılır?', '["Seramik kaplar","Ahşap oyuncaklar","Deri çantalar","Kumaş giysiler"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Japon furoshiki geleneğinde nesneler hangi malzemeyle sarılır?', '["Kumaş","Kâğıt","Deri","Hasır"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('İtalyan ''colomba'' Paskalya keki hangi kuşun biçimindedir?', '["Güvercin","Kuğu","Tavus kuşu","Horoz"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Yeşilin Kızı Anne'' kitabının yazarı kimdir?', '["L. M. Montgomery","Louisa May Alcott","Frances Hodgson Burnett","Johanna Spyri"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Bülbülü Öldürmek''teki Atticus Finch karakterinin mesleği nedir?', '["Avukat","Doktor","Denizci","Mimar"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Fahrenheit 451''deki Guy Montag karakterinin mesleği nedir?', '["İtfaiyeci","Mürebbiye","Öğretmen","Gazeteci"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Orman Kitabı''ndaki Baloo hangi tür hayvandır?', '["Ayı","At","Fare","Kurt"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Heathcliff hangi romandaki karakterdir?', '["Uğultulu Tepeler","Gurur ve Önyargı","Büyük Umutlar","Oliver Twist"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Mr Darcy hangi romandaki karakterdir?', '["Gurur ve Önyargı","Uğultulu Tepeler","Büyük Umutlar","Dorian Gray''in Portresi"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Long John Silver hangi romandaki karakterdir?', '["Define Adası","Oliver Twist","Frankenstein","Büyük Gatsby"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Watership Tepesi'' kitabının yazarı kimdir?', '["Richard Adams","Philip Pullman","Diana Wynne Jones","Michael Morpurgo"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Ray Bradbury''nin romanı ''Fahrenheit 451''de 451 sayısı hangi malzemenin tutuşma sıcaklığına gönderme yapar?', '["Kâğıt","Tahta","Kumaş","Plastik"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Hobbit''te Bilbo''nun cücelerle birlikte gittiği dağın adı nedir?', '["Yalnız Dağ","Sisli Dağlar","Hüküm Dağı","Demir Tepeler"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Tom Sawyer''ın Maceraları''nda Tom''u büyüten kadının adı nedir?', '["Polly","Sally","Betsy","Clara"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Charlotte ve Emily Brontë''nin romancı olan kız kardeşleri kimdir?', '["Anne","Maria","Elizabeth","Mary"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Robinson Crusoe'' kurtardığı adama hangi günün adını verir?', '["Cuma","Pazartesi","Çarşamba","Pazar"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Harry Potter''da Fleur Delacour hangi okulda okur?', '["Beauxbatons","Durmstrang","Ilvermorny","Castelobruxo"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Antoine de Saint-Exupéry ''Küçük Prens''i hangi arkadaşına ithaf etmiştir?', '["Léon Werth","André Malraux","Jean-Richard Bloch","Paul Éluard"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Dönüşüm''de Gregor Samsa''nın işe giderken yetişmesi gereken taşıt hangisidir?', '["Tren","Otobüs","Tramvay","Vapur"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Dünyanın Merkezine Yolculuk''ta profesörün eski kitabında bulunan gizli mesaj hangi yazıyla yazılmıştır?', '["Runik yazı","Hiyeroglif","Çivi yazısı","Brahmi yazısı"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''İki Şehrin Hikâyesi''nde Dr. Manette hapiste hangi zanaatı öğrenmiştir?', '["Ayakkabıcılık","Saat tamirciliği","Kitap ciltçiliği","Marangozluk"]'::jsonb, 0, 'edebiyat', 'global', null, 3)
on conflict (soru) do nothing;

-- ---------------------------------------------------- İngilizce çeviri
insert into public.question_translations (question_id, dil, soru, secenekler)
select q.id, 'en', v.en_soru, v.en_secenekler
  from (values
  ('Botticelli''nin ''İlkbahar''ını görmek isteyen biri hangi müzeyi ziyaret etmelidir?', 'Which museum holds Botticelli''s ''Primavera''?', '["Uffizi","Louvre","Prado","MoMA"]'::jsonb),
  ('Van Gogh''un kardeşi Theo hangi mesleği yapıyordu?', 'What was Vincent van Gogh''s brother Theo''s profession?', '["Art dealer","Newspaper editor","Orchestra conductor","Stage actor"]'::jsonb),
  ('Yayoi Kusama''nın resim ve heykellerinde sık kullandığı desen hangisidir?', 'Which pattern frequently appears in Yayoi Kusama''s paintings and sculptures?', '["Polka dots","Zigzag lines","Spiral lines","Square grids"]'::jsonb),
  ('Keith Haring''in ''Radiant Baby'' figüründe bebek hangi pozisyondadır?', 'What is the baby doing in Keith Haring''s ''Radiant Baby'' figure?', '["Crawling","Sitting","Standing upright","Lying down"]'::jsonb),
  ('Jeff Koons''un Bilbao''daki ''Puppy'' heykelinin yüzeyi neyle kaplıdır?', 'What covers the surface of Jeff Koons''s ''Puppy'' in Bilbao?', '["Living flowers","Coloured glass","Metal plates","Wooden pieces"]'::jsonb),
  ('Frida Kahlo’nun Meksiko’daki müze evinin dış duvarlarının baskın rengi hangisidir?', 'What is the dominant colour of the exterior walls of Frida Kahlo''s museum house in Mexico City?', '["Blue","Red","Yellow","Green"]'::jsonb),
  ('Rodin''in ''Öpücük'' heykelindeki iki figür hangi konumdadır?', 'How are the two figures positioned in Rodin''s ''The Kiss''?', '["Seated in an embrace","Standing hand in hand","Walking side by side","Sitting back to back"]'::jsonb),
  ('''Kuğu Gölü'' balesinde kuğuya dönüştürülen prensesin adı nedir?', 'What is the name of the princess turned into a swan in ''Swan Lake''?', '["Odette","Aurora","Giselle","Clara"]'::jsonb),
  ('Toulouse-Lautrec''in Moulin Rouge afişleri en çok hangi sahne sanatını konu alır?', 'What performing art is most associated with Toulouse-Lautrec''s Moulin Rouge posters?', '["Dance","Opera","Pantomime","Puppet theatre"]'::jsonb),
  ('Goya''nın kraliyet fabrikası için hazırladığı renkli tasarımlar hangi ürünün dokunmasında kullanıldı?', 'What woven product was made using Goya''s designs for the royal factory?', '["Tapestry","Tablecloth","Upholstery fabric","Palace curtain"]'::jsonb),
  ('Vermeer''in ''Sütçü Kız'' tablosundaki kadının üst giysisinin baskın rengi nedir?', 'What is the dominant colour of the woman''s upper garment in Vermeer''s ''The Milkmaid''?', '["Yellow","Red","Green","Navy blue"]'::jsonb),
  ('Wyeth''in “Christina''nın Dünyası” tablosundaki kadın hangi açık alanda görülür?', 'In what open setting is the woman shown in Wyeth''s ''Christina''s World''?', '["Meadow","Forest","Beach","Town square"]'::jsonb),
  ('''West Side Story''de Jets çetesinin rakibi olan çetenin adı nedir?', 'What is the name of the Jets'' rival gang in the stage musical ''West Side Story''?', '["Sharks","Tigers","Eagles","Panthers"]'::jsonb),
  ('''Chicago'' sahne müzikalinin kadın baş karakterlerinden Roxie''nin soyadı nedir?', 'What is Roxie''s surname in the stage musical ''Chicago''?', '["Hart","Kelly","Morton","Sunshine"]'::jsonb),
  ('''Cabaret'' sahne müzikalindeki gece kulübünün adı nedir?', 'What is the nightclub called in the stage musical ''Cabaret''?', '["Kit Kat Club","Moulin Rouge","Crazy Horse","Folies Bergère"]'::jsonb),
  ('Rodin''in ''Calais Burjuvaları'' heykel grubu kaç insan figüründen oluşur?', 'How many human figures form Rodin''s ''The Burghers of Calais''?', '["6","4","5","7"]'::jsonb),
  ('New York''taki Flatiron Binası''nın planı hangi geometrik şekli andırır?', 'Which geometric shape does the plan of New York''s Flatiron Building resemble?', '["Triangle","Rectangle","Pentagon","Circle"]'::jsonb),
  ('Seurat''nın “La Grande Jatte Adası''nda Bir Pazar Öğleden Sonra” tablosunda hangi ortam görülür?', 'What setting appears in Seurat''s ''A Sunday Afternoon on the Island of La Grande Jatte''?', '["Riverside park","Seaside harbour","Mountain village","City-centre market"]'::jsonb),
  ('''Annie'' sahne müzikalinin başkahramanı başlangıçta nerede yaşar?', 'Where does the title character live at the start of the stage musical ''Annie''?', '["Orphanage","Boarding school","Farmhouse","Circus camp"]'::jsonb),
  ('Habitat 67 tasarımını yapan mimar kimdir?', 'Who designed Habitat 67?', '["Moshe Safdie","Le Corbusier","Antoni Gaudí","Alvar Aalto"]'::jsonb),
  ('Vitra İtfaiye İstasyonu tasarımını yapan mimar kimdir?', 'Who designed the Vitra Fire Station?', '["Zaha Hadid","Louis Kahn","Jørn Utzon","Tadao Ando"]'::jsonb),
  ('Lloyd''s of London binası tasarımını yapan mimar kimdir?', 'Who designed the Lloyd''s of London building?', '["Richard Rogers","Walter Gropius","Oscar Niemeyer","Eero Saarinen"]'::jsonb),
  ('Bernini''nin ''Apollon ve Dafne'' heykelinin ana malzemesi hangisidir?', 'What is the main material of Bernini''s ''Apollo and Daphne''?', '["Marble","Granite","Basalt","Bronze"]'::jsonb),
  ('Winston Churchill''in ''Kükreyen Aslan'' portresini çeken fotoğrafçı kimdir?', 'Who took ''The Roaring Lion'' portrait of Winston Churchill?', '["Yousuf Karsh","Alfred Eisenstaedt","Robert Capa","Ansel Adams"]'::jsonb),
  ('Umberto Boccioni hangi sanat akımının önde gelen temsilcilerindendir?', 'Which art movement is closely associated with Umberto Boccioni?', '["Futurism","Pop art","Romanticism","Cubism"]'::jsonb),
  ('Venedik Bienali''ndeki Arsenale yapıları başlangıçta ne olarak kullanılıyordu?', 'What was Venice''s Arsenale originally used as?', '["Shipyard","Railway station","Power station","Textile factory"]'::jsonb),
  ('Man Ray''in nesneleri ışığa duyarlı kâğıda koyarak yaptığı fotoğraflar hangi adla anılır?', 'What did Man Ray call his photographs made by placing objects on light-sensitive paper?', '["Rayograph","Daguerreotype","Ambrotype","Tintype"]'::jsonb),
  ('Christo''nun büyük ölçekli projelerinde 2009''a kadar ortak çalıştığı eşi kimdir?', 'Who was Christo''s wife and collaborator on his large-scale projects until 2009?', '["Jeanne-Claude","Niki de Saint Phalle","Sonia Delaunay","Louise Bourgeois"]'::jsonb),
  ('Christine McVie hangi grubun üyesiydi?', 'Which band was Christine McVie a member of?', '["Fleetwood Mac","Black Sabbath","Led Zeppelin","Dire Straits"]'::jsonb),
  ('Tony Iommi hangi grubun üyesiydi?', 'Which band was Tony Iommi a member of?', '["Black Sabbath","Fleetwood Mac","Led Zeppelin","Dire Straits"]'::jsonb),
  ('Buddy Rich en çok hangi enstrümanla tanınır?', 'Which instrument is Buddy Rich best known for playing?', '["Drums","Keyboards","Guitar","Violin"]'::jsonb),
  ('''The Joshua Tree'' albümü hangi gruba aittir?', 'Which band released ''The Joshua Tree''?', '["U2","Yes","ABBA","Blur"]'::jsonb),
  ('''Madama Butterfly'' operasını kim bestelemiştir?', 'Who composed the opera ''Madama Butterfly''?', '["Giacomo Puccini","Richard Strauss","Giuseppe Verdi","Richard Wagner"]'::jsonb),
  ('''While My Guitar Gently Weeps'' şarkısı ilk olarak hangi albümde yayımlandı?', 'Which album first featured ''While My Guitar Gently Weeps''?', '["The White Album","Please Please Me","With the Beatles","A Hard Day’s Night"]'::jsonb),
  ('''Nothing Compares 2 U'' şarkısını yazan müzisyen kimdir?', 'Which musician wrote ''Nothing Compares 2 U''?', '["Prince","George Michael","David Bowie","Stevie Wonder"]'::jsonb),
  ('Queen''in ''Under Pressure'' kaydında Freddie Mercury ile düet yapan kimdir?', 'Who sings a duet with Freddie Mercury on Queen''s ''Under Pressure''?', '["David Bowie","Elton John","Mick Jagger","Rod Stewart"]'::jsonb),
  ('Eminem''in ''Stan'' şarkısında hangi şarkıcının ''Thank You'' kaydı örneklenir?', 'Whose recording of ''Thank You'' is sampled in Eminem''s ''Stan''?', '["Dido","Enya","Sade","Sarah McLachlan"]'::jsonb),
  ('Bee Gees''teki Robin''in ikiz kardeşi olan üye kimdir?', 'Which member of the Bee Gees was Robin''s twin brother?', '["Maurice Gibb","Barry Gibb","Andy Gibb","Colin Petersen"]'::jsonb),
  ('The Beatles''ın son halka açık konseri 1969''da hangi yerde yapıldı?', 'Where did the Beatles give their final public performance in 1969?', '["Building rooftop","Railway platform","Hotel lobby","Cinema auditorium"]'::jsonb),
  ('''Don''t Go Breaking My Heart''ta Elton John''un düet partneri kimdir?', 'Who duets with Elton John on ''Don''t Go Breaking My Heart''?', '["Kiki Dee","Dusty Springfield","Bonnie Tyler","Kate Bush"]'::jsonb),
  ('''Tosca'' operasında Cavaradossi hangi sanat dalıyla uğraşır?', 'What art does Cavaradossi practise in the opera ''Tosca''?', '["Painting","Sculpture","Music","Theatre"]'::jsonb),
  ('Mozart''ın ''Sihirli Flüt'' operasındaki Gece Kraliçesi rolü hangi ses türü için yazılmıştır?', 'What voice type is the Queen of the Night role in Mozart''s ''The Magic Flute'' written for?', '["Soprano","Contralto","Tenor","Baritone"]'::jsonb),
  ('Freddie Mercury''nin rock kariyerinden önce eğitimini aldığı görsel alan hangisidir?', 'Which visual field did Freddie Mercury study before his rock career?', '["Graphic design","Fashion design","Industrial design","Interior design"]'::jsonb),
  ('Puccini''nin ''La bohème'' operasında Rodolfo''nun âşık olduğu genç kadın kimdir?', 'Who is the young woman Rodolfo falls in love with in Puccini''s ''La bohème''?', '["Mimì","Musetta","Tosca","Butterfly"]'::jsonb),
  ('Bizet''nin ''Carmen'' operasında Carmen''in âşık olduğu boğa güreşçisi kimdir?', 'Which bullfighter does Carmen fall in love with in Bizet''s opera?', '["Escamillo","Don José","Le Remendado","Dancaïre"]'::jsonb),
  ('Beethoven''ın Beşinci Senfonisi''nin ünlü açılış motifinde kaç nota vardır?', 'How many notes form the famous opening motif of Beethoven''s Fifth Symphony?', '["4","3","5","6"]'::jsonb),
  ('ZX Spectrum hangi şirket tarafından üretilmiştir?', 'Which company made ZX Spectrum?', '["Sinclair Research","Texas Instruments","Hewlett-Packard","Microsoft"]'::jsonb),
  ('Sega Dreamcast, Japonya''da hangi yıl piyasaya çıktı?', 'In which year was the Sega Dreamcast released in Japan?', '["1998","1997","1999","2001"]'::jsonb),
  ('Google''ın Chrome tarayıcısı hangi yıl piyasaya çıktı?', 'In which year was Google Chrome released?', '["2008","2007","2009","2011"]'::jsonb),
  ('''Stardew Valley'' oyununu geliştiren kişi kimdir?', 'Who developed ''Stardew Valley''?', '["Eric Barone","Toby Fox","Lucas Pope","Daniel Mullins"]'::jsonb),
  ('Adobe Photoshop 1.0 ilk kez hangi yıl yayımlandı?', 'In which year was Adobe Photoshop 1.0 released?', '["1990","1989","1991","1993"]'::jsonb),
  ('Nintendo Switch ilk kez hangi yıl yayımlandı?', 'In which year was Nintendo Switch released?', '["2017","2015","2016","2019"]'::jsonb),
  ('Cassini''nin Titan''a indirdiği sondanın adı nedir?', 'What was the name of the probe Cassini delivered to Titan?', '["Huygens","Philae","Deep Space 2","MINERVA"]'::jsonb),
  ('Ethernet''in ilk çalışmalarının yapıldığı PARC hangi şirkete aitti?', 'Which company owned PARC, where the original Ethernet work was done?', '["Xerox","Adobe","Intel","Nokia"]'::jsonb),
  ('Standart RJ45 Ethernet fişinde kaç temas ucu vardır?', 'How many contacts does a standard RJ45 Ethernet plug have?', '["8","4","6","10"]'::jsonb),
  ('İlk uzay mekiği uçuşu STS-1 hangi mekikle yapıldı?', 'Which shuttle flew the first space-shuttle mission, STS-1?', '["Columbia","Discovery","Atlantis","Endeavour"]'::jsonb),
  ('Java dili, Oracle satın almadan önce hangi şirkette geliştirildi?', 'At which company was Java developed before Oracle acquired it?', '["Sun Microsystems","Silicon Graphics","Digital Equipment","Hewlett-Packard"]'::jsonb),
  ('2012''de Mars''a inen ve ''Sky Crane'' sistemiyle bırakılan keşif robotu hangisidir?', 'Which rover landed on Mars in 2012 using the ''Sky Crane'' system?', '["Curiosity","Opportunity","Sojourner","Spirit"]'::jsonb),
  ('NASA''nın 2004''te Mars''a indirdiği Spirit''in ikiz keşif robotu hangisidir?', 'Which rover was Spirit''s twin in NASA''s 2004 Mars mission?', '["Opportunity","Curiosity","Sojourner","Perseverance"]'::jsonb),
  ('İnternetteki ilk YouTube videosunda Jawed Karim hangi tür yerde görülür?', 'What kind of place appears in the first YouTube video featuring Jawed Karim?', '["Zoo","Amusement park","Railway station","Shopping mall"]'::jsonb),
  ('1990''larda yaygınlaşan sert plastik gövdeli küçük disketin çapı kaç inçti?', 'What was the diameter in inches of the small rigid-plastic floppy disk popular in the 1990s?', '["3.5","2.5","4.5","5.5"]'::jsonb),
  ('1990''ların iMac G3 bilgisayarında sistem birimi hangi parçayla aynı kasadaydı?', 'Which component shared a case with the system unit in the iMac G3? ', '["Display","Printer","Scanner","Speaker stand"]'::jsonb),
  ('Apple''ın 2016''da tanıttığı kablosuz kulaklık serisinin adı nedir?', 'What wireless earphone series did Apple introduce in 2016?', '["AirPods","EarPods","Beats Studio","Powerbeats"]'::jsonb),
  ('Amazon Kindle''ın ilk modellerinde kullanılan kâğıda benzeyen ekran teknolojisi hangisidir?', 'What paper-like display technology was used in the earliest Amazon Kindle models?', '["Electronic ink","Plasma display panel","Cathode-ray tube","Liquid-crystal display"]'::jsonb),
  ('BlackBerry telefonları klasik modellerinde hangi fiziksel özelliğiyle tanınmıştır?', 'What physical feature were classic BlackBerry phones known for?', '["QWERTY keyboard","Numeric rotary dial","Only directional keys","Detachable gamepad"]'::jsonb),
  ('Apple iPod''un klasik modellerindeki dairesel kontrol yüzeyinin adı nedir?', 'What is the circular control surface on classic Apple iPod models called?', '["Click Wheel","Magic Trackpad","Touch Bar","Digital Crown"]'::jsonb),
  ('Atari 2600''ün oyunları konsola hangi fiziksel ortamda takılırdı?', 'What physical medium was plugged into the Atari 2600 to load games?', '["Cartridge","Floppy disk","CD-ROM","DVD-ROM"]'::jsonb),
  ('ThinkPad klavyelerindeki kırmızı işaretleme çubuğunun adı nedir?', 'What is the red pointing stick in ThinkPad keyboards called?', '["TrackPoint","Trackball","TouchPad","Magic Mouse"]'::jsonb),
  ('NASA''nın Apollo Ay modülleri inişte kaç ayağa dayanıyordu?', 'How many legs supported NASA''s Apollo lunar modules on landing?', '["4","3","5","6"]'::jsonb),
  ('Sputnik 1''in gövdesi hangi geometrik biçimdeydi?', 'What geometric shape was Sputnik 1''s body? ', '["Sphere","Cube","Cylinder","Cone"]'::jsonb),
  ('Microsoft Kinect aygıtı geliştirilirken hangi kod adı kullanıldı?', 'What was the development codename for Microsoft Kinect?', '["Project Natal","Project Scorpio","Revolution","Project Morpheus"]'::jsonb),
  ('1998''de tanıtılan ilk iMac''in mavi tonu hangi adla pazarlandı?', 'What was the marketed name of the blue colour of the first iMac introduced in 1998?', '["Bondi Blue","Pacific Blue","Ocean Blue","Midnight Blue"]'::jsonb),
  ('1984''teki ilk Macintosh''ta hangi şirketin 68000 işlemcisi kullanılmıştır?', 'Which company made the 68000 processor in the original 1984 Macintosh?', '["Motorola","National Semiconductor","Texas Instruments","Intel"]'::jsonb),
  ('1947''de Harvard Mark II''de bulunan ve hata günlüğüne yapıştırılan böcek hangisiydi?', 'What insect was found in the Harvard Mark II in 1947 and taped into its log?', '["Moth","Ant","Fly","Cockroach"]'::jsonb),
  ('Adobe şirketinin adı kuruculardan birinin evinin yanındaki hangi doğal oluşumdan alınmıştır?', 'Adobe was named after what natural feature near a founder''s home?', '["Creek","Cave","Ocean","Hill"]'::jsonb),
  ('İlk Photoshop sürümü başlangıçta hangi bilgisayar platformu için yayımlandı?', 'For which computer platform was the first version of Photoshop initially released?', '["Macintosh","Windows PC","Amiga","Atari ST"]'::jsonb),
  ('eBay''deki ilk satışta Pierre Omidyar''ın sattığı bozuk nesne neydi?', 'What broken object did Pierre Omidyar sell in eBay''s first sale?', '["Laser pointer","Pocket calculator","Portable radio","Digital wristwatch"]'::jsonb),
  ('Uluslararası Uzay İstasyonu''nun 1998''de fırlatılan ilk modülü hangisidir?', 'Which was the first International Space Station module, launched in 1998?', '["Zarya","Zvezda","Unity","Destiny"]'::jsonb),
  ('Hewlett-Packard''ın ilk ticari ürünü hangi tür cihazdı?', 'What type of device was Hewlett-Packard''s first commercial product?', '["Audio oscillator","Radio receiver","Camera","Mechanical calculator"]'::jsonb),
  ('Apple''ın 1977''deki ısırılmış elma logosunu tasarlayan kişi kimdir?', 'Who designed Apple''s bitten-apple logo in 1977?', '["Rob Janoff","Ronald Wayne","Paul Rand","Susan Kare"]'::jsonb),
  ('Carl Lewis hangi spor dalıyla tanınır?', 'Which sport is Carl Lewis known for?', '["Athletics","Cycling","Basketball","Baseball"]'::jsonb),
  ('Lin Dan hangi spor dalıyla tanınır?', 'Which sport is Lin Dan known for?', '["Badminton","Table tennis","Tennis","Squash"]'::jsonb),
  ('Anfield hangi futbol kulübünün stadıdır?', 'Which football club plays at Anfield?', '["Liverpool","Barcelona","Feyenoord","Juventus"]'::jsonb),
  ('Santiago Bernabéu hangi futbol kulübünün stadıdır?', 'Which football club plays at Santiago Bernabéu?', '["Real Madrid","Inter Milan","Barcelona","Liverpool"]'::jsonb),
  ('Camp Nou hangi futbol kulübünün stadıdır?', 'Which football club plays at Camp Nou?', '["Barcelona","Liverpool","Feyenoord","Juventus"]'::jsonb),
  ('Claret Jug hangi spor dalında verilen bir kupadır?', 'In which sport is the Claret Jug awarded?', '["Golf","Boxing","Tennis","Swimming"]'::jsonb),
  ('Magic Johnson hangi forma numarasıyla özdeşleşmiştir?', 'Which jersey number is closely associated with Magic Johnson?', '["32","31","33","34"]'::jsonb),
  ('Larry Bird hangi forma numarasıyla özdeşleşmiştir?', 'Which jersey number is closely associated with Larry Bird?', '["33","32","34","35"]'::jsonb),
  ('Paolo Maldini''nin AC Milan dönemi hangi forma numarasıyla özdeşleşmiştir?', 'Which jersey number is closely associated with Paolo Maldini at AC Milan?', '["3","7","8","9"]'::jsonb),
  ('Kobe Bryant''ın ilk Lakers yılları hangi forma numarasıyla özdeşleşmiştir?', 'Which jersey number is closely associated with Kobe Bryant''s early Lakers years?', '["8","3","7","9"]'::jsonb),
  ('Shaun White hangi spor dalıyla tanınır?', 'Which sport is Shaun White known for?', '["Snowboarding","Ski jumping","Freestyle skiing","Alpine skiing"]'::jsonb),
  ('Cruyff dönüşü hareketi hangi spor dalında kullanılır?', 'In which sport is the Cruyff turn used?', '["Football","Fencing","Cricket","Weightlifting"]'::jsonb),
  ('''Toprak Kortların Kralı'' lakabıyla tanınan tenisçi kimdir?', 'Which tennis player is known as the ''King of Clay''?', '["Rafael Nadal","Novak Djokovic","Roger Federer","Juan Carlos Ferrero"]'::jsonb),
  ('''The Dream'' lakabıyla tanınan NBA pivotu kimdir?', 'Which NBA centre was nicknamed ''The Dream''?', '["Hakeem Olajuwon","Dikembe Mutombo","Patrick Ewing","David Robinson"]'::jsonb),
  ('1973''teki ''Battle of the Sexes'' maçında Billie Jean King''in rakibi kimdi?', 'Who was Billie Jean King''s opponent in the 1973 ''Battle of the Sexes''?', '["Bobby Riggs","Jack Kramer","Pancho Gonzales","Roy Emerson"]'::jsonb),
  ('Chicago Bulls''un 1990''lardaki şampiyonluklarında koç kimdi?', 'Who coached the Chicago Bulls during their championship years in the 1990s?', '["Phil Jackson","Pat Riley","Chuck Daly","Gregg Popovich"]'::jsonb),
  ('Lewis Hamilton''ın ilk Formula 1 şampiyonluğu hangi yılda gerçekleşti?', 'In which year did Lewis Hamilton win his first Formula One title?', '["2008","2007","2009","2011"]'::jsonb),
  ('Thierry Henry, Arsenal''e transfer olmadan hemen önce hangi kulüpteydi?', 'Which club was Thierry Henry at immediately before joining Arsenal?', '["Juventus","Inter Milan","AC Milan","Fiorentina"]'::jsonb),
  ('Nadia Comăneci olimpiyatlarda ilk tam 10 puanını hangi jimnastik aletinde aldı?', 'On which apparatus did Nadia Comăneci receive the first Olympic perfect 10?', '["Uneven bars","Floor exercise","Vaulting horse","Balance beam"]'::jsonb),
  ('Wimbledon erkekler tekler kupasının tepesinde hangi meyve figürü vardır?', 'Which fruit appears on top of the Wimbledon men''s singles trophy?', '["Pineapple","Pomegranate","Apple","Orange"]'::jsonb),
  ('Juventus siyah-beyaz formalarını hangi İngiliz kulübünden esinlenerek benimsemiştir?', 'Which English club inspired Juventus''s black-and-white shirts?', '["Notts County","Derby County","Newcastle United","Sunderland"]'::jsonb),
  ('Bob Beamon 1968 Mexico City''de 8,90 metre ile hangi atletizm dalında olimpiyat şampiyonu oldu?', 'In which event did Bob Beamon win Olympic gold with 8.90 metres at Mexico City in 1968?', '["Long jump","Triple jump","High jump","Pole vault"]'::jsonb),
  ('1998 Dünya Kupası''nı kazanan Fransa''nın teknik direktörü kimdi?', 'Who coached France to victory at the 1998 World Cup?', '["Aimé Jacquet","Roger Lemerre","Gérard Houllier","Didier Deschamps"]'::jsonb),
  ('Michael Jordan''ın 1997 NBA finali altıncı maçta galibiyet basketi için pas verdiği takım arkadaşı kimdi?', 'Who received Michael Jordan''s pass for the winning shot in Game 6 of the 1997 NBA Finals?', '["Steve Kerr","John Paxson","Ron Harper","Toni Kukoč"]'::jsonb),
  ('1773 Boston protestosunda denize atılan ticari yük neydi?', 'What cargo was thrown into the sea during the 1773 Boston protest?', '["Tea","Tobacco","Sugar","Coffee"]'::jsonb),
  ('Titanic''in 1912''deki kaptanının soyadı nedir?', 'What was the surname of the Titanic''s captain in 1912?', '["Smith","Rostron","Lord","Lightoller"]'::jsonb),
  ('İngiltere Kralı VIII. Henry''nin ilk eşi kimdir?', 'Who was King Henry VIII of England''s first wife?', '["Catherine of Aragon","Catherine of Austria","Anne Boleyn","Jane Seymour"]'::jsonb),
  ('ABD''nin Savunma Bakanlığı binasına adını veren geometrik şekil hangisidir?', 'Which geometric shape gives the US Department of Defense building its name?', '["Pentagon","Hexagon","Quadrilateral","Octagon"]'::jsonb),
  ('Roma İmparatoru Nero''nun gençlik dönemindeki Stoacı öğretmeni kimdir?', 'Who was the Stoic tutor of the young Roman emperor Nero?', '["Seneca","Musonius Rufus","Epictetus","Hierocles"]'::jsonb),
  ('''Altıncı His'' filmini kim yönetmiştir?', 'Who directed ''The Sixth Sense''?', '["M. Night Shyamalan","Guillermo del Toro","Quentin Tarantino","Christopher Nolan"]'::jsonb),
  ('The Matrix''teki Neo karakterini hangi oyuncu canlandırmıştır?', 'Which actor played Neo in The Matrix?', '["Keanu Reeves","Bruce Willis","Heath Ledger","Hugh Jackman"]'::jsonb),
  ('Harry Potter filmlerindeki Severus Snape karakterini hangi oyuncu canlandırmıştır?', 'Which actor played Severus Snape in the Harry Potter films?', '["Alan Rickman","Ralph Fiennes","Jeremy Irons","Timothy Spall"]'::jsonb),
  ('''Can Dostum''daki Sean Maguire karakterini hangi oyuncu canlandırmıştır?', 'Which actor played Sean Maguire in Good Will Hunting?', '["Robin Williams","Robert De Niro","Morgan Freeman","Dustin Hoffman"]'::jsonb),
  ('''Yüzüklerin Efendisi: Yüzük Kardeşliği'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''The Lord of the Rings: The Fellowship of the Ring''?', '["Howard Shore","Danny Elfman","James Horner","John Williams"]'::jsonb),
  ('''Chariots of Fire'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''Chariots of Fire''?', '["Vangelis","Nino Rota","Hans Zimmer","Danny Elfman"]'::jsonb),
  ('2018 yılında verilen En İyi Film Oscar''ını hangi film kazandı?', 'Which film won Best Picture at the 2018 Academy Awards?', '["The Shape of Water","Dunkirk","Three Billboards Outside Ebbing, Missouri","Lady Bird"]'::jsonb),
  ('Madagascar''daki Kral Julien hangi tür hayvandır?', 'What kind of animal is King Julien in Madagascar?', '["Lemur","Panda","Lion","Fox"]'::jsonb),
  ('''Apollo 13'' filminde görev kontrol merkezi hangi şehirde bulunur?', 'In which city is mission control located in ''Apollo 13''?', '["Houston","Dallas","Austin","San Antonio"]'::jsonb),
  ('''RoboCop'' (1987) filminde Detroit polisini yöneten şirket hangisidir?', 'Which corporation runs Detroit''s police in the 1987 ''RoboCop''?', '["OCP","Weyland-Yutani","Tyrell Corporation","Cyberdyne Systems"]'::jsonb),
  ('''Büyük Lebowski''de Dude ve arkadaşları hangi salon sporunu oynar?', 'What indoor sport do the Dude and his friends play in ''The Big Lebowski''?', '["Bowling","Billiards","Table tennis","Badminton"]'::jsonb),
  ('''Amélie''de babanın süs olarak bahçesine koyduğu figür hangisidir?', 'What ornamental figure does Amélie''s father keep in his garden?', '["Gnome","Flamingo","Tortoise","Frog"]'::jsonb),
  ('''Ucuz Roman''da Vincent ile Mia restoranda birlikte hangi etkinliğe katılır?', 'What do Vincent and Mia enter together at the restaurant in ''Pulp Fiction''?', '["Dance contest","Karaoke contest","Quiz contest","Billiards tournament"]'::jsonb),
  ('''Ölüm Tarlaları'' (The Killing Fields) hangi ülkedeki Kızıl Kmer dönemini anlatır?', 'Which country''s Khmer Rouge era is depicted in ''The Killing Fields''?', '["Cambodia","Bangladesh","Indonesia","Thailand"]'::jsonb),
  ('''Gremlinler''de Gizmo''nun türünün adı nedir?', 'What is Gizmo''s species in ''Gremlins''?', '["Mogwai","Ewok","Wookiee","Tribble"]'::jsonb),
  ('''Bıçak Sırtı'' (1982) filmindeki yapay insanların adı nedir?', 'What are the artificial humans called in the 1982 film ''Blade Runner''?', '["Replicant","Terminator","Cybernaut","Mechanoid"]'::jsonb),
  ('''Çitlerin Ötesinde''deki RJ hangi tür hayvandır?', 'What kind of animal is RJ in Over the Hedge?', '["Raccoon","Skunk","Badger","Porcupine"]'::jsonb),
  ('''Kuzuların Sessizliği'' filminin uyarlandığı kitabın yazarı kimdir?', 'Who wrote the book adapted into ''The Silence of the Lambs''?', '["Thomas Harris","Winston Groom","John le Carré","Stephen King"]'::jsonb),
  ('''Tutku'' (The Passion of the Christ) filminde konuşulan başlıca antik Sami dili hangisidir?', 'What is the main ancient Semitic language spoken in ''The Passion of the Christ''?', '["Aramaic","Arabic","Akkadian","Phoenician"]'::jsonb),
  ('Salvador Dalí ile Luis Buñuel''in birlikte yaptığı 1929 kısa filminin adı nedir?', 'What is the 1929 short film made by Salvador Dalí and Luis Buñuel called?', '["Un Chien Andalou","La Fille de l''eau","Les Visiteurs du Soir","Une partie de campagne"]'::jsonb),
  ('''Kahraman'' (Hero, 2002) filminde Adı Olmayan savaşçının hikâyesini anlattığı hükümdar hangi devletin kralıdır?', 'In ''Hero'' (2002), the Nameless warrior tells his story to the king of which state?', '["Qin","Han","Tang","Song"]'::jsonb),
  ('''127 Saat''te Aron''un kolunu sıkıştıran nesne nedir?', 'What traps Aron''s arm in ''127 Hours''?', '["Boulder","Fallen tree","Metal beam","Block of ice"]'::jsonb),
  ('''Geceyarısı Paris''te Gil''in gece yolculuklarında karşılaştığı sanatçılar ağırlıkla hangi on yıldandır?', 'Which decade are the artists Gil meets on his night-time journeys in ''Midnight in Paris'' mainly from?', '["1920s","1910s","1930s","1940s"]'::jsonb),
  ('Pizza Margherita için geleneksel olarak hangi peynir kullanılır?', 'Which cheese is traditionally used in pizza Margherita?', '["Mozzarella","Mascarpone","Gorgonzola","Roquefort"]'::jsonb),
  ('Yunan salatası için geleneksel olarak hangi peynir kullanılır?', 'Which cheese is traditionally used in Greek salad?', '["Feta","Ricotta","Cheddar","Gruyère"]'::jsonb),
  ('Farfalle makarnası hangi biçimdedir?', 'What shape is farfalle pasta?', '["Bow tie","Short tube","Spiral","Little ear"]'::jsonb),
  ('Çin Yeni Yılı''nda para hediye etme geleneğinde hangi nesne öne çıkar?', 'Which object is closely associated with giving money at Chinese New Year?', '["Red envelope","Nesting dolls","Paper crane","Flower wreath"]'::jsonb),
  ('Noel''de altında öpüşme geleneği için hangi bitki sembol olarak kullanılır?', 'Which plant is a symbol of the Christmas kissing tradition?', '["Mistletoe","Holly","Pine branch","Ivy"]'::jsonb),
  ('Jenga oyununu tasarlayan kişi kimdir?', 'Who designed the game Jenga?', '["Leslie Scott","Alfred Butts","Elizabeth Magie","Reiner Knizia"]'::jsonb),
  ('Qantas markasının ambleminde hangi hayvan görülür?', 'Which animal appears in the Qantas logo?', '["Kangaroo","Penguin","Crocodile","Jaguar"]'::jsonb),
  ('Tac Mahal''in ana yapısını çevreleyen kaç minare vardır?', 'How many minarets surround the main Taj Mahal building?', '["4","2","3","5"]'::jsonb),
  ('Geleneksel Çin düğünlerinde gelinin giydiği baskın renk hangisidir?', 'What is the traditional dominant colour of a Chinese bride''s wedding dress?', '["Red","Navy blue","Emerald green","Golden yellow"]'::jsonb),
  ('Pavlova tatlısı adını hangi meslekten bir kadından alır?', 'The dessert pavlova is named after a woman of which profession?', '["Ballerina","Opera singer","Film actress","Novelist"]'::jsonb),
  ('Standart Monopoly tahtasında her turda yeniden geçilen köşenin adı nedir?', 'What is the corner passed again on every lap of a standard Monopoly board called?', '["GO","FREE PARKING","JAIL","GO TO JAIL"]'::jsonb),
  ('Gideon Sundback''ın geliştirdiği günlük giysi kapatma parçası hangisidir?', 'Which everyday clothing fastener did Gideon Sundback develop?', '["Zipper","Hook-and-loop tape","Snap fastener","Hook and eye"]'::jsonb),
  ('Kore''nin ''baechu kimchi'' türünün ana sebzesi hangisidir?', 'What is the main vegetable in Korean baechu kimchi?', '["Napa cabbage","White cabbage","Kale","Spring onion"]'::jsonb),
  ('Alman sauerkraut geleneksel olarak hangi sebzeden yapılır?', 'Which vegetable is traditionally used to make German sauerkraut?', '["Cabbage","Cauliflower","Broccoli","Celery"]'::jsonb),
  ('Bagel hamuru fırına verilmeden önce hangi işlemden geçirilir?', 'What is done to bagel dough before it is baked?', '["Boiled in water","Deep-fried in oil","Cooked in steam","Grilled over coals"]'::jsonb),
  ('İspanyol paella geleneksel olarak hangi tür kapta pişirilir?', 'In what type of pan is traditional Spanish paella cooked?', '["Shallow pan","Deep earthenware pot","Steamer basket","Cast-iron pot"]'::jsonb),
  ('Japon wasabi ezmesi genellikle hangi renktedir?', 'What colour is Japanese wasabi paste usually?', '["Green","Red","Yellow","White"]'::jsonb),
  ('Meksika tamales''i geleneksel olarak pişirilirken sık kullanılan sarma malzemesi hangisidir?', 'What wrapping is commonly used when cooking traditional Mexican tamales?', '["Corn husk","Grape leaf","Cabbage leaf","Lettuce leaf"]'::jsonb),
  ('Birleşmiş Milletler amblemindeki dünya haritasını hangi bitkinin dalları çevreler?', 'What plant''s branches surround the world map on the United Nations emblem?', '["Olive","Laurel","Palm","Eucalyptus"]'::jsonb),
  ('İrlanda geleneğinde leprechaun''un hazinesi hangi nesnede saklanır?', 'In Irish folklore, what object holds a leprechaun''s treasure?', '["Pot of gold","Chest of silver","Bag of stones","Box of pearls"]'::jsonb),
  ('Japon kimonosundaki obi vücudun hangi bölümüne bağlanır?', 'Around which part of the body is the obi tied on a Japanese kimono?', '["Waist","Neck","Head","Ankle"]'::jsonb),
  ('Trivial Pursuit''te oyuncuların topladığı renkli parçalar hangi biçimdedir?', 'What shape are the coloured pieces collected by players in Trivial Pursuit?', '["Wedge","Ring","Cube","Cylinder"]'::jsonb),
  ('Klasik Scrabble tahtası her kenarda kaç kareden oluşur?', 'How many squares run along each side of a classic Scrabble board?', '["15","12","14","16"]'::jsonb),
  ('İrlanda''nın euro madeni paralarının ulusal yüzünde hangi çalgı vardır?', 'Which musical instrument appears on the national side of Ireland''s euro coins?', '["Harp","Violin","Bagpipes","Accordion"]'::jsonb),
  ('Çin''in Ay Festivali''nde geleneksel olarak hangi tatlı hediye edilir?', 'What sweet is traditionally given during China''s Mid-Autumn Festival?', '["Mooncake","Rice pudding","Sesame halva","Banana cake"]'::jsonb),
  ('Fransız ''galette des rois'' pastasındaki küçük figürü bulan kişi başına ne takar?', 'What does the person who finds the small figurine in a French galette des rois wear on their head?', '["Crown","Headband","Cap","Hat"]'::jsonb),
  ('Tayland''ın Loy Krathong festivalinde suya bırakılan geleneksel nesne hangisidir?', 'Which traditional object is floated on water during Thailand''s Loy Krathong festival?', '["Flower basket","Paper lantern","Bamboo fan","Fabric flag"]'::jsonb),
  ('Alman Polterabend geleneğinde düğün öncesi uğur için ne kırılır?', 'What is broken for good luck before a wedding in the German Polterabend tradition?', '["Porcelain","Glass tumblers","Wooden spoons","Metal trays"]'::jsonb),
  ('Japon senbazuru geleneğinde hangi nesne öne çıkar?', 'Which object is closely associated with Japanese senbazuru?', '["Paper crane","Coloured powder","Nesting dolls","Red envelope"]'::jsonb),
  ('Antik Olimpiyat galiplerinin tacı hangi bitkiden yapılırdı?', 'Which plant was used for the ancient Olympic victors'' wreath?', '["Olive branch","Laurel branch","Oak branch","Palm branch"]'::jsonb),
  ('İngilizce Scrabble setinde boş taşın puan değeri kaçtır?', 'How many points is a blank tile worth in English-language Scrabble?', '["0","1","2","3"]'::jsonb),
  ('San Francisco''daki Golden Gate Köprüsü''nün boya rengi hangi adla bilinir?', 'What is the name of the Golden Gate Bridge''s paint colour?', '["International Orange","International Red","International Yellow","International Blue"]'::jsonb),
  ('Japonya''da yıl sonunda geleneksel olarak 108 kez çalınan nesne hangisidir?', 'What is traditionally rung 108 times at Japanese temples at the end of the year?', '["Temple bell","Taiko drum","Bamboo flute","Metal gong"]'::jsonb),
  ('Standart mahjong taşlarında bambu ve çember yanında üçüncü sayı grubu hangisidir?', 'What is the third numbered suit in standard mahjong alongside bamboo and circles?', '["Characters","Flower tiles","Wind tiles","Dragon tiles"]'::jsonb),
  ('Hanuka için kullanılan hanukiyada yardımcı mum dahil kaç mum yeri vardır?', 'How many candle holders does a Hanukkah menorah have, including the helper candle?', '["9","7","8","10"]'::jsonb),
  ('Japon daruma bebeğinde bir dilek tutulurken ilk olarak hangi bölüm boyanır?', 'Which part is painted first when a wish is made with a Japanese daruma doll?', '["One eye","Mouth","One ear","Nose"]'::jsonb),
  ('İskoç quaich içki kabının karşılıklı kaç sapı vardır?', 'How many opposing handles does a Scottish quaich drinking cup have?', '["2","1","3","4"]'::jsonb),
  ('Japon koi balığı biçimli koinobori süsleri hangi bayramda asılır?', 'For which Japanese holiday are carp-shaped koinobori streamers displayed?', '["Children''s Day","New Year","Respect for the Aged Day","Marine Day"]'::jsonb),
  ('Japon kintsugi geleneğinde hangi eşyaların kırıkları altın renkli birleşimlerle onarılır?', 'What objects are repaired with gold-coloured joins in Japanese kintsugi?', '["Ceramic vessels","Wooden toys","Leather bags","Fabric garments"]'::jsonb),
  ('Japon furoshiki geleneğinde nesneler hangi malzemeyle sarılır?', 'What material is used to wrap objects in Japanese furoshiki?', '["Cloth","Paper","Leather","Wicker"]'::jsonb),
  ('İtalyan ''colomba'' Paskalya keki hangi kuşun biçimindedir?', 'What bird is the Italian Easter cake colomba shaped like?', '["Dove","Swan","Peacock","Rooster"]'::jsonb),
  ('''Yeşilin Kızı Anne'' kitabının yazarı kimdir?', 'Who wrote ''Anne of Green Gables''?', '["L. M. Montgomery","Louisa May Alcott","Frances Hodgson Burnett","Johanna Spyri"]'::jsonb),
  ('Bülbülü Öldürmek''teki Atticus Finch karakterinin mesleği nedir?', 'What is Atticus Finch in To Kill a Mockingbird''s profession?', '["Lawyer","Doctor","Sailor","Architect"]'::jsonb),
  ('Fahrenheit 451''deki Guy Montag karakterinin mesleği nedir?', 'What is Guy Montag in Fahrenheit 451''s profession?', '["Fireman","Governess","Teacher","Journalist"]'::jsonb),
  ('Orman Kitabı''ndaki Baloo hangi tür hayvandır?', 'What kind of animal is Baloo in The Jungle Book?', '["Bear","Horse","Mouse","Wolf"]'::jsonb),
  ('Heathcliff hangi romandaki karakterdir?', 'In which novel does Heathcliff appear?', '["Wuthering Heights","Pride and Prejudice","Great Expectations","Oliver Twist"]'::jsonb),
  ('Mr Darcy hangi romandaki karakterdir?', 'In which novel does Mr Darcy appear?', '["Pride and Prejudice","Wuthering Heights","Great Expectations","The Picture of Dorian Gray"]'::jsonb),
  ('Long John Silver hangi romandaki karakterdir?', 'In which novel does Long John Silver appear?', '["Treasure Island","Oliver Twist","Frankenstein","The Great Gatsby"]'::jsonb),
  ('''Watership Tepesi'' kitabının yazarı kimdir?', 'Who wrote ''Watership Down''?', '["Richard Adams","Philip Pullman","Diana Wynne Jones","Michael Morpurgo"]'::jsonb),
  ('Ray Bradbury''nin romanı ''Fahrenheit 451''de 451 sayısı hangi malzemenin tutuşma sıcaklığına gönderme yapar?', 'What material''s ignition temperature does 451 refer to in Ray Bradbury''s ''Fahrenheit 451''?', '["Paper","Wood","Cloth","Plastic"]'::jsonb),
  ('''Hobbit''te Bilbo''nun cücelerle birlikte gittiği dağın adı nedir?', 'What mountain do Bilbo and the dwarves travel to in ''The Hobbit''?', '["Lonely Mountain","Misty Mountains","Mount Doom","Iron Hills"]'::jsonb),
  ('''Tom Sawyer''ın Maceraları''nda Tom''u büyüten kadının adı nedir?', 'What is the name of the woman who raises Tom in ''The Adventures of Tom Sawyer''?', '["Polly","Sally","Betsy","Clara"]'::jsonb),
  ('Charlotte ve Emily Brontë''nin romancı olan kız kardeşleri kimdir?', 'Who was Charlotte and Emily Brontë''s novelist sister?', '["Anne","Maria","Elizabeth","Mary"]'::jsonb),
  ('''Robinson Crusoe'' kurtardığı adama hangi günün adını verir?', 'Which day''s name does Robinson Crusoe give to the man he rescues?', '["Friday","Monday","Wednesday","Sunday"]'::jsonb),
  ('Harry Potter''da Fleur Delacour hangi okulda okur?', 'Which school does Fleur Delacour attend in Harry Potter?', '["Beauxbatons","Durmstrang","Ilvermorny","Castelobruxo"]'::jsonb),
  ('Antoine de Saint-Exupéry ''Küçük Prens''i hangi arkadaşına ithaf etmiştir?', 'To which friend did Antoine de Saint-Exupéry dedicate ''The Little Prince''?', '["Léon Werth","André Malraux","Jean-Richard Bloch","Paul Éluard"]'::jsonb),
  ('''Dönüşüm''de Gregor Samsa''nın işe giderken yetişmesi gereken taşıt hangisidir?', 'Which form of transport must Gregor Samsa catch for work in ''The Metamorphosis''?', '["Train","Bus","Tram","Ferry"]'::jsonb),
  ('''Dünyanın Merkezine Yolculuk''ta profesörün eski kitabında bulunan gizli mesaj hangi yazıyla yazılmıştır?', 'In ''Journey to the Centre of the Earth'', what script is used for the secret message in the old book?', '["Runic script","Hieroglyphs","Cuneiform","Brahmi script"]'::jsonb),
  ('''İki Şehrin Hikâyesi''nde Dr. Manette hapiste hangi zanaatı öğrenmiştir?', 'What craft does Dr Manette learn in prison in ''A Tale of Two Cities''?', '["Shoemaking","Watch repairing","Bookbinding","Carpentry"]'::jsonb)
  ) v(soru, en_soru, en_secenekler)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Karıştırma (TR + EN aynı permütasyon)
drop table if exists pg_temp._parti_karistir;
create temp table _parti_karistir as
select q.id, array_agg(s.idx order by s.rnd) as perm
  from public.questions q
  cross join lateral (
    select (ordinality - 1)::int as idx, random() as rnd
      from jsonb_array_elements(q.secenekler) with ordinality
  ) s
 where q.created_at >= transaction_timestamp()
 group by q.id;

update public.questions q
   set secenekler = (select jsonb_agg(q.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o)),
       dogru_cevap = (array_position(k.perm, q.dogru_cevap::int) - 1)::smallint
  from _parti_karistir k
 where q.id = k.id;

update public.question_translations t
   set secenekler = (select jsonb_agg(t.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o))
  from _parti_karistir k
 where t.question_id = k.id;

drop table if exists pg_temp._parti_karistir;
