-- ============================================================
-- 997 — Şık ipucu düzeltmesi, parti 4 (8 Eki 2026, Claude API)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide işaretli kolay/orta
-- (zorluk 1–3) sorulardan 50 tanesinin YANLIŞ şıkları Claude API (claude-sonnet-5-5) ile yeniden yazıldı;
-- soru metni, doğru cevap ve doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar dört kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0.75), Jev tek doğru cevap kontrolü ve
-- yanlış şık başına ayrı Claude hakem çağrısı (kesin_yanlis). Geçemeyen sorulara dokunulmadı, işaretli kalır.
-- EN çeviri: aynı indekslerle güncellenir (EN çevirisi olmayan soruda yalnız TR). Üretici: araclar/soru-temizlik/sik-ipucu-api.mjs --tam
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 4   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('6f44a03f-bcf1-4d62-8649-50c1275a2bc9'::uuid, 2, '["Yalnız masaüstü uyum","Renk azaltma","Farklı ekranlarda uyumlu görünüm","Ses eklemek"]'::jsonb, '["Yalnız yazıcı çıktısı uyumu","Sayfa yükleme süresini kısaltma","Farklı ekranlarda uyumlu görünüm","Veritabanı yedekleme"]'::jsonb, '["Desktop-only fit","Reducing colours","A layout that works on different screens","Adding sound"]'::jsonb, '["Print-only formatting","Shortening page load time","A layout that works on different screens","Backing up databases"]'::jsonb),
    ('439acb72-a143-4abd-9ccb-0b043d16b10c'::uuid, 3, '["İkincil yorum sunması","Kurgu içermesi","Sadece harita içermesi","Birincil kaynak sunması"]'::jsonb, '["Modern yorum sunması","Edebî eser içermesi","Yalnızca vergi tahriri içermesi","Birincil kaynak sunması"]'::jsonb, '["They offer secondary interpretation","They contain fiction","They only contain maps","They offer primary sources"]'::jsonb, '["They offer modern interpretation","They contain literary works","They only contain tax registers","They offer primary sources"]'::jsonb),
    ('32199470-c435-4486-9cb0-af6b88f20a93'::uuid, 2, '["Popülariteyi","Bilet satışını","Tarafsızlık ve seviyeyi","Yaş sınırını"]'::jsonb, '["Kulüp bütçesini ve gelirini","Forma sponsorluğunu ve reklamı","Tarafsızlık ve seviyeyi","Maç tarihini ve saatini"]'::jsonb, '["Popularity","Ticket sales","Impartiality and level","The age limit"]'::jsonb, '["Club budget and revenue","Jersey sponsorship and advertising","Impartiality and level","Match date and time"]'::jsonb),
    ('add467d2-2f81-45b4-b3c9-5389e82e6a55'::uuid, 1, '["Attila İlhan","Nâzım Hikmet","Rıfat Ilgaz","Ahmed Arif"]'::jsonb, '["Orhan Veli Kanık","Nâzım Hikmet","Cemal Süreya","Can Yücel"]'::jsonb, '["Attila İlhan","Nâzım Hikmet","Rıfat Ilgaz","Ahmed Arif"]'::jsonb, '["Orhan Veli Kanık","Nâzım Hikmet","Cemal Süreya","Can Yücel"]'::jsonb),
    ('f07d887f-eb8e-4893-a2c3-a5e5947a3c6a'::uuid, 2, '["Hans Zimmer","Jerry Goldsmith","John Williams","Danny Elfman"]'::jsonb, '["Ennio Morricone","Jerry Goldsmith","John Williams","Bernard Herrmann"]'::jsonb, '["Hans Zimmer","Jerry Goldsmith","John Williams","Danny Elfman"]'::jsonb, '["Ennio Morricone","Jerry Goldsmith","John Williams","Bernard Herrmann"]'::jsonb),
    ('51445e39-b8b0-49cd-8901-5c2c485f5fad'::uuid, 0, '["George Martin","Brian Epstein","Joe Meek","Glyn Johns"]'::jsonb, '["George Martin","Phil Spector","Tony Visconti","Glyn Johns"]'::jsonb, '["George Martin","Brian Epstein","Joe Meek","Glyn Johns"]'::jsonb, '["George Martin","Phil Spector","Tony Visconti","Glyn Johns"]'::jsonb),
    ('d38e9df6-b76f-4eaa-baa9-0493bbc48cd3'::uuid, 0, '["Kaynakların ihtiyaca göre artırılabilmesi","Donanım azlığı","Sabit kapasite","Ağ kesintisi"]'::jsonb, '["Kaynakların ihtiyaca göre artırılabilmesi","Verilerin şifrelenerek saklanması","Sunucuların fiziksel olarak taşınması","Yazılımların otomatik güncellenmesi"]'::jsonb, '["Resources can be increased as needed","A shortage of hardware","Fixed capacity","A network outage"]'::jsonb, '["Resources can be increased as needed","Data being stored in encrypted form","Servers being physically relocated","Software being updated automatically"]'::jsonb),
    ('9324d208-f86a-4098-b8c2-faa1b30479bd'::uuid, 0, '["Ellis Adası","Staten Adası","Roosevelt Adası","Governors Adası"]'::jsonb, '["Ellis Adası","Staten Adası","Roosevelt Adası","Governors Adası"]'::jsonb, '["Ellis Island","Staten Island","Roosevelt Island","Governors Island"]'::jsonb, '["Ellis Island","Staten Island","Roosevelt Island","Governors Island"]'::jsonb),
    ('6995e259-b89d-4906-adbf-f1c049a73ce3'::uuid, 2, '["Uzunluğa","Renge","Oturuş ve kürek biçimine","Ağırlığa"]'::jsonb, '["Gövde malzemesine ve üretim yöntemine","Su akıntısına ve rota uzunluğuna","Oturuş ve kürek biçimine","Kullanılan yelken ve dümen tipine"]'::jsonb, '["Length","Colour","The seating position and the paddle","Weight"]'::jsonb, '["The hull material and the manufacturing method","The water current and the route length","The seating position and the paddle","The sail and the rudder type used"]'::jsonb),
    ('1a72a20a-95e0-42c5-a6b9-2d8438830847'::uuid, 1, '["Ev taşımak","Gözden düşmek","Ayakkabı almak","Çatı yapmak"]'::jsonb, '["Borcunu ödemek","Gözden düşmek","Yolculuğa çıkmak","Başarıyı kutlamak"]'::jsonb, null, null),
    ('b0ecdf77-af94-4508-9a08-1a5e1e7cf083'::uuid, 3, '["Dan Brown","Conan Doyle","Simenon","Agatha Christie"]'::jsonb, '["Dorothy L. Sayers","Arthur Conan Doyle","Georges Simenon","Agatha Christie"]'::jsonb, '["Dan Brown","Conan Doyle","Simenon","Agatha Christie"]'::jsonb, '["Dorothy L. Sayers","Arthur Conan Doyle","Georges Simenon","Agatha Christie"]'::jsonb),
    ('ca729cb5-0349-457e-84f0-973c41155f02'::uuid, 0, '["Bir sesi referanssız tanıyabilme","Yüksek sesle söyleme","Nota yazma","Hızlı çalma"]'::jsonb, '["Bir sesi referanssız tanıyabilme","İki sesin arasındaki aralığı bulabilme","Duyduğu ezgiyi ritmiyle tekrar edebilme","Bir şarkının tonunu yarım perde değiştirebilme"]'::jsonb, '["Being able to name a note without a reference","Singing loudly","Writing notation","Playing fast"]'::jsonb, '["Being able to name a note without a reference","Being able to find the interval between two notes","Being able to repeat a heard melody with its rhythm","Being able to shift a song''s key by a semitone"]'::jsonb),
    ('ee03439d-6862-4b59-af84-3f6668496db0'::uuid, 3, '["Kaleye şut atmayı","Taç atmayı","Korner kullanmayı","Kalecinin ayakla gelen geri pası elle almasını"]'::jsonb, '["Oyuncunun kaleciye sözlü talimat vermesini","Savunmacının topu kendi ceza sahasında kafayla oynamasını","Hakemin oyunu avantaj için devam ettirmesini","Kalecinin ayakla gelen geri pası elle almasını"]'::jsonb, '["Shooting at goal","Taking a throw-in","Taking a corner","The keeper handling a deliberate pass from a team-mate''s foot"]'::jsonb, '["A player giving verbal instructions to the keeper","A defender heading the ball inside his own penalty area","The referee letting play continue for an advantage","The keeper handling a deliberate pass from a team-mate''s foot"]'::jsonb),
    ('54882261-79e1-47d3-a5a6-3fb87c1a7da1'::uuid, 3, '["Mauritshuis","Van Gogh Müzesi","Stedelijk","Rijksmuseum"]'::jsonb, '["Frans Hals Müzesi","Van Gogh Müzesi","Boijmans Müzesi","Rijksmuseum"]'::jsonb, '["Mauritshuis","Van Gogh Museum","Stedelijk","Rijksmuseum"]'::jsonb, '["Frans Hals Museum","Van Gogh Museum","Boijmans Museum","Rijksmuseum"]'::jsonb),
    ('c9a981b2-d8ac-4bbb-9278-f601a0165e68'::uuid, 1, '["Uzun destanlar","Sade dil ve gündelik konular","Aruz ölçüsü","Ağır dil"]'::jsonb, '["Divan edebiyatı nazım biçimleri","Sade dil ve gündelik konular","Hece ölçüsü ve dörtlük düzeni","Mitolojik ve dinî temalar"]'::jsonb, '["Long epics","Plain language and everyday subjects","The aruz metre","Heavy language"]'::jsonb, '["Divan literature verse forms","Plain language and everyday subjects","Syllabic metre and quatrain structure","Mythological and religious themes"]'::jsonb),
    ('2bd40f64-e6ef-4ac5-ba4d-4897868cabf3'::uuid, 2, '["Geniş fırça darbesine","Spatula kullanımına","Küçük renk noktalarına","Sprey boyaya"]'::jsonb, '["Kısa çapraz çizgilere","Yarı saydam sır katmanlarına","Küçük renk noktalarına","Keskin siyah konturlara"]'::jsonb, '["Broad brushstrokes","The use of a palette knife","Small dots of colour","Spray paint"]'::jsonb, '["Short diagonal hatching strokes","Layers of translucent glaze","Small dots of colour","Sharp black outlines"]'::jsonb),
    ('5df2592b-fb06-4379-9f9f-3c29209c2379'::uuid, 2, '["Galata Köprüsü","Haliç Köprüsü","Boğaziçi Köprüsü","Fatih Köprüsü"]'::jsonb, '["Yavuz Sultan Selim Köprüsü","Osmangazi Köprüsü","Boğaziçi Köprüsü","Fatih Sultan Mehmet Köprüsü"]'::jsonb, '["Galata Bridge","Golden Horn Bridge","Bosphorus Bridge","Fatih Bridge"]'::jsonb, '["Yavuz Sultan Selim Bridge","Osmangazi Bridge","Bosphorus Bridge","Fatih Sultan Mehmet Bridge"]'::jsonb),
    ('bb7da62a-f8a6-49d9-a32c-1a642aaa7682'::uuid, 0, '["Acıklı ve gülünç yanları birlikte vermesi","Yalnız acıklı","Ölçülü olması","Yalnız gülünç"]'::jsonb, '["Acıklı ve gülünç yanları birlikte vermesi","Kahramanın soylu kişilerden seçilmesi","Yalnızca nazım biçiminde yazılması","Üç birlik kuralına sıkı sıkıya uyması"]'::jsonb, '["Giving the sorrowful and the comic together","Only the sorrowful","Being measured","Only the comic"]'::jsonb, '["Giving the sorrowful and the comic together","Choosing its hero from among noble figures","Being written only in verse form","Strictly obeying the rule of three unities"]'::jsonb),
    ('f9651604-8c3e-4cad-b01f-86d71013c7e1'::uuid, 2, '["Metalleri","Gazları yalnızca","Karışımdaki bileşenleri","Tuzları yalnızca"]'::jsonb, '["Çözeltideki iyonların yükünü","Sıvıların kaynama noktalarını","Karışımdaki bileşenleri","Atomların çekirdek parçacıklarını"]'::jsonb, '["Metals","Gases only","The components of a mixture","Salts only"]'::jsonb, '["The ionic charges in a solution","The boiling points of liquids","The components of a mixture","The nuclear particles of atoms"]'::jsonb),
    ('af156f9b-a3e3-415f-848b-563f91bb8957'::uuid, 1, '["Kuraklık","Aşırı yağış ve eğim","Rüzgâr","Yüksek sıcaklık"]'::jsonb, '["Düşük hava basıncı ve sis","Aşırı yağış ve eğim","Kutup rüzgârlarının şiddeti","Gelgit hareketleri ve tuzluluk"]'::jsonb, '["Drought","Heavy rainfall and a steep slope","Wind","High temperature"]'::jsonb, '["Low air pressure and fog","Heavy rainfall and a steep slope","Intensity of polar winds","Tidal movements and salinity"]'::jsonb),
    ('731e635b-14cf-450b-81db-7d16ac28484d'::uuid, 0, '["İşlemleri resmen onaylamak","Ceza vermek","Vergi toplamak","Dava açmak"]'::jsonb, '["İşlemleri resmen onaylamak","Davaları karara bağlamak","Kimlik belgelerini düzenlemek","Tapu kayıtlarını tutmak"]'::jsonb, '["Certifying transactions officially","Imposing penalties","Collecting taxes","Bringing lawsuits"]'::jsonb, '["Certifying transactions officially","Deciding court cases","Issuing identity documents","Keeping land registry records"]'::jsonb),
    ('06a64086-5099-4a4b-9a28-6eabf23c19f3'::uuid, 0, '["1,21 gigavat","2,42 gigavat","1,21 megavat","0,88 gigavat"]'::jsonb, '["1,21 gigavat","1,88 gigavat","2,21 gigavat","0,88 gigavat"]'::jsonb, '["1.21 gigawatts","2.42 gigawatts","1.21 megawatts","0.88 gigawatts"]'::jsonb, '["1.21 gigawatts","1.88 gigawatts","2.21 gigawatts","0.88 gigawatts"]'::jsonb),
    ('57a24725-ebb5-4eb2-b3e5-471462bd4c44'::uuid, 0, '["Sistemin erişilebilir kaldığı süreyi","Kod uzunluğunu","Kullanıcı sayısını","Veri boyutunu"]'::jsonb, '["Sistemin erişilebilir kaldığı süreyi","Sistemin yanıt verme hızını","Sistemin işlem yapabildiği kullanıcı kapasitesini","Sistemin ağ üzerinden aktarabildiği veri miktarını"]'::jsonb, '["How long a system stays reachable","The length of the code","The number of users","The size of the data"]'::jsonb, '["How long a system stays reachable","How fast a system responds to requests","How many users a system can handle","How much data a system can transfer over a network"]'::jsonb),
    ('a9cf0d63-2bc4-4f40-abcc-65b7d64a7ae1'::uuid, 0, '["Ağaç halkalarına","Kemik yoğunluğuna","Toprak rengine","Sikke ağırlığına"]'::jsonb, '["Ağaç halkalarına","Kaya katmanlarına","Buzul çökellerine","Mercan kabuklarına"]'::jsonb, '["Tree rings","Bone density","Soil colour","The weight of coins"]'::jsonb, '["Tree rings","Rock layers","Glacial sediments","Coral shells"]'::jsonb),
    ('f3253ba7-7ce3-44ed-ba7c-30a1a781d62d'::uuid, 3, '["Akabe","İrbid","Zerka","Amman"]'::jsonb, '["Akabe","Kerek","Zerka","Amman"]'::jsonb, '["Aqaba","Irbid","Zarqa","Amman"]'::jsonb, '["Aqaba","Karak","Zarqa","Amman"]'::jsonb),
    ('9050520b-1681-4e86-b687-fb6268cd5661'::uuid, 0, '["Liverpool","Leeds United","Aston Villa","Everton"]'::jsonb, '["Liverpool","Newcastle United","Manchester City","Tottenham Hotspur"]'::jsonb, '["Liverpool","Leeds United","Aston Villa","Everton"]'::jsonb, '["Liverpool","Newcastle United","Manchester City","Tottenham Hotspur"]'::jsonb),
    ('198bc500-a569-46b5-bff7-6ccc7b9a5dc0'::uuid, 0, '["Sanatçı teknik ve tarih","Bilet fiyatı","Sponsor","Salon adı"]'::jsonb, '["Sanatçı teknik ve tarih","Sigorta bedeli ve nakliye firması","Koleksiyoncunun adres bilgisi","Sergi kürsüsü ve ışık düzeni"]'::jsonb, '["Artist, technique and date","The ticket price","The sponsor","The name of the hall"]'::jsonb, '["Artist, technique and date","Insurance value and shipping company","The collector''s home address","The display stand and lighting layout"]'::jsonb),
    ('9bdc5ecd-3c67-4122-8a76-ad2fe5b5ac67'::uuid, 1, '["Gizli eser","Kamu malı","Taslak","Yasak eser"]'::jsonb, '["Özel mülk","Kamu malı","Lisanslı eser","Koruma altı eser"]'::jsonb, '["Secret works","Public domain","Drafts","Banned works"]'::jsonb, '["Private property","Public domain","Licensed works","Protected works"]'::jsonb),
    ('3f5a222a-df08-4442-bd1f-72fe81b90fb8'::uuid, 0, '["Oscar Wilde","Shaw","Stevenson","Conrad"]'::jsonb, '["Oscar Wilde","Thomas Hardy","Bram Stoker","Henry James"]'::jsonb, '["Oscar Wilde","Shaw","Stevenson","Conrad"]'::jsonb, '["Oscar Wilde","Thomas Hardy","Bram Stoker","Henry James"]'::jsonb),
    ('e4e528a2-72c1-403a-8468-9b694935cdea'::uuid, 3, '["Günleri","Yılları","Mevsimleri","Yer tarihini dönemlere"]'::jsonb, '["Kayaçları sertliğine göre sınıflara","Fosilleri boyutlarına göre gruplara","Depremleri şiddetine göre dereceler","Yer tarihini dönemlere"]'::jsonb, '["Days","Years","Seasons","The Earth''s history into periods"]'::jsonb, '["Rocks into classes by hardness","Fossils into groups by size","Earthquakes into levels by intensity","The Earth''s history into periods"]'::jsonb),
    ('46f38914-35f6-404e-ba7a-9114f4c113b1'::uuid, 2, '["Toplam su miktarı","Yağış miktarı","Havanın taşıyabileceği neme oranı","Basınç"]'::jsonb, '["Havadaki toplam su buharı miktarı","Bulutlardan düşen su miktarı","Havanın taşıyabileceği neme oranı","Havanın yüzeye uyguladığı basınç oranı"]'::jsonb, '["The total amount of water","The amount of rainfall","The ratio to the moisture the air can hold","The pressure"]'::jsonb, '["The total amount of water vapor in the air","The amount of water falling from clouds","The ratio to the moisture the air can hold","The ratio of air pressure exerted on the surface"]'::jsonb),
    ('2dbb9936-7635-4f0d-96b7-682a72689b17'::uuid, 0, '["Sanatçının bedeni ve eylemi","Tuval","Mermer","Bronz"]'::jsonb, '["Sanatçının bedeni ve eylemi","Boyalı tuval ve fırça","Oyulmuş mermer blok","Dökümlü bronz heykel"]'::jsonb, '["The artist''s body and actions","Canvas","Marble","Bronze"]'::jsonb, '["The artist''s body and actions","Painted canvas and brush","Carved marble block","Cast bronze sculpture"]'::jsonb),
    ('54ed9d7d-8c71-4ca8-84b9-750cc59e0ea2'::uuid, 3, '["Kent yaşamını","Sarayı","Denizi","Anadolu insanını ve coğrafyasını"]'::jsonb, '["İstanbul beyefendilerinin salon hayatını","Osmanlı divan geleneğinin aşk temalarını","Doğu Avrupa göçmenlerinin gurbet hikâyelerini","Anadolu insanını ve coğrafyasını"]'::jsonb, '["City life","The palace","The sea","The people and landscape of Anatolia"]'::jsonb, '["The salon life of Istanbul gentlemen","The love themes of the Ottoman divan tradition","The homesickness stories of Eastern European immigrants","The people and landscape of Anatolia"]'::jsonb),
    ('361d5d6f-0a90-44d6-a657-7507dfaa768e'::uuid, 3, '["Film çekmek","Oyuncu yetiştirmek","Bilet dağıtmak","Sinema mirasını göstermek ve korumak"]'::jsonb, '["Filmleri yurt dışına satmak ve dağıtmak","Sinema oyuncularına ödül vermek ve tanıtmak","Yeni çıkan filmleri vizyona sokmak ve yaymak","Sinema mirasını göstermek ve korumak"]'::jsonb, '["Making films","Training actors","Distributing tickets","Showing and preserving the heritage of cinema"]'::jsonb, '["Selling films abroad and distributing them","Awarding and promoting film actors","Releasing new films to theaters widely","Showing and preserving the heritage of cinema"]'::jsonb),
    ('03fd172c-2442-4cb5-bf02-de1240644053'::uuid, 0, '["Eseri başka tona aktarmak","Tempoyu değiştirmek","Çalgıyı değiştirmek","Sözü değiştirmek"]'::jsonb, '["Eseri başka tona aktarmak","Eseri daha yavaş tempoda çalmak","Eseri farklı bir çalgı için düzenlemek","Eseri iki sesli hale getirmek"]'::jsonb, '["Moving a piece to another key","Changing the tempo","Changing the instrument","Changing the lyrics"]'::jsonb, '["Moving a piece to another key","Playing a piece at a slower tempo","Arranging a piece for a different instrument","Turning a piece into two-part harmony"]'::jsonb),
    ('148c9a31-1863-4ca2-94dd-46787249e960'::uuid, 0, '["Yunan ve Doğu kültürlerinin","Roma ve Kelt kültürlerinin","Mısır ve Nubya kültürlerinin","Çin ve Hint kültürlerinin"]'::jsonb, '["Yunan ve Doğu kültürlerinin","Roma ve Kelt kültürlerinin","Mısır ve Nubya kültürlerinin","Çin ve Hint kültürlerinin"]'::jsonb, '["Greek and Eastern cultures","Roman and Celtic","Egyptian and Nubian","Chinese and Indian"]'::jsonb, '["Greek and Eastern cultures","Roman and Celtic","Egyptian and Nubian","Chinese and Indian"]'::jsonb),
    ('6f6c3aaa-0b6c-4254-8fa7-51e178beefc6'::uuid, 1, '["Belgenin uzunluğunu","Belgenin kaynağını ve bütünlüğünü","Belgenin rengini","Belgenin tarihini yalnızca"]'::jsonb, '["Belgenin dil ve yazım doğruluğunu","Belgenin kaynağını ve bütünlüğünü","Belgenin gizliliğini ve okunmazlığını","Belgenin yazdırılma sayısını"]'::jsonb, '["The length of the document","The document''s origin and integrity","The document''s colour","The document''s date only"]'::jsonb, '["The document''s language and spelling accuracy","The document''s origin and integrity","The document''s secrecy and unreadability","The document''s number of printouts"]'::jsonb),
    ('8add4a0d-82a1-4d78-afe4-6bb9b8568c3f'::uuid, 1, '["Doğrusal hızı","Birim zamandaki dönme miktarını","Kütleyi","Kuvveti"]'::jsonb, '["Birim zamandaki yer değiştirme miktarını","Birim zamandaki dönme miktarını","Birim zamandaki enerji değişimini","Birim zamandaki ivme değişimini"]'::jsonb, '["Linear speed","How much something turns per unit of time","Mass","Force"]'::jsonb, '["How much something is displaced per unit of time","How much something turns per unit of time","How much energy changes per unit of time","How much acceleration changes per unit of time"]'::jsonb),
    ('0b2160a3-60cc-44e5-84cc-6ef4f7bc5767'::uuid, 3, '["Hızlıca kilo vermeyi","Eklem esnekliğini artırmayı","Teknik beceri gelişimini","Oksijen taşıma kapasitesini"]'::jsonb, '["Kas hacmini hızla artırmayı","Eklem esnekliğini artırmayı","Teknik beceri gelişimini","Oksijen taşıma kapasitesini"]'::jsonb, '["Losing weight","Flexibility","Technique","Oxygen-carrying capacity"]'::jsonb, '["Rapid muscle growth","Flexibility","Technique","Oxygen-carrying capacity"]'::jsonb),
    ('1d49ac59-3746-4f23-b3c1-8201fad9b64e'::uuid, 1, '["Eser üretir","Sanatçıyı temsil edip eser satar","Restorasyon yapar","Müze yönetir"]'::jsonb, '["Eserlere sigorta poliçesi düzenler","Sanatçıyı temsil edip eser satar","Eserlerin sahteliğini laboratuvarda inceler","Sanat dersleri verip öğrenci yetiştirir"]'::jsonb, '["Makes works","Represents artists and sells works","Carries out restoration","Runs a museum"]'::jsonb, '["Issues insurance policies for works","Represents artists and sells works","Examines works for forgery in a laboratory","Gives art lessons and trains students"]'::jsonb),
    ('59616def-ca7b-434d-84b7-f62d604e1d1c'::uuid, 2, '["Karakterin basit olması","Tipin karmaşık olması","Tipin tek özelliği temsil etmesi","İkisinin aynı olması"]'::jsonb, '["Karakterin yalnızca yan rollerde yer alması","Tipin zamanla köklü biçimde değişmesi","Tipin tek özelliği temsil etmesi","Karakterin yalnızca bir toplumu temsil etmesi"]'::jsonb, '["The character is simple","The type is complex","The type represents a single trait","They are the same"]'::jsonb, '["The character appears only in minor roles","The type changes radically over time","The type represents a single trait","The character represents only a society"]'::jsonb),
    ('d76a373f-f6cc-473a-9079-3131b3d66967'::uuid, 1, '["Film müziği","Aynı mekân ve zamandaki planlar bütünü","Tek kare","Jenerik"]'::jsonb, '["Filmin başında ve sonunda yer alan yazılar bütünü","Aynı mekân ve zamandaki planlar bütünü","Çekimde kullanılan ışık ve ses düzeni","Bir filmin tamamının kısa özeti"]'::jsonb, '["The film music","The shots in one place and time taken together","A single frame","The credits"]'::jsonb, '["The text sequence at the beginning and end of a film","The shots in one place and time taken together","The lighting and sound setup used during filming","A short summary of an entire film"]'::jsonb),
    ('64793a8d-99a1-4c99-a9fe-6340d9314c24'::uuid, 1, '["Tempo eşitliği","Yayın düzeyinde ses tutarlılığı","Frekans artışı","Süre eşitliği"]'::jsonb, '["Parçalar arası tempo uyumu","Yayın düzeyinde ses tutarlılığı","Stereo kanal dengesi","Parçalar arası tonalite uyumu"]'::jsonb, '["Equal tempo","Consistent volume across a broadcast","A rise in frequency","Equal duration"]'::jsonb, '["Tempo matching between tracks","Consistent volume across a broadcast","Stereo channel balance","Key matching between tracks"]'::jsonb),
    ('370c0262-6859-4ab2-8e27-234562a81cfc'::uuid, 3, '["Sıkıştırmayı","Şifrelemeyi","Hızı","Dünya yazılarının ortak kodlanmasını"]'::jsonb, '["Dosya boyutlarının küçültülmesini sağlayan ortak yöntemi","Verilerin yetkisiz erişime karşı korunmasını sağlayan yöntemi","Ağ üzerinden veri aktarımının hızlandırılmasını","Dünya yazılarının ortak kodlanmasını"]'::jsonb, '["Compression","Encryption","Speed","A common encoding for the world''s writing systems"]'::jsonb, '["A shared method for reducing file sizes","A method for protecting data from unauthorized access","Faster data transfer across networks","A common encoding for the world''s writing systems"]'::jsonb),
    ('bf0fa86a-5f71-490f-9288-fada7221160f'::uuid, 0, '["Güvenli geçiş hızını","Yol rengini","Yol uzunluğunu","Yol genişliğini yalnızca"]'::jsonb, '["Güvenli geçiş hızını","Gerekli şerit sayısını","Asfaltın kalınlığını","Trafik yoğunluğunu"]'::jsonb, '["The safe speed through it","The colour of the road","The length of the road","Only the width of the road"]'::jsonb, '["The safe speed through it","The number of lanes needed","The thickness of the asphalt","The density of the traffic"]'::jsonb),
    ('42874d3a-05ab-48ed-a05f-1f42a5975cc1'::uuid, 2, '["Demyan Bedni","Saşa Çorni","Maksim Gorki","Andrey Beli"]'::jsonb, '["Anton Çehov","Saşa Çorni","Maksim Gorki","Andrey Beli"]'::jsonb, '["Demyan Bedny","Sasha Chorny","Maxim Gorky","Andrei Bely"]'::jsonb, '["Anton Chekhov","Sasha Chorny","Maxim Gorky","Andrei Bely"]'::jsonb),
    ('7f12fa40-ce4d-4923-9ac2-8de31bfb31ec'::uuid, 0, '["Tüm işitsel öğelerin kurgulanması","Yalnız diyalogu","Yalnız müziği","Yalnız efekti"]'::jsonb, '["Tüm işitsel öğelerin kurgulanması","Sahne ışığı ile renk uyumunun düzenlenmesi","Oyuncuların kostüm ve makyaj seçimlerinin belirlenmesi","Kamera hareketlerinin ve çekim açılarının planlanması"]'::jsonb, '["Shaping every audible element","Dialogue only","Music only","Effects only"]'::jsonb, '["Shaping every audible element","Coordinating stage lighting with color balance","Choosing the actors'' costumes and makeup","Planning camera movements and shot angles"]'::jsonb),
    ('6daa04d0-92e4-4335-acfa-a47f826075b5'::uuid, 3, '["Keman, flüt, obua, çello","Piyano, keman, çello, arp","Dört keman","İki keman, viyola, çello"]'::jsonb, '["Keman, viyola, çello, kontrbas","Üç keman, çello","Keman, viyola, çello, arp","İki keman, viyola, çello"]'::jsonb, '["Violin, flute, oboe, cello","Piano, violin, cello, harp","Four violins","Two violins, viola, cello"]'::jsonb, '["Violin, viola, cello, double bass","Three violins, cello","Violin, viola, cello, harp","Two violins, viola, cello"]'::jsonb),
    ('5619d693-97ac-40d4-a0f8-98e265abea06'::uuid, 1, '["Yalnız video","Kayıpsız ve saydamlık desteği","Yalnız metin","Yalnız ses"]'::jsonb, '["Kayıplı ve animasyon zorunluluğu","Kayıpsız ve saydamlık desteği","Vektörel ve sonsuz ölçeklenebilirlik","Yalnız 256 renk ve sıkıştırmasız"]'::jsonb, '["Video only","Lossless with transparency support","Text only","Audio only"]'::jsonb, '["Lossy with mandatory animation","Lossless with transparency support","Vector-based with infinite scalability","Only 256 colors and uncompressed"]'::jsonb),
    ('2d8d8b9c-2279-40f1-b480-ce00bc64e366'::uuid, 3, '["Aynıdır","İkisi de yankı içindir","İkisi de yalıtımdır","Biri dışarıyı biri içeriyi düzenler"]'::jsonb, '["Biri sesi emer, diğeri sesi yansıtır","Biri yalnızca tavana, diğeri yalnızca zemine uygulanır","Biri sesi güçlendirir, diğeri sesi kısar","Biri dışarıyı biri içeriyi düzenler"]'::jsonb, '["They are the same","Both are for echo","Both are insulation","One deals with the outside, the other with the inside"]'::jsonb, '["One absorbs sound, one reflects it","One is for ceilings only, one for floors only","One amplifies sound, one reduces it","One deals with the outside, the other with the inside"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 4: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 4: yanlış şıklar yeniden yazıldı (997)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 4: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 4: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
