-- ============================================================
-- 005 — Şık ipucu düzeltmesi, parti 9 (8 Eki 2026, Claude API)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide işaretli kolay/orta
-- (zorluk 1–3) sorulardan 42 tanesinin YANLIŞ şıkları Claude API (claude-sonnet-5-5) ile yeniden yazıldı;
-- soru metni, doğru cevap ve doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar dört kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0.75), Jev tek doğru cevap kontrolü ve
-- yanlış şık başına ayrı Claude hakem çağrısı (kesin_yanlis). Geçemeyen sorulara dokunulmadı, işaretli kalır.
-- EN çeviri: aynı indekslerle güncellenir (EN çevirisi olmayan soruda yalnız TR). Üretici: araclar/soru-temizlik/sik-ipucu-api.mjs --tam
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 9   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('32e7b9ec-e751-4ad6-a1b4-3c3c5a43617e'::uuid, 2, '["Rüzgarla","Yağışla","Isıyı tutan gazlarla","Bulutla yalnızca"]'::jsonb, '["Okyanus akıntılarıyla","Güneş lekelerinin artmasıyla","Isıyı tutan gazlarla","Dünyanın eksen eğikliğiyle"]'::jsonb, '["Wind","Rainfall","Gases that trap heat","Clouds alone"]'::jsonb, '["Ocean currents","Increased sunspots","Gases that trap heat","Earth''s axial tilt"]'::jsonb),
    ('1441c3ee-72bb-4476-a33a-3833c728ceec'::uuid, 3, '["Kentleri genelde küçültmüştür","Yerleşmeleri hiç etkilememiştir","Yalnız kırsalı büyütmüştür","Hat boyunca kentleri büyütmüştür"]'::jsonb, '["Hat boyunca kentleri kalıcı biçimde küçültmüştür","Nüfusu tamamen kıyı limanlarına yöneltmiştir","Yerleşmeleri nehir vadilerine hapsetmiştir","Hat boyunca kentleri büyütmüştür"]'::jsonb, '["It shrank cities","It had no effect","It grew the countryside","It grew towns along the line"]'::jsonb, '["It permanently shrank towns along the line","It drew the population entirely to coastal ports","It confined settlements to river valleys","It grew towns along the line"]'::jsonb),
    ('134fa573-39d0-49b1-aa67-bbafe3475e31'::uuid, 3, '["Dosyaları sıkıştırıp küçültmeyi","Ekran parlaklığını ayarlamayı","Ses düzeyini yükseltmeyi","İstenmeyen ağ trafiğini kesmeyi"]'::jsonb, '["Verileri şifreleyerek yedeklemeyi","Ağ bağlantı hızını artırmayı","Sabit disk alanını genişletmeyi","İstenmeyen ağ trafiğini kesmeyi"]'::jsonb, '["File compression","Screen brightness","Louder sound","Blocking unwanted network traffic"]'::jsonb, '["Encrypted data backup","Faster network speed","Larger hard disk space","Blocking unwanted network traffic"]'::jsonb),
    ('83a2a381-2ecf-47c2-8708-d09c5b62fd2e'::uuid, 3, '["Yalnız yaşam alanını","Yalnız besinini","Yalnız düşmanını","Türün ekosistemdeki rolünü"]'::jsonb, '["Türün coğrafi dağılım sınırlarını","Türün popülasyon büyüklüğünü","Türün evrimsel geçmişini","Türün ekosistemdeki rolünü"]'::jsonb, '["Only the habitat","Only the food","Only the predators","The species'' role in the ecosystem"]'::jsonb, '["The species'' geographic range limits","The species'' population size","The species'' evolutionary history","The species'' role in the ecosystem"]'::jsonb),
    ('b2be4f72-1c9f-45d8-8e14-1397bf11bf39'::uuid, 3, '["Ekran boyutunu","Renk sayısını","Parlaklığı","Birim uzunluktaki nokta sayısını"]'::jsonb, '["Birim alandaki renk tonu sayısını","Saniyedeki görüntü yenileme sayısını","Ekranın piksel başına ışık şiddetini","Birim uzunluktaki nokta sayısını"]'::jsonb, '["The screen size","The number of colours","The brightness","The number of dots per unit of length"]'::jsonb, '["The number of colour shades per unit of area","The number of image refreshes per second","The light intensity per pixel of the screen","The number of dots per unit of length"]'::jsonb),
    ('c15a7eb4-3fa9-42e2-b894-75dff8c973b1'::uuid, 0, '["Daha hızlı erişim","Daha çok gürültü","Daha çok hareketli parça","Daha yavaş"]'::jsonb, '["Daha hızlı erişim","Daha yüksek ısınma","Daha fazla titreşim","Daha kısa kablo"]'::jsonb, '["Faster access","More noise","More moving parts","Being slower"]'::jsonb, '["Faster access","Higher heat output","More vibration","Shorter cables"]'::jsonb),
    ('15c77a4e-7fa6-4f36-b18f-9523185a41b3'::uuid, 3, '["İşlemci saatlerinin çok yavaşlaması","Saat dilimlerinin birbirine karışması","Bellek kartlarının hızla eskimesi","Yılın iki haneyle kaydedilmesi"]'::jsonb, '["Tarihlerin ay ve gün sırasıyla yazılması","Saat dilimlerinin birbirine karışması","Gün sayacının sınırına ulaşması","Yılın iki haneyle kaydedilmesi"]'::jsonb, '["Processor clocks running too slowly","Time zones getting mixed together","Memory cards wearing out quickly","Years stored with two digits"]'::jsonb, '["Dates being written in month-day order","Time zones getting mixed together","Day counter reaching its limit","Years stored with two digits"]'::jsonb),
    ('101dcf9d-d583-41e2-af45-694dadb88d54'::uuid, 0, '["Doğal frekansta zorlama olunca","Ortam sıcaklığı yükselince","Dış basınç iyice düşünce","Toplam kütle çoğalınca"]'::jsonb, '["Doğal frekansta zorlama olunca","İki dalga zıt fazda birleşince","Titreşim genliği sürekli azalınca","Sistemin sönümü sıfıra inince"]'::jsonb, '["When forcing occurs at the natural frequency","When the temperature rises","When the pressure drops","When the mass increases"]'::jsonb, '["When forcing occurs at the natural frequency","When two waves combine in opposite phase","When vibration amplitude keeps decreasing","When the system''s damping drops to zero"]'::jsonb),
    ('a893807c-821a-48ae-895f-29fc831ad14e'::uuid, 3, '["Karpatlar","Pireneler","Apeninler","Alpler"]'::jsonb, '["Karpatlar","Dinarik Alpler","Apeninler","Alpler"]'::jsonb, '["The Carpathians","The Pyrenees","The Apennines","The Alps"]'::jsonb, '["The Carpathians","The Dinaric Alps","The Apennines","The Alps"]'::jsonb),
    ('1e66253a-6413-4e80-ba1d-c02d5ddbc38f'::uuid, 0, '["Çeşitliliğe kaynak sağlamak","Çeşitliliği azaltmak","Üremeyi durdurmak","Beslenmeyi sağlamak"]'::jsonb, '["Çeşitliliğe kaynak sağlamak","Çevreye uyumu sabitlemek","Genetik bilgiyi aktarmak","Popülasyonu bölmek"]'::jsonb, '["Providing a source of variation","Reducing variation","Stopping reproduction","Providing nutrition"]'::jsonb, '["Providing a source of variation","Fixing adaptation to the environment","Transmitting genetic information","Splitting the population"]'::jsonb),
    ('d3659cdc-656f-49d1-8f1a-002abb628997'::uuid, 2, '["Yedeği hızlandırmak","Boyut küçültmek","Yedek çalınırsa veriyi korumak","Renk vermek"]'::jsonb, '["Yedek alma süresini kısaltmak","Yedeğin depolama maliyetini düşürmek","Yedek çalınırsa veriyi korumak","Yedekten geri yüklemeyi kolaylaştırmak"]'::jsonb, '["To speed up the backup","To reduce the size","To protect the data if the backup is stolen","To add colour"]'::jsonb, '["To shorten the backup time","To lower the storage cost of the backup","To protect the data if the backup is stolen","To make restoring from the backup easier"]'::jsonb),
    ('6a26d3b0-4874-4b61-902a-f7b5c352cfbf'::uuid, 3, '["Ekran büyütme","Ses iyileştirme","Kablo azaltma","Tek donanımda çok sistem çalıştırma"]'::jsonb, '["Verileri otomatik yedekleme","Ağ hızını iki katına çıkarma","Disk alanını sıkıştırma","Tek donanımda çok sistem çalıştırma"]'::jsonb, '["A bigger screen","Better sound","Fewer cables","Running many systems on one machine"]'::jsonb, '["Backing up data automatically","Doubling network speed","Compressing disk space","Running many systems on one machine"]'::jsonb),
    ('1a919dec-a419-4ae0-86d1-0eef81870dba'::uuid, 2, '["Yakından bakmak","Karanlıkta bakmak","20-20-20 kuralı","Sürekli bakmak"]'::jsonb, '["30-30-30 kuralı","10-10-10 kuralı","20-20-20 kuralı","40-20-40 kuralı"]'::jsonb, '["Looking from close up","Looking in the dark","The 20-20-20 rule","Looking constantly"]'::jsonb, '["The 30-30-30 rule","The 10-10-10 rule","The 20-20-20 rule","The 40-20-40 rule"]'::jsonb),
    ('a2aed7c6-315e-4d61-9461-866f9eb7944d'::uuid, 1, '["Klavye tuşu","İnternette bıraktığımız veri izleri","Disk bölümü","Ekran görüntüsü"]'::jsonb, '["Cihazların ekranda bıraktığı parmak izleri","İnternette bıraktığımız veri izleri","Bilgisayarın açılış sürecinde kaydedilen kayıtlar","Kullanıcının cihaz için belirlediği giriş şifresi"]'::jsonb, '["A keyboard key","The traces of data we leave online","A disk partition","A screenshot"]'::jsonb, '["The fingerprints devices leave on the screen","The traces of data we leave online","The records saved during a computer''s startup","The login password a user sets for a device"]'::jsonb),
    ('1a26fba0-3aff-4172-ae4d-c1486d1952a9'::uuid, 2, '["Isı yayılımı","Işık saçılması","Kararsız çekirdeğin ışıma yapması","Elektron kaybı"]'::jsonb, '["Kararlı atomun elektron alması","Ağır çekirdeğin ikiye bölünmesi","Kararsız çekirdeğin ışıma yapması","Atomlar arası bağ kurulması"]'::jsonb, '["The spread of heat","The scattering of light","An unstable nucleus emitting radiation","The loss of an electron"]'::jsonb, '["A stable atom gaining an electron","A heavy nucleus splitting in two","An unstable nucleus emitting radiation","The forming of bonds between atoms"]'::jsonb),
    ('d17e5ee8-c73f-4302-82d1-97bc855aeece'::uuid, 2, '["Bir okyanus akıntısı","Bir çöl adı","Kıtaların birleşik olduğu eski kara","Bir sıradağ"]'::jsonb, '["Kıtaları ayıran derin bir okyanus çukuru","Kuzey yarım kürede yer alan büyük bir takımada","Kıtaların birleşik olduğu eski kara","Buzul çağında oluşmuş geniş bir buz örtüsü"]'::jsonb, '["An ocean current","The name of a desert","The ancient landmass in which the continents were joined","A mountain range"]'::jsonb, '["A deep ocean trench separating the continents","A large archipelago in the northern hemisphere","The ancient landmass in which the continents were joined","A vast ice sheet formed during the Ice Age"]'::jsonb),
    ('1f8484f1-f7d3-4680-b7ff-4fa14a9f5c4f'::uuid, 1, '["Tohum oluşumu","Polenin dişi organa taşınması","Meyve olgunlaşması","Kök gelişimi"]'::jsonb, '["Çiçeğin tohum bırakması","Polenin dişi organa taşınması","Bitkinin topraktan su emmesi","Yaprakların renk değiştirmesi"]'::jsonb, '["Seed formation","The transfer of pollen to the female organ","Fruit ripening","Root growth"]'::jsonb, '["A flower releasing its seeds","The transfer of pollen to the female organ","A plant absorbing water from the soil","Leaves changing color"]'::jsonb),
    ('7d39b76b-1902-49ec-b501-9da92e5c23dd'::uuid, 3, '["Yıl boyu sabit","Yalnız yazın yüksek","Hiç değişmez","Yağış dönemine bağlı düzensiz"]'::jsonb, '["Kış boyunca donarak kesilir","Kar erimesine bağlı düzenli","Buzulların erimesine bağlı sabit","Yağış dönemine bağlı düzensiz"]'::jsonb, '["Constant all year","High only in summer","Never changing","Irregular, tied to the rainy season"]'::jsonb, '["Freezes and stops flowing all winter","Regular, tied to snowmelt","Constant, tied to glacier melt","Irregular, tied to the rainy season"]'::jsonb),
    ('26fffc32-81b6-453a-9594-63e72f9608cf'::uuid, 3, '["Ağır olmaları","Renksiz olmaları","Nadir olmaları","Kararlı elektron dizilimi"]'::jsonb, '["Atom çekirdeklerinin çok kararsız olması","Yalnızca tek atomlu gaz hâlinde bulunmaları","Dış kabuklarında yalnızca tek elektron bulunması","Kararlı elektron dizilimi"]'::jsonb, '["They are heavy","They are colourless","They are rare","They have a stable electron configuration"]'::jsonb, '["Their atomic nuclei are highly unstable","They exist only as single-atom gases","They have only one electron in their outer shell","They have a stable electron configuration"]'::jsonb),
    ('2f99e8a5-a7fa-413b-859f-f5368599b35c'::uuid, 3, '["Ekranı büyütmek","Dosya silmek","Yazı yazmak","Şifreli bir ağ tüneli kurmak"]'::jsonb, '["Bilgisayarın işlemci hızını artırmak","Ağdaki cihazlara otomatik IP dağıtmak","Gelen e-postalardaki virüsleri temizlemek","Şifreli bir ağ tüneli kurmak"]'::jsonb, '["Enlarging the screen","Deleting files","Writing text","Setting up an encrypted network tunnel"]'::jsonb, '["Increasing the computer''s processor speed","Automatically assigning IP addresses to network devices","Cleaning viruses from incoming emails","Setting up an encrypted network tunnel"]'::jsonb),
    ('f9a6316f-bd87-4056-b7c4-b9b4786e0a7a'::uuid, 0, '["8850 metre","6000 metre","7000 metre","10000 metre"]'::jsonb, '["8850 metre","8420 metre","8610 metre","9150 metre"]'::jsonb, '["8,850 metres","6,000 metres","7,000 metres","10,000 metres"]'::jsonb, '["8,850 metres","8,420 metres","8,610 metres","9,150 metres"]'::jsonb),
    ('e293113f-e907-4674-8031-5d31068240c6'::uuid, 0, '["5, 12, 13","4, 6, 8","7, 10, 13","6, 9, 12"]'::jsonb, '["5, 12, 13","6, 9, 11","7, 10, 13","9, 14, 16"]'::jsonb, '["5, 12, 13","4, 6, 8","7, 10, 13","6, 9, 12"]'::jsonb, '["5, 12, 13","6, 9, 11","7, 10, 13","9, 14, 16"]'::jsonb),
    ('f87d9f7d-5c39-4824-8ea3-8490b3003722'::uuid, 2, '["Kültürün yok olması","Nüfusun artması","Kültür öğelerinin başka alanlara geçmesi","İklimin değişmesi"]'::jsonb, '["Kültür öğelerinin tek bölgede kalması","Kültür öğelerinin yeniden üretilmesi","Kültür öğelerinin başka alanlara geçmesi","Kültür öğelerinin yasalarla korunması"]'::jsonb, '["A culture dying out","The population rising","Cultural elements passing into other areas","The climate changing"]'::jsonb, '["Cultural elements staying in one region","Cultural elements being reproduced anew","Cultural elements passing into other areas","Cultural elements being protected by laws"]'::jsonb),
    ('f656c283-45d9-4bb7-ab33-15c72f63b04e'::uuid, 1, '["Hiç bölünmemesi","Farklı hücrelere dönüşebilmesi","Ölü olması","Çekirdeksiz olması"]'::jsonb, '["Yalnızca sinir dokusunda bulunması","Farklı hücrelere dönüşebilmesi","Yalnızca bir kez bölünebilmesi","Hücre zarının bulunmaması"]'::jsonb, '["It never divides","It can turn into different cells","It is dead","It has no nucleus"]'::jsonb, '["It is found only in nerve tissue","It can turn into different cells","It can divide only once","It has no cell membrane"]'::jsonb),
    ('b439870b-6f3d-41f1-b6ba-f680ce14a477'::uuid, 3, '["İklim yalnızca","Manzara","Dil","Hammadde ve ulaşım"]'::jsonb, '["Yalnızca yerel festivaller ve etkinlikler","Bölgenin turistik çekiciliği","Çevredeki tarihî yapıların sayısı","Hammadde ve ulaşım"]'::jsonb, '["Climate alone","The view","The language","Raw materials and transport"]'::jsonb, '["Only local festivals and events","The region''s tourist appeal","The number of historic buildings nearby","Raw materials and transport"]'::jsonb),
    ('774f5e28-8aea-4101-b06d-889e272c1f9f'::uuid, 2, '["Mikropları öldürmek doğrudan","Ağrıyı kesmek","Bağışıklığı önceden uyarmak","Ateşi düşürmek"]'::jsonb, '["Vücuttaki mikropları doğrudan yok etmek","Ağrı sinyallerini baskılamak","Bağışıklığı önceden uyarmak","Vücut ısısını düzenlemek"]'::jsonb, '["Killing germs directly","Relieving pain","Priming the immune system in advance","Reducing fever"]'::jsonb, '["Destroying germs in the body directly","Suppressing pain signals","Priming the immune system in advance","Regulating body temperature"]'::jsonb),
    ('9c936245-c809-4172-afd3-3a311f41b07b'::uuid, 0, '["-273","-300","-200","-100"]'::jsonb, '["-273","-269","-253","-283"]'::jsonb, '["-273","-300","-200","-100"]'::jsonb, '["-273","-269","-253","-283"]'::jsonb),
    ('270cd3c9-73f4-41d6-a817-32c43c9c3eb2'::uuid, 2, '["Ticaret yapmak","Turizm için","Çatışmayı önlemek için ayırıcı alan","Tarım için"]'::jsonb, '["Gümrük vergisini azaltmak için serbest alan","Nüfus yoğunluğunu artırmak için yerleşim alanı","Çatışmayı önlemek için ayırıcı alan","Sanayi tesislerini toplamak için üretim alanı"]'::jsonb, '["For trade","For tourism","As a separating area to prevent conflict","For farming"]'::jsonb, '["A free area to reduce customs duties","A residential area to increase population density","As a separating area to prevent conflict","A production area to gather industrial facilities"]'::jsonb),
    ('57e8ba48-6b6b-4a25-8c79-3cbdf56a2bd1'::uuid, 2, '["Renk farkına","Kütle farkına","Kaynama noktası farkına","Sertlik farkına"]'::jsonb, '["Erime noktası farkına","Yoğunluk farkına","Kaynama noktası farkına","Çözünürlük farkına"]'::jsonb, '["A difference in colour","A difference in mass","A difference in boiling point","A difference in hardness"]'::jsonb, '["A difference in melting point","A difference in density","A difference in boiling point","A difference in solubility"]'::jsonb),
    ('0a739a91-9ad4-438e-add6-c9f3b753eb4a'::uuid, 3, '["Kentteki nüfus yoğunluğunu","Kesilen trafik cezasını","Yalnızca yağış miktarını","Kirletici madde derişimlerini"]'::jsonb, '["Kentteki bina yüksekliklerini ölçmeyi","Kentteki toplu taşıma yolcu sayısını","Kentteki yeşil alan oranını","Kirletici madde derişimlerini"]'::jsonb, '["The population","Traffic fines","Only rainfall","The concentration of pollutants"]'::jsonb, '["The heights of buildings","The number of public transport passengers","The proportion of green space","The concentration of pollutants"]'::jsonb),
    ('0325ecc8-dced-4940-abe4-64dacc37c09e'::uuid, 1, '["Oral","Almatı","Aktau","Şımkent"]'::jsonb, '["Karaganda","Almatı","Astana","Şımkent"]'::jsonb, '["Oral","Almaty","Aktau","Shymkent"]'::jsonb, '["Karaganda","Almaty","Astana","Shymkent"]'::jsonb),
    ('37e18d95-5a5a-4b8b-9091-3ec8b47d55d2'::uuid, 1, '["Karına","Göğüs kemiğinin ortasına","Sırta","Boyna"]'::jsonb, '["Kaburgaların alt kenarına","Göğüs kemiğinin ortasına","Sol köprücük kemiğinin altına","Göğsün sol yanına, koltuk altına yakın"]'::jsonb, '["The abdomen","The centre of the breastbone","The back","The neck"]'::jsonb, '["The lower edge of the ribcage","The centre of the breastbone","Just below the left collarbone","The left side of the chest, near the armpit"]'::jsonb),
    ('c6572a6d-aca0-4976-ac9d-f7bb40c87c5d'::uuid, 1, '["Yalnız gaz","Tuz ve su","Yalnız asit","Yalnız baz"]'::jsonb, '["Hidrojen ve oksijen","Tuz ve su","Asit ve metal","Baz ve karbondioksit"]'::jsonb, '["Gas only","Salt and water","Acid only","Base only"]'::jsonb, '["Hydrogen and oxygen","Salt and water","Acid and metal","Base and carbon dioxide"]'::jsonb),
    ('a24674e8-5037-40d8-9b0c-42c1c33b80e4'::uuid, 1, '["Çöl alanlarıyla","Binlerce göle sahip olması","Volkanlarıyla","Yüksek dağlarıyla"]'::jsonb, '["Geniş mercan resifleriyle","Binlerce göle sahip olması","Büyük tropik yağmur ormanlarıyla","Uçsuz bucaksız bozkırlarıyla"]'::jsonb, '["Its deserts","Having thousands of lakes","Its volcanoes","Its high mountains"]'::jsonb, '["Its vast coral reefs","Having thousands of lakes","Its large tropical rainforests","Its endless steppes"]'::jsonb),
    ('7525a8fc-47b8-4fa7-8808-31611e1c9335'::uuid, 1, '["Dalga durur","Dalgalar üst üste binerek etkileşir","Dalga kaybolur","Dalga yön değiştirir"]'::jsonb, '["Dalgalar birbirinden yansıyarak geri döner","Dalgalar üst üste binerek etkileşir","Dalgalar ortam değiştirip hız kazanır","Dalgalar engelin kenarında kırılarak yayılır"]'::jsonb, '["The wave stops","Waves superpose and interact","The wave disappears","The wave changes direction"]'::jsonb, '["Waves reflect off each other and return","Waves superpose and interact","Waves enter a new medium and gain speed","Waves bend around an obstacle''s edge and spread"]'::jsonb),
    ('b51ecae3-da35-4d80-bf3e-18390107f118'::uuid, 0, '["Proton ve nötron","Elektron ve nötron","Proton ve elektron","Sadece proton"]'::jsonb, '["Proton ve nötron","Elektron ve nötron","Proton ve elektron","Elektron ve pozitron"]'::jsonb, '["Protons and neutrons","Electrons and neutrons","Protons and electrons","Protons only"]'::jsonb, '["Protons and neutrons","Electrons and neutrons","Protons and electrons","Electrons and positrons"]'::jsonb),
    ('57ec3851-0e6c-460f-a0dd-e17aa5fd92b8'::uuid, 2, '["Kurak düzlüklerde","Çöllerde","Su ve arazinin bol olduğu engebede","Kutuplarda"]'::jsonb, '["Su kaynaklarının kıt olduğu ova tabanında","Verimli arazinin dar olduğu vadi içinde","Su ve arazinin bol olduğu engebede","Ulaşım yollarının kesiştiği düzlükte"]'::jsonb, '["On arid plains","In deserts","On broken ground with plenty of water and land","At the poles"]'::jsonb, '["On a plain floor where water sources are scarce","Inside a valley where fertile land is limited","On broken ground with plenty of water and land","On flatland where transport routes intersect"]'::jsonb),
    ('c7471777-bcd1-4e41-9a6a-c630e9e5f4de'::uuid, 0, '["Işığı elektriğe","Isıyı harekete","Sesi ışığa","Rüzgârı ısıya"]'::jsonb, '["Işığı elektriğe","Isıyı elektriğe","Sesi elektriğe","Rüzgârı elektriğe"]'::jsonb, '["Light into electricity","Heat into motion","Sound into light","Wind into heat"]'::jsonb, '["Light into electricity","Heat into electricity","Sound into electricity","Wind into electricity"]'::jsonb),
    ('b788647e-bbb2-48b0-ace0-8ebadb9fa35e'::uuid, 0, '["Mezopotamya ve çevresi","Nil deltası yalnızca","İndus vadisi","Sarı Irmak havzası"]'::jsonb, '["Mezopotamya ve çevresi","Anadolu platosu ve çevresi","Hint Yarımadası ve çevresi","Orta Asya bozkırları ve çevresi"]'::jsonb, '["Mesopotamia and its surroundings","The Nile delta only","The Indus valley","The Yellow River basin"]'::jsonb, '["Mesopotamia and its surroundings","The Anatolian plateau and its surroundings","The Indian subcontinent and its surroundings","The Central Asian steppes and their surroundings"]'::jsonb),
    ('ba2aa038-b5cb-4295-bd2a-c684abe2c64a'::uuid, 3, '["Küçük kasaba","Köy yerleşimi","Sanayi sitesi","Geniş etki alanı olan büyük kent"]'::jsonb, '["Çevresine hizmet veren orta ölçekli ilçe merkezi","Yalnızca ticaret yapılan liman kenti","Nüfusu azalan eski tarım kasabası","Geniş etki alanı olan büyük kent"]'::jsonb, '["A small town","A village settlement","An industrial estate","A large city with a wide sphere of influence"]'::jsonb, '["A mid-sized district center serving its surroundings","A port town used only for trade","An old farming town with a declining population","A large city with a wide sphere of influence"]'::jsonb),
    ('0803b55a-8fa8-4719-92d6-ea068f42ab93'::uuid, 1, '["Maddenin rengine","Sıcaklığa ve basınca","Tanenin şekline","Toplam kütleye"]'::jsonb, '["Işık şiddetine ve rengine","Sıcaklığa ve basınca","Kabın hacmine ve şekline","Havadaki nem oranına"]'::jsonb, '["Colour","Temperature","Shape","Mass"]'::jsonb, '["Light intensity","Temperature","Container volume","Air humidity"]'::jsonb),
    ('7a0b7c56-5741-411a-844d-fb8da1485f35'::uuid, 3, '["24000","12000","1600","5730"]'::jsonb, '["8300","11460","1600","5730"]'::jsonb, '["24000","12000","1600","5730"]'::jsonb, '["8300","11460","1600","5730"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 9: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 9: yanlış şıklar yeniden yazıldı (005)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 9: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 9: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
