-- ============================================================
-- 1048 — soru_parti_codex_02 (stil: docs/SORU_STIL_PROFILI.md): 198 soru · 2026-10-10
--
-- Kategori: edebiyat 21 · genel_kultur 42 · muzik 18 · sanat 30 · sinema 22 · spor 26 · tarih 4 · teknoloji 35
-- Yerel (kapsam='yerel', ulke='TR'): 0 · zorluk 1–5: 0/139/59/0/0
-- İngilizce çeviri: 198 · çevrilmeyen (ceviri_atlanan, kod 'cevrilemez'): 0
--
-- Kalite: Codex yazımı; codex-kapi.mjs kapı 1–5 (TR/EN biçim ve şık denge,
-- havuz/parti birebir ve Jaccard tekrar, cevap soruda değil, DB kural kapısı,
-- Jev şık ipucu p ≤ 0,75 ve tek doğru yanlış şık p < 0,5).
-- Claude API kullanılmadı. Son Claude incelemesi AYRI; bekleyen SQL onaysız UYGULANMAZ.
--
-- Sıra: sorular doğru şık 0'da eklenir, çeviriler aynı sırayla yazılır, sonunda YALNIZ
-- bu işlemde eklenen satırların şıkları karıştırılır — TR ve EN AYNI permütasyonla
-- (dogru_cevap indeksi ortak olduğu için şart). `created_at >= transaction_timestamp()`
-- koşulu ZORUNLUDUR; onsuz tüm havuz karışır ve oynanan maçlarda indeks kayar.
-- Üretici: node araclar/soru-uretim/uret-migration-parti.mjs --parti 2 --no 1048 --klasor codex-02 --ad soru_parti_codex_02 --codex --onayli
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori, kapsam, ulke, zorluk) values
('Grant Wood''un ''Amerikan Gotiği'' tablosu hangi müzenin koleksiyonundadır?', '["Art Institute of Chicago","Kunsthistorisches Museum","Philadelphia Museum of Art","Accademia Gallery"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Arnolfini Portresi'' tablosu hangi müzenin koleksiyonundadır?', '["National Gallery","Borghese Gallery","Accademia Gallery","Alte Pinakothek"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Rodin''in ''Düşünen Adam'' heykelinin dökümlerinde hangi metal kullanılır?', '["Bronz","Demir","Çelik","Gümüş"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Özgürlük Heykeli''nin dış kaplamasında hangi metal kullanılmıştır?', '["Bakır","Demir","Çelik","Gümüş"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Paul Gauguin ressam olmadan önce hangi meslekte çalışıyordu?', '["Borsa simsarı","Gümrük memuru","Muhasebeci","Öğretmen"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Afgan Kızı'' fotoğrafını kim çekmiştir?', '["Steve McCurry","Dorothea Lange","Yousuf Karsh","Elliott Erwitt"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Mavi At I'' tablosunun ressamı kimdir?', '["Franz Marc","Caravaggio","Grant Wood","Edgar Degas"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Çiçek Taşıyıcısı'' tablosunun ressamı kimdir?', '["Diego Rivera","Claude Monet","Paul Cézanne","Paul Gauguin"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Otoportre, Dikenli Kolye ve Sinekkuşu'' tablosunun ressamı kimdir?', '["Frida Kahlo","Edgar Degas","Claude Monet","Paul Cézanne"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Çiçekli İki Tahitili Kadın'' tablosunun ressamı kimdir?', '["Paul Gauguin","Claude Monet","Paul Cézanne","Gustav Klimt"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Kızıl Balıklar'' tablosunun ressamı kimdir?', '["Henri Matisse","Édouard Manet","René Magritte","Salvador Dalí"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Tac Mahal''in beyaz dış cephesinin ana malzemesi hangisidir?', '["Mermer","Granit","Traverten","Kumtaşı"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Louvre Piramidi''nin yüzey panelleri hangi malzemedendir?', '["Cam","Akrilik","Polikarbonat","Polyester"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Rushmore Dağı''ndaki dört başkan yüzünden en soldaki kime aittir?', '["George Washington","Thomas Jefferson","Theodore Roosevelt","Abraham Lincoln"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Monet''nin Giverny göletinden esinlenen tablo dizisinin adı nedir?', '["Nilüferler","Dansçılar","Ayçiçekleri","Siyah Resimler"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Van Gogh''un ''Yıldızlı Gece'' tablosundaki köyde hangi yapının sivri kulesi yükselir?', '["Kilise","Saray","Fabrika","Belediye"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Rousseau''nun ''Uyuyan Çingene'' tablosunda uyuyan kadının yanında hangi hayvan durur?', '["Aslan","Kaplan","Zürafa","Gergedan"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Hopper''ın ''Gece Kuşları'' tablosundaki lokantada toplam kaç kişi vardır?', '["4","3","5","6"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Grant Wood''un ''Amerikan Gotiği'' tablosundaki erkeğin yüzünde hangi aksesuar vardır?', '["Gözlük","Monokl","Göz bandı","Maske"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Manet''nin ''Olympia'' tablosunda yatağın ayak ucunda hangi hayvan bulunur?', '["Kedi","Köpek","Tavşan","Papağan"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Özgürlük Heykeli''nin başındaki tacında kaç ışın bulunur?', '["7","5","6","8"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Klimt''in ''Öpücük'' tablosu hangi müzenin koleksiyonundadır?', '["Belvedere","Albertina","Leopold Museum","Kunsthistorisches Museum"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Christina''nın Dünyası'' tablosu hangi müzenin koleksiyonundadır?', '["MoMA","Prado","Louvre","Uffizi"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Fragonard''ın ''Salıncak'' tablosu hangi müzenin koleksiyonundadır?', '["Wallace Collection","Accademia Gallery","National Gallery","Kunsthistorisches Museum"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Bruegel''in 1563 tarihli büyük ''Babil Kulesi'' tablosu hangi müzededir?', '["Kunsthistorisches Museum","Art Institute of Chicago","Philadelphia Museum of Art","Accademia Gallery"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Berlin Yahudi Müzesi tasarımını yapan mimar kimdir?', '["Daniel Libeskind","Frank Lloyd Wright","Walter Gropius","Oscar Niemeyer"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Sargent''ın ''Madam X'' portresindeki kadın kimdir?', '["Virginie Gautreau","Adele Bloch-Bauer","Elizabeth Siddal","Jeanne Hébuterne"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Millais''nin ''Ophelia'' tablosuna model olan kadın kimdir?', '["Elizabeth Siddal","Jeanne Hébuterne","Lisa Gherardini","Virginie Gautreau"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Dalí Atomicus'' fotoğrafını kim çekmiştir?', '["Philippe Halsman","Robert Doisneau","Dorothea Lange","Alfred Eisenstaedt"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Çingene Kızı'' tablosunun ressamı kimdir?', '["Frans Hals","Caravaggio","Grant Wood","Edgar Degas"]'::jsonb, 0, 'sanat', 'global', null, 3),
('John Bonham hangi grubun üyesiydi?', '["Led Zeppelin","Dire Straits","The Beatles","Deep Purple"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Stewart Copeland hangi grubun üyesiydi?', '["The Police","Pink Floyd","The Beatles","Deep Purple"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Nick Mason hangi grubun üyesiydi?', '["Pink Floyd","The Police","The Beatles","Deep Purple"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Glenn Frey hangi grubun üyesiydi?', '["Eagles","R.E.M.","Queen","Nirvana"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Ray Manzarek hangi grubun üyesiydi?', '["The Doors","Metallica","Radiohead","Pink Floyd"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Jon Lord hangi grubun üyesiydi?', '["Deep Purple","The Beatles","Pink Floyd","Led Zeppelin"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Peter Gabriel hangi grubun üyesiydi?', '["Genesis","Nirvana","The Who","Eagles"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Benny Goodman en çok hangi enstrümanla tanınır?', '["Klarnet","Trompet","Bateri","Saksafon"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Ian Anderson en çok hangi enstrümanla tanınır?', '["Flüt","Gitar","Keman","Bateri"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Brothers in Arms'' albümü hangi gruba aittir?', '["Dire Straits","Led Zeppelin","The Beatles","Deep Purple"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Machine Head'' albümü hangi gruba aittir?', '["Deep Purple","The Beatles","Pink Floyd","Led Zeppelin"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Eleanor Rigby'' şarkısı ilk olarak hangi albümde yayımlandı?', '["Revolver","Let It Be","Abbey Road","Rubber Soul"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Norwegian Wood'' şarkısı ilk olarak hangi albümde yayımlandı?', '["Rubber Soul","Abbey Road","Let It Be","The White Album"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Geddy Lee hangi grubun üyesiydi?', '["Rush","ABBA","Blur","Queen"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Andy Rourke hangi grubun üyesiydi?', '["The Smiths","Pink Floyd","The Police","The Beatles"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Toots Thielemans en çok hangi enstrümanla tanınır?', '["Armonika","Saksafon","Bas gitar","Trompet"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Norma'' operasını kim bestelemiştir?', '["Vincenzo Bellini","Benjamin Britten","Giacomo Puccini","Gioachino Rossini"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Salome'' operasını kim bestelemiştir?', '["Richard Strauss","Giacomo Puccini","Giuseppe Verdi","Richard Wagner"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Dreamcast hangi şirket tarafından üretilmiştir?', '["Sega","Sony","Palm","Korg"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Amiga 500 hangi şirket tarafından üretilmiştir?', '["Commodore","Microsoft","Panasonic","Nintendo"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('2600 oyun konsolu hangi şirket tarafından üretilmiştir?', '["Atari","Apple","Nokia","Canon"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('LaserJet yazıcı serisi hangi şirket tarafından üretilmiştir?', '["Hewlett-Packard","Texas Instruments","Sinclair Research","Microsoft"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('9000 Communicator hangi şirket tarafından üretilmiştir?', '["Nokia","Apple","Atari","Canon"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('RAZR V3 hangi şirket tarafından üretilmiştir?', '["Motorola","Nintendo","Logitech","Ericsson"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk Sony PlayStation, Japonya''da hangi yıl piyasaya çıktı?', '["1994","1993","1995","1997"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Amazon Kindle''ın ilk modeli hangi yıl piyasaya çıktı?', '["2007","2005","2006","2009"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nintendo Wii hangi yıl piyasaya çıktı?', '["2006","2005","2007","2009"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Microsoft Xbox''ın ilk modeli hangi yıl piyasaya çıktı?', '["2001","1999","2000","2003"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Atari 2600 hangi yıl piyasaya çıktı?', '["1977","1975","1976","1979"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Viking 1 görevinin hedefi hangi gök cismiydi?', '["Mars","Venüs","Ay","Satürn"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('New Horizons''ın 2015 geçişi görevinin hedefi hangi gök cismiydi?', '["Plüton","Satürn","Merkür","Neptün"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Mass Effect'' oyununu hangi stüdyo geliştirdi?', '["BioWare","Mojang","Bungie","Toby Fox"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Hollow Knight'' oyununu hangi stüdyo geliştirdi?', '["Team Cherry","Naughty Dog","id Software","FromSoftware"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Alan Wake'' oyununu hangi stüdyo geliştirdi?', '["Remedy Entertainment","Bethesda Game Studios","Supergiant Games","Insomniac Games"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Microsoft Windows XP ilk kez hangi yıl yayımlandı?', '["2001","1999","2000","2003"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('İlk Apple iMac ilk kez hangi yıl yayımlandı?', '["1998","1997","1999","2001"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Nintendo DS, Kuzey Amerika''da ilk kez hangi yıl yayımlandı?', '["2004","2003","2005","2007"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('eBay''in ilk adı neydi?', '["AuctionWeb","Relentless","TheFacebook","Facemash"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apollo 11’in Ay modülünün çağrı adı neydi?', '["Eagle","Orion","Snoopy","Falcon"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Hubble''ı 1990''da yörüngeye taşıma görevi için kullanılan aracın adı hangisiydi?', '["Discovery","Endeavour","Sojourner","Curiosity"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('VHS video kaset standardını geliştiren kuruluş hangisidir?', '["JVC","IBM","Sony","Adobe"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Sputnik 1''de kaç anten bulunuyordu?', '["4","2","3","5"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('TRS-80 hangi şirket tarafından üretilmiştir?', '["Tandy","Apple","Atari","Nokia"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('DX7 synthesizer hangi şirket tarafından üretilmiştir?', '["Yamaha","Roland","Apple","Atari"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Galileo sondasını 1989''da fırlatan mekik görevi için kullanılan aracın adı hangisiydi?', '["Atlantis","Columbia","Discovery","Endeavour"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('PostScript sayfa tanımlama standardını geliştiren kuruluş hangisidir?', '["Adobe","Xerox","Intel","Nokia"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Nintendo Wii aygıtı geliştirilirken hangi kod adı kullanıldı?', '["Revolution","Dolphin","Project Natal","Durango"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Standart USB 2.0 Type-A fişinde kaç metal temas ucu vardır?', '["4","2","3","5"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('HDMI Type-A fişinde kaç pim vardır?', '["19","15","17","21"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Nintendo GameCube''un geliştirme kod adı neydi?', '["Dolphin","Revolution","Project Natal","Project Scorpio"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Sony PlayStation VR geliştirilirken hangi kod adı kullanıldı?', '["Project Morpheus","Project Scorpio","Project Natal","Project Revolution"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Apollo 13''te Ay''a iniş iptal edilince sığınak olarak kullanılan aracın çağrı adı neydi?', '["Aquarius","Odyssey","Endeavour","Challenger"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('1970''teki Apollo 13 uçuşunun komuta kapsülü hangi çağrı adıyla anılıyordu?', '["Odyssey","Columbia","Endeavour","Challenger"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Sachin Tendulkar hangi spor dalıyla tanınır?', '["Kriket","Futbol","Eskrim","Halter"]'::jsonb, 0, 'spor', 'global', null, 2),
('Jonah Lomu hangi spor dalıyla tanınır?', '["Ragbi","Tenis","Yüzme","Kayak"]'::jsonb, 0, 'spor', 'global', null, 2),
('Simone Biles hangi spor dalıyla tanınır?', '["Jimnastik","Basketbol","Badminton","Atletizm"]'::jsonb, 0, 'spor', 'global', null, 2),
('Eddy Merckx hangi spor dalıyla tanınır?', '["Bisiklet","Atletizm","Basketbol","Beyzbol"]'::jsonb, 0, 'spor', 'global', null, 2),
('Mikaela Shiffrin hangi spor dalıyla tanınır?', '["Kayak","Tenis","Yüzme","Ragbi"]'::jsonb, 0, 'spor', 'global', null, 2),
('Teddy Riner hangi spor dalıyla tanınır?', '["Judo","Golf","Boks","Tenis"]'::jsonb, 0, 'spor', 'global', null, 2),
('Emirates Stadium hangi futbol kulübünün stadıdır?', '["Arsenal","Chelsea","Benfica","Rangers"]'::jsonb, 0, 'spor', 'global', null, 2),
('Signal Iduna Park hangi futbol kulübünün stadıdır?', '["Borussia Dortmund","Manchester United","Tottenham Hotspur","Olympique Lyonnais"]'::jsonb, 0, 'spor', 'global', null, 2),
('2024 yılında Goodison Park''ı iç saha stadı olarak kullanan kulüp hangisiydi?', '["Everton","Arsenal","Chelsea","Benfica"]'::jsonb, 0, 'spor', 'global', null, 2),
('Stadio Diego Armando Maradona hangi futbol kulübünün stadıdır?', '["Napoli","Celtic","Arsenal","Chelsea"]'::jsonb, 0, 'spor', 'global', null, 2),
('Davis Cup hangi spor dalında verilen bir kupadır?', '["Tenis","Yüzme","Kayak","Ragbi"]'::jsonb, 0, 'spor', 'global', null, 2),
('Larry O''Brien Trophy hangi spor dalında verilen bir kupadır?', '["Basketbol","Jimnastik","Badminton","Atletizm"]'::jsonb, 0, 'spor', 'global', null, 2),
('Johan Cruyff hangi forma numarasıyla özdeşleşmiştir?', '["14","10","11","12"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Love'' terimi hangi sporla ilişkilidir?', '["Tenis","Yüzme","Kayak","Ragbi"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Alley-oop'' terimi hangi sporla ilişkilidir?', '["Basketbol","Jimnastik","Badminton","Atletizm"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Home run'' terimi hangi sporla ilişkilidir?', '["Beyzbol","Futbol","Atletizm","Bisiklet"]'::jsonb, 0, 'spor', 'global', null, 2),
('Tony Hawk hangi spor dalıyla tanınır?', '["Kaykay","Futbol","Eskrim","Halter"]'::jsonb, 0, 'spor', 'global', null, 2),
('Kelly Slater hangi spor dalıyla tanınır?', '["Sörf","Golf","Boks","Yüzme"]'::jsonb, 0, 'spor', 'global', null, 2),
('Estádio da Luz hangi futbol kulübünün stadıdır?', '["Benfica","Arsenal","Chelsea","Rangers"]'::jsonb, 0, 'spor', 'global', null, 3),
('''Off-spin'' terimi hangi sporla ilişkilidir?', '["Kriket","Futbol","Eskrim","Halter"]'::jsonb, 0, 'spor', 'global', null, 3),
('Roger Federer''in ilk Wimbledon şampiyonluğu hangi yılda gerçekleşti?', '["2003","2001","2002","2005"]'::jsonb, 0, 'spor', 'global', null, 3),
('Serena Williams''ın ilk Grand Slam tekler şampiyonluğu hangi yılda gerçekleşti?', '["1999","1997","1998","2001"]'::jsonb, 0, 'spor', 'global', null, 3),
('Michael Schumacher''in ilk Formula 1 şampiyonluğu hangi yılda gerçekleşti?', '["1994","1993","1995","1997"]'::jsonb, 0, 'spor', 'global', null, 3),
('Kareem Abdul-Jabbar, Lakers''a geçmeden önce hangi NBA takımında oynadı?', '["Milwaukee Bucks","Chicago Bulls","Boston Celtics","Detroit Pistons"]'::jsonb, 0, 'spor', 'global', null, 3),
('Calcutta Cup hangi spor dalındaki bir rekabette verilir?', '["Ragbi","Kriket","Beyzbol","Basketbol"]'::jsonb, 0, 'spor', 'global', null, 3),
('''Swiss Maestro'' lakabıyla anılan tenisçi kimdir?', '["Roger Federer","Rafael Nadal","Novak Djokovic","Stan Wawrinka"]'::jsonb, 0, 'spor', 'global', null, 3),
('''Güneş Kral'' lakabı hangi hükümdar için kullanılmıştır?', '["Louis XIV","Richard I","George VI","Henry VIII"]'::jsonb, 0, 'tarih', 'global', null, 2),
('HMS Beagle gemisi hangi tarihî kişinin yolculuğuyla ilişkilidir?', '["Charles Darwin","Roald Amundsen","Francis Drake","Vasco da Gama"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Amundsen''in 1910''da Güney Kutbu seferine çıktığı geminin adı neydi?', '["Fram","Beagle","Endurance","Terra Nova"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Domesday Book hangi olayla ilişkilidir?', '["İngiltere''nin Norman fethi","İngiltere''nin Reform hareketi","İngiltere''nin sanayileşmesi","İngiltere''nin iç savaşı"]'::jsonb, 0, 'tarih', 'global', null, 3),
('''Goodfellas'' filmini kim yönetmiştir?', '["Martin Scorsese","Stanley Kubrick","Robert Zemeckis","Steven Spielberg"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Apocalypse Now'' filmini kim yönetmiştir?', '["Francis Ford Coppola","Guillermo del Toro","Quentin Tarantino","Alejandro González Iñárritu"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Jackie Brown'' filmini kim yönetmiştir?', '["Quentin Tarantino","Christopher Nolan","Steven Spielberg","Alfred Hitchcock"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Memento'' filmini kim yönetmiştir?', '["Christopher Nolan","Quentin Tarantino","Steven Spielberg","Alfred Hitchcock"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Edward Scissorhands'' filmini kim yönetmiştir?', '["Tim Burton","Sam Mendes","Danny Boyle","Ridley Scott"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''The Green Mile'' filmini kim yönetmiştir?', '["Frank Darabont","Akira Kurosawa","Martin Scorsese","Stanley Kubrick"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''The Truman Show'' filmini kim yönetmiştir?', '["Peter Weir","Tim Burton","Sam Mendes","Danny Boyle"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Arrival'' filmini kim yönetmiştir?', '["Denis Villeneuve","Steven Spielberg","Alfred Hitchcock","Martin Scorsese"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Die Hard''daki John McClane karakterini hangi oyuncu canlandırmıştır?', '["Bruce Willis","Keanu Reeves","Heath Ledger","Hugh Jackman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('Skyfall''daki James Bond karakterini hangi oyuncu canlandırmıştır?', '["Daniel Craig","Bruce Willis","Keanu Reeves","Heath Ledger"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Titanic'' filminin müziklerini kim bestelemiştir?', '["James Horner","Danny Elfman","Howard Shore","John Williams"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Back to the Future'' filminin müziklerini kim bestelemiştir?', '["Alan Silvestri","Rachel Portman","John Williams","Ennio Morricone"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Edward Scissorhands'' filminin müziklerini kim bestelemiştir?', '["Danny Elfman","Howard Shore","James Horner","John Williams"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''The Shawshank Redemption'' filminin müziklerini kim bestelemiştir?', '["Thomas Newman","John Williams","Clint Mansell","Danny Elfman"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''One Flew Over the Cuckoo''s Nest'' filminin uyarlandığı kitabın yazarı kimdir?', '["Ken Kesey","Mario Puzo","Stephen King","Irvine Welsh"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Requiem for a Dream'' filminin müziklerini kim bestelemiştir?', '["Clint Mansell","John Williams","Thomas Newman","Danny Elfman"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''The Imitation Game'' filminin müziklerini kim bestelemiştir?', '["Alexandre Desplat","Michael Giacchino","Bernard Herrmann","Ennio Morricone"]'::jsonb, 0, 'sinema', 'global', null, 3),
('1996 yapımı ''Emma'' filminin müziklerini kim bestelemiştir?', '["Rachel Portman","Alan Silvestri","John Williams","Ennio Morricone"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Trainspotting'' filminin uyarlandığı kitabın yazarı kimdir?', '["Irvine Welsh","Stephen King","Thomas Harris","Winston Groom"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Never Let Me Go'' filminin uyarlandığı kitabın yazarı kimdir?', '["Kazuo Ishiguro","Philip K. Dick","Peter Benchley","Anthony Burgess"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Fight Club'' filminin uyarlandığı romanı kim yazmıştır?', '["Chuck Palahniuk","Bret Easton Ellis","Don DeLillo","Jonathan Franzen"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Pulp Fiction''da Butch''un aile yadigârı nesnesi hangisidir?', '["Kol saati","Çakı","Çakmak","Cep pusulası"]'::jsonb, 0, 'sinema', 'global', null, 3),
('Geleneksel İskoç porridge tarifinde hangi tahıl kullanılır?', '["Yulaf","Mısır","Pirinç","Arpa"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Geleneksel tabbouleh tarifinde kullanılan tahıl ürünü hangisidir?', '["Bulgur","Pirinç","Kuskus","Kinoa"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Marzipan geleneksel olarak hangi kuruyemişle yapılır?', '["Badem","Ceviz","Fındık","Kaju"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Tiramisu için geleneksel olarak hangi peynir kullanılır?', '["Mascarpone","Mozzarella","Gorgonzola","Roquefort"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Cannoli dolgusu için geleneksel olarak hangi peynir kullanılır?', '["Ricotta","Cheddar","Gruyère","Parmesan"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Pesto alla genovese tarifinin ayırt edici bitkisi veya baharatı hangisidir?', '["Fesleğen","Biberiye","Zencefil","Karanfil"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Fusilli makarnası hangi biçimdedir?', '["Burgu","Kelebek","Kısa tüp","Küçük kulak"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Fettuccine makarnası hangi biçimdedir?', '["Geniş şerit","Küçük kulak","Deniz kabuğu","İnce uzun tel"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Penne makarnası hangi biçimdedir?', '["Kısa tüp","Kelebek","Burgu","Küçük kulak"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Aziz Patrick Günü için hangi bitki sembol olarak kullanılır?', '["Yonca","Defne","Bambu","Ökseotu"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Birleşik Krallık''ta Anma Günü için hangi bitki sembol olarak kullanılır?', '["Gelincik","Yonca","Ökseotu","Peygamber çiçeği"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('1903 patentli otomobil cam sileceği ile tanınan mucit veya tasarımcı kimdir?', '["Mary Anderson","Louis Braille","Leslie Scott","Alfred Butts"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('1849 patentli çengelli iğne ile tanınan mucit veya tasarımcı kimdir?', '["Walter Hunt","Laszlo Biro","Earl Tupper","Ernő Rubik"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Jenga oyununda temel olarak hangi nesne kullanılır?', '["Ahşap bloklar","Harfli taşlar","Numaralı toplar","Renkli çubuklar"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Hush Puppies markasının ambleminde hangi hayvan görülür?', '["Köpek","Aslan","Timsah","Boğa"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Garfield''ın köpek arkadaşının adı nedir?', '["Odie","Daisy","Pluto","Goofy"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Donald Duck''ın kız arkadaşının adı nedir?', '["Daisy","Pluto","Goofy","Porky"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Pad thai hangi ülkenin mutfağıyla özdeşleşmiştir?', '["Tayland","İspanya","Japonya","Portekiz"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Wiener schnitzel hangi ülkenin mutfağıyla özdeşleşmiştir?', '["Avusturya","Hindistan","İngiltere","Portekiz"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Aziz Patrick Günü hangi tarihte kutlanır?', '["17 Mart","31 Ekim","1 Mayıs","5 Kasım"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kore''nin geleneksel tören giysisinin adı nedir?', '["Hanbok","Kimono","Dirndl","Poncho"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Hindistan''da vücuda sarılarak giyilen uzun kumaş giysinin adı nedir?', '["Sari","Kilt","Kimono","Hanbok"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik Jenga setindeki ahşap blok kaç tanedir?', '["54","48","60","64"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Eiffel Kulesi''nin zemine dayanan kaç ayağı vardır?', '["4","2","3","5"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Golden Gate Köprüsü''nün kaç ana kulesi vardır?', '["2","3","4","5"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Geleneksel şarap şişesi tıpası temel olarak hangi malzemeden yapılır?', '["Mantar","Grafit","Kauçuk","Balmumu"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Tenis topunun iç gövdesinin ana malzemesi hangisidir?', '["Kauçuk","Mantar","Deri","Keçe"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Geleneksel tagine kabının kapağı hangi biçimdedir?', '["Konik","Kübik","Düz disk","Silindir"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Klasik Cluedo setindeki altı silahtan hangisi biridir?', '["Hançer","Balta","Tokmak","Tüfek"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Béarnaise sosu tarifinin ayırt edici bitkisi veya baharatı hangisidir?', '["Tarhun","Safran","Tarçın","Dereotu"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Poire belle Hélène geleneksel olarak hangi meyveyle yapılır?', '["Armut","Limon","Vişne","Çilek"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Orecchiette makarnası hangi biçimdedir?', '["Küçük kulak","Geniş şerit","Deniz kabuğu","İnce uzun tel"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Conchiglie makarnası hangi biçimdedir?', '["Deniz kabuğu","Küçük kulak","İnce uzun tel","Pirinç tanesi"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Orzo makarnası hangi biçimdedir?', '["Pirinç tanesi","İnce uzun tel","Deniz kabuğu","Küçük kulak"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Rogan josh hangi ülkenin mutfağıyla özdeşleşmiştir?', '["Hindistan","Avusturya","İngiltere","Portekiz"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Guy Fawkes Gecesi hangi tarihte kutlanır?', '["5 Kasım","17 Mart","31 Ekim","1 Mayıs"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Batı Hristiyanlığı takviminde Epifani hangi tarihte kutlanır?', '["6 Ocak","1 Ocak","17 Mart","31 Ekim"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Bavyera''nın geleneksel kadın giysisinin adı nedir?', '["Dirndl","Kimono","Hanbok","Poncho"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Çift altılı standart bir domino setinde kaç taş bulunur?', '["28","24","30","32"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Geleneksel peynir fondüsünde ekmek tencereye hangi araçla batırılır?', '["Uzun çatal","Tahta kaşık","Metal kepçe","Bambu çubuk"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Piñata geleneğinde şeker dolu nesne neyle kırılır?', '["Sopa","Çekiç","Makas","Tahta kepçe"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Cluedo oyununu tasarlayan İngiliz kimdir?', '["Anthony Pratt","Alfred Butts","Leslie Scott","Elizabeth Magie"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Gizli Bahçe'' kitabının yazarı kimdir?', '["Frances Hodgson Burnett","Robert Louis Stevenson","Antoine de Saint-Exupéry","F. Scott Fitzgerald"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Zamanda Kıvrılma'' kitabının yazarı kimdir?', '["Madeleine L''Engle","Charlotte Brontë","Arthur Conan Doyle","Ernest Hemingway"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Coraline'' kitabının yazarı kimdir?', '["Neil Gaiman","Jane Austen","Bram Stoker","Jules Verne"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Altın Pusula'' kitabının yazarı kimdir?', '["Philip Pullman","John Steinbeck","Charles Dickens","George Orwell"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Ulysses'' romanının olayları ağırlıklı olarak hangi şehirde geçer?', '["Dublin","Londra","Boston","Paris"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Jane Eyre karakterinin mesleği nedir?', '["Mürebbiye","İtfaiyeci","Hemşire","Gazeteci"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Winnie-the-Pooh hangi tür hayvandır?', '["Ayı","At","Fare","Kurt"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Hayvan Çiftliği''ndeki Boxer hangi tür hayvandır?', '["At","Eşek","Keçi","İnek"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Yüzüklerin Efendisi''ndeki Boromir karakterinin babası kimdir?', '["Denethor","Arathorn","Thranduil","Elrond"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Miss Havisham hangi romandaki karakterdir?', '["Büyük Umutlar","Oliver Twist","Frankenstein","Gurur ve Önyargı"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Demiryolu Çocukları'' kitabının yazarı kimdir?', '["Edith Nesbit","Mary Shelley","J. M. Barrie","Ray Bradbury"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Rüzgâr Söğütlerde'' kitabının yazarı kimdir?', '["Kenneth Grahame","Charles Dickens","Agatha Christie","John Steinbeck"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Siyah İnci'' kitabının yazarı kimdir?', '["Anna Sewell","Jane Austen","Bram Stoker","Jules Verne"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Tom Sawyer''ın üvey kardeşinin adı nedir?', '["Sid","Ben","Joe","Huck"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Küçük Kadınlar''da Jo''nun en büyük ablasının adı nedir?', '["Meg","Amy","Beth","Mary"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('The Fountainhead''deki Howard Roark karakterinin mesleği nedir?', '["Mimar","Avukat","Doktor","Gazeteci"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Ron Weasley''nin baykuşunun adı nedir?', '["Pigwidgeon","Crookshanks","Buckbeak","Fang"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Saki hangi yazarın takma adıdır?', '["Hector Hugh Munro","Eric Arthur Blair","Charlotte Brontë","Charles Dodgson"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Ellis Bell hangi yazarın takma adıdır?', '["Emily Brontë","Karen Blixen","Samuel Clemens","Mary Ann Evans"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('''Tom''un Gece Yarısı Bahçesi'' kitabının yazarı kimdir?', '["Philippa Pearce","Charles Dickens","Agatha Christie","John Steinbeck"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Jane Eyre''in çocukken gönderildiği okulun adı nedir?', '["Lowood","Hogwarts","Smeltings","Nevermore"]'::jsonb, 0, 'edebiyat', 'global', null, 3)
on conflict (soru) do nothing;

-- ---------------------------------------------------- İngilizce çeviri
insert into public.question_translations (question_id, dil, soru, secenekler)
select q.id, 'en', v.en_soru, v.en_secenekler
  from (values
  ('Grant Wood''un ''Amerikan Gotiği'' tablosu hangi müzenin koleksiyonundadır?', 'Which museum holds Grant Wood''s ''American Gothic''?', '["Art Institute of Chicago","Kunsthistorisches Museum","Philadelphia Museum of Art","Accademia Gallery"]'::jsonb),
  ('''Arnolfini Portresi'' tablosu hangi müzenin koleksiyonundadır?', 'Which museum holds ''The Arnolfini Portrait''?', '["National Gallery","Borghese Gallery","Accademia Gallery","Alte Pinakothek"]'::jsonb),
  ('Rodin''in ''Düşünen Adam'' heykelinin dökümlerinde hangi metal kullanılır?', 'Which metal is used for casts of Rodin''s ''The Thinker''?', '["Bronze","Iron","Steel","Silver"]'::jsonb),
  ('Özgürlük Heykeli''nin dış kaplamasında hangi metal kullanılmıştır?', 'Which metal forms the outer skin of the Statue of Liberty?', '["Copper","Iron","Steel","Silver"]'::jsonb),
  ('Paul Gauguin ressam olmadan önce hangi meslekte çalışıyordu?', 'What was Paul Gauguin''s job before becoming a painter?', '["Stockbroker","Customs officer","Accountant","Teacher"]'::jsonb),
  ('''Afgan Kızı'' fotoğrafını kim çekmiştir?', 'Who took the photograph ''Afghan Girl''?', '["Steve McCurry","Dorothea Lange","Yousuf Karsh","Elliott Erwitt"]'::jsonb),
  ('''Mavi At I'' tablosunun ressamı kimdir?', 'Who painted ''Blue Horse I''?', '["Franz Marc","Caravaggio","Grant Wood","Edgar Degas"]'::jsonb),
  ('''Çiçek Taşıyıcısı'' tablosunun ressamı kimdir?', 'Who painted ''The Flower Carrier''?', '["Diego Rivera","Claude Monet","Paul Cézanne","Paul Gauguin"]'::jsonb),
  ('''Otoportre, Dikenli Kolye ve Sinekkuşu'' tablosunun ressamı kimdir?', 'Who painted ''Self-Portrait with Thorn Necklace and Hummingbird''?', '["Frida Kahlo","Edgar Degas","Claude Monet","Paul Cézanne"]'::jsonb),
  ('''Çiçekli İki Tahitili Kadın'' tablosunun ressamı kimdir?', 'Who painted ''Two Tahitian Women''?', '["Paul Gauguin","Claude Monet","Paul Cézanne","Gustav Klimt"]'::jsonb),
  ('''Kızıl Balıklar'' tablosunun ressamı kimdir?', 'Who painted ''Goldfish''?', '["Henri Matisse","Édouard Manet","René Magritte","Salvador Dalí"]'::jsonb),
  ('Tac Mahal''in beyaz dış cephesinin ana malzemesi hangisidir?', 'What is the main material of the Taj Mahal''s white exterior?', '["Marble","Granite","Travertine","Sandstone"]'::jsonb),
  ('Louvre Piramidi''nin yüzey panelleri hangi malzemedendir?', 'What are the surface panels of the Louvre Pyramid made from?', '["Glass","Acrylic","Polycarbonate","Polyester"]'::jsonb),
  ('Rushmore Dağı''ndaki dört başkan yüzünden en soldaki kime aittir?', 'Which president is depicted by the leftmost face at Mount Rushmore?', '["George Washington","Thomas Jefferson","Theodore Roosevelt","Abraham Lincoln"]'::jsonb),
  ('Monet''nin Giverny göletinden esinlenen tablo dizisinin adı nedir?', 'What is the title of Monet''s series inspired by his Giverny pond?', '["Water Lilies","Dancers","Sunflowers","Black Paintings"]'::jsonb),
  ('Van Gogh''un ''Yıldızlı Gece'' tablosundaki köyde hangi yapının sivri kulesi yükselir?', 'Which building has a pointed steeple in the village in Van Gogh''s ''The Starry Night''?', '["Church","Palace","Factory","Town hall"]'::jsonb),
  ('Rousseau''nun ''Uyuyan Çingene'' tablosunda uyuyan kadının yanında hangi hayvan durur?', 'Which animal stands beside the sleeping woman in Rousseau''s ''The Sleeping Gypsy''?', '["Lion","Tiger","Giraffe","Rhinoceros"]'::jsonb),
  ('Hopper''ın ''Gece Kuşları'' tablosundaki lokantada toplam kaç kişi vardır?', 'How many people are in the diner in Hopper''s ''Nighthawks''?', '["4","3","5","6"]'::jsonb),
  ('Grant Wood''un ''Amerikan Gotiği'' tablosundaki erkeğin yüzünde hangi aksesuar vardır?', 'What accessory does the man wear on his face in Grant Wood''s ''American Gothic''?', '["Glasses","Monocle","Eye patch","Face mask"]'::jsonb),
  ('Manet''nin ''Olympia'' tablosunda yatağın ayak ucunda hangi hayvan bulunur?', 'Which animal is at the foot of the bed in Manet''s ''Olympia''?', '["Cat","Dog","Rabbit","Parrot"]'::jsonb),
  ('Özgürlük Heykeli''nin başındaki tacında kaç ışın bulunur?', 'How many rays are on the crown of the Statue of Liberty?', '["7","5","6","8"]'::jsonb),
  ('Klimt''in ''Öpücük'' tablosu hangi müzenin koleksiyonundadır?', 'Which museum holds Klimt''s ''The Kiss''?', '["Belvedere","Albertina","Leopold Museum","Kunsthistorisches Museum"]'::jsonb),
  ('''Christina''nın Dünyası'' tablosu hangi müzenin koleksiyonundadır?', 'Which museum holds ''Christina''s World''?', '["MoMA","Prado","Louvre","Uffizi"]'::jsonb),
  ('Fragonard''ın ''Salıncak'' tablosu hangi müzenin koleksiyonundadır?', 'Which museum''s collection includes Fragonard''s ''The Swing''?', '["Wallace Collection","Accademia Gallery","National Gallery","Kunsthistorisches Museum"]'::jsonb),
  ('Bruegel''in 1563 tarihli büyük ''Babil Kulesi'' tablosu hangi müzededir?', 'Which museum houses Bruegel''s large ''The Tower of Babel'' painting from 1563?', '["Kunsthistorisches Museum","Art Institute of Chicago","Philadelphia Museum of Art","Accademia Gallery"]'::jsonb),
  ('Berlin Yahudi Müzesi tasarımını yapan mimar kimdir?', 'Who designed the Jewish Museum Berlin?', '["Daniel Libeskind","Frank Lloyd Wright","Walter Gropius","Oscar Niemeyer"]'::jsonb),
  ('Sargent''ın ''Madam X'' portresindeki kadın kimdir?', 'Who is the woman in Sargent''s ''Madame X''?', '["Virginie Gautreau","Adele Bloch-Bauer","Elizabeth Siddal","Jeanne Hébuterne"]'::jsonb),
  ('Millais''nin ''Ophelia'' tablosuna model olan kadın kimdir?', 'Who modelled for Millais''s ''Ophelia''?', '["Elizabeth Siddal","Jeanne Hébuterne","Lisa Gherardini","Virginie Gautreau"]'::jsonb),
  ('''Dalí Atomicus'' fotoğrafını kim çekmiştir?', 'Who took the photograph ''Dalí Atomicus''?', '["Philippe Halsman","Robert Doisneau","Dorothea Lange","Alfred Eisenstaedt"]'::jsonb),
  ('''Çingene Kızı'' tablosunun ressamı kimdir?', 'Who painted ''The Gypsy Girl''?', '["Frans Hals","Caravaggio","Grant Wood","Edgar Degas"]'::jsonb),
  ('John Bonham hangi grubun üyesiydi?', 'Which band was John Bonham a member of?', '["Led Zeppelin","Dire Straits","The Beatles","Deep Purple"]'::jsonb),
  ('Stewart Copeland hangi grubun üyesiydi?', 'Which band was Stewart Copeland a member of?', '["The Police","Pink Floyd","The Beatles","Deep Purple"]'::jsonb),
  ('Nick Mason hangi grubun üyesiydi?', 'Which band was Nick Mason a member of?', '["Pink Floyd","The Police","The Beatles","Deep Purple"]'::jsonb),
  ('Glenn Frey hangi grubun üyesiydi?', 'Which band was Glenn Frey a member of?', '["Eagles","R.E.M.","Queen","Nirvana"]'::jsonb),
  ('Ray Manzarek hangi grubun üyesiydi?', 'Which band was Ray Manzarek a member of?', '["The Doors","Metallica","Radiohead","Pink Floyd"]'::jsonb),
  ('Jon Lord hangi grubun üyesiydi?', 'Which band was Jon Lord a member of?', '["Deep Purple","The Beatles","Pink Floyd","Led Zeppelin"]'::jsonb),
  ('Peter Gabriel hangi grubun üyesiydi?', 'Which band was Peter Gabriel a member of?', '["Genesis","Nirvana","The Who","Eagles"]'::jsonb),
  ('Benny Goodman en çok hangi enstrümanla tanınır?', 'Which instrument is Benny Goodman best known for playing?', '["Clarinet","Trumpet","Drums","Saxophone"]'::jsonb),
  ('Ian Anderson en çok hangi enstrümanla tanınır?', 'Which instrument is Ian Anderson best known for playing?', '["Flute","Guitar","Violin","Drums"]'::jsonb),
  ('''Brothers in Arms'' albümü hangi gruba aittir?', 'Which band released ''Brothers in Arms''?', '["Dire Straits","Led Zeppelin","The Beatles","Deep Purple"]'::jsonb),
  ('''Machine Head'' albümü hangi gruba aittir?', 'Which band released ''Machine Head''?', '["Deep Purple","The Beatles","Pink Floyd","Led Zeppelin"]'::jsonb),
  ('''Eleanor Rigby'' şarkısı ilk olarak hangi albümde yayımlandı?', 'Which album first featured ''Eleanor Rigby''?', '["Revolver","Let It Be","Abbey Road","Rubber Soul"]'::jsonb),
  ('''Norwegian Wood'' şarkısı ilk olarak hangi albümde yayımlandı?', 'Which album first featured ''Norwegian Wood''?', '["Rubber Soul","Abbey Road","Let It Be","The White Album"]'::jsonb),
  ('Geddy Lee hangi grubun üyesiydi?', 'Which band was Geddy Lee a member of?', '["Rush","ABBA","Blur","Queen"]'::jsonb),
  ('Andy Rourke hangi grubun üyesiydi?', 'Which band was Andy Rourke a member of?', '["The Smiths","Pink Floyd","The Police","The Beatles"]'::jsonb),
  ('Toots Thielemans en çok hangi enstrümanla tanınır?', 'Which instrument is Toots Thielemans best known for playing?', '["Harmonica","Saxophone","Bass guitar","Trumpet"]'::jsonb),
  ('''Norma'' operasını kim bestelemiştir?', 'Who composed the opera ''Norma''?', '["Vincenzo Bellini","Benjamin Britten","Giacomo Puccini","Gioachino Rossini"]'::jsonb),
  ('''Salome'' operasını kim bestelemiştir?', 'Who composed the opera ''Salome''?', '["Richard Strauss","Giacomo Puccini","Giuseppe Verdi","Richard Wagner"]'::jsonb),
  ('Dreamcast hangi şirket tarafından üretilmiştir?', 'Which company made Dreamcast?', '["Sega","Sony","Palm","Korg"]'::jsonb),
  ('Amiga 500 hangi şirket tarafından üretilmiştir?', 'Which company made Amiga 500?', '["Commodore","Microsoft","Panasonic","Nintendo"]'::jsonb),
  ('2600 oyun konsolu hangi şirket tarafından üretilmiştir?', 'Which company made the 2600 games console?', '["Atari","Apple","Nokia","Canon"]'::jsonb),
  ('LaserJet yazıcı serisi hangi şirket tarafından üretilmiştir?', 'Which company made the LaserJet printer range?', '["Hewlett-Packard","Texas Instruments","Sinclair Research","Microsoft"]'::jsonb),
  ('9000 Communicator hangi şirket tarafından üretilmiştir?', 'Which company made 9000 Communicator?', '["Nokia","Apple","Atari","Canon"]'::jsonb),
  ('RAZR V3 hangi şirket tarafından üretilmiştir?', 'Which company made RAZR V3?', '["Motorola","Nintendo","Logitech","Ericsson"]'::jsonb),
  ('İlk Sony PlayStation, Japonya''da hangi yıl piyasaya çıktı?', 'In which year did Sony release the original PlayStation in Japan?', '["1994","1993","1995","1997"]'::jsonb),
  ('Amazon Kindle''ın ilk modeli hangi yıl piyasaya çıktı?', 'In which year was the first Amazon Kindle released?', '["2007","2005","2006","2009"]'::jsonb),
  ('Nintendo Wii hangi yıl piyasaya çıktı?', 'In which year was Nintendo Wii released?', '["2006","2005","2007","2009"]'::jsonb),
  ('Microsoft Xbox''ın ilk modeli hangi yıl piyasaya çıktı?', 'In which year was the original Microsoft Xbox released?', '["2001","1999","2000","2003"]'::jsonb),
  ('Atari 2600 hangi yıl piyasaya çıktı?', 'In which year was Atari 2600 released?', '["1977","1975","1976","1979"]'::jsonb),
  ('Viking 1 görevinin hedefi hangi gök cismiydi?', 'Which celestial body was the main destination of Viking 1?', '["Mars","Venus","Moon","Saturn"]'::jsonb),
  ('New Horizons''ın 2015 geçişi görevinin hedefi hangi gök cismiydi?', 'Which celestial body was the main destination of the 2015 flyby by New Horizons?', '["Pluto","Saturn","Mercury","Neptune"]'::jsonb),
  ('''Mass Effect'' oyununu hangi stüdyo geliştirdi?', 'Which studio developed ''Mass Effect''?', '["BioWare","Mojang","Bungie","Toby Fox"]'::jsonb),
  ('''Hollow Knight'' oyununu hangi stüdyo geliştirdi?', 'Which studio developed ''Hollow Knight''?', '["Team Cherry","Naughty Dog","id Software","FromSoftware"]'::jsonb),
  ('''Alan Wake'' oyununu hangi stüdyo geliştirdi?', 'Which studio developed ''Alan Wake''?', '["Remedy Entertainment","Bethesda Game Studios","Supergiant Games","Insomniac Games"]'::jsonb),
  ('Microsoft Windows XP ilk kez hangi yıl yayımlandı?', 'In which year was Microsoft Windows XP released?', '["2001","1999","2000","2003"]'::jsonb),
  ('İlk Apple iMac ilk kez hangi yıl yayımlandı?', 'In which year was the first Apple iMac released?', '["1998","1997","1999","2001"]'::jsonb),
  ('Nintendo DS, Kuzey Amerika''da ilk kez hangi yıl yayımlandı?', 'In which year did Nintendo DS launch in North America?', '["2004","2003","2005","2007"]'::jsonb),
  ('eBay''in ilk adı neydi?', 'What was eBay originally called?', '["AuctionWeb","Relentless","TheFacebook","Facemash"]'::jsonb),
  ('Apollo 11’in Ay modülünün çağrı adı neydi?', 'What was the call sign of Apollo 11''s lunar module?', '["Eagle","Orion","Snoopy","Falcon"]'::jsonb),
  ('Hubble''ı 1990''da yörüngeye taşıma görevi için kullanılan aracın adı hangisiydi?', 'Which vehicle was used for launching Hubble into orbit in 1990?', '["Discovery","Endeavour","Sojourner","Curiosity"]'::jsonb),
  ('VHS video kaset standardını geliştiren kuruluş hangisidir?', 'Which organisation developed the VHS videocassette standard?', '["JVC","IBM","Sony","Adobe"]'::jsonb),
  ('Sputnik 1''de kaç anten bulunuyordu?', 'How many antennas did Sputnik 1 have?', '["4","2","3","5"]'::jsonb),
  ('TRS-80 hangi şirket tarafından üretilmiştir?', 'Which company made TRS-80?', '["Tandy","Apple","Atari","Nokia"]'::jsonb),
  ('DX7 synthesizer hangi şirket tarafından üretilmiştir?', 'Which company made DX7 synthesizer?', '["Yamaha","Roland","Apple","Atari"]'::jsonb),
  ('Galileo sondasını 1989''da fırlatan mekik görevi için kullanılan aracın adı hangisiydi?', 'Which vehicle was used for the 1989 shuttle launch of the Galileo probe?', '["Atlantis","Columbia","Discovery","Endeavour"]'::jsonb),
  ('PostScript sayfa tanımlama standardını geliştiren kuruluş hangisidir?', 'Which organisation developed the PostScript page-description standard?', '["Adobe","Xerox","Intel","Nokia"]'::jsonb),
  ('Nintendo Wii aygıtı geliştirilirken hangi kod adı kullanıldı?', 'What was the development codename for Nintendo Wii?', '["Revolution","Dolphin","Project Natal","Durango"]'::jsonb),
  ('Standart USB 2.0 Type-A fişinde kaç metal temas ucu vardır?', 'How many metal contacts does a standard USB 2.0 Type-A plug have?', '["4","2","3","5"]'::jsonb),
  ('HDMI Type-A fişinde kaç pim vardır?', 'How many pins does a Type-A HDMI plug have?', '["19","15","17","21"]'::jsonb),
  ('Nintendo GameCube''un geliştirme kod adı neydi?', 'What was the development codename of Nintendo GameCube?', '["Dolphin","Revolution","Project Natal","Project Scorpio"]'::jsonb),
  ('Sony PlayStation VR geliştirilirken hangi kod adı kullanıldı?', 'What was the development codename of Sony PlayStation VR?', '["Project Morpheus","Project Scorpio","Project Natal","Project Revolution"]'::jsonb),
  ('Apollo 13''te Ay''a iniş iptal edilince sığınak olarak kullanılan aracın çağrı adı neydi?', 'What was the call sign of the vehicle used as a lifeboat after Apollo 13''s lunar landing was cancelled?', '["Aquarius","Odyssey","Endeavour","Challenger"]'::jsonb),
  ('1970''teki Apollo 13 uçuşunun komuta kapsülü hangi çağrı adıyla anılıyordu?', 'What was the call sign of the command capsule on Apollo 13''s 1970 flight?', '["Odyssey","Columbia","Endeavour","Challenger"]'::jsonb),
  ('Sachin Tendulkar hangi spor dalıyla tanınır?', 'Which sport is Sachin Tendulkar known for?', '["Cricket","Football","Fencing","Weightlifting"]'::jsonb),
  ('Jonah Lomu hangi spor dalıyla tanınır?', 'Which sport is Jonah Lomu known for?', '["Rugby","Tennis","Swimming","Skiing"]'::jsonb),
  ('Simone Biles hangi spor dalıyla tanınır?', 'Which sport is Simone Biles known for?', '["Gymnastics","Basketball","Badminton","Athletics"]'::jsonb),
  ('Eddy Merckx hangi spor dalıyla tanınır?', 'Which sport is Eddy Merckx known for?', '["Cycling","Athletics","Basketball","Baseball"]'::jsonb),
  ('Mikaela Shiffrin hangi spor dalıyla tanınır?', 'Which sport is Mikaela Shiffrin known for?', '["Skiing","Tennis","Swimming","Rugby"]'::jsonb),
  ('Teddy Riner hangi spor dalıyla tanınır?', 'Which sport is Teddy Riner known for?', '["Judo","Golf","Boxing","Tennis"]'::jsonb),
  ('Emirates Stadium hangi futbol kulübünün stadıdır?', 'Which football club plays at Emirates Stadium?', '["Arsenal","Chelsea","Benfica","Rangers"]'::jsonb),
  ('Signal Iduna Park hangi futbol kulübünün stadıdır?', 'Which football club plays at Signal Iduna Park?', '["Borussia Dortmund","Manchester United","Tottenham Hotspur","Olympique Lyonnais"]'::jsonb),
  ('2024 yılında Goodison Park''ı iç saha stadı olarak kullanan kulüp hangisiydi?', 'Which football club used Goodison Park for home matches in 2024?', '["Everton","Arsenal","Chelsea","Benfica"]'::jsonb),
  ('Stadio Diego Armando Maradona hangi futbol kulübünün stadıdır?', 'Which football club plays at Stadio Diego Armando Maradona?', '["Napoli","Celtic","Arsenal","Chelsea"]'::jsonb),
  ('Davis Cup hangi spor dalında verilen bir kupadır?', 'In which sport is the Davis Cup awarded?', '["Tennis","Swimming","Skiing","Rugby"]'::jsonb),
  ('Larry O''Brien Trophy hangi spor dalında verilen bir kupadır?', 'In which sport is the Larry O''Brien Trophy awarded?', '["Basketball","Gymnastics","Badminton","Athletics"]'::jsonb),
  ('Johan Cruyff hangi forma numarasıyla özdeşleşmiştir?', 'Which jersey number is closely associated with Johan Cruyff?', '["14","10","11","12"]'::jsonb),
  ('''Love'' terimi hangi sporla ilişkilidir?', 'Which sport uses the term ''Love''?', '["Tennis","Swimming","Skiing","Rugby"]'::jsonb),
  ('''Alley-oop'' terimi hangi sporla ilişkilidir?', 'Which sport uses the term ''Alley-oop''?', '["Basketball","Gymnastics","Badminton","Athletics"]'::jsonb),
  ('''Home run'' terimi hangi sporla ilişkilidir?', 'Which sport uses the term ''Home run''?', '["Baseball","Football","Athletics","Cycling"]'::jsonb),
  ('Tony Hawk hangi spor dalıyla tanınır?', 'Which sport is Tony Hawk known for?', '["Skateboarding","Football","Fencing","Weightlifting"]'::jsonb),
  ('Kelly Slater hangi spor dalıyla tanınır?', 'Which sport is Kelly Slater known for?', '["Surfing","Golf","Boxing","Swimming"]'::jsonb),
  ('Estádio da Luz hangi futbol kulübünün stadıdır?', 'Which football club plays at Estádio da Luz?', '["Benfica","Arsenal","Chelsea","Rangers"]'::jsonb),
  ('''Off-spin'' terimi hangi sporla ilişkilidir?', 'Which sport uses the term ''Off-spin''?', '["Cricket","Football","Fencing","Weightlifting"]'::jsonb),
  ('Roger Federer''in ilk Wimbledon şampiyonluğu hangi yılda gerçekleşti?', 'In which year did Roger Federer win his first Wimbledon title?', '["2003","2001","2002","2005"]'::jsonb),
  ('Serena Williams''ın ilk Grand Slam tekler şampiyonluğu hangi yılda gerçekleşti?', 'In which year did Serena Williams win her first Grand Slam singles title?', '["1999","1997","1998","2001"]'::jsonb),
  ('Michael Schumacher''in ilk Formula 1 şampiyonluğu hangi yılda gerçekleşti?', 'In which year did Michael Schumacher win his first Formula One title?', '["1994","1993","1995","1997"]'::jsonb),
  ('Kareem Abdul-Jabbar, Lakers''a geçmeden önce hangi NBA takımında oynadı?', 'Which NBA team did Kareem Abdul-Jabbar play for before joining the Lakers?', '["Milwaukee Bucks","Chicago Bulls","Boston Celtics","Detroit Pistons"]'::jsonb),
  ('Calcutta Cup hangi spor dalındaki bir rekabette verilir?', 'In which sport is the Calcutta Cup contested?', '["Rugby","Cricket","Baseball","Basketball"]'::jsonb),
  ('''Swiss Maestro'' lakabıyla anılan tenisçi kimdir?', 'Which tennis player is known as the ''Swiss Maestro''?', '["Roger Federer","Rafael Nadal","Novak Djokovic","Stan Wawrinka"]'::jsonb),
  ('''Güneş Kral'' lakabı hangi hükümdar için kullanılmıştır?', 'Which ruler was known as ''the Sun King''?', '["Louis XIV","Richard I","George VI","Henry VIII"]'::jsonb),
  ('HMS Beagle gemisi hangi tarihî kişinin yolculuğuyla ilişkilidir?', 'Whose voyage is associated with the ship HMS Beagle?', '["Charles Darwin","Roald Amundsen","Francis Drake","Vasco da Gama"]'::jsonb),
  ('Amundsen''in 1910''da Güney Kutbu seferine çıktığı geminin adı neydi?', 'What was the name of the ship Amundsen took on his 1910 South Pole expedition?', '["Fram","Beagle","Endurance","Terra Nova"]'::jsonb),
  ('Domesday Book hangi olayla ilişkilidir?', 'Which event is associated with Domesday Book?', '["The Norman conquest of England","The English Reformation","The Industrial Revolution in England","The English Civil War"]'::jsonb),
  ('''Goodfellas'' filmini kim yönetmiştir?', 'Who directed ''Goodfellas''?', '["Martin Scorsese","Stanley Kubrick","Robert Zemeckis","Steven Spielberg"]'::jsonb),
  ('''Apocalypse Now'' filmini kim yönetmiştir?', 'Who directed ''Apocalypse Now''?', '["Francis Ford Coppola","Guillermo del Toro","Quentin Tarantino","Alejandro González Iñárritu"]'::jsonb),
  ('''Jackie Brown'' filmini kim yönetmiştir?', 'Who directed ''Jackie Brown''?', '["Quentin Tarantino","Christopher Nolan","Steven Spielberg","Alfred Hitchcock"]'::jsonb),
  ('''Memento'' filmini kim yönetmiştir?', 'Who directed ''Memento''?', '["Christopher Nolan","Quentin Tarantino","Steven Spielberg","Alfred Hitchcock"]'::jsonb),
  ('''Edward Scissorhands'' filmini kim yönetmiştir?', 'Who directed ''Edward Scissorhands''?', '["Tim Burton","Sam Mendes","Danny Boyle","Ridley Scott"]'::jsonb),
  ('''The Green Mile'' filmini kim yönetmiştir?', 'Who directed ''The Green Mile''?', '["Frank Darabont","Akira Kurosawa","Martin Scorsese","Stanley Kubrick"]'::jsonb),
  ('''The Truman Show'' filmini kim yönetmiştir?', 'Who directed ''The Truman Show''?', '["Peter Weir","Tim Burton","Sam Mendes","Danny Boyle"]'::jsonb),
  ('''Arrival'' filmini kim yönetmiştir?', 'Who directed ''Arrival''?', '["Denis Villeneuve","Steven Spielberg","Alfred Hitchcock","Martin Scorsese"]'::jsonb),
  ('Die Hard''daki John McClane karakterini hangi oyuncu canlandırmıştır?', 'Which actor played John McClane in Die Hard?', '["Bruce Willis","Keanu Reeves","Heath Ledger","Hugh Jackman"]'::jsonb),
  ('Skyfall''daki James Bond karakterini hangi oyuncu canlandırmıştır?', 'Which actor played James Bond in Skyfall?', '["Daniel Craig","Bruce Willis","Keanu Reeves","Heath Ledger"]'::jsonb),
  ('''Titanic'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''Titanic''?', '["James Horner","Danny Elfman","Howard Shore","John Williams"]'::jsonb),
  ('''Back to the Future'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''Back to the Future''?', '["Alan Silvestri","Rachel Portman","John Williams","Ennio Morricone"]'::jsonb),
  ('''Edward Scissorhands'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''Edward Scissorhands''?', '["Danny Elfman","Howard Shore","James Horner","John Williams"]'::jsonb),
  ('''The Shawshank Redemption'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''The Shawshank Redemption''?', '["Thomas Newman","John Williams","Clint Mansell","Danny Elfman"]'::jsonb),
  ('''One Flew Over the Cuckoo''s Nest'' filminin uyarlandığı kitabın yazarı kimdir?', 'Who wrote the book adapted into ''One Flew Over the Cuckoo''s Nest''?', '["Ken Kesey","Mario Puzo","Stephen King","Irvine Welsh"]'::jsonb),
  ('''Requiem for a Dream'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''Requiem for a Dream''?', '["Clint Mansell","John Williams","Thomas Newman","Danny Elfman"]'::jsonb),
  ('''The Imitation Game'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for ''The Imitation Game''?', '["Alexandre Desplat","Michael Giacchino","Bernard Herrmann","Ennio Morricone"]'::jsonb),
  ('1996 yapımı ''Emma'' filminin müziklerini kim bestelemiştir?', 'Who composed the score for the 1996 film ''Emma''?', '["Rachel Portman","Alan Silvestri","John Williams","Ennio Morricone"]'::jsonb),
  ('''Trainspotting'' filminin uyarlandığı kitabın yazarı kimdir?', 'Who wrote the book adapted into ''Trainspotting''?', '["Irvine Welsh","Stephen King","Thomas Harris","Winston Groom"]'::jsonb),
  ('''Never Let Me Go'' filminin uyarlandığı kitabın yazarı kimdir?', 'Who wrote the book adapted into ''Never Let Me Go''?', '["Kazuo Ishiguro","Philip K. Dick","Peter Benchley","Anthony Burgess"]'::jsonb),
  ('''Fight Club'' filminin uyarlandığı romanı kim yazmıştır?', 'Who wrote the novel adapted into ''Fight Club''?', '["Chuck Palahniuk","Bret Easton Ellis","Don DeLillo","Jonathan Franzen"]'::jsonb),
  ('''Pulp Fiction''da Butch''un aile yadigârı nesnesi hangisidir?', 'What family heirloom does Butch treasure in ''Pulp Fiction''?', '["Wristwatch","Pocketknife","Lighter","Pocket compass"]'::jsonb),
  ('Geleneksel İskoç porridge tarifinde hangi tahıl kullanılır?', 'Which grain is used in traditional Scottish porridge?', '["Oats","Corn","Rice","Barley"]'::jsonb),
  ('Geleneksel tabbouleh tarifinde kullanılan tahıl ürünü hangisidir?', 'Which grain product is traditionally used in tabbouleh?', '["Bulgur","Rice","Couscous","Quinoa"]'::jsonb),
  ('Marzipan geleneksel olarak hangi kuruyemişle yapılır?', 'Which nut is traditionally used in marzipan?', '["Almonds","Walnuts","Hazelnuts","Cashews"]'::jsonb),
  ('Tiramisu için geleneksel olarak hangi peynir kullanılır?', 'Which cheese is traditionally used in tiramisu?', '["Mascarpone","Mozzarella","Gorgonzola","Roquefort"]'::jsonb),
  ('Cannoli dolgusu için geleneksel olarak hangi peynir kullanılır?', 'Which cheese is traditionally used in cannoli filling?', '["Ricotta","Cheddar","Gruyère","Parmesan"]'::jsonb),
  ('Pesto alla genovese tarifinin ayırt edici bitkisi veya baharatı hangisidir?', 'Which herb or spice is characteristic of pesto alla genovese?', '["Basil","Rosemary","Ginger","Cloves"]'::jsonb),
  ('Fusilli makarnası hangi biçimdedir?', 'What shape is fusilli pasta?', '["Spiral","Bow tie","Short tube","Little ear"]'::jsonb),
  ('Fettuccine makarnası hangi biçimdedir?', 'What shape is fettuccine pasta?', '["Wide ribbon","Little ear","Shell","Long thin strand"]'::jsonb),
  ('Penne makarnası hangi biçimdedir?', 'What shape is penne pasta?', '["Short tube","Bow tie","Spiral","Little ear"]'::jsonb),
  ('Aziz Patrick Günü için hangi bitki sembol olarak kullanılır?', 'Which plant is a symbol of St Patrick''s Day?', '["Shamrock","Laurel","Bamboo","Mistletoe"]'::jsonb),
  ('Birleşik Krallık''ta Anma Günü için hangi bitki sembol olarak kullanılır?', 'Which plant is a symbol of Remembrance Day in the United Kingdom?', '["Poppy","Shamrock","Mistletoe","Cornflower"]'::jsonb),
  ('1903 patentli otomobil cam sileceği ile tanınan mucit veya tasarımcı kimdir?', 'Who is associated with inventing or designing the windscreen wiper patented in 1903?', '["Mary Anderson","Louis Braille","Leslie Scott","Alfred Butts"]'::jsonb),
  ('1849 patentli çengelli iğne ile tanınan mucit veya tasarımcı kimdir?', 'Who is associated with inventing or designing the safety pin patented in 1849?', '["Walter Hunt","Laszlo Biro","Earl Tupper","Ernő Rubik"]'::jsonb),
  ('Jenga oyununda temel olarak hangi nesne kullanılır?', 'Which object is central to playing Jenga?', '["Wooden blocks","Letter tiles","Numbered balls","Coloured sticks"]'::jsonb),
  ('Hush Puppies markasının ambleminde hangi hayvan görülür?', 'Which animal appears in the Hush Puppies logo?', '["Dog","Lion","Crocodile","Bull"]'::jsonb),
  ('Garfield''ın köpek arkadaşının adı nedir?', 'What is the name of Garfield''s dog friend?', '["Odie","Daisy","Pluto","Goofy"]'::jsonb),
  ('Donald Duck''ın kız arkadaşının adı nedir?', 'What is the name of Donald Duck''s girlfriend?', '["Daisy","Pluto","Goofy","Porky"]'::jsonb),
  ('Pad thai hangi ülkenin mutfağıyla özdeşleşmiştir?', 'Which country''s cuisine is pad thai associated with?', '["Thailand","Spain","Japan","Portugal"]'::jsonb),
  ('Wiener schnitzel hangi ülkenin mutfağıyla özdeşleşmiştir?', 'Which country''s cuisine is Wiener schnitzel associated with?', '["Austria","India","England","Portugal"]'::jsonb),
  ('Aziz Patrick Günü hangi tarihte kutlanır?', 'On which date is St Patrick''s Day celebrated?', '["17 March","31 October","1 May","5 November"]'::jsonb),
  ('Kore''nin geleneksel tören giysisinin adı nedir?', 'What is Korea''s traditional ceremonial dress called?', '["Hanbok","Kimono","Dirndl","Poncho"]'::jsonb),
  ('Hindistan''da vücuda sarılarak giyilen uzun kumaş giysinin adı nedir?', 'What is the long cloth garment wrapped around the body in India called?', '["Sari","Kilt","Kimono","Hanbok"]'::jsonb),
  ('Klasik Jenga setindeki ahşap blok kaç tanedir?', 'How many wooden blocks are in a classic Jenga set?', '["54","48","60","64"]'::jsonb),
  ('Eiffel Kulesi''nin zemine dayanan kaç ayağı vardır?', 'How many legs support the Eiffel Tower?', '["4","2","3","5"]'::jsonb),
  ('Golden Gate Köprüsü''nün kaç ana kulesi vardır?', 'How many main towers does the Golden Gate Bridge have?', '["2","3","4","5"]'::jsonb),
  ('Geleneksel şarap şişesi tıpası temel olarak hangi malzemeden yapılır?', 'What is a traditional wine-bottle stopper made from?', '["Cork","Graphite","Rubber","Beeswax"]'::jsonb),
  ('Tenis topunun iç gövdesinin ana malzemesi hangisidir?', 'What is the main material of the inner body of a tennis ball?', '["Rubber","Cork","Leather","Felt"]'::jsonb),
  ('Geleneksel tagine kabının kapağı hangi biçimdedir?', 'What shape is the lid of a traditional tagine pot?', '["Conical","Cubic","Flat disc","Cylindrical"]'::jsonb),
  ('Klasik Cluedo setindeki altı silahtan hangisi biridir?', 'Which of these is one of the six weapons in classic Cluedo?', '["Dagger","Hatchet","Mallet","Rifle"]'::jsonb),
  ('Béarnaise sosu tarifinin ayırt edici bitkisi veya baharatı hangisidir?', 'Which herb or spice is characteristic of béarnaise sauce?', '["Tarragon","Saffron","Cinnamon","Dill"]'::jsonb),
  ('Poire belle Hélène geleneksel olarak hangi meyveyle yapılır?', 'Which fruit is traditionally used in Poire belle Hélène?', '["Pear","Lemon","Sour cherry","Strawberry"]'::jsonb),
  ('Orecchiette makarnası hangi biçimdedir?', 'What shape is orecchiette pasta?', '["Little ear","Wide ribbon","Shell","Long thin strand"]'::jsonb),
  ('Conchiglie makarnası hangi biçimdedir?', 'What shape is conchiglie pasta?', '["Shell","Little ear","Long thin strand","Rice grain"]'::jsonb),
  ('Orzo makarnası hangi biçimdedir?', 'What shape is orzo pasta?', '["Rice grain","Long thin strand","Shell","Little ear"]'::jsonb),
  ('Rogan josh hangi ülkenin mutfağıyla özdeşleşmiştir?', 'Which country''s cuisine is rogan josh associated with?', '["India","Austria","England","Portugal"]'::jsonb),
  ('Guy Fawkes Gecesi hangi tarihte kutlanır?', 'On which date is Guy Fawkes Night celebrated?', '["5 November","17 March","31 October","1 May"]'::jsonb),
  ('Batı Hristiyanlığı takviminde Epifani hangi tarihte kutlanır?', 'On which date is Epiphany celebrated in the Western Christian calendar?', '["6 January","1 January","17 March","31 October"]'::jsonb),
  ('Bavyera''nın geleneksel kadın giysisinin adı nedir?', 'What is the traditional Bavarian women''s dress called?', '["Dirndl","Kimono","Hanbok","Poncho"]'::jsonb),
  ('Çift altılı standart bir domino setinde kaç taş bulunur?', 'How many tiles are in a standard double-six domino set?', '["28","24","30","32"]'::jsonb),
  ('Geleneksel peynir fondüsünde ekmek tencereye hangi araçla batırılır?', 'Which utensil is used to dip bread into a traditional cheese fondue?', '["Long fork","Wooden spoon","Metal ladle","Bamboo chopstick"]'::jsonb),
  ('Piñata geleneğinde şeker dolu nesne neyle kırılır?', 'What is used to break the candy-filled object in the piñata tradition?', '["Stick","Hammer","Scissors","Wooden ladle"]'::jsonb),
  ('Cluedo oyununu tasarlayan İngiliz kimdir?', 'Which British designer created Cluedo?', '["Anthony Pratt","Alfred Butts","Leslie Scott","Elizabeth Magie"]'::jsonb),
  ('''Gizli Bahçe'' kitabının yazarı kimdir?', 'Who wrote ''The Secret Garden''?', '["Frances Hodgson Burnett","Robert Louis Stevenson","Antoine de Saint-Exupéry","F. Scott Fitzgerald"]'::jsonb),
  ('''Zamanda Kıvrılma'' kitabının yazarı kimdir?', 'Who wrote ''A Wrinkle in Time''?', '["Madeleine L''Engle","Charlotte Brontë","Arthur Conan Doyle","Ernest Hemingway"]'::jsonb),
  ('''Coraline'' kitabının yazarı kimdir?', 'Who wrote ''Coraline''?', '["Neil Gaiman","Jane Austen","Bram Stoker","Jules Verne"]'::jsonb),
  ('''Altın Pusula'' kitabının yazarı kimdir?', 'Who wrote ''Northern Lights''?', '["Philip Pullman","John Steinbeck","Charles Dickens","George Orwell"]'::jsonb),
  ('''Ulysses'' romanının olayları ağırlıklı olarak hangi şehirde geçer?', 'Which city is the main setting of ''Ulysses''?', '["Dublin","London","Boston","Paris"]'::jsonb),
  ('Jane Eyre karakterinin mesleği nedir?', 'What is Jane Eyre''s profession?', '["Governess","Fireman","Nurse","Journalist"]'::jsonb),
  ('Winnie-the-Pooh hangi tür hayvandır?', 'What kind of animal is Winnie-the-Pooh?', '["Bear","Horse","Mouse","Wolf"]'::jsonb),
  ('Hayvan Çiftliği''ndeki Boxer hangi tür hayvandır?', 'What kind of animal is Boxer in Animal Farm?', '["Horse","Donkey","Goat","Cow"]'::jsonb),
  ('Yüzüklerin Efendisi''ndeki Boromir karakterinin babası kimdir?', 'Who is Boromir''s father in The Lord of the Rings?', '["Denethor","Arathorn","Thranduil","Elrond"]'::jsonb),
  ('Miss Havisham hangi romandaki karakterdir?', 'In which novel does Miss Havisham appear?', '["Great Expectations","Oliver Twist","Frankenstein","Pride and Prejudice"]'::jsonb),
  ('''Demiryolu Çocukları'' kitabının yazarı kimdir?', 'Who wrote ''The Railway Children''?', '["Edith Nesbit","Mary Shelley","J. M. Barrie","Ray Bradbury"]'::jsonb),
  ('''Rüzgâr Söğütlerde'' kitabının yazarı kimdir?', 'Who wrote ''The Wind in the Willows''?', '["Kenneth Grahame","Charles Dickens","Agatha Christie","John Steinbeck"]'::jsonb),
  ('''Siyah İnci'' kitabının yazarı kimdir?', 'Who wrote ''Black Beauty''?', '["Anna Sewell","Jane Austen","Bram Stoker","Jules Verne"]'::jsonb),
  ('Tom Sawyer''ın üvey kardeşinin adı nedir?', 'What is the name of Tom Sawyer''s half-brother?', '["Sid","Ben","Joe","Huck"]'::jsonb),
  ('Küçük Kadınlar''da Jo''nun en büyük ablasının adı nedir?', 'Who is Jo''s eldest sister in Little Women?', '["Meg","Amy","Beth","Mary"]'::jsonb),
  ('The Fountainhead''deki Howard Roark karakterinin mesleği nedir?', 'What is Howard Roark''s profession in The Fountainhead?', '["Architect","Lawyer","Doctor","Journalist"]'::jsonb),
  ('Ron Weasley''nin baykuşunun adı nedir?', 'What is the name of Ron Weasley''s owl?', '["Pigwidgeon","Crookshanks","Buckbeak","Fang"]'::jsonb),
  ('Saki hangi yazarın takma adıdır?', 'Which writer used the pen name Saki?', '["Hector Hugh Munro","Eric Arthur Blair","Charlotte Brontë","Charles Dodgson"]'::jsonb),
  ('Ellis Bell hangi yazarın takma adıdır?', 'Which writer used the pen name Ellis Bell?', '["Emily Brontë","Karen Blixen","Samuel Clemens","Mary Ann Evans"]'::jsonb),
  ('''Tom''un Gece Yarısı Bahçesi'' kitabının yazarı kimdir?', 'Who wrote ''Tom''s Midnight Garden''?', '["Philippa Pearce","Charles Dickens","Agatha Christie","John Steinbeck"]'::jsonb),
  ('Jane Eyre''in çocukken gönderildiği okulun adı nedir?', 'What is the name of the school Jane Eyre attends as a child?', '["Lowood","Hogwarts","Smeltings","Nevermore"]'::jsonb)
  ) v(soru, en_soru, en_secenekler)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Karıştırma (TR + EN aynı permütasyon)
drop table if exists pg_temp._parti_karistir;
create temp table _parti_karistir as
select q.id, array_agg(s.idx order by s.rnd) as perm
  from public.questions q
  cross join lateral (
    select (ordinality - 1)::int as idx, random() as rnd
      from jsonb_array_elements(q.secenekler) with ordinality
  ) s
 where q.created_at >= transaction_timestamp()
 group by q.id;

update public.questions q
   set secenekler = (select jsonb_agg(q.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o)),
       dogru_cevap = (array_position(k.perm, q.dogru_cevap::int) - 1)::smallint
  from _parti_karistir k
 where q.id = k.id;

update public.question_translations t
   set secenekler = (select jsonb_agg(t.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o))
  from _parti_karistir k
 where t.question_id = k.id;

drop table if exists pg_temp._parti_karistir;
