-- ============================================================
-- 421 — Şık ipucu düzeltmesi, parti 2/3 (23 Eyl 2026, Ajan J)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide 100 işaretli
-- kolay/orta (zorluk 1–3) sorunun YANLIŞ şıkları yeniden yazıldı; soru metni, doğru cevap ve
-- doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar üç kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0,8) ve tek doğru cevap kontrolü.
-- Geçen 78 soru yazılır ve işareti kaldırılır → rekabetçi havuza döner; 22 soru üç denemede
-- geçemedi ya da (cevabı ünlü ad/sayı olduğu için) yazılmadı; dokunulmadı, işaretli kalır. EN çeviri: 77 satır aynı indekslerle güncellenir.
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 2   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('2201afce-43ce-46ef-8202-01f0db44ee54'::uuid, 0, '["Çekirdek","Sitoplazma","Zar","Koful"]'::jsonb, '["Çekirdek","Ribozom","Golgi cisimciği","Lizozom"]'::jsonb, '["Nucleus","Cytoplasm","Membrane","Vacuole"]'::jsonb, '["Nucleus","Ribosome","Golgi apparatus","Lysosome"]'::jsonb),
    ('9f95b8fb-c9e2-47d0-a26a-772031bb3b31'::uuid, 3, '["Günlük hareket","Rüzgârlar","Ay''ın hareketi","Eksen eğikliği ve yıllık hareket"]'::jsonb, '["Günlük dönüş ve yerel saat farkı","Ay''ın çekimi ve gelgit etkisi","Güneş lekeleri ve güneş rüzgârı","Eksen eğikliği ve yıllık hareket"]'::jsonb, '["The daily rotation","The winds","The Moon''s motion","The tilt of the axis and the yearly orbit"]'::jsonb, '["Daily rotation and local time differences","The Moon''s pull and the tides","Sunspots and the solar wind","The tilt of the axis and the yearly orbit"]'::jsonb),
    ('652f67b6-287e-441c-9816-bca4e9c67850'::uuid, 3, '["Belgeler","Ciddileştirir","Kısaltır","Bir yapıtı güldürüyle taklit eder"]'::jsonb, '["Bir yapıtı başka dile aktarır","Bir yapıtı kısaltarak özetler","Bir yapıtı eleştirel olarak inceler","Bir yapıtı güldürüyle taklit eder"]'::jsonb, '["Documents","Makes serious","Shortens","Imitates a work comically"]'::jsonb, '["Carries a work into another language","Summarises a work by shortening it","Examines a work critically","Imitates a work comically"]'::jsonb),
    ('1516c00b-b3d7-45d8-afb2-528dd17ec412'::uuid, 1, '["Saat farklarını kaldırmak","Gün ışığından çok yararlanmak","Ek elektrik enerjisi üretmek","Takvim düzenini değiştirmek"]'::jsonb, '["Uluslararası saat dilimlerini eşitlemek","Gün ışığından çok yararlanmak","Güneş panellerinden daha çok enerji almak","Artık yıl kaymasını telafi etmek"]'::jsonb, '["To abolish time differences","To make more use of daylight","To generate energy","To change the calendar"]'::jsonb, '["To align international time zones","To make more use of daylight","To get more energy from solar panels","To compensate for leap-year drift"]'::jsonb),
    ('acc2a772-d754-43b2-9bcd-d902a7ea0b98'::uuid, 0, '["Diyez ve bemolleri","Es işaretlerini","Sadece re''yi","Sadece doları"]'::jsonb, '["Diyez ve bemolleri","Oktavların başlangıç notalarını","Değiştirici işareti olmayan notaları","Pedalla uzatılan notaları"]'::jsonb, '["Sharps and flats","Rest signs","Only D","Only C"]'::jsonb, '["Sharps and flats","The first note of each octave","Notes without accidentals","Notes sustained with the pedal"]'::jsonb),
    ('44517e8f-a3b8-4de6-befe-d583147a7ec0'::uuid, 0, '["Abartılı çizgi ve eleştiriyi","Gerçekçiliği","Belgeselliği","Perspektifi"]'::jsonb, '["Abartılı çizgi ve eleştiriyi","Ayrıntılı gölge ve derinliği","Işık ve renk izlenimini","Geometrik biçim ve düzeni"]'::jsonb, '["Exaggerated line and criticism","Realism","Documentation","Perspective"]'::jsonb, '["Exaggerated line and criticism","Detailed shading and depth","Impressions of light and colour","Geometric form and order"]'::jsonb),
    ('2bd5fe33-d68f-4830-b28a-e1f32c639e2d'::uuid, 3, '["Kurgu hızını","Renk dengesini","Ses efektini","Geçmişe dair kanıt ve bağlam"]'::jsonb, '["Sahnenin oyuncularla gerçek zamanlı canlandırmasını","Olayların uzmanlarca yorumlanmasını","Konunun anlatıcı sesle özetlenmesini","Geçmişe dair kanıt ve bağlam"]'::jsonb, '["The pace of the edit","Colour balance","A sound effect","Evidence and context about the past"]'::jsonb, '["A real-time dramatisation of the scene by actors","Interpretation of the events by experts","A narrator summarising the subject","Evidence and context about the past"]'::jsonb),
    ('29bdde39-8e29-4132-8ac0-178ba239e9ea'::uuid, 3, '["Bireysel skoru","Fiziksel gücü","Hızı","Ortak hedefe bağlılığı"]'::jsonb, '["Teknik beceri ve ustalığı","Dayanıklılık ve kondisyonu","Taktik bilgi ve analizi","Ortak hedefe bağlılığı"]'::jsonb, '["Individual scoring","Physical strength","Speed","Commitment to a shared goal"]'::jsonb, '["Technical skill and mastery","Stamina and fitness","Tactical knowledge and analysis","Commitment to a shared goal"]'::jsonb),
    ('e6e372b0-e1d1-4d7d-bb45-2234c92bc80d'::uuid, 3, '["Ağ kurmak","Virüs yaymak","Dosya silmek","Tarayıcıda küçük veri saklamak"]'::jsonb, '["Ağ trafiğini şifrelemek","Alan adını IP adresine çevirmek","Açılır pencereleri engellemek","Tarayıcıda küçük veri saklamak"]'::jsonb, '["Setting up a network","Spreading viruses","Deleting files","Storing small data in the browser"]'::jsonb, '["Encrypting network traffic","Translating domain names into IP addresses","Blocking pop-up windows","Storing small data in the browser"]'::jsonb),
    ('8b019f2a-afc1-44cb-b1ac-686ab71d3b64'::uuid, 3, '["90","120","80","100"]'::jsonb, '["37","0","4","100"]'::jsonb, '["90","120","80","100"]'::jsonb, '["37","0","4","100"]'::jsonb),
    ('93d49d75-2935-4739-a18c-ca1c12bf631c'::uuid, 0, '["Berlin","Münih","Frankfurt","Hamburg"]'::jsonb, '["Berlin","Viyana","Bern","Varşova"]'::jsonb, '["Berlin","Munich","Frankfurt","Hamburg"]'::jsonb, '["Berlin","Vienna","Bern","Warsaw"]'::jsonb),
    ('84e35851-58bd-45a1-b47b-53d863232edf'::uuid, 0, '["Ölçü, kafiye ve ses yinelemeleriyle","Sayfa sayısıyla","Başlıkla","Yazı tipiyle"]'::jsonb, '["Ölçü, kafiye ve ses yinelemeleriyle","İmge, mecaz ve benzetmelerle","Tema, konu ve ana duyguyla","Kıta düzeni ve dize sayısıyla"]'::jsonb, '["Metre, rhyme and repeated sounds","The page count","The title","The typeface"]'::jsonb, '["Metre, rhyme and repeated sounds","Imagery, metaphor and simile","Theme, subject and main feeling","Stanza layout and line count"]'::jsonb),
    ('8fac266e-43db-4726-a6d4-1c2bca36c25a'::uuid, 0, '["Kavram ve adların yerini bulmaya","Kapak tasarımına","Baskıya","Fiyata"]'::jsonb, '["Kavram ve adların yerini bulmaya","Bölümlerin sırasını ve sayfalarını göstermeye","Kullanılan kaynakları alfabetik listelemeye","Terimlerin anlamını kısaca açıklamaya"]'::jsonb, '["Finding where terms and names appear","The cover design","Printing","The price"]'::jsonb, '["Finding where terms and names appear","Showing the order and pages of chapters","Listing the sources used alphabetically","Briefly explaining the meaning of terms"]'::jsonb),
    ('783c60e8-6355-4a66-affd-0d20f7b81838'::uuid, 1, '["Ritimle","Seslerin birlikte kullanımıyla","Tempoyla","Şiddetle"]'::jsonb, '["Seslerin süre ilişkisiyle","Seslerin birlikte kullanımıyla","Seslerin art arda dizilişiyle","Seslerin şiddet değişimiyle"]'::jsonb, '["Rhythm","How notes are used together","Tempo","Loudness"]'::jsonb, '["How long notes last relative to each other","How notes are used together","How notes follow one another","How loudness changes"]'::jsonb),
    ('03c5f568-128a-4d9e-8623-22f3f42a4de6'::uuid, 1, '["Yalnızca ses efektini","Canlandırılan nesneleri","Yalnızca sahne ışığını","Yalnızca yazılı metni"]'::jsonb, '["Maskeli oyuncuları","Canlandırılan nesneleri","Sessiz jestleri","Doğaçlama diyalogları"]'::jsonb, '["Only sound","Objects brought to life","Only light","Only the text"]'::jsonb, '["Masked actors","Objects brought to life","Silent gestures","Improvised dialogue"]'::jsonb),
    ('714e8bd1-7bc8-44bb-828f-46caaf9ef68b'::uuid, 1, '["Şarkı","Görüntü dışından duyulan anlatım","Efekt","Diyalog"]'::jsonb, '["Oyuncuların sahnedeki konuşması","Görüntü dışından duyulan anlatım","Sahneye sonradan eklenen efekt","Filme eşlik eden özgün müzik"]'::jsonb, '["A song","Narration heard from outside the image","An effect","Dialogue"]'::jsonb, '["The actors'' on-screen speech","Narration heard from outside the image","An effect added to the scene later","The original score accompanying the film"]'::jsonb),
    ('1b234866-578e-4ae6-b154-7e20613b9110'::uuid, 1, '["Forma satmak","Branşı düzenlemek ve yönetmek","Bilet basmak","Stadyum işletmek"]'::jsonb, '["Stadyumu işletmek ve kiralamak","Branşı düzenlemek ve yönetmek","Takım formasını üretmek ve satmak","Kulüp kadrosunu kurmak ve yönetmek"]'::jsonb, '["Selling shirts","Regulating and governing the sport","Printing tickets","Running the stadium"]'::jsonb, '["Running and renting out stadiums","Regulating and governing the sport","Making and selling team kits","Building and managing a club squad"]'::jsonb),
    ('bf8e420d-d4b9-4695-85d6-2a5b33814875'::uuid, 3, '["Yalnız yükü","Yalnız rotayı","Yalnız mürettebatı","Rüzgara bağımlılığı"]'::jsonb, '["Pusula kullanımını","Harita kullanımını","Bayrak kullanımını","Rüzgara bağımlılığı"]'::jsonb, '["Only the cargo","Only the route","Only the crew","Dependence on the wind"]'::jsonb, '["Use of the compass","Use of charts","Use of flags","Dependence on the wind"]'::jsonb),
    ('00dea4dc-9d81-42ff-bd83-7f82364c1362'::uuid, 2, '["Yalnız yerel diskte","Yalnız telefonda","Uzak sunucularda","Yalnız USB''de"]'::jsonb, '["Yerel sabit diskte","Taşınabilir bellekte","Uzak sunucularda","Cihazın RAM''inde"]'::jsonb, '["Only on the local disk","Only on the phone","On remote servers","Only on a USB stick"]'::jsonb, '["On the local hard disk","On a portable memory stick","On remote servers","In the device''s RAM"]'::jsonb),
    ('12871e4e-22cb-4bb9-9764-e564e32cd9a9'::uuid, 3, '["50","80","120","100"]'::jsonb, '["0","37","4","100"]'::jsonb, '["50","80","120","100"]'::jsonb, '["0","37","4","100"]'::jsonb),
    ('7927b9a5-08e7-4838-9185-56322788840b'::uuid, 0, '["Açıklama ve kaynak vermek","Başlık atmak","Fiyat yazmak","Kapak yapmak"]'::jsonb, '["Açıklama ve kaynak vermek","Konuyu ve amacı tanıtmak","Bölümleri ve sayfaları listelemek","Terimleri ve anlamları sıralamak"]'::jsonb, '["Giving an explanation and a source","Setting a heading","Writing the price","Making the cover"]'::jsonb, '["Giving an explanation and a source","Introducing the subject and aim","Listing chapters and pages","Listing terms and meanings"]'::jsonb),
    ('a10f7bbe-7584-4dcb-b33d-486198851f2b'::uuid, 0, '["Anayasa","Tüzük","Genelge","Bildiri"]'::jsonb, '["Anayasa","Kanun","Yönetmelik","Tüzük"]'::jsonb, '["Constitution","Regulation","Circular","Declaration"]'::jsonb, '["Constitution","Statute","Regulation","Bylaw"]'::jsonb),
    ('ec5593a9-b4bb-49b8-93a4-e7f5c9e6d99b'::uuid, 0, '["Sesi gecikmeli yineler","Sesi kısar","Perdeyi değiştirir","Tempoyu artırır"]'::jsonb, '["Sesi gecikmeli yineler","Sesi mekânda yansıtır","Sesi dalgalandırır","Sesi bozarak sertleştirir"]'::jsonb, '["Repeats the sound after a lag","Turns the sound down","Changes the pitch","Increases the tempo"]'::jsonb, '["Repeats the sound after a lag","Makes the sound reverberate in a space","Makes the sound waver","Roughens the sound by distorting it"]'::jsonb),
    ('7dc17d36-94da-44d8-9742-7924dbf74490'::uuid, 0, '["Yaratıcı ve eleştirel gelişimi","Yalnız tekniği","Yalnız tarihi","Yalnız satışı"]'::jsonb, '["Yaratıcı ve eleştirel gelişimi","Müze ve galeri yönetimini","Eser koruma ve onarımını","Sanat piyasası ve satışını"]'::jsonb, '["Creative and critical development","Technique alone","History alone","Sales alone"]'::jsonb, '["Creative and critical development","Museum and gallery management","Conservation and repair of works","The art market and sales"]'::jsonb),
    ('6818bc4e-f79d-4776-91ef-eabe4299f54e'::uuid, 2, '["Bilet satmak","Ödül vermek","Filmleri koruyup geleceğe aktarmak","Fragman çekmek"]'::jsonb, '["Filmleri sınıflandırıp yaş sınırı koymak","Filmleri dağıtıp salonlara ulaştırmak","Filmleri koruyup geleceğe aktarmak","Filmleri tanıtıp izleyici çekmek"]'::jsonb, '["Selling tickets","Giving awards","Preserving films for the future","Shooting trailers"]'::jsonb, '["Classifying films and setting age ratings","Distributing films to cinemas","Preserving films for the future","Promoting films and drawing audiences"]'::jsonb),
    ('6c8cabde-7c4a-4f98-9526-e1fb25abdbdd'::uuid, 3, '["Ortalama derece","Antrenman süresi","Katılım sayısı","Resmî olarak ölçülmüş en iyi derece"]'::jsonb, '["Resmî olarak ölçülmüş en düşük baraj derecesi","Resmî olarak ölçülmüş ortalama derece","Resmî olarak ölçülmüş ilk derece","Resmî olarak ölçülmüş en iyi derece"]'::jsonb, '["An average mark","Training time","The number of entrants","The best mark officially measured"]'::jsonb, '["The lowest qualifying mark officially measured","The average mark officially measured","The first mark officially measured","The best mark officially measured"]'::jsonb),
    ('0c26afe8-71a2-46e0-b805-e235c85d442e'::uuid, 3, '["Tarımsal üretimi azaltmak","Kırsaldan göçü artırmak","Daha çok vergi toplamak","Planlı üretim ve istihdam"]'::jsonb, '["Kırsal kalkınma ve tarım","Turizm ve kültür tanıtımı","Konut ve kentsel dönüşüm","Planlı üretim ve istihdam"]'::jsonb, '["Reducing agriculture","Increasing migration","Collecting taxes","Planned production and employment"]'::jsonb, '["Rural development and farming","Tourism and cultural promotion","Housing and urban renewal","Planned production and employment"]'::jsonb),
    ('4cfd8db0-e086-44ff-a6b0-d97c015643be'::uuid, 2, '["Tek boyutlu olması","Renkli olması zorunluluğu","İki boyutlu olup daha çok veri taşıması","Okunamaması"]'::jsonb, '["Tek boyutlu olup daha az yer kaplaması","Manyetik olup kart okuyucuyla okunması","İki boyutlu olup daha çok veri taşıması","Radyo dalgasıyla temassız okunabilmesi"]'::jsonb, '["It is one-dimensional","It must be in colour","It is two-dimensional and carries more data","It cannot be read"]'::jsonb, '["It is one-dimensional and takes less space","It is magnetic and read by a card reader","It is two-dimensional and carries more data","It can be read contactlessly by radio"]'::jsonb),
    ('2f26059b-c2dd-464d-97bc-1bf53ce02c2c'::uuid, 1, '["Koklayarak","Ses dalgalarıyla (ekolokasyon)","Görerek","Isıyla"]'::jsonb, '["Isı algısıyla (termoresepsiyon)","Ses dalgalarıyla (ekolokasyon)","Koku izleriyle (kemoresepsiyon)","Elektrik alanıyla (elektroresepsiyon)"]'::jsonb, '["By smell","By sound waves (echolocation)","By sight","By heat"]'::jsonb, '["By heat sensing (thermoreception)","By sound waves (echolocation)","By scent trails (chemoreception)","By electric fields (electroreception)"]'::jsonb),
    ('20efc089-c01d-475b-b4a3-6c0333432e6b'::uuid, 1, '["Açılışı","Çatışmanın en yoğun anını","Ara sahneyi","Kapanış yazısını"]'::jsonb, '["Çatışmanın ilk ortaya çıkışını","Çatışmanın en yoğun anını","Çatışmanın çözüme kavuşmasını","Olayların geçtiği ortamın tanıtımını"]'::jsonb, '["The opening","The most intense moment of the conflict","An interlude","The closing title"]'::jsonb, '["The first appearance of the conflict","The most intense moment of the conflict","The resolution of the conflict","The introduction of the setting"]'::jsonb),
    ('fdf10b30-5514-4831-aa3c-dd0532fa1c04'::uuid, 0, '["Küllerinden yeniden doğması","Konuşması","Su altında yaşaması","Uçamaması"]'::jsonb, '["Küllerinden yeniden doğması","Bakışıyla insanları taşa çevirmesi","Yedi başlı bir ejderha olması","Kanatlı bir at olarak uçması"]'::jsonb, '["Being reborn from its ashes","Speaking","Living underwater","Being unable to fly"]'::jsonb, '["Being reborn from its ashes","A gaze that turns people to stone","Being a seven-headed dragon","Flying as a winged horse"]'::jsonb),
    ('f6bc5719-ed27-468e-928c-08e8a4e66ae3'::uuid, 2, '["Aynayla","Boyayla","Perde arkası ışık ve figürlerle","Kameraya"]'::jsonb, '["Sahnede ip ile oynatılan bebeklerle","Yüze takılan maske ve kostümle","Perde arkası ışık ve figürlerle","Karanlık odada iğne deliğiyle"]'::jsonb, '["With a mirror","With paint","With a light and figures behind a screen","With a camera"]'::jsonb, '["With puppets worked on strings on stage","With masks and costumes worn by actors","With a light and figures behind a screen","With a pinhole in a dark room"]'::jsonb),
    ('0a714bd0-3b18-437a-9182-8cdeee15c820'::uuid, 1, '["Cannes Festival Kurulu","Sinema Sanatları Akademisi","BAFTA İngiliz Akademisi","Altın Küre Basın Derneği"]'::jsonb, '["Avrupa Film Akademisi","Sinema Sanatları Akademisi","İngiliz Film Akademisi","Hollywood Yabancı Basın Derneği"]'::jsonb, '["The Cannes board","The Academy of Motion Picture Arts and Sciences","BAFTA","The Golden Globe association"]'::jsonb, '["The European Film Academy","The Academy of Motion Picture Arts and Sciences","The British Film Academy","The Hollywood Foreign Press Association"]'::jsonb),
    ('7e973915-623d-4800-9004-eccf773e8e7c'::uuid, 2, '["Ticaret tercihini","İklim tercihini","Güvenlik ve merkezîlik tercihini","Nüfus tercihini"]'::jsonb, '["Liman ve ticaret tercihini","Tarih ve miras tercihini","Güvenlik ve merkezîlik tercihini","Sanayi ve nüfus tercihini"]'::jsonb, '["A preference for trade","A preference for climate","A preference for security and centrality","A preference for population"]'::jsonb, '["A preference for ports and trade","A preference for history and heritage","A preference for security and centrality","A preference for industry and population"]'::jsonb),
    ('6a17a980-e413-4ee2-895f-4438f0ce610f'::uuid, 0, '["Sinyalleri dönüştürerek internet bağlantısı sağlar","Ses üretir","Görüntü işler","Yazı yazar"]'::jsonb, '["Sinyalleri dönüştürerek internet bağlantısı sağlar","Paketleri yönlendirerek yerel ağ trafiğini düzenler","Verileri sıkıştırarak diskte daha az yer kaplatır","Görüntüleri işleyerek ekranda grafik oluşturur"]'::jsonb, '["Converts signals to provide an internet connection","Produces sound","Processes images","Writes text"]'::jsonb, '["Converts signals to provide an internet connection","Routes packets to manage local network traffic","Compresses data so it takes less disk space","Processes images to produce graphics on screen"]'::jsonb),
    ('2f28a0a9-6742-4674-b2d6-4458be5adaa5'::uuid, 2, '["Bulutlar sesi tutar","Işık sesten yavaştır","Ses ışıktan yavaştır","Kulağımız geç algılar"]'::jsonb, '["Işık sesten yavaştır","Ses suda daha hızlıdır","Ses ışıktan yavaştır","Ses boşlukta yayılmaz"]'::jsonb, '["The clouds hold the sound","Light is slower than sound","Sound is slower than light","Our ears perceive it late"]'::jsonb, '["Light is slower than sound","Sound travels faster in water","Sound is slower than light","Sound cannot travel in a vacuum"]'::jsonb),
    ('dd9c4170-d341-4def-b8c9-6e7c25d22c84'::uuid, 2, '["Tadını değiştirmek","Sertliği artırmak","Mikroorganizmaları etkisizleştirmek","Renk vermek"]'::jsonb, '["Kireç ve sertlik oranını düşürmek","Askıdaki tortuları dibe çöktürmek","Mikroorganizmaları etkisizleştirmek","Florür ekleyerek diş sağlığını korumak"]'::jsonb, '["Changing its taste","Increasing its hardness","Killing micro-organisms","Adding colour"]'::jsonb, '["Lowering the lime and hardness","Settling suspended sediment","Killing micro-organisms","Adding fluoride to protect teeth"]'::jsonb),
    ('57a31a7b-0b08-4037-b83b-2c3978129d16'::uuid, 2, '["Dış engellere","Doğaya","Kendi içindeki çelişkiye","Topluma"]'::jsonb, '["Başka bir karakterle çekişmeye","Toplumun kurallarıyla çatışmaya","Kendi içindeki çelişkiye","Doğanın zorluklarıyla mücadeleye"]'::jsonb, '["External obstacles","Nature","A contradiction within themselves","Society"]'::jsonb, '["A clash with another character","A conflict with society''s rules","A contradiction within themselves","A struggle against nature''s hardships"]'::jsonb),
    ('5fd472dd-5985-49a1-a97e-f82f612161e3'::uuid, 0, '["Yinelenen kısa ezgi kalıbı","Şarkı sözü","Davul solosu","Konser adı"]'::jsonb, '["Yinelenen kısa ezgi kalıbı","Tek notanın uzun titreşimi","Doğaçlama uzun gitar solosu","Şarkıyı açan davul girişi"]'::jsonb, '["A short repeated melodic figure","The lyrics","A drum solo","A concert name"]'::jsonb, '["A short repeated melodic figure","A long vibrato on one note","A long improvised guitar solo","A drum intro opening the song"]'::jsonb),
    ('0bcc81ec-69db-4537-b61e-e8a40f3236e2'::uuid, 1, '["Ses kalitesinin tümden kaybı","Film şeridi yerine dosya kullanımı","Film sürelerinin uzaması","Renk doygunluğunun kaybı"]'::jsonb, '["Ses yerine altyazı kullanımı","Film şeridi yerine dosya kullanımı","Renkli yerine siyah-beyaz kullanımı","Stüdyo yerine doğal mekân kullanımı"]'::jsonb, '["Loss of sound","Files replacing the film strip","Longer running times","Loss of colour"]'::jsonb, '["Subtitles replacing sound","Files replacing the film strip","Black-and-white replacing colour","Natural locations replacing studios"]'::jsonb),
    ('2b35aeea-745f-456d-8468-11d8921f0999'::uuid, 3, '["Isınma","Süslenme","Ağırlık","Koruma ve destek"]'::jsonb, '["Isınma ve esneme","Hız ve çeviklik","Denge ve ağırlık","Koruma ve destek"]'::jsonb, '["Warming up","Decoration","Weight","Protection and support"]'::jsonb, '["Warming up and stretching","Speed and agility","Balance and weight","Protection and support"]'::jsonb),
    ('02d9938f-a89c-4385-a424-f5c1e6c68628'::uuid, 0, '["Sahte iletiyle bilgi çalarak","Sunucuyu zorla kırarak","Ağ kablosunu keserek","Diski uzaktan silerek"]'::jsonb, '["Sahte iletiyle bilgi çalarak","Sunucuyu sahte istekle boğarak","Dosyaları şifreleyip fidye isteyerek","Klavye vuruşlarını gizlice kaydederek"]'::jsonb, '["By stealing information with a fake message","By hacking a server","By cutting cables","By wiping disks"]'::jsonb, '["By stealing information with a fake message","By flooding a server with fake requests","By encrypting files and demanding a ransom","By secretly logging keystrokes"]'::jsonb),
    ('7e3cf80a-db51-40e2-af3e-8743daad321d'::uuid, 0, '["İklimi ve uzun dönem değişimini","Günlük havayı","Kayaçları","Nüfusu"]'::jsonb, '["İklimi ve uzun dönem değişimini","Havayı ve günlük kısa dönem değişimini","Kayaçları ve oluşum süreçlerini","Nüfusu ve dağılış özelliklerini"]'::jsonb, '["Climate and its long-term change","The daily weather","Rocks","Population"]'::jsonb, '["Climate and its long-term change","The weather and its short-term daily changes","Rocks and how they form","Population and its distribution"]'::jsonb),
    ('346764e0-1d36-4374-8bff-e7af9165c206'::uuid, 0, '["Başkasının eserini sahiplenme","Alıntı yapma","Özet","Çeviri"]'::jsonb, '["Başkasının eserini sahiplenme","Başkasının eserinden kaynak göstererek alıntı","Bir eseri başka dile aktarma","Bir eseri kısaltarak özetleme"]'::jsonb, '["Passing off someone else''s work as one''s own","Quoting","Summarising","Translating"]'::jsonb, '["Passing off someone else''s work as one''s own","Quoting someone else''s work with a citation","Rendering a work in another language","Summarising a work by shortening it"]'::jsonb),
    ('821894ad-be86-4382-9fe8-f51bb4af0bf3'::uuid, 3, '["Şarkı bestelenir","Nota yazılır","Konser verilir","Kanallar dengelenip birleştirilir"]'::jsonb, '["Enstrümanlar tek tek kaydedilir","Şarkının sözleri yazılır","Kayıt plağa ya da dosyaya basılır","Kanallar dengelenip birleştirilir"]'::jsonb, '["The song is composed","The score is written","A concert is given","The channels are balanced and combined"]'::jsonb, '["The instruments are recorded one by one","The lyrics are written","The recording is pressed to vinyl or file","The channels are balanced and combined"]'::jsonb),
    ('f8a33cf2-3ac0-478b-918f-d91912a5c3e5'::uuid, 1, '["Yalnız estetiği","Koruma ve iletişimi","Yalnız maliyeti","Yalnız rengi"]'::jsonb, '["Tat ve kokuyu","Koruma ve iletişimi","Hız ve performansı","Ses ve ritmi"]'::jsonb, '["Aesthetics only","Protection and communication","Cost only","Colour only"]'::jsonb, '["Taste and smell","Protection and communication","Speed and performance","Sound and rhythm"]'::jsonb),
    ('39b4e276-65c1-432d-aa57-b6341f94af3a'::uuid, 3, '["Tek kanal","Sessizlik","Mono ses","Çevresel ses alanı"]'::jsonb, '["Tek kanallı ses alanı","Keskin görüntü alanı","Derin renk alanı","Çevresel ses alanı"]'::jsonb, '["A single channel","Silence","Mono sound","An enveloping sound field"]'::jsonb, '["A single-channel sound field","A sharp image field","A deep colour field","An enveloping sound field"]'::jsonb),
    ('4ba03a48-a553-4d0f-8d17-e15293b53ffd'::uuid, 3, '["Kürek kemiği","Pazu kemiği","Kaval kemiği","Uyluk kemiği (femur)"]'::jsonb, '["Kaval kemiği (tibia)","Pazu kemiği (humerus)","Köprücük kemiği (klavikula)","Uyluk kemiği (femur)"]'::jsonb, '["The shoulder blade","The humerus","The tibia","The thigh bone (femur)"]'::jsonb, '["The shin bone (tibia)","The upper arm bone (humerus)","The collarbone (clavicle)","The thigh bone (femur)"]'::jsonb),
    ('02a58ee6-b919-4d9e-aa8c-4e4dbfa725c7'::uuid, 3, '["Miami","Chicago","Los Angeles","New York"]'::jsonb, '["Los Angeles","Hong Kong","San Francisco","New York"]'::jsonb, '["Miami","Chicago","Los Angeles","New York"]'::jsonb, '["Los Angeles","Hong Kong","San Francisco","New York"]'::jsonb),
    ('7926c5c9-3253-4cf9-bd0e-a6e4a85f867d'::uuid, 3, '["Ağdalı olması","Uzun cümleli olması","İmgeli olması","Süssüz ve açık olması"]'::jsonb, '["İmgeli ve çok anlamlı olması","Ahenkli ve ölçülü olması","Ayrıntılı ve betimleyici olması","Süssüz ve açık olması"]'::jsonb, '["Being ornate","Having long sentences","Being full of imagery","Being unadorned and clear"]'::jsonb, '["Being full of images and meanings","Being rhythmic and metrical","Being detailed and descriptive","Being unadorned and clear"]'::jsonb),
    ('e5205974-591f-4bdb-9d71-96d8a9b60429'::uuid, 1, '["Sözlüğün resimli olması","Ansiklopedinin konuyu açıklaması","Ansiklopedinin küçük olması","Sözlüğün yıllık çıkması"]'::jsonb, '["Sözlüğün konuyu açıklaması","Ansiklopedinin konuyu açıklaması","Ansiklopedinin kök bilgisi vermesi","Sözlüğün çok ciltli olması"]'::jsonb, '["The dictionary has pictures","The encyclopaedia explains the subject","The encyclopaedia is smaller","The dictionary comes out yearly"]'::jsonb, '["The dictionary explains the subject","The encyclopaedia explains the subject","The encyclopaedia gives word origins","The dictionary runs to many volumes"]'::jsonb),
    ('ea7d9bbc-0c4b-47db-b87e-dac26d66f349'::uuid, 0, '["Belirli sırayla sunulan eserler bütünü","Tek şarkı","Doğaçlama","Enstrüman"]'::jsonb, '["Belirli sırayla sunulan eserler bütünü","Tek çalgıyla yapılan doğaçlama","Bir makamın dizisini gösteren nota","Şarkı içinde çalınan ara nağme"]'::jsonb, '["A set of pieces presented in a set order","A single song","Improvisation","An instrument"]'::jsonb, '["A set of pieces presented in a set order","An improvisation on a single instrument","The written scale of a makam","An instrumental interlude within a song"]'::jsonb),
    ('4cef6c10-83ca-43e3-8201-474025b63f93'::uuid, 2, '["Giriş kapısını","Minare yerini","Kıble yönünü","Avlu sınırını"]'::jsonb, '["Vaaz verilen yeri","Müezzinin okuduğu yeri","Kıble yönünü","Abdest alınan yeri"]'::jsonb, '["The entrance","The place of the minaret","The direction of Mecca","The edge of the courtyard"]'::jsonb, '["Where sermons are preached","Where the muezzin recites","The direction of Mecca","Where ablutions are made"]'::jsonb),
    ('691c85b9-f955-44cd-8990-1f6725d7c96a'::uuid, 2, '["Sesin hızlanmasını","Renklerin doygunlaşmasını","Uzun sürecin kısa gösterilmesini","Görüntünün donmasını"]'::jsonb, '["Kısa anın uzun gösterilmesini","Anın tek karede dondurulmasını","Uzun sürecin kısa gösterilmesini","Sahnenin tersten oynatılmasını"]'::jsonb, '["Speeding up the sound","Saturating the colours","Showing a long process briefly","Freezing the image"]'::jsonb, '["Showing a brief moment at length","Freezing a moment in a single frame","Showing a long process briefly","Playing the scene backwards"]'::jsonb),
    ('8dd96c61-edd1-4aa5-b810-21daa3d6c60a'::uuid, 0, '["Apartheid","Segregasyon yalnızca","Kolonyalizm","Feodalite"]'::jsonb, '["Apartheid","Jim Crow","Kast sistemi","Getto politikası"]'::jsonb, '["Apartheid","Segregation only","Colonialism","Feudalism"]'::jsonb, '["Apartheid","Jim Crow","The caste system","Ghettoisation"]'::jsonb),
    ('bd76ab59-7606-406b-b3f6-b5d6a7d73b85'::uuid, 1, '["Veri yedekleme","Sahte mesajla bilgi çalma girişimi","Ağ hızlandırma","Yazılım güncelleme"]'::jsonb, '["Sunucuyu sahte istekle çökertme girişimi","Sahte mesajla bilgi çalma girişimi","Dosyaları şifreleyip fidye isteme girişimi","Ağ trafiğini gizlice dinleme girişimi"]'::jsonb, '["Backing up data","An attempt to steal information with a fake message","Speeding up the network","Updating software"]'::jsonb, '["An attempt to crash a server with fake requests","An attempt to steal information with a fake message","An attempt to encrypt files for ransom","An attempt to secretly eavesdrop on network traffic"]'::jsonb),
    ('c10c98ea-9555-469a-921c-22c2943c97d3'::uuid, 2, '["400 gün","350 gün","365 gün","360 gün"]'::jsonb, '["687 gün","225 gün","365 gün","88 gün"]'::jsonb, '["400 days","350 days","365 days","360 days"]'::jsonb, '["687 days","225 days","365 days","88 days"]'::jsonb),
    ('30a95561-1573-4aee-99fb-e148e7cfd460'::uuid, 3, '["Rüzgârlar","Deprem","Volkanizma","Ay ve Güneş''in çekim etkisi"]'::jsonb, '["Yer kabuğundaki levhaların yavaş hareketi","Okyanus suyundaki tuzluluk ve sıcaklık farkı","Atmosferdeki hava basıncı farkları","Ay ve Güneş''in çekim etkisi"]'::jsonb, '["Winds","Earthquakes","Volcanism","The gravitational pull of the Moon and the Sun"]'::jsonb, '["Slow movement of the crust''s plates","Salinity and temperature differences in ocean water","Pressure differences in the atmosphere","The gravitational pull of the Moon and the Sun"]'::jsonb),
    ('849ee9c3-9f5d-4a78-877c-d33c6ff89aa4'::uuid, 1, '["Akor dizisini","Kendine özgü ritmik salınımı","Solistin adını","Enstrüman sayısını"]'::jsonb, '["Kendine özgü akor dizisini","Kendine özgü ritmik salınımı","Solistin doğaçlama bölümünü","Kontrbasın yürüyen hattını"]'::jsonb, '["The chord sequence","Its distinctive rhythmic lilt","The soloist''s name","The number of instruments"]'::jsonb, '["Its distinctive chord progression","Its distinctive rhythmic lilt","The soloist''s improvised section","The double bass''s walking line"]'::jsonb),
    ('65e973ca-c89d-4613-9eb1-d19f66ba1e23'::uuid, 2, '["Eser satmayı","Sergi açmayı","İyileşme ve ifadeyi desteklemeyi","Teknik öğretmeyi"]'::jsonb, '["Eserlerin piyasa değerini belirlemeyi","Yıpranmış eserleri onarmayı","İyileşme ve ifadeyi desteklemeyi","Sanat tarihini öğretmeyi"]'::jsonb, '["Selling work","Mounting exhibitions","Supporting healing and expression","Teaching technique"]'::jsonb, '["Appraising the market value of works","Repairing worn artworks","Supporting healing and expression","Teaching art history"]'::jsonb),
    ('dc63a8c9-f9f2-4250-b67f-f2e0f5a330f6'::uuid, 2, '["Süreyi uzatır","Kadrajı büyütür","Gerilim ve vurgu yaratır","Rengi değiştirir"]'::jsonb, '["Tempo ve hareket katar","Derinlik ve perspektif verir","Gerilim ve vurgu yaratır","Renk ve doku katar"]'::jsonb, '["It lengthens the running time","It widens the frame","It creates tension and emphasis","It changes the colour"]'::jsonb, '["It adds pace and movement","It gives depth and perspective","It creates tension and emphasis","It adds colour and texture"]'::jsonb),
    ('1f101dcc-c6a6-44e2-8dff-f96790588f86'::uuid, 1, '["Hiçbir sebeple","Performans ve sakatlık","Sadece hakem isteğiyle","Sadece seyirci isteğiyle"]'::jsonb, '["Seyirci ve medya baskısı","Performans ve sakatlık","Sponsor ve reklam anlaşması","Forma ve ekipman sorunu"]'::jsonb, '["For no reason","Performance and injury","Only at the referee''s request","Only at the crowd''s request"]'::jsonb, '["Crowd and media pressure","Performance and injury","Sponsorship and advertising deals","Kit and equipment problems"]'::jsonb),
    ('64c76727-3866-40ee-8170-33b218f0cae6'::uuid, 0, '["Üretim ve fiyat kayıtlarını","Yalnız savaş raporlarını","Yalnız mimariyi","Yalnız edebiyatı"]'::jsonb, '["Üretim ve fiyat kayıtlarını","Savaş ve antlaşma metinlerini","Sanat ve mimari eserlerini","Dil ve edebiyat metinlerini"]'::jsonb, '["Production and price records","War reports only","Architecture only","Literature only"]'::jsonb, '["Production and price records","Treaties and war records","Works of art and architecture","Literary and linguistic texts"]'::jsonb),
    ('6a1b0fb0-b580-4a60-94ce-a34de81de149'::uuid, 3, '["Diske yazılır","Kalıcı olur","Şifrelenir","Silinir"]'::jsonb, '["Önbelleğe alınır","Buluta yedeklenir","Sıkıştırılır","Silinir"]'::jsonb, '["It is written to disk","It becomes permanent","It is encrypted","It is lost"]'::jsonb, '["It is cached","It is backed up to the cloud","It is compressed","It is lost"]'::jsonb),
    ('0117c539-60e1-4012-8c8f-083ec59b5d00'::uuid, 3, '["90°C","110°C","120°C","100°C"]'::jsonb, '["0°C","4°C","37°C","100°C"]'::jsonb, '["90°C","110°C","120°C","100°C"]'::jsonb, '["0°C","4°C","37°C","100°C"]'::jsonb),
    ('1609a497-0d94-425b-8d6a-4c01bdde486c'::uuid, 1, '["Görünümü","Olayların akışını","Düşünceyi","Duyguyu yalnızca"]'::jsonb, '["Varlıkların görünümünü","Olayların akışını","Görüşlerin tartışmasını","Bilgilerin açıklanmasını"]'::jsonb, '["Appearance","The flow of events","Thought","Only emotion"]'::jsonb, '["What things look like","The flow of events","A debate between views","The explanation of information"]'::jsonb),
    ('2dc86cb7-39d8-4a69-95c4-f3bc66641702'::uuid, 2, '["Sadece konu","Sadece adres","Ad, soyad ve imza","Sadece tarih"]'::jsonb, '["Meslek ve maaş bilgisi","Doğum yeri ve medeni hal","Ad, soyad ve imza","Eğitim ve iş geçmişi"]'::jsonb, '["Only the subject","Only the address","Name, surname and signature","Only the date"]'::jsonb, '["Occupation and salary","Place of birth and marital status","Name, surname and signature","Education and work history"]'::jsonb),
    ('d858e16d-2edf-40ae-836d-effb27e524cd'::uuid, 3, '["Renk için","Ağırlık için","Görünüm için","Tını ve akort kararlılığı için"]'::jsonb, '["Sapın düz kalmasını sağlamak için","Gövdenin ahşabını nemden korumak için","Perdelerin aşınmasını önlemek için","Tını ve akort kararlılığı için"]'::jsonb, '["For the colour","For the weight","For appearance","For tone and stable tuning"]'::jsonb, '["To keep the neck straight","To protect the body''s wood from damp","To prevent fret wear","For tone and stable tuning"]'::jsonb),
    ('a08d81e1-e105-4918-a917-3d226430d596'::uuid, 2, '["Renkle yalnızca","Boyutla yalnızca","Yön çizgi ve bulanıklıkla","Çerçeveyle"]'::jsonb, '["Işık, gölge ve hacimle","Ufuk çizgisi ve kaçış noktasıyla","Yön çizgi ve bulanıklıkla","Sıcak soğuk renk karşıtlığıyla"]'::jsonb, '["By colour alone","By size alone","By directional lines and blur","By the frame"]'::jsonb, '["By light, shadow and volume","By horizon line and vanishing point","By directional lines and blur","By warm-cool colour contrast"]'::jsonb),
    ('26b701ec-e114-4b0d-a507-f224baf2f8d5'::uuid, 1, '["Maç oynar","Branşı düzenler ve yönetir","Bilet basar","Saha yapar"]'::jsonb, '["Kulübü kurar ve yönetir","Branşı düzenler ve yönetir","Stadı işletir ve kiralar","Formayı üretir ve satar"]'::jsonb, '["Plays matches","Regulates and governs the sport","Prints tickets","Builds grounds"]'::jsonb, '["Founds and runs a club","Regulates and governs the sport","Operates and rents out the stadium","Makes and sells the kit"]'::jsonb),
    ('6526e06e-078c-4f1d-9c31-93ecaf231f3c'::uuid, 0, '["Hristiyan tebaanın çocuklarından","Müslüman tebaadan","Yabancı paralı askerlerden","Göçebe aşiretlerden"]'::jsonb, '["Hristiyan tebaanın çocuklarından","Savaş esirlerinden ve kölelerden","Tımarlı sipahi ailelerinden","Türkmen aşiretlerinin gençlerinden"]'::jsonb, '["Children of Christian subjects","Muslim subjects","Foreign mercenaries","Nomadic tribes"]'::jsonb, '["Children of Christian subjects","Prisoners of war and slaves","Families of timariot cavalry","Young men of Turkmen tribes"]'::jsonb),
    ('f5b40b80-a674-484c-8db8-2d6b51da5f04'::uuid, 0, '["Belgeyi biçimi bozulmadan taşımak","Ağ kurmak","Kod derlemek","Video oynatmak"]'::jsonb, '["Belgeyi biçimi bozulmadan taşımak","Görüntüyü kayıplı olarak sıkıştırmak","Tablodaki verileri formülle hesaplamak","Metni hiçbir biçim olmadan saklamak"]'::jsonb, '["Carrying a document without its layout breaking","Setting up a network","Compiling code","Playing video"]'::jsonb, '["Carrying a document without its layout breaking","Compressing an image lossily","Calculating table data with formulas","Storing text without any formatting"]'::jsonb),
    ('2c6e4f28-582c-4b6c-9f39-6d08052b77e3'::uuid, 0, '["Yapıt ve akımların gelişimini","Yalnız dilbilgisini","Yalnız ölçüyü","Yalnız yazımı"]'::jsonb, '["Yapıt ve akımların gelişimini","Sözcüklerin köken ve gelişimini","Dilin ses ve yapı kurallarını","Metnin ölçü ve uyak düzenini"]'::jsonb, '["The development of works and movements","Only grammar","Only metre","Only spelling"]'::jsonb, '["The development of works and movements","The origin and development of words","The sound and structure rules of language","A text''s metre and rhyme scheme"]'::jsonb),
    ('cf91b22a-033f-4f00-9d72-9d7eb5275099'::uuid, 3, '["Erken kalkmayı","Uzun yürümeyi","Çok uyumayı","Ölçülü harcamayı"]'::jsonb, '["Sabırlı olmayı","Çok çalışmayı","Büyüklere saygıyı","Ölçülü harcamayı"]'::jsonb, null, null),
    ('29ba991e-fcdd-4974-8eed-290472efef2d'::uuid, 1, '["Bol renk","Az öğeyle yalın anlatım","Aşırı süsleme","Anlatısal karmaşa"]'::jsonb, '["Işığın anlık ve renkli izlenimi","Az öğeyle yalın anlatım","Bilinçaltının rüya imgesi","Nesnenin geometrik parçalanması"]'::jsonb, '["Abundant colour","Plain expression with few elements","Excessive ornament","Narrative complexity"]'::jsonb, '["The fleeting, colourful impression of light","Plain expression with few elements","Dream images of the unconscious","Geometric fragmentation of the object"]'::jsonb),
    ('c2d09587-6957-48a2-8bee-8dc98ba26414'::uuid, 1, '["Aksiyon ve romantizmi","Karanlık konuyu gülünç anlatımla","Belgesel ve animasyonu","Müzikal ve korkuyu"]'::jsonb, '["Gerçek olayları kurgu anlatımla","Karanlık konuyu gülünç anlatımla","Aşk konusunu gülünç anlatımla","Suç konusunu karamsar anlatımla"]'::jsonb, '["Action and romance","A dark subject with comic treatment","Documentary and animation","The musical and horror"]'::jsonb, '["Real events with fictional treatment","A dark subject with comic treatment","A love story with comic treatment","A crime story with bleak treatment"]'::jsonb),
    ('7f79ac23-d7e6-4f58-b2a8-8ac353371d1a'::uuid, 0, '["James Watt","Newcomen","Stephenson","Fulton"]'::jsonb, '["James Watt","Thomas Newcomen","George Stephenson","Robert Fulton"]'::jsonb, '["James Watt","Newcomen","Stephenson","Fulton"]'::jsonb, '["James Watt","Thomas Newcomen","George Stephenson","Robert Fulton"]'::jsonb),
    ('4eb4fb54-d980-4d16-8db7-27d450325f1f'::uuid, 2, '["Yalnız yazıcı","Yalnız oyun çalıştırmak","Donanım ve yazılım arasında yönetim","Yalnız internet"]'::jsonb, '["Kaynak kodu makine diline çevirme","Web sayfalarını görüntüleme ve gezinme","Donanım ve yazılım arasında yönetim","Verileri tablo halinde düzenleme"]'::jsonb, '["Only the printer","Only running games","Managing between hardware and software","Only the internet"]'::jsonb, '["Translating source code into machine code","Displaying and browsing web pages","Managing between hardware and software","Organising data in tables"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 2: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 2: yanlış şıklar yeniden yazıldı (421)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 2: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 2: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
