-- ============================================================
-- 940 — 851'de "şık ipucu" nedeniyle pasife alınan 110 genel_kultur sorusu: şıklar düzeltildi, geri açıldı
-- (2 Eki 2026, Ida)
--
-- 851 bu 110 soruyu doğru şık çeldiricilerden belirgin uzun / tek çok kelimeli olduğu ya da Jev'in
-- soru metnini görmeden doğru şıkkı bulduğu için pasife almıştı. Bu migration:
--   • 93 sorunun YANLIŞ şıklarını yeniden yazar (doğru şıkla aynı uzunluk, biçim ve ayrıntı düzeyi) ve
--     aktif = true yapar. Soru metni, doğru cevap ve doğru şıkkın indeksi DEĞİŞMEZ
--     (match_answers.cevap indeksle tutulur; şık sırası karışmaz).
--   • 17 soruya DOKUNMAZ (pasif kalır): aynı bilgiyi soran tekrarlar, belirsiz bir soru ve üç denemede
--     Jev "soru gizli" testini geçemeyenler. Liste: docs/IPUCU_SIKLARI_YEDEK.json › acilmayan.
--   • EN çeviri: 91 satır AYNI indekslerle güncellenir (doğru şıkkın İngilizcesi aynen); 2 sorunun
--     çeviri satırı yoktur (atasözü/deyim) → Türkçe dışı maçta zaten sorulmaz.
--   • sik_ipucu_jev işareti (35 soruda vardı) kaldırılır: yeni şıklar aynı Jev testinden geçti
--     (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0,8). Kural işaretleri tetikleyicide yeniden hesaplanır.
-- Yalnız questions.secenekler / aktif / supheli_isaretler ve question_translations.secenekler yazılır.
-- Eski şıklar ve geri alma: docs/IPUCU_SIKLARI_YEDEK.json.
-- Koruma: yalnız hâlâ genel_kultur'da, pasif ve eski şıkları taşıyan satırlar; biri bile farklıysa hiçbiri yazılmaz.
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _ipucu_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _ipucu_sik values
    ('07ef6ff0-d7b3-4405-a3f2-f2cafa160133'::uuid, 2, '["Seçmeni bir partiye yöneltmek","Markaya bağlılık oluşturmak","Toplum yararına bilgilendirmek","Dizinin reytingini artırmak"]'::jsonb, '["Yeni bir ürünü tanıtmak","Güncel haberleri özetleyip sunmak","Toplum yararına bilgilendirmek","Bir sanat etkinliğini duyurmak"]'::jsonb, '["Steering voters towards a party","Building brand loyalty","Informing for the public good","Boosting a series'' ratings"]'::jsonb, '["Promoting a new product","Summarising and presenting the news","Informing for the public good","Announcing an arts event"]'::jsonb),
    ('0a46d4aa-37a1-4752-af2f-1c95796ad80e'::uuid, 3, '["Atığı toprağa gömmek","Atığı depoda biriktirmek","Atığı fırında yakmak","Atığı en aza indirmek"]'::jsonb, '["Enerjiyi daha verimli kullanmak","Su kaynaklarını korumak","Hava kirliliğini azaltmak","Atığı en aza indirmek"]'::jsonb, '["Burying waste","Accumulating waste","Burning waste","Minimising waste"]'::jsonb, '["Using energy more efficiently","Protecting water resources","Reducing air pollution","Minimising waste"]'::jsonb),
    ('0f95abdc-acf2-428c-9f23-bdd1c211e6da'::uuid, 0, '["Üretilen mal ve hizmetin değerini","Ülkedeki toplam nüfus sayısını","Ülkenin toplam yüzölçümünü","Yıllık ihracat miktarını"]'::jsonb, '["Üretilen mal ve hizmetin değerini","Fiyatların genel düzeyindeki artışı","İhracat ile ithalat arasındaki farkı","İş arayıp bulamayanların oranını"]'::jsonb, '["The value of goods and services produced","The population","The land area","The volume of exports"]'::jsonb, '["The value of goods and services produced","The rise in the general level of all prices","The gap between exports and imports","The share of job seekers without work"]'::jsonb),
    ('151ee83f-d710-4c41-a1f6-3117fb65bfe8'::uuid, 3, '["Sergilemeyle","Reklamla","Restorasyonla","Denetim ve uluslararası iş birliğiyle"]'::jsonb, '["Sergileme ve tanıtım kampanyalarıyla","Restorasyon ve düzenli bakım çalışmalarıyla","Müze giriş ücretlerini artırmakla","Denetim ve uluslararası iş birliğiyle"]'::jsonb, '["By exhibiting","By advertising","By restoration","By oversight and international cooperation"]'::jsonb, '["By exhibitions and publicity campaigns","By restoration and regular maintenance work","By raising museum admission fees","By oversight and international cooperation"]'::jsonb),
    ('1632f5aa-8b36-4f26-8d1f-d2d24bffce82'::uuid, 3, '["Çay","Fındık","İncir","Kaşar ve bal"]'::jsonb, '["Çay ve mısır","Fındık ve hamsi","İncir ve üzüm","Kaşar ve bal"]'::jsonb, '["Tea","Hazelnuts","Figs","Kaşar cheese and honey"]'::jsonb, '["Tea and maize","Hazelnuts and fresh anchovies","Figs and grapes","Kaşar cheese and honey"]'::jsonb),
    ('18b43af8-f022-4c71-99f9-79fd028cc409'::uuid, 3, '["Yasak koymayı","Vergi artırmayı","Nüfus azaltmayı","Gümrük kolaylıklarıyla ticaret çekmeyi"]'::jsonb, '["Yabancı bayraklı gemilere limanı kapatmayı","İthal mallara ek vergi koymayı","Kıyı kentlerinde nüfusu sınırlamayı","Gümrük kolaylıklarıyla ticaret çekmeyi"]'::jsonb, '["Imposing bans","Raising taxes","Reducing population","Attracting trade with customs facilities"]'::jsonb, '["Closing the port to foreign-flagged ships","Putting extra duties on imports","Limiting population in coastal towns","Attracting trade with customs facilities"]'::jsonb),
    ('19519f26-184a-496b-a9f2-774eb366b638'::uuid, 0, '["Tepki süresinin uzaması","Lastik aşınması","Motor ısınması","Yakıt tüketimi"]'::jsonb, '["Tepki süresinin uzaması","Yakıt tüketiminin artması","Motorun aşırı ısınması","Lastiklerin hızlı aşınması"]'::jsonb, '["Slower reaction time","Tyre wear","Engine overheating","Fuel consumption"]'::jsonb, '["Slower reaction time","Higher fuel consumption","Engine overheating","Faster tyre wear"]'::jsonb),
    ('1cf67ef7-8fd4-4449-b5fe-d200408e9de9'::uuid, 2, '["Turizmi yalnızca","Vergiyi","Evrensel değerli varlıkları korumayı","Ticareti"]'::jsonb, '["Nesli tehlikedeki türleri korumayı","Temiz su kaynaklarını korumayı","Evrensel değerli varlıkları korumayı","Deniz ticaret yollarını güvenceye almayı"]'::jsonb, '["Only tourism","Taxation","Protecting assets of universal value","Trade"]'::jsonb, '["Protecting endangered species","Protecting sources of clean water","Protecting assets of universal value","Securing the sea routes used for trade"]'::jsonb),
    ('1d63f5b0-ac12-4a17-bc33-2248217d9955'::uuid, 0, '["Kişisel verilerin korunmasını","Vergiyi","Ticareti","Telifi"]'::jsonb, '["Kişisel verilerin korunmasını","Kamu ihalelerinin denetlenmesini","Kira sözleşmelerinin koşullarını","Katma değer vergisinin oranını"]'::jsonb, '["Protection of personal data","Tax","Trade","Copyright"]'::jsonb, '["Protection of personal data","Oversight of public procurement","Terms of tenancy agreements","The rate of value added tax"]'::jsonb),
    ('1dd3d3ad-4715-4259-8f5e-e2c4ac1d6fd1'::uuid, 0, '["Dışarıya gideğeninin olmaması","Derin olması","Küçük olması","Soğuk olması"]'::jsonb, '["Dışarıya gideğeninin olmaması","Deniz seviyesinin altında olması","Yer altı sularıyla beslenmesi","Yüksek rakımda bulunması"]'::jsonb, '["It has no outlet to the sea","It is deep","It is small","It is cold"]'::jsonb, '["It has no outlet to the sea","It lies below sea level","It is fed mainly by underground springs","It sits at a high altitude"]'::jsonb),
    ('2396a312-60b5-4d00-b6c7-c0827ca00990'::uuid, 2, '["Vergi muafiyeti","Toprak bağışı","Girdi ve pazarlamada güç birliği","Su hakkı"]'::jsonb, '["Vergi ve harçlardan tam muafiyet","Hazine arazisinin bedelsiz devri","Girdi ve pazarlamada güç birliği","Sulama suyunun ücretsiz sağlanması"]'::jsonb, '["Tax exemption","A grant of land","Joint strength in inputs and marketing","Water rights"]'::jsonb, '["Full exemption from taxes and fees","Free transfer of treasury land","Joint strength in inputs and marketing","Irrigation water supplied free of charge"]'::jsonb),
    ('2452e982-4681-48a0-9c4d-72c78ae9787d'::uuid, 2, '["Genel okura","Çocuklara","Belirli alan uzmanlarına","Şairlere"]'::jsonb, '["Genel okur kitlesine","Yeni okuma yazma öğrenenlere","Belirli alan uzmanlarına","Yabancı dil öğrenenlere"]'::jsonb, '["The general reader","Children","Specialists in a particular field","Poets"]'::jsonb, '["The general reading public","People just learning to read and write","Specialists in a particular field","Learners of a foreign language"]'::jsonb),
    ('2543be5f-c8ff-48ba-9f44-63e07fa52f11'::uuid, 0, '["Salamurada bekletilir","Kızartılır","Dondurulur","Kurutulur"]'::jsonb, '["Salamurada bekletilir","Fırında kurutulur","Buzlukta dondurulur","Kızgın yağda kızartılır"]'::jsonb, '["They are kept in brine","They are fried","They are frozen","They are dried"]'::jsonb, '["They are kept in brine","They are dried in the oven","They are frozen solid","They are fried in hot oil"]'::jsonb),
    ('27255261-dd1f-4d0d-b63b-bf3cdc50aa48'::uuid, 2, '["Islak katlamak","Ütüsüz bırakmak","Uygun sıcaklıkta yıkamak","Kaynatmak"]'::jsonb, '["Renklileri ayrı yıkamak","Ters çevirip ütülemek","Uygun sıcaklıkta yıkamak","Yumuşatıcı ekleyip durulamak"]'::jsonb, '["Folding it wet","Leaving it unironed","Washing it at a suitable temperature","Boiling it"]'::jsonb, '["Washing coloureds separately","Ironing it inside out","Washing it at a suitable temperature","Rinsing it with fabric softener added"]'::jsonb),
    ('28703b1f-9a60-4b0f-bb7c-e6e8ade5372c'::uuid, 1, '["Kâr oranı","İki para biriminin değişim oranı","Vergi oranı","Faiz oranı"]'::jsonb, '["Bir bankanın yıllık kâr oranı","İki para biriminin değişim oranı","Devletin gelirden aldığı vergi oranı","Mevduata uygulanan faiz oranı"]'::jsonb, '["A profit rate","The rate of exchange between two currencies","A tax rate","An interest rate"]'::jsonb, '["A bank''s annual rate of profit","The rate of exchange between two currencies","The rate of tax the state charges on income","The interest rate applied to deposits"]'::jsonb),
    ('297afb2d-a25e-4864-bc70-f00c64390298'::uuid, 1, '["Vergi toplamak","Bölgeler arası farkı azaltmak","Nüfus saymak","Yol yapmak"]'::jsonb, '["Yerel vergileri toplamak","Bölgeler arası farkı azaltmak","İllerin nüfus sayımını yapmak","Şehirler arası kara yollarını yapmak"]'::jsonb, '["Collecting taxes","Reducing regional disparities","Counting the population","Building roads"]'::jsonb, '["Collecting local taxes","Reducing regional disparities","Carrying out the provincial census","Building intercity highways"]'::jsonb),
    ('2c6571cd-3a9b-40e2-b28a-5694df5b66d6'::uuid, 0, '["Ulusal değer ve tarihi","Nüfusu","Yüzölçümünü","İklimini"]'::jsonb, '["Ulusal değer ve tarihi","Nüfus ve yüzölçümünü","İklim ve bitki örtüsünü","Para birimi ve ekonomisini"]'::jsonb, '["National values and history","The population","The land area","The climate"]'::jsonb, '["National values and history","Population and land area","Climate and vegetation","The currency and the economy"]'::jsonb),
    ('2f2cd350-f9fe-4e35-9857-7b775b2178c1'::uuid, 3, '["Rokfor","Kaşar","Tulum","Tuzsuz taze peynir"]'::jsonb, '["Olgun kaşar peyniri","Erzincan tulum peyniri","Küflü rokfor peyniri","Tuzsuz taze peynir"]'::jsonb, '["Roquefort","Kaşar","Tulum","Unsalted fresh cheese"]'::jsonb, '["Mature kaşar cheese","Erzincan tulum cheese","Blue Roquefort cheese","Unsalted fresh cheese"]'::jsonb),
    ('3252490e-bc7d-4f1c-a243-36915b029d55'::uuid, 0, '["Metni düzeltip düzenler","Basar","Dağıtır","Satar"]'::jsonb, '["Metni düzeltip düzenler","Kitabı basıp ciltler","Kapağı çizip tasarlar","Baskıyı kitapçılara dağıtır"]'::jsonb, '["Corrects and arranges the text","Prints it","Distributes it","Sells it"]'::jsonb, '["Corrects and arranges the text","Prints and binds the book","Draws and designs the cover","Distributes the print run to bookshops"]'::jsonb),
    ('37cc75ff-1ddc-4775-b7b0-8de0737a98f3'::uuid, 3, '["Su","Güneş","Toprak","Sentetik kimyasallar"]'::jsonb, '["Nöbetleşe ekim yöntemi","Yerel tohumlar","Damla sulama","Sentetik kimyasallar"]'::jsonb, '["Water","Sunlight","Soil","Synthetic chemicals"]'::jsonb, '["The crop rotation method","Local seeds","Drip irrigation","Synthetic chemicals"]'::jsonb),
    ('394f6808-9249-4d8b-9654-ec4a9a8639a2'::uuid, 0, '["İthalatın ihracattan fazla olması","Nüfus artışı","Vergi artışı","İhracatın fazla olması"]'::jsonb, '["İthalatın ihracattan fazla olması","İhracatın ithalattan fazla olması","Kamu giderlerinin gelirleri aşması","Dış borcun millî geliri aşması"]'::jsonb, '["Imports exceeding exports","Population growth","A tax increase","Exports being higher"]'::jsonb, '["Imports exceeding exports","Exports exceeding imports","Public spending exceeding revenue","Foreign debt exceeding national income"]'::jsonb),
    ('3e3b1759-0a5d-4dd5-bd4c-5d18704ffb15'::uuid, 1, '["Irka","Ortak yurt ve kültür birliğine","Dine","Sınıfa"]'::jsonb, '["Egemenliğin millete ait olmasına","Ortak yurt ve kültür birliğine","Din ve devlet işlerinin ayrılığına","Yasalar önünde herkesin eşitliğine"]'::jsonb, '["Race","A shared homeland and culture","Religion","Class"]'::jsonb, '["Sovereignty belonging to the nation","A shared homeland and culture","The separation of religion and state","The equality of everyone before the law"]'::jsonb),
    ('3f1a176a-7ff6-4db9-ac85-029230a12716'::uuid, 1, '["Işık yakılmalı","Yetkili kontrolü beklenmeli","Hemen girilmeli","Asansör kullanılmalı"]'::jsonb, '["Elektrik sayacı okunmalı","Yetkili kontrolü beklenmeli","Bina yöneticisine haber verilmeli","Apartman görevlisi aranmalı"]'::jsonb, '["Turn on the lights","Wait for an official inspection","Go straight in","Use the lift"]'::jsonb, '["Read the electricity meter","Wait for an official inspection","Let the building manager know first","Call the building caretaker"]'::jsonb),
    ('42658a39-901c-47bc-bc90-5bf63dadd457'::uuid, 2, '["Cami binası","Antik kent","Gelenek, el sanatı ve müzik","Kale"]'::jsonb, '["Cami, kilise ve sinagog","Antik kent, höyük ve kale","Gelenek, el sanatı ve müzik","Saray, kasır ve tarihî konak"]'::jsonb, '["A mosque building","An ancient city","Traditions, crafts and music","A castle"]'::jsonb, '["Mosques, churches and synagogues","Ancient cities, mounds and castles","Traditions, crafts and music","Palaces, pavilions and old mansions"]'::jsonb),
    ('433d8d6f-5d48-4a2c-beca-6da7a353ddde'::uuid, 2, '["Gelişmiş bölgeyi büyütmek","Vergi artırmak","Geri kalmış bölgelere yatırım çekmek","Göçü artırmak"]'::jsonb, '["Kıyı bölgelerinde doğal alanları korumak","Büyük kentlerde trafik yoğunluğunu azaltmak","Geri kalmış bölgelere yatırım çekmek","Sınır bölgelerinde güvenliği artırmak"]'::jsonb, '["Grow an already developed region","Raise taxes","Attract investment to lagging regions","Increase migration"]'::jsonb, '["Protect natural areas in coastal regions","Reduce traffic congestion in big cities","Attract investment to lagging regions","Increase security in border regions"]'::jsonb),
    ('45828b01-4479-4773-b87e-1e7575070940'::uuid, 2, '["Valiliğe","Belediyeye","Sosyal güvenlik kurumuna","Bankaya"]'::jsonb, '["Vergi dairesi müdürlüğüne","İl özel idaresine","Sosyal güvenlik kurumuna","Nüfus müdürlüğüne"]'::jsonb, '["The governor''s office","The municipality","The social security institution","A bank"]'::jsonb, '["The tax office directorate","The special provincial administration","The social security institution","The civil registry office"]'::jsonb),
    ('481337a8-482a-4afa-9933-09d0befa2526'::uuid, 0, '["Gereksiz görüneni saklamak","Hızlı olmak","Saman satmak","Tarla sürmek"]'::jsonb, '["Gereksiz görüneni saklamak","Borcu vaktinde ödemek","Fırsatı hemen değerlendirmek","Sırrı kimseye söylememek"]'::jsonb, null, null),
    ('49292a24-8bd2-4393-a714-f861e785ec70'::uuid, 3, '["Sürücü belgesi","Sağlık kartı","Vergi kaydı","Uluslararası kimlik ve seyahat belgesi"]'::jsonb, '["Ulusal sürücü ve araç tescil belgesi","Uluslararası sağlık ve aşı belgesi","Yurt içi ikametgâh ve adres kayıt belgesi","Uluslararası kimlik ve seyahat belgesi"]'::jsonb, '["A driving licence","A health card","A tax record","An international identity and travel document"]'::jsonb, '["A national driving and vehicle registration document","An international health and vaccination document","A domestic residence and address record","An international identity and travel document"]'::jsonb),
    ('4ec64789-8fd9-43bb-be51-7ba5d8a17842'::uuid, 0, '["Enerji verimliliğini","Sesini","Ağırlığı","Rengi"]'::jsonb, '["Enerji verimliliğini","Gürültü düzeyini","Garanti süresini","Azami yük kapasitesini"]'::jsonb, '["Its energy efficiency","Its noise","Its weight","Its colour"]'::jsonb, '["Its energy efficiency","Its noise level","Its warranty period","Its maximum load capacity"]'::jsonb),
    ('4f1bdb40-f3ba-454d-a9be-6d5e05dfec44'::uuid, 3, '["Silahlı direniş","Oy kullanmama","Vergi kaçırma","Haksız yasaya şiddetsiz karşı çıkma"]'::jsonb, '["Haksız işleme mahkemede itiraz etme","Yöneticileri seçimle görevden uzaklaştırma","İşverene karşı topluca iş bırakma","Haksız yasaya şiddetsiz karşı çıkma"]'::jsonb, '["Armed resistance","Not voting","Tax evasion","Opposing an unjust law without violence"]'::jsonb, '["Challenging an unjust act in court","Removing those in office through an election","Collectively stopping work against an employer","Opposing an unjust law without violence"]'::jsonb),
    ('4fdd0b03-dea7-4b28-ae07-d1e1bc20e6d7'::uuid, 0, '["İzlenecek yol doğrultusu","Gemi hızı","Yük miktarı","Liman adı"]'::jsonb, '["İzlenecek yol doğrultusu","Geminin ulaşabildiği azami hız","Taşınan yükün miktarı","Varılacak limanın adı"]'::jsonb, '["The direction to be followed","The ship''s speed","The amount of cargo","The name of the port"]'::jsonb, '["The direction to be followed","The top speed the ship can reach","The amount of cargo carried","The name of the port of arrival"]'::jsonb),
    ('58bd94bc-e4a8-4c86-9c44-0890a23ea94f'::uuid, 2, '["Rahatlık","Görüş açısı","Çocuğun bedenine uygun koruma","Estetik"]'::jsonb, '["Çocuğun yaşına uygun eğlence","Çocuğun boyuna uygun görüş açısı","Çocuğun bedenine uygun koruma","Çocuğun kilosuna uygun konfor"]'::jsonb, '["Comfort","The field of view","Protection suited to a child''s body","Appearance"]'::jsonb, '["Entertainment suited to a child''s age","A field of view suited to a child''s height","Protection suited to a child''s body","Comfort suited to a child''s weight"]'::jsonb),
    ('5cde6d88-3324-4b7f-b0b9-8dfb6a182287'::uuid, 2, '["Fazla un","Soğuk yumurta","Erken kapak açma ve ısı düşüşü","Az şeker"]'::jsonb, '["Kalıbı hiç yağlamama ve kekin yapışması","Fazla pişirme ve kekin kuruması","Erken kapak açma ve ısı düşüşü","Unu elememe ve hamurun topaklanması"]'::jsonb, '["Too much flour","Cold eggs","Opening the oven early and the drop in heat","Too little sugar"]'::jsonb, '["Not greasing the tin at all and the cake sticking","Overbaking and the cake drying out","Opening the oven early and the drop in heat","Not sifting the flour and the batter going lumpy"]'::jsonb),
    ('5dfa93f7-b6a1-4c50-9cd5-a9169b1ec35a'::uuid, 1, '["Kart verilir","Belirli süre bekletilir","Şubesizdir","Ücretsizdir"]'::jsonb, '["Faiz geliri sağlamaz","Belirli süre bekletilir","Yalnızca dövizle açılır","Devlet güvencesi taşımaz"]'::jsonb, '["A card is issued","The money is held for a set period","It has no branch","It is free"]'::jsonb, '["It earns no interest at all","The money is held for a set period","It can only be opened in foreign currency","It carries no state guarantee"]'::jsonb),
    ('5f77ae49-1ddc-4f8f-ac2c-c14cda4a9acd'::uuid, 3, '["Hava yollarını","Demir yollarını","Kara yollarını","Türk karasularında taşımacılığı"]'::jsonb, '["Türk hava sahasında uçuşları","Türk limanlarında gümrük vergisini","Boğazlardan geçiş ücretlerini","Türk karasularında taşımacılığı"]'::jsonb, '["Air routes","Railways","Roads","Shipping in Turkish territorial waters"]'::jsonb, '["Flights in Turkish airspace","Customs duties charged at Turkish ports","Transit fees through the Straits","Shipping in Turkish territorial waters"]'::jsonb),
    ('627c2014-2977-442e-a643-7e6509f588b2'::uuid, 3, '["Pirinç","Nohut","Mercimek","Darı veya bulgur"]'::jsonb, '["Nohut veya mercimek","Susam veya haşhaş","Fasulye veya bakla","Darı veya bulgur"]'::jsonb, '["Rice","Chickpeas","Lentils","Millet or bulgur"]'::jsonb, '["Chickpeas or lentils","Sesame or poppy seed","Beans or broad beans","Millet or bulgur"]'::jsonb),
    ('63843f4c-11df-4a3f-bec0-015e29aa8418'::uuid, 2, '["Özel yazışmaları okumayı","Sınav sorusu almayı","Kamu bilgilerine erişebilmeyi","Ticari sır öğrenmeyi"]'::jsonb, '["Özel yazışmalara erişebilmeyi","Ticari sırlara erişebilmeyi","Kamu bilgilerine erişebilmeyi","Sınav sorularına önceden erişebilmeyi"]'::jsonb, '["Reading private correspondence","Obtaining exam questions","Access to public information","Learning trade secrets"]'::jsonb, '["Access to private correspondence","Access to trade secrets","Access to public information","Access to exam questions in advance"]'::jsonb),
    ('656446f6-4fc4-4deb-82e3-ae10b5fc1dc8'::uuid, 2, '["Rengini","Şişesini","Pişirmeye uygunluğunu","Fiyatını"]'::jsonb, '["Şişedeki raf ömrünü","Asitlik derecesini","Pişirmeye uygunluğunu","Hasat ve sıkım tarihini"]'::jsonb, '["Its colour","Its bottle","Its suitability for cooking","Its price"]'::jsonb, '["Its shelf life in the bottle","Its degree of acidity","Its suitability for cooking","Its harvest and pressing date"]'::jsonb),
    ('6622b126-6ab5-405b-8bc2-4a1e02f42c26'::uuid, 3, '["Vergi geliri","İhracat artışı","Nüfus artışı","Dayanışma ve hizmet üretimi"]'::jsonb, '["Vergi geliri ve bütçe fazlası","İhracat artışı ve döviz girdisi","Nüfus artışı ve iş gücü","Dayanışma ve hizmet üretimi"]'::jsonb, '["Tax revenue","Higher exports","Population growth","Solidarity and the provision of services"]'::jsonb, '["Tax revenue and a budget surplus","Higher exports and foreign currency income","Population growth and labour","Solidarity and the provision of services"]'::jsonb),
    ('68cee3dd-381a-416f-9414-6068fb2bb2dc'::uuid, 1, '["Tek merkezli olması","Eyaletlerin kendi yetkilerinin olması","Yönetimsiz olması","Sınırsız olması"]'::jsonb, '["Tüm yetkinin merkezde toplanması","Eyaletlerin kendi yetkilerinin olması","Eyaletlerin tam bağımsız devlet olması","Yasama organının hiç bulunmaması"]'::jsonb, '["Having a single centre","States having their own powers","Having no government","Being unlimited"]'::jsonb, '["All power being held at the centre","States having their own powers","States being fully independent countries","Having no legislature at all"]'::jsonb),
    ('6afae723-c5a5-45b3-a1d5-559f239f45a2'::uuid, 2, '["Kavurma","Haşlama","Salamura ve fermantasyon","Kurutma"]'::jsonb, '["Kavurma ve tütsüleme","Kaynatma ve yoğunlaştırma","Salamura ve fermantasyon","Kurutma ve öğütme"]'::jsonb, '["Roasting","Boiling","Brining and fermentation","Drying"]'::jsonb, '["Roasting and smoking","Boiling and concentrating","Brining and fermentation","Drying and grinding"]'::jsonb),
    ('6ba6f991-8947-4107-89ae-bee35f55aef8'::uuid, 3, '["Kahve","Çay","Zeytin","Çikolata ve saat"]'::jsonb, '["Kahve ve puro","Çay ve ince porselen","Zeytinyağı ve şarap","Çikolata ve saat"]'::jsonb, '["Coffee","Tea","Olives","Chocolate and watches"]'::jsonb, '["Coffee and cigars","Tea and fine porcelain","Olive oil and wine","Chocolate and watches"]'::jsonb),
    ('7353ebcb-2a41-4b61-9b1a-c65e14d0b45e'::uuid, 2, '["Tek ülkede üretimi","Yerel ticareti","Üretimin ülkelere yayılmış olmasını","El üretimini"]'::jsonb, '["Şirketlerin sınır ötesi birleşmesini","Ülkelerin ortak para kullanmasını","Üretimin ülkelere yayılmış olmasını","Gümrük vergilerinin kaldırılmasını"]'::jsonb, '["Production in a single country","Local trade","Production spread across countries","Handmade production"]'::jsonb, '["Companies merging across borders","Countries sharing a single common currency","Production spread across countries","The removal of customs duties"]'::jsonb),
    ('75fb4ac6-a00f-4b42-8b4e-f4d88d74d7af'::uuid, 0, '["Gelecek kuşakları gözeten kalkınma","Sınırsız üretim","Doğayı yok sayma","Hızlı tüketim"]'::jsonb, '["Gelecek kuşakları gözeten kalkınma","Kırsal kesimi önceleyen kalkınma","Bölgeler arası dengeyi gözeten kalkınma","Sanayileşmeyi önceleyen kalkınma"]'::jsonb, '["Development that considers future generations","Unlimited production","Ignoring nature","Rapid consumption"]'::jsonb, '["Development that considers future generations","Development that puts rural areas first","Development that seeks balance between regions","Development that puts industrialisation first"]'::jsonb),
    ('7a64238c-4992-4d3d-960d-971894a894d8'::uuid, 1, '["Ürün fiyatını","Tüketicinin markayı tanıma düzeyini","Üretim miktarını","Mağaza sayısını"]'::jsonb, '["Tüketicinin markaya bağlılık düzeyini","Tüketicinin markayı tanıma düzeyini","Markanın pazardaki satış payını","Müşterinin üründen memnuniyet düzeyini"]'::jsonb, '["The price of the product","How well consumers know the brand","The volume produced","The number of shops"]'::jsonb, '["How loyal consumers are to the brand","How well consumers know the brand","The brand''s share of sales in the market","How satisfied customers are with the product"]'::jsonb),
    ('7a939b14-07eb-46db-b559-958d0817f910'::uuid, 0, '["Standart hacim","Renk","Uzunluk","Malzeme"]'::jsonb, '["Standart hacim","Daha uzun sap","Paslanmaz çelik","Daha sivri uç"]'::jsonb, '["A standard volume","The colour","The length","The material"]'::jsonb, '["A standard volume","A longer handle","Stainless steel","A more pointed tip"]'::jsonb),
    ('7bc21bcf-dcf3-4c3b-b957-056e90e6a268'::uuid, 3, '["Yol genişliğini artırması","Otopark artırması","Hız artırması","Emisyon ve trafiği azaltması"]'::jsonb, '["Sel ve taşkını önlemesi","Gürültü ve tozu perdelemesi","Konut ve kira fiyatını düşürmesi","Emisyon ve trafiği azaltması"]'::jsonb, '["Widening the road","More parking","Higher speeds","Less emission and traffic"]'::jsonb, '["Preventing floods and overflow","Screening out noise and dust","Lowering house prices and rents","Less emission and traffic"]'::jsonb),
    ('7c1e7d4e-1b24-43e4-bfd9-d395f19add2b'::uuid, 1, '["Bütçe artırmak","Riskleri belirlemek","Rapor yazmak","Ekip kurmak"]'::jsonb, '["Önlemleri uygulamak","Riskleri belirlemek","Riskleri önceliklendirmek","Sonuçları izlemek"]'::jsonb, '["Increasing the budget","Identifying the risks","Writing a report","Forming a team"]'::jsonb, '["Applying the measures","Identifying the risks","Prioritising the risks","Monitoring the results"]'::jsonb),
    ('7d292eb4-5a62-44d1-a3eb-391ad2fa5f46'::uuid, 2, '["Karadeniz","Trakya","Doğu ve Güneydoğu Anadolu","Ege"]'::jsonb, '["Doğu Karadeniz kıyı şeridi","Trakya ve Güney Marmara","Doğu ve Güneydoğu Anadolu","Ege ve Batı Akdeniz"]'::jsonb, '["Black Sea","Thrace","Eastern and Southeastern Anatolia","Aegean"]'::jsonb, '["The eastern Black Sea coastal strip","Thrace and southern Marmara","Eastern and Southeastern Anatolia","The Aegean and western Mediterranean"]'::jsonb),
    ('7e3b0826-449b-42f3-bea9-fe8fa7256e70'::uuid, 3, '["Ürün tanıtmak","Kurgu anlatmak","Oy toplamak","Bilgilendirmek"]'::jsonb, '["Eğlendirmek","İkna etmek","Heyecanlandırmak","Bilgilendirmek"]'::jsonb, '["Promoting a product","Telling fiction","Winning votes","Informing"]'::jsonb, '["Entertaining","Persuading","Thrilling","Informing"]'::jsonb),
    ('7efbf9ae-465e-4d6f-989f-01f2a3892603'::uuid, 0, '["Maden ve enerji","Dokuma","Gıda","Ulaşım"]'::jsonb, '["Maden ve enerji","Dokuma ve giyim","Tarım ve gıda","Denizcilik ve ulaşım"]'::jsonb, '["Mining and energy","Textiles","Food","Transport"]'::jsonb, '["Mining and energy","Textiles and clothing","Farming and food","Shipping and transport"]'::jsonb),
    ('82701b11-3591-4872-bfbc-91eb185529f8'::uuid, 3, '["Savaş","Bilgelik","Av","Aşk ve güzellik"]'::jsonb, '["Bilgelik ve savaş","Av ve yaban hayatı","Tarım ve bereket","Aşk ve güzellik"]'::jsonb, '["War","Wisdom","The hunt","Love and beauty"]'::jsonb, '["Wisdom and war","The hunt and wild animals","Farming and fertility","Love and beauty"]'::jsonb),
    ('852e3611-ec1d-41e8-943b-bcad22ff99bd'::uuid, 1, '["Üretimin azalması","Genel fiyat düzeyinin artması","İşsizliğin artması","Faizin düşmesi"]'::jsonb, '["Toplam üretim miktarının azalması","Genel fiyat düzeyinin artması","İşsizlik oranının artması","Faiz oranlarının düşmesi"]'::jsonb, '["A fall in production","A rise in the general price level","Rising unemployment","Falling interest rates"]'::jsonb, '["A fall in the total volume of output","A rise in the general price level","A rise in the unemployment rate","A fall in interest rates"]'::jsonb),
    ('8a4fe5b9-1acb-4f4e-b375-e28955ba4452'::uuid, 2, '["Ses yankısını","Haber çeşitliliğini","Benzer görüşlerle çevrelenmeyi","Tarafsızlığı"]'::jsonb, '["Sesin duvarlardan yansımasını","Farklı kaynaklardan haber almayı","Benzer görüşlerle çevrelenmeyi","Haberin tarafsız aktarılmasını"]'::jsonb, '["An acoustic echo","A variety of news","Being surrounded by like-minded views","Impartiality"]'::jsonb, '["Sound bouncing back off the walls","Getting news from a variety of sources","Being surrounded by like-minded views","News being reported impartially"]'::jsonb),
    ('8dd526b7-18b6-4872-88e7-f166407d7f35'::uuid, 1, '["Ülke politikasını","Parsel ve yapılaşma koşullarını","Bölge iklimini","Nüfus sayımını"]'::jsonb, '["Ülkenin kalkınma hedeflerini","Parsel ve yapılaşma koşullarını","Bölgenin iklim ve bitki özelliklerini","İlin nüfus ve göç tahminlerini"]'::jsonb, '["National policy","Plot boundaries and building conditions","The regional climate","The census"]'::jsonb, '["The country''s development goals","Plot boundaries and building conditions","The region''s climate and vegetation features","The province''s population and migration forecasts"]'::jsonb),
    ('902ae1b1-4a6b-4e6c-a9af-6d029f8cade1'::uuid, 0, '["Geleneksel evleri","Yaylaları","Mağaraları","Plajları"]'::jsonb, '["Geleneksel evleri","Kaya kiliseleri","Antik tiyatrosu","Damlataşı mağaraları"]'::jsonb, '["Its traditional houses","Its highland pastures","Its caves","Its beaches"]'::jsonb, '["Its traditional houses","Its rock churches","Its ancient theatre","Its stalactite-filled caves"]'::jsonb),
    ('9684d3a4-6ea3-4d8d-a4ba-c37972d91d80'::uuid, 3, '["Fark etmez","Kışın en soğuğu","Yaz ortası","Sonbahar veya ilkbahar"]'::jsonb, '["Yaz ortası veya sonu","Kışın en soğuk ayı","Yazın en sıcak haftaları","Sonbahar veya ilkbahar"]'::jsonb, '["It makes no difference","The coldest part of winter","Midsummer","Autumn or spring"]'::jsonb, '["Midsummer or late summer","The coldest month of winter","The hottest weeks of summer","Autumn or spring"]'::jsonb),
    ('98b25f3b-e0c1-458d-88cf-37f71518cc5f'::uuid, 3, '["Ticareti","Savaşı","Dini","Siyasal iktidarın kaynağını"]'::jsonb, '["Uluslararası ticaretin kurallarını","Dinî inançların kökenini","Sanatın toplumsal işlevini","Siyasal iktidarın kaynağını"]'::jsonb, '["Trade","War","Religion","The source of political authority"]'::jsonb, '["The rules governing international trade","The origin of religious beliefs","The social function of art","The source of political authority"]'::jsonb),
    ('9bd2c45a-1378-49be-b4cc-8db5cf52204a'::uuid, 0, '["Biri güvenlik, diğeri kalite","İkisi aynı","Biri ağırlık","Biri fiyat"]'::jsonb, '["Biri güvenlik, diğeri kalite","Biri üretim, diğeri paketleme","Biri ithal, diğeri yerli ürün","Biri açılmış, diğeri kapalı ürün"]'::jsonb, '["One is about safety, the other about quality","They are the same","One is about weight","One is about price"]'::jsonb, '["One is about safety, the other about quality","One is about production, the other about packaging","One is for imported, the other for local goods","One is for opened, the other for sealed goods"]'::jsonb),
    ('9c9fa247-ab20-44eb-adbd-9d195cd3b00c'::uuid, 1, '["Kesin tedavi uygulamak","Yardım gelene dek durumu korumak","İlaç yazmak","Ameliyat yapmak"]'::jsonb, '["Hastalığın nedenini kesin olarak belirlemek","Yardım gelene dek durumu korumak","Hastalığı ortaya çıkmadan önlemek","Hastayı normal yaşamına döndürmek"]'::jsonb, '["Applying definitive treatment","Keeping the person stable until help arrives","Prescribing medicine","Operating"]'::jsonb, '["Establishing the exact underlying cause of the illness","Keeping the person stable until help arrives","Preventing the illness before it appears","Returning the patient to normal daily life"]'::jsonb),
    ('9cfdb289-0159-40de-9d37-47dc3e33a0aa'::uuid, 1, '["Fiyat indirimini","Belirli süre onarım ve değişim hakkını","Kargo ücretini","Vergi iadesini"]'::jsonb, '["Belirli süre içinde cayma ve iade hakkını","Belirli süre onarım ve değişim hakkını","Taksitle ödeme ve erteleme hakkını","Kaza ve hırsızlığa karşı tazminat hakkını"]'::jsonb, '["A discount","The right to repair or replacement for a set period","The shipping cost","A tax refund"]'::jsonb, '["The right to withdraw and return it within a set period","The right to repair or replacement for a set period","The right to pay in instalments or defer","The right to compensation for accident or theft"]'::jsonb),
    ('a11db30d-7401-4481-9e04-dcae1f6e162b'::uuid, 2, '["Hava tahmini","Su yapıları","Maden ve yer bilimleri araştırmaları","Orman yönetimi"]'::jsonb, '["Hava tahmini ve iklim araştırmaları","Baraj ve sulama yapılarının yapımı","Maden ve yer bilimleri araştırmaları","Orman varlığının korunması ve yönetimi"]'::jsonb, '["Weather forecasting","Hydraulic works","Mineral and earth science research","Forest management"]'::jsonb, '["Weather forecasting and climate research","Building dams and irrigation works","Mineral and earth science research","Protecting and managing forests"]'::jsonb),
    ('a16e948d-e5b0-4f2f-86ba-a38d8ec25398'::uuid, 1, '["Sadece ihracat","Bir ülke üzerinden geçen ticaret","Sadece ithalat","İç ticaret"]'::jsonb, '["Yalnız komşu ülkelerle yapılan ticaret","Bir ülke üzerinden geçen ticaret","Serbest bölge içinde yapılan ticaret","Aynı ülke içinde yapılan ticaret"]'::jsonb, '["Export only","Trade passing through a country","Import only","Domestic trade"]'::jsonb, '["Trade carried on only with neighbours","Trade passing through a country","Trade carried on inside a free zone","Trade within a single country"]'::jsonb),
    ('a2595d97-930d-4c65-bee6-aba324ec12d3'::uuid, 1, '["Tatlı çeşidi","Ana yemek öncesi küçük tabaklar","Çorba türü","Ekmek çeşidi"]'::jsonb, '["Ana yemek sonrası hafif tatlılar","Ana yemek öncesi küçük tabaklar","Çay yanında sunulan kuru pastalar","Yolculukta yenen hafif azıklar"]'::jsonb, '["A kind of dessert","Small plates before the main course","A kind of soup","A kind of bread"]'::jsonb, '["Light sweets after the main course","Small plates before the main course","Dry pastries served alongside tea","Light provisions eaten on a journey"]'::jsonb),
    ('abea9f65-6ade-428a-8350-d97133e254a6'::uuid, 2, '["Tarımın çöktüğünü","Nüfusun azaldığını","Katma değerin yükseldiğini","İthalatın bittiğini"]'::jsonb, '["Nüfusun hızla yaşlandığını","Ham madde üretiminin arttığını","Katma değerin yükseldiğini","Turizm gelirinin azaldığını"]'::jsonb, '["That farming has collapsed","That the population has fallen","That value added has risen","That imports have ceased"]'::jsonb, '["That the population is ageing fast","That raw material output has risen","That value added has risen","That tourism income has fallen"]'::jsonb),
    ('ac608f83-1a25-435a-ad61-3f9483bff9c6'::uuid, 1, '["İklim değişikliği","Baskın dile geçiş ve kuşak kopukluğu","Deprem","Ulaşım"]'::jsonb, '["Küresel iklim değişikliği ve uzun kuraklık","Baskın dile geçiş ve kuşak kopukluğu","Yazı sistemlerinin karmaşık olması","Deprem ve benzeri doğal afetler"]'::jsonb, '["Climate change","A shift to a dominant language and a break between generations","Earthquakes","Transport"]'::jsonb, '["Global climate change and the prolonged periods of drought that follow","A shift to a dominant language and a break between generations","The great complexity of their writing systems","Earthquakes and other similar natural disasters"]'::jsonb),
    ('ac76149b-f9ec-4ffa-a611-90d701bae49c'::uuid, 1, '["Depo büyüklüğü","Hızlı ve doğru dağıtım","Araç rengi","Personel sayısı"]'::jsonb, '["Düşük ve sabit maliyet","Hızlı ve doğru dağıtım","Geniş ve çeşitli ürün yelpazesi","Yüksek ve düzenli kâr"]'::jsonb, '["Warehouse size","Fast and accurate distribution","The colour of the vehicles","The number of staff"]'::jsonb, '["Low and stable cost","Fast and accurate distribution","A wide and varied product range","High and steady profit"]'::jsonb),
    ('af6d6517-ebde-4c4c-a230-99d9d5153a79'::uuid, 3, '["Yağ ekler","Şeker katar","Tuz artırır","Besin değerini korur"]'::jsonb, '["Yemeği çıtır yapar","Kabuğu kızartır","Şekeri karamelize eder","Besin değerini korur"]'::jsonb, '["It adds fat","It adds sugar","It raises the salt","It preserves nutritional value"]'::jsonb, '["It makes food crisp","It browns the crust","It caramelises the natural sugars","It preserves nutritional value"]'::jsonb),
    ('b0f64dec-7364-4af9-970f-0fdbdac86fed'::uuid, 1, '["Mucidinin adından","Klavyenin ilk altı harfinden","Bir kısaltmadan","Üretici firmadan"]'::jsonb, '["Mucidinin adının baş harflerinden","Klavyenin ilk altı harfinden","Üretici firmanın kısaltmasından","İlk daktilo modelinin adından"]'::jsonb, '["From its inventor''s name","From the first six letters of the keyboard","From an abbreviation","From the manufacturer"]'::jsonb, '["From the initials of its inventor''s name","From the first six letters of the keyboard","From the manufacturer''s abbreviation","From the name of the first typewriter model"]'::jsonb),
    ('b28bf292-4303-4fe8-bb9f-3cedbc5f9ed5'::uuid, 0, '["Aynalardan görülemeyen alan","Duraklama yeri","Kavşak ortası","Yaya geçidi"]'::jsonb, '["Aynalardan görülemeyen alan","Duraklamanın yasak olduğu alan","Kavşağın tam orta noktası","Yaya geçidinin önündeki alan"]'::jsonb, '["The area not visible in the mirrors","A place to stop","The middle of a junction","A pedestrian crossing"]'::jsonb, '["The area not visible in the mirrors","The area where stopping is forbidden","The exact centre of a junction","The area in front of a pedestrian crossing"]'::jsonb),
    ('b39bab70-30b9-4f7d-aa64-352796cc8544'::uuid, 2, '["Bitkileri","Denizleri","İnsanı ve kültürlerini","Metalleri"]'::jsonb, '["Bitkileri ve ortamlarını","Denizleri ve canlılarını","İnsanı ve kültürlerini","Metalleri ve alaşımlarını"]'::jsonb, '["Plants","The seas","Humans and their cultures","Metals"]'::jsonb, '["Plants and their habitats","The seas and their creatures","Humans and their cultures","Metals and their alloys"]'::jsonb),
    ('b48cb8b2-4345-4611-bce3-c15113c3c888'::uuid, 2, '["Kira sözleşmesini","Trafik cezasını","Ölen kişinin mal paylaşımını","Vergi oranını"]'::jsonb, '["Kiracı ile ev sahibi ilişkisini","Trafik cezalarının tahsilini","Ölen kişinin mal paylaşımını","Şirketlerin vergi oranını"]'::jsonb, '["Tenancy agreements","Traffic fines","The division of a deceased person''s property","Tax rates"]'::jsonb, '["The relationship between a tenant and a landlord","The collection of traffic fines","The division of a deceased person''s property","The rate of tax paid by companies"]'::jsonb),
    ('b4e54d05-26fa-432d-abd6-7e494a5431b4'::uuid, 1, '["Kabuk","Çiçek tepeciği","Tohum","Kök"]'::jsonb, '["Ağaç kabuğu","Çiçek tepeciği","Kurutulmuş tohum","Kök gövdesi"]'::jsonb, '["The bark","The flower''s stigma","The seed","The root"]'::jsonb, '["The bark of the tree","The flower''s stigma","The dried seed","The root stem"]'::jsonb),
    ('b50d313f-027b-478c-a594-14b5f89e1883'::uuid, 3, '["Karbonun depolanması","Ormanın satılması","Enerji üretimi","Salım hakkının alınıp satılması"]'::jsonb, '["Karbonun yer altında depolanması","Yakıta salım oranında vergi konması","Ağaç dikilerek salımın dengelenmesi","Salım hakkının alınıp satılması"]'::jsonb, '["Storing carbon","Selling forests","Producing energy","Buying and selling the right to emit"]'::jsonb, '["Storing the captured carbon deep under the ground","Taxing fuel in proportion to its emissions","Offsetting emissions by planting trees","Buying and selling the right to emit"]'::jsonb),
    ('b5505fb6-bfc0-468e-80e8-71992cccbe8b'::uuid, 2, '["Hızlanmak","Tünelde durmak","Güvenli yerde durmak","Köprüye girmek"]'::jsonb, '["Alt geçide sığınmak","Köprü altında beklemek","Güvenli yerde durmak","Binaya yakın park etmek"]'::jsonb, '["Accelerate","Stop in a tunnel","Stop in a safe place","Drive onto a bridge"]'::jsonb, '["Shelter in an underpass","Wait under a bridge","Stop in a safe place","Park close to a building"]'::jsonb),
    ('b67fcfa3-1788-4304-8a71-1fd7ccf51fb1'::uuid, 1, '["Uzayın paylaşılması","Uzayın tüm insanlığın ortak alanı olması","Uzayın satılması","Uzayın kapatılması"]'::jsonb, '["Açık denizlerin tüm devletlere açık olması","Uzayın tüm insanlığın ortak alanı olması","Savaşta sivillerin hedef alınmaması","Devletlerin hava sahasında egemen olması"]'::jsonb, '["Dividing space up","Space as the common domain of all humanity","Selling space","Closing space off"]'::jsonb, '["The high seas being open to all states","Space as the common domain of all humanity","Civilians not being targeted in war","States being sovereign over their own airspace"]'::jsonb),
    ('b988a92f-f784-443f-96b1-3d0f2983bce5'::uuid, 2, '["Uyku","Susuzluk","Tırnak bakımı ve işaretleme","Açlık"]'::jsonb, '["Uyku ve dinlenme hazırlığı","Susuzluk ve açlık belirtisi","Tırnak bakımı ve işaretleme","Mevsimlik tüy dökümü ve kaşıntı"]'::jsonb, '["Sleep","Thirst","Claw care and marking","Hunger"]'::jsonb, '["Getting ready to sleep","A sign of thirst and hunger","Claw care and marking","Seasonal moulting and itching"]'::jsonb),
    ('bc7cc6a4-7457-40c3-a1ae-dda4ab97ae9b'::uuid, 3, '["Kültürlerin ayrışması","Göçün durması","Dilin korunması","Bir grubun baskın kültüre karışması"]'::jsonb, '["İki kültürün birbirinden ayrışması","Bir dilin okullarda korunması","Bir topluluğun başka ülkeye göç etmesi","Bir grubun baskın kültüre karışması"]'::jsonb, '["Cultures separating","Migration stopping","A language being preserved","A group merging into the dominant culture"]'::jsonb, '["Two cultures drifting apart from each other","A language being preserved in schools","A community migrating to another country","A group merging into the dominant culture"]'::jsonb),
    ('c6e0574a-e3a6-4374-8368-e2b50975da16'::uuid, 3, '["Fiyat düşüşü","Üretim artışı","Talep artışı","Üretim gecikmesi ve fiyat artışı"]'::jsonb, '["Üretim artışı ve fiyat düşüşü","Stok fazlası ve talepte hızlı düşüş","İstihdam artışı ve ücret artışı","Üretim gecikmesi ve fiyat artışı"]'::jsonb, '["A fall in prices","A rise in output","A rise in demand","Delayed production and rising prices"]'::jsonb, '["Higher output and falling prices","Excess stock and a sharp fall in demand","More jobs and rising wages","Delayed production and rising prices"]'::jsonb),
    ('d0e22222-8074-42fb-b927-0e6b81671f96'::uuid, 0, '["Anayasa ve meclisin varlığı","Hükümdarın yaşı","Ülkenin büyüklüğü","Ordunun gücü"]'::jsonb, '["Anayasa ve meclisin varlığı","Hükümdarın tahta soydan gelmesi","Ordunun hükümdara bağlılığı","Başkentin ve sarayın konumu"]'::jsonb, '["The existence of a constitution and a parliament","The ruler''s age","The size of the country","The strength of the army"]'::jsonb, '["The existence of a constitution and a parliament","The ruler coming to the throne by hereditary descent","The army''s loyalty to the ruler","The location of the capital and the palace"]'::jsonb),
    ('d7ebfed3-9a2d-4486-a5de-3b328adac33f'::uuid, 1, '["Tarım ürünleri","Petrol üretim ve fiyat politikası","Tekstil","Turizm"]'::jsonb, '["Nükleer enerji ve güvenlik denetimi","Petrol üretim ve fiyat politikası","Dünya ticareti ve gümrük kuralları","Küresel sağlık ve salgın yönetimi"]'::jsonb, '["Farm produce","Oil production and pricing policy","Textiles","Tourism"]'::jsonb, '["Nuclear energy and safety oversight","Oil production and pricing policy","World trade and customs rules","Global health and epidemic management"]'::jsonb),
    ('e10a2e69-fbef-412c-baf6-e59c81ff4c0e'::uuid, 1, '["Fiyatı","Yapılmaması gerekeni","Zorunluluğu","Öneriyi"]'::jsonb, '["Yapılması zorunlu olanı","Yapılmaması gerekeni","Tavsiye edilen işlemi","Kumaşın türünü"]'::jsonb, '["The price","What must not be done","A requirement","A recommendation"]'::jsonb, '["What must always be done","What must not be done","The recommended treatment","The type of fabric"]'::jsonb),
    ('e15c25f2-abad-4dbc-892b-0c879ffec1a8'::uuid, 1, '["Sanayisi","Farklı din ve kültürlerin birlikteliği","Üniversiteleri","Limanı"]'::jsonb, '["Köklü ağır sanayi ve demir çelik üretimi","Farklı din ve kültürlerin birlikteliği","Eski ve büyük üniversiteleri","İşlek limanı ve serbest bölgesi"]'::jsonb, '["Its industry","The coexistence of different faiths and cultures","Its universities","Its port"]'::jsonb, '["Its long-established heavy industry and steel making","The coexistence of different faiths and cultures","Its old and large universities","Its busy port and free zone"]'::jsonb),
    ('e17e3c38-4e72-4ba2-b191-ca3b4bf0bc93'::uuid, 3, '["Tek kişi","İkili","Sırayla","El ele halka veya sıra hâlinde"]'::jsonb, '["Tek başına, kollar iki yana açık","Karşılıklı çiftler hâlinde","Oturarak, kaşık eşliğinde","El ele halka veya sıra hâlinde"]'::jsonb, '["Solo","In pairs","In turns","Hand in hand in a circle or line"]'::jsonb, '["Alone, with both arms spread out to the sides","In couples facing each other","Seated, to the beat of spoons","Hand in hand in a circle or line"]'::jsonb),
    ('e31a0d42-45e2-4cfc-bed1-29d6d0c0d7cd'::uuid, 1, '["Dondurulmuş üretimi","Ürünün üretimden tüketime soğuk kalması","Buzdolabı markasını","Sıcak taşımayı"]'::jsonb, '["Ürünün üretimden tüketime kadar izlenebilmesi","Ürünün üretimden tüketime soğuk kalması","Ürünün depodan mağazaya hızlı taşınması","Ürünün tek kullanımlık ambalajla satılması"]'::jsonb, '["Frozen production","Keeping a product cold from production to consumption","A brand of fridge","Transporting it hot"]'::jsonb, '["Being able to trace a product from production to consumption","Keeping a product cold from production to consumption","Moving a product quickly from warehouse to shop","Selling a product in single-use packaging"]'::jsonb),
    ('e4e383dd-8f39-4a98-bc95-c26f353cada6'::uuid, 3, '["Nüfusu artırmak","Yeşil alanı azaltmak","Trafiği artırmak","Sağlıksız yapı stokunu yenilemek"]'::jsonb, '["Tarihî kent dokusunu onarmak","Kent çevresine yeşil kuşak kurmak","Toplu taşıma ağını genişletmek","Sağlıksız yapı stokunu yenilemek"]'::jsonb, '["Increasing the population","Reducing green space","Increasing traffic","Renewing unsafe building stock"]'::jsonb, '["Restoring the historic urban fabric","Creating a green belt around the city","Expanding the public transport network","Renewing unsafe building stock"]'::jsonb),
    ('e7970a93-9b10-4951-8eb8-f50123003209'::uuid, 0, '["Sözleşmeye uygun olmayan ürün","Pahalı ürün","İthal ürün","İkinci el ürün"]'::jsonb, '["Sözleşmeye uygun olmayan ürün","Piyasa değerinden pahalı satılan ürün","Yurt dışından getirilen ürün","Daha önce kullanılmış ürün"]'::jsonb, '["A product not as specified in the contract","An expensive product","An imported product","A second-hand product"]'::jsonb, '["A product not as specified in the contract","A product sold for more than its market value","A product brought in from abroad","A product that has been used before"]'::jsonb),
    ('e888bb1b-db18-42e3-a799-60eb27a374ca'::uuid, 1, '["Uyumak","Şaşırıp beceremez olmak","Dans etmek","Çok yürümek"]'::jsonb, '["Yorgunluktan uyuyakalmak","Şaşırıp beceremez olmak","Sevinçten havalara uçmak","Çok yürüyüp bitkin düşmek"]'::jsonb, null, null),
    ('f1181a9a-25f8-4bda-9c9c-9123012d0748'::uuid, 0, '["Ekonomik hedef ve yatırımları","Nüfus sayımını","Seçimi","Askerliği"]'::jsonb, '["Ekonomik hedef ve yatırımları","Nüfus sayımı ve kayıtlarını","Seçim takvimi ve kurallarını","Askerlik süresi ve koşullarını"]'::jsonb, '["Economic targets and investments","The census","The election","Military service"]'::jsonb, '["Economic targets and investments","The census and its records","The election timetable and rules","The length and terms of military service"]'::jsonb),
    ('f1d52acf-0376-4f5f-981a-33f9a25093f8'::uuid, 3, '["Üretimi azaltmak","İthalatı artırmak","Fiyatı yükseltmek","Üretimi sürdürülebilir kılmak"]'::jsonb, '["Sanayi ürünleri ihracatını artırmak","Kent nüfusunu dengelemek","Orman alanlarını genişletmek","Üretimi sürdürülebilir kılmak"]'::jsonb, '["Reducing production","Increasing imports","Raising prices","Making production sustainable"]'::jsonb, '["Increasing exports of industrial goods","Balancing the urban population","Expanding forest areas","Making production sustainable"]'::jsonb),
    ('f3b88c09-78e6-4c05-a9d7-b1ba800a8ca5'::uuid, 2, '["Turist vizesi","Öğrenci izni","Zulümden kaçana sığınma hakkı","Çalışma izni"]'::jsonb, '["Suçlanana adil yargılanma hakkı","Çalışana sendika kurma hakkı","Zulümden kaçana sığınma hakkı","Yurttaşa dilekçe verme hakkı"]'::jsonb, '["A tourist visa","A student permit","Refuge for someone fleeing persecution","A work permit"]'::jsonb, '["A fair trial for someone accused of a crime","The right of workers to form a union","Refuge for someone fleeing persecution","The right of citizens to petition"]'::jsonb),
    ('f4c0d532-30c4-4a94-8ffb-ab9ccb5514e1'::uuid, 2, '["Uzunluk","Hız","Değerli taş ve altın","Basınç"]'::jsonb, '["Uzunluk ve derinlik","Rüzgâr ve akıntı hızı","Değerli taş ve altın","Hava ve su basıncı"]'::jsonb, '["Length","Speed","Precious stones and gold","Pressure"]'::jsonb, '["Length and depth","Wind speed and current speed","Precious stones and gold","Air and water pressure"]'::jsonb),
    ('fd9ce03f-a23f-4858-b02f-54c782ca2da8'::uuid, 1, '["Renk vermek","Pişme süresini kısaltmak","Ağırlaştırmak","Tuzlamak"]'::jsonb, '["Rengini koyulaştırmak","Pişme süresini kısaltmak","Protein miktarını artırmak","Tuzunu dengelemek"]'::jsonb, '["To add colour","To shorten the cooking time","To make them heavier","To salt them"]'::jsonb, '["To darken their colour","To shorten the cooking time","To raise the protein content","To balance the salt"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _ipucu_sik);
begin
  -- Yalnız 851'in bıraktığı hâldeki satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _ipucu_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru and q.aktif = false and q.kategori = 'genel_kultur';
  if v_n <> v_beklenen then
    raise exception '940: % sorudan % tanesi beklenen eski hâlde (pasif, genel_kultur, eski şıklar)', v_beklenen, v_n;
  end if;

  -- Yeni şık dizileri: 4 şık, doğru şık metni aynı yerde
  select count(*) into v_n from _ipucu_sik s
   where jsonb_array_length(s.yeni_tr) <> 4 or s.yeni_tr -> s.dogru::int is distinct from s.eski_tr -> s.dogru::int
      or (s.yeni_en is not null and (jsonb_array_length(s.yeni_en) <> 4 or s.yeni_en -> s.dogru::int is distinct from s.eski_en -> s.dogru::int));
  if v_n > 0 then
    raise exception '940: % satırda yeni şık dizisi bozuk (4 şık / doğru şık aynı değil)', v_n;
  end if;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         aktif = true
    from _ipucu_sik s
   where q.id = s.id;

  -- EN çeviri: aynı indekslerle; eski çeviri beklenen hâlde değilse dur (yeni TR + eski EN birlikte kalmasın)
  update public.question_translations t
     set secenekler = s.yeni_en
    from _ipucu_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _ipucu_sik where yeni_en is not null) then
    raise exception '940: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _ipucu_sik where yeni_en is not null);
  end if;
  -- EN'i yazılmayan soruda çeviri satırı olmamalı
  select count(*) into v_n from public.question_translations t join _ipucu_sik s on s.id = t.question_id where s.yeni_en is null;
  if v_n > 0 then
    raise exception '940: % soruda çeviri satırı var ama yeni çeviri şıkkı yok', v_n;
  end if;

  -- Sonuç: sik_ipucu_jev kalmamalı, rekabetçi havuzdan düşüren kural işareti olmamalı
  select count(*) into v_n from public.questions q join _ipucu_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception '940: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
