-- ============================================================
-- 002 — Şık ipucu düzeltmesi, parti 6 (8 Eki 2026, Claude API)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide işaretli kolay/orta
-- (zorluk 1–3) sorulardan 31 tanesinin YANLIŞ şıkları Claude API (claude-sonnet-5-5) ile yeniden yazıldı;
-- soru metni, doğru cevap ve doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar dört kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0.75), Jev tek doğru cevap kontrolü ve
-- yanlış şık başına ayrı Claude hakem çağrısı (kesin_yanlis). Geçemeyen sorulara dokunulmadı, işaretli kalır.
-- EN çeviri: aynı indekslerle güncellenir (EN çevirisi olmayan soruda yalnız TR). Üretici: araclar/soru-temizlik/sik-ipucu-api.mjs --tam
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 6   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('49c6af2b-e8a8-4ad2-8332-25601890cace'::uuid, 1, '["Veri miktarını","Verinin gidiş-dönüş süresini","Kablo kalınlığını","Cihaz sayısını"]'::jsonb, '["Verinin saniyedeki aktarım hızını","Verinin gidiş-dönüş süresini","Verinin sıkıştırma oranını","Verinin depolama süresini"]'::jsonb, '["The amount of data","The round-trip time of data","Cable thickness","The number of devices"]'::jsonb, '["The data transfer rate per second","The round-trip time of data","The compression ratio of data","The storage duration of data"]'::jsonb),
    ('d7a7ccdb-9cb8-4d9c-ae14-49c42fc1e1ee'::uuid, 3, '["Olga Korbut","Nellie Kim","Ludmilla Turischeva","Nadia Comaneci"]'::jsonb, '["Věra Čáslavská","Larisa Latynina","Svetlana Khorkina","Nadia Comaneci"]'::jsonb, '["Olga Korbut","Nellie Kim","Ludmilla Turischeva","Nadia Comaneci"]'::jsonb, '["Věra Čáslavská","Larisa Latynina","Svetlana Khorkina","Nadia Comaneci"]'::jsonb),
    ('f31fc661-e519-436e-b5ec-5dc47415f9c1'::uuid, 3, '["Bilet saymaya","Ödül vermeye","Salon açmaya","Gelişimi evrelere ayırmaya"]'::jsonb, '["Yönetmenleri sıralamaya","Filmleri türlerine göre raflamaya","Yapım bütçelerini karşılaştırmaya","Gelişimi evrelere ayırmaya"]'::jsonb, '["Counting tickets","Awarding prizes","Opening cinemas","Dividing the development into phases"]'::jsonb, '["Ranking the directors","Shelving films by genre","Comparing production budgets","Dividing the development into phases"]'::jsonb),
    ('79b1bc66-ff72-4221-94fa-c962dae1f0bf'::uuid, 3, '["Hızlı kodu","Küçük dosyayı","Ucuz donanımı","Arıza durumunda çalışmayı sürdürmeyi"]'::jsonb, '["Verilerin gizli kalmasını","Kodun daha hızlı derlenmesini","Donanım maliyetinin düşmesini","Arıza durumunda çalışmayı sürdürmeyi"]'::jsonb, '["Fast code","A small file","Cheap hardware","Continued operation when something fails"]'::jsonb, '["Keeping data confidential","Faster compilation of code","Lower hardware costs","Continued operation when something fails"]'::jsonb),
    ('53773e97-13e9-4146-8720-dd6a7968ee1d'::uuid, 2, '["Çözeltinin rengini","Çözeltinin sıcaklığını","Birim çözeltideki çözünen miktarını","Kabın hacmini"]'::jsonb, '["Çözeltideki çözücünün kaynama noktasını","Çözeltinin yoğunluğunun sıcaklıkla değişimini","Birim çözeltideki çözünen miktarını","Çözünen maddenin molekül kütlesini"]'::jsonb, '["The colour of the solution","The temperature of the solution","The amount of solute per unit of solution","The volume of the container"]'::jsonb, '["The boiling point of the solvent in the solution","The change of the solution''s density with temperature","The amount of solute per unit of solution","The molecular mass of the dissolved substance"]'::jsonb),
    ('f6349bb6-ab62-4414-bb6a-6dcaae115033'::uuid, 0, '["Dağ yamacından sıcak ve kuru inmesi","Soğuk ve nemli olması","Yağış getirmesi","Kutuplardan gelmesi"]'::jsonb, '["Dağ yamacından sıcak ve kuru inmesi","Deniz üzerinden ılık ve nemli esmesi","Çöl ovasından toz taşıyarak esmesi","Mevsimlik yön değiştirerek esmesi"]'::jsonb, '["Coming down a mountain slope warm and dry","Being cold and damp","Bringing rain","Coming from the poles"]'::jsonb, '["Coming down a mountain slope warm and dry","Blowing mild and humid across the sea","Blowing across a desert plain carrying dust","Changing direction with the seasons"]'::jsonb),
    ('4c1518d3-975b-4fba-ab4b-1bbc26a0542e'::uuid, 3, '["Kara sınırını","Hava sahasını","Ticareti","Boğazların yönetimini"]'::jsonb, '["Sömürge topraklarının paylaşımını","Savaş tazminatlarının ödenmesini","Azınlıkların haklarını","Boğazların yönetimini"]'::jsonb, '["Land borders","Airspace","Trade","Administration of the Straits"]'::jsonb, '["Division of colonial territories","Payment of war reparations","Rights of minorities","Administration of the Straits"]'::jsonb),
    ('1a67fc51-6a9e-4e5d-a821-213094b0c5bd'::uuid, 1, '["Süsleme","Kubbe yükünü zemine aktarmak","Aydınlatma","Havalandırma"]'::jsonb, '["Kubbe geçişini üçgen yüzeylerle sağlamak","Kubbe yükünü zemine aktarmak","Avlu girişini gölgeli bir revakla çevirmek","Minare gövdesini yan duvara bağlamak"]'::jsonb, '["Decoration","Transferring the dome''s load to the ground","Lighting","Ventilation"]'::jsonb, '["Providing the dome transition with triangular surfaces","Transferring the dome''s load to the ground","Surrounding the courtyard entrance with a shaded portico","Connecting the minaret shaft to the side wall"]'::jsonb),
    ('d9b5fd5e-ad40-4b7f-80fc-ed16579b001c'::uuid, 1, '["Conan Doyle","Agatha Christie","Simenon","Highsmith"]'::jsonb, '["Conan Doyle","Agatha Christie","Dorothy Sayers","Raymond Chandler"]'::jsonb, '["Conan Doyle","Agatha Christie","Simenon","Highsmith"]'::jsonb, '["Conan Doyle","Agatha Christie","Dorothy Sayers","Raymond Chandler"]'::jsonb),
    ('56e6a987-9da6-44f2-b818-776a9847cdc3'::uuid, 3, '["Bütçe hazırlamak","Bilet satmak","Ses kaydetmek","Çekimleri önceden çizerek planlamak"]'::jsonb, '["Oyuncuları önceden seçerek kadroyu belirlemek","Çekim mekanlarını önceden izinle kiralamak","Müzikleri önceden besteleyerek kaydetmek","Çekimleri önceden çizerek planlamak"]'::jsonb, '["Preparing the budget","Selling tickets","Recording sound","Planning the shots by drawing them in advance"]'::jsonb, '["Choosing the cast in advance to form the ensemble","Renting filming locations in advance with permits","Composing and recording the music in advance","Planning the shots by drawing them in advance"]'::jsonb),
    ('a6d57331-71b6-4e6b-94c4-4913460d382c'::uuid, 1, '["Kalite artışı","Önden veri tutup kesintiyi önlemeyi","Dosya küçültme","Ses eşitleme"]'::jsonb, '["Görüntüyü yüksek çözünürlüğe yükseltmeyi","Önden veri tutup kesintiyi önlemeyi","Verileri şifreleyerek korumayı","Yayını birden fazla cihaza kopyalamayı"]'::jsonb, '["Higher quality","Holding data ahead to prevent interruption","Shrinking the file","Syncing the audio"]'::jsonb, '["Upscaling the picture to a higher resolution","Holding data ahead to prevent interruption","Protecting the data by encrypting it","Copying the stream to multiple devices"]'::jsonb),
    ('2416da4a-05de-4d31-9c57-be0c5dfcc33d'::uuid, 2, '["Tarımsal","İklimsel","Jeopolitik ve ticari","Madensel"]'::jsonb, '["Tarımsal ve hayvancılık","İklimsel ve bitki örtüsüne dair","Jeopolitik ve ticari","Jeotermal ve volkanik"]'::jsonb, '["Agricultural","Climatic","Geopolitical and commercial","Mineral"]'::jsonb, '["Agricultural and livestock-related","Climatic and vegetation-related","Geopolitical and commercial","Geothermal and volcanic"]'::jsonb),
    ('8a53834b-3a68-449e-8de0-8a3533ad8edc'::uuid, 3, '["Denizcilikle","Sanayiyle","Sömürgecilikle","İlk Müslüman Türk devletlerinden olmakla"]'::jsonb, '["Hint Okyanusu''ndaki deniz ticaret ağıyla bilinen bir devlet olmakla","Anadolu''daki ilk Türk beyliklerinden biri olmakla","Orta Asya''da Budist bir Türk devleti olmakla","İlk Müslüman Türk devletlerinden olmakla"]'::jsonb, '["Seafaring","Industry","Colonialism","Being one of the first Muslim Turkic states"]'::jsonb, '["Being a state known for its Indian Ocean maritime trade network","Being one of the first Turkic principalities in Anatolia","Being a Buddhist Turkic state in Central Asia","Being one of the first Muslim Turkic states"]'::jsonb),
    ('310ad36e-5353-4c35-9533-f4fc35dfe530'::uuid, 1, '["Sınırlı bilgi","Her şeyi bilen anlatıcı","Yalnız diyalog","Yalnız betimleme"]'::jsonb, '["Yalnızca bir kahramanın gözünden anlatım","Her şeyi bilen anlatıcı","Okurun hiçbir şey öğrenmemesi","Karakterlerin kendi mektuplarıyla anlatım"]'::jsonb, '["Limited knowledge","A narrator who knows everything","Only dialogue","Only description"]'::jsonb, '["Narration only through one character''s eyes","A narrator who knows everything","The reader learning nothing","Narration through the characters'' own letters"]'::jsonb),
    ('79686e00-80d8-46ad-bea0-3bd201c76831'::uuid, 3, '["Rastgele müzik","Sessizlik","Doğal ses","Karaktere bağlı yinelenen ezgi"]'::jsonb, '["Sahneler arasında geçişi sağlayan ses efekti","Diyalogların arka planda kısılması tekniği","Görüntüyle eş zamanlı çalınan gerçek ses","Karaktere bağlı yinelenen ezgi"]'::jsonb, '["Random music","Silence","Natural sound","A recurring theme tied to a character"]'::jsonb, '["A sound effect that links transitions between scenes","A technique of lowering dialogue in the background","A real sound played in sync with the image","A recurring theme tied to a character"]'::jsonb),
    ('1a27b68f-8244-458e-aff4-760e346e5fa7'::uuid, 0, '["Yeni ortamda dengeyi bozan yabancı tür","Yerli tür","Nesli tükenen tür","Evcil tür"]'::jsonb, '["Yeni ortamda dengeyi bozan yabancı tür","Yalnızca tek bir adada yaşayan, yayılımı sınırlı tür","Besin zincirinde en üst basamakta yer alan tür","Göç yollarında mevsimlik olarak yer değiştiren tür"]'::jsonb, '["A foreign species that upsets the balance in a new environment","A native species","An extinct species","A domesticated species"]'::jsonb, '["A foreign species that upsets the balance in a new environment","A species living on only one island with a limited range","A species at the top level of the food chain","A species that moves seasonally along migration routes"]'::jsonb),
    ('dd953682-b9ca-4fbf-bf92-44da0895a895'::uuid, 3, '["Onaylamak","Yargılamak","Yüceltmek","Dönemin koşullarını anlamaya çalışmak"]'::jsonb, '["Geçmiş olayları bugünün ölçütleriyle değerlendirmek","Tarihsel olaylardan ders çıkarmaya çalışmak","Geçmişteki kişilere hayranlık duymak","Dönemin koşullarını anlamaya çalışmak"]'::jsonb, '["Approving","Judging","Glorifying","Trying to understand the conditions of the period"]'::jsonb, '["Evaluating past events by today''s standards","Trying to draw lessons from historical events","Admiring the people of the past","Trying to understand the conditions of the period"]'::jsonb),
    ('1a388151-84aa-4548-a7bf-c477391c831d'::uuid, 0, '["Yolculuk boyunca dönüşüme","Tek mekânda kalmaya","Savaş sahnelerine","Dans gösterisine"]'::jsonb, '["Yolculuk boyunca dönüşüme","Cinayet soruşturmasının çözülmesine","Mahkeme salonundaki tartışmalara","Zaman atlamalı aşk hikâyesine"]'::jsonb, '["Transformation over the course of a journey","Staying in one place","Battle scenes","A dance show"]'::jsonb, '["Transformation over the course of a journey","Solving a murder investigation","Courtroom debates","A time-jumping love story"]'::jsonb),
    ('4d64bab6-5327-4003-90e4-f3d4c7872c4f'::uuid, 3, '["Toplam enerjiyi","Kuvveti","Kütleyi","Birim zamandaki işi"]'::jsonb, '["Birim yüzeydeki kuvveti","Birim zamandaki hız değişimini","Birim hacimdeki kütleyi","Birim zamandaki işi"]'::jsonb, '["Total energy","Force","Mass","Work done per unit of time"]'::jsonb, '["Force per unit of area","Change in velocity per unit of time","Mass per unit of volume","Work done per unit of time"]'::jsonb),
    ('8d892e4b-b743-4cd4-8d08-a719be3dff50'::uuid, 2, '["Ticaret","Vergi","Yazısız hukuk kuralları","Ordu"]'::jsonb, '["Devlet hazinesi","Askerî birlik düzeni","Yazısız hukuk kuralları","Hanedan soyağacı"]'::jsonb, '["Trade","Tax","Unwritten customary law","Army"]'::jsonb, '["State treasury","Military unit order","Unwritten customary law","Dynastic genealogy"]'::jsonb),
    ('21a397db-d5b9-454e-8816-d4bc294ff845'::uuid, 0, '["Görevleri otomatikleştirmek","Donanım üretmek","Kablo döşemek","Ekran yapmak"]'::jsonb, '["Görevleri otomatikleştirmek","Cihaz sürücüsü yazmak","Veri kablosu test etmek","Ağ trafiğini yönlendirmek"]'::jsonb, '["Automating tasks","Manufacturing hardware","Laying cable","Making screens"]'::jsonb, '["Automating tasks","Writing device drivers","Testing data cables","Routing network traffic"]'::jsonb),
    ('99d689e2-f40e-49e8-8be3-6f89e493e9e3'::uuid, 2, '["Yalnız depolama","Yalnız ses","Grafik ve paralel hesaplama","Yalnız ağ"]'::jsonb, '["Veri depolama ve yedekleme","Ses işleme ve kayıt","Grafik ve paralel hesaplama","Ağ trafiği yönlendirme"]'::jsonb, '["Storage only","Sound only","Graphics and parallel computation","Networking only"]'::jsonb, '["Data storage and backup","Sound processing and recording","Graphics and parallel computation","Network traffic routing"]'::jsonb),
    ('7e47d1ad-a631-413c-bc2f-0315dd86e7f3'::uuid, 3, '["Ağ hızı","Renk düzeltme","Ses kaydı","Kimlik doğrulama ve bütünlük"]'::jsonb, '["Veri sıkıştırma ve hız","Gizlilik ve anonimlik","Yedekleme ve kurtarma","Kimlik doğrulama ve bütünlük"]'::jsonb, '["Network speed","Colour correction","Sound recording","Authentication and integrity"]'::jsonb, '["Data compression and speed","Secrecy and anonymity","Backup and recovery","Authentication and integrity"]'::jsonb),
    ('9b54127f-e59c-45a7-b083-9e989305d4e4'::uuid, 1, '["Sıcaklık eşitliği","Basınç farkı","Nem","Yükseklik yok"]'::jsonb, '["Bulut miktarı","Basınç farkı","Nem oranı","Yağış miktarı"]'::jsonb, '["Equal temperature","A pressure difference","Humidity","No effect from altitude"]'::jsonb, '["Cloud amount","A pressure difference","Humidity level","Amount of precipitation"]'::jsonb),
    ('29a043b5-585a-42a3-bfc9-a432078df38d'::uuid, 0, '["İnsan davranışını manipüle etmeye","Şifre kırma yazılımına","Donanım sökmeye","Ağ kablosuna"]'::jsonb, '["İnsan davranışını manipüle etmeye","Yazılım güvenlik açığı sömürmeye","Sunucu sistemini aşırı yüklemeye","Şifreli trafiği çözmeye"]'::jsonb, '["Manipulating human behaviour","Password-cracking software","Dismantling hardware","The network cable"]'::jsonb, '["Manipulating human behaviour","Exploiting software vulnerabilities","Overloading the server system","Decrypting encrypted traffic"]'::jsonb),
    ('6ee4556d-7194-41bf-a6d5-b5ae83b1bca6'::uuid, 1, '["Dağ zirvelerinde","Akarsu taşkın ovalarında","Çöl ortasında","Buzul üstünde"]'::jsonb, '["Dağ yamaçlarında","Akarsu taşkın ovalarında","Kıyı kumullarında","Volkanik koniler üzerinde"]'::jsonb, '["On mountain summits","On river floodplains","In the middle of the desert","On top of a glacier"]'::jsonb, '["On mountain slopes","On river floodplains","On coastal sand dunes","On volcanic cones"]'::jsonb),
    ('3856cf67-a99b-4fd7-a768-534a7cc2600e'::uuid, 2, '["Pallas","Juno","Ceres","Vesta"]'::jsonb, '["Hygiea","Astraea","Ceres","Eros"]'::jsonb, '["Pallas","Juno","Ceres","Vesta"]'::jsonb, '["Hygiea","Astraea","Ceres","Eros"]'::jsonb),
    ('50980c01-29f9-4128-9e63-f0443f77dfae'::uuid, 0, '["Suyun mineralli katmanlardan geçmesine","Deniz suyunun süzülmesine","Buzul erimesine","Yağmurun donmasına"]'::jsonb, '["Suyun mineralli katmanlardan geçmesine","Suyun güneş ışığıyla buharlaşıp yoğuşmasına","Suyun yüzeyde nehir yatağında hızlı akmasına","Suyun yüksek dağlarda kar olarak birikmesine"]'::jsonb, '["Water passing through mineral-rich layers","Seawater being filtered","Glacial melt","Rain freezing"]'::jsonb, '["Water passing through mineral-rich layers","Water evaporating and condensing under sunlight","Water flowing quickly along a surface riverbed","Water accumulating as snow on high mountains"]'::jsonb),
    ('791f452e-f719-4f7d-94d9-7511a28a20fe'::uuid, 2, '["Askerî talim","Ticaret eğitimi","Saray görevlisi yetiştirme","Din eğitimi yalnızca"]'::jsonb, '["Donanma subayı yetiştirme","Vakıf yönetimi eğitimi","Saray görevlisi yetiştirme","Kadı ve müderris yetiştirme"]'::jsonb, '["Military drill","Commercial training","Training palace officials","Only religious education"]'::jsonb, '["Training naval officers","Endowment management training","Training palace officials","Training judges and scholars"]'::jsonb),
    ('75671524-4685-463c-b3b6-4569f5455fda'::uuid, 3, '["Gece yarısı","Öğle güneşi","Sabah 10","Gün doğumu ve batımına yakın ışık"]'::jsonb, '["Alacakaranlık sonrası mavi gökyüzü ışığı","Bulutlu havanın yumuşak yayılmış ışığı","Gün ortasında tepeden gelen sert ışık","Gün doğumu ve batımına yakın ışık"]'::jsonb, '["Midnight","Midday sun","Ten in the morning","The light near sunrise and sunset"]'::jsonb, '["The blue sky light after twilight","The soft diffused light of an overcast sky","The harsh overhead light at midday","The light near sunrise and sunset"]'::jsonb),
    ('356e9be0-b7f2-45f0-9777-1caaf092de21'::uuid, 3, '["Tritone","Najadlar","Barcaccia","Trevi"]'::jsonb, '["Tritone","Najadlar","Barcaccia","Trevi"]'::jsonb, '["Triton Fountain","Fountain of the Naiads","Barcaccia Fountain","Trevi Fountain"]'::jsonb, '["Triton Fountain","Fountain of the Naiads","Barcaccia Fountain","Trevi Fountain"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 6: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 6: yanlış şıklar yeniden yazıldı (002)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 6: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 6: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
