-- ============================================================
-- 422 — Şık ipucu düzeltmesi, parti 3/3 (23 Eyl 2026, Ajan J)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide 100 işaretli
-- kolay/orta (zorluk 1–3) sorunun YANLIŞ şıkları yeniden yazıldı; soru metni, doğru cevap ve
-- doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar üç kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0,8) ve tek doğru cevap kontrolü.
-- Geçen 60 soru yazılır ve işareti kaldırılır → rekabetçi havuza döner; 40 soru üç denemede
-- geçemedi ya da (cevabı ünlü ad/sayı olduğu için) yazılmadı; dokunulmadı, işaretli kalır. EN çeviri: 60 satır aynı indekslerle güncellenir.
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 3   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('3cd2c88a-dd90-4065-8f99-21fd38d2ba68'::uuid, 2, '["Nice","Marsilya","Paris","Lyon"]'::jsonb, '["Roma","Madrid","Paris","Brüksel"]'::jsonb, '["Nice","Marseille","Paris","Lyon"]'::jsonb, '["Rome","Madrid","Paris","Brussels"]'::jsonb),
    ('07ef6ff0-d7b3-4405-a3f2-f2cafa160133'::uuid, 2, '["Ürün satışını artırıp yaymak","Şirketi tanıtıp yüceltmek","Toplum yararına bilgilendirmek","Etkinlik bileti satmak"]'::jsonb, '["Seçmeni bir partiye yöneltmek","Markaya bağlılık oluşturmak","Toplum yararına bilgilendirmek","Dizinin reytingini artırmak"]'::jsonb, '["Selling a product","Promoting a company","Informing for the public good","Selling tickets"]'::jsonb, '["Steering voters towards a party","Building brand loyalty","Informing for the public good","Boosting a series'' ratings"]'::jsonb),
    ('b9f88581-f937-49bc-97b5-c3a14b68f11d'::uuid, 1, '["Kesin nota","Rastlantıya","Tek tempoya","Tek çalgıya"]'::jsonb, '["Tekrara","Rastlantıya","Elektronik sese","Halk ezgisine"]'::jsonb, '["Exact notation","Chance","A single tempo","A single instrument"]'::jsonb, '["Repetition","Chance","Electronic sound","Folk melody"]'::jsonb),
    ('32e46a0a-c0ed-44c5-93da-65c97f8c81dc'::uuid, 3, '["Satışı","Eleştiriyi","Üretimi engeller","Sürdürülebilir kaynak sağlar"]'::jsonb, '["Telif hakkı güvencesi sağlar","Sansür muafiyeti sağlar","Eserin satış fiyatını belirler","Sürdürülebilir kaynak sağlar"]'::jsonb, '["Sales","Criticism","Block production","Provide a sustainable source of funding"]'::jsonb, '["Guarantees copyright","Grants exemption from censorship","Sets the work''s sale price","Provide a sustainable source of funding"]'::jsonb),
    ('d1198f0e-13e9-49c2-9166-3cc19f9c9eb2'::uuid, 3, '["Sadece süs","Sadece jenerik","Sadece fon","Anlatıyı ilerletme"]'::jsonb, '["Oyuncu değişimini gizleme","Reklam arasına hazırlama","Jenerik yazılarını taşıma","Anlatıyı ilerletme"]'::jsonb, '["Mere decoration","Only the credits","Only background","Advancing the story"]'::jsonb, '["Hiding cast changes","Leading into an ad break","Carrying the credits","Advancing the story"]'::jsonb),
    ('a8955360-0910-4753-b876-33afe744b581'::uuid, 1, '["Dinlenmek","Lastik değişimi ve bakım","Yemek","Seyirci selamlamak"]'::jsonb, '["Sürücü değişimi ve dinlenme","Lastik değişimi ve bakım","Hakem kontrolü ve tartı","Seyirci selamı ve onur turu"]'::jsonb, '["Resting","Changing tyres and servicing","Eating","Greeting the crowd"]'::jsonb, '["Swapping drivers and resting","Changing tyres and servicing","Stewards'' checks and weighing","Greeting the crowd and a lap of honour"]'::jsonb),
    ('1a88c007-f00f-440d-9241-0792a589c20b'::uuid, 0, '["Alpleri fillerle aşmasıyla","Donanmasıyla","Surlarıyla","Kanunlarıyla"]'::jsonb, '["Alpleri fillerle aşmasıyla","Rubicon''u ordusuyla geçmesiyle","Galya''yı baştan fethetmesiyle","Kartaca''yı yerle bir etmesiyle"]'::jsonb, '["Crossing the Alps with elephants","His fleet","His walls","His laws"]'::jsonb, '["Crossing the Alps with elephants","Crossing the Rubicon with his army","Conquering the whole of Gaul","Razing Carthage to the ground"]'::jsonb),
    ('67336186-3830-4b9d-a72d-1938e33fc826'::uuid, 2, '["Ekranı büyütmek","Pil ömrü","Güvenli ve gizli bağlantı","Ses kalitesi"]'::jsonb, '["Hızlı ve kesintisiz bağlantı","Ücretsiz ve sınırsız bağlantı","Güvenli ve gizli bağlantı","Kablosuz ve uzun menzilli bağlantı"]'::jsonb, '["Enlarging the screen","Battery life","A secure and private connection","Sound quality"]'::jsonb, '["A fast and uninterrupted connection","A free and unlimited connection","A secure and private connection","A wireless long-range connection"]'::jsonb),
    ('e24daffa-965d-4daa-9acc-83cd40c4d411'::uuid, 0, '["Emisyonun azalması","Trafiğin artması","Gürültünün artması","Enerji tüketiminin artması"]'::jsonb, '["Emisyonun azalması","Yağışın artması","Yeraltı suyunun artması","Orman alanının genişlemesi"]'::jsonb, '["Lower emissions","More traffic","More noise","More energy use"]'::jsonb, '["Lower emissions","More rainfall","Higher groundwater","Forests expanding"]'::jsonb),
    ('4fbf9145-07ff-4952-9b1c-96202b1dce2d'::uuid, 3, '["Sayfa sayısını","Bölüm başlığını","Yayınevini","Olayın kimin gözünden anlatıldığını"]'::jsonb, '["Olayın hangi zamanda geçtiğini","Olayın hangi mekânda yaşandığını","Olayın hangi sırayla aktarıldığını","Olayın kimin gözünden anlatıldığını"]'::jsonb, '["The number of pages","The chapter title","The publisher","Whose eyes the story is told through"]'::jsonb, '["When the story takes place","Where the events happen","In what order the events are told","Whose eyes the story is told through"]'::jsonb),
    ('c29f755a-a003-4939-8478-dec1bc92e347'::uuid, 2, '["Yalnız biçimi","Yalnız ritmi","Müzik dışı bir öyküyü","Yalnız armoniyi"]'::jsonb, '["Salt müziksel biçim ve yapıyı","Dansın ritmik kalıbını","Müzik dışı bir öyküyü","Şarkı sözünün anlamını"]'::jsonb, '["Form alone","Rhythm alone","A story outside the music","Harmony alone"]'::jsonb, '["Pure musical form and structure","The rhythmic pattern of a dance","A story outside the music","The meaning of song lyrics"]'::jsonb),
    ('bd00c994-2990-4d5a-94da-afc5f0d16a56'::uuid, 3, '["Öğlen","Gece yarısı","Sabah erken","Gün doğumu ve batımı çevresi"]'::jsonb, '["Güneşin tepede olduğu öğle saati","Gün batımından sonraki mavi saat","Ay ışığının en güçlü olduğu gece","Gün doğumu ve batımı çevresi"]'::jsonb, '["Midday","Midnight","Early morning","Around sunrise and sunset"]'::jsonb, '["Midday, when the sun is highest","The blue hour after sunset","The night when moonlight is strongest","Around sunrise and sunset"]'::jsonb),
    ('68539bd2-3ab7-4ac4-9816-987a7a1726fe'::uuid, 2, '["Yalnız senaryoyla","Yalnız oyuncuyla","Görüntü, ses ve mekân bütünlüğüyle","Yalnız afişle"]'::jsonb, '["Oyuncu kadrosu ve yıldız gücüyle","Bütçe, takvim ve yapım planıyla","Görüntü, ses ve mekân bütünlüğüyle","Afiş, fragman ve tanıtımla"]'::jsonb, '["By the screenplay alone","By the actors alone","By image, sound and setting together","By the poster alone"]'::jsonb, '["By the cast and star power","By budget, schedule and production plan","By image, sound and setting together","By poster, trailer and promotion"]'::jsonb),
    ('debccd72-1abd-4d7a-9668-068c60268bb3'::uuid, 2, '["Yalnız hızı","Yalnız mesafeyi","Teknik öğeler ve sanatsal sunum","Yalnız süreyi"]'::jsonb, '["Bitiş süresi ve atlama yüksekliği","Kat edilen mesafe ve hız","Teknik öğeler ve sanatsal sunum","Buz yüzeyi ve pist ölçüsü"]'::jsonb, '["Speed alone","Distance alone","Technical elements and artistic presentation","Time alone"]'::jsonb, '["Finishing time and jump height","Distance covered and speed","Technical elements and artistic presentation","Ice surface and rink size"]'::jsonb),
    ('f9d72ff9-874f-4641-a3ac-50523d19acd4'::uuid, 0, '["Doğu güney ve batı","Yalnız batı","Yalnız doğu","Yalnız güney"]'::jsonb, '["Doğu güney ve batı","Doğu batı ve kuzey","Güney batı ve Irak","Doğu Irak ve Filistin"]'::jsonb, '["East, south and west","Only the west","Only the east","Only the south"]'::jsonb, '["East, south and west","East, west and north","South, west and Iraq","East, Iraq and Palestine"]'::jsonb),
    ('328cae26-d4eb-4356-a7dc-25935b22746b'::uuid, 1, '["Tijuana","Meksiko","Cancún","Guadalajara"]'::jsonb, '["Bogota","Meksiko","Lima","Havana"]'::jsonb, '["Tijuana","Mexico City","Cancún","Guadalajara"]'::jsonb, '["Bogotá","Mexico City","Lima","Havana"]'::jsonb),
    ('7e115937-6c7a-485e-b2d3-0fb3e205a615'::uuid, 3, '["Konu seçimini","Yayın biçimini","Sayfa sayısını","Yazarın kendine özgü anlatım biçimini"]'::jsonb, '["Yazarın eserinde işlediği ana konuyu","Yazarın eserini yayımladığı türü","Yazarın hayatını anlatan eseri","Yazarın kendine özgü anlatım biçimini"]'::jsonb, '["The choice of subject","The form of publication","The number of pages","A writer''s distinctive way of expression"]'::jsonb, '["The main theme the author treats","The genre in which the author publishes","A work telling the author''s life","A writer''s distinctive way of expression"]'::jsonb),
    ('72c9909b-2d13-489d-b6a3-467fec1f2ea2'::uuid, 0, '["İddianın kanıtla sınanmasını","Haberi yaymayı","Yorum eklemeyi","Metni kısaltmayı"]'::jsonb, '["İddianın kanıtla sınanmasını","Haberin okura en hızlı ulaşmasını","Metnin yazım kurallarına uymasını","Yorumun haberden ayrılmasını"]'::jsonb, '["Testing a claim against evidence","Spreading the story","Adding commentary","Shortening the text"]'::jsonb, '["Testing a claim against evidence","The story reaching readers fastest","The text following spelling rules","Keeping comment separate from news"]'::jsonb),
    ('da1d6b40-7f15-4762-b94d-bbee3441788d'::uuid, 0, '["Ezgi ve icra üslubunu belirlemesi","Nota sayısını","Tempoyu yalnızca","Çalgı fiyatını"]'::jsonb, '["Ezgi ve icra üslubunu belirlemesi","Telif ve lisans hakkını belirlemesi","Sanatçının ücretini belirlemesi","Konser takvimini belirlemesi"]'::jsonb, '["It determines the melody and performing style","The number of notes","The tempo alone","The price of the instrument"]'::jsonb, '["It determines the melody and performing style","It determines copyright and licensing","It determines the performer''s fee","It determines the concert schedule"]'::jsonb),
    ('fc09a085-2f9d-4580-9de1-e0c4b0e197fc'::uuid, 2, '["Barok usta","Gotik mimar","Rönesans insanı","Modern tasarımcı"]'::jsonb, '["Aydınlanma filozofu","Romantik deha","Rönesans insanı","Maniyerist usta"]'::jsonb, '["A Baroque master","A Gothic architect","A Renaissance man","A modern designer"]'::jsonb, '["An Enlightenment philosopher","A Romantic genius","A Renaissance man","A Mannerist master"]'::jsonb),
    ('e277b968-af01-4a0b-b4d0-845619723839'::uuid, 1, '["Bütçeyi","Özgün belgeyi yıpranmadan","Personeli","Binayı"]'::jsonb, '["Arşiv binasını yangından","Özgün belgeyi yıpranmadan","Belgenin telif hakkını","Belgenin gizliliğini sızıntıdan"]'::jsonb, '["The budget","The original document from wear","The staff","The building"]'::jsonb, '["The archive building from fire","The original document from wear","The document''s copyright","The document''s confidentiality from leaks"]'::jsonb),
    ('4a752d40-3102-4abb-8e1c-4fbbd62dfd82'::uuid, 0, '["Hizmet sunan bilgisayar","Yalnız klavye","Yalnız yazıcı","Yalnız monitör"]'::jsonb, '["Hizmet sunan bilgisayar","Paketleri yönlendiren cihaz","Kullanıcının çalıştığı istemci","Veriyi saklayan sabit disk"]'::jsonb, '["A computer that provides services","Only a keyboard","Only a printer","Only a monitor"]'::jsonb, '["A computer that provides services","A device that routes packets","The client a user works on","A hard disk that stores data"]'::jsonb),
    ('5773d6ca-1036-4475-a598-d6cb19e0729d'::uuid, 2, '["Orkestra ile","Piyano ile","Çalgısız","Elektronik ile"]'::jsonb, '["Orkestra eşliğinde","Doğaçlamayla","Çalgısız","Fısıltıyla"]'::jsonb, '["With an orchestra","With a piano","Without instruments","With electronics"]'::jsonb, '["With orchestral accompaniment","Improvised","Without instruments","Whispered"]'::jsonb),
    ('242dd6a8-0dda-45e3-a2c3-5073b95a836f'::uuid, 0, '["Hareket rahatlığı ve görünürlüğü","Yalnız modayı","Yalnız maliyeti","Yalnız rengi"]'::jsonb, '["Hareket rahatlığı ve görünürlüğü","Moda trendi ve marka değerini","Satış fiyatı ve kâr payını","Tarihî orijinallik ve el dikişini"]'::jsonb, '["Freedom of movement and visibility","Only fashion","Only cost","Only colour"]'::jsonb, '["Freedom of movement and visibility","Fashion trends and brand value","Retail price and profit margin","Historical authenticity and hand stitching"]'::jsonb),
    ('e9bf1b43-e552-4680-836d-c1202e04421b'::uuid, 1, '["Roma ve Pers","Yunan şehir devletleri ve Persler","Mısır ve Pers","Hitit ve Pers"]'::jsonb, '["Roma Cumhuriyeti ve Kartacalılar","Yunan şehir devletleri ve Persler","Atina ve Sparta şehir devletleri","Mısır Krallığı ve Hititler"]'::jsonb, '["Rome and Persia","The Greek city-states and the Persians","Egypt and Persia","The Hittites and Persia"]'::jsonb, '["The Roman Republic and the Carthaginians","The Greek city-states and the Persians","Athens and Sparta","Egypt and the Hittites"]'::jsonb),
    ('5b8bfe2c-9a81-4730-99d2-a450f07f65d2'::uuid, 1, '["Elle kurulması","Kendi kendine yayılması","Zararsız olması","Yalnız yazıcıyı etkilemesi"]'::jsonb, '["Zararsız görünüp aldatması","Kendi kendine yayılması","Dosyaları şifrelemesi","Reklam göstermesi"]'::jsonb, '["Being installed by hand","Spreading by itself","Being harmless","Only affecting printers"]'::jsonb, '["Posing as something harmless","Spreading by itself","Encrypting files","Showing adverts"]'::jsonb),
    ('71dd23f8-abe9-4db6-957e-e605c326429c'::uuid, 2, '["Markayı","Boyutu","Artı kutbu","Ağırlığı"]'::jsonb, '["Şarj edilebilirliği","Eksi kutbu","Artı kutbu","Voltaj değerini"]'::jsonb, '["The brand","The size","The positive terminal","The weight"]'::jsonb, '["That it is rechargeable","The negative terminal","The positive terminal","The voltage"]'::jsonb),
    ('990ede4a-0c1b-49b1-b2fc-d738fc982f40'::uuid, 1, '["Seul","Tokyo","Kyoto","Osaka"]'::jsonb, '["Seul","Tokyo","Pekin","Taipei"]'::jsonb, '["Seoul","Tokyo","Kyoto","Osaka"]'::jsonb, '["Seoul","Tokyo","Beijing","Taipei"]'::jsonb),
    ('05a49262-66bf-4d20-9188-15b0e5975267'::uuid, 1, '["Yalnız sürücüde","Tüm koltuklarda","Yalnız ön koltukta","Yalnız arkada"]'::jsonb, '["Ön koltuklarda","Tüm koltuklarda","Sürücü koltuğunda","Çocuk koltuklarında"]'::jsonb, '["Only the driver''s","All seats","Only the front seat","Only the back"]'::jsonb, '["In the front seats","All seats","In the driver''s seat","In child seats"]'::jsonb),
    ('2673cc3b-31bd-4f8a-9b87-dd4136462980'::uuid, 0, '["Ses ve çalgı topluluğu","Yalnız piyano","Yalnız bando","Yalnız yaylı"]'::jsonb, '["Ses ve çalgı topluluğu","Yaylı dörtlü topluluğu","Nefesli bando topluluğu","Solo piyano ve orkestra"]'::jsonb, '["Voices and instruments","Piano alone","A brass band alone","Strings alone"]'::jsonb, '["Voices and instruments","A string quartet","A wind band","Solo piano and orchestra"]'::jsonb),
    ('7c1f43c0-f5fc-46ee-b31b-f8570ceef0ef'::uuid, 3, '["Bina cephesini","Mobilyayı","Afişi","Açık alan ve yeşil düzenlemeleri"]'::jsonb, '["İç mekân ve mobilya düzenlerini","Yol ve köprü projelerini","Kentin imar ve yoğunluk planını","Açık alan ve yeşil düzenlemeleri"]'::jsonb, '["A building façade","Furniture","A poster","Open spaces and green settings"]'::jsonb, '["Interiors and furniture layouts","Road and bridge projects","A city''s zoning and density plan","Open spaces and green settings"]'::jsonb),
    ('1f64a3de-5ad2-4e92-a280-670c97fc9f87'::uuid, 3, '["Yalnız diyalog","Yalnız süre","Yalnız afiş","Işık, ses ve mekân birlikte"]'::jsonb, '["Bütçe, takvim ve yapım birlikte","Afiş, fragman ve tanıtım birlikte","Kurgu süresi ve gişe birlikte","Işık, ses ve mekân birlikte"]'::jsonb, '["Only by dialogue","Only by duration","Only by the poster","By light, sound and setting together"]'::jsonb, '["Budget, schedule and production together","Poster, trailer and publicity together","Running time and box office together","By light, sound and setting together"]'::jsonb),
    ('4f080dd5-e436-46f5-a78d-04b4a0e97083'::uuid, 1, '["Gelenek","Akıl ve bilim","Otorite","Mistisizm"]'::jsonb, '["Gelenek ve otorite","Akıl ve bilim","Sanat ve estetik","İnanç ve vahiy"]'::jsonb, '["Tradition","Reason and science","Authority","Mysticism"]'::jsonb, '["Tradition and authority","Reason and science","Art and aesthetics","Faith and revelation"]'::jsonb),
    ('276388ca-2956-4316-83b7-586f41b97b96'::uuid, 3, '["Daha ağır olması","Daha büyük olması","Daha gürültülü olması","Daha hızlı olması"]'::jsonb, '["Daha ucuz olması","Daha büyük kapasiteli olması","Daha kolay onarılması","Daha hızlı olması"]'::jsonb, '["Being heavier","Being larger","Being noisier","Being faster"]'::jsonb, '["Being cheaper","Having greater capacity","Being easier to repair","Being faster"]'::jsonb),
    ('b06d174d-5c3c-4ec8-80f8-e88ce1f1e4d2'::uuid, 0, '["Londra","Birmingham","Manchester","Liverpool"]'::jsonb, '["Londra","Dublin","Edinburgh","Cardiff"]'::jsonb, '["London","Birmingham","Manchester","Liverpool"]'::jsonb, '["London","Dublin","Edinburgh","Cardiff"]'::jsonb),
    ('201e6a79-6c32-4926-9322-a14d7c90bf13'::uuid, 3, '["Fabl","Günlük komik olaylar","Belgesel","Soylu kişilerin acıklı sonu"]'::jsonb, '["Sıradan kişilerin gülünç hâli","Hayvanların öğretici öyküsü","Tanrıların yaratılış öyküsü","Soylu kişilerin acıklı sonu"]'::jsonb, '["The fable","Everyday comic incidents","Documentary","The sorrowful end of noble figures"]'::jsonb, '["The comic plight of ordinary people","Instructive animal stories","The gods'' creation stories","The sorrowful end of noble figures"]'::jsonb),
    ('7a071912-ce6c-4471-8940-7c2dd4276a74'::uuid, 3, '["Sadece fotoğraf","Sadece başlık","Sadece yorum","Ne, nerede, ne zaman"]'::jsonb, '["Serim, düğüm ve çözüm","Olay örgüsü, kişi ve çatışma","Ölçü, uyak ve redif","Ne, nerede, ne zaman"]'::jsonb, '["A photograph alone","A headline alone","Comment alone","What, where and when"]'::jsonb, '["Exposition, complication and resolution","Plot, character and conflict","Metre, rhyme and redif","What, where and when"]'::jsonb),
    ('7962cf24-5426-4655-9c85-91b62f32e924'::uuid, 3, '["Yüksek sesle söylemek","Hızlı çalmak","Nota yazmak","Bir sesi referanssız tanıyabilmek"]'::jsonb, '["Bir ezgiyi kulaktan duyup çalabilmek","İki ses arasındaki aralığı tanımak","Ritmi hiç şaşmadan tutabilmek","Bir sesi referanssız tanıyabilmek"]'::jsonb, '["Singing loudly","Playing fast","Writing notation","Recognising a note without a reference"]'::jsonb, '["Being able to play a tune by ear","Recognising the interval between two notes","Keeping time without ever slipping","Recognising a note without a reference"]'::jsonb),
    ('5b2c44bb-dd48-477c-8eed-cbd7debf7edf'::uuid, 3, '["Sergilemek için","Satmak için","Arşiv için","Hızlı ön çalışma için"]'::jsonb, '["Eserin son kopyası için","Eserin baskı kalıbı için","Eserin restorasyonu için","Hızlı ön çalışma için"]'::jsonb, '["To exhibit","To sell","For the archive","As quick preparatory work"]'::jsonb, '["As the final copy of the work","As a printing plate for the work","For restoring the work","As quick preparatory work"]'::jsonb),
    ('762d9e39-d17a-4aee-abda-19d89651b80d'::uuid, 1, '["Kısaltılmış filmi","Onarılmış görüntü ve sesi","Yeni çekimi","Farklı kadroyu"]'::jsonb, '["Yeniden çekilmiş sahne ve sesi","Onarılmış görüntü ve sesi","Yönetmenin uzatılmış kurgusunu","Dublajlı görüntü ve sesi"]'::jsonb, '["A shortened film","Repaired picture and sound","New footage","A different cast"]'::jsonb, '["Reshot scenes and sound","Repaired picture and sound","The director''s extended cut","A dubbed picture and soundtrack"]'::jsonb),
    ('851e0c3b-cb02-47f7-a087-77dc6099f0f0'::uuid, 1, '["Kas geliştirme","Odaklanma ve baskıyla başa çıkma","Esneklik çalışması","Kilo verme"]'::jsonb, '["Kas gücü ve dayanıklılık geliştirme","Odaklanma ve baskıyla başa çıkma","Esneklik ve hareket açıklığı çalışması","Beslenme ve kilo kontrolü yapma"]'::jsonb, '["Building muscle","Focus and coping with pressure","Flexibility work","Losing weight"]'::jsonb, '["Building muscle strength and endurance","Focus and coping with pressure","Flexibility and range-of-motion work","Nutrition and weight control"]'::jsonb),
    ('1da6da91-a6cd-42b0-90d9-d3ff7a2289f3'::uuid, 2, '["Disk hızını","Ses seviyesini","Görüntüdeki piksel sayısını","Ağ gecikmesini"]'::jsonb, '["Saniyedeki kare sayısını","Ekrandaki renk derinliğini","Görüntüdeki piksel sayısını","Ekranın yenileme hızını"]'::jsonb, '["Disk speed","The volume","The number of pixels in an image","Network latency"]'::jsonb, '["The number of frames per second","The colour depth on screen","The number of pixels in an image","The screen refresh rate"]'::jsonb),
    ('64e4adef-4830-4131-9f57-051d9e2c7ea5'::uuid, 0, '["Ölçü, kafiye ve redif","Kapak","Yazı tipi","Sayfa sayısı"]'::jsonb, '["Ölçü, kafiye ve redif","İmge, mecaz ve benzetme","Tema, konu ve ana fikir","Nazım birimi ve kıta"]'::jsonb, '["Metre, rhyme and redif","The cover","The typeface","The page count"]'::jsonb, '["Metre, rhyme and redif","Imagery, metaphor and simile","Theme, subject and main idea","Stanza form and verse unit"]'::jsonb),
    ('aa49a927-1561-4551-b643-a19e15effc89'::uuid, 1, '["Sesin kesilmesi","Sesin hafifçe titreşerek zenginleşmesi","Tempo artışı","Ton değişimi"]'::jsonb, '["Sesin kısa kesilerek vurgulanması","Sesin hafifçe titreşerek zenginleşmesi","Sesin iki nota arasında kayması","Sesin giderek yükselmesi"]'::jsonb, '["Cutting the sound off","Enriching the note with a slight oscillation","An increase in tempo","A change of key"]'::jsonb, '["Accenting notes by cutting them short","Enriching the note with a slight oscillation","Sliding between two notes","The sound gradually getting louder"]'::jsonb),
    ('09f6db66-8788-4452-b05a-35428ee201eb'::uuid, 0, '["Saniyedeki görüntü sayısını","Kaydın ses kalitesini","Ekran çözünürlüğünü","Filmin toplam süresini"]'::jsonb, '["Saniyedeki görüntü sayısını","Karedeki piksel sayısını","Saniyedeki bit sayısını","Pikseldeki renk sayısını"]'::jsonb, '["The number of images per second","The sound quality","The resolution","The film''s length"]'::jsonb, '["The number of images per second","The number of pixels in a frame","The number of bits per second","The number of colours per pixel"]'::jsonb),
    ('5d08fdc1-3be0-4927-a090-b062da29ca45'::uuid, 0, '["Genelde 6 ile 8","11","15","4"]'::jsonb, '["Genelde 6 ile 8","Genelde 3 ile 4","Genelde 9 ile 10","Genelde 11 ile 13"]'::jsonb, '["Usually 6 to 8","11","15","4"]'::jsonb, '["Usually 6 to 8","Usually 3 to 4","Usually 9 to 10","Usually 11 to 13"]'::jsonb),
    ('0200a1b0-aed3-47c6-8f42-e024372eaae2'::uuid, 3, '["Feodalitenin güçlenmesi","Ticaretin durması","Köylerin büyümesi","İşçi sınıfının doğuşu"]'::jsonb, '["Toprak ağalığının doğuşu","Lonca düzeninin doğuşu","Şövalye sınıfının doğuşu","İşçi sınıfının doğuşu"]'::jsonb, '["The strengthening of feudalism","The halt of trade","The growth of villages","The birth of the working class"]'::jsonb, '["The rise of the landed gentry","The rise of the guild system","The rise of the knightly class","The birth of the working class"]'::jsonb),
    ('6a8bae98-9159-4f52-943a-862968cf4694'::uuid, 1, '["Yalnız sıcaklık","Kütle ve yer çekimi","Yalnız hacim","Yalnız renk"]'::jsonb, '["Sıcaklık ve hava basıncı","Kütle ve yer çekimi","Renk ve yüzey parlaklığı","Hız ve hareket yönü"]'::jsonb, '["Temperature alone","Mass and gravity","Volume alone","Colour alone"]'::jsonb, '["Temperature and air pressure","Mass and gravity","Colour and surface brightness","Speed and direction of motion"]'::jsonb),
    ('7aae9c9f-05e5-4fa6-9859-a81d7ce45da1'::uuid, 0, '["İş ve eğitim olanakları","Temiz hava","Ucuz arazi","Sessizlik"]'::jsonb, '["İş ve eğitim olanakları","Temiz hava ve sessizlik","Ucuz arazi ve konut","Doğal ve tarımsal alanlar"]'::jsonb, '["Work and education","Clean air","Cheap land","Quiet"]'::jsonb, '["Work and education","Clean air and quiet","Cheap land and housing","Natural and farming areas"]'::jsonb),
    ('cccaec8c-a799-4454-b70d-a4eeecb4f75a'::uuid, 1, '["Yalnız dile","Ülkeye özgü anlatı ve üretim koşullarına","Yalnız bütçeye","Yalnız salon sayısına"]'::jsonb, '["Uluslararası ortak yapım ve dağıtım anlaşmalarına","Ülkeye özgü anlatı ve üretim koşullarına","Hollywood tarzı yüksek bütçeli yapım koşullarına","Festival ödülleri ve eleştirmen puanlarına"]'::jsonb, '["Language alone","A country''s distinctive narratives and conditions of production","The budget alone","The number of cinemas alone"]'::jsonb, '["International co-production and distribution deals","A country''s distinctive narratives and conditions of production","Hollywood-style big-budget production","Festival awards and critics'' scores"]'::jsonb),
    ('76f5d165-1e3c-410f-b00b-0b91b7098466'::uuid, 3, '["Geleneği","İnancı","Soyluluğu","Akıl ve bilimi"]'::jsonb, '["Gelenek ve otoriteyi","Sanat ve estetiği","İnanç ve vahyi","Akıl ve bilimi"]'::jsonb, '["Tradition","Faith","Nobility","Reason and science"]'::jsonb, '["Tradition and authority","Art and aesthetics","Faith and revelation","Reason and science"]'::jsonb),
    ('4af370a1-557f-4db7-b5d3-21974f17e7cf'::uuid, 0, '["Bağdat","Basra","Musul","Erbil"]'::jsonb, '["Bağdat","Şam","Tahran","Amman"]'::jsonb, '["Baghdad","Basra","Mosul","Erbil"]'::jsonb, '["Baghdad","Damascus","Tehran","Amman"]'::jsonb),
    ('27f7e270-909e-41b0-b660-3795bf79817a'::uuid, 0, '["Çapraz bulaşmayı önlemek","Yer kazanmak","Renk için","Koku için"]'::jsonb, '["Çapraz bulaşmayı önlemek","Vitamin kaybını önlemek","Nem kaybını önlemek","Donmayı önlemek"]'::jsonb, '["To prevent cross-contamination","To save space","For colour","For smell"]'::jsonb, '["To prevent cross-contamination","To prevent vitamin loss","To prevent moisture loss","To prevent freezing"]'::jsonb),
    ('f17e64f3-890c-4a46-b7d6-139a26ecb0da'::uuid, 2, '["Rengi soldurmayı","Boyutu büyütmeyi","Bakışı belirli noktaya çekmeyi","Dokuyu silmeyi"]'::jsonb, '["Yüzeyde doku etkisi yaratmayı","Uzaklık ve derinlik hissi vermeyi","Bakışı belirli noktaya çekmeyi","Parçalar arasında denge kurmayı"]'::jsonb, '["Fading the colour","Enlarging the size","Drawing the eye to a particular point","Erasing the texture"]'::jsonb, '["Creating a sense of texture","Giving a sense of distance and depth","Drawing the eye to a particular point","Balancing the parts"]'::jsonb),
    ('40cef15f-9121-4452-b180-45d47587591b'::uuid, 2, '["Parlak renkler","Geniş açık mekânlar","Sert gölgeler ve karanlık atmosfer","Yumuşak pastel tonlar"]'::jsonb, '["Parlak renkler ve müzikal numaralar","Geniş çöl manzaraları ve ufuk","Sert gölgeler ve karanlık atmosfer","Pastel tonlar ve simetrik kadraj"]'::jsonb, '["Bright colours","Wide open spaces","Hard shadows and a dark atmosphere","Soft pastel tones"]'::jsonb, '["Bright colours and musical numbers","Wide desert landscapes and horizons","Hard shadows and a dark atmosphere","Pastel tones and symmetrical framing"]'::jsonb),
    ('c3214e83-4eae-4726-b2d3-8b4c14e5e956'::uuid, 0, '["Donanım ve yazılım arasında aracılık","Yalnız dosya saklama","Yalnız ağ kurma","Yalnız ekran çizme"]'::jsonb, '["Donanım ve yazılım arasında aracılık","Kaynak kodu makine diline çevirme","Web sayfalarını görüntüleme","Verileri tablo halinde düzenleme"]'::jsonb, '["Mediating between hardware and software","Storing files only","Networking only","Drawing on screen only"]'::jsonb, '["Mediating between hardware and software","Translating source code into machine code","Displaying web pages","Organising data in tables"]'::jsonb),
    ('05d350fd-0554-4324-b650-6ff8035966a3'::uuid, 3, '["Bol güneş ışığı","Zengin kömür yatağı","Sürekli rüzgâr","Su ve eğim"]'::jsonb, '["Güneş ve açıklık","Kömür ve maden","Rüzgâr ve yükselti","Su ve eğim"]'::jsonb, '["Sunshine","Coal","Wind","Water and a gradient"]'::jsonb, '["Sunshine and open land","Coal and mines","Wind and altitude","Water and a gradient"]'::jsonb),
    ('2a7f0f9d-e7c4-4fde-b225-4c2e392c2acc'::uuid, 2, '["Okuma süresini","Sayfa sayısını","Olay ve anlatım süresi ilişkisini","Diyalog sayısını"]'::jsonb, '["Anlatıcı ve okur arasındaki mesafeyi","Kişi ve mekân arasındaki uyumu","Olay ve anlatım süresi ilişkisini","Bölüm ve sayfa sayısı ilişkisini"]'::jsonb, '["The reading time","The number of pages","The relation between story time and telling time","The number of dialogues"]'::jsonb, '["The distance between narrator and reader","The harmony between character and setting","The relation between story time and telling time","The ratio of chapters to pages"]'::jsonb),
    ('ec19416c-866a-4ec6-82d1-33dead7e38d6'::uuid, 2, '["Anlatıcı sesi","Canlandırmayı","Olaya müdahale etmeden kaydetmeyi","Röportajı"]'::jsonb, '["Olayı anlatıcı sesle yorumlamayı","Olayı oyuncularla yeniden canlandırmayı","Olaya müdahale etmeden kaydetmeyi","Olayı röportajlarla aktarmayı"]'::jsonb, '["Narration","Reenactment","Recording without intervening","The interview"]'::jsonb, '["Interpreting events with a narrator","Re-enacting events with actors","Recording without intervening","Relating events through interviews"]'::jsonb),
    ('3a5037db-33a9-4314-a084-2633db94704a'::uuid, 0, '["Duruş nefes ve odaklanmayı","Yalnız duruşu","Yalnız nefesi","Yalnız meditasyonu"]'::jsonb, '["Duruş nefes ve odaklanmayı","Sürat kuvvet ve dayanıklılığı","Top kontrolü ve pas oyununu","Ritim müzik ve koreografiyi"]'::jsonb, '["Posture, breath and focus","Posture alone","Breath alone","Meditation alone"]'::jsonb, '["Posture, breath and focus","Speed, strength and stamina","Ball control and passing","Rhythm, music and choreography"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 3: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 3: yanlış şıklar yeniden yazıldı (422)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 3: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 3: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
