-- ============================================================
-- 1042 — soru_parti_kolay_04 (stil: docs/SORU_STIL_PROFILI.md): 194 soru · 2026-10-10
--
-- Kategori: edebiyat 23 · genel_kultur 35 · muzik 20 · sanat 30 · sinema 21 · spor 23 · tarih 3 · teknoloji 39
-- Yerel (kapsam='yerel', ulke='TR'): 16 · zorluk 1–5: 0/132/62/0/0
-- İngilizce çeviri: 178 · çevrilmeyen (ceviri_atlanan, kod 'cevrilemez'): 16
--
-- Kalite (araclar/soru-uretim/api-uret.mjs; üretim claude-opus-5-5, hakem claude-sonnet-5-5):
-- biçim + şık denge (TR/EN), havuzla birebir ve anlamca tekrar (aynı cevap + Jaccard ≥ 0,3),
-- cevap soru metninde değil, soru_kural_isaretleri (ağırlık ≥ 2 yok), Jev şık ipucu testi
-- (soru gizli, doğru şıkka p ≤ 0,75), Jev tek doğru, Claude hakem (doğru şık kesin, yanlış
-- şıklar kesin yanlış, yasak tip yok: genel kavram / tanımlama / okuduğunu anlama / mantıkla
-- bulunur; tek olgu, eskimez, EN aynı sırada ve doğal, zorluk tahmini etiketle uyumlu).
--
-- Sıra: sorular doğru şık 0'da eklenir, çeviriler aynı sırayla yazılır, sonunda YALNIZ
-- bu işlemde eklenen satırların şıkları karıştırılır — TR ve EN AYNI permütasyonla
-- (dogru_cevap indeksi ortak olduğu için şart). `created_at >= transaction_timestamp()`
-- koşulu ZORUNLUDUR; onsuz tüm havuz karışır ve oynanan maçlarda indeks kayar.
-- Üretici: node araclar/soru-uretim/uret-migration-parti.mjs --parti 4 --no 1042 --klasor kolay-04 --ad soru_parti_kolay_04 --api
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori, kapsam, ulke, zorluk) values
('İkiz Petronas Kuleleri hangi şehirdedir?', '["Kuala Lumpur","Ho Chi Minh","Singapur","Cakarta"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Sevil Berberi'' operasının bestecisi kimdir?', '["Rossini","Verdi","Puccini","Bellini"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Amadeus'' filminde Mozart''ı kıskanan saray bestecisi kimdir?', '["Salieri","Haydn","Gluck","Clementi"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Uzun boyunlu, badem gözlü portreleriyle tanınan İtalyan ressam kimdir?', '["Modigliani","De Chirico","Boccioni","Morandi"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Londra''daki Trafalgar Meydanı''nın ünlü sütununun tepesinde kimin heykeli durur?', '["Nelson","Wellington","Churchill","Cromwell"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Ünlü anıt mezar Tac Mahal hangi Hindistan şehrindedir?', '["Agra","Delhi","Jaipur","Mumbai"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Endülüs mimarisinin şaheseri Elhamra Sarayı hangi İspanyol şehrindedir?', '["Granada","Sevilla","Kurtuba","Malaga"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Pink Floyd''un ''The Dark Side of the Moon'' kapağında ışık hangi nesneden geçer?', '["Prizma","Mercek","Ayna","Kristal küre"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Gize''deki en büyük piramit hangi firavun için yapılmıştır?', '["Keops","II. Ramses","Tutankamon","Akhenaton"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Wicked'' müzikali hangi ünlü hikâyenin cadılarını anlatır?', '["Oz Büyücüsü","Peter Pan","Alice Harikalar Diyarında","Narnia Günlükleri"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Çaykovski''nin ''Fındıkkıran'' balesi hangi bayram gecesinde geçer?', '["Noel","Paskalya","Cadılar Bayramı","Şükran Günü"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Heykellerle süslü tarihi Charles Köprüsü hangi şehirdedir?', '["Prag","Viyana","Budapeşte","Krakov"]'::jsonb, 0, 'sanat', 'global', null, 2),
('James Whistler''ın sandalyede yandan oturan kadını gösteren ünlü tablosu kimi tasvir eder?', '["Annesini","Karısını","Kızını","Kız kardeşini"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Sanat Güneşi'' lakabıyla anılan şarkıcı kimdir?', '["Zeki Müren","Bülent Ersoy","Emel Sayın","Ajda Pekkan"]'::jsonb, 0, 'sanat', 'yerel', 'TR', 2),
('Disney''in ''Aslan Kral'' filminin şarkılarını Tim Rice ile birlikte yazan şarkıcı kimdir?', '["Elton John","Phil Collins","Billy Joel","Rod Stewart"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Bebek Evi'' oyununun yazarı olan Norveçli oyun yazarı kimdir?', '["Ibsen","Strindberg","Shaw","Pirandello"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Atina Akropolisi''ndeki Parthenon hangi tanrıça adına inşa edilmiştir?', '["Athena","Hera","Artemis","Afrodit"]'::jsonb, 0, 'sanat', 'global', null, 2),
('Dev dikili taşlardan oluşan tarih öncesi anıt Stonehenge hangi ülkededir?', '["İngiltere","İrlanda","Fransa","Galler"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Nibelungen Yüzüğü'' opera dizisinin bestecisi kimdir?', '["Richard Wagner","Gustav Mahler","Anton Bruckner","Richard Strauss"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Les Misérables'' müzikali hangi yazarın romanından uyarlanmıştır?', '["Victor Hugo","Émile Zola","Alexandre Dumas","Gustave Flaubert"]'::jsonb, 0, 'sanat', 'global', null, 2),
('''Romeo ve Juliet'' balesinin müziğini besteleyen Rus besteci kimdir?', '["Prokofiev","Stravinsky","Şostakoviç","Rimski-Korsakov"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Beethoven''ın 9. Senfonisi''ndeki ''Neşeye Övgü'' sözleri hangi şaire aittir?', '["Schiller","Goethe","Heine","Hölderlin"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Tek bir ritmin baştan sona tekrarlandığı orkestra eseri ''Bolero''nun bestecisi kimdir?', '["Ravel","Debussy","Satie","Saint-Saëns"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Andy Warhol muz çizimli ünlü albüm kapağını hangi grup için tasarlamıştır?', '["The Velvet Underground","Creedence Clearwater Revival","The Grateful Dead","Jefferson Airplane"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Dağ Kralının Sarayında'' bölümünü içeren ''Peer Gynt'' müziğinin bestecisi kimdir?', '["Edvard Grieg","Jean Sibelius","Antonín Dvořák","Bedřich Smetana"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''My Fair Lady'' müzikalinde Eliza Doolittle sokakta ne satmaktadır?', '["Çiçek","Gazete","Kibrit","Meyve"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Shakespeare''in ''Bir Yaz Gecesi Rüyası''nda Bottom''un başı hangi hayvanın başına dönüşür?', '["Eşek","Keçi","Domuz","Öküz"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Botticelli''nin ''Venüs''ün Doğuşu'' tablosu hangi müzede sergilenir?', '["Uffizi","Prado","Louvre","Borghese"]'::jsonb, 0, 'sanat', 'global', null, 3),
('''Bir Satıcının Ölümü'' oyununun yazarı kimdir?', '["Arthur Miller","Tennessee Williams","Eugene O''Neill","Edward Albee"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Mısır''daki dev Ebu Simbel tapınaklarını hangi firavun yaptırmıştır?', '["II. Ramses","Tutankamon","Hatşepsut","III. Thutmose"]'::jsonb, 0, 'sanat', 'global', null, 3),
('Wolfgang Amadeus Mozart hangi şehirde doğmuştur?', '["Salzburg","Viyana","Prag","Münih"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Hallelujah'' korosuyla ünlü ''Messiah'' oratoryosunun bestecisi kimdir?', '["Handel","Bach","Haydn","Telemann"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''İstanbul''da Sonbahar'' şarkısının sahibi kimdir?', '["Teoman","Haluk Levent","Kıraç","Cem Adrian"]'::jsonb, 0, 'muzik', 'yerel', 'TR', 2),
('''What a Wonderful World'' şarkısının en ünlü yorumcusu kimdir?', '["Louis Armstrong","Nat King Cole","Ray Charles","Sammy Davis Jr."]'::jsonb, 0, 'muzik', 'global', null, 2),
('''What''s Love Got to Do with It'' ve ''The Best'' şarkılarının sahibi kimdir?', '["Tina Turner","Diana Ross","Donna Summer","Grace Jones"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''La Bohème'' ve ''Tosca'' operalarının bestecisi kimdir?', '["Puccini","Verdi","Rossini","Donizetti"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''The Sound of Music'' filminde Maria''yı canlandıran oyuncu kimdir?', '["Julie Andrews","Audrey Hepburn","Judy Garland","Debbie Reynolds"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Du Hast'' şarkısıyla tanınan Alman metal grubu hangisidir?', '["Rammstein","Scorpions","Accept","Helloween"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Bu Akşam'' ve ''Senden Daha Güzel'' şarkıları hangi grubundur?', '["Duman","Mor ve Ötesi","Gripin","Pinhani"]'::jsonb, 0, 'muzik', 'yerel', 'TR', 2),
('''Sil Baştan'' şarkısıyla tanınan rock şarkıcısı kimdir?', '["Şebnem Ferah","Aylin Aslım","Özlem Tekin","Nil Karaibrahimgil"]'::jsonb, 0, 'muzik', 'yerel', 'TR', 2),
('''A Star Is Born'' filminde Lady Gaga ile ''Shallow''u seslendiren oyuncu kimdir?', '["Bradley Cooper","Ryan Gosling","Hugh Jackman","Jake Gyllenhaal"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Livin'' la Vida Loca'' şarkısıyla dünya listelerine giren şarkıcı kimdir?', '["Ricky Martin","Marc Anthony","Chayanne","Luis Miguel"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Superstition'' ve ''I Just Called to Say I Love You'' şarkılarının sahibi kimdir?', '["Stevie Wonder","Marvin Gaye","Al Green","Lionel Richie"]'::jsonb, 0, 'muzik', 'global', null, 2),
('''Valkürlerin Uçuşu'' adlı ünlü parçanın bestecisi kimdir?', '["Wagner","Verdi","Mahler","Brahms"]'::jsonb, 0, 'muzik', 'global', null, 2),
('Ludwig van Beethoven hangi şehirde doğmuştur?', '["Bonn","Viyana","Leipzig","Salzburg"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Cats'' müzikali hangi şairin kediler üzerine şiirlerine dayanır?', '["T. S. Eliot","W. H. Auden","Rudyard Kipling","Lewis Carroll"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Orkestra süiti ''Gezegenler''in (The Planets) bestecisi kimdir?', '["Gustav Holst","Edward Elgar","Benjamin Britten","Vaughan Williams"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Walk the Line'' filminde Johnny Cash''i canlandıran oyuncu kimdir?', '["Joaquin Phoenix","Christian Bale","Russell Crowe","Jamie Foxx"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Blackpink grubunun Taylandlı üyesi kimdir?', '["Lisa","Jennie","Rosé","Jisoo"]'::jsonb, 0, 'muzik', 'global', null, 3),
('Beats kulaklık markasının kurucularından olan rapçi ve yapımcı kimdir?', '["Dr. Dre","Snoop Dogg","Kanye West","Jay-Z"]'::jsonb, 0, 'muzik', 'global', null, 3),
('''Grand Theft Auto: Vice City'' oyunundaki şehir hangi gerçek şehirden esinlenmiştir?', '["Miami","Los Angeles","New York","Las Vegas"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Microsoft''un bulut bilişim platformunun adı nedir?', '["Azure","AWS","Watson","Oracle Cloud"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Video oyunu karakteri Spyro hangi tür canlıdır?', '["Ejderha","Kertenkele","Dinozor","Bukalemun"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('PlayStation kumandasındaki semboller üçgen, kare, daire ve hangisidir?', '["Çarpı","Artı","Yıldız","Kalp"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Instagram''ı 2012''de satın alan şirket hangisidir?', '["Facebook","Google","Twitter","Yahoo"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('League of Legends oyununu geliştiren şirket hangisidir?', '["Riot Games","Epic Games","Valve Corporation","Blizzard Entertainment"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Minecraft''ın klasik varsayılan oyuncu karakterinin adı nedir?', '["Steve","Jack","Max","Tom"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Call of Duty oyun serisini yayımlayan şirket hangisidir?', '["Activision","Ubisoft","Bethesda","Square Enix"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''The Last of Us'' oyununda Joel''in korumakla görevlendirildiği genç kızın adı nedir?', '["Ellie","Abby","Tess","Riley"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Meta''nın kablosuz sanal gerçeklik başlığı serisinin adı nedir?', '["Quest","Vive","Index","Pico"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Snapchat uygulamasının kurucularından olan iş insanı kimdir?', '["Evan Spiegel","Kevin Systrom","Drew Houston","Jack Dorsey"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Windows''ta tüm pencereleri küçültüp masaüstünü gösteren kısayol hangisidir?', '["Win+D","Win+E","Win+L","Win+R"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Windows''ta etkin pencereyi kapatan klasik klavye kısayolu hangisidir?', '["Alt+F4","Alt+Tab","Ctrl+Esc","Shift+F10"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Türkiye''de geliştirilen mesajlaşma uygulaması BiP hangi şirkete aittir?', '["Turkcell","Vodafone","Türk Telekom","Türksat"]'::jsonb, 0, 'teknoloji', 'yerel', 'TR', 2),
('Firefox internet tarayıcısını geliştiren kuruluş hangisidir?', '["Mozilla","Opera","Apache","Canonical"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Reddit''in logosundaki maskot figürü nedir?', '["Uzaylı","Robot","Hayalet","Astronot"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''The Elder Scrolls V: Skyrim'' oyununu geliştiren stüdyo hangisidir?', '["Bethesda","BioWare","Obsidian","Bungie"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Dil öğrenme uygulaması Duolingo''nun yeşil maskotu hangi hayvandır?', '["Baykuş","Papağan","Penguen","Sincap"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Super Mario oyunlarında Mario''yu kısa süreliğine yenilmez yapan güçlendirme hangisidir?', '["Yıldız","Mantar","Ateş çiçeği","Tüy"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''Animal Crossing''de oyuncuya ev kredisi veren rakun tüccar kimdir?', '["Tom Nook","K.K. Slider","Blathers","Isabelle"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Pikachu, Gök Gürültüsü Taşı ile hangi Pokémon''a evrimleşir?', '["Raichu","Pichu","Jolteon","Plusle"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Uzun yıllar FIFA adıyla çıkan futbol oyunu serisini yayımlayan şirket hangisidir?', '["Electronic Arts","Activision Blizzard","Take-Two Interactive","Bandai Namco"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Google''ın 2016''dan beri ürettiği akıllı telefon serisinin adı nedir?', '["Pixel","Galaxy","Xperia","Lumia"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Spartalı savaşçı Kratos hangi oyun serisinin ana karakteridir?', '["God of War","Devil May Cry","Dark Souls","Diablo"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Windows''ta açık pencereler arasında geçiş yapmayı sağlayan kısayol hangisidir?', '["Alt+Tab","Alt+F4","Ctrl+Esc","Shift+Tab"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('''GTA: San Andreas'' oyununun başkarakteri kimdir?', '["Carl Johnson","Tommy Vercetti","Niko Bellic","Claude Speed"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Popüler oyun Fortnite''ı geliştiren şirket hangisidir?', '["Epic Games","Riot Games","Blizzard","Activision"]'::jsonb, 0, 'teknoloji', 'global', null, 2),
('Apple''ın Super Bowl''da yayınlanan ünlü ''1984'' Macintosh reklamını kim yönetti?', '["Ridley Scott","David Fincher","James Cameron","Steven Spielberg"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Halo serisinin ilk oyunlarını geliştiren stüdyo hangisidir?', '["Bungie","Valve","Epic Games","id Software"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Tetris''in akılda kalan müziği hangi Rus halk şarkısına dayanır?', '["Korobeiniki","Kalinka","Katyuşa","Moskova Geceleri"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Klasik Donkey Kong oyununda goril tarafından kaçırılan kadının adı nedir?', '["Pauline","Peach","Daisy","Rosalina"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Tesla''nın seri olarak ürettiği ilk otomobil modeli hangisidir?', '["Roadster","Model S","Model X","Model 3"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Mortal Kombat''ta zıpkınını fırlatıp ''Get over here!'' diye bağıran ninja kimdir?', '["Scorpion","Sub-Zero","Raiden","Liu Kang"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Nintendo 19. yüzyılda kurulduğunda hangi ürünü üretiyordu?', '["Oyun kartları","Oyuncak trenler","Daktilolar","Fotoğraf makineleri"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Mobil oyun Flappy Bird''ü yaratan geliştirici Dong Nguyen hangi ülkedendir?', '["Vietnam","Tayland","Endonezya","Filipinler"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Pokédex''te 1 numaralı Pokémon hangisidir?', '["Bulbasaur","Charmander","Squirtle","Mew"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Minecraft''ı geliştiren İsveçli oyun stüdyosu hangisidir?', '["Mojang","Rovio","Supercell","King"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('WhatsApp''ı Brian Acton ile birlikte kuran kişi kimdir?', '["Jan Koum","Kevin Systrom","Pavel Durov","Evan Spiegel"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Skype yazılımı ilk olarak hangi ülkedeki mühendislerce geliştirildi?', '["Estonya","Finlandiya","Letonya","Litvanya"]'::jsonb, 0, 'teknoloji', 'global', null, 3),
('Harry Kane 2023''te Tottenham''dan ayrılarak hangi kulübe transfer oldu?', '["Bayern Münih","Real Madrid","Manchester City","PSG"]'::jsonb, 0, 'spor', 'global', null, 2),
('Golden State''in ''Splash Brothers'' ikilisinde Stephen Curry''nin partneri kimdir?', '["Klay Thompson","Kevin Durant","Draymond Green","Andre Iguodala"]'::jsonb, 0, 'spor', 'global', null, 2),
('Efsanevi golcü Didier Drogba hangi ülkenin milli takımında oynamıştır?', '["Fildişi Sahili","Gana","Burkina Faso","Demokratik Kongo"]'::jsonb, 0, 'spor', 'global', null, 2),
('Çinli basketbolcu Yao Ming NBA''de hangi takımın formasını giymiştir?', '["Houston Rockets","Los Angeles Clippers","Denver Nuggets","Dallas Mavericks"]'::jsonb, 0, 'spor', 'global', null, 2),
('1997''de Garry Kasparov''u maçta yenen IBM satranç bilgisayarının adı nedir?', '["Deep Blue","Blue Gene","Big Blue","Watson"]'::jsonb, 0, 'spor', 'global', null, 2),
('Muhammad Ali''nin ünlü sözüne göre o kelebek gibi uçar, neyin gibi sokar?', '["Arı","Akrep","Yılan","Sivrisinek"]'::jsonb, 0, 'spor', 'global', null, 2),
('2014 Dünya Kupası''nda İtalyan Chiellini''yi ısıran Uruguaylı forvet kimdir?', '["Luis Suárez","Edinson Cavani","Diego Forlán","Sebastián Abreu"]'::jsonb, 0, 'spor', 'global', null, 2),
('Buz hokeyi efsanesi Wayne Gretzky hangi ülkelidir?', '["Kanada","ABD","İsveç","Finlandiya"]'::jsonb, 0, 'spor', 'global', null, 2),
('Lakers''ta Kobe Bryant''la üst üste üç NBA şampiyonluğu kazanan pivot kimdir?', '["Shaquille O''Neal","Kareem Abdul-Jabbar","Dikembe Mutombo","Patrick Ewing"]'::jsonb, 0, 'spor', 'global', null, 2),
('Larry Bird NBA kariyerinin tamamını hangi takımda geçirmiştir?', '["Boston Celtics","Los Angeles Lakers","Detroit Pistons","New York Knicks"]'::jsonb, 0, 'spor', 'global', null, 2),
('Sebastian Vettel dört F1 dünya şampiyonluğunu hangi takımla kazandı?', '["Red Bull","Aston Martin","Toro Rosso","Ferrari"]'::jsonb, 0, 'spor', 'global', null, 2),
('Neymar 2017''de rekor bir bonservisle Barcelona''dan hangi kulübe transfer oldu?', '["PSG","Juventus","Chelsea","Bayern Münih"]'::jsonb, 0, 'spor', 'global', null, 2),
('2010 Dünya Kupası finalinde İspanya''ya kupayı getiren golü kim attı?', '["Andrés Iniesta","Xavi Hernández","David Villa","Fernando Torres"]'::jsonb, 0, 'spor', 'global', null, 2),
('Cristiano Ronaldo Manchester United''dan ayrılınca hangi Suudi kulübüne geçti?', '["Al-Nassr","Al-Hilal","Al-Ittihad","Al-Ahli"]'::jsonb, 0, 'spor', 'global', null, 2),
('NHL''de sezonun şampiyonu olan takıma verilen kupanın adı nedir?', '["Stanley Kupası","Calder Kupası","Davis Kupası","Ryder Kupası"]'::jsonb, 0, 'spor', 'global', null, 2),
('Motosiklet yarışçısı Valentino Rossi hangi lakapla tanınır?', '["Doktor","Profesör","Kaptan","Baron"]'::jsonb, 0, 'spor', 'global', null, 2),
('''Herminator'' lakaplı alp disiplini kayakçısı Hermann Maier hangi ülkelidir?', '["Avusturya","İsviçre","Almanya","Norveç"]'::jsonb, 0, 'spor', 'global', null, 3),
('Fernando Alonso iki F1 dünya şampiyonluğunu hangi takımla kazandı?', '["Renault","Ferrari","McLaren","Williams"]'::jsonb, 0, 'spor', 'global', null, 3),
('Yüzücü Michael Phelps ABD''nin hangi şehrinde doğmuştur?', '["Baltimore","Boston","Denver","Seattle"]'::jsonb, 0, 'spor', 'global', null, 3),
('Lionel Messi Arjantin''in hangi şehrinde doğmuştur?', '["Rosario","Córdoba","Mendoza","La Plata"]'::jsonb, 0, 'spor', 'global', null, 3),
('Michael Jordan NBA''de son olarak hangi takımın formasını giydi?', '["Washington Wizards","Charlotte Hornets","Atlanta Hawks","Cleveland Cavaliers"]'::jsonb, 0, 'spor', 'global', null, 3),
('2006 Dünya Kupası finalinde İtalya''ya kupayı getiren son penaltıyı kim attı?', '["Fabio Grosso","Andrea Pirlo","Marco Materazzi","Alessandro Del Piero"]'::jsonb, 0, 'spor', 'global', null, 3),
('1994''te Tonya Harding''in çevresince dizine saldırı düzenlenen patinajcı kimdir?', '["Nancy Kerrigan","Kristi Yamaguchi","Michelle Kwan","Oksana Baiul"]'::jsonb, 0, 'spor', 'global', null, 3),
('1986''da felakete sahne olan Çernobil nükleer santrali bugün hangi ülkenin sınırları içindedir?', '["Ukrayna","Belarus","Rusya","Litvanya"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Sovyet lideri Josef Stalin bugün hangi ülkenin toprakları içinde kalan bir kasabada doğdu?', '["Gürcistan","Ermenistan","Ukrayna","Azerbaycan"]'::jsonb, 0, 'tarih', 'global', null, 2),
('Lenin takma adıyla tanınan Bolşevik liderin asıl soyadı nedir?', '["Ulyanov","Cugaşvili","Bronştayn","Skryabin"]'::jsonb, 0, 'tarih', 'global', null, 3),
('''Titanik'' filmindeki ünlü mavi elmas kolyenin adı nedir?', '["Okyanusun Kalbi","Denizin Yıldızı","Mavi Gözyaşı","Kraliçenin Gözü"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Dövüş Kulübü''nde isimsiz anlatıcıyı canlandıran oyuncu kimdir?', '["Edward Norton","Matt Damon","Jared Leto","Ethan Hawke"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Küçük Deniz Kızı''nda Ariel''e göz kulak olan yengecin adı nedir?', '["Sebastian","Flounder","Scuttle","Triton"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yaralı Yüz'' (1983) filminde Tony Montana''yı canlandıran oyuncu kimdir?', '["Al Pacino","Robert De Niro","Andy García","Joe Pesci"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Eşkıya'' filminde Baran''ın İstanbul''da tanıştığı Cumali''yi kim canlandırır?', '["Uğur Yücel","Haluk Bilginer","Kenan İmirzalıoğlu","Okan Bayülgen"]'::jsonb, 0, 'sinema', 'yerel', 'TR', 2),
('''Babam ve Oğlum'' filminde baba Hüseyin Efendi''yi canlandıran oyuncu kimdir?', '["Çetin Tekindor","Fikret Kuşkan","Tuncel Kurtiz","Halil Ergün"]'::jsonb, 0, 'sinema', 'yerel', 'TR', 2),
('''Shrek 2''de Çizmeli Kedi''yi seslendiren oyuncu kimdir?', '["Antonio Banderas","Javier Bardem","Andy García","Benicio del Toro"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Zootropolis''te Judy Hopps''a yardım eden Nick Wilde hangi hayvandır?', '["Tilki","Kurt","Rakun","Gelincik"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Yıldızlararası'' filminde pilot Cooper''ı canlandıran oyuncu kimdir?', '["M. McConaughey","Christian Bale","Jake Gyllenhaal","Ryan Gosling"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Esaretin Bedeli''nde Red karakterini canlandıran oyuncu kimdir?', '["Morgan Freeman","Denzel Washington","Danny Glover","Samuel L. Jackson"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Harry Potter'' filmlerinde Lord Voldemort''u canlandıran oyuncu kimdir?', '["Ralph Fiennes","Gary Oldman","Jason Isaacs","Kenneth Branagh"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Diriliş'' (The Revenant) filminde Hugh Glass''a hangi hayvan saldırır?', '["Ayı","Kurt","Puma","Bizon"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Hababam Sınıfı'' filmlerinde olayların geçtiği okulun adı nedir?', '["Özel Çamlıca Lisesi","Özel Moda Lisesi","Özel Kadıköy Lisesi","Özel Üsküdar Lisesi"]'::jsonb, 0, 'sinema', 'yerel', 'TR', 2),
('''Baba'' (1972) filminde Vito Corleone''yi canlandıran oyuncu kimdir?', '["Marlon Brando","Al Pacino","James Caan","Robert Duvall"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Ucuz Roman'' filminde Mia Wallace''ı canlandıran oyuncu kimdir?', '["Uma Thurman","Bridget Fonda","Rosanna Arquette","Juliette Lewis"]'::jsonb, 0, 'sinema', 'global', null, 2),
('''Siyah Giyen Adamlar''da tanıkların hafızasını silen cihazın adı nedir?', '["Neuralyzer","Tricorder","Flux Capacitor","Portal Gun"]'::jsonb, 0, 'sinema', 'global', null, 3),
('Pixar''ın ''Yukarı Bak'' filminde konuşan tasma takan köpeğin adı nedir?', '["Dug","Rex","Max","Bolt"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Dirty Dancing'' filminde ''Baby'' lakaplı kahramanın gerçek adı nedir?', '["Frances","Penny","Lisa","Margaret"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''RoboCop'' (1987) filmi hangi ABD şehrinde geçer?', '["Detroit","Chicago","Cleveland","Pittsburgh"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Avengers: Sonsuzluk Savaşı''nda Thanos''u canlandıran oyuncu kimdir?', '["Josh Brolin","Mickey Rourke","Michael Shannon","Jeff Bridges"]'::jsonb, 0, 'sinema', 'global', null, 3),
('''Şeytan'' (The Exorcist) filminde içine şeytan giren kızın adı nedir?', '["Regan","Carrie","Samara","Wednesday"]'::jsonb, 0, 'sinema', 'global', null, 3),
('Çizgi filmlerde sarı kanarya Tweety''yi kovalayan kedinin adı nedir?', '["Sylvester","Tom","Heathcliff","Felix"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Breaking Bad''de Walter White''ın uyuşturucu dünyasında kullandığı takma ad nedir?', '["Heisenberg","Schrödinger","Einstein","Oppenheimer"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Pembe Panter'' filmlerindeki beceriksiz Fransız müfettişin soyadı nedir?', '["Clouseau","Maigret","Columbo","Gadget"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Çığlık'' tablosunun ressamı Edvard Munch hangi ülkelidir?', '["Norveç","İsveç","Danimarka","Finlandiya"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Reşat Nuri Güntekin''in ''Çalıkuşu'' romanının baş kahramanının adı nedir?', '["Feride","Nermin","Leyla","Necla"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('''Star Wars''ta Darth Vader''ın karanlık tarafa geçmeden önceki ilk adı nedir?', '["Anakin","Luke","Owen","Ben"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Deniz kabuğu üzerinde duran tanrıçayı betimleyen ''Venüs''ün Doğuşu'' kimin eseridir?', '["Botticelli","Raffaello","Tiziano","Caravaggio"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kemal Sunal''ın ''Hababam Sınıfı'' filmlerinde canlandırdığı karakter kimdir?', '["İnek Şaban","Damat Ferit","Güdük Necmi","Tulum Hayri"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 2),
('1971 tarihli ''Imagine'' şarkısını hangi eski Beatles üyesi yazıp seslendirmiştir?', '["John Lennon","Paul McCartney","George Harrison","Ringo Starr"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Purple Rain'' albümü ve filmiyle tanınan Amerikalı müzisyen kimdir?', '["Prince","David Bowie","Stevie Wonder","Lionel Richie"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Rivayete göre Kleopatra hangi hayvanın ısırığıyla ölmüştür?', '["Yılan","Akrep","Örümcek","Timsah"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Çakmaktaş Ailesi''nde Fred Çakmaktaş''ın eşinin adı nedir?', '["Wilma","Betty","Pebbles","Marge"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('''Star Trek''te Kaptan Kirk''ün komuta ettiği yıldız gemisinin adı nedir?', '["Enterprise","Nostromo","Serenity","Galactica"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Cervantes''in ''Don Kişot'' romanında kahramanın sadık yaverinin adı nedir?', '["Sancho Panza","Lazarillo","Gil Blas","Rodrigo Díaz"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kahve zinciri Starbucks ilk mağazasını hangi ABD şehrinde açmıştır?', '["Seattle","Portland","Chicago","Boston"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Barselona''daki Sagrada Família bazilikasının mimarı kimdir?', '["Antoni Gaudí","Le Corbusier","Frank Gehry","Santiago Calatrava"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Kont Drakula''nın yurdu Transilvanya bölgesi bugün hangi ülkededir?', '["Romanya","Macaristan","Bulgaristan","Sırbistan"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('The Beatles üyelerinin yaya geçidinde yürüdüğü ünlü kapak hangi albümlerine aittir?', '["Abbey Road","Let It Be","Revolver","Help!"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Sherlock Holmes''un ünlü 221B numaralı evi Londra''nın hangi caddesindedir?', '["Baker Street","Abbey Road","Oxford Street","Fleet Street"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('1975 yapımı köpekbalığı filmi ''Jaws''un yönetmeni kimdir?', '["Spielberg","Lucas","Scorsese","Coppola"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('ABD dizisi ''The Office''te Michael Scott''ın çalıştığı kâğıt şirketinin adı nedir?', '["Dunder Mifflin","Initech","Sterling Cooper","Pied Piper"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Efsanevi sprinter Usain Bolt hangi ülkelidir?', '["Jamaika","Bahamalar","Barbados","Trinidad ve Tobago"]'::jsonb, 0, 'genel_kultur', 'global', null, 2),
('Video oyunu Tetris ilk olarak hangi şehirde geliştirilmiştir?', '["Moskova","Tokyo","Helsinki","Seattle"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Çizgi film kahramanı Scooby-Doo hangi köpek ırkındandır?', '["Danua","Saint Bernard","Doberman","Boksör"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Moby Dick'' romanında beyaz balinanın peşine düşen kaptanın adı nedir?', '["Ahab","Nemo","Flint","Hook"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Apollo 11''de Neil Armstrong''dan sonra Ay''a ayak basan astronot kimdir?', '["Buzz Aldrin","Michael Collins","John Glenn","Alan Shepard"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Ninja Kaplumbağalar''ın mavi bantlı lideri hangisidir?', '["Leonardo","Raphael","Donatello","Michelangelo"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Casablanca'' filminde Rick''in barında piyano çalan karakterin adı nedir?', '["Sam","Louis","Victor","Carl"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Burnu yalan söyledikçe uzayan Pinokyo''nun yazarı kimdir?', '["Carlo Collodi","Gianni Rodari","Italo Calvino","Umberto Eco"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Küçük Prens''in yazarı Antoine de Saint-Exupéry''nin asıl mesleği neydi?', '["Pilot","Doktor","Öğretmen","Avukat"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Orwell''in ''Hayvan Çiftliği''nde iktidarı ele geçiren diktatör domuzun adı nedir?', '["Napoleon","Snowball","Squealer","Old Major"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Orhan Pamuk''un ''Masumiyet Müzesi'' romanının baş erkek karakterinin adı nedir?', '["Kemal","Ka","Galip","Celal"]'::jsonb, 0, 'genel_kultur', 'yerel', 'TR', 3),
('''Game of Thrones''ta Jon Snow''un dire kurdunun adı nedir?', '["Ghost","Nymeria","Summer","Grey Wind"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Monet''nin nilüfer tablolarına ilham veren bahçesi hangi Fransız köyündedir?', '["Giverny","Arles","Barbizon","Honfleur"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('''Yurttaş Kane'' filminde Kane''in ölürken söylediği son sözcük nedir?', '["Rosebud","Xanadu","Mayflower","Moonlight"]'::jsonb, 0, 'genel_kultur', 'global', null, 3),
('Agatha Christie''nin dedektifi Hercule Poirot hangi ülkelidir?', '["Belçika","Fransa","İsviçre","Lüksemburg"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Halit Ziya''nın ''Aşk-ı Memnu'' romanında Adnan Bey''le evlenen genç kadın kimdir?', '["Bihter","Nihal","Firdevs","Peyker"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('Sherlock Holmes''un Baker Street''teki evinin sahibesi olan kadın kimdir?', '["Bayan Hudson","Bayan Hughes","Bayan Turner","Bayan Brown"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Oscar Wilde''ın romanında Dorian Gray hiç yaşlanmazken onun yerine ne yaşlanır?', '["Portresi","Aynası","Heykeli","Gölgesi"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Jane Eyre''de Jane''in mürebbiye olarak çalıştığı Thornfield Konağı''nın sahibi kimdir?', '["Rochester","Darcy","Heathcliff","Knightley"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Shakespeare''in ''Hamlet'' oyununda derede boğularak ölen genç kız kimdir?', '["Ophelia","Desdemona","Cordelia","Portia"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Oz Büyücüsü''nde Dorothy kasırgayla hangi ABD eyaletinden Oz''a savrulur?', '["Kansas","Nebraska","Oklahoma","Iowa"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Roald Dahl''ın ''Charlie''nin Çikolata Fabrikası'' kitabında Charlie''nin soyadı nedir?', '["Bucket","Salt","Gloop","Teavee"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Harry Potter'' serisinde Harry, Gryffindor Quidditch takımında hangi mevkide oynar?', '["Arayıcı","Vurucu","Kovalayıcı","Tutucu"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Kürk Mantolu Madonna''da Raif Efendi''nin Berlin''de âşık olduğu ressamın adı nedir?', '["Maria Puder","Anna Schmidt","Greta Weber","Helga Braun"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('Yaşar Kemal''in ''İnce Memed'' romanında Memed''in sevdiği kızın adı nedir?', '["Hatçe","Zeliha","Elif","Seher"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 2),
('''Üç Silahşörler''de Athos ve Porthos''un yanındaki üçüncü silahşör kimdir?', '["Aramis","Rochefort","Tréville","Planchet"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Winnie the Pooh'' kitaplarında Pooh''un kasvetli eşek arkadaşının adı nedir?', '["Eeyore","Tigger","Piglet","Kanga"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Muhteşem Gatsby''de Gatsby''nin yıllardır sevdiği kadının adı nedir?', '["Daisy","Myrtle","Jordan","Rosie"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('''Alice Harikalar Diyarında''da durmadan ''Kafasını uçurun!'' diye bağıran karakter kimdir?', '["Kupa Kraliçesi","Maça Kraliçesi","Karo Kraliçesi","Sinek Kraliçesi"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Kafka''nın ''Dönüşüm''ünde bir sabah böceğe dönüşmüş olarak uyanan kahramanın adı nedir?', '["Gregor","Josef","Karl","Franz"]'::jsonb, 0, 'edebiyat', 'global', null, 2),
('Bram Stoker''ın ''Dracula'' romanında Jonathan Harker''ın nişanlısının adı nedir?', '["Mina","Lucy","Ilona","Clara"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Orhan Pamuk''un ''Masumiyet Müzesi''nde Kemal''in tutkuyla bağlandığı uzak akrabası kimdir?', '["Füsun","Sibel","Nesrin","Zaim"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 3),
('Stoker''ın ''Dracula''sında kontun gemisi İngiltere''de hangi liman kasabasına varır?', '["Whitby","Dover","Brighton","Plymouth"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Victor Hugo''nun ''Sefiller'' romanında Cosette''in annesinin adı nedir?', '["Fantine","Éponine","Colette","Odette"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Halide Edib''in ''Sinekli Bakkal'' romanının kahramanı olan genç kızın adı nedir?', '["Rabia","Feride","Bihter","Nermin"]'::jsonb, 0, 'edebiyat', 'yerel', 'TR', 3),
('Tolkien''in ''Hobbit'' romanında Bilbo''nun katıldığı cüce grubunun lideri kimdir?', '["Thorin","Balin","Gimli","Dwalin"]'::jsonb, 0, 'edebiyat', 'global', null, 3),
('Bradbury''nin ''Fahrenheit 451'' romanının itfaiyeci kahramanının soyadı nedir?', '["Montag","Beatty","Faber","Granger"]'::jsonb, 0, 'edebiyat', 'global', null, 3)
on conflict (soru) do nothing;

-- ---------------------------------------------------- İngilizce çeviri
insert into public.question_translations (question_id, dil, soru, secenekler)
select q.id, 'en', v.en_soru, v.en_secenekler
  from (values
  ('İkiz Petronas Kuleleri hangi şehirdedir?', 'The twin Petronas Towers are located in which city?', '["Kuala Lumpur","Ho Chi Minh City","Singapore","Jakarta"]'::jsonb),
  ('''Sevil Berberi'' operasının bestecisi kimdir?', 'Who composed the opera ''The Barber of Seville''?', '["Rossini","Verdi","Puccini","Bellini"]'::jsonb),
  ('''Amadeus'' filminde Mozart''ı kıskanan saray bestecisi kimdir?', 'In the film Amadeus, which court composer is consumed by jealousy of Mozart?', '["Salieri","Haydn","Gluck","Clementi"]'::jsonb),
  ('Uzun boyunlu, badem gözlü portreleriyle tanınan İtalyan ressam kimdir?', 'Which Italian painter is known for portraits of figures with long necks and almond eyes?', '["Modigliani","De Chirico","Boccioni","Morandi"]'::jsonb),
  ('Londra''daki Trafalgar Meydanı''nın ünlü sütununun tepesinde kimin heykeli durur?', 'Whose statue stands on top of the famous column in London''s Trafalgar Square?', '["Nelson","Wellington","Churchill","Cromwell"]'::jsonb),
  ('Ünlü anıt mezar Tac Mahal hangi Hindistan şehrindedir?', 'In which Indian city is the Taj Mahal located?', '["Agra","Delhi","Jaipur","Mumbai"]'::jsonb),
  ('Endülüs mimarisinin şaheseri Elhamra Sarayı hangi İspanyol şehrindedir?', 'The Alhambra palace complex is located in which Spanish city?', '["Granada","Seville","Cordoba","Malaga"]'::jsonb),
  ('Pink Floyd''un ''The Dark Side of the Moon'' kapağında ışık hangi nesneden geçer?', 'On the cover of Pink Floyd''s ''The Dark Side of the Moon'', light passes through what?', '["A prism","A lens","A mirror","A crystal ball"]'::jsonb),
  ('Gize''deki en büyük piramit hangi firavun için yapılmıştır?', 'For which pharaoh was the Great Pyramid of Giza built?', '["Khufu","Ramesses II","Tutankhamun","Akhenaten"]'::jsonb),
  ('''Wicked'' müzikali hangi ünlü hikâyenin cadılarını anlatır?', 'The musical ''Wicked'' tells the story of the witches from which famous tale?', '["The Wizard of Oz","Peter Pan","Alice in Wonderland","The Chronicles of Narnia"]'::jsonb),
  ('Çaykovski''nin ''Fındıkkıran'' balesi hangi bayram gecesinde geçer?', 'Tchaikovsky''s ballet ''The Nutcracker'' takes place on the eve of which holiday?', '["Christmas","Easter","Halloween","Thanksgiving"]'::jsonb),
  ('Heykellerle süslü tarihi Charles Köprüsü hangi şehirdedir?', 'The historic, statue-lined Charles Bridge is in which city?', '["Prague","Vienna","Budapest","Krakow"]'::jsonb),
  ('James Whistler''ın sandalyede yandan oturan kadını gösteren ünlü tablosu kimi tasvir eder?', 'Whistler''s famous painting of a woman seated in profile depicts which of his relatives?', '["His mother","His wife","His daughter","His sister"]'::jsonb),
  ('Disney''in ''Aslan Kral'' filminin şarkılarını Tim Rice ile birlikte yazan şarkıcı kimdir?', 'Which singer wrote the songs for Disney''s The Lion King together with Tim Rice?', '["Elton John","Phil Collins","Billy Joel","Rod Stewart"]'::jsonb),
  ('''Bebek Evi'' oyununun yazarı olan Norveçli oyun yazarı kimdir?', 'Which Norwegian playwright wrote ''A Doll''s House''?', '["Ibsen","Strindberg","Shaw","Pirandello"]'::jsonb),
  ('Atina Akropolisi''ndeki Parthenon hangi tanrıça adına inşa edilmiştir?', 'The Parthenon in Athens was built in honor of which goddess?', '["Athena","Hera","Artemis","Aphrodite"]'::jsonb),
  ('Dev dikili taşlardan oluşan tarih öncesi anıt Stonehenge hangi ülkededir?', 'The prehistoric monument of huge standing stones, Stonehenge, is in which country?', '["England","Ireland","France","Wales"]'::jsonb),
  ('''Nibelungen Yüzüğü'' opera dizisinin bestecisi kimdir?', 'Which composer wrote the opera cycle ''The Ring of the Nibelung''?', '["Richard Wagner","Gustav Mahler","Anton Bruckner","Richard Strauss"]'::jsonb),
  ('''Les Misérables'' müzikali hangi yazarın romanından uyarlanmıştır?', 'The musical ''Les Miserables'' is based on a novel by which author?', '["Victor Hugo","Emile Zola","Alexandre Dumas","Gustave Flaubert"]'::jsonb),
  ('''Romeo ve Juliet'' balesinin müziğini besteleyen Rus besteci kimdir?', 'Which Russian composer wrote the music for the ballet ''Romeo and Juliet''?', '["Prokofiev","Stravinsky","Shostakovich","Rimsky-Korsakov"]'::jsonb),
  ('Beethoven''ın 9. Senfonisi''ndeki ''Neşeye Övgü'' sözleri hangi şaire aittir?', 'Which poet wrote the ''Ode to Joy'' words used in Beethoven''s Ninth Symphony?', '["Schiller","Goethe","Heine","Holderlin"]'::jsonb),
  ('Tek bir ritmin baştan sona tekrarlandığı orkestra eseri ''Bolero''nun bestecisi kimdir?', 'Who composed ''Bolero'', the orchestral piece built on one relentlessly repeated rhythm?', '["Ravel","Debussy","Satie","Saint-Saens"]'::jsonb),
  ('Andy Warhol muz çizimli ünlü albüm kapağını hangi grup için tasarlamıştır?', 'Andy Warhol designed the famous banana album cover for which band?', '["The Velvet Underground","Creedence Clearwater Revival","The Grateful Dead","Jefferson Airplane"]'::jsonb),
  ('''Dağ Kralının Sarayında'' bölümünü içeren ''Peer Gynt'' müziğinin bestecisi kimdir?', 'Who composed the ''Peer Gynt'' music, including ''In the Hall of the Mountain King''?', '["Edvard Grieg","Jean Sibelius","Antonin Dvorak","Bedrich Smetana"]'::jsonb),
  ('''My Fair Lady'' müzikalinde Eliza Doolittle sokakta ne satmaktadır?', 'In ''My Fair Lady'', what does Eliza Doolittle sell on the street?', '["Flowers","Newspapers","Matches","Fruit"]'::jsonb),
  ('Shakespeare''in ''Bir Yaz Gecesi Rüyası''nda Bottom''un başı hangi hayvanın başına dönüşür?', 'In ''A Midsummer Night''s Dream'', Bottom''s head is turned into that of which animal?', '["A donkey","A goat","A pig","An ox"]'::jsonb),
  ('Botticelli''nin ''Venüs''ün Doğuşu'' tablosu hangi müzede sergilenir?', 'In which museum is Botticelli''s ''The Birth of Venus'' displayed?', '["Uffizi","Prado","Louvre","Borghese"]'::jsonb),
  ('''Bir Satıcının Ölümü'' oyununun yazarı kimdir?', 'Who wrote the play ''Death of a Salesman''?', '["Arthur Miller","Tennessee Williams","Eugene O''Neill","Edward Albee"]'::jsonb),
  ('Mısır''daki dev Ebu Simbel tapınaklarını hangi firavun yaptırmıştır?', 'Which pharaoh built the colossal temples of Abu Simbel in Egypt?', '["Ramesses II","Tutankhamun","Hatshepsut","Thutmose III"]'::jsonb),
  ('Wolfgang Amadeus Mozart hangi şehirde doğmuştur?', 'In which city was Wolfgang Amadeus Mozart born?', '["Salzburg","Vienna","Prague","Munich"]'::jsonb),
  ('''Hallelujah'' korosuyla ünlü ''Messiah'' oratoryosunun bestecisi kimdir?', 'Who composed the oratorio ''Messiah'', famous for its ''Hallelujah'' chorus?', '["Handel","Bach","Haydn","Telemann"]'::jsonb),
  ('''What a Wonderful World'' şarkısının en ünlü yorumcusu kimdir?', 'Who is best known for singing ''What a Wonderful World''?', '["Louis Armstrong","Nat King Cole","Ray Charles","Sammy Davis Jr."]'::jsonb),
  ('''What''s Love Got to Do with It'' ve ''The Best'' şarkılarının sahibi kimdir?', 'Who sang ''What''s Love Got to Do with It'' and ''The Best''?', '["Tina Turner","Diana Ross","Donna Summer","Grace Jones"]'::jsonb),
  ('''La Bohème'' ve ''Tosca'' operalarının bestecisi kimdir?', 'Who composed the operas ''La Boheme'' and ''Tosca''?', '["Puccini","Verdi","Rossini","Donizetti"]'::jsonb),
  ('''The Sound of Music'' filminde Maria''yı canlandıran oyuncu kimdir?', 'Who played Maria in the film ''The Sound of Music''?', '["Julie Andrews","Audrey Hepburn","Judy Garland","Debbie Reynolds"]'::jsonb),
  ('''Du Hast'' şarkısıyla tanınan Alman metal grubu hangisidir?', 'Which German metal band is known for ''Du Hast''?', '["Rammstein","Scorpions","Accept","Helloween"]'::jsonb),
  ('''A Star Is Born'' filminde Lady Gaga ile ''Shallow''u seslendiren oyuncu kimdir?', 'Which actor sang ''Shallow'' with Lady Gaga in ''A Star Is Born''?', '["Bradley Cooper","Ryan Gosling","Hugh Jackman","Jake Gyllenhaal"]'::jsonb),
  ('''Livin'' la Vida Loca'' şarkısıyla dünya listelerine giren şarkıcı kimdir?', 'Who topped the charts with ''Livin'' la Vida Loca''?', '["Ricky Martin","Marc Anthony","Chayanne","Luis Miguel"]'::jsonb),
  ('''Superstition'' ve ''I Just Called to Say I Love You'' şarkılarının sahibi kimdir?', 'Who sang ''Superstition'' and ''I Just Called to Say I Love You''?', '["Stevie Wonder","Marvin Gaye","Al Green","Lionel Richie"]'::jsonb),
  ('''Valkürlerin Uçuşu'' adlı ünlü parçanın bestecisi kimdir?', 'Who composed ''Ride of the Valkyries''?', '["Wagner","Verdi","Mahler","Brahms"]'::jsonb),
  ('Ludwig van Beethoven hangi şehirde doğmuştur?', 'In which city was Ludwig van Beethoven born?', '["Bonn","Vienna","Leipzig","Salzburg"]'::jsonb),
  ('''Cats'' müzikali hangi şairin kediler üzerine şiirlerine dayanır?', 'The musical ''Cats'' is based on poems by which poet?', '["T. S. Eliot","W. H. Auden","Rudyard Kipling","Lewis Carroll"]'::jsonb),
  ('Orkestra süiti ''Gezegenler''in (The Planets) bestecisi kimdir?', 'Who composed the orchestral suite ''The Planets''?', '["Gustav Holst","Edward Elgar","Benjamin Britten","Vaughan Williams"]'::jsonb),
  ('''Walk the Line'' filminde Johnny Cash''i canlandıran oyuncu kimdir?', 'Who played Johnny Cash in the film ''Walk the Line''?', '["Joaquin Phoenix","Christian Bale","Russell Crowe","Jamie Foxx"]'::jsonb),
  ('Blackpink grubunun Taylandlı üyesi kimdir?', 'Which member of Blackpink is from Thailand?', '["Lisa","Jennie","Rose","Jisoo"]'::jsonb),
  ('Beats kulaklık markasının kurucularından olan rapçi ve yapımcı kimdir?', 'Which rapper and producer co-founded the Beats headphone brand?', '["Dr. Dre","Snoop Dogg","Kanye West","Jay-Z"]'::jsonb),
  ('''Grand Theft Auto: Vice City'' oyunundaki şehir hangi gerçek şehirden esinlenmiştir?', 'The fictional city in ''Grand Theft Auto: Vice City'' is based on which real city?', '["Miami","Los Angeles","New York","Las Vegas"]'::jsonb),
  ('Microsoft''un bulut bilişim platformunun adı nedir?', 'What is the name of Microsoft''s cloud computing platform?', '["Azure","AWS","Watson","Oracle Cloud"]'::jsonb),
  ('Video oyunu karakteri Spyro hangi tür canlıdır?', 'What kind of creature is the video game character Spyro?', '["Dragon","Lizard","Dinosaur","Chameleon"]'::jsonb),
  ('PlayStation kumandasındaki semboller üçgen, kare, daire ve hangisidir?', 'The PlayStation controller''s symbols are triangle, square, circle and what?', '["Cross","Plus","Star","Heart"]'::jsonb),
  ('Instagram''ı 2012''de satın alan şirket hangisidir?', 'Which company bought Instagram in 2012?', '["Facebook","Google","Twitter","Yahoo"]'::jsonb),
  ('League of Legends oyununu geliştiren şirket hangisidir?', 'Which company developed League of Legends?', '["Riot Games","Epic Games","Valve Corporation","Blizzard Entertainment"]'::jsonb),
  ('Minecraft''ın klasik varsayılan oyuncu karakterinin adı nedir?', 'What is the name of Minecraft''s classic default player character?', '["Steve","Jack","Max","Tom"]'::jsonb),
  ('Call of Duty oyun serisini yayımlayan şirket hangisidir?', 'Which company publishes the Call of Duty series?', '["Activision","Ubisoft","Bethesda","Square Enix"]'::jsonb),
  ('''The Last of Us'' oyununda Joel''in korumakla görevlendirildiği genç kızın adı nedir?', 'In ''The Last of Us'', what is the name of the girl Joel is tasked with protecting?', '["Ellie","Abby","Tess","Riley"]'::jsonb),
  ('Meta''nın kablosuz sanal gerçeklik başlığı serisinin adı nedir?', 'What is the name of Meta''s line of standalone VR headsets?', '["Quest","Vive","Index","Pico"]'::jsonb),
  ('Snapchat uygulamasının kurucularından olan iş insanı kimdir?', 'Which entrepreneur is one of the co-founders of Snapchat?', '["Evan Spiegel","Kevin Systrom","Drew Houston","Jack Dorsey"]'::jsonb),
  ('Windows''ta tüm pencereleri küçültüp masaüstünü gösteren kısayol hangisidir?', 'In Windows, which shortcut minimizes everything and shows the desktop?', '["Win+D","Win+E","Win+L","Win+R"]'::jsonb),
  ('Windows''ta etkin pencereyi kapatan klasik klavye kısayolu hangisidir?', 'In Windows, which classic shortcut closes the active window?', '["Alt+F4","Alt+Tab","Ctrl+Esc","Shift+F10"]'::jsonb),
  ('Firefox internet tarayıcısını geliştiren kuruluş hangisidir?', 'Which organization develops the Firefox web browser?', '["Mozilla","Opera","Apache","Canonical"]'::jsonb),
  ('Reddit''in logosundaki maskot figürü nedir?', 'What kind of figure is the mascot in Reddit''s logo?', '["Alien","Robot","Ghost","Astronaut"]'::jsonb),
  ('''The Elder Scrolls V: Skyrim'' oyununu geliştiren stüdyo hangisidir?', 'Which studio developed ''The Elder Scrolls V: Skyrim''?', '["Bethesda","BioWare","Obsidian","Bungie"]'::jsonb),
  ('Dil öğrenme uygulaması Duolingo''nun yeşil maskotu hangi hayvandır?', 'What animal is Duolingo''s green mascot?', '["Owl","Parrot","Penguin","Squirrel"]'::jsonb),
  ('Super Mario oyunlarında Mario''yu kısa süreliğine yenilmez yapan güçlendirme hangisidir?', 'In the Super Mario games, which power-up makes Mario temporarily invincible?', '["Star","Mushroom","Fire Flower","Feather"]'::jsonb),
  ('''Animal Crossing''de oyuncuya ev kredisi veren rakun tüccar kimdir?', 'In Animal Crossing, which raccoon-like shopkeeper gives you a home loan?', '["Tom Nook","K.K. Slider","Blathers","Isabelle"]'::jsonb),
  ('Pikachu, Gök Gürültüsü Taşı ile hangi Pokémon''a evrimleşir?', 'Which Pokemon does Pikachu evolve into with a Thunder Stone?', '["Raichu","Pichu","Jolteon","Plusle"]'::jsonb),
  ('Uzun yıllar FIFA adıyla çıkan futbol oyunu serisini yayımlayan şirket hangisidir?', 'Which company published the long-running FIFA football video game series?', '["Electronic Arts","Activision Blizzard","Take-Two Interactive","Bandai Namco"]'::jsonb),
  ('Google''ın 2016''dan beri ürettiği akıllı telefon serisinin adı nedir?', 'What is the name of Google''s smartphone line, made since 2016?', '["Pixel","Galaxy","Xperia","Lumia"]'::jsonb),
  ('Spartalı savaşçı Kratos hangi oyun serisinin ana karakteridir?', 'The Spartan warrior Kratos is the lead character of which game series?', '["God of War","Devil May Cry","Dark Souls","Diablo"]'::jsonb),
  ('Windows''ta açık pencereler arasında geçiş yapmayı sağlayan kısayol hangisidir?', 'In Windows, which shortcut lets you switch between open windows?', '["Alt+Tab","Alt+F4","Ctrl+Esc","Shift+Tab"]'::jsonb),
  ('''GTA: San Andreas'' oyununun başkarakteri kimdir?', 'Who is the main character of GTA: San Andreas?', '["Carl Johnson","Tommy Vercetti","Niko Bellic","Claude Speed"]'::jsonb),
  ('Popüler oyun Fortnite''ı geliştiren şirket hangisidir?', 'Which company developed the hit game Fortnite?', '["Epic Games","Riot Games","Blizzard","Activision"]'::jsonb),
  ('Apple''ın Super Bowl''da yayınlanan ünlü ''1984'' Macintosh reklamını kim yönetti?', 'Who directed Apple''s famous ''1984'' Macintosh ad that aired during the Super Bowl?', '["Ridley Scott","David Fincher","James Cameron","Steven Spielberg"]'::jsonb),
  ('Halo serisinin ilk oyunlarını geliştiren stüdyo hangisidir?', 'Which studio developed the original Halo games?', '["Bungie","Valve","Epic Games","id Software"]'::jsonb),
  ('Tetris''in akılda kalan müziği hangi Rus halk şarkısına dayanır?', 'The famous Tetris theme is based on which Russian folk song?', '["Korobeiniki","Kalinka","Katyusha","Moscow Nights"]'::jsonb),
  ('Klasik Donkey Kong oyununda goril tarafından kaçırılan kadının adı nedir?', 'In the classic Donkey Kong arcade game, what is the name of the woman kidnapped by the ape?', '["Pauline","Peach","Daisy","Rosalina"]'::jsonb),
  ('Tesla''nın seri olarak ürettiği ilk otomobil modeli hangisidir?', 'What was the first production car made by Tesla?', '["Roadster","Model S","Model X","Model 3"]'::jsonb),
  ('Mortal Kombat''ta zıpkınını fırlatıp ''Get over here!'' diye bağıran ninja kimdir?', 'Which Mortal Kombat ninja throws his spear and yells ''Get over here!''?', '["Scorpion","Sub-Zero","Raiden","Liu Kang"]'::jsonb),
  ('Nintendo 19. yüzyılda kurulduğunda hangi ürünü üretiyordu?', 'What did Nintendo make when it was founded in the 19th century?', '["Playing cards","Toy trains","Typewriters","Cameras"]'::jsonb),
  ('Mobil oyun Flappy Bird''ü yaratan geliştirici Dong Nguyen hangi ülkedendir?', 'Flappy Bird creator Dong Nguyen is from which country?', '["Vietnam","Thailand","Indonesia","Philippines"]'::jsonb),
  ('Pokédex''te 1 numaralı Pokémon hangisidir?', 'Which Pokemon is number 1 in the Pokedex?', '["Bulbasaur","Charmander","Squirtle","Mew"]'::jsonb),
  ('Minecraft''ı geliştiren İsveçli oyun stüdyosu hangisidir?', 'Which Swedish game studio developed Minecraft?', '["Mojang","Rovio","Supercell","King"]'::jsonb),
  ('WhatsApp''ı Brian Acton ile birlikte kuran kişi kimdir?', 'Who co-founded WhatsApp with Brian Acton?', '["Jan Koum","Kevin Systrom","Pavel Durov","Evan Spiegel"]'::jsonb),
  ('Skype yazılımı ilk olarak hangi ülkedeki mühendislerce geliştirildi?', 'Skype''s software was originally built by engineers in which country?', '["Estonia","Finland","Latvia","Lithuania"]'::jsonb),
  ('Harry Kane 2023''te Tottenham''dan ayrılarak hangi kulübe transfer oldu?', 'Which club did Harry Kane join when he left Tottenham in 2023?', '["Bayern Munich","Real Madrid","Manchester City","PSG"]'::jsonb),
  ('Golden State''in ''Splash Brothers'' ikilisinde Stephen Curry''nin partneri kimdir?', 'Who is Stephen Curry''s partner in Golden State''s ''Splash Brothers'' duo?', '["Klay Thompson","Kevin Durant","Draymond Green","Andre Iguodala"]'::jsonb),
  ('Efsanevi golcü Didier Drogba hangi ülkenin milli takımında oynamıştır?', 'Striker Didier Drogba played international football for which country?', '["Ivory Coast","Ghana","Burkina Faso","DR Congo"]'::jsonb),
  ('Çinli basketbolcu Yao Ming NBA''de hangi takımın formasını giymiştir?', 'Chinese basketball star Yao Ming played for which NBA team?', '["Houston Rockets","Los Angeles Clippers","Denver Nuggets","Dallas Mavericks"]'::jsonb),
  ('1997''de Garry Kasparov''u maçta yenen IBM satranç bilgisayarının adı nedir?', 'What was the name of the IBM chess computer that beat Garry Kasparov in a 1997 match?', '["Deep Blue","Blue Gene","Big Blue","Watson"]'::jsonb),
  ('Muhammad Ali''nin ünlü sözüne göre o kelebek gibi uçar, neyin gibi sokar?', 'Muhammad Ali famously said he could float like a butterfly and sting like a what?', '["Bee","Scorpion","Snake","Mosquito"]'::jsonb),
  ('2014 Dünya Kupası''nda İtalyan Chiellini''yi ısıran Uruguaylı forvet kimdir?', 'Which Uruguayan striker bit Italy''s Giorgio Chiellini at the 2014 World Cup?', '["Luis Suarez","Edinson Cavani","Diego Forlan","Sebastian Abreu"]'::jsonb),
  ('Buz hokeyi efsanesi Wayne Gretzky hangi ülkelidir?', 'Which country does ice hockey legend Wayne Gretzky come from?', '["Canada","USA","Sweden","Finland"]'::jsonb),
  ('Lakers''ta Kobe Bryant''la üst üste üç NBA şampiyonluğu kazanan pivot kimdir?', 'Which center won three straight NBA titles alongside Kobe Bryant with the Lakers?', '["Shaquille O''Neal","Kareem Abdul-Jabbar","Dikembe Mutombo","Patrick Ewing"]'::jsonb),
  ('Larry Bird NBA kariyerinin tamamını hangi takımda geçirmiştir?', 'Larry Bird spent his entire NBA career with which team?', '["Boston Celtics","Los Angeles Lakers","Detroit Pistons","New York Knicks"]'::jsonb),
  ('Sebastian Vettel dört F1 dünya şampiyonluğunu hangi takımla kazandı?', 'With which team did Sebastian Vettel win his four F1 world titles?', '["Red Bull","Aston Martin","Toro Rosso","Ferrari"]'::jsonb),
  ('Neymar 2017''de rekor bir bonservisle Barcelona''dan hangi kulübe transfer oldu?', 'Neymar left Barcelona in 2017 for a world-record fee to join which club?', '["PSG","Juventus","Chelsea","Bayern Munich"]'::jsonb),
  ('2010 Dünya Kupası finalinde İspanya''ya kupayı getiren golü kim attı?', 'Who scored the winning goal for Spain in the 2010 World Cup final?', '["Andres Iniesta","Xavi Hernandez","David Villa","Fernando Torres"]'::jsonb),
  ('Cristiano Ronaldo Manchester United''dan ayrılınca hangi Suudi kulübüne geçti?', 'Which Saudi club did Cristiano Ronaldo join after leaving Manchester United?', '["Al-Nassr","Al-Hilal","Al-Ittihad","Al-Ahli"]'::jsonb),
  ('NHL''de sezonun şampiyonu olan takıma verilen kupanın adı nedir?', 'What trophy is awarded to the NHL champions each season?', '["The Stanley Cup","The Calder Cup","The Davis Cup","The Ryder Cup"]'::jsonb),
  ('Motosiklet yarışçısı Valentino Rossi hangi lakapla tanınır?', 'By what nickname is motorcycle racer Valentino Rossi known?', '["The Doctor","The Professor","The Captain","The Baron"]'::jsonb),
  ('''Herminator'' lakaplı alp disiplini kayakçısı Hermann Maier hangi ülkelidir?', 'Which country does alpine skier Hermann ''The Herminator'' Maier come from?', '["Austria","Switzerland","Germany","Norway"]'::jsonb),
  ('Fernando Alonso iki F1 dünya şampiyonluğunu hangi takımla kazandı?', 'With which team did Fernando Alonso win both of his F1 world titles?', '["Renault","Ferrari","McLaren","Williams"]'::jsonb),
  ('Yüzücü Michael Phelps ABD''nin hangi şehrinde doğmuştur?', 'In which US city was swimmer Michael Phelps born?', '["Baltimore","Boston","Denver","Seattle"]'::jsonb),
  ('Lionel Messi Arjantin''in hangi şehrinde doğmuştur?', 'In which Argentine city was Lionel Messi born?', '["Rosario","Cordoba","Mendoza","La Plata"]'::jsonb),
  ('Michael Jordan NBA''de son olarak hangi takımın formasını giydi?', 'Which team did Michael Jordan play for in the final seasons of his NBA career?', '["Washington Wizards","Charlotte Hornets","Atlanta Hawks","Cleveland Cavaliers"]'::jsonb),
  ('2006 Dünya Kupası finalinde İtalya''ya kupayı getiren son penaltıyı kim attı?', 'Who scored the decisive penalty that won Italy the 2006 World Cup final shootout?', '["Fabio Grosso","Andrea Pirlo","Marco Materazzi","Alessandro Del Piero"]'::jsonb),
  ('1994''te Tonya Harding''in çevresince dizine saldırı düzenlenen patinajcı kimdir?', 'Which figure skater was attacked in 1994 in a plot linked to Tonya Harding?', '["Nancy Kerrigan","Kristi Yamaguchi","Michelle Kwan","Oksana Baiul"]'::jsonb),
  ('1986''da felakete sahne olan Çernobil nükleer santrali bugün hangi ülkenin sınırları içindedir?', 'The Chernobyl nuclear plant, site of the 1986 disaster, is located in which present-day country?', '["Ukraine","Belarus","Russia","Lithuania"]'::jsonb),
  ('Sovyet lideri Josef Stalin bugün hangi ülkenin toprakları içinde kalan bir kasabada doğdu?', 'Soviet leader Joseph Stalin was born in a town that lies in which present-day country?', '["Georgia","Armenia","Ukraine","Azerbaijan"]'::jsonb),
  ('Lenin takma adıyla tanınan Bolşevik liderin asıl soyadı nedir?', 'The Bolshevik leader known as Lenin was born with what surname?', '["Ulyanov","Dzhugashvili","Bronstein","Skryabin"]'::jsonb),
  ('''Titanik'' filmindeki ünlü mavi elmas kolyenin adı nedir?', 'In ''Titanic'', what is the famous blue diamond necklace called?', '["Heart of the Ocean","Star of the Sea","Blue Teardrop","Queen''s Eye"]'::jsonb),
  ('''Dövüş Kulübü''nde isimsiz anlatıcıyı canlandıran oyuncu kimdir?', 'Who played the unnamed narrator in ''Fight Club''?', '["Edward Norton","Matt Damon","Jared Leto","Ethan Hawke"]'::jsonb),
  ('''Küçük Deniz Kızı''nda Ariel''e göz kulak olan yengecin adı nedir?', 'In ''The Little Mermaid'', what is the name of the crab who looks after Ariel?', '["Sebastian","Flounder","Scuttle","Triton"]'::jsonb),
  ('''Yaralı Yüz'' (1983) filminde Tony Montana''yı canlandıran oyuncu kimdir?', 'Who played Tony Montana in ''Scarface'' (1983)?', '["Al Pacino","Robert De Niro","Andy Garcia","Joe Pesci"]'::jsonb),
  ('''Shrek 2''de Çizmeli Kedi''yi seslendiren oyuncu kimdir?', 'Who voices Puss in Boots in ''Shrek 2''?', '["Antonio Banderas","Javier Bardem","Andy Garcia","Benicio del Toro"]'::jsonb),
  ('''Zootropolis''te Judy Hopps''a yardım eden Nick Wilde hangi hayvandır?', 'In ''Zootopia'', what kind of animal is Nick Wilde?', '["Fox","Wolf","Raccoon","Weasel"]'::jsonb),
  ('''Yıldızlararası'' filminde pilot Cooper''ı canlandıran oyuncu kimdir?', 'Who played the pilot Cooper in ''Interstellar''?', '["M. McConaughey","Christian Bale","Jake Gyllenhaal","Ryan Gosling"]'::jsonb),
  ('''Esaretin Bedeli''nde Red karakterini canlandıran oyuncu kimdir?', 'Who played Red in ''The Shawshank Redemption''?', '["Morgan Freeman","Denzel Washington","Danny Glover","Samuel L. Jackson"]'::jsonb),
  ('''Harry Potter'' filmlerinde Lord Voldemort''u canlandıran oyuncu kimdir?', 'Who played Lord Voldemort in the ''Harry Potter'' films?', '["Ralph Fiennes","Gary Oldman","Jason Isaacs","Kenneth Branagh"]'::jsonb),
  ('''Diriliş'' (The Revenant) filminde Hugh Glass''a hangi hayvan saldırır?', 'In ''The Revenant'', what animal mauls Hugh Glass?', '["Bear","Wolf","Cougar","Bison"]'::jsonb),
  ('''Baba'' (1972) filminde Vito Corleone''yi canlandıran oyuncu kimdir?', 'Who played Vito Corleone in ''The Godfather'' (1972)?', '["Marlon Brando","Al Pacino","James Caan","Robert Duvall"]'::jsonb),
  ('''Ucuz Roman'' filminde Mia Wallace''ı canlandıran oyuncu kimdir?', 'Who played Mia Wallace in ''Pulp Fiction''?', '["Uma Thurman","Bridget Fonda","Rosanna Arquette","Juliette Lewis"]'::jsonb),
  ('''Siyah Giyen Adamlar''da tanıkların hafızasını silen cihazın adı nedir?', 'In ''Men in Black'', what is the device that wipes witnesses'' memories called?', '["Neuralyzer","Tricorder","Flux Capacitor","Portal Gun"]'::jsonb),
  ('Pixar''ın ''Yukarı Bak'' filminde konuşan tasma takan köpeğin adı nedir?', 'In Pixar''s ''Up'', what is the name of the dog with the talking collar?', '["Dug","Rex","Max","Bolt"]'::jsonb),
  ('''Dirty Dancing'' filminde ''Baby'' lakaplı kahramanın gerçek adı nedir?', 'In ''Dirty Dancing'', what is the real first name of the heroine nicknamed Baby?', '["Frances","Penny","Lisa","Margaret"]'::jsonb),
  ('''RoboCop'' (1987) filmi hangi ABD şehrinde geçer?', 'In which US city is ''RoboCop'' (1987) set?', '["Detroit","Chicago","Cleveland","Pittsburgh"]'::jsonb),
  ('''Avengers: Sonsuzluk Savaşı''nda Thanos''u canlandıran oyuncu kimdir?', 'Who played Thanos in ''Avengers: Infinity War''?', '["Josh Brolin","Mickey Rourke","Michael Shannon","Jeff Bridges"]'::jsonb),
  ('''Şeytan'' (The Exorcist) filminde içine şeytan giren kızın adı nedir?', 'In ''The Exorcist'', what is the name of the possessed girl?', '["Regan","Carrie","Samara","Wednesday"]'::jsonb),
  ('Çizgi filmlerde sarı kanarya Tweety''yi kovalayan kedinin adı nedir?', 'In the cartoons, what is the name of the cat who is always chasing Tweety?', '["Sylvester","Tom","Heathcliff","Felix"]'::jsonb),
  ('''Breaking Bad''de Walter White''ın uyuşturucu dünyasında kullandığı takma ad nedir?', 'In ''Breaking Bad'', what alias does Walter White use in the drug world?', '["Heisenberg","Schrodinger","Einstein","Oppenheimer"]'::jsonb),
  ('''Pembe Panter'' filmlerindeki beceriksiz Fransız müfettişin soyadı nedir?', 'What is the surname of the bumbling French inspector in ''The Pink Panther'' films?', '["Clouseau","Maigret","Columbo","Gadget"]'::jsonb),
  ('''Çığlık'' tablosunun ressamı Edvard Munch hangi ülkelidir?', 'Edvard Munch, the painter of ''The Scream'', came from which country?', '["Norway","Sweden","Denmark","Finland"]'::jsonb),
  ('''Star Wars''ta Darth Vader''ın karanlık tarafa geçmeden önceki ilk adı nedir?', 'In ''Star Wars'', what was Darth Vader''s first name before he turned to the dark side?', '["Anakin","Luke","Owen","Ben"]'::jsonb),
  ('Deniz kabuğu üzerinde duran tanrıçayı betimleyen ''Venüs''ün Doğuşu'' kimin eseridir?', 'Who painted ''The Birth of Venus''?', '["Botticelli","Raphael","Titian","Caravaggio"]'::jsonb),
  ('1971 tarihli ''Imagine'' şarkısını hangi eski Beatles üyesi yazıp seslendirmiştir?', 'Which former Beatle wrote and sang the 1971 song ''Imagine''?', '["John Lennon","Paul McCartney","George Harrison","Ringo Starr"]'::jsonb),
  ('''Purple Rain'' albümü ve filmiyle tanınan Amerikalı müzisyen kimdir?', 'Which American musician is famous for the album and film ''Purple Rain''?', '["Prince","David Bowie","Stevie Wonder","Lionel Richie"]'::jsonb),
  ('Rivayete göre Kleopatra hangi hayvanın ısırığıyla ölmüştür?', 'According to legend, the bite of which creature killed Cleopatra?', '["Snake","Scorpion","Spider","Crocodile"]'::jsonb),
  ('''Çakmaktaş Ailesi''nde Fred Çakmaktaş''ın eşinin adı nedir?', 'In ''The Flintstones'', what is the name of Fred''s wife?', '["Wilma","Betty","Pebbles","Marge"]'::jsonb),
  ('''Star Trek''te Kaptan Kirk''ün komuta ettiği yıldız gemisinin adı nedir?', 'In ''Star Trek'', what is the name of the starship commanded by Captain Kirk?', '["Enterprise","Nostromo","Serenity","Galactica"]'::jsonb),
  ('Cervantes''in ''Don Kişot'' romanında kahramanın sadık yaverinin adı nedir?', 'In Cervantes'' ''Don Quixote'', what is the name of the hero''s loyal squire?', '["Sancho Panza","Lazarillo","Gil Blas","Rodrigo Diaz"]'::jsonb),
  ('Kahve zinciri Starbucks ilk mağazasını hangi ABD şehrinde açmıştır?', 'In which US city did Starbucks open its very first store?', '["Seattle","Portland","Chicago","Boston"]'::jsonb),
  ('Barselona''daki Sagrada Família bazilikasının mimarı kimdir?', 'Which architect designed the Sagrada Familia in Barcelona?', '["Antoni Gaudi","Le Corbusier","Frank Gehry","Santiago Calatrava"]'::jsonb),
  ('Kont Drakula''nın yurdu Transilvanya bölgesi bugün hangi ülkededir?', 'Transylvania, home of Count Dracula, is a region of which present-day country?', '["Romania","Hungary","Bulgaria","Serbia"]'::jsonb),
  ('The Beatles üyelerinin yaya geçidinde yürüdüğü ünlü kapak hangi albümlerine aittir?', 'Which Beatles album cover shows the band walking across a zebra crossing?', '["Abbey Road","Let It Be","Revolver","Help!"]'::jsonb),
  ('Sherlock Holmes''un ünlü 221B numaralı evi Londra''nın hangi caddesindedir?', 'On which London street is Sherlock Holmes''s famous address 221B?', '["Baker Street","Abbey Road","Oxford Street","Fleet Street"]'::jsonb),
  ('1975 yapımı köpekbalığı filmi ''Jaws''un yönetmeni kimdir?', 'Who directed the 1975 shark thriller Jaws?', '["Spielberg","Lucas","Scorsese","Coppola"]'::jsonb),
  ('ABD dizisi ''The Office''te Michael Scott''ın çalıştığı kâğıt şirketinin adı nedir?', 'In the US version of ''The Office'', what paper company does Michael Scott work for?', '["Dunder Mifflin","Initech","Sterling Cooper","Pied Piper"]'::jsonb),
  ('Efsanevi sprinter Usain Bolt hangi ülkelidir?', 'Which country does legendary sprinter Usain Bolt come from?', '["Jamaica","The Bahamas","Barbados","Trinidad and Tobago"]'::jsonb),
  ('Video oyunu Tetris ilk olarak hangi şehirde geliştirilmiştir?', 'In which city was the video game Tetris originally created?', '["Moscow","Tokyo","Helsinki","Seattle"]'::jsonb),
  ('Çizgi film kahramanı Scooby-Doo hangi köpek ırkındandır?', 'What breed of dog is the cartoon character Scooby-Doo?', '["Great Dane","St. Bernard","Doberman","Boxer"]'::jsonb),
  ('''Moby Dick'' romanında beyaz balinanın peşine düşen kaptanın adı nedir?', 'In ''Moby-Dick'', what is the name of the captain obsessed with the white whale?', '["Ahab","Nemo","Flint","Hook"]'::jsonb),
  ('Apollo 11''de Neil Armstrong''dan sonra Ay''a ayak basan astronot kimdir?', 'On Apollo 11, who walked on the Moon right after Neil Armstrong?', '["Buzz Aldrin","Michael Collins","John Glenn","Alan Shepard"]'::jsonb),
  ('Ninja Kaplumbağalar''ın mavi bantlı lideri hangisidir?', 'Which Teenage Mutant Ninja Turtle wears the blue mask and leads the team?', '["Leonardo","Raphael","Donatello","Michelangelo"]'::jsonb),
  ('''Casablanca'' filminde Rick''in barında piyano çalan karakterin adı nedir?', 'In ''Casablanca'', what is the name of the piano player at Rick''s cafe?', '["Sam","Louis","Victor","Carl"]'::jsonb),
  ('Burnu yalan söyledikçe uzayan Pinokyo''nun yazarı kimdir?', 'Who wrote ''The Adventures of Pinocchio''?', '["Carlo Collodi","Gianni Rodari","Italo Calvino","Umberto Eco"]'::jsonb),
  ('''Küçük Prens''in yazarı Antoine de Saint-Exupéry''nin asıl mesleği neydi?', 'What was the main profession of ''The Little Prince'' author Antoine de Saint-Exupery?', '["Pilot","Doctor","Teacher","Lawyer"]'::jsonb),
  ('Orwell''in ''Hayvan Çiftliği''nde iktidarı ele geçiren diktatör domuzun adı nedir?', 'In Orwell''s ''Animal Farm'', what is the name of the pig who becomes the farm''s dictator?', '["Napoleon","Snowball","Squealer","Old Major"]'::jsonb),
  ('''Game of Thrones''ta Jon Snow''un dire kurdunun adı nedir?', 'In Game of Thrones, what is the name of Jon Snow''s direwolf?', '["Ghost","Nymeria","Summer","Grey Wind"]'::jsonb),
  ('Monet''nin nilüfer tablolarına ilham veren bahçesi hangi Fransız köyündedir?', 'In which French village is the garden that inspired Monet''s Water Lilies?', '["Giverny","Arles","Barbizon","Honfleur"]'::jsonb),
  ('''Yurttaş Kane'' filminde Kane''in ölürken söylediği son sözcük nedir?', 'In Citizen Kane, what is Kane''s dying word?', '["Rosebud","Xanadu","Mayflower","Moonlight"]'::jsonb),
  ('Agatha Christie''nin dedektifi Hercule Poirot hangi ülkelidir?', 'Agatha Christie''s detective Hercule Poirot comes from which country?', '["Belgium","France","Switzerland","Luxembourg"]'::jsonb),
  ('Sherlock Holmes''un Baker Street''teki evinin sahibesi olan kadın kimdir?', 'Who is Sherlock Holmes''s landlady at Baker Street?', '["Mrs. Hudson","Mrs. Hughes","Mrs. Turner","Mrs. Brown"]'::jsonb),
  ('Oscar Wilde''ın romanında Dorian Gray hiç yaşlanmazken onun yerine ne yaşlanır?', 'In Oscar Wilde''s novel, Dorian Gray never ages. What ages in his place?', '["His portrait","His mirror","His statue","His shadow"]'::jsonb),
  ('''Jane Eyre''de Jane''in mürebbiye olarak çalıştığı Thornfield Konağı''nın sahibi kimdir?', 'In ''Jane Eyre'', who is the master of Thornfield Hall, where Jane works as a governess?', '["Rochester","Darcy","Heathcliff","Knightley"]'::jsonb),
  ('Shakespeare''in ''Hamlet'' oyununda derede boğularak ölen genç kız kimdir?', 'In Shakespeare''s ''Hamlet'', which young woman dies by drowning in a brook?', '["Ophelia","Desdemona","Cordelia","Portia"]'::jsonb),
  ('''Oz Büyücüsü''nde Dorothy kasırgayla hangi ABD eyaletinden Oz''a savrulur?', 'In The Wonderful Wizard of Oz, which US state is Dorothy swept away from?', '["Kansas","Nebraska","Oklahoma","Iowa"]'::jsonb),
  ('Roald Dahl''ın ''Charlie''nin Çikolata Fabrikası'' kitabında Charlie''nin soyadı nedir?', 'In Roald Dahl''s ''Charlie and the Chocolate Factory'', what is Charlie''s surname?', '["Bucket","Salt","Gloop","Teavee"]'::jsonb),
  ('''Harry Potter'' serisinde Harry, Gryffindor Quidditch takımında hangi mevkide oynar?', 'In the ''Harry Potter'' series, what position does Harry play on the Gryffindor Quidditch team?', '["Seeker","Beater","Chaser","Keeper"]'::jsonb),
  ('''Üç Silahşörler''de Athos ve Porthos''un yanındaki üçüncü silahşör kimdir?', 'In ''The Three Musketeers'', who is the third musketeer alongside Athos and Porthos?', '["Aramis","Rochefort","Treville","Planchet"]'::jsonb),
  ('''Winnie the Pooh'' kitaplarında Pooh''un kasvetli eşek arkadaşının adı nedir?', 'In the Winnie-the-Pooh books, what is the name of Pooh''s gloomy donkey friend?', '["Eeyore","Tigger","Piglet","Kanga"]'::jsonb),
  ('''Muhteşem Gatsby''de Gatsby''nin yıllardır sevdiği kadının adı nedir?', 'In The Great Gatsby, what is the name of the woman Gatsby has loved for years?', '["Daisy","Myrtle","Jordan","Rosie"]'::jsonb),
  ('''Alice Harikalar Diyarında''da durmadan ''Kafasını uçurun!'' diye bağıran karakter kimdir?', 'In ''Alice''s Adventures in Wonderland'', which character keeps shouting ''Off with her head!''?', '["The Queen of Hearts","The Queen of Spades","The Queen of Diamonds","The Queen of Clubs"]'::jsonb),
  ('Kafka''nın ''Dönüşüm''ünde bir sabah böceğe dönüşmüş olarak uyanan kahramanın adı nedir?', 'In Kafka''s The Metamorphosis, what is the first name of the man who wakes up as an insect?', '["Gregor","Josef","Karl","Franz"]'::jsonb),
  ('Bram Stoker''ın ''Dracula'' romanında Jonathan Harker''ın nişanlısının adı nedir?', 'In Bram Stoker''s ''Dracula'', what is the name of Jonathan Harker''s fiancée?', '["Mina","Lucy","Ilona","Clara"]'::jsonb),
  ('Stoker''ın ''Dracula''sında kontun gemisi İngiltere''de hangi liman kasabasına varır?', 'In Bram Stoker''s Dracula, at which English port town does the Count''s ship run aground?', '["Whitby","Dover","Brighton","Plymouth"]'::jsonb),
  ('Victor Hugo''nun ''Sefiller'' romanında Cosette''in annesinin adı nedir?', 'In Victor Hugo''s ''Les Misérables'', what is the name of Cosette''s mother?', '["Fantine","Éponine","Colette","Odette"]'::jsonb),
  ('Tolkien''in ''Hobbit'' romanında Bilbo''nun katıldığı cüce grubunun lideri kimdir?', 'In Tolkien''s ''The Hobbit'', who leads the company of dwarves that Bilbo joins?', '["Thorin","Balin","Gimli","Dwalin"]'::jsonb),
  ('Bradbury''nin ''Fahrenheit 451'' romanının itfaiyeci kahramanının soyadı nedir?', 'In Bradbury''s ''Fahrenheit 451'', what is the surname of the fireman protagonist?', '["Montag","Beatty","Faber","Granger"]'::jsonb)
  ) v(soru, en_soru, en_secenekler)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Çevrilmeyenler
insert into public.ceviri_atlanan (question_id, dil, neden, kod)
select q.id, 'en', v.neden, 'cevrilemez'
  from (values
  ('''Sanat Güneşi'' lakabıyla anılan şarkıcı kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''İstanbul''da Sonbahar'' şarkısının sahibi kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Bu Akşam'' ve ''Senden Daha Güzel'' şarkıları hangi grubundur?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Sil Baştan'' şarkısıyla tanınan rock şarkıcısı kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Türkiye''de geliştirilen mesajlaşma uygulaması BiP hangi şirkete aittir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Eşkıya'' filminde Baran''ın İstanbul''da tanıştığı Cumali''yi kim canlandırır?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Babam ve Oğlum'' filminde baba Hüseyin Efendi''yi canlandıran oyuncu kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Hababam Sınıfı'' filmlerinde olayların geçtiği okulun adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Reşat Nuri Güntekin''in ''Çalıkuşu'' romanının baş kahramanının adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Kemal Sunal''ın ''Hababam Sınıfı'' filmlerinde canlandırdığı karakter kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Orhan Pamuk''un ''Masumiyet Müzesi'' romanının baş erkek karakterinin adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Halit Ziya''nın ''Aşk-ı Memnu'' romanında Adnan Bey''le evlenen genç kadın kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('''Kürk Mantolu Madonna''da Raif Efendi''nin Berlin''de âşık olduğu ressamın adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Yaşar Kemal''in ''İnce Memed'' romanında Memed''in sevdiği kızın adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Orhan Pamuk''un ''Masumiyet Müzesi''nde Kemal''in tutkuyla bağlandığı uzak akrabası kimdir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız'),
  ('Halide Edib''in ''Sinekli Bakkal'' romanının kahramanı olan genç kızın adı nedir?', 'Yerel TR sorusu (kapsam=yerel); İngilizce oyuncu için anlamsız')
  ) v(soru, neden)
  join public.questions q on q.soru = v.soru and q.created_at >= transaction_timestamp()
on conflict (question_id, dil) do nothing;

-- ---------------------------------------------------- Karıştırma (TR + EN aynı permütasyon)
drop table if exists pg_temp._parti_karistir;
create temp table _parti_karistir as
select q.id, array_agg(s.idx order by s.rnd) as perm
  from public.questions q
  cross join lateral (
    select (ordinality - 1)::int as idx, random() as rnd
      from jsonb_array_elements(q.secenekler) with ordinality
  ) s
 where q.created_at >= transaction_timestamp()
 group by q.id;

update public.questions q
   set secenekler = (select jsonb_agg(q.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o)),
       dogru_cevap = (array_position(k.perm, q.dogru_cevap::int) - 1)::smallint
  from _parti_karistir k
 where q.id = k.id;

update public.question_translations t
   set secenekler = (select jsonb_agg(t.secenekler -> u.p order by u.o)
                       from unnest(k.perm) with ordinality u(p, o))
  from _parti_karistir k
 where t.question_id = k.id;

drop table if exists pg_temp._parti_karistir;
