-- ============================================================
-- 001 — Şık ipucu düzeltmesi, parti 5 (8 Eki 2026, Claude API)
--
-- 298'de Jev'in soru metnini görmeden doğru şıkkı > 0,8 güvenle bulduğu sorular
-- `sik_ipucu_jev` ile işaretlenip rekabetçi havuzdan çıkarılmıştı. Bu partide işaretli kolay/orta
-- (zorluk 1–3) sorulardan 43 tanesinin YANLIŞ şıkları Claude API (claude-sonnet-5-5) ile yeniden yazıldı;
-- soru metni, doğru cevap ve doğru şıkkın indeksi DEĞİŞMEDİ (match_answers.cevap indeksle tutulur, şık sırası karışmaz).
-- Yeni şıklar dört kapıdan geçti: soru_kural_isaretleri (ağırlık >= 2 işaret yok), Jev "soru olmadan"
-- testi (soru_denetim/kapi.mjs › sikIpucuTesti, doğru şıkka <= 0.75), Jev tek doğru cevap kontrolü ve
-- yanlış şık başına ayrı Claude hakem çağrısı (kesin_yanlis). Geçemeyen sorulara dokunulmadı, işaretli kalır.
-- EN çeviri: aynı indekslerle güncellenir (EN çevirisi olmayan soruda yalnız TR). Üretici: araclar/soru-temizlik/sik-ipucu-api.mjs --tam
-- Eski hâl: soru_surum (surum +1) ve araclar/soru-temizlik/sik-ipucu-duzeltme.csv.
-- Geri alma: node araclar/soru-temizlik/sik-ipucu-geri-al.mjs --parti 5   (önce prova)
-- ============================================================

-- Elle işaret (sik_ipucu_jev) tetikleyicide korunur; bilerek kaldırmak için (298):
select set_config('app.soru_elle_isaret_yaz', 'on', true);

create temp table _j_sik (id uuid primary key, dogru smallint, eski_tr jsonb, yeni_tr jsonb, eski_en jsonb, yeni_en jsonb) on commit drop;
insert into _j_sik values
    ('59b56693-5156-478b-af2a-551a5b16c37f'::uuid, 2, '["Her pozisyonda","Yalnız faullerde","Belirlenmiş kritik durumlarda","Yalnız kartlarda"]'::jsonb, '["Her pozisyonda","Yalnız oyuncu değişikliklerinde","Belirlenmiş kritik durumlarda","Yalnız taç atışlarında"]'::jsonb, '["On every incident","Only on fouls","Only in defined critical situations","Only on cards"]'::jsonb, '["On every incident","Only on substitutions","Only in defined critical situations","Only on throw-ins"]'::jsonb),
    ('f7e0d0d5-77f2-4537-a595-5dec85524b0c'::uuid, 2, '["Düz görüntü","Basılı eser","Çevreleyen deneyim","Ses yalnızca"]'::jsonb, '["Hareketsiz tablo","Dokunsal heykel","Çevreleyen deneyim","Canlı sahne gösterisi"]'::jsonb, '["A flat image","A printed work","An enveloping experience","Sound only"]'::jsonb, '["A motionless painting","A tactile sculpture","An enveloping experience","A live stage show"]'::jsonb),
    ('1c615d49-c408-4a3a-81f9-db1758fe57d2'::uuid, 1, '["Jenerik yazısı","Söylenmeyen ama sezilen anlam","Altyazı","Dipnot"]'::jsonb, '["Diyaloglardaki açık anlatım","Söylenmeyen ama sezilen anlam","Sahnenin görsel kompozisyonu","Karakterin iç sesle yaptığı anlatım"]'::jsonb, '["The credit titles","Meaning that is unspoken but sensed","Subtitles","A footnote"]'::jsonb, '["Explicit explanation in the dialogue","Meaning that is unspoken but sensed","The visual composition of a scene","A character''s narration in voice-over"]'::jsonb),
    ('782f09d3-3e5d-4939-9e02-aae91692bbe8'::uuid, 1, '["İki","Dört","Altı","Sekiz"]'::jsonb, '["İki","Dört","Yedi","On"]'::jsonb, '["Two","Four","Six","Eight"]'::jsonb, '["Two","Four","Seven","Ten"]'::jsonb),
    ('03f438d1-e7b0-49ee-9120-6ba07e0ac129'::uuid, 3, '["Doğa manzarası","Reklam imgeleri","Belgesel fotoğraf","Optik yanılsama"]'::jsonb, '["Soyut duygu dışavurumu","Gündelik tüketim nesneleri","Geometrik kübik parçalanma","Optik yanılsama"]'::jsonb, '["Landscapes of nature","Advertising imagery","Documentary photography","Optical illusion"]'::jsonb, '["Abstract emotional expression","Everyday consumer objects","Geometric cubist fragmentation","Optical illusion"]'::jsonb),
    ('850bcdb3-e241-4a46-92b9-d0888212cf28'::uuid, 0, '["Büyük yapıları küçük modelle göstermek","Ses eklemek","Renk düzenlemek","Kurgu yapmak"]'::jsonb, '["Büyük yapıları küçük modelle göstermek","Oyuncu sahnelerini mekân dışında kaydetmek","Karakterleri bilgisayarda canlandırmak","Sahne geçişlerini görüntü üzerinde birleştirmek"]'::jsonb, '["Showing large structures with a small model","Adding sound","Grading colour","Editing"]'::jsonb, '["Showing large structures with a small model","Recording actor scenes outside the studio","Animating characters on a computer","Joining scene transitions in post-production"]'::jsonb),
    ('e422ddd3-256e-4d20-897e-5fbc3b5a57ba'::uuid, 2, '["Sunucu da","Herkes","Yalnız gönderen ve alan","Servis sağlayıcı"]'::jsonb, '["Gönderen ile sunucu yöneticisi","Alıcının tüm kişi listesi","Yalnız gönderen ve alan","Gönderenle birlikte servis sağlayıcı"]'::jsonb, '["The server too","Everyone","Only the sender and the recipient","The service provider"]'::jsonb, '["The sender and the server administrator","The recipient''s entire contact list","Only the sender and the recipient","The sender along with the service provider"]'::jsonb),
    ('db64de8b-7e45-4cb6-b9fa-76e591b67b4a'::uuid, 2, '["Bronşta","Soluk borusunda","Alveollerde","Gırtlakta"]'::jsonb, '["Bronşiyollerde","Plevra zarında","Alveollerde","Diyaframda"]'::jsonb, '["In the bronchus","In the windpipe","In the alveoli","In the larynx"]'::jsonb, '["In the bronchioles","In the pleural membrane","In the alveoli","In the diaphragm"]'::jsonb),
    ('77b32477-ad8f-463b-8f32-c291b9724424'::uuid, 3, '["Vergi sınırını","Ordu sayısını","Meclis düzenini","Ulusal sınır ve bağımsızlık ilkelerini"]'::jsonb, '["Dış borç ödemelerini ve takvimini","Ticaret yollarını ve gümrük ilkelerini","Anayasal yönetim biçimini ve ilkelerini","Ulusal sınır ve bağımsızlık ilkelerini"]'::jsonb, '["Tax limits","Army size","Parliamentary order","Principles of national borders and independence"]'::jsonb, '["Foreign debt payments and schedules","Trade routes and customs principles","Constitutional form of government and its principles","Principles of national borders and independence"]'::jsonb),
    ('414b54c1-ad50-48d5-af3a-8cd2bca01edb'::uuid, 3, '["Yan yana duran renk","Aynı tonun açığı","Tek renk ailesi","Çemberde karşıt renk"]'::jsonb, '["Çemberde komşu renk","Aynı tonun koyusu","Üç renkli uyum","Çemberde karşıt renk"]'::jsonb, '["A colour placed next to it","A lighter shade of the same tone","A single colour family","The opposite colour on the wheel"]'::jsonb, '["A neighbouring colour on the wheel","A darker shade of the same tone","A three-colour harmony","The opposite colour on the wheel"]'::jsonb),
    ('6d5d8ac1-7aab-4e10-b404-03114bf0b01b'::uuid, 1, '["Volkan riski","Fay hattı üzerinde olması","Buzul riski","Tsunami riski"]'::jsonb, '["Heyelanlı ova üzerinde olması","Fay hattı üzerinde olması","Tuz domu üzerinde olması","Karstik çöküntü alanında olması"]'::jsonb, '["Volcanic risk","Lying on a fault line","Glacial risk","Tsunami risk"]'::jsonb, '["Sitting on a landslide-prone plain","Lying on a fault line","Sitting on a salt dome","Lying in a karst sinkhole area"]'::jsonb),
    ('540991f1-43a0-4c11-bf7d-520ffe33b4e1'::uuid, 0, '["Varoluş ve seçim sorumluluğunu","Doğa betimlemesini","Tarihî olayı","Halk masalını"]'::jsonb, '["Varoluş ve seçim sorumluluğunu","Toplumsal sınıf çatışmasını","Bilinçaltı arzuların çözümlenmesini","Ahlaki değerlerin mutlak üstünlüğünü"]'::jsonb, '["Existence and the responsibility of choice","Descriptions of nature","Historical events","Folk tales"]'::jsonb, '["Existence and the responsibility of choice","Conflict between social classes","The analysis of unconscious desires","The absolute supremacy of moral values"]'::jsonb),
    ('f856f9c7-2dab-479d-ae7c-9ceeed9fd03a'::uuid, 2, '["Tema hiç duyulmaz","Ritim sabit kalır","Tema çeşitlenerek işlenir","Söz eklenir"]'::jsonb, '["Tema tek kez çalınıp biter","Tema her bölümde aynen tekrarlanır","Tema çeşitlenerek işlenir","İki zıt tema karşılıklı işlenir"]'::jsonb, '["The theme is never heard","The rhythm stays fixed","The theme is worked in varied forms","Words are added"]'::jsonb, '["The theme is played once and ends","The theme is repeated unchanged in every section","The theme is worked in varied forms","Two contrasting themes are developed in turn"]'::jsonb),
    ('73943626-c83d-49e6-bd21-1c18fe744d44'::uuid, 3, '["Parmak gücünü","Nefes kapasitesini","Ritim tutmayı yalnızca","Nota okuma ve işitmeyi"]'::jsonb, '["Enstrüman tanıma ve akort bilgisini","Ses telini güçlendirmeyi yalnızca","Beste ve armoni yazmayı","Nota okuma ve işitmeyi"]'::jsonb, '["Finger strength","Lung capacity","Keeping time only","Sight-reading and aural skill"]'::jsonb, '["Instrument recognition and tuning knowledge","Strengthening the vocal cords only","Composing and harmonizing music","Sight-reading and aural skill"]'::jsonb),
    ('9196ed4b-1502-4675-ae2d-53d74aadef19'::uuid, 2, '["Kırmızı olduğu için","Kokulu olduğu için","Renksiz ve kokusuz olduğu için","Ağır olduğu için"]'::jsonb, '["Çok yanıcı bir sıvı olduğu için","Kolayca görülebilen yoğun duman çıkardığı için","Renksiz ve kokusuz olduğu için","Suda hızla çözünüp zehir bıraktığı için"]'::jsonb, '["Because it is red","Because it smells","Because it is colourless and odourless","Because it is heavy"]'::jsonb, '["Because it is a highly flammable liquid","Because it gives off thick, easily visible smoke","Because it is colourless and odourless","Because it dissolves quickly in water and leaves poison"]'::jsonb),
    ('2609c35c-1aa9-4c9f-a400-6bf1eb5b7ec2'::uuid, 3, '["Burgaz","Varna","Filibe","Sofya"]'::jsonb, '["Burgaz","Varna","Filibe","Sofya"]'::jsonb, '["Burgas","Varna","Plovdiv","Sofia"]'::jsonb, '["Burgas","Varna","Plovdiv","Sofia"]'::jsonb),
    ('528ce5cf-f7ce-4175-9a42-1657cb854cd0'::uuid, 1, '["Tarımı azaltmak","Devlet eliyle sanayileşmek","İthalatı artırmak","Göçü durdurmak"]'::jsonb, '["Tarımı azaltmak","Devlet eliyle sanayileşmek","Dış borçları kapatmak","Eğitimi yaygınlaştırmak"]'::jsonb, '["Reducing agriculture","State-led industrialisation","Increasing imports","Stopping migration"]'::jsonb, '["Reducing agriculture","State-led industrialisation","Paying off foreign debts","Expanding education"]'::jsonb),
    ('4cc1b732-9283-4b6f-93ff-9253011253ab'::uuid, 2, '["Bobby Charlton","Roger Hunt","Geoff Hurst","Martin Peters"]'::jsonb, '["Gordon Banks","Nobby Stiles","Geoff Hurst","Jimmy Greaves"]'::jsonb, '["Bobby Charlton","Roger Hunt","Geoff Hurst","Martin Peters"]'::jsonb, '["Gordon Banks","Nobby Stiles","Geoff Hurst","Jimmy Greaves"]'::jsonb),
    ('edb66b39-3d2a-41e0-9f3f-4919939573bb'::uuid, 0, '["Olay aktaran metin türlerini","Yalnız şiiri","Yalnız tiyatroyu","Yalnız denemeyi"]'::jsonb, '["Olay aktaran metin türlerini","Duygu ve coşkuyu dile getiren metinleri","Sahnede oynanmak için yazılan eserleri","Düşünce ve görüşleri savunan yazıları"]'::jsonb, '["Forms that recount events","Poetry only","Theatre only","The essay only"]'::jsonb, '["Forms that recount events","Texts that express emotion and enthusiasm","Works written to be performed on stage","Writings that argue thoughts and opinions"]'::jsonb),
    ('6b369ea3-4cf2-435e-8f4c-0a657f220f58'::uuid, 1, '["Nota yazar","Kanalları dengeler ve birleştirir","Enstrüman akort eder","Konser düzenler"]'::jsonb, '["Sesleri kayda alır","Kanalları dengeler ve birleştirir","Kayıtları son kez masteringler","Mikrofonları yerleştirir"]'::jsonb, '["Writes the notation","Balances and combines the channels","Tunes the instruments","Organises the concert"]'::jsonb, '["Records the sounds","Balances and combines the channels","Finalizes the recordings for release","Positions the microphones"]'::jsonb),
    ('298a98f1-c702-4e81-b7ee-b40f3ec85f07'::uuid, 2, '["Ekran boyutunu","Disk boyutunu","Birim zamanda taşınabilen veri miktarını","Kablo uzunluğunu"]'::jsonb, '["İşlemcinin saniyedeki işlem sayısını","Verinin kaynaktan hedefe ulaşma süresini","Birim zamanda taşınabilen veri miktarını","Bellekte aynı anda tutulabilen veri miktarını"]'::jsonb, '["The screen size","The disk size","The amount of data that can be carried per unit of time","The cable length"]'::jsonb, '["The number of operations a processor performs per second","The time it takes for data to travel from source to destination","The amount of data that can be carried per unit of time","The amount of data that can be held in memory at once"]'::jsonb),
    ('1e5c22a3-b351-435f-aa19-d026dc9f03e9'::uuid, 2, '["Vergi toplamayı","Toprak dağıtmayı","Devlet hizmetine eleman yetiştirmeyi","Ticaret kurmayı"]'::jsonb, '["Orduya sefer erzağı sağlamayı","Mahkemelerde hüküm vermeyi","Devlet hizmetine eleman yetiştirmeyi","Şehirlerde imar işlerini yürütmeyi"]'::jsonb, '["Tax collection","Land distribution","Training personnel for state service","Establishing trade"]'::jsonb, '["Supplying provisions to the army on campaign","Delivering judgments in courts","Training personnel for state service","Carrying out urban construction works"]'::jsonb),
    ('acf984e2-7d3f-4724-8f0a-8e76c9167581'::uuid, 2, '["Kadraj tekniği","Işık düzeni","Bir hikâyenin içinde başka hikâye","Ses efekti"]'::jsonb, '["Bir öyküyü baştan sona tek bir mektupla anlatma","Bir öyküyü ters sırayla anlatma","Bir hikâyenin içinde başka hikâye","Bir öyküyü yalnızca diyaloglarla anlatma"]'::jsonb, '["A framing technique","A lighting set-up","One story told inside another","A sound effect"]'::jsonb, '["Telling a story entirely through a single letter","Telling a story in reverse order","One story told inside another","Telling a story only through dialogue"]'::jsonb),
    ('235f8375-cf29-4f8e-8f8a-f7f69a6653a0'::uuid, 0, '["Bağlantıyı şifreli tünelden geçirmek","İnterneti hızlandırmak","Bellek artırmak","Disk temizlemek"]'::jsonb, '["Bağlantıyı şifreli tünelden geçirmek","Bağlantıyı önbellek sunucusuna yönlendirmek","Ağ cihazlarının sinyalini güçlendirmek","Dosyaları sıkıştırarak depolamak"]'::jsonb, '["Routing the connection through an encrypted tunnel","Speeding up the internet","Increasing memory","Cleaning the disk"]'::jsonb, '["Routing the connection through an encrypted tunnel","Redirecting the connection to a cache server","Boosting the signal of network devices","Compressing files for storage"]'::jsonb),
    ('8425be93-40fd-472c-b850-47a505cc2ecf'::uuid, 2, '["Yağmuru","Bulutu","Radyo dalgası yansımasını","Rüzgarı"]'::jsonb, '["Asit yağmuru oluşumunu","Ozon tabakasının oluşmasını","Radyo dalgası yansımasını","Okyanus akıntılarını"]'::jsonb, '["Rain","Cloud","The reflection of radio waves","Wind"]'::jsonb, '["The formation of acid rain","The formation of the ozone layer","The reflection of radio waves","Ocean currents"]'::jsonb),
    ('e6abf677-ef55-4ae0-a1cc-a715f71dea4b'::uuid, 2, '["Pompa gücüyle","Yağmurla dolarak","Basınçlı yeraltı suyunun yükselmesiyle","Buhar basıncıyla"]'::jsonb, '["Motorlu pompanın emmesiyle","Yağmur suyunun birikmesiyle","Basınçlı yeraltı suyunun yükselmesiyle","Kılcal borularla suyun çekilmesiyle"]'::jsonb, '["By pump power","By filling with rain","By pressurised groundwater rising","By steam pressure"]'::jsonb, '["By motorised pump suction","By rainwater collecting","By pressurised groundwater rising","By water drawn through capillary tubes"]'::jsonb),
    ('114ced14-abf2-4e33-af5c-6331408da9d5'::uuid, 0, '["Toplumsal hatırlamayı taşıyan yer","Yalnızca müze yapılarını","Yalnızca arşiv birimlerini","Yalnızca okul binalarını"]'::jsonb, '["Toplumsal hatırlamayı taşıyan yer","Bir ülkenin resmî sınırlarını belirleyen çizgi","Bir şehrin nüfus kayıtlarının tutulduğu merkez","Bir devletin vergi gelirlerini topladığı bölge"]'::jsonb, '["A place that carries collective remembrance","Only a museum","An archive","A school"]'::jsonb, '["A place that carries collective remembrance","A line that sets a country''s official borders","A center where a city''s population records are kept","A region where a state collects its tax revenue"]'::jsonb),
    ('2ec21c17-dcf5-453c-b840-bc4f989104e6'::uuid, 1, '["Tenniel","Dodgson","Liddell","Kingsley"]'::jsonb, '["Thackeray","Dodgson","Brontë","Hargreaves"]'::jsonb, '["Tenniel","Dodgson","Liddell","Kingsley"]'::jsonb, '["Thackeray","Dodgson","Brontë","Hargreaves"]'::jsonb),
    ('1829a753-86f7-4cbd-90d7-39a58fa69a32'::uuid, 0, '["Ekran boyutuna uyum sağlaması","Yalnız mobil","Yalnız masaüstü","Sabit genişlik"]'::jsonb, '["Ekran boyutuna uyum sağlaması","Sayfanın çok hızlı yüklenmesi","Kullanıcı tıklamalarına ses ile yanıt vermesi","Sunucu yükünü otomatik dengelemesi"]'::jsonb, '["That it adapts to the screen size","Mobile only","Desktop only","Fixed width"]'::jsonb, '["That it adapts to the screen size","That the page loads very quickly","That it responds to user clicks with sound","That it balances server load automatically"]'::jsonb),
    ('c7ac24b2-1ec0-45fc-a4c8-3d172dcf3192'::uuid, 0, '["Kinetik enerji ve momentum","Yalnız kütle","Yalnız hız","Yalnız ısı"]'::jsonb, '["Kinetik enerji ve momentum","Yalnız potansiyel enerji ve sıcaklık","Yalnız kinetik enerji ve ısı","Yalnız kütle ve elektrik yükü"]'::jsonb, '["Kinetic energy and momentum","Mass only","Speed only","Heat only"]'::jsonb, '["Kinetic energy and momentum","Potential energy and temperature only","Kinetic energy and heat only","Mass and electric charge only"]'::jsonb),
    ('31bfeca0-a1aa-4341-b8f3-364625073bfa'::uuid, 0, '["Sivri kemer ve uçan payanda","Yuvarlak kemer","Düz çatı","Kubbe zorunluluğu"]'::jsonb, '["Sivri kemer ve uçan payanda","Yuvarlak kemer ve kalın duvar","Sütunlu portiko ve alınlık","Kubbe ve yarım kubbe sistemi"]'::jsonb, '["The pointed arch and the flying buttress","The round arch","The flat roof","A compulsory dome"]'::jsonb, '["The pointed arch and the flying buttress","The round arch and the thick wall","The columned portico and pediment","The dome and semi-dome system"]'::jsonb),
    ('2bb5ac23-ca37-43a0-a572-cf780c08bb07'::uuid, 1, '["Kurgu ritmini","Mekân, dekor ve genel görsel dünyayı","Ses miksini","Dağıtımı"]'::jsonb, '["Oyuncu seçimi, rol dağılımı ve set kadrosunun yönetimi","Mekân, dekor ve genel görsel dünyayı","Müzik bestesi, ses efekti ve diyalog kaydının düzenlenmesi","Senaryo geliştirme, bütçe planı ve yapımcı anlaşmaları"]'::jsonb, '["The rhythm of the edit","Locations, sets and the overall visual world","The sound mix","Distribution"]'::jsonb, '["Casting, role assignment and management of the crew","Locations, sets and the overall visual world","Music composition, sound effects and dialogue recording","Script development, budget planning and producer deals"]'::jsonb),
    ('2dda3839-ed2f-4058-99b6-6d70ccb913c5'::uuid, 0, '["Bileşenleri birbirine bağlar","Veri saklar","Ekran çizer","Ses üretir"]'::jsonb, '["Bileşenleri birbirine bağlar","Bileşenleri soğutur","Elektrik şebekesini dönüştürür","Ağ trafiğini yönlendirir"]'::jsonb, '["Connects the components to each other","Stores data","Draws the screen","Produces sound"]'::jsonb, '["Connects the components to each other","Cools the components","Converts the mains electricity","Routes network traffic"]'::jsonb),
    ('4491e08c-4b3e-4b45-8fa4-c1841679f1cd'::uuid, 1, '["Yalnız katıda","Boşlukta bile","Yalnız sıvıda","Yalnız gazda"]'::jsonb, '["Yalnız katılarda","Boşlukta bile","Yalnız metallerde","Yalnız akışkanlarda"]'::jsonb, '["In solids only","Even in a vacuum","In liquids only","In gases only"]'::jsonb, '["In solids only","Even in a vacuum","In metals only","In fluids only"]'::jsonb),
    ('810188af-51ca-4dc9-bff2-86f37ea049d6'::uuid, 1, '["Kuzey Nil ve Güney Nil","Beyaz Nil ve Mavi Nil","Doğu Nil ve Batı Nil","Sarı Nil ve Kızıl Nil"]'::jsonb, '["Beyaz Nil ve Kara Nil","Beyaz Nil ve Mavi Nil","Yeşil Nil ve Mavi Nil","Kızıl Nil ve Sarı Nil"]'::jsonb, '["The North Nile and the South Nile","The White Nile and the Blue Nile","The East Nile and the West Nile","The Yellow Nile and the Red Nile"]'::jsonb, '["The White Nile and the Black Nile","The White Nile and the Blue Nile","The Green Nile and the Blue Nile","The Red Nile and the Yellow Nile"]'::jsonb),
    ('96a61ba1-8e91-4de1-95d3-ca03aa79afb2'::uuid, 3, '["Petrarca","Boccaccio","Vergilius","Dante"]'::jsonb, '["Ariosto","Tasso","Vergilius","Dante"]'::jsonb, '["Petrarch","Boccaccio","Virgil","Dante"]'::jsonb, '["Ariosto","Tasso","Virgil","Dante"]'::jsonb),
    ('cb6656b0-276a-4a06-9f01-48025097859e'::uuid, 3, '["Aracı büyütür","Aracı temizler","Aracı boyar","Aracı standarda göre ayarlar"]'::jsonb, '["Aracı standarda göre sökerek parçalara ayırır","Aracı kullanım sonrası steril hale getirir","Aracı yeni bir model ile değiştirir","Aracı standarda göre ayarlar"]'::jsonb, '["Enlarges the instrument","Cleans the instrument","Paints the instrument","Sets the instrument against a standard"]'::jsonb, '["Takes the instrument apart into its components","Sterilizes the instrument after use","Replaces the instrument with a newer model","Sets the instrument against a standard"]'::jsonb),
    ('d93c7408-061a-411e-b728-a3bb57cd40fb'::uuid, 2, '["Uzun süre kaldırma","Hızlı kaldırma","Tek tekrarda kaldırılan en yüksek yük","Hafif yük"]'::jsonb, '["Yükü uzun süre taşıyabilme kapasitesi","Yükü en kısa sürede kaldırabilme hızı","Tek tekrarda kaldırılan en yüksek yük","Kasın birim sürede ürettiği güç miktarı"]'::jsonb, '["Lifting for a long time","Lifting quickly","The heaviest load lifted in one repetition","A light load"]'::jsonb, '["The capacity to carry a load for a long time","The speed of lifting a load in the shortest time","The heaviest load lifted in one repetition","The amount of power a muscle produces per unit of time"]'::jsonb),
    ('43d8fa78-15a8-43f0-adaa-e335127b88cd'::uuid, 3, '["Tek yapı","Sur sistemi","Saray bahçesi","Cami çevresinde yapılar bütünü"]'::jsonb, '["Tek bir kubbeli yapı","Şehir surları ve kapıları","Saray çevresinde bahçeler bütünü","Cami çevresinde yapılar bütünü"]'::jsonb, '["A single building","A system of walls","A palace garden","A complex of buildings around a mosque"]'::jsonb, '["A single domed building","A city''s walls and gates","A set of gardens around a palace","A complex of buildings around a mosque"]'::jsonb),
    ('3aa3afa3-4e13-420e-ae99-3a8177d6aa57'::uuid, 0, '["Farklı hava kütlelerinin karşılaşmasıyla","Yükseltiyle","Isınmayla yalnızca","Basınçla"]'::jsonb, '["Farklı hava kütlelerinin karşılaşmasıyla","Havanın dağ yamacında yükselmesiyle","Yerin aşırı ısınıp hava akımı oluşmasıyla","Havanın alçalıp sıkışarak ısınmasıyla"]'::jsonb, '["When different air masses meet","Through elevation","Through heating alone","Through pressure"]'::jsonb, '["When different air masses meet","When air rises up a mountain slope","When the ground overheats and creates updrafts","When air descends and warms by compression"]'::jsonb),
    ('1764f3b0-00ec-4110-ae54-f41d7107280e'::uuid, 0, '["Hızlı ve birleşik saldırı","Siper savunması","Kuşatma","Deniz ablukası"]'::jsonb, '["Hızlı ve birleşik saldırı","Uzun süreli siper savaşı","Gerilla pusu taktiği","Yıpratma savaşı"]'::jsonb, '["A rapid, combined assault","Trench defence","A siege","A naval blockade"]'::jsonb, '["A rapid, combined assault","Prolonged trench warfare","Guerrilla ambush tactics","A war of attrition"]'::jsonb),
    ('2c2d7823-84bd-4bc2-a197-779c682986be'::uuid, 1, '["Carpeaux","Bartholdi","Dalou","Falguière"]'::jsonb, '["Rodin","Bartholdi","Dalou","Falguière"]'::jsonb, '["Carpeaux","Bartholdi","Dalou","Falguière"]'::jsonb, '["Rodin","Bartholdi","Dalou","Falguière"]'::jsonb),
    ('3cedeb16-edbf-4b17-9afd-bc309298f118'::uuid, 3, '["Ahmet Ümit","Elif Şafak","Hakan Günday","Orhan Pamuk"]'::jsonb, '["Yaşar Kemal","Latife Tekin","Orhan Kemal","Orhan Pamuk"]'::jsonb, '["Ahmet Ümit","Elif Şafak","Hakan Günday","Orhan Pamuk"]'::jsonb, '["Yaşar Kemal","Latife Tekin","Orhan Kemal","Orhan Pamuk"]'::jsonb);

do $$
declare v_n int; v_beklenen int := (select count(*) from _j_sik);
begin
  -- Yalnız hâlâ eski şıkları taşıyan satırlar (araya başka düzeltme girdiyse dur)
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where q.secenekler = s.eski_tr and q.dogru_cevap = s.dogru;
  if v_n <> v_beklenen then
    raise exception 'Şık ipucu parti 5: % sorudan % tanesi beklenen eski hâlde', v_beklenen, v_n;
  end if;

  insert into public.soru_surum (question_id, surum, soru, secenekler, dogru_cevap, degisiklik_notu)
  select q.id, q.surum, q.soru, q.secenekler, q.dogru_cevap, 'Şık ipucu düzeltmesi parti 5: yanlış şıklar yeniden yazıldı (001)'
    from public.questions q join _j_sik s on s.id = q.id;

  update public.questions q
     set secenekler = s.yeni_tr,
         supheli_isaretler = array_remove(q.supheli_isaretler, 'sik_ipucu_jev'),
         surum = q.surum + 1
    from _j_sik s
   where q.id = s.id;

  update public.question_translations t
     set secenekler = s.yeni_en
    from _j_sik s
   where t.question_id = s.id and t.dil = 'en' and s.yeni_en is not null and t.secenekler = s.eski_en;
  get diagnostics v_n = row_count;
  if v_n <> (select count(*) from _j_sik where yeni_en is not null) then
    raise exception 'Şık ipucu parti 5: EN çeviri % satır güncellendi, beklenen %', v_n, (select count(*) from _j_sik where yeni_en is not null);
  end if;

  -- Sonuç: yazılanlarda sik_ipucu_jev kalmamalı, ağır kural işareti olmamalı
  select count(*) into v_n from public.questions q join _j_sik s on s.id = q.id
   where 'sik_ipucu_jev' = any(q.supheli_isaretler) or q.supheli_agirlik >= public.ayar_sayi('soru_rekabetci_haric_agirlik', 2);
  if v_n > 0 then
    raise exception 'Şık ipucu parti 5: % soruda işaret/ağırlık kaldı', v_n;
  end if;
end $$;

select set_config('app.soru_elle_isaret_yaz', '', true);
